### ISSUE TITLE
i18n for quoted email (and sig/disclaimer) folding 

### ISSUE THREAD

**Issue by sebbacon** [mysociety/alaveteli#104]
The [current code] (https://github.com/sebbacon/alaveteli/blob/master/app/models/incoming_message.rb#L577) for folding quoted emails uses various hard-coded English words like "disclaimer:" and "intended recipient" in regular expressions to try to match any standard disclaimers.

It also matches `^(On .+ (wrote|said):\n)` to find prefixes to quoted sections.

These bits of logic are obviously language-dependent, and should be factored out to a config file.

Perhaps the logic itself could lose some of the keywords, but we should obviously be very careful about any such changes :)

**Comment by garethrees** [comment]
Superseded by https://github.com/mysociety/alaveteli/issues/2662
