### ISSUE TITLE
Make administration guide more prominent on Alaveteli.org 

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/alaveteli#1076]
Currently the link to the administration manual occurs once in the http://www.alaveteli.org/getting-started-guide/ and is quite easy to miss. This doc will be useful for anyone running a site so we should make it more prominent!

**Comment by garethrees** [comment]
http://alaveteli.org/docs/running/ is linked from the main /docs/ page. We're also starting to include links to the relevant sections of the guide in inline help on the admin pages themselves.
