### ISSUE TITLE
change confusing wording in general.yml-example

### ISSUE THREAD

**Issue by mhl** [mysociety/alaveteli#1100]
I found this a bit difficult to parse:

```
# Comment out if you want this to be auto-generated.
# WARNING: this is slow & don't use production!
FRONTPAGE_PUBLICBODY_EXAMPLES: 'tgq'
```

I assume this means that if FRONTPAGE_PUBLICBODY_EXAMPLES is commented out, then it's very slow and that shouldn't be done for production, but it could be read either way...

**Comment by garethrees** [comment]
We've updated the wording on this since this issue was opened, and I think its better explained now.

https://github.com/mysociety/alaveteli/blob/develop/config/general.yml-example#L243-L258

Arguably we should just remove the functionality if we're saying not to use it though.
