### ISSUE TITLE
Make it easy to identify new potential volunteer administrators

### ISSUE THREAD

**Issue by henare** [mysociety/alaveteli#1107]
I've noticed a few enthusiastic users on our Alaveteli site helpfully making annotations on new requests. But now I can't remember who those users are and as an administrator I have no way of tracking them down and asking if they want to help being a site administrator.

I think the easiest way to solve this is to have a section in the admin backend that allows me to see users with the most annotations. Maybe just a sort field on the user page?

**Comment by henare** [comment]
>I think the easiest way to solve this is to have a section in the admin backend that allows me to see users with the most annotations.

Is there anything that would stop us putting this on the frontend instead of the backend?

**Comment by henare** [comment]
We were curious so ran this on Right To Know's console to find the top ten annotators:

```ruby
Comment.joins(:user).group(:user).order("count_all DESC").limit(10).count.each { |k,v| puts "#{k.name}: #{v}" }
```

**Comment by equivalentideas** [comment]
@henare and I have done a bit of a hack on this, which you can read about here https://github.com/openaustralia/righttoknow/issues/645 and see here:

![screen shot 2016-10-05 at 6 11 37 pm](https://cloud.githubusercontent.com/assets/1239550/19104332/9b266f98-8b27-11e6-9d74-cb555a765956.png)
![screen shot 2016-10-05 at 6 11 46 pm](https://cloud.githubusercontent.com/assets/1239550/19104331/9b261f8e-8b27-11e6-8104-984dc49b9e6c.png)

**Comment by garethrees** [comment]
👍 👍 👍 👍 👍

**Comment by garethrees** [comment]
Literally just arrived through my letterbox 10 minutes ago:

![img_4861](https://cloud.githubusercontent.com/assets/282788/19107419/01f2ecea-8ae4-11e6-8bb1-1f936050cb94.JPG)

Index page:

![img_4860](https://cloud.githubusercontent.com/assets/282788/19107429/0814aff0-8ae4-11e6-97ff-87cd7f89e4e9.JPG)

Great work 🍰 🍰

**Comment by Gemmamysoc** [comment]
Ooh, this is exciting! @RichardTaylor and @kingqueen3065 might be interested in this :)

**Comment by garethrees** [comment]
https://www.righttoknow.org.au/people
