### ISSUE TITLE
explore running Alavateli on JRuby

### ISSUE THREAD

**Issue by mhl** [mysociety/alaveteli#1157]
Many people report good performance results, particularly with regard to memory consumption, when running Rails sites on JRuby instead of MRI.  (The author of JRuby, Charles Nutter, even [suggested this for Alaveteli](http://www.mysociety.org/2009/09/17/whatdotheyknow-growing-pains-and-ruby-memory-leaks/#comment-1840).)  I guess the likely issue here would be any dependent gems that include native code.

@crowbot suggested that it would be worth allocating a day at some point to explore this.

**Comment by garethrees** [comment]
MRI Ruby is getting much more performance focused these days, so lets stick with that for now
