### ISSUE TITLE
Links to Wikipedia

### ISSUE THREAD

**Issue by confirmordeny** [mysociety/alaveteli#1171]
Add a feature whereby tagging an authority with wikipedia:[authority_page_name] would add a link on the site's authority page to Wikipedia' page for the authority.

e.g.

tag: wikipedia:HM_Treasury to link to
https://en.wikipedia.org/wiki/HM_Treasury

**Comment by garethrees** [comment]
Related to linking to wikidata entry by similar mechanism #6535

**Comment by confirmordeny** [comment]
Closed as not planned. Result can be achieved with changes to theme.
