### ISSUE TITLE
Admin 'internal discussion' area

### ISSUE THREAD

**Issue by abibroom** [mysociety/alaveteli#1172]
Idea that came up in discussion of mySociety's own intranet/wiki. The WDTK team have an area there which they use to log takedowns, record potentially controversial decisions/users/etc.  Plainly there should be _something_ within Alaveteli to support this requirement.

**Comment by garethrees** [comment]
Parts of this related to / could be implemented by https://github.com/mysociety/alaveteli/issues/5422
