### ISSUE TITLE
build a new alaveteli AMI without origin/install-script present

### ISSUE THREAD

**Issue by mhl** [mysociety/alaveteli#1259]
When I built the current Alaveteli AMI, the stale remote-tracking branch origin/install-script was still in the respository (it's deleted in the central repository). Unfortunately, the `site-specific-install` script will checkout `origin/install-script` in preference to `0.15` and `origin/master`. We should generate a new AMI where that's not the case and either run `git remote prune` before trying to checkout the commitish or remove the mention of `origin/install-script` completely. (I favour the latter, since it's been confusing in the past as well.)

**Comment by garethrees** [comment]
We're not really updating the AMI now, so closing
