### ISSUE TITLE
Additional contact fields for Public Bodies

### ISSUE THREAD

**Issue by j-norwood-young** [mysociety/alaveteli#1266]
I know changing database schemas is a schlep, but the following fields are important, especially in countries where an email address isn't guaranteed:
- Postal address
- Physical address
- Fax
- Telephone

These data would let us fall back gracefully to fax, then postal, and then escalate to phoning or visiting the office of the public body. It'd also be useful for the users to be able to reference these contact details, especially since the default Alaveteli help documentation advises phoning the authority to check if the information is available.

**Comment by garethrees** [comment]
We usually just use the `#notes` field for this, which works well enough.
