### ISSUE TITLE
acts_as_xapian: make xapianbs location configurable, and move on our servers

### ISSUE THREAD

**Issue by mhl** [mysociety/alaveteli#1292]
At the moment, the location of the xapian databases is hard-coded to be `lib/acts_as_xapian/xapiandbs`, which creates various problems. For example, it means that:
- The xapian databases have to be kept under the repository tree, which is awkward for deployments - for example, extra care (or manipulation of symlinks) would have to be done if deploying to one directory which is swapped into place by a symlink - I consider that this issue is blocking #1289
- That path is git-ignored, which means that in certain situations git may treat it as disposable, since the ignore mechanism is really intended for build products. This is potentially dangerous with something so important as the xapian database.

For example, on our systems, it would be better to have the databases at:

```
/var/www/some.host/xapiandbs/
```

... instead of:

```
/var/www/some.host/alaveteli/lib/acts_as_xapian/xapiandbs
```

(I think @crowbot said that this was something @dracos had suggested in the past.) To change this creates some issues, though:
- What's the right way of making the location of the xapian databases configurable, ideally still maintaining some separation of acts_as_xapian from Alaveteli's configuration system?
- How do we safely move the xapiandbs directory when the location is changed in the configuration? We automatically moved the xapian database with the last change of location, but that was only possible because the paths were completely predictable. I think if it's configurable, the xapiandbs directory would have to moved manually.

**Comment by garethrees** [comment]
When given a path starting `/`, `Rails.root.join` doesn't actually join it relative to `Rails.root`

```ruby
Rails.root.join('/foo').to_s
# => "/foo"

Rails.root.join('foo').to_s
# => "/home/vagrant/alaveteli/foo"
```

So, this issue is resolved.

> What's the right way of making the location of the xapian databases configurable, ideally still maintaining some separation of acts_as_xapian from Alaveteli's configuration system?

I think the current format of `config/xapian.yml` is good. It makes it an "edge case" customisation without adding complexity for installs where the defaults are fine.

> How do we safely move the xapiandbs directory when the location is changed in the configuration? We automatically moved the xapian database with the last change of location, but that was only possible because the paths were completely predictable. I think if it's configurable, the xapiandbs directory would have to moved manually.

I don't think we deal with this. If someone decides to change the path they should plan to manually move the existing database or rebuild from scratch.
