### ISSUE TITLE
investigate EC2-based performance problems for .mk 

### ISSUE THREAD

**Issue by mhl** [mysociety/alaveteli#1300]
The team in Macedonia are having problems getting good performance out of Alaveteli on EC2; my suggestion for things to try are, in this order:
- Switching to Rails' production mode
- Updating to our upcoming release, which adds caching of search results to several key pages on the site
- Setting up varnish as a caching reverse proxy

It would also be worth investigating whether the I/O performance of the EC2 instance is a bottleneck, given that pages that include xapian results seem to be particularly slow.

**Comment by garethrees** [comment]
we host them now
