### ISSUE TITLE
change deploy.rb to use shared file lists now in general.yml

### ISSUE THREAD

**Issue by mhl** [mysociety/alaveteli#1330]
With recent changes to the deploy process, we're now listing the files that should be shared on a given deployment in `general.yml` in `SHARED_FILES` and `SHARED_DIRECTORIES`. The `deploy.rb` used by Capistrano should now use these lists instead of that hardcoded in the script. Thanks to @crowbot for raising this.

**Comment by garethrees** [comment]
Closing in favour of https://github.com/mysociety/alaveteli/issues/7158
