### ISSUE TITLE
Add Twitter profile to Alaveteli user profile

### ISSUE THREAD

**Issue by henare** [mysociety/alaveteli#1339]
I think it's pretty common for people to put their Twitter details in their Alaveteli profile - it's even suggested in the help text on the edit profile page.

The other day I was thinking, "Why don't we add a field for your Twitter username so we can display your profile right there". But then I realised most people already have a Twitter link in their profile text so why not just automatically extract that and display the profile - magic!

**Comment by garethrees** [comment]
Going to close this because I think, while nice, isn't core to the purpose of Alaveteli. Twitter is popular now, but it probably won't be around forever, which means we'll have to clean it up down the line.
