### ISSUE TITLE
Incorrect entity escaping in plaintext notification emails

### ISSUE THREAD

**Issue by hsenag** [mysociety/alaveteli#1400]
Some characters from request titles (and perhaps bodies) appear to be being HTML entity escaped in outgoing plaintext notification emails. For example a user reported that an apostrophe was showing up as "&#x27;".

[Apologies as usual if this is a duplicate - I vaguely recall seeing something about this before but I've searched and can't find any relevant issue]

**Comment by RichardTaylor** [comment]
The footer of the email to the body containing a request appears to show a problem with the encoding of apostrophes. The below is from a message which was sent today via WhatDoTheyKnow.com : 

>`the wrong address for Freedom of Information requests to Doug&#x27;s Test Authority? If so, >please contact us using this form`

**Comment by RichardTaylor** [comment]
Today an email from the WhatDoTheyKnow system to the admin team prompted by submission of the add a new body form had a subject containing:

>Add authority - The Coroner&#x27;s Office,

**Comment by lizconlan** [comment]
@RichardTaylor argh, a real one! Thanks

**Comment by lizconlan** [comment]
Hmm, in theory Rails Magic&trade; should take care of this for us - https://github.com/rails/rails/pull/8235 (they even have [an apostrophe test](https://github.com/rails/rails/pull/8235/files#diff-4f1db8fb5c131c8d7cc582aac4e12103R86))

**Comment by lizconlan** [comment]
mmm... delicious red herring!

**Comment by RichardTaylor** [comment]
I used the request a new body form at:

https://www.whatdotheyknow.com/change_request/new

To suggest a body with the name: "Testing don't add"

The subject line of the email to the admin team was:

>Add authority - Testing don&#x27;t add

Clearly unimportant but as it's a bug I thought I'd note it.

**Comment by lizconlan** [comment]
I *think* this has been fixed but not deployed - doesn't appear to be in the wdtk branch

**Comment by lizconlan** [comment]
(for some value of "fixed")

**Comment by garethrees** [comment]
Check when WDTK is deployed

**Comment by garethrees** [comment]
@lizconlan ready for checking

**Comment by lizconlan** [comment]
looks ok - will reopen if the problem reoccurs
