### ISSUE TITLE
Make an easy way for admins to bulk update public bodies

### ISSUE THREAD

**Issue by henare** [mysociety/alaveteli#1415]
See also https://github.com/openaustralia/righttoknow/issues/321

**Comment by kat** [comment]
Hi sorry I didn't follow this conversation at the time. 

The process for updating authorities via CSV upload right now would be fine if there were some better user feedback on uploading. When I did a test upload, I got the feeling I had was of uploading into a black hole. System messages did not make clear what would be kept or deleted on upload. 

We're about to do some updates again on RightToKnow, so I'll work with @henare and @bfairless give this a go again. If it's still useful we'll report back here and clarify those improvements which would help make CSV upload more useable in its current form.

**Comment by garethrees** [comment]
Awesome! Cheers @kat :+1:

**Comment by kat** [comment]
I managed ok in that last epic upload once I recognised the difference between the error messages and other messages, so @henare please can you close this (until the next time) -thanks!
