### ISSUE TITLE
Emails from Mac Mail aren't parsed properly

### ISSUE THREAD

**Issue by benrfairless** [mysociety/alaveteli#1437]
See https://github.com/openaustralia/righttoknow/issues/327

When an email is sent from Mac Mail to a requestor, the email is not parsed correctly.

This is what the user sees:
![rtk view](https://cloud.githubusercontent.com/assets/6841582/2692806/03149826-c3a9-11e3-9896-d8fe27a1b8fe.png)

This is the raw email:
https://drive.google.com/file/d/0B6FvM3R1FeGaN1hQZUZwZGU0Zkk/edit?usp=sharing

**Comment by garethrees** [comment]
Going to close this as the main problem was fixed in https://github.com/mysociety/alaveteli/pull/1469. #1476 and #975 cover other cases.
