### ISSUE TITLE
On chrome browser pre-filled (remembered) fields on signin / signup page a little bit confused

### ISSUE THREAD

**Issue by benrfairless** [mysociety/alaveteli#1452]
Downstream issue: https://github.com/openaustralia/righttoknow/issues/47

It was indicated that this was addressed in #710 however is still happening (see below):

![chrome](https://cloud.githubusercontent.com/assets/6841582/2801416/f73c57f0-cc81-11e3-93e1-c9d502299eee.png)

**Comment by garethrees** [comment]
Is this still a problem I wonder? Going to close but happy to reopen if this still actually happens.
