### ISSUE TITLE
Consider banning signups from disposable email addresses

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#1473]
Problematic users on WhatDoTheyKnow sometimes have signed up via disposable email address services eg. 

https://grr.la/

We could create a list of such services and ban registration via them. 

There is though potentially a legitimate use for them with those who are whistleblowing or otherwise have good reasons to wish to hide their IDs; so this is something for consideration, for discussion. 

Anyone can create a new Gmail or similar address anyway to sign-up; these disposable email address services just make it easier. 

On WhatDoTheyKnow we sometimes ban users we can't contact (eg. due to using such addresses) when we have cause to get in touch about their abuse of our service.

**Comment by garethrees** [comment]
Rather than ban, we've added the ability to add domains to "suspicious" and "known spam" lists, which increase spam scores that flag these users up in our spam detection systems.

**Comment by FOIMonkey** [comment]
+1 Banned a user today who'd used a [24hr inbox service](https://shitmail.me/) to evade a previous ban. 

I think allowing signups from users using anonymous email services is fine, as it can help protect whistleblowers and helps users who feel that they have reason to use a pseudonym. I think we should ban signups from users using addresses that we know are only going to be active for 24hrs or less, as we can't contact these users, and it makes ban evasion pretty effortless.

**Comment by garethrees** [comment]
> I think we should ban signups from users using addresses that we know are only going to be active for 24hrs or less, as we can't contact these users, and it makes ban evasion pretty effortless.

We'll never win. These services are constantly cycling domains. There are probably open source lists, but I imagine these services are faster than a community-driven list can be updated. The only way to do this would be to whitelist major email providers (gmail, outlook, etc), but that would add barriers for anyone with their own domain (organisations, me!)

**Comment by FOIMonkey** [comment]
> We'll never win.

True, but we wouldn't need to catch every possible service on the planet to make an impact. Blocking ones that'd had recently been used for misuse would still help a little.
