### ISSUE TITLE
Remove material from caches as soon as it is hidden 

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#1475]
Regularly when administrators remove material from the site, and notify complainants, the complainants complain again saying the material is still visible to them, and it remains so for quite a few minutes. 

The issue can be a message still appearing to them on a request thread; or it can be an appearance in search results, or the "similar requests" side bar. 

Ideally when an administrator hides a request it ought be immediately removed from public view.

**Comment by MattK1234** [comment]
WDTK-team-priority tag added following discussion on the catch-up call 25/08/2020

**Comment by garethrees** [comment]
We don't think this is the 5-10 minute lag of Xapian search indexing – much more likely to be Varnish/browser cache related. A thing to investigate is whether some misconfiguration of Varnish has crept in over the years as its been upgraded, etc.

**Comment by RichardTaylor** [comment]
In the last week or so I've observed redactions / changes to have all taken place straight away. I've not recently seen caching to be an issue.

**Comment by RichardTaylor** [comment]
I've just done another redaction of request/response message text on WhatDoTheyKnow which was immediately effective for non-logged in users - this didn't used to happen - something has changed for the better.

**Comment by RichardTaylor** [comment]
This is of course still a regular issue for site admins on WhatDoTheyKnow.

**Comment by RichardTaylor** [comment]
Just to note that today I hit no issues with caching. A couple of times I checked a request page I'd just changed from the point of view of a non logged in user and it already reflected the change I'd just made.  

Perhaps neither I or anyone else had recently requested the page as a non-logged in user before I did to check material had gone?

**Comment by dracos** [comment]
https://github.com/mysociety/alaveteli/pull/7893 means there is now a `VARNISH_HOSTS` configuration option; if set (to hosts holding proxy caches, e.g. load balancers), it will use background jobs to send relevant PURGE or BAN requests to each of the hosts listed at appropriate times. If those hosts are then set up to action such requests (following e.g. https://varnish-cache.org/docs/trunk/users-guide/purging.html ), their cache entries will be invalidated.

**Comment by garethrees** [comment]
Considering closed via https://github.com/mysociety/alaveteli/pull/7893. Can open new tickets for issues that doesn't resolve.
