### ISSUE TITLE
Redesign request pages

### ISSUE THREAD

**Issue by TomSteinberg** [mysociety/alaveteli#1523]
This means the template of a page like this:
https://www.whatdotheyknow.com/request/school_cluster_groups_57

**Comment by garethrees** [comment]
https://www.foiamachine.org/requests/3263/

**Comment by RichardTaylor** [comment]
Users on WhatDoTheyKnow are still on occasion missing the "write a reply" link and sending messages intended for public bodies to the WhatDoTheyKnow team via the contact form instead.  The numbers involved are not large. Three in the first 10 days of March 2016, and about three in February 2016.

**Comment by garethrees** [comment]
Closing this as its too broad
