### ISSUE TITLE
Viewing this attachment as HTML is broken

### ISSUE THREAD

**Issue by TomSteinberg** [mysociety/alaveteli#1527]
https://www.whatdotheyknow.com/request/registered_pharmacists_prescribi#incoming-245446

@hsenag taken from #18

**Comment by RichardTaylor** [comment]
Here's another example where "view as HTML" doesn't currently work:

https://www.whatdotheyknow.com/request/travelling_and_subsistence_expen#incoming-854417

**Comment by garethrees** [comment]
Closing as it just seems to be poor parsing – not errors. Can't do much about this specific case really.
