### ISSUE TITLE
Holding pen misses

### ISSUE THREAD

**Issue by hsenag** [mysociety/alaveteli#162]
I'm seeing a pattern emerging where a leading angle bracket in the to line, e.g.

To: <Paul Grimshaw <request-81543-7a700ad4@whatdotheyknow.com>

https://www.whatdotheyknow.com/admin/raw_emails/205194

causes the message to hit the holding pen.

**Comment by RichardTaylor** [comment]
Holding pen miss due perhaps to an unusual use of ' and " in the To: line at https://www.whatdotheyknow.com/admin/raw_emails/794992 

>To: "'request-nnnnn-xxxxxxxxx@whatdotheyknow.com'"
	<request-nnnnnn-xxxxxxxxx@whatdotheyknow.com>

Also in this case the correct address was present in the To: line so presumably the system should have been able to "guess" where it was supposed to go? RE: #109 "Improve guessing heuristics for holding pen emails "

**Comment by RichardTaylor** [comment]
I've been looking at the legitimate messages ending up in the holding pen and many are still errors in the secret hash part of the address indicating manual transcription is taking place and people are missing a character. 

It's getting complex but can we not do an exact match on the hash - in other words allow messages though if the hash is say one character out?

I'd have thought it only worth doing something like that if we could move towards not having to administer the holding pen.

What about an automated email to the sender when they got the address wrong, to say we've spotted the error but they should use the new address in the future, or [as has been suggested before](https://github.com/mysociety/alaveteli/issues/15#issuecomment-1263702), remembering the error and delivering future messages accordingly.

**Comment by RichardTaylor** [comment]
We've just had one on WhatDoTheyKnow where the public body switched a 6 to a b in the hash

**Comment by RichardTaylor** [comment]
Two real messages in the holding pen on WhatDoTheyKnow today:
1. One digit omitted from the end of the request ID part of the email address. 
2. Some characters omitted from the end of the secret hash part.

On WhatDoTheyKnow we had just these two real messages in the holding pen in about a week and about sixty spam messages. 

Just providing an update on the state of things.

**Comment by RichardTaylor** [comment]
We've had what looks like a further case of the leading angle bracket problem described in the initial comment on this ticket at:

https://www.whatdotheyknow.com/request/local_authority_collected_waste_2#incoming-1245414

(which I redirected from the holding pen)

I don't think we routinely look at why a request is in the holding pen, we just redirect it so I have no idea how common this issue is. 

Fewer messages in the holding pen reduces admin work - and means users get their responses quicker. 

cc @sagepe

**Comment by garethrees** [comment]
Interesting. Looks like we're breaking some behaviour of the `Mail` library:

```ruby
# $ bin/rails c
# Loading development environment (Rails 4.2.10)
Mail.read('./tmp/leading_angle_bracket_in_to.email').to
# => nil
Mail::VERSION.version
# => "2.6.6"
```

But when I try loading the same email with just the mail library, we don't get a `nil` `To` attribute:

```ruby
# $ bundle console
Mail.read('/tmp/leading_angle_bracket_in_to.email').to
# => "<Bob Smith <bob@localhost>"
Mail::VERSION.version
# => "2.6.6"
```

We're explicitly returning `nil` for invalid addresses to mirror some old behaviour:

https://github.com/mysociety/alaveteli/blob/ed73db7f823d7b08e356cc8538645ab6b1d85ed1/lib/mail_handler/backends/mail_backend.rb#L9-L26

We could possibly match this specific case in `clean_addresses`…

```ruby
old_result.slice!(0) if old_result =~ /\A<.*<.*@.*>/

# Example:
old_result = '<Bob Smith <bob@localhost>'
# => "<Bob Smith <bob@localhost>"
old_result.slice!(0)
# => "<"
old_result
# => "Bob Smith <bob@localhost>"
```

…but we'd have to figure out how to re-parse the valid address in to an `AddressContainer`.

**Comment by RichardTaylor** [comment]
I've been having looking to see the causes of messages ending up in the holding pen. Missing the first digit from the secret hash part has been the reason in a couple of cases.  As suggested previously 

>allow messages though if the hash is say one character out

would have meant these didn't need manual intervention.
