### ISSUE TITLE
Changes to final screen once a new request is complete

### ISSUE THREAD

**Issue by wrightmartin** [mysociety/alaveteli#1682]
Part of #1526

More sharing, better cross-selling

- [x] Extract "You've just made a request" stuff to a partial (#2078)
- [x] Link up elements here (https://github.com/mysociety/alaveteli/pull/2147#discussion_r24252160)
- [x] Implement sharing
- [x] Replace $authority_name$ with actual authority name in sidebar

![screen shot 2014-07-03 at 15 30 42](https://cloud.githubusercontent.com/assets/2292925/3470915/a142ead0-02be-11e4-99e5-6c7186ef2c51.png)

**Comment by garethrees** [comment]
Oops PR closed this, but PR only covered the code bits

**Comment by wrightmartin** [comment]
![screen shot 2015-01-15 at 15 39 25](https://cloud.githubusercontent.com/assets/2292925/5760469/b68607ee-9ccc-11e4-87df-fc37c32445a1.png)

Here's what it looks like implemented

**Comment by garethrees** [comment]
Definite improvement!

I think we have lost a bit of the boldness of the green flash message though. Could you add a screenshot with a bit more vertical (both up and down) context so we can see how it flows from the  header and in to the request?

**Comment by wrightmartin** [comment]
@garethrees 

![screen shot 2015-01-15 at 16 21 49](https://cloud.githubusercontent.com/assets/2292925/5761331/a6170cd6-9cd2-11e4-8025-d904a09aada9.png)

**Comment by garethrees** [comment]
Yeah, I think it needs to be more obvious that its some sort of (large) alert and unique to the action the user has just taken. As a starting point, maybe render it within `<div id="notice>"` to reintroduce the (very) green notice box and add `class=".subtle"` to mute the colours?

**Comment by wrightmartin** [comment]
![screen shot 2015-01-16 at 11 51 41](https://cloud.githubusercontent.com/assets/2292925/5775748/2d381f18-9d76-11e4-8efe-ee656bcd541c.png)

Yes, that looks better, thanks @garethrees

**Comment by garethrees** [comment]
Yeah that definitely stands out more! Do you think it feels okay at full size while going through the request process? I'm totally open to not putting it in a giant green box if you have other ideas.

Also I notice in the "What's Next" box there's "View other requests to **$authority_name$** – assuming that's something you'd like us to do?

**Comment by garethrees** [comment]
Any coding bits, could you add to the to-do list at the top of the ticket? Cheers.

**Comment by garethrees** [comment]
Fixed in https://github.com/mysociety/alaveteli/pull/2147
