### ISSUE TITLE
Corrupt mail file stopped update-xapian-index running

### ISSUE THREAD

**Issue by Flupsy** [mysociety/alaveteli#1719]
The `update-xapian-index` job was failing over the weekend due to a corrupt mail file (`/data/vhost/www.whatdotheyknow.com/raw_emails/217/217302/540916`).  The associated request (https://www.whatdotheyknow.com/request/post_review_correspondence_2) was also generating an error when retrieved.

I've moved the file to `~foi/217302/540916` and replaced it with an empty one; the job and request are no longer generating errors.

**Comment by garethrees** [comment]
Haven't seen this for ages, so closing.
