### ISSUE TITLE
Truncate list of alternative users shown on user profiles

### ISSUE THREAD

**Issue by samsmith** [mysociety/alaveteli#1732]
![screen shot 2014-07-29 at 15 40 21](https://cloud.githubusercontent.com/assets/365140/3736491/55afa048-172e-11e4-8c88-48f477b9699f.png)

The "more than one person has this name" list, may want to become "one of these x other accounts" for names like: https://www.whatdotheyknow.com/user/s_smith_2/profile 

That list is becoming unusably wieldy as no one can tell the difference between them (which is probably only doable by seeing the last few requests that were asked/successful)

**Comment by garethrees** [comment]
Related to https://github.com/mysociety/alaveteli/issues/2406
