### ISSUE TITLE
Ability to minimise administrative messages on threads

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#1749]
This is a feature suggestion to allow users and administrators to "minimise" certain messages on a correspondence thread. 

The way it could work:
- Responses which the system knows are just an acknowledgement (following classification) are not shown in full; but are reduced to one line high with an "expand" arrow; and are labelled "acknowledgement".  
- There could be an option to mark other responses eg. "sorry your response is delayed" or "out of office" for minimisation in a similar way. 

This is all about just tidying up and simplifying the appearance of the request thread. 

I don't think this is an important feature at all; I'm noting as we occasionally get requests from users to tidy up the appearance of their correspondence threads in this way.

This could be a good contender for part of an escalating privileges system #229

**Comment by RichardTaylor** [comment]
This could be used where there are error messages on a thread too eg. imagine if the initial error response at:

https://www.whatdotheyknow.com/request/gp_direct_access_pathology_price_14#incoming-868504

could be collapsed - either by an admin or the requestor or a trusted user. 

#748 is related and suggests collapsing auto-responses.

**Comment by RichardTaylor** [comment]
So we now have the ability to minimise messages by clicking a "-" button in the top left of the message (see #4085)  but as I understand it minimisation doesn't persist and there's no way to make it persist. 

Enabling a requester or admin to make a message appear collapsed by default is the next step to achieving what was envisaged here. 

Automatic collapsing (maybe not if it's the latest message on the thread) would be an enhancement. 

[This note prompted by WhatDoTheyKnow user writing: "each time I respond to XXX County Council an automated email is sent back which confuses the web page]

**Comment by RichardTaylor** [comment]
Automatically collapsing delivery failed messages once a re-send has occurred after them is an idea. This might help prevent the reporting of delivery failures even in cases where a re-send has already taken place. See also #6709

**Comment by HelenWDTK** [comment]
+1 We had user support come in reporting a delivery error where the request had subsequently been delivered and acknowledged. Minimising  the response could have helped prevent this.

**Comment by garethrees** [comment]
This is desirable, but unlikely to be worked on in the next 12 months so closing for now.
