### ISSUE TITLE
Provide Myf with bare-bones instructions to work up into a blog post

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/alaveteli#1772]
I'm writing a series of 'walk through' blog posts across all our sites. There's just [one live at the moment](https://www.mysociety.org/2014/07/23/want-to-know-what-your-mp-is-saying-subscribe-to-a-theyworkforyou-alert/), but several more in draft.

They're not intended to replace documentation (and in some cases they will link to it) - they are really designed to be search-engine material that will help channel people towards the projects.

If someone could provide me with a basic list of actions for setting up an Alaveteli site, I will write the post, hopefully so that the man in the street can follow it.

**Comment by garethrees** [comment]
Looks like this turned in to https://www.mysociety.org/2014/08/15/how-to-make-a-freedom-of-information-request-with-whatdotheyknow/
