### ISSUE TITLE
Allow requestors to opt not to have their name shown publicly

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#1776]
Having to give their name, and having their name published, might put some users off making a request via an Alaveteli site. 

We could allow users to opt out of having their user-name displayed on the site on a per request, or per user-account, basis.

The users' name could still be submitted to the authority and an attempt made to redact the name where it is present in any responses.

A risk with offering this feature would be the inability to promise any redaction of responses will be effective. However some users simply wishing to reduce the ease with which their requests can be found by Google may appreciate such a feature.

Related to #444 (Admin option to disassociate request from user) in that this is a suggestion that a user could effectively be given the ability to preemptively dissociate a request from their name/account).

See also:
https://www.whatdotheyknow.com/help/privacy#real_name

This suggestion arose when I read a walk-through of WhatDoTheyKnow by @MyfanwyNixon which advised users not wanting their names made public not to use WhatDoTheyKnow and I thought we should consider serving those requestors too.

Other related ideas:
- Alaveteli could more actively support anonymous requests (where the public body doesn't see a user's name either). Such requests would be technically invalid in the UK; however the ICO's guidance is they ought be responded to.
-  Alaveteli could more actively support pseudonymous requests.

**Comment by garethrees** [comment]
Kinda related to #3074

**Comment by garethrees** [comment]
Going to close this as I don't think we're ever realistically going to do this. The options I see are:

* Use your real name
* Use a company or organisation name
* Use a pseudonym, with the possibility that you won't be able to appeal
* Get someone else to request for you

**Comment by RichardTaylor** [comment]
I agree with keeping this closed, however a council has just effectively said, in discussion with the WhatDoTheyKnow support team, that the lack of this feature is one reason why they don't feel they can point all their requesters to WhatDoTheyKnow. 

As noted above if we did send a users' name privately to a public body dealing with responses would still be challenging as responses contain users' names in all sorts of variations and formats, including sometimes in images of response letters which we're unlikely to ever be able to programmatically deal with.  

With a co-operative public body though there might be some chance of this working - if they understood not to mention a requesters' name which was sent to them privately in a response. 

I think it's something to think about as we consider why we're not serving everyone who wants to make a FOI (or similar) request.

**Comment by schlos** [comment]
I tend to agree with Richard. At leas from Croatia perspective, I think people would initiate more requests if they would know that their name will not be publicly exposed. I had encounters with people which do not want their real name appearing in Google searches...

Real name is required to make valid request in Croatia, so in any case, we should send "real name", but allowing users to register with nickname and having separate field for real name not publicly exposed would be nice to have.

**Comment by WilliamWDTK** [comment]
Just to note that a user has suggested that requesters should be able to submit requests, while retaining online anonymity. I believe that FragDenStaat (sp.?) offers this ability, and MaDada makes usernames less obvious (i.e. names online where signed in the body of the request).
