### ISSUE TITLE
Encourage users to find new email addresses for bodies themselves in case of errors/bounces

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#1782]
When users mark a response for our attention we give them a free text box to explain the problem. 

If the issue is the email address for the authority needs updating we should point them to the update authority form.

https://www.whatdotheyknow.com/change_request/new?body=bens_test_authority

We should encourage users to research a new address for themselves - eg. stressing the site is administered by volunteers and they can help us by finding the address and saying if they provide the address we might be able to re-send their request quicker too.

**Comment by garethrees** [comment]
Could also include this where we show a failed delivery status.
