### ISSUE TITLE
"Cite this" page button

### ISSUE THREAD

**Issue by confirmordeny** [mysociety/alaveteli#1823]
WhatDoTheyKnow contains thousands of documents many of which are not available elsewhere online. Researchers may want to cite these in papers. We should make this as easy as possible.

http://en.wikipedia.org/w/index.php?title=Special:Cite&page=Neutron&id=623346964

**Comment by garethrees** [comment]
Nice pattern for this on [The Journal of Design and Science](https://jods.mitpress.mit.edu/pub/ageofentanglement/release/1):

![Screenshot 2021-01-13 at 11 51 58](https://user-images.githubusercontent.com/282788/104449001-d95a6480-5595-11eb-925b-8f30eb1b0820.png)


![Screenshot 2021-01-13 at 11 52 21](https://user-images.githubusercontent.com/282788/104448993-d5c6dd80-5595-11eb-8a27-914260eb06d0.png)

**Comment by gbp** [comment]
Github has recently added a button like this: https://github.blog/2021-08-19-enhanced-support-citations-github/

**Comment by garethrees** [comment]
Nice clear "How to cite" section of this [journal article](https://www.thecommonsjournal.org/article/10.18352/ijc.325/).

![Screenshot 2022-04-19 at 13 12 19](https://user-images.githubusercontent.com/282788/164001539-3d37fe59-5966-408d-951a-9594f1f93f09.png)

**Comment by WilliamWDTK** [comment]
A perhaps useful tool for citations could be [citation.js](https://citation.js.org/) (I believe it's client-side).  There's a [demo on the website](https://citation.js.org/demo/).  We would have to come up with appropriate mappings for each field.  It can parse [BibJSON](http://okfnlabs.org/bibjson/) through a plug-in.

There's also an [article from the ALA](https://www.ala.org/tools/article/ala-techsource/%E2%80%9Ccitethis%E2%80%9D-building-javascript-bookmarklet-creates-citations-sharing-web) ([archived version](https://archive.ph/VkvDt)) on a similar topic.

**Comment by WilliamWDTK** [comment]
I also started wondering whether mySociety or Alaveteli could assign DOIs (Digital Object Identifiers), since I'd imagine they'd potentially be applicable to some of the output.  It seems like you have to pay, but I'd noted down the following links:

- [https://datacite.org/feemodel.html](https://datacite.org/feemodel.html)
- [https://www.medra.org/en/guide.htm](https://www.medra.org/en/guide.htm)
- [https://www.doi.org/](https://www.doi.org/)

**Comment by WilliamWDTK** [comment]
We could also use the citation generation page/box/whatever to encourage adding a citation from the Alavateli platform concerned (e.g. WDTK) to the work citing the request.  Attempting to make a circle of citation, of sorts.

**Comment by WilliamWDTK** [comment]
And I'm not sure whether it's worth separating (or even considering) the suggestion I had of facilitating Re-use of Public Sector Information requests by those other than the original requester.  Or whether people should just make their own FOI requests…

**Comment by garethrees** [comment]
Nice [example](https://data.ubdc.ac.uk/dataset/sensor-enhanced-housing-survey-data-for-urban-heat-investigation) of "cite this" for datasets:

![Screenshot 2024-03-05 at 09 54 44](https://github.com/mysociety/alaveteli/assets/282788/cd7724f5-5cf5-419a-9cb8-a14b70feb8c5)

**Comment by garethrees** [comment]
This is desirable, but unlikely to be worked on in the next 12 months so closing for now.
