### ISSUE TITLE
Set up Alaveteli for Isle of Man

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/alaveteli#1829]
By October - waiting for clarification on

- [ ] Colour Scheme
- [ ] Logo
- [ ] Bodies

Site name will be askmann.org and domain has already been purchased. Include Facebook and Twitter logos or links if possible.

Facebook: www.facebook.com/groups/AskMann/
twitter: realaskmann

**Comment by abimysoc** [comment]
Drive-by "happened to see this ticket while looking for something else: ooh that's really out of date isn't it" closure.
