### ISSUE TITLE
Enable a user to add an annotation to all, or a set of, their requests

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#1878]
This feature has been requested by a WhatDoTheyKnow user wanting to easily link to the results of their research from all the requests they used to collect their data.

Some related discussion about #34 

This feels like something which might be usefully connected to batch requests; eg. easily enabling an annotation to be made which is shown on all requests in a batch.

**Comment by RichardTaylor** [comment]
This feature could have been used to annotate the recent "Local authority pension fund investment" requests at

https://www.whatdotheyknow.com/user/rob_davies_2

to what appears to be collated data from the responses and an article at

https://www.theguardian.com/uk-news/2019/jan/10/uk-councils-invest-566m-in-arms-firms-implicated-in-saudis-yemen-campaign

h/t @Gemmamysoc for spotting.

**Comment by RichardTaylor** [comment]
If users were able to draft an annotation explaining the purpose of their set of requests prior to making them that could be used in moderation decisions.  In some cases the existence of such an annotation could be a pre-condition of making certain sets of requests (either via large batches as pro, or sets of requests made via the free service, with the rate cap removed).

**Comment by garethrees** [comment]
Closing in favour of basically the same issue at https://github.com/mysociety/alaveteli/issues/6768.
