### ISSUE TITLE
Add documentation on generating admin/stats graphs

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#1906]
We should probably do https://github.com/mysociety/alaveteli/issues/675 first, but we should add notes about how to generate these graphs on http://alaveteli.org/docs/installing/next_steps/

**Comment by lizconlan** [comment]
(changed "fix" to "do" in the initial comment to prevent waffle treating this a PR)

**Comment by lizconlan** [comment]
(#675 now closed)

**Comment by garethrees** [comment]
Generating the graphs is now done in Ruby and uses Rails' database connection, so no additional config is required. The graphs also only start to get generated when there's enough data, so we don't need to worry about turning them on.
