### ISSUE TITLE
Google docs viewer bandwith limit errors

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#1907]
Sometimes when clicking the "view has HTML" option an error is shown stating:

> You’ve reached the bandwidth limit for viewing or downloading files that aren’t in Google Docs format. Please try again later. You can also try to download the original document by clicking here.

This appears to be a per-user issue rather than one related to Alaveteli sites given the way @Google publishes bandwidth limits https://support.google.com/a/answer/1071518?hl=en

It could just be a Google Docs/Viewer bug.

This is something I've experienced a fair amount while using WhatDoTheyKnow; and today a user drew it to our attention too. 

Could consider
- Reporting this issue to Google in some way
- Looking at other options for online viewers
- Updating this thread with any future reports of problems

**Comment by garethrees** [comment]
Haven't seen this for ages, so closing until it comes up again.
