### ISSUE TITLE
Add "similar authorities" to /body/:id

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#1996]
Part of #1526

I guess just make a search for the body's full name and take the top 3.

![screen shot 2014-11-24 at 11 18 38](https://cloud.githubusercontent.com/assets/282788/5164159/04677990-73cc-11e4-8e3c-aedd072c4bf9.png)

**Comment by wrightmartin** [comment]
I've removed this from the designs, hopefully we haven't spent any serious time on it as of yet

**Comment by garethrees** [comment]
For reference, we're going to do "Add logic to show authority page to decide if we've just come from a search (#2051)" instead.
