### ISSUE TITLE
Unable to re-withdraw requests

### ISSUE THREAD

**Issue by sebbacon** [mysociety/alaveteli#2]
I had a request marked "withdrawn", which the public body then responded to; as a normal user my options for categorising didn't let me put it back in the status of "withdrawn".

**Comment by HelenWDTK** [comment]
I have just tested this and it is no longer an issue. Sending a new message to a request that had been marked as withdrawn left the status as withdrawn. I still had the option to set the status to something else using the update the status of this request link in the actions menu.
