### ISSUE TITLE
Prevent Censor Rules defined in a theme being destroyed

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#2010]
Currently we don't allow global censor rules to be created through the admin UI, so we could catch that in the controller:

``` ruby
def destroy
  if @censor_rule.global?
    redirect_to admin_dashboard_path, :error => "Can't do that"
  # ...
end
```

[Some](https://github.com/mysociety/derechoapreguntar-theme/blob/master/lib/model_patches.rb#L38-L49) themes create censor rules for an associated record automatically. We could either introduce a `:lock => true` attribute which cannot be set through the admin UI, or we could just allow these to be destroyed. The latter would give admins more control in the event that a particular rule was causing issues.

**Comment by schlos** [comment]
+1

**Comment by garethrees** [comment]
We now allow global censor rules to be managed through the admin UI https://github.com/mysociety/alaveteli/pull/3021 so closing.
