### ISSUE TITLE
Ask Africa - Create PDF Form Submission

### ISSUE THREAD

**Issue by paullenz** [mysociety/alaveteli#2014]
For the Ask Africa site enable the user submission form to populate a submission which is then send as a PDF.  The required structure for the PDF, with editable fields is:

YELLOW - this should remain untouched
BLUE - the requester will manually enter this
RED - these are the selection options for the different manual entries by requesters where we give them a dropdown/exhaustive list of selections
GREEN - is automatically entered by askAFRICA itself. So, when they select their department the details will go in the first green section. In the final green section, the date will be automatically entered and their name simply repeated in print. 

Reference files are here:  https://drive.google.com/a/mysociety.org/?tab=mo#folders/0BykwTlYr1B-_UEUySUM3b05JXzg (PAIA form A word doc and PAIA 750 PDF)

**Comment by garethrees** [comment]
This will likely need a background job queue (#1240)
