### ISSUE TITLE
Code changes required for Authority page redesign

### ISSUE THREAD

**Issue by wrightmartin** [mysociety/alaveteli#2032]
- [x] Separate RSS feed link from 'follow' button 

``` <%= render :partial => 'track/tracking_links', :locals => { :track_thing => @track_thing, :own_request => false, :location => 'sidebar' } %>```

- [x] Separate Search fields from filter links 

``` <%= render :partial => 'request/request_filter_form' %> ```

**Comment by garethrees** [comment]
Pasting the image for reference

![](https://cloud.githubusercontent.com/assets/2292925/5199615/eabb88f2-7555-11e4-9e01-9f6922a84dde.png)

**Comment by garethrees** [comment]
See notes in #2032 for how to use the partials individually.

**Comment by wrightmartin** [comment]
@garethrees can you let me know how to get just the RSS link? I can't quite work it out from the partial

**Comment by garethrees** [comment]
Sorry I got the ticket number wrong above, so didn't link through to the notes. I've updated now.

```erb
<%= render :partial => 'track/rss_feed', :locals => { :track_thing => @track_thing, :location => 'main' }
```

You'll want to use a `:location` option appropriate to where you're putting it. I think it supports `'main'` and `'sidebar'`.
