### ISSUE TITLE
document how to demonstrate that a request was accepted by mail servers

### ISSUE THREAD

**Issue by davewhiteland** [mysociety/alaveteli#2057]
how outgoing mail log extracts are visible on the admin page for a request and can be used to demonstrate to the authority that the request email was accepted by their mail servers for delivery [from @crowbot ]

Broken out from #1075

**Comment by garethrees** [comment]
Alaveteli now just shows this to users https://www.mysociety.org/2016/07/29/the-small-symbol-that-tells-you-all-is-well/
