### ISSUE TITLE
Document flagging non-request addresses as being ones which get spam

### ISSUE THREAD

**Issue by davewhiteland** [mysociety/alaveteli#2064]
Document the ability to flag non-request addresses as being ones which get spam and so prevent them appearing in the holding pen #1409

Broken out from #1075

**Comment by garethrees** [comment]
Would it be better to spend the time here improving the UI with a "Mark as Spam" button as demonstrated in https://github.com/mysociety/alaveteli/pull/1409#issuecomment-38913533?

**Comment by davewhiteland** [comment]
Closed by #2120
