### ISSUE TITLE
add another example response to "adding a set of bodies"

### ISSUE THREAD

**Issue by davewhiteland** [mysociety/alaveteli#2070]
Add example to existing responses: Replying to someone asking us to add a set of bodies and suggesting they try and find their email addresses (perhaps crowd-sourcing it via a public Google spreadsheet) to ease the burden on the core team of volunteers.

Broken out from #1075

**Comment by garethrees** [comment]
Fixed in https://github.com/mysociety/whatdotheyknow-theme/commit/13dab27a71777bd794851c62d843d53dfd5494a4
