### ISSUE TITLE
How awesome can we make the WhatDoTheyKnow homepage?

### ISSUE THREAD

**Issue by zarino** [mysociety/alaveteli#2075]
The homepage of whatdotheyknow.com is one of the most visible pages in mySociety’s roster, with roughly 50,000 pageviews a month.

@wrightmartin had some spare time months ago and drafted up a pie-in-the-sky vision of what the homepage could look like if we were to bring it into the 2010s, and I know @TomSteinberg is keen to see something happen to the homepage soon.

So we don't run into this with our eyes closed, how about a **kick-off discussion at the Oxford team meeting this Wednesday/Thursday?**

I'm keen to actually get to the bottom of what *works* and *doesn't work* on the current page, and who it should be targeting – much as we did with the [TheyWorkForYou homepage redesign](https://github.com/mysociety/theyworkforyou/issues/589).

CCing @paullenz @MyfanwyNixon @davewhiteland since they're in Oxford this week and their contributions would be much valued, and also @crowbot and @garethrees who aren't there but can hopefully contribute insider WDTK knowledge.

**Comment by garethrees** [comment]
Dup of https://github.com/mysociety/alaveteli/issues/1525 – I've moved this to that ticket.

**Comment by zarino** [comment]
Cheers @garethrees :+1:

**Comment by paullenz** [comment]
+1 that we should do this - Thursday?

Ooo - that reminds me of another thing I want to suggest

**Comment by garethrees** [comment]
We have two calls on Thursday: Rwanda at 10:00 and Nicaragua at 15:00.

Might be able to squeeze it in, depending on how those calls go.
