### ISSUE TITLE
document the use of tags on authorities

### ISSUE THREAD

**Issue by davewhiteland** [mysociety/alaveteli#2086]
They're useful for allowing specific searches, and matching to categories. But there are also at least four tags which are hardwired with magic.

Possibly this can be largely covered by a glossary entry, and links to it where needed. 

   * `defunct` and `not_apply` 
   * `site_administration` won't be included in CSV downloads
   * `eir_only` (UK only) instead of saying FOI in reference to the request, we say EIR

Example of some magic happening here based on tag value:
https://github.com/mysociety/alaveteli/blob/rails-3-develop/app/models/public_body.rb#L217

Noticed when documenting the CSV upload feature (in the admin guide), which talks about using tags without really explaining what they are for.

(thanks to @crowbot for clarifying some of this)

**Comment by garethrees** [comment]
I think `charity` does too

**Comment by tmtmtmtm** [comment]
There's also some magic on `school` in relation to due dates.

**Comment by davewhiteland** [comment]
Closed by #2117 I believe
