### ISSUE TITLE
Provide a way to say that an authority doesn't have a homepage

### ISSUE THREAD

**Issue by hsenag** [mysociety/alaveteli#2091]
At present if you leave the "Home page" link blank, then alaveteli guesses a URL based on the email domain. For small authorities without their own domain this is usually wrong, e.g. https://www.whatdotheyknow.com/body/clifford_road_primary_school_ipswich currently links to http://www.hotmail.co.uk

We could put something invalid instead but it'd be better to have an explicit value to disable the link completely. On the other hand I don't remember ever getting a support request from a user confused by it, so it's probably low priority.

**Comment by garethrees** [comment]
Related to #6434 which covers the calculated homepage problem, but we should also have a way of saying _no_ homepage.

**Comment by garethrees** [comment]
Might be resolved by a better implementation of https://github.com/mysociety/alaveteli/issues/6434#issuecomment-1036466019

**Comment by RichardTaylor** [comment]
+1 

When listing Local Family Justice Boards many of the contact email addresses don't have domains corresponding to websites for the boards, and many of the boards don't have a home page to link to. 

https://www.whatdotheyknow.com/body/list/lfjb

Had I been able to add a special tag eg .no_calculated_homepage to prevent home pages being calculated I'd have done so in many cases.
