### ISSUE TITLE
Rate-limit undeliverable response notifications

### ISSUE THREAD

**Issue by Flupsy** [mysociety/alaveteli#2096]
Spammers sometimes target old request addresses, and we generate a `Your response to an FOI request was not delivered` message for each one.  If the `From:` address is not valid, these will sit in the outbound mail queue.

It would be nice if we could rate-limit these responses, or (for example) only send one per sender address per request.

**Comment by sagepe** [comment]
Having done a quick review I think this ticket is obsolete - the list of closed request addresses is used by Exim at the `RCPT` ACL to deny messages during the `SMTP` transaction and these changes post-date this ticket. I think you can close it.
