### ISSUE TITLE
Make it more obvious that preview responses are preview only

### ISSUE THREAD

**Issue by annapowellsmith** [mysociety/alaveteli#2116]
A couple of weeks ago I was asked to clarify https://www.whatdotheyknow.com/request/monthly_figures_for_jsa_claimant

I clicked on the link and wrote a message and _thought_ I had submitted it, but then got another message from WDTK asking me to clarify, and when I went back, I saw the message hadn't been submitted. 

I guess that first time around, I got as far as the "preview your message" page and thought that had been submitted. 

Could it be it even more obvious that the message hasn't been submitted yet? Maybe it needs an exclamation mark icon and "Your message hasn't been sent yet!", or something like that.

**Comment by garethrees** [comment]
We're working on an improved request process design (#1526), which should make this a little clearer.

Sorry about the confusion :pensive:

**Comment by garethrees** [comment]
https://github.com/mysociety/alaveteli/issues/1526 has been live for a while now, and I think we've only had one more report of this since, so I think its better now than it was when this issue was opened.
