### ISSUE TITLE
Missing AWS AMI for “Basic Alaveteli installation 2014-12-05” (ami-699c1b1e)

### ISSUE THREAD

**Issue by leowmjw** [mysociety/alaveteli#2123]
Error received:

"We cannot proceed with your requested configuration. You cannot use this AMI (ami-699c1b1e).
This AMI has been deregistered, or you do not have permission to use it. Try again with another AMI for which you have permissions, or request permission to use this AMI from its owner."

**Comment by garethrees** [comment]
The instance was still set to "Private" visibility. I've made it public now. Sorry about that, and thanks for the bug report!
