### ISSUE TITLE
Create a "I Need Help" Button for tricky requests

### ISSUE THREAD

**Issue by brfairless** [mysociety/alaveteli#2155]
Create a "I Need Help" status which could allow:
- the ability for the request to be posted to twitter/facebook with a "help" message
- a page where people can see what requests need help, and offer that help to them
-- ensure that this page has the ability for people to subscribe to requests that need help.

I could see it working this way:
1 - Requester changes status to "I need Help!". They can provide details on what help they need.
2 - People who are interested can see a list of requests which need help (and subscribe to it)
3 - People who are able to provide help could do so by annotations.
4 - When the requestor has replied to the authority, the status is changed and is then removed from the new list (in step 2).

I'm afraid I'm not really a hardcore developer, so I'm interested to see if other Alaveteli sites would find this useful.

**Comment by garethrees** [comment]
Hey @brfairless,

I've had a look through the related issues in openaustralia/righttoknow but I'm not that clear on what type of help people are asking for. It looks like "I've been asked to pay" and "I've been refused". In what way does the community provide help?

It would be worth posting this to https://groups.google.com/forum/#!forum/alaveteli-users to see if other Alaveteli's have had similar thoughts.

Cheers!

**Comment by skenaja** [comment]
Something similar to this feature was logged in #75

**Comment by brfairless** [comment]
I would say that #75 is the same as what I want, except that I want the ability to start the "expert help" process while a request is ongoing.
