### ISSUE TITLE
Prevent Banned users from editing their "About Me"

### ISSUE THREAD

**Issue by brfairless** [mysociety/alaveteli#2160]
Right to Know had a recent spate of users creating profiles with spam in the "About Me" section of the site (https://github.com/openaustralia/righttoknow/issues/394)

We either need a new category of user ("Spam Account") or to stop banned users from updating their "About Me" as suspending the users have no effect (they can just re-add their spam).

**Comment by garethrees** [comment]
@brfairless we've fixed this in #2170 and it should be available in the next release. Thanks for reporting :beers:
