### ISSUE TITLE
Requestors should be able to see own correspondence uncensored

### ISSUE THREAD

**Issue by sebbacon** [mysociety/alaveteli#218]
Let requesters view the uncensored versions of their own correspondence (e.g. with
emails in it). 

Perhaps easy thing to do is just to do it for email addresses (and not the request email address)

**Comment by RichardTaylor** [comment]
>Perhaps easy thing to do is just to do it for email addresses (and not the request email address)

Ticket #10 is the more specific version of this ticket applying to just email addresses.
