### ISSUE TITLE
Public body request count includes hidden requests

### ISSUE THREAD

**Issue by equivalentideas** [mysociety/alaveteli#2215]
The page https://www.righttoknow.org.au/body/aged_care_commissioner displays that there is:

> 1 Freedom of Information request to Aged Care Commissioner

but then doesn't display it:

![screen shot 2015-03-04 at 2 30 24 pm](https://cloud.githubusercontent.com/assets/1239550/6477729/0cea0a08-c27b-11e4-9aad-598f44779fa8.png)

There is one hidden request.

The count of requests on the public body page should not include hidden requests.

**Comment by lizconlan** [comment]
This was fixed in [release 0.22](https://github.com/mysociety/alaveteli/releases/tag/0.22.0.0)
