### ISSUE TITLE
Start alaveteli service automatically in AMI

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#2252]
When I create a new EC2 instance from an Alaveteli AMI
I should be able to `curl -I $INSTANCE_PUBLIC_HOSTNAME` and receive a 200 response

**Comment by garethrees** [comment]
We've documented that you need to manually start the service (https://github.com/mysociety/alaveteli/issues/1892)

**Comment by samsmith** [comment]
it would also be useful that the default configuration didn't break whenever the EC2 hostname changed (such as being turned off for a few days)

**Comment by garethrees** [comment]
@samsmith could you go in to a bit more detail about what breakages you're experiencing, as we're not heavy AWS users here. Cheers :)

**Comment by samsmith** [comment]
1. start an EC2 instance.
2. stop it.
3. go play with a horse for a couple of hours.
4. start it again.
5. load the front page URL: you get an nginx gateway error.

> On 28 May 02015, at 09:29, Gareth Rees <notifications@github.com> wrote:
> 
> @samsmith could you go in to a bit more detail about what breakages you're experiencing, as we're not heavy AWS users here. Cheers :)
> 
> —
> Reply to this email directly or view it on GitHub.
> 

--  
@smithsam

**Comment by garethrees** [comment]
Ah, I expect you'll have to start the alaveteli service manually in between step 4 and 5. Could you confirm whether it works after doing that? If so, then its the same issue (Alaveteli just needs to get added to `rc.d` – `sudo update-rc.d alaveteli defaults` by the looks of it)

For clarity:

1. start an EC2 instance.
2. stop it.
3. go play with a horse for a couple of hours.
4. start it again.
5. start alaveteli service (`sudo service alaveteli start`)
6. load the front page URL

**Comment by samsmith** [comment]
> On 28 May 02015, at 10:16, Gareth Rees <notifications@github.com> wrote:
> 
> Ah, I expect you'll have to start the alaveteli service manually in between step 4 and 5. Could you confirm whether it works after doing that? If so, then its the same issue (Alaveteli just needs to get added to rc.d – sudo update-rc.d alaveteli defaults by the looks of it)

it sounds like that the command there is different to the steps below.

I’ll test it the next time my image gets shutdown for a while

> For clarity:
> 
> 	• start an EC2 instance.
> 	• stop it.
> 	• go play with a horse for a couple of hours.
> 	• start it again.
> 	• start alaveteli service (sudo service alaveteli start)
> 	• load the front page URL
> —
> Reply to this email directly or view it on GitHub.
> 

--  
@smithsam

**Comment by garethrees** [comment]
> it sounds like that the command there is different to the steps below.

Yes, this is (I think) the solution to making the service start on boot/reboot.

I'm interested in checking that your error report is just because we're lacking the autostart, or whether there's an issue with a hostname change.

> I’ll test it the next time my image gets shutdown for a while

Cheers

**Comment by garethrees** [comment]
We don't really support the AMI anymore.
