### ISSUE TITLE
Implement escalating privileges system

### ISSUE THREAD

**Issue by sebbacon** [mysociety/alaveteli#229]
A full discussion is on the wiki: https://github.com/mysociety/alaveteli/wiki/Escalating-privileges-system

**Comment by schlos** [comment]
+1
also I've mentioned that in this comment: https://github.com/mysociety/alaveteli/issues/3147#issuecomment-210144927

I meant restriction for new users to post links (usually spam, as requests really don't need links to be posted) in their first 3 requests. It's like tier or user level seen on Discourse:
https://meta.discourse.org/t/what-do-user-trust-levels-do/4924/2

It's like smart way giving users more and more rights if they prove to be "trustworthy".

Now, I'm going offtopic, but something like
Level 0 - allow max 3 requests per day (configurable number), don't allow links
Level 1 - upgrade after min 3 days on site and sent min 3 requests (numbers are configurable), can add links
Level 2 - upgrade after X numbers of sent foi requests, allow same as Level 1 + allow batch sending
etc... (the more you use it correctly, more rights you get).

**Comment by RichardTaylor** [comment]
An ex-volunteer has written to WhatDoTheyKnow to say that while the don't want to be a full admin 

>A more limited set of permissions would be helpful (e.g the ability to add new authorities and to hide problematic requests) but I don't think that is possible.

This is someone who we would be happy to give the limited permissions they suggest, if we could. 

There would be connected issues though I suspect such as communication with such non-core volunteers if there were questions about their actions for example. We'd want more internal and external transparency over admin actions to, so we can all see what's being done, and peer-review each other's work (#1198).

**Comment by HelenWDTK** [comment]
+1 The absence of this feature makes it significantly harder to bring new volunteers on to the team.

**Comment by garethrees** [comment]
This is desirable, but unlikely to be worked on in the next 12 months so closing for now.
