### ISSUE TITLE
Categorising and threading FOI requests

### ISSUE THREAD

**Issue by mattmill30** [mysociety/alaveteli#2295]
To reduce clutter in search results, display formats of threaded, categorised and chronological views should be introduced, requiring a feature to be developed for assigning FOI requests to publically maintained threads and categories.

The feature could be included as an additional task of the 'Things to do with this request Anyone:' list of /request/ pages.

This would enhance the /body/ and /list/ UIs:

/body/<authority>:- (except /body/list/)
views include:
- threaded;
- categorised;
  defaults to threaded view, with category icons.

when a thread is clicked-on, the FOI requests of that thread for the authority are listed  at /body/<authority>/thread/<thread>/.

/body/<authority>/thread/ would list all threads for the authority.

when a category is clicked-on, the FOI requests within that category for the authority are listed at /body/<authority>/category/<category>/, with threads icons.

/body/<authority>/category would list all categorises with FOI requests for the authority.

"list all FOIs" would reference /list/?query=requested_from:ofcom.

/body/<authority>/thread/:
lists all threads for the authority.

where ?query= is parsed, list threads containing FOI requests once filtered to the selection criteria.

/body/<authority>/thread/<thread>/:
lists all FOI requests associated with a particular thread.

where ?query= is parsed, highlight relevant FOI requests within the list of all FOI requests of the particular thread.

incorporates the same {/,successful,unsuccessful,awaiting} request status family structure as /body/<authority>/ and /list/.

/body/<authority>/category/:
lists all categories of the authority.

where ?query= is parsed, list categories containing FOI requests once filtered to the selection criteria.

/body/<authority>/category/<category>/:
lists all threads of the particular category of an authority.

where ?query= is parsed, list threads of the particular category, which contain FOI requests once filtered to the selection criteria.

incorporates the same {/,successful,unsuccessful,awaiting} request status family structure as /body/<authority>/ and /list/.

/list/:
views include:
- cronological;
- threaded;
- categorised.
  default is a chronological listing of all FOI requests, with thread icons.

when an FOI is clicked, it loads as usual.

when a thread is clicked-on, the FOI requests of that thread for the particular authority are listed  at /body/<authority>/thread/<thread>.

when 'threaded' is clicked-on, the threads for each authority are listed at /list/threads?query=.

when 'categorised' is clicked-on, the filtered categories of each authority are listed at /list/categories/?query=.

(it would also be useful to include an 'Advanced search' button within the list page).

/list/categories/:
lists all categories associated with FOI requests; if ?query is parsed, filter the categories according to the criteria.

When a category is clicked-on, all authorities which have FOI requests accociated with the filter category are listed at /list/categories/<category>/?query=.

/list/categories/<category>/:
lists all authorities which have FOI requests accociated with the chosen category; with a 'threads' icon for each.

when an authority is clicked-on, the FOI requests for the authority of the chosen category are listed at /body/<authority>/category/<category>; if ?query= was parsed, suffix onto the URL.

when a 'threads' icon is clicked-on, the threads of the particular authority are listed at /body/<authority>/thread/; if ?query= was parsed, suffix onto the URL.

From a users perspective (without knowledge of the database schema), the following CSV gives an example of the new dataset for results to the query "requested_from:ofcom":

Authority,Request,Thread,Category
Ofcom,101 Single Non-Emergency Number - Ofcom research,101 telephone service,Research
Ofcom,Acquisition of O2 by Three,O2 acquisition,Regulatory
Ofcom,Retention policy of Ofcom's email servers,E-mail retention,Policy
Ofcom,Unlicenced radio stations in Yorkshire,Pirate radio countermeasures,Operations
Ofcom,Unlicensed Radio Bristol and West of England 2013 to 2015,Pirate radio countermeasures,Operations
Ofcom,Unlicensed Radio Wales 2007 to 2015,Pirate radio countermeasures,Operations
Ofcom,I originally made this request to the ASA who have referred me to you where I have copied my original request,Broadcast competitions,Regulatory
Ofcom,List of licencees of the Amateur Radio Call book data under Re-use of Public Sector Information Regulations 2000,Amateur radio callsign licencees,Data
Ofcom,Out of sequence amateur radio callsigns,Amateur radio callsign records,Data
Ofcom,"The Most Recent 30 Closed Cases of interference to ""Hobby Radio"" (or Amateur Radio)",Amateur radio interference not cured,Data
Ofcom,'Related' Freedom of information request to the one witf 'your ref':UNKNOWN,FOI mishandling,Complaints
Ofcom,Broadcasting signals,Broadcasting obligations,Legislation

**Comment by garethrees** [comment]
Thanks for this suggestion, but I'm going to close this as its unlikely we'll implement it any time soon. I think we'd need to find a way of not relying on human categorisation, as its tricky enough to get all requests classified in lots of installs. We'll keep this in mind when we're making other improvements to search though.
