### ISSUE TITLE
Announce alaveteli.org/es

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#2306]
- [x] Mailing lists
- [x] Twitter
- [x] Team Nicaragua
- [x] IRC topics

**Comment by JenMysoc** [comment]
I can tweet about it! was on my list of things to do anyway for international twitter.

**Comment by garethrees** [comment]
> I can tweet about it! was on my list of things to do anyway for international twitter.

Go for it! :+1:

**Comment by garethrees** [comment]
Done! https://groups.google.com/forum/#!topic/alaveteli-dev/tm36o06CUlE
