### ISSUE TITLE
Add in caveat to http://alaveteli.org/es/community/ that most of our comms is in english

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/alaveteli#2336]
I think we should clearly state that the mailing lists are predominantly english and if anyone needs technical assistance it should be asked for there in English

We can say I think that they can write to International@ in Spanish because that's fine with me (providing no one else minds, I can always translate) 

This is on the http://alaveteli.org/es/community/ page of the documentation site

**Comment by garethrees** [comment]
Closing this as we haven't updated the Spanish translations since they were added. #removespanish
