### ISSUE TITLE
Requests marked as "Successful" or "Refused" shouldn't be prompted if further emails

### ISSUE THREAD

**Issue by benrfairless** [mysociety/alaveteli#2342]
When a request is marked with an "end state" (such as Successful/Refused/No Information Found) and someone replies with a "Thanks" email, any replies are prompted to clarify the status of the request.

When requests have reached their end game, they should remain in their current status no matter what emails are received (Including, potentially, surveys).

**Comment by hsenag** [comment]
Sometimes a previously refused request might receive extra information outside the normal workflow, e.g. after a complaint to the regulator. I tend to agree that "successful" should normally be terminal. 

FWIW the user can always override explicitly even if we don't ask them to classify but many don't realise this - the "update the status of this request" isn't particularly obvious.
