### ISSUE TITLE
Extend information we hold about public bodies

### ISSUE THREAD

**Issue by sebbacon** [mysociety/alaveteli#237]
Maybe gather this data by letting authorities input it (see issue #41)

Description for each body as to what info it holds
Link to:
Company number
Aliases (not just short name, but multiple real names e.g. for museums)
Disclosure logs
Publication schemes (http://www.ico.gov.uk/what_we_cover/freedom_of_information/publication_schemes.aspx)
TWFY department search
Complaint email
Phone number for advice and assistence (House of Lords give one http://www.parliament.uk/parliamentary_publications_and_archives/freedom_of_information_in_the_house_of_lords/lords__foi___how_to_obtain_information.cfm )
e.g.
http://www.ordnancesurvey.co.uk/oswebsite/aboutus/foi/index.html
http://www.ordnancesurvey.co.uk/oswebsite/aboutus/foi/coiindex.html

**Comment by RichardTaylor** [comment]
>Maybe gather this data by letting authorities input it

The footer of outgoing messages could be used to ask public bodies to let us know if we can improve their listing on WhatDoTheyKnow. 

Ideally we'd give them a form for structured submission of proposed changes.
