### ISSUE TITLE
Allow search for requests made to a tagged set of public authorities

### ISSUE THREAD

**Issue by skenaja** [mysociety/alaveteli#24]
The tag search function only returns records with variety:authority.  You should be able to search for requests made to a set of authorities that have a specified tag, allowing alerts or a feed to be set up for requests made to bodies in your local area.  eg:

http://www.whatdotheyknow.com/search/tag:islington%20variety:sent

**Comment by RichardTaylor** [comment]
A request from a WhatDoTheyKnow user

>Is there any way to restrict a request search to requests made to authorities tagged in a certain way?
>e.g. for all requests made to authorities tagged “police” that contain “RIPA” in the last year
>I assumed this might work “ tag:police RIPA 01/01/2014.. “ but it does not.

Related #1179 (Search generally poor)

**Comment by henare** [comment]
This would be really helpful for Right To Know because it would allow you to search for all requests in a particular jurisdiction, e.g. all requests to NSW public authorities.
