### ISSUE TITLE
Don't render "There is more than one person who uses this site" on your profile page

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#2406]
Confusing when you're on your own profile page:

![screen shot 2015-05-05 at 09 57 49](https://cloud.githubusercontent.com/assets/282788/7469604/8dd260c6-f30d-11e4-864e-01a34362fb47.png)

**Comment by garethrees** [comment]
Related to https://github.com/mysociety/alaveteli/issues/1732

**Comment by mdeuk** [comment]
A WhatDoTheyKnow user has got in touch:

> There's a message at the top of the screen that says "There is more than one person who uses this site and has this name. One of them is shown below, you may mean a different one: xyxyyxyx".
> 
> I suspect I might have clicks on that... leading me to see an unfamiliar list of requests and believe I was able to access another account.
> 
> Just a suggestion... once I've logged in... you can remove that message. I know which xyxyxyz I am :)

We've provided reassurance that this isn't a security issue; however, it is certainly a usability goof.

It's a particular problem for users with a very common name (say for example, John Smith). In the example shown we render a listing of nearly all users with the same name before showing the user's own profile, which results in a very large "wall of text".

<img width="1061" alt="image" src="https://user-images.githubusercontent.com/249418/83357840-d4c6a000-a366-11ea-8b93-c8edad74d813.png">

**Comment by garethrees** [comment]
Yeah, I think we should just get rid of this.
