### ISSUE TITLE
Allow non-work days to be specified by country specific rules

### ISSUE THREAD

**Issue by petterreinholdtsen** [mysociety/alaveteli#2420]
At the moment, non-work days need to be specified per year, by specifying the dates that are non-work days.  This is not easy to maintain, as it need to be repeated every year.  It would be better if it instead
allowed us to specify the rules to generate the non-work days and allow the system to calculate the dates
on its own.  A system to do that is implemented in plan, http://www.bitrot.de/plan.html , where the
definition for Norway look like this:

:
: Norwegian holiday file. Copy to ~/.holiday for private changes or tip
: geiri@stud.cs.uit.no if things are missing.
:
weekend "1. Nyttårsdag" weekend on 1.1
black "2. Nyttårsdag" on 2.1
black "Morsdag" on second sunday in february
weekend "Søn. før faste" weekend on easter minus 49
blue "Sommertid" on last sunday in march
weekend "Skjærtorsdag" weekend on easter minus 3
weekend "Langfredag" weekend on easter minus 2
black "Påskeaften" on easter minus 1
weekend "1. Påskedag" weekend on easter
weekend "2. Påskedag" weekend on easter plus 1
black "Pinseaften" on easter plus 48 days
weekend "1. Pinsedag" weekend on easter plus 49 days
weekend "2. Pinsedag" weekend on easter plus 50 days
weekend "Kristi Him.f.dag" weekend on easter plus 39 days
weekend "Off. høytidsdag" weekend on 1.5
weekend "Grunnlovsdag" weekend on 17.5
black "St. Hans" on 23.6
blue "Vintertid" on last sunday in september
weekend "Bots & bededag" on last sunday in october
black "Farsdag" on second sunday in november
black "1. Advent" on sunday before 23.12 minus 21 days
black "2. Advent" on sunday before 23.12 minus 14 days
black "3. Advent" on sunday before 23.12 minus 7 days
black "4. Advent" on sunday before 23.12
black "Julaften" on 24.12
weekend "1. Juledag" weekend on 25.12
weekend "2. Juledag" weekend on 26.12
black "Nyttårsaften" on 31.12 

It handle both fixed and relative days, and provide the correct list of non-work days every year.

**Comment by gorm** [comment]
I don't think this is really an issue. You can load for 50 years if you want on install. using Holiday in the admin tab.

**Comment by petterreinholdtsen** [comment]
[Gorm]
> I don't think this is really an issue. You can load for 50 years if
> you want on install. using Holiday in the admin tab.

The point I am trying to make is that the current approach is far from
optimal.  It would be better if it was possible to specify how to
generate the holiday dates every year instead of having to generate them
outside Alaveteli and load them into Alaveteli regularly.  As you can
see from the provided examples, the rules are not very complex, as long
as a few key moving dates like easter are generated automatically by
Alaveteli.
-- 
Happy hacking
Petter Reinholdtsen

**Comment by garethrees** [comment]
There's now an iCal feed importer – hopefully this makes life a bit easier!
