### ISSUE TITLE
Add link to Slack chat somewhere

### ISSUE THREAD

**Issue by henare** [mysociety/alaveteli#2458]
And how to ask for access.

**Comment by garethrees** [comment]
The [community page](http://alaveteli.org/community/) currently contains all the contact/interaction mechanisums. Its in the [gh-pages branch](https://github.com/mysociety/alaveteli/blob/gh-pages/community/index.md) of this repo.

What do you need to do to ask for access?

I'm kinda put off by Slack being a closed platform, yet another comms tool (we have mysociety#alaveteli and freenode#alaveteli, and the mailing lists) and needing to ask to join is not ideal.

**Comment by garethrees** [comment]
Although, it does seem like its got a few more people than the IRC channels :+1:

**Comment by henare** [comment]
@garethrees I agree with all your points, positive and negative.

**Comment by henare** [comment]
I'd say that Slack didn't really take off for Alaveteli so I'm closing this.
