### ISSUE TITLE
Create learning materials for trainee journalists

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/alaveteli#2503]
In the UK, we have been occasionally visiting colleges and talking to trainee journalists about how they can use WDTK (and other mySociety websites). However, this kind of outreach is inefficient - it takes quite a bit of effort and only reaches a very small number of students.

Could we provide materials ([as we do for school children](https://www.mysociety.org/lesson-plans/)) which journalism colleges could download and use? These could be created as a template so that each country could drop in their own examples and links.

**Comment by MyfanwyNixon** [comment]
Further thoughts about this - some of our partners set up as part of a journalism organisation (Hungary and maybe Ukraine? And we also have friends at MuckRock) so they might be best placed to offer advice to budding journalists.

**Comment by garethrees** [comment]
Perhaps we could initiate a Q&A via the [mailing list](https://groups.google.com/forum/#!forum/alaveteli-users)?

We could submit the types of questions asked and hopefully get some advice from the groups mentioned. Then when someone asks we could just send them to the mailing list threads and prompt them to ask there?

**Comment by garethrees** [comment]
Just came across http://www.foiman.com/foi-man-training/foi-media-masterclass

**Comment by garethrees** [comment]
http://www.foiman.com/resources/foiguide1

**Comment by Gemmamysoc** [comment]
+1 OpenAustralia guys were interested in this when we caught up with them

**Comment by MyfanwyNixon** [comment]
Closing this ticket, given that anything we do of this sort will presumably now be around AP.
