### ISSUE TITLE
Google Docs Viewer unreliable - HTML view of XLS files often failing

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#2511]
Often when viewing an Excel (XLS) file via the "view as HTML" link I get the WhatDoTheyKnow header but nothing below it where the content from Google Docs Viewer ought be. 

The problem appears intermittent in that while it generally doesn't work, on occasion it does.  Trying to view the same document will sometimes work, and sometimes not - this isn't an issue about specific documents not being viewable. 

Perhaps this is some kind of bandwidth limiting as described #1907 (though then we had an explanatory error message).   It could be users hitting some kind of limit; or the limit could be related to display of documents from WhatDoTheyKnow.  The issue remains if I'm logged into Google or not. 

Consider:
- Not offering "view as HTML" for filetypes we rely on Google Viewer for as it's unreliable and makes users think there's something wrong with WhatDoTheyKnow
- Use another service for displaying XLS files ( #266 mentions Zoho https://sheet.zoho.com/excelviewer )

It appears Google Docs viewer might no longer be an officially offered Google service. 

![docs-viewer-notok](https://cloud.githubusercontent.com/assets/547695/7901936/54218dfc-0799-11e5-9478-c83cf3e884de.jpg)
![docsviewer-ok](https://cloud.githubusercontent.com/assets/547695/7901935/5420f73e-0799-11e5-8edd-cfb2e7cee7c1.jpg)

**Comment by WilliamWDTK** [comment]
A user has reported this problem, saying:
>Sometimes it works perfectly but then other times it refuses to load documents.

**Comment by garethrees** [comment]
This is desirable, but unlikely to be worked on in the next 12 months so closing for now.
