### ISSUE TITLE
WhatDoTheyKnow thinks I am in America

### ISSUE THREAD

**Issue by kingqueen3065** [mysociety/alaveteli#2520]
For some reason, WhatDoTheyKnow keeps thinking I am in America. See for example: http://puu.sh/iaOlx/1919e89f39.png

I use two ISPs; Plusnet and Wanstor - the latter provides Internet access throughout the care home in which I live. WhatIsMyIP.com has both as being in London.

Not a problem that affects my use of the site, just an interesting bug I guess.

**Comment by Flupsy** [comment]
Might need to upgrade the geoip database.

**Comment by Flupsy** [comment]
Am following up directly.

**Comment by Flupsy** [comment]
Can't reproduce this now.

I've upgraded the geoip database on the gaze servers (was `20130213`, now `20150209`).  Hopefully that will make this go away.
