### ISSUE TITLE
add documentation on marketing/site-promotion

### ISSUE THREAD

**Issue by davewhiteland** [mysociety/alaveteli#2536]
Currently we barely mention site promotion (marketing is step 6: http://alaveteli.org/docs/getting_started/#step-6 ) but we know (esp. from AlaveteliCon) that it's important there's lots that can be done here. See https://www.mysociety.org/2015/06/02/ten-ways-to-promote-alaveteli-sites/ -- this could be consolidated into the docs, probably a page of its own although I've added "admin guide" label in case that's how it sits.
- [x] in the interim Dave will add a link to that post from the docs in step 6)

**Comment by TomSteinberg** [comment]
Suggestion from Alavetelicon - provide a list of FOI requests from different countries that have generated high levels of traffic. Ideally the top 5 trafficked questions from 10 different sites, would be marvellous.

**Comment by TomSteinberg** [comment]
You could also mention cross-selling campaigns from the request funnel completion page (the 'Golden Page') but that probably isn't trivial for someone to change.
