### ISSUE TITLE
Upgrade Xapian

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#2540]
> The latest stable version is 1.2.21, released on 2015-05-20.
>
> http://xapian.org/

https://github.com/mysociety/xapian-full currently bundles `1.2.9`

**Comment by garethrees** [comment]
cc/ @Flupsy

**Comment by Flupsy** [comment]
I've pushed a branch `debian-jessie` to the xapian-full repo and tested it successfully on a jessie machine.  Not sure what to do next or how to push it to rubygems.  Probably needs an eye cast over it to make sure I've done the right things so far.

**Comment by garethrees** [comment]
I'll mark this ticket for review so @crowbot or I will take a look in to it.
