### ISSUE TITLE
Fresh deploy fails when using sysvinit-passenger.ugly

### ISSUE THREAD

**Issue by Flupsy** [mysociety/alaveteli#2577]
Doing a fresh deploy when using `sysvinit-passenger.ugly` fails with

```
Stopping Alaveteli app server: cp: cannot stat `/data/vhost/liberia.alaveteli.org/alaveteli/public/down.default.html': No such file or directory
```

Deploying with that line commented out on `vhosts.pl`, then redeploying with it uncommented, works fine.

**Comment by garethrees** [comment]
Don't think I've seen this for a while, and I've definitely deployed at least one fresh Alaveteli since this so closing until it comes up again.
