### ISSUE TITLE
Requests that need status updates

### ISSUE THREAD

**Issue by ircer** [mysociety/alaveteli#2596]
I was browsing through WDTN earlier and noticed that on some requests the site asked me to read the request and select the best explanation of the current status, which I did a couple of times. I was wondering, is it possible to use some search term to just get a list of these requests that need reading etc.?

**Comment by garethrees** [comment]
You can play the [categorisation game](https://www.whatdotheyknow.com/categorise/play), which presents you with old unclassified requests that you go through and classify. There's no [advanced search](https://www.whatdotheyknow.com/advancedsearch) option for filtering by requests awaiting classification. Hope that helps :racehorse:
