### ISSUE TITLE
Get list of public body email addresses for research

### ISSUE THREAD

**Issue by Rebeccarumbul** [mysociety/alaveteli#2605]
Please help! I need foi email addresses for the authorities in this list: https://docs.google.com/spreadsheets/d/1mdYXePGf_Nd97fEasYxMuviRKuaxy9XuZ5vKvSP-pgA/edit#gid=0

**Comment by garethrees** [comment]
Where did the names come from in the Authority column of the spreadsheet? Where they taken directly from WTDK or have you written them? (This makes a difference from making it easy to find them in the database)

**Comment by Rebeccarumbul** [comment]
They are from wdtk

Dr Rebecca Rumbul
Head of Research
mySociety

**Comment by garethrees** [comment]
I wrote a quick script to do this:

```ruby
$file = ARGV[0]

unless $file
  puts 'Path to file required'
  exit 1
end

def extract_email(name)
  name = name.chomp
  search = PublicBody.where(:name => name)
  search_size = search.size

  if search_size == 0
    data = { :input_name => name,
             :found_name => 'could not find this body',
             :request_email => 'NOT_FOUND' }
  end

  if search_size == 1
    body = search.first
    data = { :input_name => name,
             :found_name => body.name,
             :request_email => (body.request_email or 'NOT_FOUND') }

  end

  if search_size > 1
    data = { :input_name => name,
             :found_name => "Found multiple bodies: #{ search.all.map(&:name) }",
             :request_email => 'NOT_FOUND' }
  end

  data
end

collected_data = []

File.readlines($file).each do |line|
  next if line.blank?
  collected_data << extract_email(line)
end

puts "input_name,found_name,request_email"
collected_data.each do |data|
  puts %Q("#{data[:input_name]}","#{data[:found_name]}",#{data[:request_email]})
end
```

It plucks each line from the input file and looks up that name:

```
The Geraldine Quango
Department of Loneliness
Ministry of Sensible Walks
```

You can run it with `bundle exec rails runner /path/to/script.rb /path/to/names.txt`

It failed to find 48 of the authorities given in @Rebeccarumbul's spreadsheet.

I've emailed the results to @Rebeccarumbul and suggested the bodies that couldn't be found are looked up manually – probably some typos in the authority names.
