### ISSUE TITLE
Unexpected message deletion after clicking "redeliver to another request" button

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#2620]
Clicking on the "redeliver to another request" button on an incoming message admin page without anything in the form field next to it results in the message in question being deleted without trace (no reference to the deletion in the timeline or the request admin page). 

I think it's important to fix this because the presence of this bug means administrators can too easily accidentally delete material

I suggest the button should do nothing when there's nothing in the form field.

**Comment by garethrees** [comment]
Really sorry about this. A re-user experienced this recently so this is a dup of https://github.com/mysociety/alaveteli/issues/2558. I'll have a look at restoring the email.
