### ISSUE TITLE
.docx are always corrupted in "Download a zip file of all correspondence"

### ISSUE THREAD

**Issue by kingqueen3065** [mysociety/alaveteli#2623]
I initially spotted this error on a request that constituted a data breach. I've found another example, but it's not as clear. 
On this request https://www.whatdotheyknow.com/request/hr_payroll_and_bacs_software_con_121 if you directly download this .docx https://www.whatdotheyknow.com/request/276775/response/674073/attach/3/242%202015.docx all is fine.
However if you select "Download a zip file of all correspondence" https://www.whatdotheyknow.com/request/hr_payroll_and_bacs_software_con_121/download then the same .docx in the zip file is corrupted. 
The same happens with my test .docx on my test authority: https://www.whatdotheyknow.com/request/test_25
I have done some experimentation and this problem does not occur with any other attachment type I have tried, including .doc.
![ss 2015-07-02 at 06 51 38](https://cloud.githubusercontent.com/assets/11923618/8483831/6f3164d0-20eb-11e5-8f7f-3071aabb875b.png)

**Comment by garethrees** [comment]
Wonder if this got fixed by https://github.com/mysociety/alaveteli/pull/4224 as a similar issue to https://github.com/mysociety/alaveteli/issues/4161?

**Comment by HelenWDTK** [comment]
We have fixed this at some point
