### ISSUE TITLE
Make rar file attachments browseable

### ISSUE THREAD

**Issue by petterreinholdtsen** [mysociety/alaveteli#2647]
This is similar to issue #211 but for rar files instead of zip files.  The Norwegian version of
Alaveteli got a rar file as the reply from the government in &lt;URL: https://mimesbronn.no/request/innsyn_i_konkuranseutlysningen_a#incoming-4 &gt;, and its content is neither indexed nor browsable using the web pages.

**Comment by garethrees** [comment]
Going to close this as I don't think we're likely to focus on this.

On WDTK, only 0.0006% of our attachments are RAR.

```sql
SELECT COUNT(*) FROM foi_attachments WHERE content_type ILIKE '%rar%';
 count
-------
    17
(1 row)

SELECT COUNT(*) FROM foi_attachments;
  count
---------
 2780396
```
