### ISSUE TITLE
Create vanilla version of Alaveteli for Code for Nepal

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/alaveteli#2670]
We have these details:

Our site name will be: Ask Nepal
URL: www.asknepal.info (Already purchased)
Logo: (we are working on it will send it to you once it's ready.) 

We want the site to have three colours 

Red: #E00015 (hyperlinks, menus etc)
Blue: #00ADEF (banner)
White background
Text: black

**Comment by garethrees** [comment]
Done most of the setup for this. Need to create the theme and set up their domain.

**Comment by garethrees** [comment]
Done – some minor tickets remaining
