### ISSUE TITLE
include something pictorial in the default logo

### ISSUE THREAD

**Issue by davewhiteland** [mysociety/alaveteli#2699]
The default theme has a "logo" which is the text word Alaveteli.
Inserts something -- anything even a wee squiggle -- into that file which is plainly a non-text thing, so it is abundantly clear to new owners that that element is a graphic, not a text, which can therefore be replaced.

We (mySociety staff) got caught out in a redeploy by not realising this was a graphic file change requirement and not the site name being dropped in (yes we would have "inspected element" if we had reason to suspect it was not just text :-) )

**Comment by davewhiteland** [comment]
oops I think perhaps this really belongs in https://github.com/mysociety/alavetelitheme and is kind-of related to https://github.com/mysociety/alavetelitheme/issues/46 ...

Leaving this here unless Alavetelians want to move it across.

**Comment by garethrees** [comment]
The default logo for Alaveteli is the word "LOGO" as an image https://github.com/mysociety/alaveteli/blob/develop/app/assets/images/logo.png

Probably needs a similar change in both places? I thought we used an "A" logo mark somewhere, but that might have been on the old-style theme.

**Comment by zarino** [comment]
Two PRs: one for core https://github.com/mysociety/alaveteli/pull/2861, and one for alavetelitheme https://github.com/mysociety/alavetelitheme/pull/64

![screen shot 2015-10-21 at 13 31 27](https://cloud.githubusercontent.com/assets/739624/10636583/9025ecce-77f8-11e5-8eca-733bbe2c4cd3.png)

![screen shot 2015-10-21 at 13 20 10](https://cloud.githubusercontent.com/assets/739624/10636377/6b7a028a-77f7-11e5-8b93-6d9ab6289561.png)
