### ISSUE TITLE
Regexp/UTF-8 warnings in error log

### ISSUE THREAD

**Issue by Flupsy** [mysociety/alaveteli#2700]
Lots of these in the error log:

`App 5151 stderr: /data/vhost/www.whatdotheyknow.com/alaveteli-2015-07-27T13-28-41/vendor/bundle/ruby/1.9.1/gems/rack-1.4.6/lib/rack/utils.rb:81: warning: regexp match /.../n against to UTF-8 string`

**Comment by garethrees** [comment]
None of these in the last 30 days of logs and hasn't been noticed recently.
