### ISSUE TITLE
File upload feature failing for a large file

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#2713]
Apologies if this is a WhatDoTheyKnow.com specific issue. 

I just tried to use the feature for someone with a public body email address to upload a response with an attachment.  I tried three times and got an error message, after a period of time, of:

> Secure Connection Failed
> The connection to the server was reset while the page was loading.

The file was 169 MB. 

Using the same browser, computer etc. I often upload files many GB in size to YouTube so perhaps there's an issue with the way either WhatDoTheyKnow.com or Alaveteli are handling large files; perhaps a setting needs tweaking to permit more time for an upload. 

Maybe an indication the upload is happening / making progress would be useful. 

I suspect this ought be very low priority as it's not a problem I've been previously aware of.

**Comment by HelenWDTK** [comment]
There is a 50mb upload limit.
