### ISSUE TITLE
Authorities' requests no longer appearing in reverse chronological order

### ISSUE THREAD

**Issue by kingqueen3065** [mysociety/alaveteli#2721]
From an authority:

"I am the FOI contact for Dacorum Borough Council. When I click on out authority - the list no longer appears in chronological order with the most recent request first. This was very useful and I would like to ask if you can restore or rectify this issue. With Thanks."

I can verify this - the requests appear in relatively random order, or ordered according to something that I don't understand...

https://puu.sh/jsXQx/94c813fa99.png

**Comment by FOIMonkey** [comment]
Suspect this is because the top listed requests have been recently classified.

**Comment by kingqueen3065** [comment]
Superseded by https://github.com/mysociety/alaveteli/issues/2733
