### ISSUE TITLE
Display AlaveteliCon video interviews on alaveteli.org

### ISSUE THREAD

**Issue by Gemmamysoc** [mysociety/alaveteli#2745]
Would be good to have these videos: https://www.mysociety.org/2015/08/14/videos-from-alavetelicon/ somewhere on alaveteli.org. Maybe on the About page? What do others think?

**Comment by garethrees** [comment]
We have http://alaveteli.org/community/conferences/2012/, so probably http://alaveteli.org/community/conferences/2015/ to follow convention.

**Comment by garethrees** [comment]
This got fixed by https://github.com/mysociety/alaveteli/pull/2799
