### ISSUE TITLE
Check boxes for delete spam from holding pen

### ISSUE THREAD

**Issue by kingqueen3065** [mysociety/alaveteli#2769]
The majority of posts that hit WhatDoTheyKnow's holding pen are spam. It's a pfaf to load each individual one, select Delete and confirm, when there are a lot of them to do at once, particularly as this seems to invoke some system lag. It would be great to have a system like on webmail inboxes, whereby admins could select the responses they want to delete all in one go using checkboxes, then perhaps a confirmation screen listing the first line of each spam to be doubly sure, then a button to delete the whole lot.

**Comment by garethrees** [comment]
For search: bulk action

**Comment by garethrees** [comment]
Hopefully not such an issue once we get #2387 done.

**Comment by kingqueen3065** [comment]
this would still be a very lovely thing to have and save me a load of time :D

**Comment by lizconlan** [comment]
Additional: add a cron job for the `rake:cleanup` task in case that improves the speed (separate PR)

**Comment by lizconlan** [comment]
Closed via #3063 and #3064
