### ISSUE TITLE
Filter by body type in the batch request feature

### ISSUE THREAD

**Issue by kingqueen3065** [mysociety/alaveteli#2784]
We've had a small number of people use the batch request feature now (via personal invitation from administrators.) One user has suggested that it would be very useful to be able to select authorities of certain types, or to filter the list of authorities by them.

The advanced-search feature allows users to search by "tag:" - though the current list of tags isn't (to my knowledge) displayed anywhere on the user-facing section of the site, which perhaps isn't very helpful. It would be good if a) the list of tags could be published for users, b) the search by tag was available in the batch-request feature, and c) ultimately if it would be possible to enable filtering or batch-selection by tag in the batch-request feature.

**Comment by garethrees** [comment]
Fixed by https://github.com/mysociety/alaveteli/pull/4538 (coming soon in Pro TM)
