### ISSUE TITLE
Create Alaveteli stickers

### ISSUE THREAD

**Issue by Gemmamysoc** [mysociety/alaveteli#2810]
@zarino Would be awesome to get some stickers of the Alaveteli logo done :) If you could have them done by next Weds 30th September that would be brill. Thanks!

**Comment by Gemmamysoc** [comment]
Same website as before: http://www.awesomemerchandise.com/Custom-Shaped-Vinyl-Stickers-10cm?quantity=1000&designs=3 Takes 8 working days to print them, plus extra couple of days for delivery apparently

**Comment by zarino** [comment]
I’ve done these, and emailed to @Gemmamysoc. There’s a chance the printer won't like the layout, so we'll keep this ticket open until they've accepted it.

**Comment by Gemmamysoc** [comment]
They look great, thanks @zarino. I'll let you know if printer has any issues.

**Comment by garethrees** [comment]
@Gemmamysoc did this all go okay? If so, feel free to close the ticket :)

**Comment by garethrees** [comment]
Assuming this was all okay. Reopen if there's anything else we need to do! Thanks! :rocket:

**Comment by Gemmamysoc** [comment]
Yes, all went well! Thanks @garethrees
