### ISSUE TITLE
View as HTML mangling text

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#284]
The text at:

http://www.whatdotheyknow.com/request/78593/response/217326/attach/html/3/Internal%20Review%202011%20019%20response%20to%20Ben%20Brown.pdf.html

is gibberish, the conversion has failed. 

As far as I know this is a one off problem; the PDF document opens fine in PDF reading applications.

**Comment by WilliamWDTK** [comment]
This also occurs with tables, see #833

**Comment by garethrees** [comment]
This is desirable, but unlikely to be worked on in the next 12 months so closing for now.
