### ISSUE TITLE
Make placeholders customisable by themes

### ISSUE THREAD

**Issue by wrightmartin** [mysociety/alaveteli#2847]
Just noticed the placeholder for the authority search is 'ministry of defence', I think changing that now involves overriding the whole template

![screen shot 2015-10-13 at 17 01 57](https://cloud.githubusercontent.com/assets/2292925/10460526/a2ea72bc-71cc-11e5-9f3a-264da3a788a4.png)

**Comment by garethrees** [comment]
Should be able to change the translation string to something more colloquial

**Comment by garethrees** [comment]
Closing as you can do this with the [locale files](https://github.com/mysociety/alaveteli/blob/801030db53b159f625b9c59f1916483e3cbf01e7/locale/es_NI/app.po#L3942-L3943).
