### ISSUE TITLE
Admin page hard to access for very large incoming messages

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#292]
The admin page for a message shows the full raw message. 

Where there are big attachments this causes the page to load very slowly; or in extreme cases make my browser hang and give up. 

There's an easy enough workround - to stop loading the page shortly after requesting it.

Ideally perhaps if say the message was over 5 MB big (whatever the figure) then the full message ought not be displayed by default. 

This is an occasional issue which can be worked round, not a priority to fix, I'm reporting it as I just had to force quit my browser when it gave up on such a page.

**Comment by WilliamWDTK** [comment]
This is still an issue.  I encountered it today when redelivering [this message](https://www.whatdotheyknow.com/request/808136#incoming-2100224) from the holding pen.
