### ISSUE TITLE
Cant access json in details page

### ISSUE THREAD

**Issue by schlos** [mysociety/alaveteli#2942]
On details page, example:
https://www.whatdotheyknow.com/details/request/mobile_phone_requirement_for_uni

I'm not sure even if this should work, but page description says:

"You can get this page in computer-readable format as part of the main JSON page for the request. See the API documentation."

So, following that logic, by adding ".json" to the URL leads nowhere (empty page will be opened):
https://www.whatdotheyknow.com/details/request/mobile_phone_requirement_for_uni.json

I've detected this problem first on Imamo pravo znati, and opened GitHub ticket https://github.com/codeforcroatia/alaveteli/issues/31, but then I could reproduce same on WDTK.

If this is not supposed to be supported for details page, maybe text should be updated.

**Comment by garethrees** [comment]
It's referring to https://www.whatdotheyknow.com/request/mobile_phone_requirement_for_uni.json.

The wording there could definitely be improved.
