### ISSUE TITLE
Offer mechanism to submit ID in private

### ISSUE THREAD

**Issue by kingqueen3065** [mysociety/alaveteli#2944]
A user has suggested that we enable people to provide their ID in private, where an organisation has refused to provide information until their ID is proved - example https://www.whatdotheyknow.com/request/243728/response/735195/attach/2/FOI%201783%20Ms%20Anne%20Marie%20Poulson%20Response.pdf . I know that Ask the EU were having similar issues where the EU insisted on a full postal address before considering their request.

**Comment by kingqueen3065** [comment]
Giving my own view, as expressed to the user: 

I appreciate what you say about the lack of a mechanism for provision of ID in privacy, but would like to assure you that this is definitely an exception; there have been over 300,000 requests via the site and we have only had a handful of occasions where the organisation has insisted on ID (other than where requesters have signed up with obvious pseduonyms or just their first name or whatever.) I'd be concerned that if we add this as a regular mechanism, it may encourage more organisations to similarly demand ID. It's worse in other
jurisdictions; "Ask the EU" are (or were, I haven't checked recently) struggling because the EU insisted on full postal address being provided for each request. They have the requester post their address then the Ask the EU team hide it - not a perfect system...

**Comment by garethrees** [comment]
Closing this as its a really niche requirement, and there are good enough off-site alternatives.
