### ISSUE TITLE
Improving OpenGraph metadata

### ISSUE THREAD

**Issue by owenblacker** [mysociety/alaveteli#2946]
From pull request #2652, we have good OG metadata on WDTK now, but to [make Facebook happier](https://developers.facebook.com/tools/debug/og/object/?q=https://www.whatdotheyknow.com/request/theresa_mays_internet_history) (and thus to improve share quality), we need to provide an `og:image` that's 200×200. At the moment, it links to [the default "logo here" image](https://www.whatdotheyknow.com/assets/logo-034f78226699f1dbc79535cc3f45c07b.png).

We have the [favicon at 192×192](https://www.whatdotheyknow.com/assets/android-chrome-192x192-b8baa544602cbb02a21b54a46e52f525.png); any chance we could get Alaveteli to regenerate a 200px-square of this and shove that into the `og:image` tag at some point?

**Comment by zarino** [comment]
Here's the output from Facebook's Open Graph debugger, for a randomly selected WDTK request page:

![screen shot 2015-12-15 at 11 36 24](https://cloud.githubusercontent.com/assets/739624/11809659/58e82300-a320-11e5-84fb-92964599fada.png)

And here's an equivalent example from mysociety.org which had its Open Graph tags sorted out [in May this year](https://github.com/mysociety/orgsites/issues/697):

![screen shot 2015-12-15 at 11 39 20](https://cloud.githubusercontent.com/assets/739624/11809693/8d4c8a3c-a320-11e5-882d-022947391279.png)
