### ISSUE TITLE
Reset request closure countdown when outgoing message sent

### ISSUE THREAD

**Issue by kingqueen3065** [mysociety/alaveteli#2953]
When a user (perhaps ill-advisably) sends an outgoing message late, perhaps just before the request automatically shut to new correspondence, it would be great if this reset the activity countdown such that the request doesn't close before the authority's reply. 

Example: https://www.whatdotheyknow.com/request/hotham_park_cafe_costs - authority attempted to reply but it bounced, so they contacted the admins. I manually re-opened the request and asked the authority to re-send.

**Comment by RichardTaylor** [comment]
According to [the documentation](http://alaveteli.org/docs/running/requests/#old-requests-by-default-6-months-without-activity) and how I understood how this has been working any activity would re-set the clock on the request being closed to new responses.  It might be worth looking at what happened at:

https://www.whatdotheyknow.com/request/274082 

I'm concerned there may be a bug here and this isn't a request for a new feature but the system isn't behaving as intended. I'm not sure but I've clicked the bug label.

**Comment by RichardTaylor** [comment]
Another example:

https://www.whatdotheyknow.com/admin/requests/286350

There's an outgoing message at 2016-01-03 but the next day I saw it set to "authority only" which was preventing a legitimate response getting through (as the authority was responding via a different domain than the request address).

The new outgoing message ought have enabled responses from anyone.
