### ISSUE TITLE
Notices on request/body pages based on authority tags eg. foi_no and eir_only bodies

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#296]
We ought have some text at the top of all request threads making clear if bodies are not formally subject to FOI, or if they are subject to EIR only. 

We should clearly mark request threads to foi_no and eir_only tagged bodies

This might be a special case; or it maybe that in general it would be desirable for authority tags to be associated with notices which can be displayed on either:

i/ Request Threads
ii/ Body Pages
iii/ Both i/ & ii/ 

If implemented in the general case we could then easily put text on say all police authority or all housing association body and request pages. 

This is related to the WhatDoTheyKnow issue at:

https://github.com/mysociety/whatdotheyknow/issues/13

**Comment by RichardTaylor** [comment]
There's a hard-coded partial fix to this now; showing

>You can only request information about the environment 

A more general issue is #387 "Show note(s) based on a public body's tag(s)"

**Comment by lizconlan** [comment]
Closing this as the request page note was added in #4499. Have opened #4814 to add a similar note to the authority page
