### ISSUE TITLE
Case study of Batch Request feature

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/alaveteli#2965]
From the retreat:

> Push batch request feature - talk to partners about putting together a case study of how batch requests can help them boost traffic

Would be good to have a little more background on this:
- Are any partners using it? if so, who, and have they had good results?
- How exactly can it be switched on?
- Anything else partners will need to know

**Comment by Gemmamysoc** [comment]
Myf. When I've done more handover stuff with Jen, let's have a chat about this - the best way to go about contacting partners, who has used batch request feature etc. I think my chat with Jen will help us understand the best people to get in touch with :)

**Comment by MyfanwyNixon** [comment]
Great, yes!

**Comment by MyfanwyNixon** [comment]
Is this still relevant, given new developments for journalists?

**Comment by MyfanwyNixon** [comment]
Closing, as I suspect this will complicate/be covered by AP.
