### ISSUE TITLE
Test Alaveteli over poor internet connections

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#2980]
[Why?](https://aeon.co/videos/for-six-years-mahabir-pun-hiked-two-days-each-month-just-to-check-his-emails)
- http://webmasters.stackexchange.com/questions/861/how-can-i-simulate-a-slow-connection-for-page-load
- http://royal.pingdom.com/2012/06/15/loading-todays-sites-over-dialup/

**Comment by lizconlan** [comment]
The pingdom link has made me wonder whether I still own a dialup modem (probably, just on the grounds that throwing obsolete tech away is not one of my core skills). Although this may be more useful https://www.charlesproxy.com/documentation/proxying/throttling/

**Comment by garethrees** [comment]
Yeah I'm pretty sure there are tools to simulate this. I didn't read the links in the bullet points thoroughly, but that link you posted looks good.

**Comment by lizconlan** [comment]
Seems to need/include Java though so not an ideal solution (a slow internet with the laptop fans running full tilt is unlikely to be a fun experience)

**Comment by garethrees** [comment]
> a slow internet with the laptop fans running full tilt is unlikely to be a fun experience

That's pretty much the point of this ;)

**Comment by lizconlan** [comment]
Ah, there's one built into the Chrome Dev Tools, that's the simplest thing

![screen shot 2016-01-06 at 09 39 58](https://cloud.githubusercontent.com/assets/27760/12139623/a27cb158-b459-11e5-951c-01aff6159bec.png)

**Comment by garethrees** [comment]
Closing until we have a specific report of a problem
