### ISSUE TITLE
Deleting requests in the admin is really confusing

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/alaveteli#2987]
Going through and deleting requests on the infoLib site has brought up something that is quite confusing.

If a request has incoming and outgoing messages on it you have to delete the outgoing message last otherwise you can no longer access the entire request thread from (sitename)/admin/requests/ even though the request thread is still linked to there.

eg: 
![screen shot 2016-01-07 at 15 17 59](https://cloud.githubusercontent.com/assets/4170351/12173994/fa905d2e-b551-11e5-8f3b-261c45a233d1.png)

but if I click on any of those test requests that I've already deleted the outgoing messages for I get a 500 server error (to be expected I know - but the links are still there)

![screen shot 2016-01-07 at 15 20 14](https://cloud.githubusercontent.com/assets/4170351/12174037/33f04502-b552-11e5-9edb-ebf4fe505827.png)

There are two bad things about this. 

Firstly, it stays on that server error page and doesn't redirect you back to the page in the admin with the requests (/admin/requests) and when you click the back button on your browser it doesn't take you back either. 

Secondly, this happens immediately after you've deleted the outgoing message, but you might assume (as I did) that because you received that error message, yet the thread is still showing (when you get back to the requests page), deleting the message hasn't worked. Then you try and click on the thread in the /admin/requests page and you get the error again, so you can't go back into it. Fine, you think, deleting it worked BUT you are then thinking "Well there were two other messages in that thread - how do I access them now? or did it just delete everything because I deleted the outgoing message?" and you have no obvious way to check in the admin. 

So Gareth explained to me how to get hold of the messages in the thread where you've deleted the outgoing messages (going onto the live version of the request and clicking the admin link) however the same issue with the 500 server error occurs again and you again can't click the back button on the browser to go back to the page with the request thread on. This is particularly annoying if you're trying to delete a test request with multiple emails testing things on them.

**Comment by garethrees** [comment]
This looks like a better explanation of the issues in https://github.com/mysociety/alaveteli/issues/2290.

**Comment by garethrees** [comment]
I think this has now been resolved by https://github.com/mysociety/alaveteli/pull/2818. We also prevent destroying the initial outgoing message (https://github.com/mysociety/alaveteli/pull/3855) as this has the same effect of breaking requests.
