### ISSUE TITLE
"show quoted sections" is misleading

### ISSUE THREAD

**Issue by bjh21** [mysociety/alaveteli#301]
When Alaveteli chooses to hide part of a message, the hidden part is replaced by a link labelled "show quoted sections".  This is misleading because it's not only quotations that are hidden by this code.  It deliberately tries to hide some disclaimers and frequently accidentally hides useful content.  I would suggest that the link text should be something like "show rest of message".  On WhatDoTheyKnow, users frequently don't realise that their answers are hidden behind "show quoted text"; I hope that a clearer link might reduce this.

What the link should say instead of "hide quoted sections" is a bit trickier.  I suppose "show less of message" would be accurate, if a bit strange.

**Comment by hsenag** [comment]
Another example here: https://www.whatdotheyknow.com/request/fraudulent_references#incoming-641618

**Comment by hsenag** [comment]
Also some examples of things hidden inside quoted sections are listed on the more general #23.

**Comment by RichardTaylor** [comment]
Another example where the substantive response was hidden behind "show quoted sections"

https://www.whatdotheyknow.com/request/care_leavers_16_18

I doubt it would be easy or practical to detect when a substantive response was included interspersed in a quoted response, but that might be ideal. 

More practical might be a setting to prevent collapsing a particular correspondence thread - so it was always shown in "unfolded" form.

**Comment by RichardTaylor** [comment]
+1 https://www.whatdotheyknow.com/request/worker_accommodation_costs_24#incoming-1849706

**Comment by FOIMonkey** [comment]
+1 A user contacted us because the response was hidden https://www.whatdotheyknow.com/request/delays_in_reachingleaving_scene

**Comment by FOIMonkey** [comment]
+1 Milton Keynes Council have been annotating requests made to them where the response was under "show quoted sections"
https://www.whatdotheyknow.com/user/milton_keynes_council
eg https://www.whatdotheyknow.com/request/vehicle_fleet_information_and_go_24#comment-107127
https://www.whatdotheyknow.com/request/information_on_cycle_paths_3#comment-107123
https://www.whatdotheyknow.com/request/subject_highwayroads_asset_manag_114#comment-106263
