### ISSUE TITLE
Update 'get help' section of getting started guide

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#3028]
http://alaveteli.org/docs/getting_started/#step-one-get-a-working-uncustomised-version-running

> Alternatively, we have very limited capacity to run a handful of Alaveteli sites for willing volunteers. We want to learn more about how we can support third parties, and to do so we’re happy to help host low-volume sites for two or three partners. However, you will have no service level agreement, no warranties, and no guarantee on our time: if the website goes down when we’re on holiday, you’ll have to wait until we’re back! If you want to try this route, please get in touch to find out if we have capacity.

Point to https://www.mysociety.org/mysociety-around-the-world/apply-for-support-and-development-from-mysociety/

**Comment by lizconlan** [comment]
closed via #3048
