### ISSUE TITLE
Links to requests by default link to the last message, which isn't always useful

### ISSUE THREAD

**Issue by kingqueen3065** [mysociety/alaveteli#3031]
Where we send a "there's been a new response to your request" email, it makes sense to link to the last message. However, in other cases it is perhaps usually more appropriate to link to the first message, so that the person browsing the site sees the request first and then the response.

A user finds this irritating. I, too, strip the #whatever off the end of the URL several times a day whilst dealing with support requests etc.

**Comment by garethrees** [comment]
I think that when you get the new response email you _do_ want to go to the latest update.

Definitely don't want to do this while just [browsing the requests](https://www.whatdotheyknow.com/list/successful).

**Comment by kingqueen3065** [comment]
Yes, that was what I was attempting to say.

**Comment by garethrees** [comment]
> I have recently joined your site as I have been a long term admirer of your work.
> 
> I just find one part of the running of the website difficult and
> that is whenever I try to load a new page to look at; it can go
> directly to the bottom of the said new page. This may be useful for
> some people to get to the latest development in a FoI exchange but
> if your are trying to look at the issue from the beginning such as
> what was the details requested then this becomes very tricky to be manoeuvrable.
>
> I hope this could improve somehow.
>
> Keep up the great work.
