### ISSUE TITLE
Investigate exporting analytics goals and funnels

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#3062]
Ideally export them and host them somewhere depending on format.  alaveteli-analytics repo?

If not, write some guides on how to create each.

**Comment by garethrees** [comment]
Concentrate on goals; will re-prioritise funnels later

**Comment by Gemmamysoc** [comment]
This link should allow other Analytics accounts to re-use our goals: https://analytics.google.com/analytics/web/template?uid=j0qfdzwKQdCSDdvpxzCaJA
