### ISSUE TITLE
Unpleasant word wrap on outgoing emails

### ISSUE THREAD

**Issue by edent** [mysociety/alaveteli#3065]
I think this is related to https://github.com/mysociety/alaveteli/issues/2913 

Lines are artificially truncated on outgoing emails to users. This results in an unpleasant reading experience especially on mobile and other devices with narrow viewports. 

![14563815700110](https://cloud.githubusercontent.com/assets/837136/13311713/bd4f189e-db88-11e5-9d3e-48ee0b77860d.png)

**Comment by lizconlan** [comment]
@edent - quick sanity check, did that come through as an HTML email or plaintext?

**Comment by edent** [comment]
Plain text.

**Comment by lizconlan** [comment]
@edent thanks, was slightly thrown by the auto formatting of the link. Experimenting

**Comment by edent** [comment]
This is still a problem.

![14683147255070](https://cloud.githubusercontent.com/assets/837136/16761690/21454696-4819-11e6-8552-3843a8e137a8.jpg)
