### ISSUE TITLE
Check the motd script for jessie

### ISSUE THREAD

**Issue by lizconlan** [mysociety/alaveteli#3116]
Seems to have stopped working, possibly as a result of the updated hashicorp box (from 1.0.0
to 1.0.1).

Appears to be because `/var/run/motd` has been created as `/var/run/motd.new` (which prevents the symlink working) so the quick fix is:

```
sudo mv /var/run/motd.new /var/run/motd
```

**Comment by garethrees** [comment]
Given Debian stretch is now the default, just going to close this. PRs accepted if anyone does want to fix this though
