### ISSUE TITLE
Document building translations for a theme

### ISSUE THREAD

**Issue by stevenday** [mysociety/alaveteli#3122]
I think I need to run:

```shell
$ bundle exec rake gettext:find_theme THEME=mytheme-name
```

But I only figured this out by poking around in `lib/tasks`. http://alaveteli.org/docs/developers/i18n/ and http://alaveteli.org/docs/customising/themes/ don't make any mention of it.

**Comment by garethrees** [comment]
Dupe of https://github.com/mysociety/alaveteli/issues/3122

**Comment by garethrees** [comment]
Edited with correct issue!

**Comment by stevenday** [comment]
D'oh, I thought I'd had this issue before but I couldn't find it, sorry!

**Comment by garethrees** [comment]
No problem! The link back to the original is a good pointer that its come up again, anyway :)
