### ISSUE TITLE
script/cleanup-holding-pen has output, which gets printed when run via cron

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#3128]
Looks like the [`--silent`](https://github.com/mysociety/alaveteli/blob/develop/script/cleanup-holding-pen#L4) option is not surprising the rake task's [stdout](https://github.com/mysociety/alaveteli/blob/develop/lib/tasks/cleanup.rake#L13).

**Comment by lizconlan** [comment]
It appears that `--silent` prevent message sent to `$stderr` ending up in `$stdout` which is not what I was expecting it to do
