### ISSUE TITLE
Batch request placeholder not replaced

### ISSUE THREAD

**Issue by schlos** [mysociety/alaveteli#3130]
Placeholder [Authority name] is not replaced with autority name when sending group requests.

Examples:
http://imamopravoznati.org/info_request_batch/3
http://imamopravoznati.org/info_request_batch/6

**Comment by garethrees** [comment]
Reported by Sweden e.g. https://www.fragastaten.se/sv/info_request_batch/1

**Comment by garethrees** [comment]
The code is fine – the problem for Sweden is that they don't have translations at their [current release version (0.23.0.3)](https://github.com/mysociety/alaveteli/blob/0.23.0.3/locale/sv/app.po#L707-L714).

The easiest answer is to upgrade a minor version (to 0.23.0.4), where [translations exist](https://github.com/mysociety/alaveteli/blob/0.23.0.4/locale/sv/app.po#L716-L723) for these strings. These aren't the current translations, but better than nothing. The current translations were introduced in [0.24.0.7](https://github.com/mysociety/alaveteli/blob/0.24.0.7/locale/sv/app.po#L695-L702).
