### ISSUE TITLE
Adwords guide is very hard to find

### ISSUE THREAD

**Issue by abimysoc** [mysociety/alaveteli#3168]
http://alaveteli.org/docs/running/adwords/ exists.

It is not linked from http://alaveteli.org/docs/running/ (should be in the sidebar nav, surely?) and also the [search](http://alaveteli.org/search/?q=adwords) draws a blank on it.

**Comment by garethrees** [comment]
Dup of last bits of https://github.com/mysociety/alaveteli/issues/3069#issuecomment-203859178
