### ISSUE TITLE
More prominent 'Built by mySociety' messaging

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/alaveteli#3208]
Moving across from mysociety/sysadmin#676 which discusses more prominent branding across all of our sites as a way of making their provenance clear.

**Comment by zarino** [comment]
@MyfanwyNixon I’m assuming the intention of this ticket is to have prominent mySociety branding (ie: standard mySociety footer) on the [default "alaveteli-theme"](http://demo.alaveteli.org) – is that correct?

If so, we should move this ticket to the https://github.com/mysociety/alavetelitheme repo.

We can have a chat about this in a hangout, if you need context on how the various bits of alaveteli fit together.

**Comment by MyfanwyNixon** [comment]
OK so the ticket just came about from a general discussion about how all mySociety sites should have this branding. See martin's comment here https://github.com/mysociety/sysadmin/issues/676#issuecomment-179926554 where alaveteli.org is listed as one of those sites.

I understand the logic of having it on the theme and I can also see that in some ways that is more desirable, but the intention of *this* ticket is to ensure that alaveteli.org is in line with all our other 'product' sites.

**Comment by zarino** [comment]
Cool, in that case, we can close this ticket in favour of the one for [mysociety-docs-theme](https://github.com/mysociety/mysociety-docs-theme/issues/19) – which is the place that alaveteli.org lives.
