### ISSUE TITLE
Add Ubuntu 16.04 LTS (Xenial) support to install scripts

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#3211]
Released today https://insights.ubuntu.com/2016/04/20/canonical-unveils-6th-lts-release-of-ubuntu-with-16-04/

Related: https://github.com/mysociety/alaveteli/issues/2019

**Comment by garethrees** [comment]
We should do this and remove precise (related to #3928)

**Comment by garethrees** [comment]
https://wiki.ubuntu.com/Releases

**Comment by garethrees** [comment]
We might want to skip this and go straight to Bionic https://github.com/mysociety/alaveteli/issues/4971

**Comment by gbp** [comment]
https://blog.travis-ci.com/2018-11-08-xenial-release
