### ISSUE TITLE
Add documentation for `USE_RECAPTCHA_FOR_REGISTRATION`

### ISSUE THREAD

**Issue by lizconlan** [mysociety/alaveteli#3213]
Once #3145 is merged and #3146 is included in a release, a new section should be added to `docs/running/handling_spam` (in [the `gh-pages` branch](https://github.com/mysociety/alaveteli/tree/gh-pages)) to explain the use of the new `USE_RECAPTCHA_FOR_REGISTRATION` config option to limit the creation of new spammy user accounts.

**Comment by garethrees** [comment]
Need to do in https://github.com/mysociety/alaveteli/issues/3137

**Comment by lizconlan** [comment]
if we're still going to use it, my understanding was that it wasn't successful in reducing spam

**Comment by garethrees** [comment]
Yeah, just a reminder for when we get to it

**Comment by lizconlan** [comment]
needed for #3137 unless we revert 783f5ea and remove the feature from the release (note that the documentation advises against using it)

**Comment by lizconlan** [comment]
decision: drop this, looks like the change commit is not in master \o/
