### ISSUE TITLE
Mail quote is not detected properly (Croatian)

### ISSUE THREAD

**Issue by schlos** [mysociety/alaveteli#3225]
When information officer replies, usually MS Outlook set in Croatian language, it will set line below which original message is quoted.

This is not detected (presumably due to Croatian words "Original message" = "Izvorna poruka").

Few existing examples:
http://imamopravoznati.org/request/zdravstvena_skrb_broj_kreveta_16
http://imamopravoznati.org/request/otvaranje_baze_podataka_popis_sk#incoming-752
http://imamopravoznati.org/request/broj_turista_u_2014_godini_313#incoming-342
http://imamopravoznati.org/request/broj_turista_u_2014_godini_52#incoming-314 

For example:

```
-----Izvorna poruka----- 
From: Miroslav Schlossberg
Sent: Thursday, April 14, 2016 10:50 PM
To: Zahtjevi za PPI upućeni prema Neuropsihijatrijska bolnica &#x27;Dr. Ivan 
Barbot&#x27; Popovača
Subject: Zahtjev za pristup informacijama - Zdravstvena skrb - broj kreveta
```

**Comment by schlos** [comment]
I assume this is part of code:
https://github.com/mysociety/alaveteli/blob/c7793fe2a9eb8d041c3d8bd843e6c5b3d05645f4/app/models/outgoing_message.rb#L273

Would it be possible to include regex with list of possible combinations here?

-----REGEX-----

Regex values:
- Original Message
- Izvorna poruka
- etc.. same in other languages

I.e. regex:
(Original Message|Izvorna poruka|etc..)

**Comment by garethrees** [comment]
Hey @schlos. Sorry that this is causing you some trouble.

We already have a ticket open for this at https://github.com/mysociety/alaveteli/issues/2662.

Until then, the best bet is to [monkeypatch the method](http://alaveteli.org/docs/customising/themes/#adding-or-overriding-models-and-controllers) in your theme with the options you want.

Cheers.

**Comment by schlos** [comment]
Hi,
I tried to find but couldnt related ticket for this. Thanks for pointing to #2662.
Cheers!
