### ISSUE TITLE
Gemma to learn some git & markdown

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#3245]
We discussed in sprint planning that it would be useful for Gemma to learn some basic git and markdown to make it easier for her to contribute to the experiments repo and other documentation repos.

Here are some first steps:

- [ ] Run through [try.github.com](https://try.github.io/)
- [ ] Do the [markdown tutorial](http://www.markdowntutorial.com/)

After these we'll have to get you set up with the [GitHub desktop](https://desktop.github.com/) app and an editor that has a built-in markdown previewer.

**Comment by Gemmamysoc** [comment]
Training done. Just need to practice it :D

**Comment by garethrees** [comment]
> Training done. Just need to practice it :D

In that case lets close this until anything more specific comes up. 🎆
