### ISSUE TITLE
Add AnalyticsEvent for tracking GitHub links

### ISSUE THREAD

**Issue by lizconlan** [mysociety/alaveteli#3249]
Enable the WDTK theme to track GitHub exit links as well as Facebook and Twitter ones

**Comment by lizconlan** [comment]
in 'lib/analytics_event.rb` add 

`GITHUB_EXIT = 'GitHub Exit'` to the `module Action` section

**Comment by garethrees** [comment]
https://github.com/mysociety/alaveteli/graphs/traffic
