### ISSUE TITLE
Stats graphs have output

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#3250]
We moved the graph generation to ruby in https://github.com/mysociety/alaveteli/pull/3000 (fixing https://github.com/mysociety/alaveteli/issues/675).

I think that then caused https://github.com/mysociety/alaveteli/issues/3126 – or at least didn't fix it – which got addressed by https://github.com/mysociety/alaveteli/issues/3138.

Somewhere in this is https://github.com/mysociety/alaveteli/issues/619, which I _think_ should be fixed by #3138, but the scripts now seem to output even when they have enough data:

```
vagrant@vagrant-ubuntu-precise-64: ~/alaveteli
$ script/user-use-graph
(in /home/vagrant/alaveteli)
```

We're getting this from WDTK:

```
[cron-alaveteli] Cron <USER@SERVER> /APP_ROOT/www.whatdotheyknow.com/alaveteli/script/user-use-graph
(in /APP_ROOT/www.whatdotheyknow.com/alaveteli-2016-05-12T14-11-51)
```

As I understand it these scripts should be silent by default, and can be passed a `--verbose` option in some way?

**Comment by lizconlan** [comment]
I think this is because I incorrectly took out the `--silent` option which suppresses the `in /APP_ROOT/www.whatdotheyknow.com/alaveteli-2016-05-12T14-11-51` message. Sorry! 😞
