### ISSUE TITLE
Change mail server log text to "check back tomorrow"

### ISSUE THREAD

**Issue by kingqueen3065** [mysociety/alaveteli#3251]
I sent this FOI request about midnight last night. https://www.whatdotheyknow.com/request/testing_mail_delivery_log_views
As of midday today, no logs have appeared, either in the user display or in the admin: 
![ss 2016-05-15 at 12 36 31](https://cloud.githubusercontent.com/assets/11923618/15273721/15cf227a-1a9a-11e6-8089-b8d127119839.png)
![ss 2016-05-15 at 12 37 51](https://cloud.githubusercontent.com/assets/11923618/15273723/17d27702-1a9a-11e6-9988-71d7accf0e85.png)
My mail server definitely received it at the time:
![ss 2016-05-15 at 12 34 33](https://cloud.githubusercontent.com/assets/11923618/15273727/35bc69e4-1a9a-11e6-8d43-f8ced1360826.png)
And so did my mail client:
![ss 2016-05-15 at 12 40 55](https://cloud.githubusercontent.com/assets/11923618/15273741/570cf096-1a9a-11e6-8455-5db4ed396822.png)

**Comment by garethrees** [comment]
Hey @kingqueen3065. I can see them now (although I couldn't last night when I marked this issue as `1 - new`). I wonder if the varnish cache duration is too long for the endpoint that provides the logs to the dropdown. I'll take a look in to it.

**Comment by garethrees** [comment]
Thanks for the excellent issue report too, btw!

**Comment by garethrees** [comment]
For whatever reason, the mail server logs were created ~24 hours after the initial request was made.

```ruby
outgoing_message.created_at
# => Sun, 15 May 2016 00:24:45 BST +01:00

outgoing_message.mail_server_logs.map(&:created_at)
# => [Mon, 16 May 2016 00:46:17 BST +01:00,
#     Mon, 16 May 2016 00:46:17 BST +01:00]
```

**Comment by garethrees** [comment]
Linking to #624

**Comment by garethrees** [comment]
This is because the script that looks for logs acts on the 3 most recent logs that have been rotated. It doesn't scan the active log (given that its still being written to). We should update the wording on that message to "check back tomorrow" or similar.
