### ISSUE TITLE
Update error message for reCAPTCHA failure and consider improving reCAPTCHA implementation

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#3275]
Currently if a user doesn't complete the reCAPTCHA challenge on sign up they get the error:

> There was an error with the words you entered, please try again.

as reCAPTCHA isn't generally asking people to enter words now, but to click a checkbox next to the text "I am not a robot" this error message is confusing and needs updating.  I'm raising this ticket as the error / requirement to complete the reCAPTCHA test has confused one user of WhatDoTheyKnow.  

(Other tests are sometimes presented to users too eg. there's a click the images containing this type of thing test so the error message probably shouldn't just refer to the checkbox.)

Perhaps it could be made clearer to users what's required of them via the reCAPTCHA and why.  Text could be added to the sign-up form to explain / introduce the reCAPTCHA requirement. Inspiration could be drawn from http://ux.stackexchange.com/nocaptcha (screenshot attached) 

Consider investigating to see how many legitimate users sign-ups are being thwarted by reCAPTCHA. Is one confused user writing a request for help the tip of an iceberg? 

<img width="1067" alt="screen shot 2016-05-25 at 23 30 32" src="https://cloud.githubusercontent.com/assets/547695/15558327/1a9b53b6-22d1-11e6-85fd-0d43431768cc.png">

**Comment by RichardTaylor** [comment]
The user who wrote to us after experiencing the confusing error message has provided a screenshot showing they were not seeing the reCAPTCHA box at all.

**Comment by lizconlan** [comment]
I wonder whether Adblock is removing it 😢

**Comment by garethrees** [comment]
> A suggestion, if it's not already implemented: where reCaptcha is on a
webpage, tell people who experience difficulties using it for whatever
reason, e.g. visual impairment, to get in touch with us so we can
manually exempt them?
