### ISSUE TITLE
Contact journalists worldwide to ask for quotes on how FOI has been useful to them

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/alaveteli#3322]
To tie in with International RTK Day and the 250th anniversary of FOI.

Identify those journalists who have written important stories thanks to FOI. Approach to see if they'd provide a quote for a round-up blog post.

**Comment by MyfanwyNixon** [comment]
I have begun to assemble this list but am coming to two conclusions:
- Our Alaveteli partners probably have better contacts than we do among the journalists for their own countries;
- Journalists may be too busy to bother to provide us with a quote, unless they are already particularly friendly towards mySociety (as some are) or our partners' orgs.

**Comment by garethrees** [comment]
Looks like discussion is happening in https://groups.google.com/forum/#!topic/alaveteli-users/6Mle_gTajSo – might be worth making a new thread asking for journalist contacts?
