### ISSUE TITLE
"Twitterstorm" for International Right To Know Day

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/alaveteli#3323]
For 28 September, International RTK Day. Needs setting up beforehand.

Use hashtags #IRTKD2016 and #IRTKD
@Gemmamysoc to encourage Alaveteli partners to tweet links to their most interesting requests; other partners to  RT them.

**Comment by Gemmamysoc** [comment]
Design Alaveteli shared graphics to promote the use of FOI across the sites.

**Comment by MyfanwyNixon** [comment]
All scheduled for WDTK and Gemma has done a great job getting the graphics to partners.
