### ISSUE TITLE
Improve documentation relating to the CSV upload page

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#3325]
Suggestions:

* Link from the CSV upload form to the documentation at: http://alaveteli.org/docs/running/admin_manual/#creating-changing-and-uploading-public-authority-data 
* Add an example with a comma in the name to the example given on the form itsself, and a line with the use of ""  around entries. 
* The Alaveteli documentation and / or the text on the CSV upload form should explain what the "import tag" is. Presumably the "import tag" isn't a tag, or is some kind of special tag (it doesn't appear on the body admin page in the tag field).

**Comment by lizconlan** [comment]
> explain what the "import tag" is

Is this a reference to the optional tag field? Text first introduced in https://github.com/mysociety/alaveteli/commit/ac450ac508f1b7e3db5bb7a6162b182531c1cdaa
