### ISSUE TITLE
Translated share graphics for top Alaveteli sites

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/alaveteli#3330]
Nice graphics that sites can share via social media for International Right To Know day.

Ideas needed but as a start, maybe something along the lines of:

> It's International Right To Know Day - thanks to [name of site] we know [number of requests] more things 

> What do YOU want to know? [URL of site]

(Add better ideas, please @Gemmamysoc !)

Ideally the text would be finalised in time to have the site owners translate them before the design.

**Comment by Gemmamysoc** [comment]
Some more copy ideas here: https://docs.google.com/document/d/1Tph4QT0Q2F9Uxn9VsvObS_Coayd98ItpKhkDsiUfgL8/edit

**Comment by wrightmartin** [comment]
I've gone completely freestyle with these as a starter, thoughts?

![right-to-know-aus](https://cloud.githubusercontent.com/assets/2292925/18381688/682161c8-7675-11e6-8ec7-18dc9d31a789.png)
![right-to-know-nz](https://cloud.githubusercontent.com/assets/2292925/18381690/6824158a-7675-11e6-9aca-e55512535202.png)

**Comment by Gemmamysoc** [comment]
I really like these! I'll let @MyfanwyNixon have a look, then I'll share with partners to see if they'd like some in their languages

**Comment by MyfanwyNixon** [comment]
Yes, like!

**Comment by wrightmartin** [comment]
Here's the UK one with actual data...

![right-to-know-uk](https://cloud.githubusercontent.com/assets/2292925/18389682/005c2ab2-769f-11e6-8809-1c0f86d5a5ca.png)

When we do translations we may need to tweak the design country-to-country depending on word-length and character count etc

**Comment by Gemmamysoc** [comment]
Sorry, @wrightmartin Just noticed that it says 23 September on the graphics - it should say 28 September :) Cheers

**Comment by wrightmartin** [comment]
Nicely spotted @Gemmamysoc

**Comment by Gemmamysoc** [comment]
Martin - have you done these designs on InDesign? I.e. can I edit them myself?

**Comment by wrightmartin** [comment]
@Gemmamysoc in Illustrator, you're welcome to make changes etc if you can, if not I'll be nice and quick if you need things done urgently

**Comment by Gemmamysoc** [comment]
Hmm, I'm actually not very good at using Illustrator :( Would you have time to create some for AsktheEU? Copy is here: https://docs.google.com/document/d/1vvbzVNhmJnQ_1e1MOu-PmaNwd5JVKT8taWZfbS3VklQ/edit

**Comment by Gemmamysoc** [comment]
Italian partners would like some too :) Here is the copy they'd like (one in English, one in Italian):

Celebrate International Right To Know Day by exercising your right to access information.
Request information now on [chiedi.dirittodisapere.it]

Festeggia la Giornata Mondiale del Diritto di Accesso alle Informazioni esercitando il tuo diritto alla trasparenza.
Invia una richiesta di accesso su [chiedi.dirittodisapere.it]

**Comment by Gemmamysoc** [comment]
AsktheEU have confirmed this copy is okay: https://docs.google.com/document/d/1vvbzVNhmJnQ_1e1MOu-PmaNwd5JVKT8taWZfbS3VklQ/edit

**Comment by StephenAbbott** [comment]
@MyfanwyNixon @Gemmamysoc @wrightmartin Hi everyone. Is September 28th still known as International Right to Know Day? I thought that it was now called International Day for Universal Access to Information following last year's UN resolution http://en.unesco.org/iduai2016 Or are campaigners still calling that data International Right to Know Day?

**Comment by Gemmamysoc** [comment]
Hi Stephen!

There has been a lot of discussion about this over on FOIANet. I'll forward
you the thread. They would like to continue using International Right To
Know Day, and are looking at trying to convince UNESCO to use that too :)

**Comment by wrightmartin** [comment]
@Gemmamysoc I've done the EU and Italian ones - they're in the design drive under Alaveteli/Right to know day/pngs

Let me know if they're any problems

**Comment by Gemmamysoc** [comment]
Love them! Thanks Martin

**Comment by fin** [comment]
Hi there! Could I get access to the Template to create a version of this for Austria?
We (Forum Informationsfreiheit / informationsfreiheit.at) are currently finalizing our outreach plans for the day. Thanks!

**Comment by Gemmamysoc** [comment]
Hey Markus! I just tried to attach the source file to here but it's more than 10MB in size, so wouldn't let me. It's an Illustrator file, so you'll need to have the software to be able to open it. If you'd like me to email you the Illustrator file, let me know best address! Otherwise, if you let us know what text you want on it we are happy to create them for you.
