### ISSUE TITLE
Create mock-ups for AskYourGov homepage image

### ISSUE THREAD

**Issue by Gemmamysoc** [mysociety/alaveteli#3331]
I suggested to AskYourGov that a photo could be put on homepage banner and they seemed keen to try it. Could we create a couple of examples to help them?

**Comment by Gemmamysoc** [comment]
We'd need to check that adding an image wouldn't affect site's speed for users. Can do this via Analytics apparently.

**Comment by garethrees** [comment]
> We'd need to check that adding an image wouldn't affect site's speed for users. Can do this via Analytics apparently.

I think we can check the before and after. Behaviour > Site Speed > Page Timings > `/`

**Comment by garethrees** [comment]
Might be able to compare that against Audience > Technology > Network to specifically look at 3G connections, but that might be hard to figure out.

**Comment by zarino** [comment]
As I mentioned to @crowbot – it would be good to get access to their analytics, so we can check how much of an impact a big hero image on the homepage is likely to be.

Aside from that, I did a quick search for images of Uganda, here were a few concepts:

![screen shot 2016-06-28 at 10 10 52](https://cloud.githubusercontent.com/assets/739624/16410334/f81e56a4-3d19-11e6-839e-c98e0d59654b.png)

[(Photo of Merchison Falls, near Lake Victoria)](https://www.stocksy.com/576453)

![screen shot 2016-06-28 at 10 18 11](https://cloud.githubusercontent.com/assets/739624/16410337/fb942520-3d19-11e6-9fd5-1bd5828899fd.png)

[(Photo of rural Ugandan village)](https://www.stocksy.com/553927)

![screen shot 2016-06-28 at 10 22 47](https://cloud.githubusercontent.com/assets/739624/16410436/69d9b82e-3d1a-11e6-8b18-3297fa1f0d2f.png)

[(Photo of busy Kampala street)](http://www.shutterstock.com/pic-129730406)

![screen shot 2016-06-28 at 10 36 18](https://cloud.githubusercontent.com/assets/739624/16410846/443b6962-3d1c-11e6-9dcf-e4ab114628db.png)

[(Photo of Grey Crowned Crane, the national bird)](http://www.shutterstock.com/pic-153424112)

There are lots of other directions we could take this too. It depends what sort of feeling they're trying to evoke.

**Comment by garethrees** [comment]
Waiting on feedback

**Comment by Gemmamysoc** [comment]
Justus and the AskYourGov team prefer the Kampala street banner image.

**Comment by lizconlan** [comment]
going to leave this until we've got a bit more data in GA otherwise it's going to be hard to tell what sort of effect - if any - the change has made (thanks @garethrees for sorting the GA code changes!)

**Comment by zarino** [comment]
Pull request here with the Kampala street scene on the homepage: https://github.com/mysociety/askyourgovug-theme/pull/14

**Comment by Gemmamysoc** [comment]
Reopening this just to remind ourselves to check the affect of banner image on the site's speed in a few weeks.

**Comment by garethrees** [comment]
Doesn't look like any obvious change in Analytics, and PageSpeed test says "Your images are optimized.", so I think we're good.

**Comment by Gemmamysoc** [comment]
Have written to partners to inform them of findings

**Comment by garethrees** [comment]
They've replied and are happy
