### ISSUE TITLE
Add public note on request threads which are closed to further correspondence

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#3332]
From time to time the WhatDoTheyKnow team have to re-open a request thread to correspondence after it has been set to "Allow new responses from: nobody" due to a lack of activity. 

Typically this occurs after an appeal to the Information Commissioner, prompting correspondence many months later from the public body.  Currently such correspondence bounces, and if the public body reads the bounce message they write to us and ask us to re-open the thread. 

Perhaps a requestor, or anyone else following a thread, will be aware a further response is due and will be able to see closing it is not appropriate. If we were public about which threads were closed to new responses this would give people a chance to point out ones which shouldn't be and give the admin team a chance to re-open them before an attempt to send a further response was made. 

We don't know how many, if any, public bodies don't read a bounce message and perhaps don't re-try or use another route to supply the information to the requestor. 

The note on the request page could say eg. "This request has been closed to new correspondence from the public body. Contact us if you think it ought be re-opened".  With appropriate linking on the "Contact us if you think it ought be re-opened". 

It may be this affects so few threads it's not important. 

Would any/many requestors revisit their request pages unprompted to read any such message?

**Comment by RichardTaylor** [comment]
Another use-case would be for public bodies with experience of WhatDoTheyKnow seeking to pre-empt a bounce and wondering about the status of a request thread. WhatDoTheyKnow support just received the following:

>Based on past experience, it is possible that the thread has been closed as it has been inactive for some time.  The delay has been caused by the Tribunal appeal process, which is now complete.  I would be grateful if you would arrange for this request thread to be re-opened so that we can send information to it by 6.15pm today.

**Comment by lizconlan** [comment]
Closed via #4958
