### ISSUE TITLE
Plan how to research, redesign and test a redesign of the request page

### ISSUE THREAD

**Issue by wrightmartin** [mysociety/alaveteli#3336]
related to #3269

**Comment by wrightmartin** [comment]
# Notes from our call with the team to discuss this

## Suggested approach

1. Split the page into elements and set priority
2. Drop the low priority items completely
3. Design a new page
4. Decide if we implement the new design all at once, or piece meal
5. AB test the new page on a live site to determine success
6. Repeat 3-6 until we're happy

### Priority items
Non-exhaustive

#### Low priority things

- Write to your MP
- Donate
- AskTheEU
- Share/tweet/other social

####  High priority things

- Read the request
- Make a new request

#### Medium priority things

- Follow
- Report a request
- Similar request

####  Logged in actions

- Only show these to logged in users

### Testing
Use WDTK, or find a partner site which has enough usage to run a valid test

**Comment by garethrees** [comment]
Is this *the plan*? Can we consider this ticket done and continue tracking work on this in https://github.com/mysociety/alaveteli/issues/3269?

**Comment by wrightmartin** [comment]
> Is this the plan? Can we consider this ticket done and continue tracking work on this in #3269?

If we all agree, then yep!

**Comment by garethrees** [comment]
Worth noting that we've already made some of these decisions and started [discussing priority](https://github.com/mysociety/alaveteli/issues/3269#issuecomment-233596276).

> Split the page into elements and set priority

https://github.com/mysociety/alaveteli/issues/3269#issuecomment-233596276

> Design a new page

https://github.com/mysociety/alaveteli/issues/3269#issuecomment-233310573

> Decide if we implement the new design all at once, or piece meal
> AB test the new page on a live site to determine success

Not all at once. Probably a small element at a time in quick succession, with A/B tests on contentious items

**Comment by garethrees** [comment]
I think given how much progress has been made already that reviewing this is kind of redundant. Would be better for @lizconlan to jump in on individual tickets (e.g. https://github.com/mysociety/alaveteli/issues/3394 / https://github.com/mysociety/alaveteli/pull/3395)
