### ISSUE TITLE
Mail message attached to response not being shown properly

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#3338]
On WhatDoTheyKnow at:

https://www.whatdotheyknow.com/request/minutes_and_associated_papers_re#incoming-826330

A public body has included attachments with the type:

> Content-Type: message/rfc822
> Content-Disposition: attachment;

There appear also to be text versions of the attachments in question. WhatDoTheyKnow has only made the text versions available to view / download on the request thread. 

The mail messages in this case contained more information of interest to the requestor in the header than could be seen in the text versions.

In this case we should probably have been giving the user the option to download the attached message file. 

Mail App on Mac OSX deals with the response in question by showing "Mail Attachment.eml" as an attachment to the incoming message, and on opening that message there's another "Mail Attachment.eml" attachment containing another message within.

**Comment by RichardTaylor** [comment]
A further instance of this bug has occurred at

https://www.whatdotheyknow.com/request/revision_of_facebook_live_format

**Comment by WilliamWDTK** [comment]
A user has contacted us wanting to know the time of one of the emails attached to [this response](https://www.whatdotheyknow.com/request/emails_to_tobias_ellwood_mp_from#incoming-2713955), it would be useful if this were displayed.

**Comment by garethrees** [comment]
This is desirable, but unlikely to be worked on in the next 12 months so closing for now.
