### ISSUE TITLE
Handle the display of a large list of attachments better

### ISSUE THREAD

**Issue by wrightmartin** [mysociety/alaveteli#3347]
https://www.whatdotheyknow.com/request/credit_charge_debit_corporate_cr_13#incoming-824206

![screen shot 2016-06-24 at 12 13 46](https://cloud.githubusercontent.com/assets/2292925/16336408/2548309a-3a05-11e6-8a11-3b2960105c61.png)

**Comment by garethrees** [comment]
Maybe consider in https://github.com/mysociety/alaveteli/issues/3269

**Comment by garethrees** [comment]
Fixed in https://github.com/mysociety/alaveteli/pull/3408
