### ISSUE TITLE
Redesign request page

### ISSUE THREAD

**Issue by wrightmartin** [mysociety/alaveteli#3358]

**Comment by wrightmartin** [comment]
Related: #3336, #3269

**Comment by garethrees** [comment]
I think this is covered by https://github.com/mysociety/alaveteli/issues/3269?

**Comment by wrightmartin** [comment]
### Request page wireframe
![request page](https://cloud.githubusercontent.com/assets/2292925/16870851/98c66f10-4a7b-11e6-84df-476cfd7073ef.png)

### Action menus with various permissions
![action menus](https://cloud.githubusercontent.com/assets/2292925/16870852/98c75f6a-4a7b-11e6-8fcc-d0c0ecf92dfb.png)

### Request with attachments
![attachments](https://cloud.githubusercontent.com/assets/2292925/16870850/98c38764-4a7b-11e6-8b21-49ef2fbba730.png)

**Comment by garethrees** [comment]
Closing in favour of https://github.com/mysociety/alaveteli/issues/3269 – moved the wireframes across.
