### ISSUE TITLE
Improve documentation and promotion of feature allowing links to pre-formed draft requests

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#3378]
Documentation currently at:

https://www.whatdotheyknow.com/help/api
and
http://alaveteli.org/docs/developers/api/

is currently written for an audience of programmers. 

There are other potential users of pre-formed draft requests:
- anyone posting content to the web who wants to include a link to a pre-formed request, for example a blogger including a link in a post, or a journalist including one in an article. 
- users considering making lots of requests might create draft-request links to help them speed up their workflow.
- administrators of Alaveteli sites might want to create links to pre-formed requests to suggest requests to users.
- people might want to put a request form on their own site eg. campaign groups, or public bodies. 

Suggestions:
- Include an example link.
- Include a "get a link to a preformed request" tool.
- Include an example form, and a form generator tool.
- Mention if POSTing the data works, and if/how it needs to be encoded.
- Write the documentation targeting a wider audience
- Don't only document/promote the feature under the API heading

The documentation doesn't make clear a form like the following can be included on any site:

``` html
<form action="https://www.whatdotheyknow.com/new/liverpool_city_council">
<input type="text" name="title" value="Edit this title" />
<textarea name="default_letter">Enter text of request here...</textarea>
<input type="submit" />
</form>
```

**Comment by RichardTaylor** [comment]
Added the professional tag as if well presented and promoted this could be professional tool - journalists, campaigners and lobbying organisations might use it.

**Comment by Gemmamysoc** [comment]
Ah, so I opened a duplicate ticket for this over on Alaveteli repo: https://github.com/mysociety/alaveteli/issues/3616 after discussion on [this experiment idea](https://github.com/mysociety/alaveteli-experiments/issues/106). 

I have drafted something which can be used as documentation on alaveteli.org and WDTK Help pages, and could be its own blog post: https://docs.google.com/document/d/19s6Hhu94g1IJFBev3V-bSVEupsj0lOq0FrLcpVQOn5Y/edit 

Just waiting for @garethrees to explain some technical stuff. Any other comments on the draft?

**Comment by Gemmamysoc** [comment]
Guidance is published on mySociety blog here: https://www.mysociety.org/2016/12/19/alaveteli-for-campaigners-how-to-create-pre-written-requests-for-your-supporters/?refferer=mailnotify&uid=138 I opened a new ticket to add this to alaveteli.org [here](https://github.com/mysociety/alaveteli/issues/3652).
