### ISSUE TITLE
Proactive spam checking on comments

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#3380]
See https://www.whatdotheyknow.com/request/canteen_sheet as an example. It looks somewhat intelligent. Related to https://github.com/mysociety/alaveteli/issues/2958.
- [ ] See if we can find examples of existing spam to gauge the scale of the problem.
- [ ] See if we can extract patterns to add to the spam scorer (might want a specific `CommentSpamScorer` given the different content)
- [ ] Remove existing spam
- [ ] Add proactive spam checking to new comments

**Comment by garethrees** [comment]
We could close comments to everyone except the request owner (or maybe make them "moderated") after a period of inactivity.

**Comment by kingqueen3065** [comment]
It's a shame that the selfish actions of a few cause us to have to restrict functionality on the site. It's also a shame that they use up developer time and headspace which would be much better spent elsewhere. 
If there is any way of dealing with this without restricting annotations that would be better in my view. But maybe there isn't.

**Comment by garethrees** [comment]
Fixed by https://github.com/mysociety/alaveteli/commit/f717f49cfaa4df90f4997f38e4afdadf05a90bc4
