### ISSUE TITLE
Redesign profile pages

### ISSUE THREAD

**Issue by wrightmartin** [mysociety/alaveteli#3383]

**Comment by wrightmartin** [comment]
### Public profile page
![public profile](https://cloud.githubusercontent.com/assets/2292925/16870762/1a8c579a-4a7b-11e6-8a42-80094fdf349c.png)

### Your profile - following 
![your profile - following](https://cloud.githubusercontent.com/assets/2292925/16870764/1a8ee276-4a7b-11e6-8191-aeca94777e04.png)

### Your profile - contributions
![your profile - contributions](https://cloud.githubusercontent.com/assets/2292925/16870763/1a8ca9ca-4a7b-11e6-9d99-54f0d7071088.png)


### Editing your profile 

**Editing about you**
![editing about you](https://cloud.githubusercontent.com/assets/2292925/16870758/1a6d776c-4a7b-11e6-9fdb-3cb2a719514a.png)

**Editing social media**
![editing social media](https://cloud.githubusercontent.com/assets/2292925/16870759/1a8003aa-4a7b-11e6-8eea-fe397e2761b3.png)

**Blank slate design for users who aren't following anyone or anything**
![not following blank slate](https://cloud.githubusercontent.com/assets/2292925/16870760/1a899794-4a7b-11e6-9de2-09b723d24c9f.png)

**Hover states for uploading a photo**
![photo hover states](https://cloud.githubusercontent.com/assets/2292925/16870761/1a89c2aa-4a7b-11e6-9eb2-3c8cd22d10a5.png)

**Comment by garethrees** [comment]
https://github.com/mysociety/alaveteli/issues/1524. Closing this one has https://github.com/mysociety/alaveteli/issues/1524 has more linked tickets for context.
