### ISSUE TITLE
Broken unsubscribe link

### ISSUE THREAD

**Issue by kingqueen3065** [mysociety/alaveteli#3385]
I've got the following watch set up so I get emailed about it.

![ss 2016-07-15 at 09 18 10](https://cloud.githubusercontent.com/assets/11923618/16887403/bedfe950-4ad1-11e6-9e0a-c2462c1e2b61.png)

If I click the unsubscribe button, I get a 404

![ss 2016-07-15 at 09 19 57](https://cloud.githubusercontent.com/assets/11923618/16887432/f19e23c0-4ad1-11e6-8869-5e49774b92d5.png)

**Comment by garethrees** [comment]
Routing error maybe (POST > PUT)?
