### ISSUE TITLE
Test suite is really slow

### ISSUE THREAD

**Issue by henare** [mysociety/alaveteli#3431]
It takes over 8 minutes on my machine which is unreasonably long. I think we should aim to get it under 2 minutes.

**Comment by lizconlan** [comment]
need to get the Rails upgrade done first

**Comment by garethrees** [comment]
https://github.com/mysociety/alaveteli/issues/3969 & the newer required Ruby version is going to be the first thing to do here. I'm just going to close this until we're at at least got to https://github.com/mysociety/alaveteli/issues/3970.
