### ISSUE TITLE
Create more case studies of users of FOI/Alaveteli sites

### ISSUE THREAD

**Issue by Gemmamysoc** [mysociety/alaveteli#3464]
It would be nice to have more case studies that explain how using FOI/Alaveteli sites has helped a variety of different audiences. Types of users could be:
- Students
- Journalists
- Local campaigners
- Small business owners
- Anyone that has found information they obtained useful/beneficial to their lives

**Comment by garethrees** [comment]
Mentioned in catchup call with Open Australia.

**Comment by garethrees** [comment]
https://www.mysociety.org/2016/08/19/how-350-foi-requests-will-increase-the-chance-of-success-for-start-ups/ is a good example

**Comment by Gemmamysoc** [comment]
Myf is currently working on writing up an interview with a woman who used WDTK to find out how many UK schools contain asbestos, after her mum died of mesothelioma. It's a clear-cut example of doing good through FOI.

**Comment by Gemmamysoc** [comment]
'Freedom of Information and asbestos in schools', a case study about an individual who has used FOI for a campaign: https://www.mysociety.org/2016/12/07/freedom-of-information-and-asbestos-in-schools/

**Comment by Gemmamysoc** [comment]
'Standing up for erectile dysfunction care: a digital empowerment tool' - case study of how a campgining organisation has used WhatDoTheyKnow: https://www.mysociety.org/2016/12/16/standing-up-for-erectile-dysfunction-care-a-digital-empowerment-tool/

**Comment by Gemmamysoc** [comment]
'Detention Logs: using FOI to reveal the truth about immigration detention in Australia' - case study of how Detention Logs used RightToKnow: https://www.mysociety.org/2016/12/14/detention-logs-using-foi-to-reveal-the-truth-about-immigration-detention-in-australia/

**Comment by garethrees** [comment]
Case of MEPs using AskTheEU https://www.asktheeu.org/en/request/is_glyphosate_safe_we_have_the_r/new – Really interesting angle of the system using the system!

**Comment by garethrees** [comment]
Real user stories mentioned in https://github.com/mysociety/orgsites/issues/858#issuecomment-274745787 – may be able to repurpose them for general marketing.

**Comment by garethrees** [comment]
Related https://github.com/openaustralia/righttoknow/issues/671

**Comment by garethrees** [comment]
Closing as there's no "end" to this; we keep blogging about these as and when we can.
