### ISSUE TITLE
Add a way for users to find missing authority email addresses

### ISSUE THREAD

**Issue by henare** [mysociety/alaveteli#3477]
In the admin backend you can see authorities where we're missing an email but this isn't exposed in the frontend. I can see volunteers potentially helping find email addresses if there was something like the request categorisation game but for missing email addresses.

**Comment by garethrees** [comment]
Once done, create ticket for adding it to https://www.whatdotheyknow.com/help/volunteers

**Comment by RichardTaylor** [comment]
If implementing this authorities tagged defunct should be excluded. 

Ideally users would only get points in the game if admins accepted their suggestions. 

We'd want to encourage good quality suggestions with links to sources or other justifications. 

This isn't currently a big issue for WhatDoTheyKnow but the presence of this feature could change the way we operate - eg. we decided not to add large numbers of bodies we don't have email addresses for, but with this feature we could. 

WhatDoTheyKnow started with crowdsourced addresses on a shared GoogleSheets document, with this feature new sites could be started "on-site" rather than having to direct helpers to a spreadsheet.

**Comment by garethrees** [comment]
Linking to admin version of this issue https://github.com/mysociety/alaveteli/issues/6424.

**Comment by RichardTaylor** [comment]
>something like the request categorisation game but for missing email addresses.

The request classification game only has an overall target. 

It would be good to have more achievable per body / per category targets / reports for both an email finding "game" and the request classification game.

**Comment by garethrees** [comment]
A way of achieving this would be to use a tag and link to a tag-based search `/search/tag:missing_email/bodies`.

Would have to manually tag the bodies then remember to remove the tag once an address is accepted.

Would be quite easy to mass-apply the tag for current bodies missing an email:

```ruby
PublicBody.without_request_email.each { |b| b.add_tag_if_not_already_present('missing_email') }
```

Could hack something in the theme to automatically keep the tag up to date:

```ruby
class PublicBody
  after_save :update_missing_email_tag

  def update_missing_email_tag
    if missing_email?
      add_tag_if_not_already_present('missing_email')
    else
      remove_tag('missing_email')
    end
  end

  def missing_email?
    !has_request_email?
  end
```

**Comment by RichardTaylor** [comment]
Can we "follow success" and perhaps eg. improve 

https://www.whatdotheyknow.com/body/list/missing_email

* Can we mix up the results so different ones come to the top? 
* Can we gamify and do a leaderboard?  (Perhaps combining points with classification 'points')?
* Blog about the new feature 
* Use existing advance search features to offer more specific lists of bodies where we are missing an email eg. 
   * https://www.whatdotheyknow.com/search/tag:missing_email%20AND%20tag:parish_council/all
   * https://www.whatdotheyknow.com/search/tag:missing_email%20AND%20tag:dentist/all
   * https://www.whatdotheyknow.com/search/tag:missing_email%20AND%20tag:school/all 
* Add a note to the [relevant section of the volunteer page](https://www.whatdotheyknow.com/help/volunteers#general-tasks) linking permanently to https://www.whatdotheyknow.com/body/list/missing_email

Some of those ideas for improvement could be spun into their own tickets.

**Comment by RichardTaylor** [comment]
See: https://github.com/mysociety/whatdotheyknow-theme/issues/1124#issuecomment-1246612043

**Comment by RichardTaylor** [comment]
https://github.com/mysociety/whatdotheyknow-theme/issues/1402
