### ISSUE TITLE
Replace example of Spain on Getting Started guide on alaveteli.org

### ISSUE THREAD

**Issue by Gemmamysoc** [mysociety/alaveteli#3487]
Current copy on [this page](http://alaveteli.org/docs/getting_started/) highlights tuderechosaber.es as a best practice example. This site is no longer running, so we should use another example. I would suggest we link to http://kimittud.atlatszo.hu/ or https://dostup.pravda.com.ua/

**Comment by lizconlan** [comment]
Closed via #3511
