### ISSUE TITLE
"Replace existing tags with new ones" option when importing authorities via CSV doesn't work

### ISSUE THREAD

**Issue by equivalentideas** [mysociety/alaveteli#3491]
When importing authorities via CSV, 

When I add "testing" as an optional tag and select **“Add new tags to existing ones”** the dry runs results include:

```
line 2: creating new authority '26TEN' (locale: en):
    {"name":"26TEN","request_email":"email@26ten.tas.gov.au","notes":"26TEN is a network of organisations and individuals working together to improve adult literacy and numeracy in Tasmania.","home_page":"https://26ten.tas.gov.au/","tag_string":"TAS TAS_state testing "}
```

When I change the selection to **“Replace existing tags with new ones”** the result is:

```
line 2: creating new authority '26TEN' (locale: en):
    {"name":"26TEN","request_email":"email@26ten.tas.gov.au","notes":"26TEN is a network of organisations and individuals working together to improve adult literacy and numeracy in Tasmania.","home_page":"https://26ten.tas.gov.au/","tag_string":"TAS TAS_state testing"}
```

The existing tags aren't being removed from `tag_string`.

When you actually import, you can remove the existing tags. Am I miss understanding how this feature works maybe?

Does “existing tags” refer to tags on authorities that already exist in the database? or the tags on authorities in the csv file you’re importing?

**Comment by garethrees** [comment]
We've made some improvements to the inline docs in https://github.com/mysociety/alaveteli/commit/8136e016e5aa2cbb438a8274ef58171063ca251a that haven't made it in to master. Is the documented behaviour the same as you're experiencing?

**Comment by garethrees** [comment]
Closing as stale – assuming 8136e01 improved things a bit here.
