### ISSUE TITLE
URLs parsed in messages pick up any closing bracket

### ISSUE THREAD

**Issue by kingqueen3065** [mysociety/alaveteli#3493]
Where an authority sends a link within brackets, e.g. (http://www2.mmu.ac.uk/itservices/about-us/policies/), the URL parsing mechanism picks up the closing bracket as part of the URL, e.g. http://www2.mmu.ac.uk/itservices/about-us/policies/) 
A very minor bug as picked up in https://www.whatdotheyknow.com/request/telecoms_and_it_infrastructure_9#incoming-868404

**Comment by garethrees** [comment]
Related to https://github.com/mysociety/alaveteli/issues/3400

**Comment by garethrees** [comment]
Could be caused by https://github.com/mysociety/commonlib/pull/50

**Comment by garethrees** [comment]
(Just reassigning the ticket to @lizconlan – only the PR is intended for me I think :))
