### ISSUE TITLE
Check hosted sites for duplicate reCAPTCHA keys

### ISSUE THREAD

**Issue by lizconlan** [mysociety/alaveteli#3512]
Check the reCAPTCHA keys of all the sites we host to make sure they match the live domain. (The Liberian site has just been redeployed to fix this). Generate new keys and redeploy where necessary.

The same key being used in multiple configs is a bad sign. Visiting the site with a different IP address from the configured country code should result in a correctly displayed reCAPTCHA box on the sign up page if all is well, a visible "Invalid domain for site key" error if not.

**Comment by lizconlan** [comment]
I used TunnelBear on my phone to appear to be browsing from a different country where I needed to use a non UK IP address

**Comment by garethrees** [comment]
Duplicates are probably a sign that a key hasn't been configured with the correct domain (I think this may have come in with the latest recaptcha)

```sh
grep -r ^RECAPTCHA /data/servers/vhosts/alaveteli/
```

**Comment by lizconlan** [comment]
appears to affect:
 - [x] Italy (flagged up and fixed during retreat)
 - [x] Rwanda (although using old version so might not have impact)
 - [ ] Nicaragua (although using old version so might not have impact)
 - [ ] Macedonia

**Comment by lizconlan** [comment]
Done
