### ISSUE TITLE
Install script fails on trusty64

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#3516]
See https://groups.google.com/forum/#!topic/alaveteli-dev/vBI7D1zQHxs.

Have replicated and confirmed its failing with:

```
update-alternatives: error: no alternatives for ruby
```

Strangely, when you manually run the ruby version conditional, it doesn't try to change the default:

```
root@vagrant-ubuntu-trusty-64:/home/vagrant# ruby --version | grep -q 'ruby 1.9.3'
root@vagrant-ubuntu-trusty-64:/home/vagrant# echo $?
0
root@vagrant-ubuntu-trusty-64:/home/vagrant# if ruby --version | grep -q 'ruby 2.1.5' > /dev/null
> then
>   echo 'using ruby 2.1.5'
> elif ruby --version | grep -q 'ruby 1.9.3' > /dev/null
> then
>   echo 'using ruby 1.9.3'
> else
>   # Set ruby version to 1.9.1
>   update-alternatives --set ruby /usr/bin/ruby1.9.1
>   update-alternatives --set gem /usr/bin/gem1.9.1
> fi
using ruby 1.9.3
```

**Comment by lizconlan** [comment]
Ah, we're not yet supporting Trusty on master, only on the develop branch.

The checked out version of the script looks like this...

```
if ruby --version | grep -q 'ruby 2.1.5' > /dev/null
then
  echo 'using ruby 2.1.5'
else
  # Set ruby version to 1.9.1
  update-alternatives --set ruby /usr/bin/ruby1.9.1
  update-alternatives --set gem /usr/bin/gem1.9.1
fi
```

...so it's not doing the check for ruby 1.9.3 and is failing to run `update-alternatives`

**Comment by garethrees** [comment]
Ha, doh! Could you just reply to the mailing list saying as much? Cheers!

**Comment by lizconlan** [comment]
(done)

**Comment by lizconlan** [comment]
for the record (although without looking) I suspect it was me who prematurely updated the docs to suggest we had Trusty support
