### ISSUE TITLE
Righthand column on authority page looks odd when following

### ISSUE THREAD

**Issue by lizconlan** [mysociety/alaveteli#3541]
The single word "Following" appears, unstyled, under the list of options:

![screen shot 2016-10-14 at 16 20 32](https://cloud.githubusercontent.com/assets/27760/19394019/2d2069e0-922f-11e6-8d1e-44012a462061.png)

It is called from [`tracking/_tracking_links.html`](https://github.com/mysociety/alaveteli/blob/develop/app/views/track/_tracking_links.html.erb#L11) and the translatable string is drawn from [`models/track_thing.rb`](https://github.com/mysociety/alaveteli/blob/develop/app/models/track_thing.rb#L226).

This could affect other pages but it is noticeable that all other versions of `:verb_on_page_already` take a longer form, e.g. "You are already following this [person/request]", this is the only single word example.

**Comment by garethrees** [comment]
This doesn't happen any more, probably since we moved the follow button:

![screen shot 2018-07-30 at 13 13 18](https://user-images.githubusercontent.com/282788/43396748-6ce5e07c-93fa-11e8-9ec1-579338a5870e.png)
