### ISSUE TITLE
Add "personal information" to list of reasons admins can hide a request

### ISSUE THREAD

**Issue by henare** [mysociety/alaveteli#3543]
After years of using Alaveteli I just discovered that there's an option to hide requests in the admin backend. For all this time I've been manually editing the metadata when I wanted to hide a request!

![selection_001](https://cloud.githubusercontent.com/assets/48945/19423873/482ff960-9470-11e6-9d52-9015f8e64d37.png)

By far and away the most common reason we hide requests is because they are for, or contain, personal information. It would be great to get this option added to this screen.

**Comment by RichardTaylor** [comment]
I agree, this would be useful on WhatDoTheyKnow too.  Just to confuse matters though a "request for personal information" is a subset of "Not a valid FOI request" so I don't know if what's wanted is more classifications, or more templates for sending messages to the users concerned. 

The classification could be achieved by adding a request specific tag of eg "personal_information" 

On WhatDoTheyKnow we often edit that text to say eg. 

>We consider it is not a valid FOI request, it was correspondence about your personal circumstances, and we have therefore hidden it from other users. 

In cases where someone is trying to make a request for their own personal information we add advice on making a subject access request.

**Comment by RichardTaylor** [comment]
Added wdtk-team-priority after discussion on catch-up call.

**Comment by RichardTaylor** [comment]
Draft text for this feature has been proposed at:

https://github.com/mysociety/alaveteli/issues/881#issuecomment-132197263

**Comment by lizconlan** [comment]
Reopening so I can link it to the WDTK-specific version
