### ISSUE TITLE
Login 

### ISSUE THREAD

**Issue by samsmith** [mysociety/alaveteli#3553]
e.g. https://www.whatdotheyknow.com/profile/sign_in?r=%2F

if a username and single password is provided on the "signup" form, treat that as a login attempt rather than immediately throwing an error. 

Password managers will have saved the creation fields, and not the sign-in form fields, when providing correct values.

**Comment by garethrees** [comment]
The autofill form fields (in lastpass at least) are editable. I think the suggested behaviour would be pretty confusing and is not a common design pattern that users will be familiar with, so I don't think we'll do this. Thanks for the suggestion 😃

**Comment by samsmith** [comment]
> On 24 Oct 02016, at 14:54, Gareth Rees <notifications@github.com> wrote:
> 
> The autofill form fields (in lastpass at least) are editable. I think the suggested behaviour would be pretty confusing and is not a common design pattern that users will be familiar with, so I don't think we'll do this. Thanks for the suggestion 😃

it is something that only password managers which fill in the two fields would see, and if it doesn’t work as a valid login, then the site the normal error message. 

this is about making work something that otherwise wouldn’t, not changing anything that currently doesn't.
