### ISSUE TITLE
Allow admin interface in maintenance mode

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#3561]

**Comment by garethrees** [comment]
I think this will be tricky, because most of the time the app gets put in to maintenance mode because a deploy is happening. At this point we don't want to allow changes through the admin interface because of code and migration changes. I think the best plan is to have some example configuration commented out in the example web server config files so that we can implement it quickly on an as-needed basis.

**Comment by lizconlan** [comment]
yeah, maybe more a case of having some documentation about how to re-enable admin under exceptional circumstances

**Comment by garethrees** [comment]
Probably not going to ever do this.
