### ISSUE TITLE
Clean up any apache config from allowing admin interface access while site down

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#3568]
Related to https://github.com/mysociety/alaveteli/issues/3561

**Comment by garethrees** [comment]
I had a look in to this but I couldn't see where this change had been made, so I think it must have got blown away by a later deploy.

```sh
$ g admin /etc/apache2/apache2.conf
#ProxyPass /admin https://REDACTED/admin
$ g admin /etc/apache2/virtualhosts.d/www.whatdotheyknow.com.conf
# Large / static files for WhatDoTheyKnow. Used for manual sysadmin uploads.
$ sudo grep admin /REDACTED/alaveteli/config/httpd.conf
# so we do it on its own domain). This is for custom admin upload
$ sudo grep admin /REDACTED/alaveteli/config/httpd.conf.deployed
# so we do it on its own domain). This is for custom admin upload
```

@dracos which file did you add this override to out of interest? Might be good to add a commented example to our example files.

**Comment by dracos** [comment]
I edited `/etc/apache2/virtualhosts.d/www.whatdotheyknow.com.conf` (the live one, specifically so it would not last a redeploy) and changed the final down check to not match if the URL started with admin or profile using a negative look-ahead.
