### ISSUE TITLE
"This request has been hidden from the site" message shouldn't ever appear on published threads

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#3584]
Currently it is possible for a request to have a status of "not_foi" and a prominence of normal which prompts the

> "This request has been hidden from the site"

message to appear on published requests. 

Presumably this state of affairs arose as administrators made mistakes and manually changed the status without changing the prominence. 

29 requests on WhatDoTheyKnow are currently affected; which is a small enough number for manual correction by administrators.

**Comment by RichardTaylor** [comment]
Over the course of 2017 a further ~30 requests were marked not_foi by WhatDoTheyKnow administrators but their prominence was left such that the requests were public. Due to this again we had correspondence marked:  "This request has been hidden from the site" which was accessible to the public. 

It's not unreasonable for a new administrator seeing the text: "This request has been hidden from the site" appear on a thread to assume it's not publicly available.

Rather than have to warn new administrators about this bug when bringing the onboard - a time when there's lots to take in already. 

This bug poses a data protection risk due to unexpected behaviour confusing administrators about what is viewable by the public; and on those grounds I suggest it's reconsidered for prioritisation. I'm going to be bold and remove the backlog tag. 

Ideas for a fix:
* Giving an error message and refusing to "save" changes made on the admin page which leave the request published and with a described state of vexatious or not_foi
* Listing published requests which are published and have a described state of vexatious or not_foi  on the admin summary page. 

Just removing vexatious and not_foi from the "described state" options on the admin page is another idea but that might limit the ability of admins to make legitimate changes (though I can't immediately envisage when such a problem would occur).

**Comment by RichardTaylor** [comment]
>I'm going to be bold and remove the backlog tag.
Turns out I wasn't as bold as I thought I'd be in meddling with the prioritisation labels; but @crowbot has tagged this for reconsideration :-) 

From discussion via email administrators have noted that sometimes they want to hide a request and  set it as vexatious / not_foi without prompting the system to send an email to the user (perhaps the user has already been written to about a series of requests, or we don't want to write to them as they're vexatious or a spammer).  The fix for this issue should ideally keep this option available to administrators.

**Comment by RichardTaylor** [comment]
I just reviewed requests in this state on WhatDoTheyKnow and found four of them which I've now dealt with.

None of them had been newly put into an inappropriate state since January.

**Comment by lizconlan** [comment]
Having reproduced the problem locally, the main place this text is coming from (on the public part of the site) appears to be when `Request#show` template calls the `status_text` helper method which then calls the appropriate `status_text_` method (in this case `status_text_not_foi`)

Which suggests we may have a similar issue with `status_text_vexatious`.

Also need to check whether an admin is being incorrectly reassured that the request is hidden on the basis of the described state check alone.

**Comment by lizconlan** [comment]
### Clarification

When shown in a list (including search results), the message is from `InfoRequest.get_status_descriptions`

<img width="679" alt="screen shot 2018-07-19 at 10 02 44" src="https://user-images.githubusercontent.com/27760/42934990-6fed2216-8b40-11e8-8c4e-7f7262be0cc2.png">

When viewing the request page itself, it's from `status_text_not_foi` / `status_text_vexatious` (in the request helper)

<img width="851" alt="screen shot 2018-07-19 at 10 45 18" src="https://user-images.githubusercontent.com/27760/42935176-e080f034-8b40-11e8-9851-8130df84cd20.png">

**Comment by garethrees** [comment]
We've chatted about this and the next steps are:

* remove "has been hidden" from the status messages – there's always a separate prominence message anyway.
* Some tooltip on admin interface to remind admin to consider the prominence when selecting vexatious or not_foi statuses. This will _allow_ admins to set `not_foi` and `normal` when there's a case to do so (and non-uk admins may do this) but should give enough of a prompt that it doesn't happen.

**Comment by garethrees** [comment]
> Listing published requests which are published and have a described state of vexatious or not_foi on the admin summary page.

This would be better tackled by https://github.com/mysociety/alaveteli/issues/4740 and https://github.com/mysociety/alaveteli/issues/4741 so is out of scope for this issue.

**Comment by RichardTaylor** [comment]
I have just hidden three threads on WDTK which should have been hidden previously, but had just been marked not_foi rather than classified not_foi AND hidden. 

Other cases of published threads marked not_foi included a handful of misclassified requests, and three odd edge cases, two where correspondence which wasn't really FOI prompted the release of information anyway, and another which was an appeal to the Scottish Information Commissioner.
