### ISSUE TITLE
Closing authorities without marking them as "defunct" or "missing contact details"

### ISSUE THREAD

**Issue by kingqueen3065** [mysociety/alaveteli#3593]
There are times when we need to stop requests to an authority and direct people to another, but the original isn't defunct and we hold contact details. There isn't (AFAIK) a current option for this in Alaveteli.

The example that prompted this request: We list the House of Commons Administration Committee https://www.whatdotheyknow.com/body/house_of_commons_administration_committee and the House of Commons Commission https://www.whatdotheyknow.com/body/house_of_commons_commission separately from the House of Commons https://www.whatdotheyknow.com/body/house_of_commons, even though they are all in fact part of the House of Commons. 

We do this for historical practical reasons that are no longer relevant, and in fact all requests sent to any of those bodies now go to the same email address. However, sometimes requesters are sending the same request to each authority, apparently because they are under the impression that these are three separate authorities. This is sub-optimal and confusing for users.

The House of Commons have asked us to close the two committees on our system and redirect people to the House of Commons request page. But I can't close the committees because to do so, the only three options are to mark the committees Defunct (which they are not), missing contact details (which we are not) or to delete the authorities (which would interfere unacceptably with the archive of communications made on our website, even if we moved the existing requests to the House of Commons - particularly as there are duplicate requests.)

Suggestions or re-education welcome!

Doug

**Comment by RichardTaylor** [comment]
While this is a WhatDoTheyKnow administration matter I thought I'd add some background. One reason the House of Commons Commission is listed on WhatDoTheyKnow is [the House of Commons ceases to exist](https://www.whatdotheyknow.com/request/intranet_contents#incoming-79570) when it is dissolved the run up to a general election,[the Commission endures](http://www.publications.parliament.uk/pa/cm197879/cmacts/036/80036--c.htm#sch1), and listing the Commission enables our users to make requests to an extant body (albeit one not formally subject to Freedom of Information law) during such time.  

I think for a rare case it would be acceptable to just remove an email address from the Administration Committee's page and explain why we've done this in the notes.  (The background in this case is the House of Commons said they didn't hold some information but suggested the committee, separately, might, so we added it).

**Comment by RichardTaylor** [comment]
We have another case we're considering at the moment where a body used to be entirely publicly funded and we listed it on those grounds - it was at the time rather like a public body, but now over five years on it has a wide range of income sources and no-longer has much of the character of a public body - we wouldn't list it now, so should perhaps delist it while retaining the requests which were made to it.

**Comment by RichardTaylor** [comment]
Note from another WhatDoTheyKnow.com administrator:

>On marking defunct / removing email address: I agree that removing email address is better than marking [a body which is not defunct] as defunct. It would still be good to have a different solution from a technical point of view, because [...] they just end up on the admin page as one of the authorities for which we don't have a working email address, and I could see a well-meaning future new admin then simply "re-enabling" them by "finding" that "missing" email address.

**Comment by RichardTaylor** [comment]
We've had another occasion on WhatDoTheyKnow where this feature would have been useful. 

NHS England advised that requests for information held on their behalf by a contractor should be made directly to that contractor, so we listed the name that contractor was using in relation to the contract at:

https://www.whatdotheyknow.com/body/primary_care_support_england

NHS England have now appreciated they should have dealt with the request themselves, and taken responsibility for obtaining information from the contractor. 

We want to retain the history of what happened, but want to point future requestors to NHS England. 

We can do this reasonably well by removing the email address and adding an appropriate note, but ideally would use the feature proposed in this ticket.

**Comment by RichardTaylor** [comment]
It may be possible to "fix" this by changing the text of the alert/warning that people see when they try to make a request:

>"Unfortunately, we do not have a working Freedom of Information address for [Body Name]. You may be able to find one on their website, or by phoning them up and asking. If you manage to find one, then please send it to us. "

We could add to that explaining this may be a body we have decided to de-list and there will be an explanation on the body's page.

**Comment by RichardTaylor** [comment]
Just to note we have a not_apply tag which we appear to use for some bodies which used to be subject to FOI but no-longer meet our criteria for listing.

https://www.whatdotheyknow.com/body/list/not_apply

I don't think using this tag would resolve the issue, but I'm noting it as its closely related.

**Comment by garethrees** [comment]
> Marking NHSX defunct wasn't ideal, as it continued to exist, but not as a public body.

It sounds like what we've done here is technically correct and the edge case can be explained in the public body notes.

**Comment by HelenWDTK** [comment]
closing in favour of #8365
