### ISSUE TITLE
A specific email confirmation link doesn't work

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#3613]
There doesn't appear to be a general problem. 

The "Confirm your account on WhatDoTheyKnow" link sent to this user at 2016-11-13 21:17:51 doesn't work:

https://www.whatdotheyknow.com/admin/users/120171

Following it prompts the:

>Please check the URL (i.e. the long code of letters and numbers) is copied correctly from your email. 

error message. 

Following other newly created users' confirmation links signs them in and takes them to the home page.

**Comment by garethrees** [comment]
Not sure what happened here, but closing as it appears to have been an isolated case.

**Comment by RichardTaylor** [comment]
Another bit of unexpected behaviour from a confirmation link. 

I was logged into WDTK (as an admin and Pro user) and clicked on the confirmation link created for the user

https://www.whatdotheyknow.com/admin/users/136622

at 

 2017-06-19 15:34:58  

The system took me to a draft request on WDTK-pro while still logged in as me. The request data has become " 	--- {} " whereas it was a draft request. 

I followed this users's first confirmation link earlier and that request was sent successfully.  I'm not sure what, if anything, was different in that case.
