### ISSUE TITLE
Create a blog post about how to create pre-filled requests

### ISSUE THREAD

**Issue by Gemmamysoc** [mysociety/alaveteli#3616]
After thinking about [this experiment](https://github.com/mysociety/alaveteli-experiments/issues/106) I thought it would be useful to explain this tool more in non-technical terms, so it can be promoted better to campaigning organisations. 

Here are initial notes of chat with Gareth about how to use this: https://docs.google.com/document/d/19s6Hhu94g1IJFBev3V-bSVEupsj0lOq0FrLcpVQOn5Y/edit

**Comment by garethrees** [comment]
Related bug https://github.com/mysociety/alaveteli/issues/3615

**Comment by equivalentideas** [comment]
Dunno if this is helpful, but here's how we did it 3 years back https://github.com/DetentionLogs/detentionlogs/blob/Development/app/helpers/incidents_helper.rb#L6

**Comment by Gemmamysoc** [comment]
Write this once above bug has been fixed

**Comment by Gemmamysoc** [comment]
Draft post is here: https://docs.google.com/document/d/19s6Hhu94g1IJFBev3V-bSVEupsj0lOq0FrLcpVQOn5Y/edit#

**Comment by Gemmamysoc** [comment]
This has now been published: https://www.mysociety.org/2016/12/19/alaveteli-for-campaigners-how-to-create-pre-written-requests-for-your-supporters/
