### ISSUE TITLE
Ability to turn off annotations per user

### ISSUE THREAD

**Issue by kingqueen3065** [mysociety/alaveteli#3620]
It would sometimes be useful to be able to turn off the ability for a user to make annotations. 

This is particularly the case where the user makes reasonable use of our service for FOI requests, but continues to abuse the annotations system to send profanity, allegations etc.

**Comment by garethrees** [comment]
We already have `User#can_make_comments?` so we'd just need to add this as a database column and then consider that in the method:

```ruby
def can_make_comments?
  super && active? && !exceeded_limit?(:comments)
end
```

**Comment by garethrees** [comment]
This is desirable, but unlikely to be worked on in the next 12 months so closing for now.
