### ISSUE TITLE
Add link "report annotation / message as spam"

### ISSUE THREAD

**Issue by kingqueen3065** [mysociety/alaveteli#3645]
A user has suggested adding a button / link by which users can bring spam annotations to the attention of administrators. I think this would also be useful for request responses.

**Comment by garethrees** [comment]
Related to https://github.com/mysociety/alaveteli/issues/1479

**Comment by garethrees** [comment]
Add link to contact form – check that it adds last request visited

**Comment by garethrees** [comment]
Maybe use the "report for admin attention"?

**Comment by garethrees** [comment]
- Add "Report this [THING]" to each correspondence / comment bubble.
- Update items in dropdown box for bad comments / replies
- Use something to pre-select relevant dropdown from box
