### ISSUE TITLE
Duplicate the new action menu at the bottom of request pages

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#3648]
After reading a correspondence thread users have to scroll back up to the top to take actions such as replying to it. This suggestion is to duplicate the menu of options at the bottom of the correspondence thread as well as offering it at the top. 

See user feedback at:

https://github.com/mysociety/alaveteli/pull/3451#issuecomment-267313500

**Comment by garethrees** [comment]
Handling in https://github.com/mysociety/alaveteli/issues/3649
