### ISSUE TITLE
Request with subject "re" allowed through

### ISSUE THREAD

**Issue by kingqueen3065** [mysociety/alaveteli#3653]
Alaveteli's filtering that catches titles all in lower case etc. failed to prevent [this request](https://www.whatdotheyknow.com/request/re_31) from being sent with the title subject "re".

**Comment by lizconlan** [comment]
hmm, looks like the mixed case rule might only be applied where there's a space - that's probably not right

**Comment by lizconlan** [comment]
Some things possibly missed following conversation in standup. Need to consider whether we allow all caps acronyms (and dropping the min char length from 4 to 3) and - having had a look - something like "999 calls" should be allowed through despite technically not being mixed case

**Comment by lizconlan** [comment]
Also of note - these restrictions will only apply to new requests, previously valid requests should be fine
