### ISSUE TITLE
Using double quotes in the display name part of an email address breaks mail sending

### ISSUE THREAD

**Issue by lizconlan** [mysociety/alaveteli#3676]
Double quotes were added to the translation string used to create the address line[1] for one of the sites and it stopped new messages being sent. (This took us a while to work out as we updated the translations as part of a version upgrade and assumed that something in the code was broken, then we thought it might be something to do with UTF-8 handling which, for once, it wasn't.)

Left to its own devices, `InfoRequest#incoming_name_and_email` calls `MailHandler.address_from_name_and_email` which turns `"FOI request at \"Test Authority\" stuff"` into[2]

```rb
"\"FOI request at \\\"Test Authority\\\" stuff\""
````

(which doesn't work)

as `MailHandler.address_from_name_and_email` is one of ours, stripping out the extra escape characters is as "simple" as changing the last line as follows:

```diff
- address.to_s
+ address.to_s.delete('\\')
```

...which gets us...

```rb
"\"FOI request at \"Test Authority\" stuff\""
```

...which distressingly doesn't work either (although the entirely artificial `'"FOI request at "Test Authority" stuff'"` does). At this point I gave up and changed the translation file.

Oh and don't call `address.to_s` more than once (or call `.dup` on it) otherwise something odd happens and accented characters get turned into escape sequences e.g. "Autorità" becomes "Autorit\xC3\xA0" - no idea what's going on there so easiest just to avoid it[3].

It's possible this is related to https://github.com/mikel/mail/pull/1023 but I'm tired and can't be certain (note, we are running on mail 2.5.4 while we're still on Rails 3.2.x so maybe not).

[1] currently (for version 0.26.0.0 and up) `{{law_used}} requests at {{public_body}`
[2] the complete string is `"\"FOI request at \\\"Test Authority\\\" stuff\"<test@example.com>"` but as I only showed one part of what was  being passed in, the full string seemed unexpected but I've included here for clarity about where the string wrapping occurs
[3] appears to have been fixed in a later version of the mail gem

**Comment by garethrees** [comment]
Action: Add translator notes for this translation string

**Comment by garethrees** [comment]
For searchability, this is the exception that came through:

```
An ArgumentError occurred in request#new:

An SMTP To address is required to send a message. Set the message smtp_envelope_to, to, cc, or bcc address.
vendor/bundle/ruby/1.9.1/gems/mail-2.5.4/lib/mail/check_delivery_params.rb:9:in `check_delivery_params'
```

**Comment by lizconlan** [comment]
Added to transifex but should roll the one line change in the source file into a new hotfix along with the translation change for Italy which was originally only applied to the it_IT locale (seemed like a good idea at the time)

**Comment by lizconlan** [comment]
Translator notes added in hotfix/0.26.0.5 - `gettext:clean` tries to strip it out again tho so not ideal

**Comment by garethrees** [comment]
> `gettext:clean` tries to strip it out again tho so not ideal

I think this is because `#.` should be used for extracted comments as per the note in https://github.com/mysociety/alaveteli/commit/63055c520c48ec271b0e8d57352e683902824464#commitcomment-20572090. 

We should fix this properly as we run `gettext:clean` enough for this to become annoying and likely to get missed.

**Comment by garethrees** [comment]
Fixed by https://github.com/mysociety/alaveteli/pull/3717
