### ISSUE TITLE
OGP country research

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#3680]
- [x] List of OGP countries
- [x] Which don't have an Alaveteli or existing FOI platform?
---
- [ ] Look at their action plan
- [ ] Anecdotes about Alavetelis that we run in OGP countries

**Comment by Gemmamysoc** [comment]
Here's spreadsheet I'm working on: https://docs.google.com/spreadsheets/d/1ZrB7ss2x1kSuGa0KnhsTJFpEoT-o99u4pq6aEYn7l7M/edit

**Comment by Gemmamysoc** [comment]
18 of the 76 OGP countries have an Alaveteli instance currently = 23%
26 Alaveteli sites have existed ever (not all currently active) = 34%

**Comment by garethrees** [comment]
Duplicate of https://github.com/mysociety/alaveteli-project/issues/4
