### ISSUE TITLE
Make the list of who is following / supporting a request public

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#3701]
I'm noting this as a user suggestion, or user expectation, we've had few couple of times on WhatDoTheyKnow

There is a clear privacy question, we certainly shouldn't make the ID of current followers public (or accessible to requesters) perhaps we'd need distinct options:

i/ track/follow privately, 
ii/ publicly support and sign up for updates. 

To-date it appears to be requestors feel they ought to be allowed to see who has signed up to follow their requests. 

If a request had public "supporters" this could be used to prioritise what's shown prominently on the site.

**Comment by stevenday** [comment]
I think this is a dupe of or very similar to #3108?

**Comment by RichardTaylor** [comment]
Closing in favour of #3108
