### ISSUE TITLE
Expiry of /c/ auto-login links

### ISSUE THREAD

**Issue by kingqueen3065** [mysociety/alaveteli#3714]
A user attempted to use a /c/ link he'd been sent in an email on 13 November. He got this error message:
![ss 2017-02-04 at 06 01 10](https://cloud.githubusercontent.com/assets/11923618/22620439/1213e1e4-eb04-11e6-8120-1c50b5121727.png)
He suspects that the text is out of date and that such links actually now expire more quickly than within 6 months, and that the text could do with updating.

**Comment by lizconlan** [comment]
(it is now 2 months, change text accordingly)

**Comment by garethrees** [comment]
The code for reference https://github.com/mysociety/alaveteli/blob/b99fb8a/app/models/post_redirect.rb#L50
