### ISSUE TITLE
User menu for non-pro users is fragile

### ISSUE THREAD

**Issue by wrightmartin** [mysociety/alaveteli#3729]
![screen shot 2017-02-08 at 14 50 12](https://cloud.githubusercontent.com/assets/2292925/22742357/666c1b78-ee0e-11e6-9f06-9589f01512e2.png)

**Comment by garethrees** [comment]
Long emails overflow:

![screen shot 2017-02-09 at 12 37 27](https://cloud.githubusercontent.com/assets/282788/22783657/a9e5070a-eec4-11e6-8f99-249c806da6c2.png)

**Comment by garethrees** [comment]
Long names cause nav item to break, and overflow in the dropdown:

![screen shot 2017-02-09 at 12 39 03](https://cloud.githubusercontent.com/assets/282788/22783689/d1b8b236-eec4-11e6-88cf-bdc607d1070d.png)

**Comment by wrightmartin** [comment]
Thanks @garethrees, makes sense to fix all this at the same time 👍

**Comment by garethrees** [comment]
I think the quick fix here is to CSS truncate anything too long that fits, and maybe tweak the font sizes between name and email.

**Comment by wrightmartin** [comment]
<img width="392" alt="screen shot 2018-07-31 at 16 01 32" src="https://user-images.githubusercontent.com/2292925/43468091-094f7410-94db-11e8-81bc-8d908c3f0962.png">

Looks like I already fixed the layout issues

**Comment by garethrees** [comment]
I think this has been closed by https://github.com/mysociety/alaveteli/pull/4763, but that fix introduced  https://github.com/mysociety/alaveteli/issues/4780.
