### ISSUE TITLE
Vagrant documentation missing password for Joe Admin

### ISSUE THREAD

**Issue by gorm** [mysociety/alaveteli#3742]
"What next?

The Vagrant installation you’ve just done has loaded test data, which includes an administrator account (Joe Admin). If you just want to dive straight into customisation, every new Alaveteli site needs its own theme."

Should probably include the password?
And the username joe@localhost

**Comment by garethrees** [comment]
Good spot – If you haven't found it already, its in the comment in the [`users.yml` fixtures](https://github.com/mysociety/alaveteli/blob/develop/spec/fixtures/users.yml#L72).
