### ISSUE TITLE
latest_status search results include requests 'awaiting classification'

### ISSUE THREAD

**Issue by equivalentideas** [mysociety/alaveteli#3751]
The [explanation of advanced search](https://www.whatdotheyknow.com/advancedsearch) says “latest_status:not_held will match only requests that are currently marked as not held.”

But when you search for requests with `latest_status:successful` https://www.whatdotheyknow.com/search/latest_status:successful

You get requests in the results that are 'awaiting classification' in addition to the results you expect.

![screen shot 2017-02-15 at 4 41 04 pm](https://cloud.githubusercontent.com/assets/1239550/22961902/92c7f216-f39d-11e6-9b74-bfd315b4cc8c.png)

**Comment by garethrees** [comment]
I think this is a dup (or similar enough) of https://github.com/mysociety/alaveteli/issues/2904

**Comment by equivalentideas** [comment]
> I think this is a dup (or similar enough) of #2904

Agreed 👍 Thanks @garethrees
