### ISSUE TITLE
Improvements to the research_export task

### ISSUE THREAD

**Issue by lizconlan** [mysociety/alaveteli#3801]
- [x] make sure info request batch body is censored - the body property here is being imported without running through the censor lambda.
- [x] the full body name is missing from public body export, only returning short name and url

**Comment by lizconlan** [comment]
Note to estimator (probably me) allow extra time for this to include running it against WDTK data which will take longer than fixing the code

**Comment by ajparsons** [comment]
What might be useful in terms of future tweaks is something to limit the tables it exports - even just a switch to avoid the BIG message tables.

**Comment by garethrees** [comment]
> make sure info request batch body is censored - the body property here is being imported without running through the censor lambda.

I think we should have a review of censor rules and how they're applied. TL;DR is basically we should be doing https://github.com/mysociety/alaveteli/issues/3723 for everything.

**Comment by garethrees** [comment]
Rerun after this and https://github.com/mysociety/alaveteli/issues/3803 have been merged

**Comment by lizconlan** [comment]
> What might be useful in terms of future tweaks is something to limit the tables it exports - even just a switch to avoid the BIG message tables.

Done in https://github.com/mysociety/alaveteli/pull/3780

**Comment by lizconlan** [comment]
Oh, InfoRequestBatch.body appears not have apply text_masks - maybe we shouldn't be returning that
