### ISSUE TITLE
Install script results in "printed" version of site

### ISSUE THREAD

**Issue by gavinrozzi** [mysociety/alaveteli#3825]
In my attempt to set up a local Alaveteli site for my area, I have run across an issue with the current version's install script, after being able to use previous versions of the script without issue.

The issue I have been experiencing is that following a successful run of the install script, the home page of the site appears to be stuck in "printed" mode as if it were a document obtained from a public records request. As the screenshot will show, this results in the site being unusable. I have followed all instructions in the install guide and am on a supported platform, yet this continues to happen.

I have duplicated this on both a commercially purchased VPS server (using my own domain) running a fresh install of Debian 7 as well as now on a local VirtualBox instance (using a xip.io name), where I reached the same result following a successful run of the Alaveteli install script. Here is the log from the install script: [install log.txt](https://github.com/mysociety/alaveteli/files/842393/install.log.txt)

I have also attached a screenshot that shows the end result:
![alaveteliproblem](https://cloud.githubusercontent.com/assets/24501680/23917461/ca82c126-08c5-11e7-87dd-c756df8ddaa6.jpg)

**Comment by garethrees** [comment]
Hey @gavinrozzi.

This is a bit of an existing issue with the install script https://github.com/mysociety/alaveteli/issues/3850.

To install in production mode, you can make the [following tweaks](https://github.com/mysociety/alaveteli-production-vm/blob/master/Vagrantfile#L93-L103):

```
sed -r -i -e "s,^( *STAGING_SITE:).*,\\1 '0'," /var/www/alaveteli/alaveteli/config/general.yml
sed -r -i -e "s,^( *RAILS_ENV=).*,\\1production," /etc/init.d/alaveteli
sudo -u alaveteli echo "ENV['RAILS_ENV'] ||= 'production'" > /var/www/alaveteli/alaveteli/config/rails_env.rb
```

You'll then need to re-run the install script with the same arguments so that the production settings are applied.

Let us know if that works for you.

**Comment by gavinrozzi** [comment]
Thanks Gareth, I will give this a try tonight and let you know how this goes.

**Comment by garethrees** [comment]
Just closing the ticket as its covered by existing tickets. Feel free to reopen if you're still having a problem or the [above](https://github.com/mysociety/alaveteli/issues/3825#issuecomment-288433141) doesn't fix your issue. Cheers!
