### ISSUE TITLE
Change text of "Send" button to "Send and Publish"

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#3842]
Despite the clear notices we still have users not realising their correspondence is being published; leading in some cases to users publishing their own and others' personal information without intending to. 

Perhaps putting the word "publish" on the button they have to click when sending a request / follow-up / reply might reduce the instance of accidental inappropriate use of the service?

**Comment by garethrees** [comment]
+1

I was just thinking that we could make the "publish" aspect even bolder still for first time users somehow.
