### ISSUE TITLE
Reorganise the Alaveteli Experiments ReadMe

### ISSUE THREAD

**Issue by Gemmamysoc** [mysociety/alaveteli#3862]
I'm going to be presenting at TICTeC about our Alaveteli experiments. I'd like to show people the [experiment repo](https://github.com/mysociety/alaveteli-experiments), but it would be better if our results were split up into Acquisition, Engagement and Retention sections, so it's easier to decipher.

**Comment by Gemmamysoc** [comment]
Deadline for reorganising: 24th April

**Comment by garethrees** [comment]
Done in https://github.com/mysociety/alaveteli-experiments/pull/114
