### ISSUE TITLE
Incorrect error when attempting to "write a reply" as the wrong user

### ISSUE THREAD

**Issue by kingqueen3065** [mysociety/alaveteli#3869]
If I attempt to "write a reply" to a request made on somebody else's account I used to get a message "Sorry, only Mr X is allowed to do that" but now I get a 404.

**Comment by garethrees** [comment]
I suspect this is down to the new request scopes so that the existince of embargoed requests is not leaked. This is consistent with other sites' behaviour (e.g. https://github.com/rails/rails/settings 404s) so I think this behaviour is okay.
