### ISSUE TITLE
stats_by_domain incorrect counts

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#3892]
```
$ bundle exec rake users:ban_by_domain DOMAIN="webgarden.com"
"total users: 375"
"   banned %: 303 (81%)"
"  dormant %: 374 (100%)"
""
"Do you want to ban all the non-admin users for webgarden.com(y/N)"
y
"72 accounts banned"
```

Total users says 375, but 374 (100%) dormant.

When I banned all dormant users, I was expecting 71 banned (374-303) but got 72.

Don't know if this is related to https://github.com/mysociety/alaveteli/issues/3749.

**Comment by garethrees** [comment]
The problem here is that 1 user had transactions, so 100% dormant is not correct.

**Comment by lizconlan** [comment]
suggest rounding percentage to 2 decimal places which would have shown in this case 99.75%

**Comment by garethrees** [comment]
Q: What transactions did the non-dormant user have?

**Comment by garethrees** [comment]
The user had 1 track thing where they'd followed themselves.

TODO:

- [ ] rounding percentage to 2 decimal places
- [ ] Change ban text to "Banned for spamming"
