### ISSUE TITLE
Update Travis CI config for Precise EOL

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#3928]
https://blog.travis-ci.com/2017-04-17-precise-EOL

**Comment by garethrees** [comment]
- specify dist: trusty directly in your .travis.yml file; see if it works
- IF so, maybe remove precise from `Vagrantfile`

**Comment by lizconlan** [comment]
It works! The only gotcha is that without changes to Gemfile.lock, the WAD file is invalid as certain gems (charlock-holmes hits first, there may be others) need to be recompiled against the newer libraries packaged for Trusty. I've worked around it on the test branch by temporarily disabling use of the WAD file, if we want to deploy it for real we should alter Gemfile.lock or remove the WAD file from the Amazon bucket instead.
