### ISSUE TITLE
Capitalisation enforcement on FOI subjects not functional

### ISSUE THREAD

**Issue by kingqueen3065** [mysociety/alaveteli#3940]
A user has managed to create a FOI request with the title of simply "ves" - something that previously would not be possible.

**Comment by lizconlan** [comment]
this _should_ have been fixed in 0.27.1.0 - @kingqueen3065 is this a request that was created recently or one from before February?

**Comment by lizconlan** [comment]
(expected behaviour - "ves" not allowed "VES" allowed)

**Comment by lizconlan** [comment]
Closing this as I think it's working as expected for new requests. Please reopen if it reoccurs.

**Comment by kingqueen3065** [comment]
@lizconlan 
sorry for not getting ack to you on your query - life's overtaking me a bit. thanks for sorting it.

**Comment by lizconlan** [comment]
@kingqueen3065 heh, no problem - didn't think it was worth bugging you for an answer! (FWIW, looks to me as though the "ves" request was made last year but resurfaced because of a response)
