### ISSUE TITLE
Add "Request new authority" link to the Authorities page

### ISSUE THREAD

**Issue by kingqueen3065** [mysociety/alaveteli#3941]
I'd suggest a link from the [list of authorities](https://www.whatdotheyknow.com/body/list/all) to the [form to request an authority](https://www.whatdotheyknow.com/change_request/new) be added (which as far as I am aware is only in the [middle of the help section](https://www.whatdotheyknow.com/help/requesting#missing_body).)

**Comment by garethrees** [comment]
Hey Doug,

There are actually two links to the help section from the list of authorities page:

- One in the sidebar
- One at the end of the search results

I've added the border to separate out the categories from the extra links in the sidebar in #3964, so hopefully that will make it a bit clearer.

I think directing users to the help section is best for now, as it includes a reasonably obvious link to the form, and adds some information about what to do.

![screen shot 2017-05-08 at 17 41 14](https://cloud.githubusercontent.com/assets/282788/25814588/f8e1679a-3415-11e7-99ad-34d158b26565.png)
