### ISSUE TITLE
Re-sending a request doesn't re-open it.

### ISSUE THREAD

**Issue by kingqueen3065** [mysociety/alaveteli#3955]
Re https://www.whatdotheyknow.com/request/security_services_enquiry_52: when I re-sent the request, I didn't notice that it was still "Allow new responses from: authority only" so when the authority responded it bounced. It would be great if requests were automatically re-opened when a message is re-sent.

**Comment by MattK1234** [comment]
Closing this as upon testing this afternoon I see that resending requests does now reopen the request.

Tested with `Allow new responses from = authority_only` on the request at https://www.whatdotheyknow.com/request/comms_with_miller_home_re_kingsw

Tested with `Allow new responses from = nobody` on the request at https://www.whatdotheyknow.com/request/test_request_4

In both cases after resending I see `Allow new responses from = anybody`, therefore this issue appears to have been resolved.

**Comment by garethrees** [comment]
Just had a nose around and found that indeed this was fixed in https://github.com/mysociety/alaveteli/pull/5012.
