### ISSUE TITLE
New authority censor rules are not applied to existing responses

### ISSUE THREAD

**Issue by lizconlan** [mysociety/alaveteli#3959]
If you add a censor rule to an authority after a response has been published, the intended redaction only applies to the correspondence header until the message cache (e.g. `cached_main_body_text_unfolded`) is cleared.

The censor rule intention was to replace the last name of the sender.

![screen shot 2017-05-05 at 17 56 58](https://cloud.githubusercontent.com/assets/27760/25756145/94524948-31bd-11e7-87c4-65c9e26c9d5d.png)

(May be looking in the wrong place but I can't see how an admin can fix this)

**Comment by lizconlan** [comment]
Related to #1156

**Comment by garethrees** [comment]
Needs to follow the existing pattern and expire requests https://github.com/mysociety/alaveteli/blob/develop/app/controllers/admin_censor_rule_controller.rb#L102-L106

Note that `PublicBody` doesn't have `#expire_requests`, but it does have `purge_in_cache` so worth checking the differences there and seeing whether we can unify these methods a bit.

**Comment by lizconlan** [comment]
`purge_in_cache` is for the Varnish cache, `expire_requests` calls  `User`s `.expire_requests` calls `.expire` on each request which clears the database caches, cache files and the download zip directory (then calls `purge_in_cache`). I think `PublicBody` probably needs its own version

**Comment by garethrees** [comment]
Reopening as the existing requests with body censor rules need to get recached.

```ruby
CensorRule.where('public_body_id IS NOT NULL').each do |rule|
  rule.public_body.info_requests.find_in_batches(batch_size: 100) do |group|
    group.each do |info_request|
      info_request.clear_in_database_caches!
      puts "Cleared InfoRequest: #{ info_request.id }"
    end
  end
end
```

**Comment by garethrees** [comment]
Requests with public body censor rules have been expired.
