### ISSUE TITLE
HTML version of PDF very broken

### ISSUE THREAD

**Issue by kingqueen3065** [mysociety/alaveteli#3972]
I suspect a MIME type issue.

https://www.whatdotheyknow.com/request/402029/response/976640/attach/html/3/9499%20Final%20Response.pdf.html

![ss 2017-05-10 at 09 28 10](https://cloud.githubusercontent.com/assets/11923618/25919765/a25f8f24-35c7-11e7-9a62-dbc19921a335.png)

**Comment by garethrees** [comment]
Likely related to/caused by https://github.com/mysociety/alaveteli/commit/0dd537e4e6a77d1d54a5457dc17efb3a62209a8a

**Comment by lizconlan** [comment]
This has been deployed but the file cache will need clearing for affected requests for it to take effect (I've manually cleared the one in the description)

**Comment by garethrees** [comment]
Thanks for rolling out the fix!

> This has been deployed but the file cache will need clearing for affected requests for to fix the output of anything that's already been viewed

Have we done this?

**Comment by garethrees** [comment]
From email:

> That's been done although, as noted on the ticket, there may be other requests affected (unless we want to blow all the file caches to be sure). Great news that the fix works

So no, we still need to clear file caches of affected attachments. Reopening so that this can get completed.

**Comment by garethrees** [comment]
Cleared caches of last 31 days worth of attachments.

```sh
sudo su - APP_USER
cd /path/to/app/root
find cache/views/request -name "*.html" -type f -mtime -31 -exec rm -v {} \;
```

Was trying to clear between bug deployment and bugfix dates, but couldn't get it to work quickly, so just went with clearing the whole lot.
