### ISSUE TITLE
This request is hidden until XY - does not change

### ISSUE THREAD

**Issue by michalskop** [mysociety/alaveteli#3985]
The text "this request is hidden until XY" (loosely translated, having Czech interface) does not change when changing to (e.g.) "publish immediately) at /alaveteli_pro/info_requests/new
and still shows the default date (after 3 months), which is a bit misleading.
(e.g., http://www.infoprovsechny.cz/alaveteli_pro/info_requests/new )

**Comment by garethrees** [comment]
This works as expected now:

![Screenshot 2020-09-22 at 10 43 06](https://user-images.githubusercontent.com/282788/93867067-711f0480-fcc0-11ea-806f-884abb366c72.png)

![Screenshot 2020-09-22 at 10 43 09](https://user-images.githubusercontent.com/282788/93867073-73815e80-fcc0-11ea-8ab3-677adc680c59.png)
