### ISSUE TITLE
"Was clarification request" button does not work

### ISSUE THREAD

**Issue by mbimmler** [mysociety/alaveteli#4001]
The "was clarification request" button that administrators can click in the admin panel for incoming messages (responses) in a request does not currently appear to be work.

Example: 
In
https://www.whatdotheyknow.com/admin/requests/394699
I marked the latest response (Event 2362174 / incoming_message_id: 977491) as "was clarification request" in the admin interface, so as to reset the time clock, as the user had subsequenly sent in a new request by way of reply (event 2366467, outgoing_message_id: 650068).

However, rather than "resetting the clock" and starting to count the 20 working days again from the user's latest message, the request remains in status "waiting_response_very_overdue".  Thus, it is shown as "very overdue" which the authority is not very happy about, as they are still well within the 20 working days to respond to the fresh request of 16 May.

**Comment by lizconlan** [comment]
Thanks @mbimmler!

I _think_ what this might be doing is setting the clarifying followup to act as the initial request **but** not resetting the timestamps that are used in the overdue calculations.

**Comment by lizconlan** [comment]
setting this aside for further discussion when everyone's back rather than risking doing the wrong thing

**Comment by garethrees** [comment]
Just for reference there was some discussion about this in "Alaveteli handling follow-up requests made in same thread" to volunteers@

**Comment by garethrees** [comment]
Fixed by #4036
