### ISSUE TITLE
Escaping of email addresses

### ISSUE THREAD

**Issue by kingqueen3065** [mysociety/alaveteli#4013]
This message https://www.whatdotheyknow.com/request/is_the_servelec_corelogic_it_sys#outgoing-650447 isn't getting through to the authority because a system automatically escapes the email address. 

`FOI N&C <FOI-N&C@warrington.gov.uk>` gets converted to `FOI-N\&C@warrington.gov.uk` .

I am not certain whether this is due to Alaveteli or due to the authority's server. Apologies if this is their problem and not ours.

**Comment by lizconlan** [comment]
Looks like an interesting new variation of #3465

**Comment by lizconlan** [comment]
ToDo: add annotation and tidy up the mess a bit

**Comment by lizconlan** [comment]
Closed in favour of #3465

**Comment by kingqueen3065** [comment]
Thank you, @lizconlan
