### ISSUE TITLE
Long pre-filled requests causing 502 errors

### ISSUE THREAD

**Issue by lizconlan** [mysociety/alaveteli#4016]
From support email:

>There seems to be a limit to the number of words or
characters that will be accepted. Too many and you are taken to a page
showing 502 Bad Gateway. However through trial and error I worked out
a rough character limit (around 2558) that would be accepted. When I
tried to edit and then over write the previous request, changing the
link, it was no longer accepted and took me to the Bad Gateway page.
I've edited down so that I am well below the 2558 'limit' previously
identified but it is still not accepted.

**Comment by lizconlan** [comment]
Appears to be Nginx complaining about the header size:

`2017/05/06 11:01:45 [error] [...] upstream sent too big header while reading response header from upstream, [...] request: "GET /new/aberdeenshire_council?title=[...]&default_letter[...]`

**Comment by lizconlan** [comment]
(May have been fixed by recent config change)

**Comment by garethrees** [comment]
Subject lines of interest:

- "Creating pro forma requests and links via whatdotheyknow" to volunteers@
- "WDTK user getting 502 errors - preformed requests API" to dev@

**Comment by garethrees** [comment]
> (May have been fixed by recent config change)

See https://github.com/mysociety/alaveteli/issues/3922

**Comment by lizconlan** [comment]
Seems to be working post the Nginx change for #3922 \o/
