### ISSUE TITLE
"Hidden" incoming correspondence text is hitting bounding box

### ISSUE THREAD

**Issue by lizconlan** [mysociety/alaveteli#4018]
CSS/layout tweak required to add some padding

![screen shot 2017-06-01 at 16 56 10](https://cloud.githubusercontent.com/assets/27760/26688699/5025be38-46eb-11e7-9302-14920a7098a5.png)

**Comment by garethrees** [comment]
> Not sure whether this is a core thing, an alavetelitheme thing, or a whatdotheyknowtheme thing – so feel free to move to a different repo if required!

Its in core:

![screen shot 2017-12-01 at 11 01 44](https://user-images.githubusercontent.com/282788/33479973-09bce6f2-d687-11e7-94c8-943e0ed2e543.png)

> Looks like `.hidden_message` is missing the `padding: 1.2em` that `.correspondence_text` gets.

Via https://github.com/mysociety/alaveteli/issues/4407

**Comment by garethrees** [comment]
Fixed by https://github.com/mysociety/alaveteli/pull/4735
