### ISSUE TITLE
Searches returning 504

### ISSUE THREAD

**Issue by kingqueen3065** [mysociety/alaveteli#4027]
Google's search console https://www.google.com/webmasters/tools/crawl-errors?hl=en&siteUrl=https%3A%2F%2Fwww.whatdotheyknow.com%2F reveals that searches on WhatDoTheyKnow are frequently returning 504s.

![ss 2017-06-06 at 07 10 27](https://user-images.githubusercontent.com/11923618/26844596-dd5b1de4-4aeb-11e7-909f-27a667c3510a.png)

**Comment by garethrees** [comment]
This is basically https://github.com/mysociety/alaveteli/issues/2137, so going to close it as a dup.

Also linking to https://github.com/mysociety/alaveteli/issues/1179, as we'll tackle search in general at some point.

Thanks for reporting – the search console looks like its been quite a useful tool already!

**Comment by kingqueen3065** [comment]
The main benefit of the search console is that it looks like it provides a better and more reliable mechanism for asking Google to expedite recrawling / refreshing the cache on individual pages. The "anybody report" mechanism seems to not be working particularly well on Google these last few months. This appears to be more useful and proactive, which is a benefit. 
The other stuff is just incidental, I guess.
