### ISSUE TITLE
Problem loading assets after install script install

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#4061]
See https://groups.google.com/forum/#!topic/alaveteli-dev/egHOUi8CVIA

![gqt9p9dar1ejnhf](https://user-images.githubusercontent.com/282788/27426136-9c0873fc-5732-11e7-93bb-1c6e87886036.jpeg)

Solution was:

```
# Allow browser asset caching
# location ~* ^/(assets).*\.(ico|gif|jpe?g|png|js|css|svg|ttf|otf|eot|woff)$ {
#   expires 1y;
# }
```

Might be related to https://github.com/mysociety/alaveteli/issues/2392.

**Comment by schlos** [comment]
Hi Gareth,
I did check for #2392, result is as follows:

cat /etc/init.d/alaveteli | grep RAILS_ENV
RAILS_ENV=production
    --environment=$RAILS_ENV \

Cheers,
Miroslav

**Comment by shaundewberry** [comment]
Hit same issue with Dev install from script - Debian 9. 
After removing asset caching in nginx config, a restart to both nginx and alaveteli service was required.
