### ISSUE TITLE
Unrendered HTML when unfollowing somebody

### ISSUE THREAD

**Issue by kingqueen3065** [mysociety/alaveteli#4062]
![ss 2017-06-23 at 12 58 48](https://user-images.githubusercontent.com/11923618/27460965-55c64a36-57af-11e7-9372-509a360f89cf.png)

**Comment by garethrees** [comment]
Thanks for reporting. We've got a [fix ready](https://github.com/mysociety/alaveteli/pull/4051) for following / already following, but unfollowing is a bit trickier for various reasons. Closing as a dup of https://github.com/mysociety/alaveteli/issues/3978.
