### ISSUE TITLE
[ERROR] [www.whatdotheyknow.com] user#signin (NoMethodError) "undefined method `[]' for nil:NilClass"

### ISSUE THREAD

**Issue by stevenday** [mysociety/alaveteli#4068]
```
A NoMethodError occurred in user#signin:

  undefined method `[]' for nil:NilClass
  lib/alaveteli_pro/post_redirect_handler.rb:15:in `override_post_redirect_for_pro'

-------------------------------
Request:
-------------------------------

  * URL        : https://www.whatdotheyknow.com/profile/sign_in
  * HTTP Method: POST
  * IP address : FILTERED
  * Parameters : {"utf8"=>"✓", "authenticity_token"=>"", "user_signin"=>{"email"=>"peter.g.yeung@[GMAIL]", "password"=>"[FILTERED]"}, "token"=>"FILTERED", "modal"=>"", "commit"=>"Sign in", "controller"=>"user", "action"=>"signin"}
  * Timestamp  : 2017-06-27 13:11:46 +0100
  * Server : FILTERED
  * Rails root : /FILTERED/www.whatdotheyknow.com/alaveteli-2017-06-21T12-52-52
  * Process: FILTERED

-------------------------------
Backtrace:
-------------------------------

  lib/alaveteli_pro/post_redirect_handler.rb:15:in `override_post_redirect_for_pro'
  app/controllers/application_controller.rb:338:in `do_post_redirect'
  app/controllers/user_controller.rb:130:in `signin'
  app/controllers/application_controller.rb:108:in `record_memory'
  lib/strip_empty_sessions.rb:13:in `call'
```

**Comment by stevenday** [comment]
I think what's happened here is that the user has created a new account, I've promoted it to pro and then they've written a request before confirming their account, and so the post redirect created for them is to confirm their account (and then go to /new) rather than to create the request.

I'm not exactly sure where in the controllers this is happening though, because it *seems* like the code should just update the existing post redirect, which would keep the details. Perhaps it is, but we lose the post_params along the way somewhere?

**Comment by garethrees** [comment]
`authenticity_token` is blank, so that might have caused a problem

**Comment by stevenday** [comment]
Hmm, I've pushed a spec to test my theory in https://github.com/mysociety/alaveteli/commit/e68edc4f869435bdc337ee5f63b0e20edcfc2541 but that doesn't seem to be an issue because the spec works fine.

Looking back through the logs some more, there's some weird stuff going on with this user's access - almost as if they're not allowing cookies to be set perhaps? 

I see tons of `PostRedirect`s happening in the minutes leading up to this issue which I think are coming from the pro request form, where every autocomplete request results in another request to `profile/sign_in`, before eventually the user visits the non-js version instead (I guess they hit the search button perhaps because the js wasn't returning results?) then there's some more autocompletes from there which don't get post-redirects (because that form doesn't check you're authenticated), then they finally end up on the `/new` form (again presumably because they're not logged in) where they start the request writing process that led to this error.

I think it might be quicker to reach out the user and see if they can shed any more light on this than to try to debug it further, as this seems like it's getting very close to a being a weird edge case.

**Comment by stevenday** [comment]
After more investigation, I've written this off as a cookies problem on the user's side, because they're now using the site fine.
