### ISSUE TITLE
No opportunity to update status of request when a response has come in

### ISSUE THREAD

**Issue by kingqueen3065** [mysociety/alaveteli#4069]
I just got an (automated) response to [this request](https://www.whatdotheyknow.com/alaveteli_pro/info_requests/monitoring_of_internal_review_ti). The request page asks me to categorise the response, but the yellow box with the category options hasn't appeared and the Actions menu doesn't include "update the status of this request", so I can't.
![ss 2017-06-27 at 05 21 25](https://user-images.githubusercontent.com/11923618/27598412-50786210-5b5d-11e7-985a-fcdd938be979.png)

**Comment by stevenday** [comment]
@kingqueen3065 - you can change the status via the "Change status" link at the bottom of the status box on the right hand side. This was a design decision we took early on to be less "hand-holdy" with pro users, but one I think we'll revisit as it's not the first time we've had people miss it!

**Comment by kingqueen3065** [comment]
Thank you! 
It's inconsistent though. I've just got a response in [this request](https://www.whatdotheyknow.com/request/lists_of_accessible_taxis_under_30) and a) the yellow box has appeared and b) the "Update the status of this request" option has appeared in the Actions dropdown.

![ss 2017-06-27 at 05 44 45](https://user-images.githubusercontent.com/11923618/27599375-7cef8adc-5b60-11e7-927c-aef934fd8eb2.png)

I often have to select "Update the status of this request" because the yellow box doesn't show the option "I'm awaiting the response to an internal review" unless I do. 

Doug

**Comment by kingqueen3065** [comment]
Closed in favour of [my new issue on the Pro issue tracker](https://github.com/mysociety/alaveteli-professional/issues/311)
