### ISSUE TITLE
Blog post about QueremosDatos

### ISSUE THREAD

**Issue by Gemmamysoc** [mysociety/alaveteli#4072]
It would be nice to write a post about the launch of https://www.queremosdatos.co/ 

Perhaps we could interview Maria about why she set it up, how it's going, plans for the future, what impact she wants it to have etc.

**Comment by garethrees** [comment]
Done! https://www.mysociety.org/2017/07/27/introducing-queremosdatos-making-access-to-information-easier-in-colombia/
