### ISSUE TITLE
Errno::ENOMEM: Cannot allocate memory

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#4106]
The test suite often fails with some sort of `Errno::ENOMEM` error:

* `Errno::ENOMEM: Cannot allocate memory - fork(2)`
* `Errno::ENOMEM: Cannot allocate memory - tnef -K -C /tmp/d20170710-14885-4j5dfb 2> /dev/null`

Adding a swapfile to the Vagrant VM seems to alleviate this to some degree:

```
# Configure swapfile
echo 'swapfile not found. Adding swapfile.'
# fallocate is Ubuntu-only, I think. Need to use dd on Debian.
fallocate -l 8000M /swapfile
chmod 600 /swapfile
mkswap /swapfile
swapon /swapfile
echo '/swapfile none swap defaults 0 0' >> /etc/fstab
```

**Comment by lizconlan** [comment]
If you're worried about disk space, you can get away with setting the swapfile down at 3000 (or 3073 if you want an even 3GB) provided you can spare 4GB RAM for the VM. Set the swapfile any lower than that and you'll still encounter some errors (although even a smaller swapfile will help)

**Comment by lizconlan** [comment]
The Debian equivalent would be:

```
sudo dd if=/dev/zero of=/swapfile bs=1024 count=8192000
```

and we should probably throw in a `swapoff -a` in case there's already something allocated

**Comment by garethrees** [comment]
https://github.com/schneems/derailed_benchmarks looks like a good suite for diagnosing memory issues.

https://github.com/benoittgt/understand_ruby_memory might also be useful, but perhaps a little low level.

**Comment by garethrees** [comment]
- [ ] Look at why globalize filters by locale in ruby instead of SQL https://github.com/mysociety/alaveteli/pull/4121#issuecomment-317461465

**Comment by garethrees** [comment]
Interesting article on rspec profiling http://blog.marionzualo.com/a-random-walk-through-profiling-rspec-tests/

**Comment by garethrees** [comment]
https://robots.thoughtbot.com/a-crash-course-in-analyzing-memory-usage-in-ruby

**Comment by garethrees** [comment]
- https://schneems.com/2017/06/22/a-tale-of-slow-pagination/

NewRelic have [discontinued](https://discuss.newrelic.com/t/feedback-on-the-ruby-agent-s-developer-mode/46957) their dev-mode tooling. Scout dev tools look like they're worth trying out:

- http://blog.scoutapp.com/articles/2017/03/01/which-rails-profiler-is-right-for-you
- https://scoutapp.com/devtrace
- http://help.apm.scoutapp.com/#transaction-traces
