### ISSUE TITLE
'Report' button in the comments looks a bit off

### ISSUE THREAD

**Issue by wrightmartin** [mysociety/alaveteli#4125]
<img width="742" alt="screen shot 2017-07-27 at 10 44 06" src="https://user-images.githubusercontent.com/2292925/28664492-9cec9428-72b8-11e7-9b11-5ccf9331e16a.png">

Needs spacing, and should it be the primary brand colour?

**Comment by garethrees** [comment]
The [intention](https://github.com/mysociety/alaveteli/pull/3694#discussion_r102200662) was for it to be "joined" like a [button group](http://getbootstrap.com/2.3.2/components.html#buttonGroups).

**Comment by wrightmartin** [comment]
> The intention was for it to be "joined" like a button group. Not sure how the blue snuck in.

Ah, it looks like something in the WDTK theme because in the base theme it looks tidy

![screen shot 2017-07-27 at 14 09 11](https://user-images.githubusercontent.com/2292925/28671593-33acb7e6-72d5-11e7-8495-ed2d8c9c05d1.png)

**Comment by kingqueen3065** [comment]
I prefer the blue colour.

**Comment by zarino** [comment]
> I prefer the blue colour.

Feels like it should be _red_ to me!

**Comment by garethrees** [comment]
This is no longer true – IDK where we fixed it.

![Screenshot 2020-11-24 at 13 25 00](https://user-images.githubusercontent.com/282788/100100285-7d5a4600-2e58-11eb-8f8c-9191854dd6ab.png)
