### ISSUE TITLE
All "Download a zip file of all correspondence" zip files corrupted

### ISSUE THREAD

**Issue by kingqueen3065** [mysociety/alaveteli#4161]
Example: https://www.whatdotheyknow.com/request/prow_data/download - both the correspondence PDF and the attachment PDF fail CRC check, resulting in this in 7-Zip
![ss 2017-08-13 at 12 50 21](https://user-images.githubusercontent.com/11923618/29244973-718db74c-7fc1-11e7-9bb0-a9f238b75376.png)
and this in Windows Explorer.
![ss 2017-08-13 at 12 51 32](https://user-images.githubusercontent.com/11923618/29244976-9f126fdc-7fc1-11e7-810d-211501285bb1.png)
I've tried with multiple requests, browsers and user accounts, all with the same result.

**Comment by garethrees** [comment]
Could you try downloading a different request today? Ideally one that was created recently (last hour or so whenever you read this).

We did have a problem with zip downloads between Tuesday and Wednesday. We fixed the problem, but zips downloaded in this window were cached as corrupted files. Liz cleared the cache of these on Friday.

I just downloaded https://www.whatdotheyknow.com/request/request_for_information_about_an_4 without a problem.

**Comment by kingqueen3065** [comment]
Hi

I just downloaded https://www.whatdotheyknow.com/request/tree_preservation_orders_digital_172, it was corrupted. (Using my Android phone and Dolphin browser this time.)

Also the download problems I gave above were yesterday, after the caches were cleared; also the random one I picked was quite unlikely to have been downloaded between Tuesday and Wednesday.

Cheers

**Comment by garethrees** [comment]
Interesting – could be some access permissions thing on your account. Will discuss in sprint planning in half an hour or so :)

**Comment by kingqueen3065** [comment]
Thank you,

I've also tried it on my test non-admin account to the same result. Though I'm not 100% sure I tested on a request that I'd not already downloaded with my standard account so caching may be responsible.

**Comment by garethrees** [comment]
@kingqueen3065 this seems to be working okay for us. Might be an OS/Software issue.

Is the error happening when you unarchive the zip, or are the files extracting successfully, but then failing to open because they're corrupt.

Could be something related to https://sourceforge.net/p/sevenzip/discussion/45798/thread/7f1ed08a/?limit=25

**Comment by kingqueen3065** [comment]
It is happening across OSes, browsers and unzipping utilities. 

I just downloaded the correspondence zip file from https://www.whatdotheyknow.com/request/yorks_lists_of_accessible_taxis using Firefox on Windows. I have never downloaded it before. 7-Zip opens the zip file and displays the file list but attempting to extract any of the files fails with the result "CRC failed." Windows default zip file handling does similarly; it lists the file names but attempting to extract any gives "Error 0x80004005: Unspecified error". I attach the corrupted zip file.
[yorks_lists_of_accessible_taxis.zip](https://github.com/mysociety/alaveteli/files/1222915/yorks_lists_of_accessible_taxis.zip)

I just tried downloading this request's correspondence https://www.whatdotheyknow.com/request/freedom_of_information_request_s_153 using Chrome on Windows. 7-Zip gives the same CRC error and so does Windows' default file handling.

The same has happened on Dolphin on Ubuntu.

It happens across user accounts. I just downloaded a zip file from a recent FOI request for which I had not previously downloaded the correspondence. I used my test, non-admin user, and 7-zip refused it with a CRC error as above.

I have tried other zip files on the Internet, including uploading ones I have made myself, and they download and open in 7-zip with no problems.

Odd

**Comment by garethrees** [comment]
> I attach the corrupted zip file.
> yorks_lists_of_accessible_taxis.zip

Interesting – I can extract and open all attachments from that zip successfully.

**Comment by RichardTaylor** [comment]
A further user report from WhatDoTheyKnow:

> Please could you check if it just me, but I think there is a more general problem.
> 
> I am trying to download the zip fie of "all correspondence" for the request at this link.
> 
> https://www.whatdotheyknow.com/request/hs2_report_to_dft
> 
> The file is created and seems to download OK. The zip file opens to show the files contained but the individual files will not open and the software describes them as corrupted.
> I have downloaded to both my PC and my iPad with the same result.
> 
> I have tried downloading  the zip files similarly for other requests and am getting the same glitch.
> 
> Any help much appreciated.
> 

I have been able to download the zip, and open it and view files.

**Comment by RichardTaylor** [comment]
The WDTK user who sent the report included in the previous comment has now sent screenshots showing the same errors as those in the screenshot in the message at the start of this issue. 

The user added:

> 
> I have downloaded and installed Winzip.
> 
>  
> 
> Again it opens the zip file to identify the files within, but those files will not open.
> 
>  
> 
> It does however provide some additional information as below.
> 
>  
> 
> Extracting to "C:\Users\[user]\AppData\Local\Temp\[redacted]\"
> 
> Use Path: yes   Overlay Files: yes
> 
> Extracting correspondence.pdf
> 
> Error: Unable to extract "C:\Users\[user]\AppData\Local\Temp\[redacted]\correspondence.pdf".
> 
>  
> 
> The size of the extracted file (178412) does not match the uncompressed size (173975) recorded in the Zip file.
> 
> Severe Error: File size doesn't match uncompressed size.

**Comment by lizconlan** [comment]
Have found an a old Windows laptop. Looks like 7Zip is reporting all the contained files as corrupted if you press the info button (also, as above, the built in Windows unzip option (XP in my case - a really old laptop) errors without much extra info).

Possibly related: https://stackoverflow.com/questions/36295822/ruby-writing-zip-file-works-on-mac-but-not-on-windows-how-to-recieve-zip-file (not exactly the same problem as ours but it might point to an accidental change to line end encoding within PDF files either when adding it to the zip archive or when attempting to redact the text)

**Comment by lizconlan** [comment]
This appears to be a problem with the zip library we are using - the older ['zip' gem](https://rubygems.org/gems/zip/versions/2.0.2) (not officially on Github but [this appears to be a fork by the last committer](https://github.com/samlown/zip) - as running exactly the same code* using the [rubyzip gem](https://rubygems.org/gems/rubyzip) produces a viable Windows-friendly file - tested on an old laptop running XP)

Experimenting to see if the functionality we require is available in ruby 1.9.3 (it's permitted in the gemspec but was dropped from the test matrix some time ago)

### created with zip

![compression_bad](https://user-images.githubusercontent.com/27760/30391069-1a785bda-98b0-11e7-9583-9ae73feef035.PNG)

### created with rubyzip

![compression_good](https://user-images.githubusercontent.com/27760/30391084-2544dc78-98b0-11e7-9988-4b8b46b1e9e1.PNG)


---
\* ok so you have to call the module as `Zip::File` instead of `Zip::ZipFile` and `require 'zip'` instead of `zip/zip` but the rest of the code is unchanged

**Comment by lizconlan** [comment]
Or programmatically...

```rb
require  'zip'

Zip::File.open(broken) do |zipfile|
  zipfile.file.size('example.pdf')
end
# => 75597

Zip::File.open(working) do |zipfile|
  zipfile.file.size('example.pdf')
end
# => 78121
```

**Comment by RichardTaylor** [comment]
Looks like the fix is in progress; but just a note to say a WhatDoTheyKnow user has got in touch to report this issue again.
