### ISSUE TITLE
Closing brackets at ends of URLs in responses picked up in the href=

### ISSUE THREAD

**Issue by kingqueen3065** [mysociety/alaveteli#4168]
In https://www.whatdotheyknow.com/request/cfs_pace_permission_to_drop_more#incoming-1001883 a closing bracket has been picked up as the final character of a URL, changing `http://gtr.rcuk.ac.uk/projects?ref=G0200434` to
`http://gtr.rcuk.ac.uk/projects?ref=G0200434)` .

**Comment by garethrees** [comment]
This now works.

Looks like this issue may be a duplicate of https://github.com/mysociety/alaveteli/issues/3400
