### ISSUE TITLE
Public body admin page - missing content

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#4183]
The request email address isn't shown in the table at the top of the admin body show pages on WhatDoTheyKnow; neither is related information such as the public_body.not_requestable_reason

Unimportant but I think it's a bug.

**Comment by garethrees** [comment]
Ah, I think its stoped showing the translated fields because of #4066

**Comment by garethrees** [comment]
Just noting that clicking "edit" reveals these fields. Appreciate this is not ideal.
