### ISSUE TITLE
-bash: bundle: command not found

### ISSUE THREAD

**Issue by thinkholic** [mysociety/alaveteli#4188]
**O/S:** Windows 10
Vagrant / VirtualBox

Followed these instructions;
http://alaveteli.org/docs/installing/vagrant/

This is the error I am getting when I run `bundle exec rails server` command.

```
λ vagrant ssh
Linux vagrant 3.2.0-4-amd64 #1 SMP Debian 3.2.51-1 x86_64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Wed Feb  5 11:41:12 2014 from 10.0.2.2
vagrant@vagrant:~$ ls
alaveteli  install-arguments  install-site.sh  last-host
vagrant@vagrant:~$ cd alaveteli/
vagrant@vagrant:~/alaveteli$ bundle exec rails server
-bash: bundle: command not found
```

Appreciate If someone can help with this?

**Comment by garethrees** [comment]
I've just followed the instructions through and get a rails server running.

What versions of VirtualBox and Vagrant do you have installed?

**Comment by thinkholic** [comment]
Vagrant 1.9.8
VirtualBox Version 5.1.26 r117224 (Qt5.6.2)

**Comment by garethrees** [comment]
Yep, I've just run it successfully with those same versions.

One thing that I always do is install [vagrant vb-guest](https://github.com/dotless-de/vagrant-vbguest) to ensure guest editions are always up to date. I _think_ you'd have had an error earlier on in the process if this was the case though.

It would be helpful to see the full output of `vagrant --no-color up` so that I can look for anything that seems odd.

**Comment by thinkholic** [comment]
Okay. I installed `vb-guest` and tried again..

this time come up with a different error which once got in another machine (mac os);

```
E:\Dev\sandbox\alaveteli (develop)
λ vagrant --no-color up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.
```

**Comment by garethrees** [comment]
In that last code example it looks like the VM is already up, so running `up` again will have no effect.

Try destroying the VM and rebuilding it:

```sh
vagrant destroy
vagrant --no-color up
```

**Comment by thinkholic** [comment]
yeah! it solved the second error... but `-bash: bundle: command not found` is still the same.

**Comment by garethrees** [comment]
It would be good if you could rebuild the VM:

```
vagrant destroy
vagrant --no-color up
```

…and then paste all the output from the second command. At the moment I can't tell what might have gone wrong on your system. Cheers!

**Comment by garethrees** [comment]
Closing as we couldn't reproduce this. Will reopen if we can get it reproduced.
