### ISSUE TITLE
"Show quoted sections" missing

### ISSUE THREAD

**Issue by kingqueen3065** [mysociety/alaveteli#4189]
hi, 
this request: https://www.whatdotheyknow.com/request/managed_print_information_15#incoming-1025969

When I first went to that response a few minutes ago, the "show quoted sections" expansion link at the bottom was missing. After I downloaded the message, extracted the quoted section and posted it as an annotation, the "show quoted sections" link now appears on the message.

**Comment by RichardTaylor** [comment]
Another case has occurred:

https://www.whatdotheyknow.com/request/managed_print_information_10

It's a request to a different body by the same user, with the same request text. 

There doesn't appear to be a general problem - "show quoted sections" is working generally across the WhatDoTheyKnow. 

@kingqueen3065 are you still seeing  "show quoted sections" ? Nothing I do appears to restore the link.

**Comment by RichardTaylor** [comment]
That's really weird. After I added an annotation to release the text; a further visit to the page has resulted in the link appearing for me while logged in; and I've checked, it appears when not logged in too.  

Between visits to the page I changed:

>  described_state:        error_message    =>        successful      

I also set "Awaiting description" to "no"




I'm still not seeing "show quoted sections" at:

https://www.whatdotheyknow.com/request/managed_print_information_15

**Comment by RichardTaylor** [comment]
I returned to:

https://www.whatdotheyknow.com/request/managed_print_information_15

Where I wasn't seeing "show quoted sections"; I then toggled 
>awaiting_description: false => true 
>awaiting_description:  true    =>        false

and then on re-load I could see "show quoted sections".

**Comment by RichardTaylor** [comment]
At 

https://www.whatdotheyknow.com/request/online_safety_costs_29#incoming-1042875

"Show quoted sections" was missing; and there was no other content. 

Again toggling

>    awaiting_description: false => true
>    awaiting_description: true => false

Resulted in "show quoted sections" being shown
<img width="787" alt="screen shot 2017-09-26 at 12 36 02" src="https://user-images.githubusercontent.com/547695/30858347-366ba214-a2b7-11e7-98ea-5fcb8fec0c80.png">
<img width="794" alt="screen shot 2017-09-26 at 12 35 47" src="https://user-images.githubusercontent.com/547695/30858364-4512c720-a2b7-11e7-959f-bf088f61a26a.png">

**Comment by RichardTaylor** [comment]
Another; related to the same series of requests as the previous report:
https://www.whatdotheyknow.com/request/online_safety_costs_103

<img width="813" alt="screen shot 2017-09-26 at 14 47 15" src="https://user-images.githubusercontent.com/547695/30863839-f7d1efdc-a2c9-11e7-8050-7214252d557d.png">
<img width="807" alt="screen shot 2017-09-26 at 14 46 50" src="https://user-images.githubusercontent.com/547695/30863840-f82eb05a-a2c9-11e7-9c4d-fd9284e74ff2.png">

**Comment by RichardTaylor** [comment]
The "show quoted sections" link then disappeared from 

       https://www.whatdotheyknow.com/request/online_safety_costs_103

A user noted:

>Although the "Show quoted sections" link isn't there, if I append ?unfold=1 to the URI it does correctly show me the quoted bits.

**Comment by RichardTaylor** [comment]
Another case today where a WhatDoTheyKnow user couldn't access their response due to the lack of a "show quoted sections" link:

https://www.whatdotheyknow.com/request/university_it_infrastructure_inf_8
https://www.whatdotheyknow.com/request/university_it_infrastructure_inf_8?unfold=1

<img width="698" alt="screen shot 2017-10-03 at 14 05 50" src="https://user-images.githubusercontent.com/547695/31126771-9c8a6bb0-a844-11e7-8930-f0e7725ef094.png">

**Comment by RichardTaylor** [comment]
Another case today:
https://www.whatdotheyknow.com/request/availability_of_wheelchair_acces_15?unfold=1
https://www.whatdotheyknow.com/request/availability_of_wheelchair_acces_15

**Comment by RichardTaylor** [comment]
Another case:
https://www.whatdotheyknow.com/request/rmg_eu_funding#comment-80512

**Comment by garethrees** [comment]
@jacksonj04's case https://www.whatdotheyknow.com/request/totals_for_subject_access_reques_46

**Comment by RichardTaylor** [comment]
Another case reported to WhatDoTheyKnow today:

https://www.whatdotheyknow.com/request/availability_of_wheelchair_acces_30#comment-80571

**Comment by garethrees** [comment]
This has been fixed in https://github.com/mysociety/alaveteli/pull/4320.

The fix should work its way out next week after the retreat.

Existing problem requests won't automatically get fixed, but they will when a state change happens (either through receiving a response or manually by the requester/an admin).
