### ISSUE TITLE
Outstanding Actions Pending Alert Notification on All Pages

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#42]
Currently users get a list of their outstanding actions (uncategorised requests) when they try and make a new request or if they visit their user page. 

When users have outstanding actions pending there should be a note to this effect on all pages.

(something along the lines of a flash message at the top saying "you have outstanding actions" and offering a linking to the user page where the details will be.)

**Comment by garethrees** [comment]
Going to close in favour of https://github.com/mysociety/alaveteli/issues/3333.

I think this is intended to be a bit broader, but the "Next actions todo list" is now part of the Pro dashboard.
