### ISSUE TITLE
Box-shadow / border-radius conflict on request thread "cards" in Demo theme and WDTK theme

### ISSUE THREAD

**Issue by zarino** [mysociety/alaveteli#4214]
`div.correspondence` has `border-radius: 5px`, but the `.correspondence__footer` inside it doesn’t, meaning its square corners jut outside the parent, covering up the box shadow.

![screen shot 2017-09-11 at 14 28 19](https://user-images.githubusercontent.com/739624/30277317-4f4e1f00-96ff-11e7-90c9-33ad0847f315.png)

Most people probably wouldn't notice it. But it annoys me every time I see it.

Just needs something like `.correspondence__footer { border-radius: 0 0 5px 5px; }`.

**Comment by garethrees** [comment]
Going to close this as its never going to be something we _prioritise_. I'd be totally happy for you to make a PR that fixes this next time you notice it and have time to fix it though.

**Comment by zarino** [comment]
This was fixed September last year in mysociety/whatdotheyknow-theme@e65e7d47918ba180fe2927291079131571d91796 🎉
