### ISSUE TITLE
Exclude banned users from the TrackMailer alert_tracks email

### ISSUE THREAD

**Issue by lizconlan** [mysociety/alaveteli#4237]
From looking at the last updated timestamps we're continuing to send email updates to banned users.

**Comment by garethrees** [comment]
This is intentional…

https://github.com/mysociety/alaveteli/blob/ed73db7f823d7b08e356cc8538645ab6b1d85ed1/app/views/user/banned.html.erb#L17-L19

…but should be reviewed in https://github.com/mysociety/alaveteli/issues/3148.
