### ISSUE TITLE
Upgrade nokogiri gem

### ISSUE THREAD

**Issue by lizconlan** [mysociety/alaveteli#4246]
Depends on #4541 to move to [`~>1.7`](
https://github.com/sparklemotion/nokogiri/blob/master/CHANGELOG.md#backwards-incompatibilities-2)
Depends on #4542 to move to [`~>1.9` or above](
https://github.com/sparklemotion/nokogiri/blob/master/CHANGELOG.md#backwards-incompatibilities-1)

(`~>1.10` drops support for Ruby 2.2 but we don't support that anyway)

**Comment by garethrees** [comment]
Requires https://github.com/mysociety/alaveteli/issues/4541
