### ISSUE TITLE
AlaveteliFeatures gem fails to use database in production

### ISSUE THREAD

**Issue by lizconlan** [mysociety/alaveteli#4280]
Unexpectedly causes warnings to appear in production logs...

```
W, [2017-03-23T00:09:15.533775 #31119]  WARN -- : No database tables found for feature flags, you might need to set a backend explicitly if you don't want them stored in a database, or runrake db:migrate to create the table.
```

...when the `flipper_features` table exists.

Definitely a problem on 0.28.0.9, the code that checks for the table is different in 0.29.0.0 so it's worth checking whether this fixes the problem (in which case we should consider backporting to 0.28.0.x)

**Comment by garethrees** [comment]
Ah looks like this is resolved in https://github.com/mysociety/alaveteli/commit/5271174245d7f19671292d40e088a1b77b247619

**Comment by lizconlan** [comment]
(I'm tempted to backport it as it looks like an easy win)
