### ISSUE TITLE
Front-end performance investigation

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#4342]
Spend some time investigating and fixing.

Also related https://github.com/mysociety/alaveteli/issues/3845.

**Comment by wrightmartin** [comment]
### Results from PageSpeed Insights
 (https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.whatdotheyknow.com%2F&tab=mobile)

- Eliminate render-blocking JavaScript and CSS in above-the-fold content (no filesize saving but big improvements to first paint time)
- Enable compression (16.5KiB (66% reduction))
- Minify HTML (3.4KiB (14% reduction))

**Comment by zarino** [comment]
@garethrees How come the whatdotheyknow.com server isn’t gzipping its HTML responses?

**Comment by wrightmartin** [comment]
### Results from ySlow

Grade | B | Overall performance score 85 | Ruleset applied: YSlow(V2) | URL: https://www.whatdotheyknow.com/

- Grade C on Make fewer HTTP requests 
This page has 4 external Javascript scripts. Try combining them into one.
This page has 3 external stylesheets. Try combining them into one.
This page has 13 external background images. Try combining them with CSS sprites.
- Grade F on Use cookie-free domains

**Comment by zarino** [comment]
Doesn’t really affect performance, but I’ve noticed there’s a gap at the bottom of all the WDTK pages. Leads me to suspect there’s an unclosed HTML element somewhere? Possibly in the header/banner?

![screen shot 2017-11-07 at 10 02 27](https://user-images.githubusercontent.com/739624/32487894-dab7643c-c3a2-11e7-9a81-7c4cea81fb4c.png)

I think it’s happening on all the sites that use a theme forked from [alavetelitheme](https://github.com/mysociety/alavetelitheme): https://www.whatdotheyknow.com, https://www.queremosdatos.co, https://www.asktheeu.org…

**Comment by wrightmartin** [comment]
### General thoughts and observations
- 266.6K of JS
- 241.2K of CSS

- We serve pro styles to non pro users, should we only send these to pro users? Does the filesize of the CSS decrease enough to justify another request (sometimes non-pro users will see the pro styles, such as in the marketing pages)

- As above, but with JS

**Comment by garethrees** [comment]
Note its also worth checking a request page rather than the homepage, as they account for something like 80% of page views.

**Comment by wrightmartin** [comment]
### Spriting

- The request status icons could be sprited - combining 15 files into a single file to save on 14 requests. I'd estimate 2-3 hours for this
- Same for delivery status icons  - 4 requests into 1
- and the ```.act_link``` (ACT ON WHAT YOU'VE LEARNT) icons - 4 requests into 1

**Comment by wrightmartin** [comment]
### Google Chrome lighthouse audit

![screen shot 2017-11-07 at 10 48 55](https://user-images.githubusercontent.com/2292925/32489911-4e72d86a-c3a9-11e7-80df-2b5ecd9d7ad0.png)

**Comment by garethrees** [comment]
> How come the whatdotheyknow.com server isn’t gzipping its HTML responses?

```irc
[10:49:41]  <louise>	@gareth the historic reason there's no compression of http requests is as a mitigation against BREACH http://breachattack.com/  - that may well be worth revisiting
```

**Comment by wrightmartin** [comment]
### Critical path CSS

The FMS team have just done a lot of of work on inlining CSS and critical path rendering and are seeing very positive results

https://github.com/mysociety/fixmystreet/pull/1893/commits/fad51aa9d062eca21f52f86a81f6183f41a7c5a4

https://traintimes.org.uk/notes/performance

**Comment by wrightmartin** [comment]
Some progress here 

https://github.com/mysociety/alaveteli/tree/issues/4342-performance-improvement--sprites

**Comment by wrightmartin** [comment]
### Separating pro styles

I've run some rough tests on my local copy, removing the pro styles (all I did was delete all the styles from the pro .scss files) takes the uncompressed CSS from 498kb, down to 411kb. If we assume roughly the same equivalent would happen in the compressed CSS than would save 20% on file size. 

I think we can safely say pro styles are only going to grow in the near future, so its probably worth doing, and for JS files too.

@garethrees I'm not sure what's the approach for doing this though?

**Comment by wrightmartin** [comment]
More progress here 

https://github.com/mysociety/alaveteli/tree/issues/4342-performance-improvement

and here

https://github.com/mysociety/whatdotheyknow-theme/tree/alaveteli-issues/4342-performance-improvement

**Comment by wrightmartin** [comment]
PRs for the low hanging fruit fixes

https://github.com/mysociety/alaveteli/pull/4355

https://github.com/mysociety/whatdotheyknow-theme/pull/438

**Comment by garethrees** [comment]
Possible gzip solution https://schneems.com/2017/11/08/80-smaller-rails-footprint-with-rack-deflate/

**Comment by wrightmartin** [comment]
## Before data

### Request page
![developers google com_speed_pagespeed_insights__url https 3a 2f 2fwww whatdotheyknow com 2frequest 2fensuring_customers_are_not_subje_105 1](https://user-images.githubusercontent.com/2292925/33069531-c2473f3e-ceac-11e7-8dda-952b626f21e0.png)
![developers google com_speed_pagespeed_insights__url https 3a 2f 2fwww whatdotheyknow com 2frequest 2fensuring_customers_are_not_subje_105](https://user-images.githubusercontent.com/2292925/33069533-c2808c44-ceac-11e7-8462-3f404c6f520f.png)
<img width="1280" alt="screen shot 2017-11-21 at 09 14 39" src="https://user-images.githubusercontent.com/2292925/33069510-b324e6e6-ceac-11e7-917a-9b712c196e9e.png">


### Home page
![developers google com_speed_pagespeed_insights__url https 3a 2f 2fwww whatdotheyknow com tab mobile 2](https://user-images.githubusercontent.com/2292925/33069534-c2a42d66-ceac-11e7-98f3-422664a2c557.png)
![developers google com_speed_pagespeed_insights__url https 3a 2f 2fwww whatdotheyknow com tab mobile 1](https://user-images.githubusercontent.com/2292925/33069535-c2d9ae1e-ceac-11e7-89e8-a2964381f31d.png)




<img width="1280" alt="screen shot 2017-11-21 at 09 13 57" src="https://user-images.githubusercontent.com/2292925/33069512-b354f160-ceac-11e7-9e13-40ff8326c80d.png">

**Comment by garethrees** [comment]
@wrightmartin all the changes here should now be live

**Comment by wrightmartin** [comment]
Post-deploy results

### Homepage

<table>
<tr>
<th>Test</th><th>Before</th><th>After</th>
</tr>
<tr>
<td>ySlow</td><td>Grade B (85)</td><td>Grade B (86)</td>
</tr>
<tr>
<td>Google page speed (mobile)</td><td>73</td><td>73</td>
</tr>
<tr>
<td>Google page speed (desktop)</td><td>88</td><td>88</td>
</tr>
<tr>
<td>Number of requests</td><td>30</td><td></td>
</tr>
<tr>
<td>KB Transferred</td><td>262</td><td></td>
</tr>
<tr>
<td>Total time</td><td>3.7s</td><td></td>
</tr>
<tr>
<td>DOMContentLoaded</td><td>2.11s</td><td></td>
</tr>
<tr>
<td>Load</td><td>2.25s</td><td></td>
</tr>
</table>

**Comment by garethrees** [comment]
Looks like this made a decent impact! Thanks! 🚀
