### ISSUE TITLE
Asset was not declared to be precompiled in production

### ISSUE THREAD

**Issue by gorm** [mysociety/alaveteli#4350]
Hi,

I'm testing out new version, but get the following error, even after cleaning the assets and compiling again.

```
Asset was not declared to be precompiled in production. Add `Rails.application.config.assets.precompile += %w( logo-opengraph.png )` to `config/initializers/assets.rb` and restart your server
              
<meta property="og:site_name" content="<%= site_name %>" />
<meta property="og:url" content="<%= request.original_url.force_encoding('utf-8') %>" />
<meta property="og:image" content="<%= "#{request.protocol}#{request.host_with_port}#{asset_path('logo-opengraph.png')}" %>" />
<meta property="og:image:width" content="256" />
<meta property="og:image:height" content="256" />
```

**Comment by garethrees** [comment]
Hey @gorm,

Sorry about that.

You need to apply https://github.com/mysociety/alavetelitheme/commit/f025f5c05852c6a847349c47ebbd2f1182181182 to your theme.

There are also some other updates for themes for Rails 4+ https://github.com/mysociety/alavetelitheme/pull/97/commits.

Do post on the [mailing list](https://groups.google.com/forum/#!forum/alaveteli-dev) or get in touch if you need any help upgrading.
