### ISSUE TITLE
Users following "new message" links in emails should see latest version of request page

### ISSUE THREAD

**Issue by sebbacon** [mysociety/alaveteli#436]
Report from Ben:

> A user just reported that a new message hadn't appeared on WhatDoTheyKnow, and I was able to reproduce the problem.  
> The request in question was http://www.whatdotheyknow.com/request/hollie_bentley_prosecution_how_w, and the 
> incoming message arrived at Tue Feb 28 10:47:57 UTC 2012.  Not having signed into WhatDoTheyKnow yet today, I looked 
> at the page at 10:57, and found that the incoming message wasn't displayed yet.  I signed in (through the admin interface's 
> "sign in as this user" mechanism), and reloaded the public request page, and then the new message was visible.  I signed 
> out, and reloaded the page again, and the new message remained visible.
> 
> Users generally look at request pages shortly after receiving emails about them, so it would be good if any caches could be 
> flushed when a new response to a request is received, or something like that.

The quick solution here is to use a cache-busting URL in the alerts emails.  The better solution is to invalidate the cache when a new incoming message arrives.

**Comment by RichardTaylor** [comment]
We've not had a report of this issue for a while, but we've just had one on WhatDoTheyKnow:

>I was requested to view the [...] response, when I went onto your website , there was no message to read.

~45 minutes later, on review by an administrator the response was visible.
