### ISSUE TITLE
Introduce a link shortner

### ISSUE THREAD

**Issue by kingqueen3065** [mysociety/alaveteli#4375]
In my submission to a Government enquiry, I am referencing a DFT response to a request I made on WhatDoTheyKnow. The URL is https://www.whatdotheyknow.com/request/178430/response/462188/attach/3/131217%20L%20F0010739%20IR%20Response.pdf . I can't get it to display on a single line in my submission because it is too long.

I could use bit.my or tinyurl or whatever, but they have the disadvantage of "mystery meat", the person receiving them doesn't know what they will get.

A WhatDoTheyKnow URL shortener that only works for material on WhatDoTheyKnow would be good. E.g. https://whatdotheyknow.com/(slug). Pointing to the request, or a specific response, or (even better) a specific document like the PDF I link above.

It could be automatically generated for each request / response or generated by the user pressing a button (could cause problems for it to be auto generated I guess, e.g. for "attachments" that are actually just logos intended to prettyfy the authority's emails)

**Comment by RichardTaylor** [comment]
Already 

whatdotheyknow.com/request/178430

acts to a degree as a short URL, though that doesn't help with pointing to a specific attachment and it's attachments which have the longest URLs.  We could publicise the availability of the  /request/[number] link.

**Comment by EdaNano** [comment]
Take a look at lstu : let's shorten that url software, https://github.com/ldidry/lstu, that's the one used by Framasoft here : https://frama.link/ or another instance maintained by the developer himself is here : https://lstu.fr . It is free software (open source), privacy respectful, easy to install, one can choose the shortened name (example frama.link/my-short-url-to-my-pdf), and there is an API for it to quickly get shortened URLs without going to the website service : https://lstu.fr/api.
