### ISSUE TITLE
Reminder-followup, especially for new records custodians...

### ISSUE THREAD

**Issue by aliteralmind** [mysociety/alaveteli#4403]
We have a unique situation where the records custodian has been replaced before the requests have been fulfilled, and now all pending requests are unknown to the new custodian.

There does not seem to be any way to re-send a reminder of the original request, without manually copying the request-text, and then pasting it into a "followup." Additionally, because the [url is not included in any email](https://github.com/mysociety/alaveteli/issues/4402), there is no way for the new custodian to understand the system/the bigger picture, without having to manually paste that url in as well.

This issue is NOT about the url issue (see the link). This issue is "how can the original request-text be automatically sent to the custodian?" Does this require a new feature? Or is there a way to make this happen under the current code. 

To repead: How can an automated "reminder followup" be most elegantly implemented, that simply sends the custodian a full-repeat of the original request text, without putting such a manual burden on the requestors?

Thanks.

**Comment by aliteralmind** [comment]
Automatically including other useful information, such as the original request date and due date would also be very helpful.

**Comment by aliteralmind** [comment]
Example of a reminder-followup that I've just sent:

> FOLLOWUP-REMINDER of OPRA request originally submitted via OPRAmachine on 11/10/2017 and due 11/21/2017. 
> OPRA machine link for this request: https://opramachine.com/request/912_email_from_brennan_to_board
> Below is a full duplicate of the original request. 
> --- 
> REQUEST HERE

**Comment by garethrees** [comment]
Hey @aliteralmind 

Alaveteli doesn't quite support the workflow you're after at the moment.

Users cannot resent their requests, except via the process you describe of manually pasting the original request as a followup.

Admins can resend a request…

![admin-resend-request](https://user-images.githubusercontent.com/282788/33481318-d389e788-d68b-11e7-84a5-f329ca7cacad.gif)

…but that resets the clock.

We've always taken the position that the authority should be responsible for managing requests at their end, which would include staff changes.

You'd be able to resend the initial message as a followup (without resetting the clock) through the Rails console, but I'm not sure that would be ideal for you? I can figure out the code you'd need if its something you're interested in.

**Comment by garethrees** [comment]
This would essentially be fixed by https://github.com/mysociety/alaveteli/issues/3521.
