### ISSUE TITLE
Stop emailing new case notifications

### ISSUE THREAD

**Issue by davideaton2** [mysociety/alaveteli#4430]
This is a suggestion made by iCasework 

Also for our clients who use the API integration can you stop emailing them new case notifications? This is because they end up getting cases via the email and via the integration causing confusion.

**Comment by RichardTaylor** [comment]
We've now had two councils contact WhatDoTheyKnow asking us to stop emailing requests to them as they get them via iCasework.

**Comment by RichardTaylor** [comment]
A third council has now contacted WhatDoTheyKnow requesting this.

**Comment by MattK1234** [comment]
Just to note that another council has contacted WhatDoTheyKnow regarding this matter, requesting that emails are turned off.

**Comment by garethrees** [comment]
I'm going to close this now as we've explicitly said we can't do this (and don't have any plans to do so either) and they've responded:

> Think there was a misunderstanding on our side with what WDTK can do with the emails. We will be advising our customers correctly now, and get them to do a redirect.
