### ISSUE TITLE
Admin option to disassociate request from user

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#444]
A request's admin page ought have a button to publicly disassociate the request from the user who made it.

This would have the effect of:

1. If this was the first request publicly dissociated from this user create a new user account user name [Name Removed] email address nameremoved_X@invalid  where X auto-increments
2. Move the request so it becomes associated with either the user created in 1. or the specific [Name Removed] account associated with the user. 
3. Set up censor rules on the requests to remove the user's name, including variants (as smartly as possible!)  - at least if the user name was Richard Taylor, catching R Taylor  - these should be user wide censor rules set up on the  [Name Removed] user account. 

Note: We don't do this very often at the moment; so it might not be worth the developer effort over doing it manually.

**Comment by RichardTaylor** [comment]
Typically now we get a user asking for their name to be dissociated from all their requests; which involves changing the username to "[name removed]"; banning the user from making further requests; disabling their login and setting up a censor rule for all that users' requests. 

This feature request should cover that circumstance, as well as just wanting to dissociate a request from a user. Brining this action within the system would hopefully allow the occurrence to be flagged/recorded so it can be reported in a transparency report.

**Comment by RichardTaylor** [comment]
Increasingly on WhatDoTheyKnow we appear to be getting requests to anonymise requests from those whose requests are still in progress.  Our practice as outlined above has the side effects of preventing users getting alerts about their requests, and preventing them entering follow-up correspondence. 

When requests are still in progress it would be useful if the user could keep getting alerts, and even be able to correspond under their name to the public body, and just not have their name shown on the site. 

The numbers of case where this would be useful are small.

**Comment by kingqueen3065** [comment]
Anonymising requests and accounts is still a substantial workload for volunteer admins. The admin workload is substantial. It would be of benefit to enable this facililty.
I note that [similar has recently been implemented on FixMyStreet](https://www.mysociety.org/2018/03/06/now-youre-even-more-secure-on-fixmystreet/), which now offers the functionality for a user to anonymise a report or all their reports at the click of a button. On WhatDoTheyKnow we wouldn't want the user to be able to do this, but having this sort of automated ability for admins would be a great boon to volunteers' time and energy.

**Comment by garethrees** [comment]
I think we can consider this closed by https://github.com/mysociety/alaveteli/pull/4806.

**Comment by garethrees** [comment]
There's been another case where this might have been helpful. A user wanted a single request hidden because they had second thoughts about its impact on them. They'd made a few other requests. Can handle this by manually moving to an anonymous account. Not worth reopening at this point, but just recording when they come up.

**Comment by HelenWDTK** [comment]
+1 Dealt with one of these last week. Current workflow is: 

1. create an account in my name
2. move the request over (the profile url slugs are messy after c&a making this hard, and alaveteli doesn't seem to like user ids in this field)
3. C&A that account
4. Check the censor rules work/add more

It'd be good to streamline that a bit.
