### ISSUE TITLE
Installation docs don't cover setting up GitHub keys

### ISSUE THREAD

**Issue by lizconlan** [mysociety/alaveteli#4453]
As our instructions describe the ssh `git clone` method, new users will need to have ssh keys set up for GitHub otherwise they'll see the following error:

```
'Cloning into 'alaveteli'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Affects:
* http://alaveteli.org/docs/installing/vagrant/
* http://alaveteli.org/docs/installing/manual_install/

(ToDo: Check whether the installation script needs this as well)

The simplest thing to do is to link out to [GitHub's docs on setting up ssh keys](https://help.github.com/articles/connecting-to-github-with-ssh/) as they're good quality and kept up to date.

**Comment by garethrees** [comment]
There's only so much we can document. I'd expect someone using git to clone Alaveteli to be familiar enough with git to understand what's happening here.
