### ISSUE TITLE
Department of Health HTML attachments & IE

### ISSUE THREAD

**Issue by skenaja** [mysociety/alaveteli#447]
Internet Explorer does not display this HTML attachment correctly:

HTML attachment link:
http://www.whatdotheyknow.com/request/105223/response/260493/attach/2/Long%20Email%20Body%2001%2003%202012.html

Request message body: http://www.whatdotheyknow.com/request/department_of_health_representat#incoming-260493

Tested with IE9 with Compatibility Mode both on & off.

**Comment by garethrees** [comment]
Its not a full and valid HTML document (doesn't even have `<head>` or `<body>` tags). Don't think there's much we can really do about this, as I don't think we really want to start modifying the document.
