### ISSUE TITLE
Consider advice about annotations

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#4473]
A WhatDoTheyKnow user has written:

>I see that before I make an annotation, there is a message:
>>Annotations will be posted publicly here, and are not sent to [name of authority].

>While this is true, the authority could, like anybody else, read the annotations and I think, if they set up an alert for themselves, would be notified of it. Is it worth pointing this out, perhaps by adding something like though they may, like anybody else, read them here.

My own view is this is obvious and there's an advantage in not cluttering the site with too many warnings.

**Comment by garethrees** [comment]
> My own view is this is obvious and there's an advantage in not cluttering the site with too many warnings.

+1, so closing this as I don't think we'll realistically change this.
