### ISSUE TITLE
Users can't replace user photo

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#4477]
Attempting to replace a user photo results in the original photo still being displayed. 

Clearing the photo does clear the photo but then uploading a new photo results in the original photo being displayed again. 

Bug reported by user of WhatDoTheyKnow.com and confirmed by me.

**Comment by RichardTaylor** [comment]
On checking a day or so later after trying to update the image the new image was present, suggesting a caching issue.

**Comment by garethrees** [comment]
Here's a [link](https://groups.google.com/a/mysociety.org/forum/#!topic/alaveteli/cEhB9Jla7fY) to the specific case.

Does indeed sound like a caching issue.

**Comment by garethrees** [comment]
Duplicate of https://github.com/mysociety/alaveteli/issues/156.
