### ISSUE TITLE
Extract PublicBody#notes to model

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#4478]
At the moment we store notes as translated attributes of `PublicBody`.

We're needing to do more complex things with notes, particularly in the Pro batch interface (https://github.com/mysociety/alaveteli-professional/issues/356).

The main things we'd like to be able to do are:

* Distinguish between an "FYI" note vs a "Must Read"
* Be able to keep track of when a note was last updated

## Decisions

* Should we create a polymorphic `Note` model? It could then be used for things like `PublicBodyCategory`, `PublicBodyHeading`, maybe even `InfoRequest`…
* What levels should we use? The [Bootstrap alerts](https://getbootstrap.com/docs/4.0/components/alerts/) seem like good general cases (info, warning, danger, success), but maybe we only need `info` and `warning`?

## Main tasks

* Create a polymorphic `Note` model with attrs:
  * content (i18n)
  * severity (default to lowest severity)
  * notable_id
  * noteable_type
  * created_at
  * updated_at

* Add `has_many :notes` to `PublicBody`.

* Add admin interface for creating and editing notes for a `PublicBody`.

* Consider adding interface and nested attribute handling for creating notes in the `AdminPublicBodyCOntroller#edit` form.

* Display notes in their own table in `AdminPublicBodyController#show`, rather than in the main attributes table.

* Display all notes with relevant styling in `PublicBodyController#show`. (We could also add "last updated" to the notes now, which would be useful).

## Consequences

* CSV importer will need reworking – maybe the default is to support only one default severity note column (i18n options as usual). Additional notes can get added in the interface later.

* Notes are indexed by Xapian – we'll need to tweak that so that it finds all notes and joins the content together in to one string.

## Migration

Write a rake task to:

* Find authorities with notes
* Create a `Note` for each translation, defaulted to "info"

**Comment by garethrees** [comment]
Would be good to be able to tie a `Note` to a tag https://github.com/mysociety/alaveteli/issues/387

**Comment by garethrees** [comment]
Another case for a separate `Note` model https://github.com/mysociety/alaveteli-professional/issues/301

**Comment by garethrees** [comment]
This would help allow us to provide specific guidance to Batch users in the category picker interface.

**Comment by gbp** [comment]
Extracting out the remaining items into separate issues:

- [ ] Migrate existing `PublicBody#notes` to `Note` model
- [ ] Remove note column from CSV `PublicBody` import
- [ ] Update `PublicBody` Xapian indexing for notes
