### ISSUE TITLE
"Download" email in admin interface doesn't work unless in raw email

### ISSUE THREAD

**Issue by kingqueen3065** [mysociety/alaveteli#4482]
At https://www.whatdotheyknow.com/admin/incoming_messages/1102067/edit if I select "Download" my browser goes to https://www.whatdotheyknow.com/admin/raw_emails/1101915.txt and returns a blank page.
If I select "Raw Email" and thus go to https://www.whatdotheyknow.com/admin/raw_emails/1101915 and select "Download" my browser goes to https://www.whatdotheyknow.com/admin/raw_emails/1101915.eml and gives me the email.
One's .txt and one's .eml - perhaps that's why?

**Comment by garethrees** [comment]
Ah this is because I switched it to `.eml` in https://github.com/mysociety/alaveteli/pull/4423.

**Comment by kingqueen3065** [comment]
That .eml won't import into The Bat if I select to import a .eml but will if I tell it to import it as a Unix mailbox.

**Comment by garethrees** [comment]
The _format_ of the file hasn't changed – just the extension. Its still just a plain text file.

According to [their help pages](https://www.ritlabs.com/en/support/help/61/) the unix mailbox importer is for `.mbox` which generally contains several messages. I'm not 100% sure on how that client treats opening messages. The default export option for Apple Mail is "Raw Message Source" (with a `.eml` extension).
