### ISSUE TITLE
Updating profile photo claims to be successful but doesn't do anything

### ISSUE THREAD

**Issue by kingqueen3065** [mysociety/alaveteli#4500]
https://www.youtube.com/watch?v=udQrORivb2w
Some caching issue?
Half an hour ish later, it's still not changed

**Comment by garethrees** [comment]
Nice sample data ;)

Richard reported this at https://github.com/mysociety/alaveteli/issues/4477 – TL;DR is that there's definitely a caching issue. The new image will appear in a day or so.

Closing as a duplicate of https://github.com/mysociety/alaveteli/issues/4477
