### ISSUE TITLE
Site wide admin configurable flash message

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#452]
It would be useful to give admins the ability to set a site wide banner message. 

Recent cases where this could have been used on WhatDoTheyKnow include:
- Recruitment advertising.
- Promoting the FOI post-legislative review call for evidence. 

In the latter case had there been such an admin settable banner we might have used it.

**Comment by garethrees** [comment]
Fixed by https://github.com/mysociety/alaveteli/pull/4425
