### ISSUE TITLE
Show free-text attached to an "error message" or "report this request" status in the admin interface

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#4564]
> Annoyingly, the free text in both cases cannot be viewed in the admin interface.
>
> https://github.com/mysociety/alaveteli-professional/issues/454#issuecomment-363457092

**Comment by garethrees** [comment]
Would help with https://github.com/mysociety/alaveteli/issues/419

**Comment by garethrees** [comment]
Requires https://github.com/mysociety/alaveteli/issues/4965

**Comment by RichardTaylor** [comment]
Related is #4612 which proposes strongly encouraging, if not requiring, some free text explanation as to why a request is being reported.
