### ISSUE TITLE
Ruby Sass/Scss deprecated – Replaced by Dart Sass

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#4590]
I don't know what this means for us yet:

> This also means that the official Ruby Sass deprecation period begins today—and on 26 March 2019, Ruby Sass will no longer be maintained. We'll have a blog post soon that goes into all the details.

* https://twitter.com/SassCSS/status/978367843564695552
* http://sass.logdown.com/posts/7045860-dart-sass-100-is-released

I guess we'll wait and see what Rails does to address this?

**Comment by gbp** [comment]
Dealt with upstream https://github.com/rails/sass-rails/pull/424
