### ISSUE TITLE
Ability to unsubscribe from all transaction emails

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#4603]
- [ ] Review all emails that we send out
- [ ] Add ability to unsubscribe from any that you can't unsubscribe from that aren't sent in response to a direct user action
  * e.g. new response, new response reminder, late, etc
  * password resets are fine as the user will have clicked something like "send me the email" and they're one-time

Related to #1971.

**Comment by RichardTaylor** [comment]
Just to note that I recall a discussion years ago about if we had a duty to email people to let them know they'd had a response to their request, and as I recall that wasn't something we then thought it was right to allow/enable people to opt out of. 

I think times have changed and people do expect more control over what emails they get. I'm not objecting to this proposal just flagging that's it's not entirely obvious and clear cut that we should allow people to opt-out of getting an email alert to tell them they've had a response to a request they've made; it has been a contentious subject in the past.

**Comment by garethrees** [comment]
First step with this is adding a "turn off email alerts" link to emails that the user _already has control over_, as per https://github.com/mysociety/alaveteli/issues/4551.

**Comment by garethrees** [comment]
Being able to "unsubscribe" users from emails would help with https://github.com/mysociety/alaveteli/issues/5090

**Comment by RichardTaylor** [comment]
This feature would be desirable to enable both a user-ban (based on their email address) and a suppression of emails to banned users where such a suppression is requested.

**Comment by RichardTaylor** [comment]
A WhatDoTheyKnow user today has replied to a "Please update the status of your request" email asking to be unsubscribed from "these emails".

**Comment by garethrees** [comment]
A [user has asked](https://groups.google.com/a/mysociety.org/g/alaveteli-dev-private/c/aLpPnVo7ADc/m/mLJmwn2tAgAJ) to be unsubscribed from post request survey emails (https://github.com/mysociety/alaveteli-project/issues/127).

**Comment by garethrees** [comment]
https://github.com/stevepolitodesign/unsubscribe might be some nice inspiration here.

**Comment by garethrees** [comment]
Linking to #4910. Not 100% sure if "closing" an account would enable us to solve this from the admin interface (in that closed users shouldn't receive email, but would need to actually check it stops everything).

**Comment by FOIMonkey** [comment]
+1 This would have helped with a case where an org responded to an old request belonging to a banned user, who then contacted us to ask why they are still getting emails when they are banned.

**Comment by RichardTaylor** [comment]
We've had a WhatDoTheyKnow user asking us to stop sending them "Please update the status of your request" emails.

**Comment by FOIMonkey** [comment]
+1 We've had another request through today to stop sending someone emails.

**Comment by HelenWDTK** [comment]
In response to a user wanting account emails disabled, @gbp  has clarified that when an account is "closed" a user *will* still be emailed for:

1. new responses
2. comments other have left on their requests
3. when classifies their requests
4. not clarified alerts - sent 3 days after a request is classified as awaiting_clarification
5. maybe others

It would be good to be able to disable all of these.

**Comment by HelenWDTK** [comment]
+1 this continues to cause annoyance and upset to users.

**Comment by garethrees** [comment]
This is desirable, but unlikely to be worked on in the next 12 months so closing for now.
