### ISSUE TITLE
Enable admins to note when a "Notice of European data protection removal" has been received in relation to a request

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#4622]
While this can be done via annotations, if we had a flag in the system it could be used to show appropriate text to users and to automatically provide content for a transparency report. #2658  

Possible text based on Google's notification to us:

>Google has notified us that due to a request under data protection law in Europe, Google will no-longer be listing this request in search results for certain queries for names or other personal identifiers. Google has informed us that this only affects search results offered by European versions of Google. 

>When contacting us to tell us about this Google noted the request will still appear in the results for other searches. Google didn't disclose which searches this request will no-longer appear in response to, and pointed out that in many cases affected queries don’t relate to the name of any person mentioned prominently on the page. 

>Google has invited us to make representations to them if we want to make the case for reversing their decision. If you think there is a strong public interest case for showing this request in search results from which it is currently omitted please feel free to get in touch with us and/or Google, making the case and providing evidence to support it. If we consider it appropriate we may pass the substance of what you say to Google. 

>We do not know who has asked Google to act, or on what basis Google has been asked to act.

**Comment by garethrees** [comment]
A specific case of #34

**Comment by RichardTaylor** [comment]
The text used here should either genericised so it applies to material on request pages, and linked attachments, or perhaps preferably we should have two versions, one where the request page isn't been shown in Google search results, and one where it is an attachment which isn't being shown. 

These annotations are still being added manually.

**Comment by RichardTaylor** [comment]
Example text used where the material in question was an attachment:

>Google has notified us that due to a request under data protection law in Europe, Google will no-longer be listing an attachment to this request in search results for certain queries for names or other personal identifiers. Google has informed us that this only affects search results offered by European versions of Google.

>When contacting us to tell us about this Google noted the request will still appear in the results for other searches. Google didn't disclose which searches this request will no-longer appear in response to, and pointed out that in many cases affected queries don’t relate to the name of any person mentioned prominently on the page [or in a document].

>Google has invited us to make representations to them if we want to make the case for reversing their decision. If you think there is a strong public interest case for showing the material in search results from which it is currently omitted please feel free to get in touch with us and/or Google, making the case and providing evidence to support it. If we consider it appropriate we may pass the substance of what you say to Google.

>We do not know who has asked Google to act, or on what basis Google has been asked to act.

**Comment by mdeuk** [comment]
Just to note, I wonder if we could use an admin-only version of the citation tool to achieve this in a manner of speaking.

To give a practical example - the BBC publishes a list [every so often](https://www.bbc.co.uk/blogs/internet/entries/c9612fdf-e5c3-479a-b52d-3f598c14bc44) of removal requests that they have received - if we could replicate this on an aggregate level it'd perhaps be advantageous, since then we'd have, in effect, a form of 'rolling' list of removals which can be periodically updated.

**Comment by RichardTaylor** [comment]
This is now a candidate for a tag based note. 

Adding a tag to impacted threads which would also enable searching for relevant threads (and potentially user pages in the future) by tag). 

We should consider if the benefits of the additional transparency outweigh the risks.

**Comment by garethrees** [comment]
> This is now a candidate for a tag based note.

+1. Closing as this is now possible.
