### ISSUE TITLE
Make censor rule comments less annoying for administrators

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#4625]
Quite reasonably a comment is required when creating or editing a censor rule.

Often when implementing censor rules it's necessary to go through quite a bit of trial and improvement until a combination of rules, or a single rule, works. Having to enter comments with every edit becomes tedious. 

Often a series of related censor rules are created for the same reason - to implement one type of censoring eg. to remove personal information, or remove a users' name, or remove potential defamation. 

Pre-populating the reason/comment field with the last used comment might help; especially on an edit. 

On a related point admins can't see the a history for edited censor rules; so admins are creating a comment history which is invisible to them.

**Comment by kingqueen3065** [comment]
+1

**Comment by RichardTaylor** [comment]
Just to add "Comment for this edit" here as that's what I searched for when looking for this issue.

**Comment by garethrees** [comment]
> On a related point admins can't see the a history for edited censor rules; so admins are creating a comment history which is invisible to them.

A history isn't actually created. Only the last edit comment is preserved as there's no versioning of censor rules.

The code change required here is trivial (remove the hard-coded `value`)…

```diff
diff --git a/app/views/admin_censor_rule/_form.html.erb b/app/views/admin_censor_rule/_form.html.erb
index bbe2db136..00a9cbe83 100644
--- a/app/views/admin_censor_rule/_form.html.erb
+++ b/app/views/admin_censor_rule/_form.html.erb
@@ -68,7 +68,7 @@
 <div class="control-group">
   <label for="censor_rule_last_edit_comment" class="control-label">Comment for this edit</label>
   <div class="controls">
-    <%= text_area 'censor_rule', 'last_edit_comment', :value => '', :rows => 2, :class => "span6" %>
+    <%= text_area 'censor_rule', 'last_edit_comment', :rows => 2, :class => "span6" %>
     <div class="help-block">
```

…but I think we want to accompany this with a warning if it's unchanged:

![Screenshot 2022-05-18 at 18 08 46](https://user-images.githubusercontent.com/282788/169102072-882bad67-554d-421e-9086-e03cb93bbbd1.png)

**Comment by garethrees** [comment]
> An alternative (and preferable, I think) approach would be to make it an active choice to use the last value:

Yes, let's do this.
