### ISSUE TITLE
Check handling of special characters in email addresses public bodies reply from

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#4642]
At

https://www.whatdotheyknow.com/request/roads_compensation_1990_2014_inc_12#incoming-1149446

Oxfordshire County Council replied from an email address with a local part of FOI-E&E

I'm not sure but I suspect that tripped up Alaveteli when a reply was attempted. 

This isn't urgent as the user has been advised of the work-around - trying to reply again and this time selecting the option to reply to the main FOI email address for the council. 

Related perhaps: #3465 
Keywords: Ampersand

**Comment by garethrees** [comment]
Duplicate of https://github.com/mysociety/alaveteli/issues/3465
