### ISSUE TITLE
Add new fields to user when signing up 

### ISSUE THREAD

**Issue by kimoensi** [mysociety/alaveteli#4668]
I need to add extra fields to a user when signing up on alaveteli, I found this theme  "https://derechoapreguntar.org" . When trying to install it on http://www.e3lemni.org, I encountred some problems.

After the installation of the new theme this error appear when accessing to : http://e3lemni.org/profile/sign_in

I'm new in ruby on Rails !!! Could you plz help/guide me on how to add  extra fields and/or how to solve problems when accessing the above interface.

**Comment by garethrees** [comment]
Hi @kimoensi,

Sorry its taken so long to reply to this.

The best place for getting help with installing Alaveteli is on https://groups.google.com/forum/#!forum/alaveteli-dev.

I think the problem may be that you need to run the [theme migrations](https://github.com/mysociety/derechoapreguntar-theme/tree/master/db/migrate), but I can't see the error now as the URL returns a 502 Bad Gateway.

This should happen when you run [`bundle exec rake themes:install`](http://alaveteli.org/docs/customising/make_a_new_theme/#4-tell-alaveteli-to-get-its-theme).

I'm going to close this issue, but please do post on [alaveteli-dev](https://groups.google.com/forum/#!forum/alaveteli-dev) with any further questions, and to let us know your plans for your Alaveteli install.
