### ISSUE TITLE
 Request: auto fax when email requests are not allowed 

### ISSUE THREAD

**Issue by aliteralmind** [mysociety/alaveteli#4672]
Some governmental bodies require requests to be faxed in. They forbid emails. This should be challenged of course, but meanwhile…

It would be really cool if, in this case, requests could be automatically converted to PDF and then faxed in. 

The only complication I can think of is providing them with an email address that is not excessively long, since it would need to be manually typed. So perhaps consider some kind of shortner. Simply a table that translates a short version to the. long one.

**Comment by gavinrozzi** [comment]
This is definitely something that I would like to address in New Jersey as it is increasingly becoming an issue in more municipalities. We have been frustrated by some public bodies that arbitrarily refuse emailed requests, but with fax we can try and meet them in the middle and still try and get the requests published.

We are currently considering establishing an email to fax gateway server to that would allow us to email phone numbers (ie 609-123-4567@faxserverdomain.com and have them be faxed via VoIP. If we can set this as the request email in Alaveteli, it would take care of sending the faxes, but it would probably result in all fax reaponses going to the holding pen and creating more administrative work. Ideally if the software could be integrated with one of the VoIP provider APIs it may make it more workable. Any suggestions from the community would be appreciated.

**Comment by Gemmamysoc** [comment]
Hi both. Just to say that a lot of groups who use Alaveteli around the world have come across similar issues with authorities not accepting requests via email, but most of them have successfully changed their minds :) Some examples as inspiration: 

- [Quesabes](https://www.quesabes.org/.), Uruguay: Launched in 2012 - at the time, many authorities were refusing to accept FOI requests via email. After 170 requests filed on the site, the Unidad de Acceso a la Información Pública (the Information Ombudsman in Uruguay) issued a degree that requires all Uruguayan authorities to accept FOI requests via email.
- [RightToKnow](https://www.righttoknow.org.au/), Australia: After the Australian Tax Office refused to accept requests via RightToKnow, one of the site's volunteers appealed to the Information Commissioner and he agreed it is lawful to use Right to Know to make FOI requests and recommended that the ATO begin processing stalled requests. [Read more here](https://www.oaf.org.au/2017/05/11/a-great-win-for-right-to-know-foi-and-transparency/).
- [WhatDoTheyKnow](www.whatdotheyknow.com), UK:  The Information Commissioner's [Guidance](https://ico.org.uk/media/for-organisations/documents/1164/recognising-a-request-made-under-the-foia.pdf) on recognising a request under the Freedom of Information Act contains a section specifically on WhatDoTheyKnow which states: "With respect to the address for correspondence, we consider the @whatdotheyknow.com email address provided to authorities when requests are made through the site to be a valid contact address for the purposes of Section 8(1)(b)."
- [Queremos Datos](https://www.queremosdatos.co/), Colombia: When the site first launched, the National Police were asking requesters to telephone them for the information - they have now been convinced by users and the Queremos Datos team that receiving and responding to email requests for information is okay, and now do so via the site. [More information here](https://www.mysociety.org/2017/07/27/introducing-queremosdatos-making-access-to-information-easier-in-colombia/).

Do you have an Information Ombudsman / Commissioner you can approach to get a similar ruling to the above examples? 

It might also be worth posting on the [Alaveteli Community Google Group](https://groups.google.com/forum/#!forum/alaveteli-users) to ask others for their tips on how they got authorities to accept email requests :)

**Comment by Gemmamysoc** [comment]
Ah, just thought of another case:

[AsktheEU](www.asktheeu.org): The people behind the site got a successful ruling from the European Ombudsman to say that the European Commission should stop requiring requesters to provide postal addresses when making requests (an issue for quite a while). [More information here.](https://www.access-info.org/article/30132)

**Comment by garethrees** [comment]
I'm going to close this issue as realistically we're not going to build this in to Alaveteli in the foreseeable future (much like https://github.com/mysociety/alaveteli/issues/469).

I hope the case studies Gemma linked above help and inspire you to challenge this situation.

Do let us know if you go ahead with your fax gateway though – we'd definitely interested to hear about it!
