### ISSUE TITLE
Issues with installation script for 0.23.2.0

### ISSUE THREAD

**Issue by gbp** [mysociety/alaveteli#4675]
I'm trying to install Alaveteli on VPS where I want to do some upgrade tests, by installing my current version (0.23.2.0), but I've got error.

- my environment: VPS is Virtual machine on Azure, Ubuntu 14.04 LTS.

Steps I did:
- download install script

curl -O https://raw.githubusercontent.com/mysociety/commonlib/master/bin/install-site.sh

- edit install script (updated BRANCH=master to BRANCH="release/0.23.2.0")
- run install script:

sudo sh install-site.sh alaveteli alaveteli imamopravoznati.org

- last line in results showed following error:
Installing packages from repository packages file... 
E: Package 'rubygems' has no installation candidate

Did I miss some pre-script steps?

p.s. all tests passed in install script:
Testing for being on EC2... done
Testing imamopravoznati.org's IP address... done
...
Your branch is up-to-date with 'origin/release/0.23.2.0'.

**Comment by Gemmamysoc** [comment]
Whoever replies to Miroslav should consider copying in alaveteli-dev@googlegroups.com and letting Miroslav know you've done that, so others with similar issues can be informed of how to resolve them as well :)

**Comment by garethrees** [comment]
Looks like there’s an accepted answer for the error he’s getting on the OS he’s using though https://stackoverflow.com/questions/23985887/install-error-rubygems-has-no-installation-candidate

**Comment by gbp** [comment]
Getting the same error when I try to install on 14.04. Installing the `rubygems-integration` package helps get a little further now seeing `Unable to locate package wkhtmltopdf-static`.

**Comment by garethrees** [comment]
I built a fresh trusty VM with no problems https://gist.github.com/garethrees/89f7044f93dfdeb492da94a59acf9384

**Comment by garethrees** [comment]
Going to close this as `0.23` is no longer supported.
