### ISSUE TITLE
Add "personal immigration correspondence" to list of reasons admins can hide a request

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#4687]
A large fraction of number of the cases of people using WhatDoTheyKnow to send personal information relate to immigration. 

It would be useful if on hiding requests of this nature the system would have an option within the admin system for sending our advice, which currently reads:

>Our service is only for making Freedom of Information and similar requests in public - we help people get government information into the public domain; for personal inquiries about your own individual circumstances you should not use our service but contact the UK Visas and Immigration service directly:
>https://www.gov.uk/government/organisations/uk-visas-and-immigration
 
This can of course be done by administrators editing the draft notification email. Administrators don't always do that, making it easier might result in it happening more often.  Explaining the situation to users the first time we get in touch with them can prevent further email exchanges. 

This is closely related to #3543 and #881

**Comment by garethrees** [comment]
Just linking to very similar https://github.com/mysociety/alaveteli/issues/3543

**Comment by RichardTaylor** [comment]
As this is potentially seeing some action I'll have another go at some text:

>Dear [User Name],
>
>Your correspondence '[request title]' at [URL] has been reviewed by moderators.
>
>As it is personal correspondence which it wasn't appropriate to send via our public website we have hidden it from other users. You will still be able to view it while logged in to the site. 
>
>You should contact the Home Office directly if you want to write to them in relation to your, or others', individual circumstances. The Home Office's direct email address is:
>
>public.enquiries@homeoffice.gsi.gov.uk
>
>The Home Office also offer a range of contact forms via:
>
>https://www.gov.uk/government/organisations/home-office#org-contacts
>
>We understand that it can be very difficult to get a response from the Home Office to personal immigration queries. If you are in the UK we suggest writing to the Home Office via your local Member of Parliament (MP), if you send your correspondence to your MP, they or their office, can pass it on to the Home Office and ensure you get a response. This has the benefit of highlighting difficulties communicating with the Home Office to MPs - who are in a position to address the systemic problems. 
>
>You can find and write to your MP via:
>
>http://www.writetothem.com 
>
>
>WhatDoTheyKnow.com is an independent website which helps people make Freedom of Information requests in public. We are not part of the Government. 
>
>
>Regards,
>
>
>--
>WhatDoTheyKnow.com Volunteer Support Team
>
>www.WhatDoTheyKnow.com is run by mySociety
>Project of a registered charity
>Donate to help us maintain this site: www.mysociety.org/donate/

**Comment by lizconlan** [comment]
sigh, reopening because I've broken the waffle board
