### ISSUE TITLE
Support paper-based workflows

### ISSUE THREAD

**Issue by sebbacon** [mysociety/alaveteli#469]
In many countries, an email-only workflow will only work as a campaigning platform.

The only sane way I can think of for supporting this is for an organisation to do the printing and scanning on behalf of individuals. It would work like this:

1) User visits Alaveteli, finds authority, writes request
2) Request is sent via email (where available) to give authority a chance to respond by email first (offering them a way to save money!)
3) After some period of time, an admin from the organisation running Alaveteli prints out the request, along with a reference number that is designed to be easily OCRd
4) Letter is put in the post, admin marks request as sent
5) Once a week, admin bulk scans any responses which are automatically uploaded to Alaveteli
6) Admin then logs into management interface.  Successfully OCRd responses are already attached to the relevant request. Unsuccessful ones are put in the holding pen.

I propose that the print-and-OCR part of the application be implemented as a black box that simply consumes and emits emails, so that Alaveteli can be used as the front end without modification (this is the approach being explored by Acceso Inteligente in Chile for using Alaveteli as the user-facing front end to their form-posting-page-scraping system).

We will need to consider integration with bulk scanners (presumably quite simple, but I don't know anything about them), and OCR technology.  Derek from TI Georgia has experience with Tesseract and thinks it can be made to work quite well.

The problem with supporting a paper-based workflow is that it will be masses of work for the organisation in question...

**Comment by garethrees** [comment]
https://lob.com/blog/mail-a-physical-letter-in-ruby/

**Comment by garethrees** [comment]
Going to close this as realistically we're not planning to build this in to Alaveteli in the foreseeable future.
