### ISSUE TITLE
Record and show relationships between bodies

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#4714]
There are relationships between bodies which, if reflected in the public bodies database, and shown on the site, could perhaps enable easier administration and browsing of the site. 

Examples of relationships:
* Owned by / owns. eg. 
https://www.whatdotheyknow.com/body?tag=companies_owned_by_local_gov
* A partner/member of another body, for example:
https://www.whatdotheyknow.com/body?tag=joint_committee
https://www.whatdotheyknow.com/body?tag=welsh_regional_partnership_board
* Department of
* Preceded by / succeeded by
* Scrutinised by  / scrutinises
* Receives funds from / is funded by

This feature could assist browsing the site, and might assist site administration. 

Currently administrators can manually add annotations which, for example, lead to a successor body when an organisation is marked "defunct".  If we linked such bodies in the database the system could present such links. 

It may be possible to do this with special tags eg.  Owned_by:Body_Name

**Comment by RichardTaylor** [comment]
This feature could help deter, or prevent, duplicated requests.

This feature could enable the automated detection of requests made to:

i/ Multiple subunits of an organisation
ii/ A subunit of an organisation and the organisation itsself

A specific example would be a request to an academy school, and a request to its multi-academy trust. In such a case a warning might be appropriate rather that preventing a request being made both locally to the school and to the trust.

**Comment by RichardTaylor** [comment]
A new example of a relationship between bodies

* Shares a site / address with, or "provides services at"

I came across this within the NHS organisation data at:

https://odsportal.digital.nhs.uk/

Their data includes "sites", and there can be multiple organisations at each site.

**Comment by RichardTaylor** [comment]
* A body entry marked as a subunit of a larger body could result in a placeholder page / URL which directs users to the parent body's page to make a request. 

Alternatively: 

* Imagine a "body" entry for say Border Force which is part of the Home Office. The Border Force page would only list requests to Border Force, but the Home Office page would list (and enable searching of) all requests to all parts of the Home Office

**Comment by RichardTaylor** [comment]
Consider how we could best deal with bodies which cease to exist in their own right, but become subsumed into others eg. 

https://www.whatdotheyknow.com/body/land_and_property_services
https://www.whatdotheyknow.com/body/northumberland_college

Notes:
>There may be a conflict between what serves our users best, and what is technically correct.
> Ideally we'd be both technically correct and serve our users as well as possible.
> One of the key things we try to do though is cut through complexity and confusion.

**Comment by RichardTaylor** [comment]
Sometimes a successor body has the same name as its predecessor: #6391

**Comment by RichardTaylor** [comment]
We can use the existing functions/tools to do this to an extent. 

eg. we list 

https://www.whatdotheyknow.com/body/at_medics_ltd

and on that page we state 

>We list [the GP surgeries run by AT Medics Ltd](https://www.whatdotheyknow.com/body?tag=run_by%3Aat_medics_ltd) separately.

and we link to those bodies tagged `run_by:at_medics_ltd`

Currently the links from the individual surgeries back to the parent entity are in each individual notes field.

**Comment by RichardTaylor** [comment]
* We could link from schools to their relevant local [education] authority and [Regional Schools Commissioner ](https://www.whatdotheyknow.com/body/list/regional_schools_commissioner).


* The [NHS Organisation Data Service](https://odsdatapoint.digital.nhs.uk/) records lots of relationships between bodies including: "Is Commissioned By", "Is Operated By", "Is a Sub-Division Of", "Is Directed By", as well as Geographic based information including Local Authority, Country (within the UK) etc.

**Comment by RichardTaylor** [comment]
More work has been done using the existing tagging system on WhatDoTheyKnow to record relationships between bodies eg. 

https://www.whatdotheyknow.com/body?tag=parent_mapit%3A2595

See 

* https://github.com/mysociety/whatdotheyknow-theme/pull/1330

and

* https://github.com/mysociety/whatdotheyknow-theme/issues/1334

**Comment by mdeuk** [comment]
> * We could link from schools to their relevant local [education] authority and [Regional Schools Commissioner ](https://www.whatdotheyknow.com/body/list/regional_schools_commissioner).

We actually contacted the Department for Education about an uncannily similar thing over the weekend (linking from education authorities to GIaS, the database identifiers are inconsistent with what they advertise) - once we’ve a reply on that one this would be a good set of tasks to join together.

**Comment by laurentS** [comment]
Jumping in from madada.fr here to mention that we are facing a similar situation with cities merging or splitting (a game they seem to love playing over here). We have addressed this by tagging "old" cities as `defunct` and adding a note to point to the "new" one, but this is very clunky to do, so I'm modifying the code so that we can use a tag like `defunct:<url_name of new body>` which would render as something more useful without affecting current functionality.

**Comment by mdeuk** [comment]
> We have addressed this by tagging "old" cities as `defunct` and adding a note to point to the "new" one, but this is very clunky to do

Agreed - that’s generally what happens on WDTK. When it’s multiple bodies merging into one (or splitting), a tag note is often used. 

> I'm modifying the code so that we can use a tag like `defunct:<url_name of new body>` which would render as something more useful without affecting current functionality.

This sounds good. One concern that may, or may not, be an issue, is that some `url_name` parameters might get reused [^1] - so there may need to be a mechanism to account for that… perhaps the body ID? https://github.com/mysociety/alaveteli/issues/6535

[^1]: for example, WDTK lists a lot of companies, which are government controlled. If there is a significant change to constitution, it is generally part of the process to make one defunct, and add a successor - but, often the `url_name` will carry over.

**Comment by garethrees** [comment]
This is desirable, but unlikely to be worked on in the next 12 months so closing for now.
