### ISSUE TITLE
Remove 'Pravo Da Znam' from http://alaveteli.org/deployments

### ISSUE THREAD

**Issue by Gemmamysoc** [mysociety/alaveteli#4733]
It's definitely dead, now confirmed by [this research](https://techfails.transparencee.org/):

"In Bosnia and Herzegovina, the organisation Zasto ne? tried to localize the Alaveteli tool for freedom of information requests but could not find thematic partners that would take over and develop the tool. Today their platform that was called Pravo Da Znam (pravodaznam.ba) does not exist anymore.

"In the end, we didn’t do it: couldn’t’ raise funding on our own. There were also no other organizations from those who deals with this issue who would want to pick it up”, says Darko Brakn from Zasto ne?."

**Comment by garethrees** [comment]
We've removed spain, so yes.

**Comment by garethrees** [comment]
Fixed by https://github.com/mysociety/alaveteli/pull/4736
