### ISSUE TITLE
Don't apply censor rules to OutgoingMessage#body in AdminOutgoingMessagesController#edit

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#4760]
Censor rules are being applied to message text on outgoing message admin pages such as:

https://www.whatdotheyknow.com/admin/outgoing_messages/449151/edit

A consequence of this is that if an administrator:

1. Implements a censor rule which impacts an outgoing message
2. Changes the prominence of that message via the message admin page

that results in the outgoing message text with the censor rule applied being saved as the outgoing message.  The record of the edit shows the version with the censor rule applied as both the before, and after, and there is no record accessible of the request prior to the censor rule. 

Is applying censor rules to message text on outgoing message admin pages new? Is it a bug?

The lack of a record of the original message text in these circumstances is an issue which needs considering.

**Comment by garethrees** [comment]
I don't think this has crept in recently.

I did wonder whether dd00661123379ccb508a7422b152c17769f7501d introduced this, but we've been applying censor rules inside `OutgoingMessage#body` for [ages](https://github.com/mysociety/alaveteli/commit/3e63196fe2268c1ea4618a261bb18b76a81bacf6#diff-e2ef7bdc0342352c8c6a5167b589b11aR96).

I think what we need to do here is:

* Add `OutgoingMessage#raw_body=`:

```ruby
def raw_body=(text)
  write_attribute(:body, text)
end
```

* Use `raw_body` in the [edit form](https://github.com/mysociety/alaveteli/blob/0.31.0.0/app/views/admin_outgoing_message/edit.html.erb#L23).

That way this form would be unaffected by any text masks or censor rules.

**Comment by garethrees** [comment]
Alternatively could use a [`text_area_tag`](https://api.rubyonrails.org/v4.2.10/classes/ActionView/Helpers/FormTagHelper.html#method-i-text_area_tag), which should allow us to update `body=` but present `raw_body` as the default value.

**Comment by lizconlan** [comment]
I think there are 2 problems here:

1) Edit screen presents like this (and making changes - incorrectly - permanently applies a redaction)
<img width="819" alt="screen shot 2018-10-15 at 13 47 21" src="https://user-images.githubusercontent.com/27760/46952903-26cc8c00-d084-11e8-83c1-6d5bcdeba889.png">
2) The redaction is applied to the Event log
<img width="902" alt="screen shot 2018-10-15 at 14 15 31" src="https://user-images.githubusercontent.com/27760/46953135-da358080-d084-11e8-878c-d11bb7ec9051.png">

(Screenshots made using the sample data, the redaction set up for testing purposes switches out "badger" for "[REDACTED]")
