### ISSUE TITLE
Multiple allow_new_responses_from updates on a single request

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#4776]
> On the request at:
> 
> https://www.whatdotheyknow.com/admin/requests/412220
> 
> there are 82 events in quick succession closing the request to new
> responses. They're dated around
> 
> 2018-06-22 03:46:06 +0100
> 
> and the event records say
> 
> allow_new_responses_from: authority_only => nobody
> editor: InfoRequest.stop_new_responses_on_old_requests
> 
> 
> As this looks unusual I'm flagging it in case any action needs to be
> taken or if it's indicative of a bug.
> 
> 
> Regards
> 
> Richard

- [ ] Should clean up the repeated events once this is fixed to make the admin pages easier to use.

**Comment by garethrees** [comment]
I'm not entirely sure what's wrong here yet, but here's some initial thinking:

* The events all got created on 2018-06-22
* We [introduced event logging for `stop_new_responses_on_old_requests`](https://github.com/mysociety/alaveteli/commit/0f7994989a7608b6f1eae101e73160994fd13747) about a month prior (2018-02-21)

I wonder if somehow its finding the same request multiple times, and then logging the event for each instance of the same request.

In the previous code, where we used a direct SQL update, this wouldn't have been noticeable as we'd have just updated the attribute several times without logging events.

I _think_ the best place to start looking here would be the query.

**Comment by RichardTaylor** [comment]
This is an ongoing issue; there are many tens of these updates in the /admin/timeline event log (and presumably appear on the request admin page in due course) in respect of:

https://www.whatdotheyknow.com/admin/requests/483739

There are many other requests with a handful, rather than many tens, of such updates. 


![screen shot 2018-08-12 at 18 26 58](https://user-images.githubusercontent.com/547695/44004662-bacf3474-9e5d-11e8-8f8c-c4d852f723a9.png)

**Comment by schlos** [comment]
I can also confirm that we see the same problem on ImamoPravoZnati.org timeline:

![Screenshot from 2022-05-11 16-38-24](https://user-images.githubusercontent.com/1014134/167876726-fa653870-9a2e-478d-b6a7-713a16fc87e2.png)

Multiple InfoRequest.stop_new_responses_on_old_requests events listed on timeline for the same Request ID.

Alaveteli version:
"alaveteli_git_commit": "4c2aa965c7c0e7f6c1c77d14b3ac711e66e12f07",
"alaveteli_version": "0.39.1.6",
"ruby_version": "2.5.1",

**Comment by RichardTaylor** [comment]
Note the impact of this issue can also be seen publicly on request history pages `/details/request/[title_slug]`

**Comment by RichardTaylor** [comment]
>The events all got created on 2018-06-22

looking at last night's (11 June 2022 Saturday) timeline on WDTK we have some ~6,000 of these events created from 03:45:10 to 03:53:21.  Each request to which events are added typically receives many events, sometimes many tens of events.
