### ISSUE TITLE
Authority answered, but not on WDTK

### ISSUE THREAD

**Issue by ajparsons** [mysociety/alaveteli#4802]
As noted in an annotation by someone else, this authority has updated their disclosure log with the answer - but it never got back to WDTK.

https://www.whatdotheyknow.com/request/foi_statistics_for_2017_127#comment-84570

Would be good to track down what happened and which end the problem is on.

**Comment by garethrees** [comment]
Moved to https://github.com/mysociety/sysadmin/issues/1054
