### ISSUE TITLE
'unhappy' post-status screens not formatted correctly

### ISSUE THREAD

**Issue by ajparsons** [mysociety/alaveteli#4811]
Missing white area around text used on rest of site. 

![image](https://user-images.githubusercontent.com/8157058/44144836-fe083c48-a080-11e8-89b4-3eb939c436b3.png)

**Comment by garethrees** [comment]
Its not broken as such – that's just how it is.

We're going to improve this a bit in https://github.com/mysociety/whatdotheyknow-theme/issues/319 though.

Going to close this, and maybe write a new improvement issue after we've done https://github.com/mysociety/whatdotheyknow-theme/issues/319.
