### ISSUE TITLE
Add note on the authority page if not subject to FOI

### ISSUE THREAD

**Issue by lizconlan** [mysociety/alaveteli#4814]
Add a note for authorities tagged `foi_no` on the authority page, like the note added to the request page by #4499 

<img width="642" alt="screen shot 2018-08-16 at 10 39 14" src="https://user-images.githubusercontent.com/27760/44201481-39d4e580-a141-11e8-8525-307d212c31ee.png">

**Comment by RichardTaylor** [comment]
Are there many, or any, cases where a body is tagged both eir_only and foi_no, does what happens if both messages are displayed need considering?

**Comment by lizconlan** [comment]
> Are there many, or any, cases where a body is tagged both eir_only and foi_no

It looks like there are currently 5 cases where this could happen.

Is it a valid combination? I would be happy to resolve it if not - although would we ideally need to add something in the admin interface to either prevent further cases or to warn that the combo is not recommended?

Alternatively if we only want one of the messages to appear, which should "win"?

> does what happens if both messages are displayed need considering?

With both messages it looks like this:

<img width="569" alt="screen shot 2018-09-12 at 10 09 26" src="https://user-images.githubusercontent.com/27760/45414761-06b84000-b674-11e8-8e51-f5aa8b3b7b96.png">

...or with some dummy notes text...

<img width="1034" alt="screen shot 2018-09-12 at 10 12 09" src="https://user-images.githubusercontent.com/27760/45414950-67e01380-b674-11e8-9a4e-ecc114077b35.png">

**Comment by RichardTaylor** [comment]
In the case of an eir_only body there is a legal obligation to respond to environmental information requests so in those cases saying "is not legally obliged to respond" would be misleading.

**Comment by lizconlan** [comment]
Thanks @RichardTaylor I'll add some code to only show the "not legally obliged to respond" message if it's not also "eir_only" ... and I should probably add the same logic to the request page version for consistency.

**Comment by garethrees** [comment]
Is `eir_only` _and_ `foi_no` a valid combination? If not, then we can avoid the complexity this would introduce.

**Comment by lizconlan** [comment]
Ok, new plan...

If the authority is tagged `eir_only` (ignoring the `foi_no` tag, if present):
<img width="534" alt="screen shot 2018-09-21 at 16 09 18" src="https://user-images.githubusercontent.com/27760/45889624-d598e780-bdb8-11e8-947e-d3cb872597e4.png">

If the authority if tagged `foi_no`:
<img width="559" alt="screen shot 2018-09-21 at 16 11 13" src="https://user-images.githubusercontent.com/27760/45889689-011bd200-bdb9-11e8-904a-548bdabc6e3b.png">
