### ISSUE TITLE
how to install on shared host?

### ISSUE THREAD

**Issue by petrk94** [mysociety/alaveteli#4828]
Hello,
I looked for something like this, but it seems to be complicated to run on a shared host due it need some root things, right?
Is there any possibility to run it on shared host?

Thanks

**Comment by garethrees** [comment]
Hi @petrk94,

You'll need root access to install Alaveteli, yes.

I'd recommend looking for a cloud-based VPS provider. Here are some examples:

* https://www.bytemark.co.uk/cloud-hosting/
* https://www.scaleway.com/virtual-cloud-servers/
* https://www.linode.com/
* https://www.digitalocean.com/products/droplets/

We use [dedicated bare metal servers from Bytemark](https://www.bytemark.co.uk/dedicated/) at mySociety. Do get in touch on the [alaveteli-dev](https://groups.google.com/forum/#!forum/alaveteli-dev) mailing list for technical assistance. I'm sure others there will be using some sort of cloud services to run their Alaveteli installs.

**Comment by petrk94** [comment]
Ah I see @garethrees.
Thank you for providing me some provide for this. I will give it a try
