### ISSUE TITLE
List of substantial changes between 0.31 and develop

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#4833]
Required for https://github.com/mysociety/alaveteli/issues/4615.

0.32 is going to be a big release. First job is going to be to enumerate what's in it so that we can identify any extra work that needs doing to make individual features work for reusers.

I guess I'd go about this by:

* Getting the list of commits between the two refs
* Grouping them by PR (I assume we can do this with some git-fu and looking at the merge commits):

We can then (not part of this issue, but added for context) take a run through each grouping and inspect for incompatibilities:

```
# Summary: Added imagemagick to list of required packages
# Incompatibilities: Check that imagemagick package is installable on all supported platforms
# Upgrade notes: Install imagemagick package
27ad392f2 Merge branch '4778-imagemagick-package' into develop
   98ac14acc Add imagemagick to package files
   24d673a97 Sort package lists
```

**Comment by garethrees** [comment]
WIP https://gist.github.com/lizconlan/b7da0839ff759164f90e26233f1ba55e

**Comment by garethrees** [comment]
Done 💥

**Comment by lizconlan** [comment]
test
