### ISSUE TITLE
NGINX example config doesn't serve cached attachments

### ISSUE THREAD

**Issue by kimoensi** [mysociety/alaveteli#4841]
As you can see the response of the authority to the FOI request below .

http://www.informini.org/ar/request/tqryr_lmndwby_hwl_mlf_lkhllt_lml

The authority attached 3 images. These images can be downloaded from  "**action**" button when you choose "**Download a zip file of all correspondence**". 
But when you try to click directly from their response it show the 404 NGIX error.
example : http://www.informini.org/ar/request/5/response/18/attach/3/img080.jpg?cookie_passthrough=1 

It can be an error when parsing attachment or bad configuration, and how to solve it!
Thank you

**Comment by garethrees** [comment]
Oh, that's confusing.

Have you had a look at the Rails logs (`APP_ROOT/log/production.log`)? It would be worth seeing if any error messages appear when you try to load the attachment.

**Comment by garethrees** [comment]
We've had a bit of a look in to this and can't see anything _obviously_ wrong.

It would be good to see the following:

* Your nginx configuration
* The nginx and rails log lines of a successful request for a cached attachment
* The nginx and rails log lines of an unsuccessful request for a cached attachment

Maybe with those we can try to replicate the issue.

**Comment by kimoensi** [comment]
The issue is about the Extraction of image attachments. 
The other formats (pdf, word, xlsx etc ...) works fine except image files 

Example :
word file (OK) -  http://www.informini.org/fr/request/rsl_shkr_6#incoming-49 
image file (KO) -  http://www.informini.org/fr/request/liste_des_associations_ayant_rec#incoming-58

**Comment by garethrees** [comment]
Hi @kimoensi,

That's very strange, but really we'd need to see the [information above](https://github.com/mysociety/alaveteli/issues/4841#issuecomment-429265562) to diagnose further.
