### ISSUE TITLE
Drop "support" for Ruby 2.2

### ISSUE THREAD

**Issue by lizconlan** [mysociety/alaveteli#4842]
Official support ended on 2018-06-20

https://www.ruby-lang.org/en/news/2018/06/20/support-of-ruby-2-2-has-ended/

**Comment by lizconlan** [comment]
Requires #4542

**Comment by lizconlan** [comment]
Although we don't officially support 2.2, it's worth noting this for reusers when 2.3 becomes the oldest supported version

**Comment by garethrees** [comment]
Remove https://github.com/mysociety/alaveteli/commit/485d0092f once complete
