### ISSUE TITLE
User menu overlaps navigation for languages with long translations

### ISSUE THREAD

**Issue by lizconlan** [mysociety/alaveteli#4858]
Affects pro and normal

Theme "none":
<img width="219" alt="screen shot 2018-09-18 at 13 38 49" src="https://user-images.githubusercontent.com/27760/45688145-80569f00-bb48-11e8-8209-a25550a0aa46.png">

Alavetelitheme:
<img width="228" alt="screen shot 2018-09-18 at 13 35 53" src="https://user-images.githubusercontent.com/27760/45688170-92d0d880-bb48-11e8-8db9-fa4692066006.png">

Will happen IRL for pro users on the Belgium site if we upgrade them:
<img width="329" alt="screen shot 2018-09-18 at 13 27 32" src="https://user-images.githubusercontent.com/27760/45688205-b09e3d80-bb48-11e8-9e70-1c0975e733ac.png">

Currently the menu bar wraps, pushing the user menu link down to the next line:
<img width="379" alt="screen shot 2018-09-18 at 13 29 01" src="https://user-images.githubusercontent.com/27760/45688297-eba07100-bb48-11e8-8f68-eff207a458cb.png">

**Comment by wrightmartin** [comment]
This is... tricky

**Comment by lizconlan** [comment]
Just slightly shorter translations would help

<img width="1067" alt="screen shot 2018-09-26 at 11 31 33" src="https://user-images.githubusercontent.com/27760/46074784-781de580-c180-11e8-9365-71830d7317fd.png">

**Comment by lizconlan** [comment]
(Our Belgian partners have kindly provided some alternative translations if we can't get a technical fix into the next release)

**Comment by wrightmartin** [comment]
Complications arising so far
- The non-JS version is winding up to be really, really complex. I suggest we ditch the menu altogether for non-JS, and just link directly to the user's page. However that requires that all the links currently available in the user dropdown menu are added to the profile page https://github.com/mysociety/alaveteli/blob/develop/app/views/general/_log_in_bar.html.erb

- In core styles, we don't turn the language links into a menu, they are a list of items. If installs have 3 or more languages this starts to look messy
