### ISSUE TITLE
Extract embedded attachments from Microsoft Office documents

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#4861]
We've seen a couple of cases ([example](https://www.whatdotheyknow.com/request/legal_and_financial_advice_about#comment-85006)) where authorities send a word document (`.docx`) with embedded attachments that seem impossible to open, presumably unless you have some specific version of Office.

It turns out [you _can_ extract](https://discussions.apple.com/thread/3054435) them:

* Change extension from `.docx` to `.zip`
* `unzip PATH_TO_FILE.zip`
* Attachments are in `word/embeddings`
* PDFs get extracted with a `.bin` extension; change them to `.pdf`

```
$ tree .
.
├── 20180027329releasedwithredactions.zip
├── [Content_Types].xml
├── _rels
│   └── .rels
├── docProps
│   ├── app.xml
│   └── core.xml
└── word
    ├── _rels
    │   └── document.xml.rels
    ├── document.xml
    ├── embeddings
    │   ├── Microsoft_Word_Document.docx
    │   ├── Microsoft_Word_Document1.docx
    │   ├── Microsoft_Word_Document2.docx
    │   ├── Microsoft_Word_Document3.docx
    │   ├── oleObject1.bin
    │   ├── oleObject2.bin
    │   └── oleObject3.bin
    ├── fontTable.xml
    ├── media
    │   ├── image1.emf
    │   ├── image2.emf
    │   ├── image3.emf
    │   ├── image4.emf
    │   ├── image5.emf
    │   ├── image6.emf
    │   └── image7.emf
    ├── settings.xml
    ├── styles.xml
    ├── theme
    │   └── theme1.xml
    └── webSettings.xml

7 directories, 26 files
```

You _can_ do this without the command line, but I ran in to the problem of the `.zip` extracting to a `.cpgz`. To extract this you can try downloading with a different browser (didn't work for me) or download The Unarchiver. (Via http://osxdaily.com/2013/02/13/open-zip-cpgz-file/)

**Comment by garethrees** [comment]
Duplicate of https://github.com/mysociety/alaveteli/issues/62

**Comment by aravindkathiroju** [comment]
This doesn’t work for some reason. I have an outlook oleobject and when I change it extension
To .msg , outlook com interface doesn’t recognise or read it.
