### ISSUE TITLE
Encourage sharing after successful request

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#4886]
Imported from https://github.com/mysociety/alaveteli-project/issues/67.

> Social media buttons are currently on the top right of a request page but they are not especially prominent or reactive (and if you've scrolled right down to the foot of the request - the point at which you might be thinking 'well that was very satisfying' - they're not visible).
> 
> What if, when a user marks a request as 
> > I've received some of the information
> 
> or
> 
> >I've received all the information 
> 
> it initiated a prompt that said something like "Is this a request worth sharing? Tell the story on Twitter or Facebook."?
> 
> Perhaps the same prompt could also be triggered on successful requests when _any_ reader reaches the foot of the page.
> 
> This also keys in with #66, where people could be encouraged to nominate the best requests for awards.
> 
> Note for context: people do frequently tweet the requests they are browsing, but very often it's without any extra text other than the link. Perhaps using a word like 'story' would encourage more detail?
> 

At the moment we just say "thanks":

![screen shot 2018-10-08 at 13 01 27](https://user-images.githubusercontent.com/282788/46607895-92e64780-cafa-11e8-8b14-feab80e80de8.png)

We do have a better flash message when you've just made your request, but _this_ is the point where you might get a rush from getting info for the first time.

**Comment by garethrees** [comment]
We _do_ do this on WDTK:

![screen shot 2018-10-11 at 11 17 53](https://user-images.githubusercontent.com/282788/46797540-55c2c500-cd47-11e8-8fc9-87612048cfdb.png)

Here's some data on that:


Destination | Source | Events
-- | -- | --
Twitter Exit | Request sidebar | 875
Facebook Exit | Request sidebar | 638
Twitter Exit | Share Request | 452
Facebook Exit | Share Request | 380

This data is from 2018-01-01 – 2018-06-30 ([analytics URL](https://analytics.google.com/analytics/web/#/report/content-event-events/a24614779w48006686p48388638/_u.date00=20180101&_u.date01=20180630&explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.secSegmentId=analytics.eventLabel&explorer-table.plotKeys=%5B%5D)).

So actually, we get more shares from the sidebar, but we do get lots more shares from the above so I'd say its working well, and we should port this back to Alaveteli core, rather than a WDTK-only customisation.

**Comment by Gemmamysoc** [comment]
This is cool! I still think we could make the wording of this better though - something to say that we love hearing about why people make FOI requests, what they do with the info and why they use WDTK to do so, so they should feelf ree to contatc us if they want to share their FOI story with us. cc'ing @MyfanwyNixon

**Comment by MyfanwyNixon** [comment]
Oh that's great that we already do it, but yeah - so I guess these are the relevant parts of my initial post:

>Note for context: people do frequently tweet the requests they are browsing, but very often it's without any extra text other than the link. Perhaps using a word like 'story' would encourage more detail.

and for the wording:
> "Is this a request worth sharing? Tell the story on Twitter or Facebook."

And to pick up on Gemma's point we could also add a line:

> We often write about successful or remarkable FOI requests on the mySociety blog [LINK]: it helps others to understand what FOI is, and how they can use it themselves. If you think this is a good candidate for a case study, please drop us a line!*


\* [email address could be communications@mysociety.org or WDTK's?]
