### ISSUE TITLE
Add button to close user account

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#4910]
We now have `User#closed_at` that prevents users signing in.

We should have a button that allows admins to permanently close a user account.

Required by https://github.com/mysociety/alaveteli/issues/3148.

**Comment by RichardTaylor** [comment]
It should be made clear what this "closed" status means. (Prevention of login, and alert mails, though not a prevention of transactional emails / notifications relating to a users' own requests?)

Perhaps notifications relating to a users' own requests should also be prevented?

A user who can't login to classify a response shouldn't be asked to do so. (Comment arises from support mail on WhatDoTheyKnow from a user in this position)

**Comment by mdeuk** [comment]
> A user who can't login to classify a response shouldn't be asked to do so. (Comment arises from support mail on WhatDoTheyKnow from a user in this position)

I've raised #5090 for this as we've had another WDTK user complain about being asked to do just that this weekend.

**Comment by RichardTaylor** [comment]
I think this was done by https://github.com/mysociety/alaveteli/pull/4869

**Comment by garethrees** [comment]
> I think this was done by https://github.com/mysociety/alaveteli/pull/4869

That was Close and Anonymise. This issue is just for a "Close" button (closing does different things to adding `ban_text`).

**Comment by garethrees** [comment]
Closing in favour of https://github.com/mysociety/alaveteli/issues/7646.
