### ISSUE TITLE
Improve censor rules created by anonymise and close user account operation

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#4922]
Following the closure of #3074 this is a new ticket for improving the censor rule created on the automated anonomising and closing of an account. 

The issue is a censor rule for "Fred Blogs" doesn't catch mentions of eg. "Mr Blogs" in the text. 

Consider cases where a name (surname or firstname) is a common word; and that some user-names can contain initials, some usernames are names of organisations etc. 

Logic eg. having a separate censor rule for each "word" within a username of 4 or more letters might suffice in the vast majority of cases; and administrators can always delete/edit automatically created censor rules and create replacements.

**Comment by garethrees** [comment]
https://github.com/basecamp/name_of_person could be useful here

**Comment by RichardTaylor** [comment]
We might also want to catch cases where non-breaking spaces rather than spaces are used between elements of a name. 

Commonly we manually create censor rules which work on:

> `firstname&#160;lastname`

**Comment by gbp** [comment]
Testing this `\b(M([a-z]+)\s+)?(Firstname(\s+Lastname)?|Lastname(\s+Firstname)?)\b\s*[.,]?` rule, thinking it could work quite well.

**Comment by HelenWDTK** [comment]
> Testing this \b(M([a-z]+)\s+)?(Firstname(\s+Lastname)?|Lastname(\s+Firstname)?)\b\s*[.,]? rule, thinking it could work quite well.

The above rule worked extremely well, being ineffective in redacting the plain text of correspondence in just one case where the user's first name was in all caps. This redacted the name from over 1,000 requests that the standard default rule had not worked on. Making a rule like this be applied by default would significantly reduce the admin burden in responding to RtE and RtO cases.

**Comment by garethrees** [comment]
This is desirable, but unlikely to be worked on in the next 12 months so closing for now.
