### ISSUE TITLE
Add reCAPTCHA to UserController#contact

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#4939]
Add another barrier to automated spammers using the user to user messaging to propagate spam.

We can just show it for users in other countries to reduce impact on genuine users.

**Comment by RichardTaylor** [comment]
Is it worth checking if recent suspected spamming users had IPs from other countries? The recent  users in question were:

https://www.whatdotheyknow.com/admin/users/170126
https://www.whatdotheyknow.com/admin/users/170042
https://www.whatdotheyknow.com/admin/users/169310

**Comment by lizconlan** [comment]
Without digging into too much detail, a bunch of hits on the contact url on the day[1] those spammers were caught came from IP blocks that identify as from the US (which makes me think they were either spoofed or the spam was being automated and run from on a hosted virtual server)

If it was a script being run then a captcha might have stopped it, or at least slowed it down

[1] log file dated 2018-10-26

**Comment by gbp** [comment]
Any idea if the users who received spam had consecutive IDs? Maybe #4410 issue should be looked at too.

**Comment by mdeuk** [comment]
Another spamming user this morning which has an uncannily similar format (style of name / style of message etc) - https://www.whatdotheyknow.com/admin/users/170189

@gbp The user reporting this to us today is 3339, however, looking at yesterday's reports we seem to have had an odd mix - 18, 20187, 101615, 112280 - so, I'm not sure if we're simply seeing a RNG in effect (I'm 2779 and haven't had any - lucky me!), or, if there's something more odd in the pattern.
