### ISSUE TITLE
User sent request confirmation link but post redirect token does not exist

### ISSUE THREAD

**Issue by lizconlan** [mysociety/alaveteli#4944]
One - recent (at time of writing) - manifestation of a problem with PostRedirect tokens. Rather than the missing PostRedirect link, this describes a broken link that remains associated with the user.

A non-logged in user created a new request the signed up for an account as the last step in the process. When the clicked on the link they were sent by email, nothing happened and they had to ask a volunteer admin to intervene to verify their account and create/send the request.

From the logs, we can see that they appear to have submitted the signup form multiple times (not sure if significant, might indicate connectivity issues, but the blank authenticity token is interesting):

```
I, [2018-11-05T13:49:19.770167 #10601]  INFO -- :   Parameters: {"utf8"=>"✓", "authenticity_token"=>"", "user_signup"=>{"name"=>"[FILTERED]", "email"=>"[FILTERED]", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}, "token"=>"[MATCHING_TOKEN]", "modal"=>"", "commit"=>"Sign up"}

I, [2018-11-05T13:50:46.842133 #9665]  INFO -- :   Parameters: {"utf8"=>"✓", "authenticity_token"=>"", "user_signup"=>{"name"=>"[FILTERED]", "email"=>"[FILTERED]", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}, "token"=>"[MATCHING_TOKEN]", "modal"=>"", "commit"=>"Sign up"}

I, [2018-11-05T13:51:35.658625 #10345]  INFO -- :   Parameters: {"utf8"=>"✓", "authenticity_token"=>"", "user_signup"=>{"name"=>"[FILTERED]", "email"=>"[FILTERED]", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}, "token"=>"[MATCHING_TOKEN]", "modal"=>"", "commit"=>"Sign up"}
```

...then when they've attempted to use the link, we see this:

```
I, [2018-11-05T13:52:36.645293 #10601]  INFO -- : Started GET "/c/[MATCHING_TOKEN]" for [FILTERED] at 2018-11-05 13:52:36 +0000
I, [2018-11-05T13:52:36.652261 #10601]  INFO -- : Processing by Users::ConfirmationsController#confirm as HTML
W, [2018-11-05T13:52:37.014509 #10601]  WARN -- : Missing post redirect token.
```

The warning is raised here: https://github.com/mysociety/alaveteli/blob/e4e7a3fbee8783567bc82a6f98254b6f7b1fe51e/app/controllers/application_controller.rb#L361-L378

...which makes me wonder if this is a session handling problem

For a bonus weirdness point, the user admin page reported a track email sent before the account was created:

![screenshot](https://user-images.githubusercontent.com/27760/48060942-566b4180-e1b5-11e8-8f82-6a1f92733452.png)

**Comment by garethrees** [comment]
So is this effectively the opposite of https://github.com/mysociety/alaveteli/issues/4674. In that case, clicking the URL in the email (presumably) sent their request without completing the account creation process.

In this case, they get a seemingly valid token, but confirm their account, but can't send their request?

**Comment by lizconlan** [comment]
I think the account remained unconfirmed until a volunteer stepped in to assist

**Comment by mdeuk** [comment]
We've had another two potential instances of this on WhatDoTheyKnow;

User 173590 - signed up 07/01/19, reports clicking the verify link (account showed as 'Email confirmed' true); but, request only sent after admin manually clicked the verify email token on 4/2/19.

User 176220 - signed up today; again reports having clicked the verify link, however, request only sent after admin manually clicked the verify email token in the admin console.

**Comment by MattK1234** [comment]
I'm pretty sure I've dealt with this same issue today on WhatDoTheyKnow:

User 178602 signed up on 21/03/2019. They emailed recently to say they clicked the link when signing up, but couldn't find their request (571744). Account admin page showed email confirmed as true but no request. I clicked the email token in the admin page which then sent the request.

**Comment by garethrees** [comment]
Closing as we haven't heard much more about this and it seems very occasional.
