### ISSUE TITLE
Add Ubuntu 18.04 LTS (Bionic) support to install scripts

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#4971]

**Comment by schlos** [comment]
Hi @garethrees I saw in #3211 that you consider skipping 16.04 support and going straight to Bionic Beaver. What are your plans to support 18.04 in your install scripts? Do you have any timeline in mind?

Did anybody try to install Alaveteli on 18.04 and are there any modifications to Alaveteli necessary to run on 18.04?

Thanks!

**Comment by garethrees** [comment]
No timelines at the moment sorry. If you give it a go please do note issues here or in [alaveteli-dev](https://groups.google.com/forum/#!forum/alaveteli-dev).

**Comment by schlos** [comment]
Other than #5025, there was no other issues with install on Bionic. 
I have CSS/JS issue in Assets folder (CSS/JS is not there or has wrong filename) but I think it's just theme regeneration issue which I didn't have yet time to investigate.
I'll report if there are any other issues related to Bionic.
