### ISSUE TITLE
Number of requests in listing doesn't take into account prominence

### ISSUE THREAD

**Issue by dcabo** [mysociety/alaveteli#498]
The number of requests made to a public body is calculated by counting the number of InfoRequest objects in the database, without taking into account whether they're backpage, requester-only or hidden. This results in confusion when displaying a public body page, since the number of requests doesn't match the list returned by Xapian.

**Comment by lizconlan** [comment]
This was fixed in [release 0.22](https://github.com/mysociety/alaveteli/releases/tag/0.22.0.0) (via 39d91dcd47338f). See also #2215
