### ISSUE TITLE
Don't show followup options if the request is closed to new responses

### ISSUE THREAD

**Issue by lizconlan** [mysociety/alaveteli#4985]
If the request is closed to new responses, you currently still get shown some of the "Send a reply" template and a choice of contact options in addition to the "Follow ups and new responses have been stopped to prevent spam" message.

<img width="747" alt="screen shot 2018-11-30 at 12 25 09" src="https://user-images.githubusercontent.com/27760/49289252-2739ae80-f49b-11e8-8733-ecb186a88195.png">

(And maybe the "Write a reply" option in the menu (on the request page) should be disabled as well?)

**Comment by garethrees** [comment]
Related to https://github.com/mysociety/alaveteli/issues/4524.
