### ISSUE TITLE
Automatically redeliver messages sent to holding pen when there's a single guess

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#4990]
Extracted from https://github.com/mysociety/alaveteli/issues/4584.

If there's a single guess, we can be reasonably confident that the message will go to the right place.

We'll want to be sure that this auto-delivery is recorded as an event.

**Comment by RichardTaylor** [comment]
>We'll want to be sure that this auto-delivery is recorded as an event. 

Perhaps an email to the team/support address could be generated, maybe for each event, or perhaps as a daily digest, reporting what had been done. Such an email could contain enough material to sense-check the re-delivery.  

I suspect the "guesses" are sufficiently good, especially when there is only one, this wouldn't be needed though.

**Comment by RichardTaylor** [comment]
Can we add if the there's a header like

>X-Delivered-Suffix: -nnnnnn-xxxxxxxxx

and nnnnnn matches a request ID and xxxxxxxxx matches the secret just send it to that ID?

**Comment by FOIMonkey** [comment]
> Can we add if the there's a header like
> 
> X-Delivered-Suffix: -nnnnnn-xxxxxxxxx
> 
> and nnnnnn matches a request ID and xxxxxxxxx matches the secret just send it to that ID?

+1 We've had an uptick of BCC'd mail ending up in the holding pen recently that this would have helped to deliver.

**Comment by garethrees** [comment]
> Can we add if the there's a header like `X-Delivered-Suffix: -nnnnnn-xxxxxxxxx`

That should be added to the "guessing" mechanism (https://github.com/mysociety/alaveteli/issues/4990) so out of scope for _this_ issue.
