### ISSUE TITLE
Old email stuck in POP mailbox

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#5005]
While completing https://github.com/mysociety/sysadmin/issues/1036#issuecomment-443684254 we noticed an email stuck in the POP mailbox from ~ 3 months ago.

The message had been [received by the request](https://www.whatdotheyknow.com/request/school_library_resources_1353#incoming-1233899).

We had an `IncomingMessageError` for the email. It doesn't have a `retry_at` attribute:

```sql
foi=> SELECT id, created_at, updated_at, retry_at FROM incoming_message_errors WHERE id = 3;
 id |         created_at         |         updated_at         | retry_at
----+----------------------------+----------------------------+----------
  3 | 2018-09-17 07:36:33.090389 | 2018-09-17 07:36:33.094507 |
```

Here's what we think happened in this case.

We retrieve the mail, ingest it and set `received = true`:

https://github.com/mysociety/alaveteli/blob/8fe547d81646449203412d95a664f94001c83bab/lib/alaveteli_mail_poller.rb#L62-L63

We then try to delete the email in the mailbox:

https://github.com/mysociety/alaveteli/blob/8fe547d81646449203412d95a664f94001c83bab/lib/alaveteli_mail_poller.rb#L64

The error happens here.

We rescue the `Net::POPError` and send the [exception notification](https://groups.google.com/a/mysociety.org/d/msg/cron-alaveteli/cWFPjOPVy90/6P87mFtwCAAJ):

https://github.com/mysociety/alaveteli/blob/8fe547d81646449203412d95a664f94001c83bab/lib/alaveteli_mail_poller.rb#L66-L74

We then record the error as an `IncomingMessageError`: https://github.com/mysociety/alaveteli/blob/8fe547d81646449203412d95a664f94001c83bab/lib/alaveteli_mail_poller.rb#L75

We've previously set `received = true`, and that's passed as the second parameter to `record_error`.

We only set `retry_at` _if `received` is `false`_. https://github.com/mysociety/alaveteli/blob/8fe547d81646449203412d95a664f94001c83bab/lib/alaveteli_mail_poller.rb#L80-L82

This means that we don't try to receive it any more, and therefore it never gets deleted. https://github.com/mysociety/alaveteli/blob/8fe547d81646449203412d95a664f94001c83bab/lib/alaveteli_mail_poller.rb#L102-L104

**Comment by garethrees** [comment]
The error in the exception notification was:

```
A Net::POPError occurred in background at 2018-09-17 08:36:32 +0100 : 

  -ERR Disconnected for inactivity. 
  /opt/rbenv/versions/2.3.5/lib/ruby/2.3.0/net/pop.rb:1001:in `check_response' 

  ------------------------------- 
Backtrace: 
------------------------------- 

  /opt/rbenv/versions/2.3.5/lib/ruby/2.3.0/net/pop.rb:1001:in `check_response' 
  /opt/rbenv/versions/2.3.5/lib/ruby/2.3.0/net/pop.rb:960:in `dele' 
  /opt/rbenv/versions/2.3.5/lib/ruby/2.3.0/net/pop.rb:859:in `delete' 
  /data/vhost/www.whatdotheyknow.com/alaveteli-2018-09-05T08-32-15/lib/alaveteli_mail_poller.rb:64:in `get_mail' 
  /data/vhost/www.whatdotheyknow.com/alaveteli-2018-09-05T08-32-15/lib/alaveteli_mail_poller.rb:26:in `block (2 levels) in poll_for_incoming' 
  /opt/rbenv/versions/2.3.5/lib/ruby/2.3.0/net/pop.rb:666:in `each' 
  /opt/rbenv/versions/2.3.5/lib/ruby/2.3.0/net/pop.rb:666:in `each_mail' 
  /data/vhost/www.whatdotheyknow.com/alaveteli-2018-09-05T08-32-15/lib/alaveteli_mail_poller.rb:25:in `block in poll_for_incoming' 
  /data/vhost/www.whatdotheyknow.com/alaveteli-2018-09-05T08-32-15/lib/alaveteli_mail_poller.rb:115:in `start' 
  /data/vhost/www.whatdotheyknow.com/alaveteli-2018-09-05T08-32-15/lib/alaveteli_mail_poller.rb:24:in `poll_for_incoming' 
  /data/vhost/www.whatdotheyknow.com/alaveteli-2018-09-05T08-32-15/lib/alaveteli_mail_poller.rb:41:in `poll_for_incoming_loop' 
  /data/vhost/www.whatdotheyknow.com/alaveteli-2018-09-05T08-32-15/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/commands/runner.rb:62:in `<top (required)>' 
  /data/vhost/www.whatdotheyknow.com/alaveteli-2018-09-05T08-32-15/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/commands/runner.rb:62:in `eval' 
  /data/vhost/www.whatdotheyknow.com/alaveteli-2018-09-05T08-32-15/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/commands/runner.rb:62:in `<top (required)>' 
  /data/vhost/www.whatdotheyknow.com/alaveteli-2018-09-05T08-32-15/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:123:in `require' 
  /data/vhost/www.whatdotheyknow.com/alaveteli-2018-09-05T08-32-15/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:123:in `require_command!' 
  /data/vhost/www.whatdotheyknow.com/alaveteli-2018-09-05T08-32-15/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:90:in `runner' 
  /data/vhost/www.whatdotheyknow.com/alaveteli-2018-09-05T08-32-15/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:39:in `run_command!' 
  /data/vhost/www.whatdotheyknow.com/alaveteli-2018-09-05T08-32-15/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/commands.rb:17:in `<top (required)>' 
  bin/rails:4:in `require' 
  bin/rails:4:in `<main>' 

------------------------------- 
Data: 
------------------------------- 

  * data: {:mail=>"REDACTED", 
   :unique_id=>"0004258359f21e3d"} 
```

**Comment by garethrees** [comment]
Going to close this as we've only had one of these in the year or so that we've been running the poller.

We think it may have been a similar issue to https://github.com/mysociety/alaveteli/issues/4526, and hopefully fixed by https://github.com/mysociety/sysadmin/issues/1036.

**Comment by gbp** [comment]
We had another one of these today (for NL) which coincided with an apache restart.
