### ISSUE TITLE
docker

### ISSUE THREAD

**Issue by arruah** [mysociety/alaveteli#5007]
Is there a chance to do development and delivery through docker?

**Comment by garethrees** [comment]
Hi @arruah,

Its not in our plans at the moment, but its been attempted by other reusers https://groups.google.com/forum/#!searchin/alaveteli-dev/docker%7Csort:date/alaveteli-dev/DvvyvNGObJU/23aghIspYCMJ.

Going to close this issue as the mailing list is the best place for discussion until we make some concrete plans.
