### ISSUE TITLE
Investigate potential missing export data

### ISSUE THREAD

**Issue by lizconlan** [mysociety/alaveteli#5008]
The last export (cutoff date 20/11) of the User data produced around 19,000 records as compared to the prior export (from February) which produced 26,000.

Re-running the export produced similar numbers (a handful of records were missed on the original run due to what looked like transient errors in the anonymisation process).

Unless we've banned/excluded from reporting 7K users in that time we may have a problem with the export routine. We should examine a diff of the 2 datasets to try to work out what's happened here.

**Comment by lizconlan** [comment]
Happened again with latest export - 10k fewer users than expected. A quick examination of ~30 missing records shows only 8 are not active accounts so something is clearly wrong here.

**Comment by lizconlan** [comment]
Hoping this might have something to do with it ... re-running export for the user table only...

In export.rake
```diff
    #export non-personal user fields
    DataExport.csv_export( User,
                to_run,
                User.active.
-                  where("updated_at < ?", cut_off_date),
+                  where("created_at < ?", cut_off_date),
```

**Comment by garethrees** [comment]
See https://github.com/mysociety/alaveteli/issues/4636 – `User#updated_at` gets touched very regularly.

**Comment by lizconlan** [comment]
As an aside, exporting the User data seems slow (the expanded version has been running as a low priority task for over 24 hours now), probably because we're calling out to a third party API for every single record as part of the anonymisation process

**Comment by garethrees** [comment]
> See #4636 – `User#updated_at` gets touched very regularly.

This is now resolved, so I assume this should all work correctly. Will reopen if not.
