### ISSUE TITLE
The "history" changelog on a public body admin page isn't comprehensive

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#5011]
As a specific example the record of changes to a public body record on the public body admin page under the "History" heading doesn't include changes to tags. 

A tag change is also not noted at /admin/timeline

Not at all important, but it is an omission.

**Comment by garethrees** [comment]
Since this is identified as unimportant, I'm going to close until a specific omission is causing a specific problem. Thanks for ticketing though, as now this should appear in the search results 👍

**Comment by RichardTaylor** [comment]
More specific tickets:

* https://github.com/mysociety/alaveteli/issues/6556
* https://github.com/mysociety/alaveteli/issues/1294

**Comment by RichardTaylor** [comment]
Keywords: Event, Events, Log
