### ISSUE TITLE
Missing dependency in Ubuntu 18.04 'pdftk'

### ISSUE THREAD

**Issue by schlos** [mysociety/alaveteli#5025]
"E: Package 'pdftk' has no installation candidate"

In Ubuntu Bionic we're missing package which is part of install script (#4971).

The pdftk package in Ubuntu (and its upstream Debian package) was dropped due to its dependency on the now deprecated GCJ runtime.

https://askubuntu.com/questions/1028522/how-can-i-install-pdftk-in-ubuntu-18-04-and-later

**Comment by garethrees** [comment]
Required by https://github.com/mysociety/alaveteli/issues/4971

**Comment by garethrees** [comment]
@schlos how did you resolve this for http://imamopravoznati.org? Did you end up installing from the Cosmic repo as per https://askubuntu.com/a/1028983?

**Comment by Utopiah** [comment]
Quite important as it breaks installation on Windows Linux subsystem

**Comment by lizconlan** [comment]
Hi @Utopiah - you've commented on a closed ticket as (we thought) we'd fixed this for the latest release! Are you saying that this is broken in [Release  0.33](https://github.com/mysociety/alaveteli/releases/tag/0.33.0.0) or were you just agreeing that this was an important issue?

If you're installing manually, you'll need to add Cosmic's package list as a low priority APT source to get 'pdftk' per our install script https://github.com/mysociety/alaveteli/pull/5232/files#diff-d5eb0653888644638720a6b98d9d9f1d

**Comment by Utopiah** [comment]
Just agreeing that this was an important issue
