### ISSUE TITLE
Add Ruby 2.6 support

### ISSUE THREAD

**Issue by gbp** [mysociety/alaveteli#5038]
Originally Rails 4 wasn't going to run on Ruby 2.6 but due to [1] it now looks like this is possible. To get the specs passing we will need to monkey patch `ActionController::TestResponse` [2].

[1] https://github.com/ruby/bigdecimal/issues/114
[2] https://github.com/rails/rails/issues/34790#issuecomment-450502805

**Comment by garethrees** [comment]
- [ ] First step here is getting it in the build matrix as an allowed failure
