### ISSUE TITLE
Localised dates aren't parsed correctly when searching

### ISSUE THREAD

**Issue by sebbacon** [mysociety/alaveteli#504]
from György:

> We had problem with the localised datepicker, therefore I fixed them by hacking request controller (list method).
> The localised datepickker in hungarian translation gives date in other format then for the database query needed. (dd/mm/yyyy)

**Comment by schlos** [comment]
This is reproducible in ImamoPravoZnati v0.39.1.6.

On https://imamopravoznati.org/list/successful if you use date picker for entering date:

```
Made between
[  ... ] and [ .... ]
```

When on Croatian site, picked date will be entered in a date box n format: dd.mm.yyyy. (which is correct Croatian date format)
and it will not return any request:
https://imamopravoznati.org/list/successful?utf8=%E2%9C%93&query=&request_date_after=01.01.2022.&request_date_before=01.03.2022.&commit=Pretra%C5%BEite

For comparison, same web https://imamopravoznati.org/en/list/successful, when on EN site, date picked using date picker will be written as mm/dd/yyyy 
and it will return expected results:
https://imamopravoznati.org/en/list/successful?utf8=%E2%9C%93&query=&request_date_after=2022%2F01%2F01&request_date_before=2022%2F03%2F01&commit=Search

So issue is that date picker will use locale for date format, but Alaveteli middleware is not able to understand received date format.

If I can suggest maybe to always use same format produced in URL / sent to Alaveteli middleware, i.e. ISO 8601 (yyyy-mm-dd), more info: https://www.iso.org/iso-8601-date-and-time-format.html

**Comment by garethrees** [comment]
Could look at whether [`date_field`](https://blog.corsego.com/datetime-select-or-field) handles this with some normalisation under the hood.
