### ISSUE TITLE
GeoIP-database-contrib isn't installable

### ISSUE THREAD

**Issue by gbp** [mysociety/alaveteli#5040]
Due to deprecation of the [GeoLite Legacy databases](https://support.maxmind.com/geolite-legacy-discontinuation-notice/) we can't run CI builds or build Vagrant boxes.

> @lizconlan: with some additional digging, it looks like the underlying problem is that during the Jan 7th maintenance window, it looks like MaxMind have gone ahead and removed the v1 files from their site so the packages installer chokes while attempting the download; `geoipupdate` looks as though it should fetch the v2 files so that's a partial solution

> however...
the v2 files are a different format which the `geoip` gem we rely on does not understand them https://github.com/cjheath/geoip#featuresproblems

> we've had problems in the past where the geoip database was out of date and misidentifying users as being in the US (I _think_ what happened was an IP block or so was transferred between ISPs, possibly due to takeovers - e.g. PlusNet - etc) so keeping it up to date is definitely something we need to keep in mind https://github.com/mysociety/alaveteli/issues/2520

For a quick fix to get builds working again we could be to switch to `geoip-database`, this works as the CSV are included in the package

There seems to be some newer GeoIp replacements listed in https://github.com/cjheath/geoip/issues/75 so we should look at migrating to those at some point - possible the one [provided by MaxMind](https://github.com/maxmind/MaxMind-DB-Reader-ruby) once we drop Ruby <2.3 #4541 #4542 #4842

**Comment by garethrees** [comment]
Try to fix in https://github.com/mysociety/alaveteli/issues/5229

**Comment by garethrees** [comment]
http://www.rubygeocoder.com/ might be worth a look here.

**Comment by gbp** [comment]
> http://www.rubygeocoder.com/ might be worth a look here.

That's normally my go to gem for geocoding and... TIL it can use MaxMind with local downloaded DB see: https://github.com/alexreisner/geocoder/blob/master/test/unit/lookups/maxmind_local_test.rb evens provides rake tasks for downloading them too.

Looks like a good solution.
