### ISSUE TITLE
Only one tag allowed in tag box on CSV upload

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#506]
Only one tag can be specified in CSV upload form box "Optional: Tag to add entries to / alter entries for:"  at:

https://www.whatdotheyknow.com/admin/bodies/import_csv

It would be nice if this supported multiple, space separated, tags. 

With #60 having improved the CSV upload itsself to accept multiple tags this isn't very important at all. 

Simply improving the form's help text to explain that one tag can be put in the form field, but anything more involved should be done in the CSV would help, the issue is surprise / unexpected behaviour as much as a lack of functionality.

**Comment by HelenWDTK** [comment]
This has been fixed. Adding multiple tags is possible.
