### ISSUE TITLE
Encourage public bodies to link to Alaveteli sites from their own webpages

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#5066]
Do more to encourage public bodies to suggest those considering making requests to them do so via a relevant Alaveteli site. 

We could set out the benefits, including effectively the provision of an automated disclosure log. 

We could give code, and text, for example links, including perhaps code for a request-form which could be included on a public body's website.

**Comment by garethrees** [comment]
I think the likely route to this happening is:

* A very short note on the sidebar of the authorities page
* A help page section at `/help/officers` saying what we want it to say

![Screenshot 2022-06-13 at 11 48 59](https://user-images.githubusercontent.com/282788/173338143-21ca4f3f-6a0c-4502-bb39-b645be791794.png)

**Comment by garethrees** [comment]
I think this is more of a marketing issue than an app feature
