### ISSUE TITLE
Disable instead of hide destroy authority button

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#5070]
> > I've been trying to delete this duplicate authority, but there is no option to delete (I have deleted other duplicates with no issue - is this a bug?)
>
> …
>
> You can only destroy an authority if there are no requests associated with the authority.
> I think in this case you need to move the request to the other instance of the authority, then come back and destroy the authority when it has no requests.

https://github.com/mysociety/alaveteli/blob/42e0d5040f68d30fbed51ff0d5100df8309cc96b/app/views/admin_public_body/edit.html.erb#L22-L26

We should disable the button with a message of why you can't destroy, rather than just hiding it.

**Comment by lizconlan** [comment]
On closer inspection, it was an embargoed request causing the issue in this case which means non-Pro admins have no indication that it's not a delete-able authority

**Comment by lizconlan** [comment]
* disable rather than hide the button
* tooltip text "This authority has _n_ requests (may be embargoed)" (or similar)
