### ISSUE TITLE
Users with suspended accounts should not be prompted to classify their requests

### ISSUE THREAD

**Issue by mdeuk** [mysociety/alaveteli#5090]
When a user is suspended the "Please update the status of your request" classification prompt emails are not suppressed. This has the ability to annoy users and can lead to some unpleasant support correspondence depending on the circumstances that have led to the user's account being suspended.

Relates to #3041 and #3148

**Comment by mdeuk** [comment]
We've received a complaint from a suspended WDTK user today:

> Please can you stop emailing me to update my previous requests when you've had the audacity to 'suspend my account' <redacted>

We can implement a workaround by making the user's email address 'invalid', however this could have some side effects.

**Comment by garethrees** [comment]
We currently have logic to determine whether a user should be emailed [1], but that's not being used where we actually send these emails [2].

[1] https://github.com/mysociety/alaveteli/blob/0.39.1.4/app/models/user.rb#L616-L618
[2] https://github.com/mysociety/alaveteli/blob/0.39.1.4/app/mailers/request_mailer.rb#L346-L394

**Comment by WilliamWDTK** [comment]
We've had another complaint about this just now:

> How can I reply to the status if my account is suspended?
Weird logic....**[REDACTED]** should reply to my request first.
Thank you.

**Comment by mdeuk** [comment]
And another one today:

> How do I do that when you closed the account??

**Comment by garethrees** [comment]
This is desirable, but unlikely to be worked on in the next 12 months so closing for now.
