### ISSUE TITLE
"Edit your request" button briefly causes "Sending" state for adjacent button

### ISSUE THREAD

**Issue by mvl22** [mysociety/alaveteli#5096]
During the request composition phase, upon clicking "Edit your request", the adjacent button erroneously changes from "Send and publish request" to "Sending".

This is quite disconcerting - a different button's state is changed, and the request is not actually sent (as expected).

![screen shot 2019-02-07 at 00 27 07](https://user-images.githubusercontent.com/361423/52382974-5eb27180-2a6f-11e9-857d-44e9a8540287.png)

![screen shot 2019-02-07 at 00 30 16](https://user-images.githubusercontent.com/361423/52383028-8c97b600-2a6f-11e9-89e2-840200049079.png)

**Comment by garethrees** [comment]
Thanks for reporting.

This is actually a duplicate of https://github.com/mysociety/alaveteli/issues/3585.

We should get this fixed, as yes, it is a bit confusing that this happens!

**Comment by mvl22** [comment]
> This is actually a duplicate of #3585.

Apologies - I did do a search of existing issues but that didn't come up.

**Comment by garethrees** [comment]
No worries at all! 🙏
