### ISSUE TITLE
Signing-in in new tab while request drafted causes error 500 on submission

### ISSUE THREAD

**Issue by mvl22** [mysociety/alaveteli#5097]
If you compose a new FoI request, then realise that you are not signed in, and open the sign in link in a new tab/window, using the submission button at the bottom of the page causes an error 500, causing the composed submission text to be lost.

**Comment by lizconlan** [comment]
^ Reproduction steps for #4484

**Comment by garethrees** [comment]
Closing as a duplicate of #4484 as we've noted this problem in one of the comments https://github.com/mysociety/alaveteli/issues/4484#issuecomment-432129735
