### ISSUE TITLE
Broken sites listed on alaveteli.org/deployments

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#5102]
https://foi.sinarproject.org, Malaysia, not working
https://chiedi.dirittodisapere.it/ Italy, ssl expired
http://queremosaber.org.py/ Paragway, Domain not found 
https://fragastaten.se/ Sweden, 502 Bad Gateway

Via https://groups.google.com/forum/#!topic/alaveteli-users/MSQ_-WR0inw

**Comment by lizconlan** [comment]
Going to leave the Italian site in place for now as they've indicated that they expect this to be a temporary problem.

**Comment by lizconlan** [comment]
Closed via https://github.com/mysociety/alaveteli/pull/5111
