### ISSUE TITLE
Donate button on sidebar not working

### ISSUE THREAD

**Issue by ajparsons** [mysociety/alaveteli#5160]
Donate button on sidebar is not currently working:

![image](https://user-images.githubusercontent.com/8157058/55943673-ecad0300-5c3e-11e9-9c74-e969f6b4618f.png)

Url in link itself is right, but browser is then sent to: https://www.whatdotheyknow.com/request/[object%20Object]

**Comment by garethrees** [comment]
Hmm, works for me…

**Comment by garethrees** [comment]
Okay looks like it may be a problem with an A/B test?

```
Failed to load resource: net::ERR_UNKNOWN_URL_SCHEME
tests-f4c2b3ad53116758be4afcb74c6f1dae76bda0dcd650339788b2db3220dcc788.js:1 Uncaught ReferenceError: cxApi is not defined
    at HTMLDocument.<anonymous> (tests-f4c2b3ad53116758be4afcb74c6f1dae76bda0dcd650339788b2db3220dcc788.js:1)
    at u (application-2a8ac249e64af6c4f51ea69e2434c8015566c38f19aee6b4ee135bbca68c0b3f.js:2)
    at Object.fireWith [as resolveWith] (application-2a8ac249e64af6c4f51ea69e2434c8015566c38f19aee6b4ee135bbca68c0b3f.js:2)
    at Function.ready (application-2a8ac249e64af6c4f51ea69e2434c8015566c38f19aee6b4ee135bbca68c0b3f.js:2)
    at HTMLDocument.s (application-2a8ac249e64af6c4f51ea69e2434c8015566c38f19aee6b4ee135bbca68c0b3f.js:1)
about:blank:1 Failed to load resource: net::ERR_UNKNOWN_URL_SCHEME
```

Clicking in to `tests-f4c2b3ad53116758be4afcb74c6f1dae76bda0dcd650339788b2db3220dcc788.js` looks like its about A/B testing:

```
!function(t){t(function(){if(window.cxVariation=cxApi.chooseVariation(),1===window.cxVariation){var e=t(".sidebar__donate-cta"),n=t(".sidebar__donate-cta__button",e),a=URI(n.attr("href")).removeSearch("utm_content").addSearch("utm_content","experiment_no_"+window.cxVariation).toString();n.attr("href",a),t(".asktheeu-promo").replaceWith(e)}t(".sidebar__donate-cta__button").on("click",function(e){if("undefined"!=typeof ga&&ga.loaded){e.preventDefault();var n=t(this);ga("send",{hitType:"event",eventCategory:"sidebar__donate-cta",eventAction:"click",eventLabel:document.title,hitCallback:function(){window.location.href=n}})}})})}(window.jQuery);
```

**Comment by ajparsons** [comment]
That syncs up with the timing in the stats. I think the problem is with the ```var n = t(this);``` returning an object rather than the url, but I don't know enough to debug. Might be a @zarino question?

**Comment by zarino** [comment]
Yes, it looks to me like `window.location.href = $link;` on [line 25 of tests.js](https://github.com/mysociety/whatdotheyknow-theme/blob/879880037a17e11969e12fe8027925bf45fa0a35/app/assets/javascripts/tests.js#L25) should be `window.location.href = $link.attr('href')`.

I wonder how we didn‘t spot this [in review](https://github.com/mysociety/whatdotheyknow-theme/pull/556)!?

**Comment by lizconlan** [comment]
thanks @zarino!

**Comment by lizconlan** [comment]
Have redeployed the site with the suggested theme change
