### ISSUE TITLE
Donate link needs different source

### ISSUE THREAD

**Issue by ajparsons** [mysociety/alaveteli#5161]
Currently the donate link campaign is:

http://www.mysociety.org/donate/?utm_campaign=foi_request_page&utm_content=experiment_no_0&utm_medium=link&utm_source=whatdotheyknow

This needs to be:

http://www.mysociety.org/donate/?utm_campaign=foi_request_page&utm_content=experiment_no_0&utm_medium=link&utm_source=whatdotheyknow.com

The utm_source needs the .com to trigger the specific WDTK related language on the donate page.

**Comment by lizconlan** [comment]
I think that's happening in multiple places...

**Comment by lizconlan** [comment]
...and looks like this specific case is from `:utm_source => site_name.downcase`

**Comment by lizconlan** [comment]
Oh further investigation.... The second part is true, the first part is not and has been scrapped - I was conflating internal campaign links and outbound (to the donations page) ones.
