### ISSUE TITLE
Do not display profile photo for banned users

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#5171]
Most users we ban are spam, so lets not show the profile photo. That way we don't need need to do the extra step of removing it (time saver), and it helps us build an archive of what a spam account looks like.

For banned users that aren't spam, they'll retain their profile photo and it'll be displayed again when their ban is lifted.

**Comment by RichardTaylor** [comment]
Adding a +1 following a patch of user-profile spam. 

We probably shouldn't even show the user-name for an account banned as spam (sometimes they'll put a company/product name as the user name - and we don't want to be hosting user accounts under, for example, the names of drugs).  A non-logged in user going to their profile page url should get the same not-found error as going to non existent page.

**Comment by MattK1234** [comment]
Adding a big +1 here. I've been going through and banning a lot of spam accounts recently, this would make it a lot easier.
