### ISSUE TITLE
[Rails 5] Set up staging site for testing

### ISSUE THREAD

**Issue by lizconlan** [mysociety/alaveteli#5193]

**Comment by gbp** [comment]
I think with #5211 this should be complete. Anything else missing for this issue?

**Comment by gbp** [comment]
Actual testing being recorded at #5212

**Comment by garethrees** [comment]
> Anything else missing for this issue?

@lizconlan mentioned some hacks to get this working. If we needed more than just #5211 we should document them here. Otherwise I think yeah, we can call this done and start testing as per #5212.

**Comment by lizconlan** [comment]
Although the incoming mail poller is failing with `Net::POPAuthenticationError` (have not changed the `pop_mailer` config)

**Comment by lizconlan** [comment]
> hacks to get this working

My hacks were to force `rails5?` to return `true` and to replace `Gemfile.lock` with its Rails5 counterpart rather than waiting for a deploy script solution. Changes here: https://github.com/mysociety/alaveteli/commit/7d5fba587149650a138331e7f10cfa8a6eab9b74

**Comment by gbp** [comment]
Lets wait for the CI result of #5213 and rebuild the rollup branch tomorrow so all commits are in PRs which we can merge to develop.

**Comment by lizconlan** [comment]
Unless I've misunderstood the purpose of that PR, we don't want to make Rails 5 the default in develop, this is just for our testing purposes. We're not going to default it to Rails 5 in the release.

We've already jumped ahead by adding Ruby 2.6 ahead of time

**Comment by gbp** [comment]
> Unless I've misunderstood the purpose of that PR, we don't want to make Rails 5 the default in develop, this is just for our testing purposes. We're not going to default it to Rails 5 in the release.

Primarily purpose of the PR is to capture what was needed to be done to get our Rails 5 work deployed. We might merge it or not, I don't know, and it has to go through the standard process of being considered, reviewed and then only merged when we're ready to switch over.

> We've already jumped ahead by adding Ruby 2.6 ahead of time

Saying we've jumped ahead with 2.6 is inaccurate, we're not saying we support it at all. We're just building against it and if it fails the builds won't break. The output gives us insight into potential future problems.

**Comment by garethrees** [comment]
We've still got lots of poller errors coming through. Can we get that disabled to avoid adding to the noise?

**Comment by gbp** [comment]
> We've still got lots of poller errors coming through. Can we get that disabled to avoid adding to the noise?

Have set `PRODUCTION_MAILER_RETRIEVER_METHOD: passive` is that all that is needed?

**Comment by gbp** [comment]
Ah of course, I've also now disabled the poll-for-incoming deamon.

**Comment by lizconlan** [comment]
> Primarily purpose of the PR is to capture what was needed to be done to get our Rails 5 work deployed. 

Sorry - got mixed up between Release prep and the Testing work. Also forgot that we've configured things to only run CI builds against `develop` 🙄

**Comment by lizconlan** [comment]
Closing this as we're currently using the staging site for testing
