### ISSUE TITLE
Release 0.34

### ISSUE THREAD

**Issue by lizconlan** [mysociety/alaveteli#5194]
Requires https://github.com/mysociety/alaveteli/issues/4902.

**Comment by lizconlan** [comment]
* Reduce OS support #4782 #4970
* Reduce Ruby versions support #4541 #4542 #4842

**Comment by garethrees** [comment]
* Make Rails 5 the default #3969

**Comment by garethrees** [comment]
Remove Ruby 2.6 / Rails 4.2 monkeypatch: https://github.com/mysociety/alaveteli/pull/5055/commits/0fc7e46d0d744db66074073076724ec003c9eb50

**Comment by lizconlan** [comment]
* For the release / upgrade notes - "Use rails [instead of rake] for running tasks and tests"
https://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#use-rails-for-running-tasks-and-tests

**Comment by gbp** [comment]
>     * Make Rails 5 the default #3969

If this release is also droping Rails 4.2 then we should remove the `rails5?` conditionals - such as: https://github.com/mysociety/alaveteli/pull/5202#L191

**Comment by garethrees** [comment]
Planned Ruby / OS support list https://gist.github.com/garethrees/ec3c403e1ea0744fb736381785e1e788

**Comment by garethrees** [comment]
Should do https://github.com/mysociety/alaveteli/issues/5199#issuecomment-495588852

**Comment by lizconlan** [comment]
Done! https://github.com/mysociety/alaveteli/releases/tag/0.34.0.0
