### ISSUE TITLE
[Rails 5] Active Record models inherit from `ApplicationRecord` by default

### ISSUE THREAD

**Issue by lizconlan** [mysociety/alaveteli#5198]
Part of #3969

From: https://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#active-record-models-now-inherit-from-applicationrecord-by-default

> When upgrading from Rails 4.2 to Rails 5.0, you need to create an application_record.rb file in app/models/ and add the following content:
>
> ```ruby
> class ApplicationRecord < ActiveRecord::Base 
>   self.abstract_class = true
> end
> ```
>
> Then make sure that all your models inherit from it.

**Comment by gbp** [comment]
This has been done as part of #5202 (https://github.com/mysociety/alaveteli/pull/5202/commits/cfd7de9e5391313393ebdf8f7bdd3d10b7a220ef). Happy to extract out into a separate PR is needed.

**Comment by lizconlan** [comment]
> Happy to extract out into a separate PR

No need - was just ticketing things from the upgrade guide so they don't get missed

I've added an extra "Fixes: #xxxx" to your PR instead :)
