### ISSUE TITLE
[Rails 5] Check - Halting Active Record Callback Chains via `throw(:abort)`

### ISSUE THREAD

**Issue by lizconlan** [mysociety/alaveteli#5199]
Part of #3969

https://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#halting-callback-chains-via-throw-abort

New behaviour in Rails 5...

> In Rails 4.2, when a 'before' callback returns false in Active Record and Active Model, then the entire callback chain is halted.
>
> In Rails 5.0, returning false in an Active Record or Active Model callback will not have this side effect of halting the callback chain. Instead, callback chains must be explicitly halted by calling `throw(:abort)`.

I don't think we use this but we should go through all our `ActiveRecord` and `ActiveModel` files and double check. The old behaviour will be retained in Rails 5.0 with a deprecation warning until we opt in to the new behaviour via the `ActiveSupport.halt_callback_chains_on_return_false` config setting (documented in the guide, per the above link)

**Comment by garethrees** [comment]
I agree, I don't think we use this behaviour to halt callback chains.

I've scanned through all `before_` callbacks and can't see anything to suggest we do.

After #5194 we should review the production logs to check that we're not seeing deprecation warnings, and then set `ActiveSupport.halt_callback_chains_on_return_false`.
