### ISSUE TITLE
[Rails 5] ActiveJob Now Inherits from ApplicationJob by Default

### ISSUE THREAD

**Issue by lizconlan** [mysociety/alaveteli#5200]
Part of #3969

https://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#activejob-now-inherits-from-applicationjob-by-default

AFAIK we haven't created any `ActiveJob` classes yet, in which case all we need to do is this:

> When upgrading from Rails 4.2 to Rails 5.0, you need to create an `application_job.rb` file in `app/jobs/` and add the following content:
>
> ```ruby
> class ApplicationJob < ActiveJob::Base
> end
> ```

**Comment by garethrees** [comment]
Closing as we don't need to do this
