### ISSUE TITLE
[Rails 5] Staging testing 

### ISSUE THREAD

**Issue by gbp** [mysociety/alaveteli#5212]
Initial list taken from: https://github.com/mysociety/alaveteli/issues/2968#issuecomment-264157308

List spilt into separate comments due to collisions when multiple people were editing at the same time.

**Comment by gbp** [comment]
Noting for `Change a profile photo` photo doesn't change without clearing the varnish cache

**Comment by garethrees** [comment]
> Noting for `Change a profile photo` photo doesn't change without clearing the varnish cache

https://github.com/mysociety/alaveteli/issues/156.

**Comment by lizconlan** [comment]
Could be done locally but we should also test Pro without Pricing

**Comment by gbp** [comment]
### PRO BATCH CREATION (Pro user)
- [ ] pro_batch_access feature enables batch access
- [ ] Can search for authority
- [ ] Add authority to batch draft
- [ ] pro_batch_category_ui feature enables batch browse access
- [ ] Can browse authority categories
- [ ] Can add all authority in a category to batch draft

**Comment by gbp** [comment]
### PRO BATCH SENDING
...

**Comment by gbp** [comment]
### PRO EMBARGOS (Pro user)
- [ ] Can add embargo to pro requests
- [ ] Extend embargo
- [ ] Publish pro requests
- [ ] Requests should not be visible to public users

**Comment by gbp** [comment]
### PRO DASHBOARD
...

**Comment by gbp** [comment]
### PRO SIGNUPS/PAYMENTS (User)
- [ ] Can signup using a coupon
- [x] Enter payment details
- [x] Subscription created on Stripe

**Comment by gbp** [comment]
### PRO WEBHOOKS
- [ ] Response 200 to all webhook
- [ ] Customer updated - ignore renewals
- [x] Customer updated - email on cancelled
- [x] Customer deleted - remove pro access
- [x] Payment succeeded - update charge description
- [ ] Payment failed - email

**Comment by gbp** [comment]
### ANNOUNCEMENTS (Admin)
- [x] Create site-wide announcement
- [x] Create pro announcement
- [x] Can dismiss announcements

**Comment by gbp** [comment]
### CENSOR RULES (Admin)
- [ ] View the list of censor rules (/admin/censor_rules)
- [ ] Create a global censor rule
- [ ] Create a user censor rule
- [ ] Create an authority censor rule
- [ ] Create a request censor rule
- [ ] Create a regexp censor rule
- [ ] Edit a censor rule
- [ ] Destroy a censor rule

**Comment by gbp** [comment]
### COMMENTS (Admin)
- [x] View the list of comments (/admin/comments)
- [ ] ~~Create a comment~~
- [x] Edit a comment
- [x] Hide a comment
- [x] Clear reported comment

**Comment by gbp** [comment]
### COMMENTS (User)
- [x] Add a comment to your own request
- [x] Add a comment on someone else's request
- [x] Report a comment

**Comment by gbp** [comment]
### ATTACHMENTS (User)
- [ ] Reply to a request with a PDF
- [ ] Reply to a request with a JPG
- [ ] Reply to a request with a DOC
- [ ] Reply to a request with a DOCX
- [ ] Reply to a request with a XLS
- [ ] Reply to a request with a XLSX
- [ ] Reply to a request with a PNG
- [ ] Reply to a request with a TXT
- [ ] Reply to a request with a RTF
- [ ] Reply to a request with a ZIP
- [ ] View an attachment as HTML
- [ ] View an attachment as HTML through the Google Docs viewer
- [ ] Download an attachment

**Comment by gbp** [comment]
### HOLIDAYS (Admin)
- [x] Manually add a holiday
- [x] Add holidays from a suggested iCal feed
- [x] Add holiday from an online .ics feed (e.g. [movie releases](https://www.google.com/calendar/ical/pfutdblf1gi8jmfsvroh76f6jg%40group.calendar.google.com/public/basic.ics))
- [x] Edit a holiday
- [x] Delete a holiday

**Comment by gbp** [comment]
### INCOMING MESSAGES (Admin)
- [x] Redeliver a message to a different request
- [x] Generate an FOI officer upload URL
- [x] View the raw email
- [x] Download the raw email
- [x] Change prominence to requester only
- [x] Change prominence to hidden
- [x] Destroy a message

**Comment by gbp** [comment]
### INFO REQUEST BATCHES (Pro user)
- [ ] Create a batch request
- [ ] View a batch request (/info_request_batches/:id)

**Comment by gbp** [comment]
### INFO REQUESTS (User)
- [x] Make a request
- [x] Make 2 requests with the same title

**Comment by gbp** [comment]
### INFO REQUESTS (Admin)
- [ ] Change the title of a request
- [ ] Change prominence to backpage
- [ ] Change prominence to requester only
- [ ] Change prominence to hidden
- [ ] Allow new responses from anybody
- [ ] Allow new responses from authority only
- [ ] Allow new responses from nobody
- [ ] Handle rejected responses with bounce
- [ ] Handle rejected responses with holding pen
- [ ] Handle rejected responses with blackhole
- [ ] Change the described state of a request
- [ ] Change the awaiting description
- [ ] Prevent comments being made
- [ ] Tag a request
- [x] Move a request to a different user
- [x] Typo user url when moving request to new user
- [x] Move a request to a different public body
- [x] Mistype the url when moving request to a public body
- [x] Reopen a request thread marked as "closed to new correspondence"
- [ ] Generate an FOI officer upload URL
- [ ] Hide a request and notify the user
- [ ] Filter requests by date
- [ ] Filter requests by keyword
- [ ] Filter requests by state

**Comment by gbp** [comment]
### MAIL SERVER LOGS
- [ ] Check delivery status of a successfully delivered outgoing message
- [ ] Check delivery status of a failed outgoing message
- [ ] Check logs are only shown to requester and admins
- [ ] Check email addresses are redacted for everyone but admins

**Comment by gbp** [comment]
### OUTGOING MESSAGES (User)
- [ ] Send a followup
- [ ] Ask for an internal review

**Comment by gbp** [comment]
### OUTGOING MESSAGES (Admin)
- [ ] Resend an outgoing message
- [ ] Change prominence to requester only
- [ ] Change prominence to hidden
- [ ] Edit body of message
- [ ] Destroy an outgoing message

**Comment by gbp** [comment]
### PROFILE PHOTOS (User)
- [x] Add a profile photo
- [x] Add a photo that's not an image
- [x] Resize a profile photo
- [x] Change a profile photo _doesn't seem to work without clearing it_
- [x] Remove a profile photo

**Comment by gbp** [comment]
### PUBLIC BODIES (Admin)
- [ ] Add an authority
- [ ] Add an authority with multiple locales
- [ ] Edit an authority: Check version history
- [ ] Edit an authority with multiple locales
- [ ] Check the homepage is inferred from the email domain
- [ ] Check that a disclosure log is presented
- [ ] Tag an authority
- [ ] Tag an authority with not_apply
- [ ] Tag an authority with eir_only
- [ ] Tag an authority with defunct
- [ ] Tag an authority with a charity number
- [ ] Destroy a public body
- [ ] Confirm you don't get the option to destroy a public body with requests
- [ ] Import from CSV
- [ ] Download authorities as CSV
- [ ] Check pagination works

**Comment by gbp** [comment]
### PUBLIC BODY CATEGORIES (Admin)
- [ ] Add a category
- [ ] Add a category with multiple locales
- [ ] Add a category to a heading
- [ ] Check the category matches authorities with the category tag
- [ ] Destroy a category

**Comment by gbp** [comment]
### PUBLIC BODY CHANGE REQUESTS (User)
- [ ] Make a change request (via sign in route)

**Comment by gbp** [comment]
### PUBLIC BODY CHANGE REQUESTS (Admin)
- [ ] Close a change request
- [ ] Close and respond to a change request
- [ ] Make the proposed update

**Comment by gbp** [comment]
### PUBLIC BODY HEADINGS (Admin)
- [ ] Add a heading
- [ ] Add a heading with multiple locales
- [ ] Reorder headings
- [ ] Edit a heading
- [ ] Destroy a heading

**Comment by gbp** [comment]
### REQUEST CLASSIFICATIONS (User)
- [ ] View unclassified requests in the classification game
- [ ] Classify some unclassified requests

**Comment by gbp** [comment]
### SPAM ADDRESSES (Admin)
- [ ] Create a spam address
- [ ] Check that mail to a spam address is discarded
- [ ] Destroy a spam address

**Comment by gbp** [comment]
### TRACK THINGS (User)
- [ ] Create a request track (Follow a request)
- [ ] Create a public body track (Follow an authority)
- [ ] Create a user track (Follow a user)
- [ ] Create a search track
- [ ] Delete a track
- [ ] Delete all tracks from a group (e.g. "Individual requests")
- [ ] Check "My wall" contains correct entries
- [ ] Click unsubscribe link the alert email 
- [ ] Check emails are sent & received by correct users

**Comment by gbp** [comment]
### USERS
- [x] Create a new user
- [x] Confirm a user
- [x] Log in as a user
- [x] Make user an admin
- [x] Remove admin permissions
- [ ] Make user a pro
- [ ] Remove pro access
- [ ] Make user a pro admin
- [ ] Remove pro admin permissions
- [x] Log out
- [x] Check that 'remember me' persists the login when closing the browser tab
- [x] Ban (suspend) a user
- [x] Ban (suspend) a user via the "Ban for spamming" button
- [ ] Close a user's account
- [x] Use the "Log in as [user]" button
- [ ] Edit profile
   - [x] Set about me text
   ~- [ ] Set profile photo~
   - [ ] Try to add spam text to profile (_note: adding a link to YouTube worked - is that ok?_))
   - [x] Added known spam phrase to profile, triggered "Spam about me text from user" email alert
- [x] Set as confirmed not spam
  - [x] They should not be presented with spam measures
- [ ] Set default locale
- [ ] Check that default limit is enforced
- [ ] Set no limit and check that default limit can be exceeded
- [ ] Turn off email alerts
- [ ] Re-enable email alerts
- [ ] Allow batch requests
- [ ] Enable 2FA auth
- [ ] Regenerate OTP keys
- [ ] Check requests are shown on "my requests" (_note: requires running `update-xapian-index`_)
- [ ] Filter requests on "my requests"
- [ ] Check pagination on "my requests"
- [x] Send a message to another user

**Comment by gbp** [comment]
### WIDGET VOTES

- [ ] Enable widgets
- [ ] "Like" a widget (logged in)
- [ ] "Follow" a liked widget (via log in)
- [ ] "Unsubscribe" from widget (logged in)

**Comment by gbp** [comment]
### CRON TASKS

- [ ] `/etc/init.d/_SITE_/alert-tracks check`
- [ ] `/etc/init.d/_SITE_/poll-for-incoming check`
- [ ] `/etc/init.d/_SITE_/send-notifications check`
- [ ] `script/alert-comment-on-request`
- [ ] `script/alert-embargoes-expired`
- [ ] `script/alert-embargoes-expiring`
- [ ] `script/alert-new-response-reminders`
- [ ] `script/alert-not-clarified-request`
- [ ] `script/alert-overdue-requests`
- [ ] `script/alert-tracks`
- [ ] `script/alert-tracks-daemon`
- [ ] `script/annotate-models`
- [ ] `script/cache-incoming-emails`
- [ ] `script/check-recent-requests-sent`
- [ ] `script/cleanup-holding-pen`
- [ ] `script/clear-caches`
- [ ] `script/compact-xapian-database`
- [ ] `script/current-theme`
- [ ] `script/defer`
- [ ] `script/delete-expired-embargoes`
- [ ] `script/delete-old-things`
- [ ] `script/destroy-and-rebuild-xapian-index`
- [ ] `script/diff-theme-override`
- [ ] `script/handle-mail-replies`
- [ ] `script/handle-mail-replies.rb`
- [ ] `script/install-as-user`
- [ ] `script/load-mail-server-logs`
- [ ] `script/load-sample-data`
- [ ] `script/mailin`
- [ ] `script/mysociety-switch-to-shared`
- [ ] `script/parse-unparsed-pro`
- [ ] `script/rails-deploy-before-down`
- [ ] `script/rails-deploy-while-down`
- [ ] `script/rails-post-deploy`
- [ ] `script/replicate-xapian-database`
- [ ] `script/request-creation-graph`
- [ ] `script/runner`
- [ ] `script/send-batch-requests`
- [ ] `script/send-notifications`
- [ ] `script/send-notifications-daemon`
- [ ] `script/send-public-holiday-reminder`
- [ ] `script/site-specific-install.sh`
- [ ] `script/stop-new-responses-on-old-requests`
- [ ] `script/switch-theme.rb`
- [ ] `script/test-vagrant-provisioning`
- [ ] `script/update-expiring-embargo-info-request-events`
- [ ] `script/update-overdue-info-request-events`
- [ ] `script/update-public-body-stats`
- [ ] `script/update-xapian-index`
- [ ] `script/user-use-graph`

**Comment by gbp** [comment]
Not sure on what to do here yet:

```
INFO REQUEST EVENTS
POST REDIRECTS
DAEMONS
```

**Comment by lizconlan** [comment]
We've done  sign in and sign up as part of making a request so we've done some testing of `PostRedirect`

**Comment by lizconlan** [comment]
🎉 🏆 🚀
