### ISSUE TITLE
[Rails 5.1] ActsAsVersioned table_exists? deprecation warning

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#5230]
Required for https://github.com/mysociety/alaveteli/issues/3969.

> There is still one deprecation warning for `#table_exists?` coming from the `acts_as_versioned` gem - we might need patch this or look at alternative versioning gems.
>
> – https://github.com/mysociety/alaveteli/pull/5208#issue-282003915

The [deprecation warning](https://github.com/mysociety/alaveteli/issues/5207) is a little odd, in that it's noting a change of behaviour rather than complete method removal.

`#table_exists?` still [exists in Rails 5.2.x](https://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-table_exists-3F).

If we need to handle this, I don't see a huge problem with forking acts_as_versioned, given we've got it pinned on the most recent commit of master, which hasn't been updated since 2012.

There's only [one occurrence of `table_exists?`](https://github.com/technoweenie/acts_as_versioned/blob/63b1fc8529d028fae632fe80ec0cb25df56cd76b/lib/acts_as_versioned.rb#L422), so should be an easy patch to make and maintain.

**Comment by gbp** [comment]
Warning happens when migrating [VersionPublicBody](https://github.com/mysociety/alaveteli/blob/7839391933bc6d3235d1c969fc6c7e0abbfbdc63/db/migrate/006_version_public_body.rb):

Rails 5.0
```
Migrating to VersionPublicBody (6)
   (40.6ms)  BEGIN
   (0.5ms)  ALTER TABLE "public_bodies" ADD "version" integer
DEPRECATION WARNING: #table_exists? currently checks both tables and views. This beha
vior is deprecated and will be changed with Rails 5.1 to only check tables. Use #data
_source_exists? instead. (called from create_versioned_table at /Users/graeme/.rbenv/
versions/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/acts_as_versioned-63b1fc8529d0/lib/ac
ts_as_versioned.rb:422)
   (2.7ms)  CREATE TABLE "public_body_versions" ("id" serial primary key, "public_bod
y_id" integer, "version" integer)
   (1.4ms)  ALTER TABLE "public_body_versions" ADD "name" text
   (0.2ms)  ALTER TABLE "public_body_versions" ADD "short_name" text
   (0.2ms)  ALTER TABLE "public_body_versions" ADD "request_email" text
   (0.2ms)  ALTER TABLE "public_body_versions" ADD "complaint_email" text
   (0.8ms)  CREATE  INDEX  "index_public_body_versions_on_public_body_id" ON "public_
body_versions"  ("public_body_id")
   (0.3ms)  ALTER TABLE "public_body_versions" ADD "created_at" timestamp NOT NULL
   (0.2ms)  ALTER TABLE "public_body_versions" ADD "updated_at" timestamp NOT NULL
  SQL (0.2ms)  INSERT INTO "schema_migrations" ("version") VALUES ($1) RETURNING "ver
sion"  [["version", "6"]]
   (0.4ms)  COMMIT
```

Rails 5.1
```
Migrating to VersionPublicBody (6)
   (40.1ms)  BEGIN
   (0.3ms)  ALTER TABLE "public_bodies" ADD "version" integer
   (3.2ms)  CREATE TABLE "public_body_versions" ("id" bigserial primary key, "public_body_id" integer, "version" integer)
   (1.6ms)  ALTER TABLE "public_body_versions" ADD "name" text DEFAULT NULL
   (0.3ms)  ALTER TABLE "public_body_versions" ADD "short_name" text DEFAULT NULL
   (0.3ms)  ALTER TABLE "public_body_versions" ADD "request_email" text DEFAULT NULL
   (0.3ms)  ALTER TABLE "public_body_versions" ADD "complaint_email" text DEFAULT NULL
   (1.0ms)  CREATE  INDEX  "index_public_body_versions_on_public_body_id" ON "public_body_versions"  ("public_body_id")
   (0.6ms)  ALTER TABLE "public_body_versions" ADD "created_at" timestamp NOT NULL
   (0.6ms)  ALTER TABLE "public_body_versions" ADD "updated_at" timestamp NOT NULL
  SQL (0.5ms)  INSERT INTO "schema_migrations" ("version") VALUES ($1) RETURNING "version"  [["version", "6"]]
   (1.0ms)  COMMIT
```

**Comment by gbp** [comment]
So clearly this still works for 5.1 it appears the depreciation warning was regarding now not matching of SQL views which we don't need to worry about.

The method still exists:
https://github.com/rails/rails/blob/5-1-stable/activerecord/lib/active_record/connection_adapters/abstract/schema_statements.rb#L58-L62

Closing 🎉
