### ISSUE TITLE
Add the pro metrics script as a rake task

### ISSUE THREAD

**Issue by lizconlan** [mysociety/alaveteli#5247]
And tidy it up a bit along the way...

Step 1:
* Make a `lib/alaveteli_pro/pro_metrics.rb` (or similar) for it
* Make sure all the different counts have their own method (where that makes sense)
* ~Have a lookup of the user emails where we get account data~
* Small disclaimer that "new signups" may be missing if they're returning subscribers
* Basic email report for testing

Step 2:
* Nicer email

Future / nice to have:
_if these look easy (as in 15 minutes easy), do them here, if not ticket and move on_
* Include completed cancellations
* Get 'new signups' as per the web link and diff to find new vs returning
* Run for specific dates so we can - for example - tell it to run for Monday on a Tuesday (probably out of scope)

**Comment by lizconlan** [comment]
Hmm... in our current script, we hardcode the Stripe plan names!

**Comment by lizconlan** [comment]
Ok. My assumptions for Stripe plans are...

1. We use the plan **ID** rather than the name
1. We prefix the plan ID with the stripe namespace and a hyphen e.g.
   ```
   "#{AlaveteliConfiguration.stripe_namespace}-pro"
   => 'WDTK-pro"
   ```
1. Without a prefix the ID will just be e.g. `pro`
1. There should always be a `pro` plan
1. There might be a `pro-annual-billing` plan
1. The plan **name** doesn't matter

**Comment by garethrees** [comment]
> Run for specific dates so we can - for example - tell it to run for Monday on a Tuesday (probably out of scope)

Yeah, I think this will add lots of complexity around querying the stripe API, so lets just make it run weekly and you can just review old emails if you want to look back in time.

**Comment by lizconlan** [comment]
> > Run for specific dates so we can - for example - tell it to run for Monday on a Tuesday (probably out of scope)
>
> Yeah, I think this will add lots of complexity around querying the stripe API, so lets just make it run weekly and you can just review old emails if you want to look back in time.

👍 

As the intention is to schedule it to run unattended the no-one-was-in-to-run-the-script problem should go away anyway

**Comment by lizconlan** [comment]
Things to document:
- How to set up the Stripe webhooks
  - the endpoint
  - which webhooks to subscribe to
- The 'Automatic collection' payment settings (under Settings > Stripe apps > Billing > 'Automatic collection'), includes the custom behaviours set in 'Manage failed payments' such as 'if all retries fail - 'cancel subscription'/'mark as unpaid'/'leave as-is')
- Question: Do we have to set the API version or do we set that in the code?
