### ISSUE TITLE
Stop listing bodies in alphabetical order

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#5256]
A council whose name starts with "A" has written to WhatDoTheyKnow to say they feel they're often used for test requests and badly formed requests - they suspect this due to their alphabetical position on lists of bodies on WhatDoTheyKnow resulting in them getting requests which are to be made to lots of councils in the first wave.  

They have suggested a reordering! 

The council making the report are not in the top ten councils alphabetically. If this is an issue it's presumably worse for those right at the top alphabetically, it might be worth looking into if it is. 

The benefits to users of a list in alphabetical order probably outweigh this issue. 

The council have suggested listing councils by region. 

Related: #4047 Option to order body lists by descending number of requests

**Comment by garethrees** [comment]
At the end of the day, someone has to get listed first. Whoever that is will probably complain about it.

While I think we can make improvements – perhaps by adding region categories or different sort options – at the end of the day alphabetical ordering is a fairly intuitive way of finding a Thing in a list, so I'm going to close this on the basis that we'll continue to sort alphabetically by default.
