### ISSUE TITLE
Show when a previously embargoed request was published

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#5282]
A previously embargoed correspondence thread should show clearly the date on which it was published. 

This could be shown as an "event" in the timeline of the correspondence thread and/or towards the top of the page. 

If there is a history of hiding / publishing that could be shown too. 

This idea could be extended to requests hidden/republished by administrators but it's the case of embargoed requests being published which has prompted me to raise the ticket. 

WhatDoTheyKnow gives a potentially a misleading impression when the date shown at the top of a correspondence thread is a long time ago but it has only just been published. 

#4932 - page showing previously embargoed requests is related.

**Comment by garethrees** [comment]
We do keep events for `expire_embargo`, so I don't think it would be too much to show the last of these.

At the moment we only show correspondence events, but we could move to showing all events interspersed within the correspondence "bubbles" like GitHub does with e.g. adding labels https://github.com/mysociety/alaveteli/issues/4565.

I think the code around this area would take a bit of work to clean up first.

**Comment by garethrees** [comment]
Just noting that these are already shown on the event history page.

**Comment by garethrees** [comment]
> Just noting that these are already shown on the event history page.

Closing because of this – https://github.com/mysociety/alaveteli/issues/4565 would be the next iteration.
