### ISSUE TITLE
Incorrect explanation string in Pro Metrics mail

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#5286]
<img width="266" alt="Screenshot 2019-07-11 at 11 56 25" src="https://user-images.githubusercontent.com/282788/61045543-f75c6d00-a3d2-11e9-86d6-41e543a091b3.png">

https://github.com/mysociety/alaveteli/blob/develop/app/views/alaveteli_pro/metrics_mailer/weekly_report.text.erb#L54

This should be `Estimated total number of Pro requests`

Part of https://github.com/mysociety/transparency-adessium/issues/17

**Comment by garethrees** [comment]
While we're at it, I'm not sure `total_new_requests` is a good hash key there?

**Comment by lizconlan** [comment]
Good spot - easier to catch with live data!

**Comment by lizconlan** [comment]
> not sure `total_new_requets` is a good hash key

`estimated_total_requests` feels better given the context

**Comment by lizconlan** [comment]
… or `estimated_pro_requests` 🤔

**Comment by garethrees** [comment]
`estimated_total_pro_requests` sounds good
