### ISSUE TITLE
Applying sysvinit passenger change fails

### ISSUE THREAD

**Issue by schlos** [mysociety/alaveteli#5293]
When upgrading from 0.23.0.0, and following steps for 0.24.0.0:

> There's been a minor change to config/sysvinit-passenger.example. You should
> regenerate this file: http://alaveteli.org/docs/installing/manual_install/#passenger

By following guide:
https://alaveteli.org/docs/installing/manual_install/#passenger

With customized steps for IPZ:
```
pushd /var/www/imamopravoznati.org/alaveteli
bundle exec rake config_files:convert_init_script \
  DEPLOY_USER=alaveteli \
  VHOST_DIR=/var/www/imamopravoznati.org \
  VCSPATH=alaveteli \
  SITE=alaveteli \
  SCRIPT_FILE=/var/www/imamopravoznati.org/alaveteli/config/sysvinit-passenger.example > /etc/init.d/alaveteli
popd

chown root:alaveteli /etc/init.d/alaveteli
chmod 754 /etc/init.d/alaveteli
```

Although not sure what for "site" stands for as all in example looks as "alaveteli". Should my "site" be "imamopravoznati" or "imamopravoznati.org"? For what is "site" used for and how it will affect some specific alaveteli instance?

By running those commands I got an error:
`bash: /etc/init.d/alaveteli: Permission denied`
and
`-bash: /etc/init.d/alaveteli: Permission denied`

How should this commend be run? 
I tried running with administrator user, and alaveteli user, and with sudo. All tries failed with same error.

**Comment by garethrees** [comment]
Given IPZ is now on 0.33, I think you got this resolved! Sorry we didn't pick this up! 🙈
