### ISSUE TITLE
Users can request email change for defunct bodies

### ISSUE THREAD

**Issue by schlos** [mysociety/alaveteli#5300]
**Current**
Users can request email change for defunct bodies.

Example:
https://www.whatdotheyknow.com/body/1994_group

More about this authority
* Home page of authority
* View FOI email address
* Ask us to update FOI email <---

**Expected**
In my opinion, if body is defunct/inactive, we should not allow users to ask for email change.

**Comment by garethrees** [comment]
Would be quite easy to add a method like…

```ruby
class PublicBody
  def user_updatable?
    !defunct?
  end
end
```

…and use that as a check in the UI.

**Comment by WilliamWDTK** [comment]
Just to note, we at WDTK have recently received a change request for a defunct body.

**Comment by garethrees** [comment]
This is desirable, but unlikely to be worked on in the next 12 months so closing for now.
