### ISSUE TITLE
Admin user search should enable searching of profile (about me) text

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#5303]
This feature request is being made as it might assist with the identification of spam accounts. 

I don't know how useful it would be, but I saw a pattern in spam links in profiles and wasn't able to easily search for other profiles with eg. links to the same domain.

**Comment by gbp** [comment]
Yes this seems like it would be helpful.

I have used the Rails console and searched the about me text for "http" and all accounts created in the last two days have been spam and banned.
