### ISSUE TITLE
💥 Consider emoji support 

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#5309]
Someone has used an emoji (💥 )in a request on WhatDoTheyKnow. 

Should this be permitted?  :-)

**Comment by mdeuk** [comment]
> Someone has used an emoji (💥 )in a request on WhatDoTheyKnow.
> 
> Should this be permitted? :-)

In all honesty, I don't have any particular problem with Emoji - its developing into a language of its own right, and, is even recognised by the [Oxford Dictionary](https://www.pbs.org/newshour/rundown/oxford-dictionary-says-the-2015-word-of-the-year-is-an-emoji/).

I'd wager it is very likely that FOI officers will be able to see the Emoji in some useful form - most versions of applications such as Microsoft Office include some support, as does Windows and macOS itself.

There are, of course, some case by case considerations - what about a request where a user submits a request with Emoji that forms a rude gesture? 🙂

I do,  however,  have a slight concern from an administrative perspective; should we, for example, allow Emoji in users names, and, in email addresses?

At the moment it's probable that any email address would be invalid; however, there could be an element of future-proofing in that respect. Indeed, allowing unicode could assist with internationalisation.

**Comment by garethrees** [comment]
Closing as I don't think we've really seen any problematic use.

Can create new issues if there's a specific use that we want to discourage/prevent.

**Comment by garethrees** [comment]
Hmm, slightly more problematic https://www.whatdotheyknow.com/request/parties_22

![Screenshot 2021-12-13 at 09 48 51](https://user-images.githubusercontent.com/282788/145789513-897e077c-7918-411a-acee-255f13bd840e.png)
