### ISSUE TITLE
Use the 'bionic' distribution on Travis

### ISSUE THREAD

**Issue by lizconlan** [mysociety/alaveteli#5322]
We're dropping support for Xenial in the next release so we should configure our CI suite to use Bionic as well.

As there are breaking changes in the Bionic build environment, this has been split out from the ticket to drop Xenial support in the codebase. 

## Solvable problems

The new environment has switched to [not starting database servers by default](https://docs.travis-ci.com/user/reference/bionic/#databases-and-services) and (although this differs from the documentation) seems to means that [Postgres doesn't start](https://travis-ci.org/mysociety/alaveteli/jobs/566455970) unless a named version is listed in the `addons:` section.

And then there's the slightly weird bit where we need to install `pdftk-java` from the Cosmic packages but that's a Bionic thing rather than a Travis thing. ~~(We could do it more neatly if ATP Addons were working, but we can get it working for now and make the setup script nicer later. [No, this [causes version problems](https://travis-ci.org/mysociety/alaveteli/jobs/566561194)])~~

## Currently unsolvable problem

It has also stopped [installing ruby 2.3.3 by default](https://docs.travis-ci.com/user/reference/bionic/#ruby-support) which doesn't feel like something that's easy to solved (without removing it from the testing matrix) as there are currently 2 blockers:
* there's no publicly packaged version of ruby 2.3.3 for Bionic (only 2.3-stable which resolves to 2.3.8) - if one existed, we could install it via APT Addons which looks as though it runs before rvm so it _should_ work
  ```
   addons:
     apt:
       sources:
         - sourceline: 'ppa:/example/source'
       packages:
         - ruby-2.3.3
   ```
* Travis's APT Addons currently doesn't work on Bionic (although there is an [open PR](https://github.com/travis-ci/travis-build/pull/1754) so hopefully it will be available for use soon)

---

References:

https://docs.travis-ci.com/user/reference/bionic/
https://docs.travis-ci.com/user/installing-dependencies/
[Brightbox Bionic packages](https://launchpad.net/~brightbox/+archive/ubuntu/ruby-ng/+packages?field.name_filter=&field.status_filter=published&field.series_filter=bionic)
[Brightbox Experimental Bionic packages](https://launchpad.net/~brightbox/+archive/ubuntu/ruby-ng-experimental?field.series_filter=bionic)
[Canonical's Ruby packages on Snap](https://snapcraft.io/ruby)

**Comment by garethrees** [comment]
If we're dropping Xenial support will this be required for #5229?

**Comment by lizconlan** [comment]
> If we're dropping Xenial support will this be required for #5229?

I think we can separate the two but, we have options:

1. Don't drop Xenial in this release after all
1. Drop Xenial but don't update the CI config
1. Drop Xenial, adopt the Travis Bionic environment but drop Ruby 2.3.3 from the testing matrix

**Comment by garethrees** [comment]
> Drop Xenial but don't update the CI config

Not supporting Xenial but running our CI on it doesn't sound like a great situation

> Drop Xenial, adopt the Travis Bionic environment but drop Ruby 2.3.3 from the testing matrix

Stretch has 2.3.3 by default, and we support Stretch, so ideally want to build against that. Based on the description above, I'm not sure why we can't [install 2.3.3 through rvm](https://docs.travis-ci.com/user/languages/ruby#specifying-ruby-versions-and-implementations)?

**Comment by lizconlan** [comment]
> Stretch has 2.3.3 by default, and we support Stretch, so ideally want to build against that. Based on the description above, I'm not sure why we can't install [2.3.3 through rvm](https://docs.travis-ci.com/user/languages/ruby#specifying-ruby-versions-and-implementations)?

Per problem description, Travis [no longer supplies 2.3.3](https://docs.travis-ci.com/user/reference/bionic/#ruby-support) for their Bionic environment so when we select an unsupported Ruby version via `rvm: 2.3.3`, the [build fails with an error](https://travis-ci.org/mysociety/alaveteli/jobs/565405245):

```
$ rvm use 2.3.3 --install --binary --fuzzy
curl: (22) The requested URL returned error: 404 Not Found
Required ruby-2.3.3 is not installed - installing.
curl: (22) The requested URL returned error: 404 Not Found
Searching for binary rubies, this might take some time.
Requested binary installation but no rubies are available to download, consider skipping --binary flag.
Gemset '' does not exist, 'rvm ruby-2.3.3 do rvm gemset create ' first, or append '--create'.
```

Unfortunately, I haven't been able to find a solution that works with the build matrix as both the `before_install` and `before_script` [lifecycle steps](https://docs.travis-ci.com/user/job-lifecycle/) run after the build calls the initial `rvm use` and terminates the script:

https://travis-ci.org/mysociety/alaveteli/builds/566476767

:sob:

**Comment by lizconlan** [comment]
The odder solution would be - package 2.3.3 for bionic ourselves and (once Travis has APT Addons available), install it via APT Addons so that `rvm use: 2.3.3` (hopefully) works as the apt addons get installed first before `rvm use` gets called - here is a build where I helpfully got the APT config wrong and you can see from the logs that it never got as far as `rvm use` https://travis-ci.org/mysociety/alaveteli/jobs/566523043

**Comment by gbp** [comment]
> 2. Drop Xenial but don't update the CI config
> 
> 3. Drop Xenial, adopt the Travis Bionic environment but drop Ruby 2.3.3 from the testing matrix

I don't think testing against bionic on Travis is representative of real whole usage as the Travis images have been customised from the standard bionic image available. Of course its good to upgrade especially if we're not using xenial anywhere else.

There really shouldn't be any different between testing against Ruby 2.3.3 and Ruby 2.3.x.

I would be in favour of dropping switching to bionic and 2.3.3

**Comment by garethrees** [comment]
>  Travis [no longer supplies 2.3.3](https://docs.travis-ci.com/user/reference/bionic/#ruby-support) for their Bionic environment

I read "Other ruby versions can be installed during build time." as "you'll be able to install it from source, it'll just be slower", or something to that effect.

**Comment by lizconlan** [comment]
> I read "Other ruby versions can be installed during build time." as "you'll be able to install it from source, it'll just be slower", or something to that effect.

I think that was in the [Bionic docs](https://docs.travis-ci.com/user/reference/bionic/#ruby-support)

But, as above, this only works if you're not using the rvm-powered build matrix as then `rvm use` runs (and fails, terminating the build) before any user-supplied script is able to initiate an install. The callbacks to run them are never reached.

AFAICT, the only exception is the APT Addon stage (caveats - may not have been enabled for Bionic yet, have been unable to find a packaged ruby 2.3.3 for Bionic) which runs before the build matrix checks.

**Comment by garethrees** [comment]
> > I read "Other ruby versions can be installed during build time." as "you'll be able to install it from source, it'll just be slower", or something to that effect.
>
> I think that was in the [Bionic docs](https://docs.travis-ci.com/user/reference/bionic/#ruby-support)

Yes:

> * Pre-installed Rubies: `2.3.8`, `2.4.5`, `2.5.3` and `2.6.3`.
> * The default ruby is `2.5.3p105`.
> * Other ruby versions can be installed during build time.

I read this as "we supply binaries for `2.3.8`, `2.4.5`, `2.5.3` and `2.6.3`, but you can add `2.3.3` to the `rvm:` key (e.g. 90974b262b4e613b7211145e689e7a284e30d42a) and it will work. Clearly not :(.

I don't have a preference for how we move this forward now, as any approach is a bit less than ideal.

**Comment by lizconlan** [comment]
Just to note that our current Xenial environment on Travis defaults to Postgres 9.6

![Screen Shot 2019-08-06 at 11 06 35](https://user-images.githubusercontent.com/27760/62531510-81fd8400-b83a-11e9-8efd-2faba7ce374c.png)

**Comment by gbp** [comment]
Closing as we're aiming to move to GitHub actions
