### ISSUE TITLE
Show request prominance on admin summary page

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#5370]
I was using the admin summary page at:
https://www.whatdotheyknow.com/admin

and looking into those requests "reported by users as requiring administrator attention"

to prioritise which ones to look into it would be good if the admin summary page showed which ones were public vs requester_only or hidden. 

I don't think this is something worth fixing on its own, but it is one of many things which could contribute to a shift to administrating the site from within the web-application rather than relying on an email support mailbox. (#419 Bring user support and takedown requests within the system). 

To make that practical the usability of the admin summary page would ideally need an overhaul, this is just one small suggested tweak.  

I wonder if there are opportunities to reduce the time taken to administer the site by improving the admin summary page.  Currently on WhatDoTheyKnow it doesn't sound as if it gets much use.

**Comment by garethrees** [comment]
Basically the same as https://github.com/mysociety/alaveteli/issues/4915, but different page.

**Comment by RichardTaylor** [comment]
Related to #5434 as one of the bulk actions an admin might want to take is to change the prominence of all requests.  

The feature requested on this page would let admins easily see that such an action had taken place.

**Comment by garethrees** [comment]
This should be easier to do now that https://github.com/mysociety/alaveteli/pull/6248 is merged. We'll want to retain the link to the public request view from the eye icon, which wasn't covered in https://github.com/mysociety/alaveteli/pull/6248. There's a bit of refactoring of some of the `AdminHelper` methods to make this easier, but at least we now have `prominence_icon` to set the icon style.
