### ISSUE TITLE
Can't change timeframe on admin timeline when filtering

### ISSUE THREAD

**Issue by MattK1234** [mysociety/alaveteli#5371]
On the admin timeline on WhatDoTheyKnow (/admin/timeline) when one attempts to filter the events that are shown, for example just to show authority changes or request events, Alaveteli shows two days by default.

If you then attempt to change the time period from the default two days the timeline shows all events again.

This seems to happen whichever way you click the buttons, whether it's timeframe then type, or vice-versa.

**Comment by garethrees** [comment]
Investigation needed to see if this is a regression, or was just never built to do that. Would expect it to work though.

You can manually combine the URL params with an `&` though, e.g. `/admin/timeline?day=1&event_type=authority_change`

**Comment by sallytay** [comment]
It would be useful for creating reports of work / tasks done on WDTK to be able to change the timeline when filtering for authority change activities to more than just two days.

Although this can be done manually (https://www.whatdotheyknow.com/admin/timeline?event_type=authority_change&week=1 ) if the pre set parameters at the top of the page included this it would make the task quicker and more efficient

Sally

**Comment by garethrees** [comment]
A specific case of https://github.com/mysociety/alaveteli/issues/1748.

**Comment by HelenWDTK** [comment]
Fixing this would make my job easier, so I've had a go 🙂
