### ISSUE TITLE
Improve handling of users reporting their own requests for admin atttention

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#5377]
Users sometimes report their own requests for admin attention. 

The reasons on the form could be amended to better suit a user reporting their own request, currently the classifications, and wording are intended for reports raised by anyone. 

The reasons could start "I..."

"I accidentally sent personal correspondence"
"I have received an error message"

There's quite some overlap with the classification form and the "I've received an error message" option there which prompts a: "Please tell us more" form.   Perhaps we could add a general "I need help from the admin team in relation to this request" option on the classification form, which might stop users reporting their own requests instead. 

Related: Improve automated advice for users asked for to provide their names #5376

**Comment by RichardTaylor** [comment]
Today a WhatDoTheyKnow user has reported their own request for admin attention because a response is overdue. They used the report for admin attention rather than classifying their thread as still awaiting a response and being directed to /help/unhappy.  I think this is a reasonably common thing which happens, but I've not tried to count occurrences. 

Related to  #5378 Add option for requesting assistance to the request classification form 

The classification form does say "Submit Status (and we'll suggest what to do next)" but perhaps it needs to be made even clearer that selecting "I'm still waiting for my information" will lead to help and advice.

**Comment by RichardTaylor** [comment]
>a WhatDoTheyKnow user has reported their own request for admin attention because a response is overdue.

Inappropriate reports are now being labelled in the WhatDoTheyKnow.com support mailbox. Many of them are users writing to the admin team when they've not had a response, or if they're not happy with a response. 

The report a request option could direct people to /help/unhappy and prompt them to send a follow up to the public body rather than report the request.

**Comment by RichardTaylor** [comment]
This appears closely linked to 

https://github.com/mysociety/alaveteli/issues/4612

A key thing to do is direct users who are unhappy with a response to the advice we offer, without them writing to the admin team.

**Comment by HelenWDTK** [comment]
+1 to this. We see users hitting the report button when they need to do some other action in relation to their request on an almost daily basis. It would be nice to give them better options.

**Comment by garethrees** [comment]
This is desirable, but unlikely to be worked on in the next 12 months so closing for now.
