### ISSUE TITLE
An email alert is sent when a request is resent

### ISSUE THREAD

**Issue by MattK1234** [mysociety/alaveteli#5379]
The WhatDoTheyKnow admin team have alerts set up looking for `UKCOD` in emails. This generally indicates a bounce email that we might need to act on.

When an old request (6 months) is resent to a new contact address, it is generating an alert on the old response, which is the bounce message:

> -- Grounds Maintenance --
> Field Lane Junior Infant and Nursery School, Batley sent a response to Steve (27 February 2019)
> "...2MB3771.eurprd02.prod.outlook.com Message Hops HOP TIME FROM TO WITH RELAY (UTC) TIME 2/27/2019 local (Exim 4.89) (envelope-from 1 5:19:26 foi owl.*ukcod*.org.uk ) * PM 2/27/2019 esmtps 2 5:19:26 owl.*ukcod*.org.uk bittern.*ukcod*.org.uk (TLS1.2:ECDHE_RSA_AES_256_GCM_SHA384:256) * PM..."
> https://www.whatdotheyknow.com/request/grounds_maintenance_728?nocache=incoming-1319872#incoming-1319872

Users probably wouldn't know why this request has generated an alert.

**Comment by RichardTaylor** [comment]
In these cases I can't find the original alert email. We should have got an alert when the error message came in in February but I don't think we got it until the the original message was re-sent in September. 

Related-ish: 
* "More immediate alerts for responses to comments on others' requests" #3893
* Alerts sent on classification of a request can confuse recipients too. This is covered in the issue: "Prevent classification of old requests bumping them in sort orders" #2733

**Comment by garethrees** [comment]
This is desirable, but unlikely to be worked on in the next 12 months so closing for now.
