### ISSUE TITLE
Misleading cap command in deploy guidelines

### ISSUE THREAD

**Issue by schlos** [mysociety/alaveteli#5386]
URL: https://alaveteli.org/docs/installing/deploy/

Current:
* still on your local machine, run `cap -S stage=staging deploy:setup` to setup capistrano on the server

Expected:
* still on your local machine, run `bundle exec cap -S stage=staging deploy:setup` to setup capistrano on the server using the capistrano version provided by Alaveteli

**Comment by garethrees** [comment]
Rather than state `bundle exec` I've actually tweaked the instructions to specify the correct capistrano version to install.
