### ISSUE TITLE
Internal admin authority being created twice

### ISSUE THREAD

**Issue by gbp** [mysociety/alaveteli#5401]
There have been some cases [1] where the Internal admin authority has been created twice. While at Alaveteli Con 2019 we were able to take a look at the DB of an affected installation.

It appears the Internal admin authority translated columns were created in a secondary locale. This breas the logic in `PublicBody.internal_admin_body`, where, this query: https://github.com/mysociety/alaveteli/blob/d3dc6b3c075c98d6ca119bf12516f820af087ff1/app/models/public_body.rb#L385 will return more than one result which causes the `Multiple public bodies (n) found with url_name 'internal_admin_authority'` error to be raised.

One solution was to fix the database records by running:
```ruby
PublicBody::Translation.where(url_name: 'internal_admin_authority').where.not(locale: AlaveteliLocalization.default_locale).destroy_all
```

[1] https://groups.google.com/forum/m/#!topic/alaveteli-dev/YoOrH_qVDxc

**Comment by garethrees** [comment]
Just linking to https://github.com/codeforcroatia/imamopravoznati/issues/76 for future reference
