### ISSUE TITLE
If a user's email address becomes invalid, don't send email to it

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#5411]
If a user's email address becomes invalid, or has .invalid appended to it, prevent the system sending emails to it. 

Or alternatively devise other features to:
* Prevent all emails to a user from the system
* Prevent a user logging in

**Comment by garethrees** [comment]
What email was sent in this case?

> Prevent all emails to a user from the system

This is basically https://github.com/mysociety/alaveteli/issues/4603 (with an added extra of making it easy for an admin to enact this)

> Prevent a user logging in

"Closing" an account (part of ["Close and anonymise"](https://github.com/mysociety/alaveteli/blob/bae96d41e1101a01ada1cd1dcefcc19a0ec32606/app/models/user.rb#L469)) has this effect, though that isn't settable by admins.

**Comment by RichardTaylor** [comment]
This proposal is an suggested alternative to the proposed "Ability to unsubscribe from all transaction emails" and "Prevent a user logging in" features. 

It also flags up a current practice by admins which might want to be taken into account when implementing related features. 

For background - administrators are using the system in ways which may not have been envisaged:

* Anonymising a user account and set of requests, suspending the account, but retaining the email address in the user profile.  This prevents the user creating a new account with their email address. We use this to ban someone from re-signing up. We've used it with problematic users who have been misusing the service to publish material they shouldn't. 
* Editing a user's email address to make it invalid. Used following complaints about emails from the system, to prevent login, or when we want to publicly anonymise an account but keep a note internally as to the email address which was connected with it.

**Comment by garethrees** [comment]
Also related #3148

**Comment by garethrees** [comment]
I think this is essentially handled by the bounce recording. We try sending mail to everyone; if we receive a bounce from the recipient MTA because the email is invalid we record it and then stop sending email.

The issue here is that:

> `.invalid` is a reserved name so should never be used for a top-level domain. There is [a list here of similar domains on the IANA website](https://www.iana.org/assignments/special-use-domain-names/special-use-domain-names.xhtml).
>
> – https://github.com/mysociety/sysadmin/issues/1202#issuecomment-545496704

This doesn't actually go anywhere though, so I don't think its a problem.

I think this is best served by https://github.com/mysociety/alaveteli/issues/4910, as many of the "should we email this user" checks are hooked in to whether an account is active or not.
