### ISSUE TITLE
Add option to close a request to add a new body without a response on body edit pages

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#5427]
Emails sent to the admin team following a request to add an authority contain links for options to:
 
* Add the authority:
* Close the request and respond:

following the latter link only gives an option to "Close the request and respond", there is no option to close the request without a response. 

![Screenshot 2019-10-23 at 12 01 02](https://user-images.githubusercontent.com/282788/67386450-ea801580-f58c-11e9-81dd-95db87c0b154.png)

There is such an option at /admin where the options are: "Close", "Close and respond", and "Add authority".

![Screenshot 2019-10-23 at 12 00 54](https://user-images.githubusercontent.com/282788/67386458-ee139c80-f58c-11e9-8338-04a81c741b72.png)

Closing without a response is desirable in cases of misuse of the form, or repeated requests from the same person asking us to add the same body. 

Currently to close a request without a reply an administrator has to find it via /admin 

Ideally perhaps closing without a response would still send a message to the admin team, with a subject such that it's threaded with the request, so the email thread would be resolved.

**Comment by garethrees** [comment]
Should be quite an easy change.

We already use the same action to close OR close and respond:

https://github.com/mysociety/alaveteli/blob/fae66e3ee51818dfbc4cc2f86ecc27d43c0dbb0c/app/controllers/admin_public_body_change_requests_controller.rb#L11-L16

I think we need:

1. Change the current [button text](https://github.com/mysociety/alaveteli/blob/develop/app/views/admin_public_body_change_requests/edit.html.erb#L6) from "Close" to "Close and respond"
2. Add a new `button_to` (with class `btn-danger`) that submits to the same action, without the `:subject` and `:response` params.
3. For bonus points – render [`_change_request_summary`](https://github.com/mysociety/alaveteli/blob/develop/app/views/admin_general/_change_request_summary.html.erb) above the response.

I think keeping the links from the email as `Close the request and respond` is fine – it'll be clear enough once you've used it once or twice that you can choose not to respond.
