### ISSUE TITLE
Consider replacing recaptcha

### ISSUE THREAD

**Issue by hsenag** [mysociety/alaveteli#543]
Recaptcha graphics are becoming increasingly illegible - perhaps a victim of its own success as all the easy ones have been done? We should consider alternatives - one WDTK user suggests Kcaptcha instead.

**Comment by garethrees** [comment]
Recaptcha 2.0 (or whatever its called) is much better and implemented in Alaveteli:

![screen shot 2016-10-25 at 10 13 20](https://cloud.githubusercontent.com/assets/282788/19679931/ad35502c-9a9b-11e6-940f-c318fefc742a.png)
