### ISSUE TITLE
Add Dead Man's Handle to Alaveteli installs

### ISSUE THREAD

**Issue by TomSteinberg** [mysociety/alaveteli#544]
http://en.wikipedia.org/wiki/Dead_man's_switch

To prevent the web filling with unhelpful, misguiding websites that appear to offer FOI-requesting services when they actually haven't been maintained, we should make a dead man's handle an integral part of new installs.

**Comment by garethrees** [comment]
Closing this as I don't think this is anything we're going to act on any time soon. Can reopen if it comes up again.
