### ISSUE TITLE
Link to /admin/spam_addresses from the admin toolbar under Tools

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#5442]
Add a link to  /admin/spam_addresses from the admin toolbar under the "Tools" menu.

**Comment by RichardTaylor** [comment]
To make this feature easy to find perhaps it could also be linked from the holding pen?

**Comment by garethrees** [comment]
> To make this feature easy to find perhaps it could also be linked from the holding pen?

It is, in a way. Not as ideal, but hopefully the link in the admin nav (https://github.com/mysociety/alaveteli/pull/5444) and improved documentation (https://github.com/mysociety/alaveteli/issues/5443) should minimise the need.

![Screenshot 2019-11-05 at 15 05 02](https://user-images.githubusercontent.com/282788/68219353-c1747180-ffdd-11e9-8adb-ad57896de946.png)
