### ISSUE TITLE
Backpaged requests should impact robots.txt and no-index meta tags

### ISSUE THREAD

**Issue by MattK1234** [mysociety/alaveteli#5496]
When we 'backpage' a request, we don't want it to appear in search or on user page. It's an in-between for 'public' and 'requester_only' as anyone can still find it with the URL. Therefore if the page is cited elsewhere etc we won't impact the URL, people can still find the request and it is still publicly accessible.

Perhaps 'backpaging' a request could add the no-index and robots.txt to the relevant pages so that the page is no longer crawled by search engine bots?

Use cases might be low-quality requests, but not so bad that they warrant removal, as well as people promoting products/services. We don't really want to encourage FOI to be used as a way to sell things.

**Comment by RichardTaylor** [comment]
Consider adding 

`X-Robots-Tag: noindex`

to the HTTP header for attachments on the request in question. 

Also beware the potential impact of using both robots.txt and a noindex tag :

>We have to crawl your page in order to see your meta tags. If your page is still appearing in results, it's probably because we haven't crawled your site since you added the tag. ....  Another reason could also be that your robots.txt file is blocking this URL from Google web crawlers, so we can't see the tag

https://developers.google.com/search/docs/advanced/crawling/block-indexing

**Comment by garethrees** [comment]
> Consider adding `X-Robots-Tag: noindex` to the HTTP header for attachments on the request in question.

Yep 👍 

> Also beware the potential impact of using both robots.txt and a noindex tag :

Yeah I was just going to use the header. Don't think we need to worry about `robots.txt` for this kind of use.

**Comment by RichardTaylor** [comment]
Consider updating the inline-help on the admin page which explains what "backpage" does as part of the introduction of this feature. Currently it states:

>backpage means hidden from lists/search;

There are also references to backpaging in the Alaveteli Documentarian 

https://alaveteli.org/docs/running/requests/
https://alaveteli.org/docs/running/hiding_information/

**Comment by garethrees** [comment]
> Consider updating the inline-help on the admin page which explains what "backpage" does as part of the introduction of this feature.
> …
> There are also references to backpaging in the Alaveteli Documentarian

Good point. Fixed in https://github.com/mysociety/alaveteli/pull/6071 & https://github.com/mysociety/alaveteli/pull/6073.
