### ISSUE TITLE
Use local GeoIP database in tests

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#5518]
We [use Gaze](https://github.com/mysociety/alaveteli/blob/develop/config/test.yml#L108-L109) in spec runs; Hitting Gaze is slow.

Probably requires https://github.com/mysociety/alaveteli/issues/5516.
Related to https://github.com/mysociety/alaveteli/issues/5040.

**Comment by garethrees** [comment]
We'll want to cache this, as downloads may be rate limited https://dev.maxmind.com/geoip/geoipupdate/#Direct_Downloads

**Comment by gbp** [comment]
Using Gaze is the test env isn't an issue as the HTTP requests are stubbed https://github.com/mysociety/alaveteli/blob/develop/spec/support/gaze.rb#L4

**Comment by garethrees** [comment]
So they are! Need to do this before https://github.com/mysociety/alaveteli/issues/2905 anyway.

**Comment by garethrees** [comment]
Fixed by https://github.com/mysociety/alaveteli/pull/7004
