### ISSUE TITLE
Authority's reply shows as base64 gibberish

### ISSUE THREAD

**Issue by lukaskovarik** [mysociety/alaveteli#5525]
Hi community, 

we've been seeing this occasionally on our CZ installation in the past, and this is the newest example: https://www.infoprovsechny.cz/request/jizdni_rady_verejne_linkove_dopr_6

Looks like a certificate or possibly even other attachments are not being decoded properly. Has anybody seen this before? Maybe we're doing something wrong? 

Many thanks! 

Lukas

**Comment by garethrees** [comment]
Thanks for getting in touch.

Looks like this issue https://github.com/mysociety/ipvtheme/issues/40, so closing as a duplicate.

**Comment by lukaskovarik** [comment]
Thanks for a prompt reaction @garethrees, I wasn't aware of that one! 👍
