### ISSUE TITLE
RSS for incoming messages

### ISSUE THREAD

**Issue by lukaskovarik** [mysociety/alaveteli#5532]
Hi, 

I'm trying to get the right query for a list of all incoming messages from authorities for moderation/anonymisation purposes (to be able to set up notifications whenever a new reply arrives). 

I tried the "catch-all" RSS feed (see the screenshot below):

![image](https://user-images.githubusercontent.com/17449800/71978614-0dc97100-321c-11ea-80c7-9ded50d239cd.png)

...and expected to get a verbatim version of the list that appears below: 
![image](https://user-images.githubusercontent.com/17449800/71978891-b1b31c80-321c-11ea-9ec4-930ece06f1d2.png)

...yet what I get seems to be a bit different, e.g. the first item is my own request of which I have only changed the status, and it does not appear in the search listing:

![image](https://user-images.githubusercontent.com/17449800/71978813-86303200-321c-11ea-9a9a-c358f5f18ec9.png)

I also tried to tweak the query in the URL, but with no luck. 

Is there a way to get a list of the newest incoming messages across all requests? An equivalent of a hypothetical `SELECT * FROM messages WHERE incoming = 1 ORDER BY received_at DESC` (Doesn't necessarily have to be RSS, although that would be the most practical).

Many thanks,

Lukas

**Comment by garethrees** [comment]
The RSS feed is a feed of events, which include status updates.

You could "Follow" the body and you'll get email notifications of events through the app, though I think this would include status updates.

You could use the [advanced search](https://www.whatdotheyknow.com/advancedsearch) with `requested_from:body_url_name latest_variety:response` which I think may do what you want.

Going to close this as I don't think there's a bug in the system here. You might want to [ask the community](https://alaveteli.org/community/#project-mailing-lists) if they do anything similar.

**Comment by lukaskovarik** [comment]
Thanks Gareth, very helpful indeed! The _variety_ parameter was exactly what I was missing.
