### ISSUE TITLE
Unexpected behaviour relating to email address redaction on specific request

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#5560]
At

https://www.whatdotheyknow.com/admin/incoming_messages/1513542/edit

The message as displayed on WhatDoTheyKnow states:

> FOI Lead at [[email address]](https://www.whatdotheyknow.com/help/officers#mobiles)

The raw source (either viewed via the WDTK admin system and base64 decoded, or  from the message downloaded and opened in an email client) states:

> FOI Lead at [email address]

Was there ever an email address in the incoming message? Is Alaveteli redacting it too soon so as to make it inaccessible to administrators?

If there wasn't an email address in the incoming message why has the link to https://www.whatdotheyknow.com/help/officers#mobiles - which suggests redaction has occurred - been introduced?

As yet this appears not to be a general problem I can only see it on this specific request.

**Comment by gbp** [comment]
> Was there ever an email address in the incoming message?

No.

> Is Alaveteli redacting it too soon so as to make it inaccessible to administrators?

The raw source doesn't have any redactions applied. 

> If there wasn't an email address in the incoming message why has the link to https://www.whatdotheyknow.com/help/officers#mobiles - which suggests redaction has occurred - been introduced?

It seems Alaveteli simply searches for "[email address]" or "[mobile number]" to insert these links - the logic could certainly be improved. https://github.com/mysociety/alaveteli/blob/9b022ec/app/models/incoming_message.rb#L596-L601

**Comment by garethrees** [comment]
Closing as this wasn't a bug.
