### ISSUE TITLE
Citations added to requests should be visible within the correspondence thread

### ISSUE THREAD

**Issue by mdeuk** [mysociety/alaveteli#5573]
We've had a request from a WhatDoTheyKnow user on [Twitter](https://twitter.com/benefitforums/status/1228226116625801216) to have citations which are added to requests automatically appear within the timeline/thread of a given request.

> Benefit Forums - @benefitforums: A 'Citation' option added to @WhatDoTheyKnow foi requests https://www.mysociety.org/2020/01/14/has-your-foi-request-been-used-in-a-news-story-now-you-can-let-everyone-know/
>
>Example https://www.whatdotheyknow.com/request/provision_of_mailing_lists_of_vo (right column)
>
>Citations should b duplicated in request timeline, like annotations , as might be missed

Ref #5483, #34

**Comment by MattK1234** [comment]
Our user further comments at https://twitter.com/benefitforums/status/1228289752203497474:

> Thnks[sic], duplication in timeline would do no harm. It's a web convention for comments to articles 2 b appended @ the end, rather than in a right hand column. Would suggest Citations explicitly state nature like news, blog and one be added that covers court rulings and ICO decisions

**Comment by mdeuk** [comment]
Wonder if we could use a variation of tag based notes, appended at the end of the correspondence thread? This sort of thing would no doubt be dynamically regenerated when a citation was added (or rendered in an equivalent way to the existing citations).

Just a thought, because this capability didn't exist when this ticket was first created (ref: https://github.com/mysociety/alaveteli/issues/7220#issuecomment-1261090521)

**Comment by garethrees** [comment]
Yeah it's in my mind how we simplify the variety of things we have to get towards https://github.com/mysociety/alaveteli/issues/34.

There's quite a conceptual difference between citations as:

1. Events
2. High-prominence callouts (more analogous to "breaking news!" or pinned tweets)
3. Metadata as an aside (like footnotes in wikipedia)

Thinking about it this way, perhaps they should be recorded as Events, collected in an aside as Metadata and then selectively promoted in a Callout.

**Comment by garethrees** [comment]
Closing this as I think these are more metadata and I think mostly unrelated to the timeline of the thread.
