### ISSUE TITLE
Drop support for Postgres 9.6

### ISSUE THREAD

**Issue by gbp** [mysociety/alaveteli#5574]
Postgres 9.4 is now unsupported: 
https://www.postgresql.org/support/versioning/ 

We probably want to specify Alaveteli requires/recommend Postgres 9.6+ which is what we currently run on.

We previously warned users to upgrade to 9.4 in the changelog https://github.com/mysociety/alaveteli/commit/92e65a3c49efd8ecc5a8db7119c1018aa3a9d4a2

**Comment by garethrees** [comment]
So is the task here to state "Alaveteli now requires Postgres 9.6" in the changelog?

**Comment by gbp** [comment]
Yes

**Comment by gbp** [comment]
We currently run WDTK on v9.6 this will be changing to v13 when migrating soon. We will drop support for <v13
