### ISSUE TITLE
Link to batch requests not working 

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#5584]
For example at 

https://www.whatdotheyknow.com/request/current_and_historical_registers_51

the link with text: "a batch sent to 415 authorities" pointing to

https://www.whatdotheyknow.com/info_request_batch/1116

leads to a page giving the error:

>Sorry, we couldn't find that page

**Comment by garethrees** [comment]
Hmm _I_ can see it, but not in private mode. I wonder if the batch has an embargo attached even though it was never set on the requests.

**Comment by gbp** [comment]
I think this is caused when `InfoRequestBatch#embargo_duration` is an empty string but in the `ability.rb` we're expecting it to be `nil`. Not sure where the empty string is coming from.

**Comment by garethrees** [comment]
This is affecting https://www.wob-knop.nl/info_request_batch/2 too.

**Comment by garethrees** [comment]
To fix manually:

```ruby
b = InfoRequestBatch.find(ID_OF_BATCH)
b.update(embargo_duration: nil)
```

**Comment by garethrees** [comment]
> I've just tried clicking the two that @RichardTaylor has noted above and they work OK for me. I'm logged in on an Android mobile device with Chrome.

You're a `pro_admin`, so the privacy period isn't checked.

> https://www.whatdotheyknow.com/info_request_batch/1117
> https://www.whatdotheyknow.com/info_request_batch/1065

Fixed these.

**Comment by MattK1234** [comment]
> You're a pro_admin, so the privacy period isn't checked.

Aha, forgot that. Thanks!

**Comment by RichardTaylor** [comment]
Another example. Not working while not logged in. 

https://www.whatdotheyknow.com/info_request_batch/1234

**Comment by garethrees** [comment]
> https://www.whatdotheyknow.com/info_request_batch/1234

Fixed

**Comment by RichardTaylor** [comment]
On WhatDoTheyKnow.com /info_request_batch/1418 isn't working

**Comment by RichardTaylor** [comment]
This remains an issue with two AskTheEU batches: 

https://www.asktheeu.org/en/request/refused_registration_to_access_t
https://www.asktheeu.org/en/info_request_batch/1

and 

https://www.asktheeu.org/en/request/work_with_palantir_13
https://www.asktheeu.org/en/info_request_batch/2

**Comment by garethrees** [comment]
This will get resolved via the linked pull requests on upgrading AskTheEU.

**Comment by RichardTaylor** [comment]
I realise the code fix has been made, is it useful to note it's still not yet taken effect elsewhere eg. 

https://transparencia.be/nl_BE/request/enquete_du_journal_lesoir_projet_6
https://transparencia.be/nl_BE/info_request_batch/38

https://transparencia.be/nl_BE/request/enquete_du_vif_et_du_soir_projet_27
https://transparencia.be/nl_BE/info_request_batch/40

I've note re-opened the issue this time.

**Comment by RichardTaylor** [comment]
I'm guessing the following might be inaccessible due to an embargo, but if not perhaps it's broken:

https://www.whatdotheyknow.com/info_request_batch/2175

**Comment by RichardTaylor** [comment]
This issue appears to have arisen again, this time in relation to

https://www.whatdotheyknow.com/info_request_batch/2342

requests within that batch are published

https://www.whatdotheyknow.com/request/planning_permission_rejections_d_138

**Comment by garethrees** [comment]
> This issue appears to have arisen again, this time in relation to https://www.whatdotheyknow.com/info_request_batch/2342…

Hmm almost the reverse of the previous case. In this case the `embargo_duration` is set, but all of the requests have an `expire_embargo` event.

```ruby
InfoRequestBatch.find(2342).embargo_duration
# => "3_months"

InfoRequestBatch.find(2342).info_requests.size
# => 285

InfoRequestEvent.where(info_request_id: InfoRequestBatch.find(2342).info_requests.pluck(:id)).where(event_type: 'expire_embargo').size
# => 285
```

I tried manually setting the `embargo_duration` to `nil` but that resulted in validation errors:

```ruby
InfoRequestBatch.find(2342).update(embargo_duration: nil)
# => false

b = InfoRequestBatch.find(2342)
# => #<InfoRequestBatch id: 2342 …>

b.embargo_duration = nil
# => nil

b.valid?
# => false

b.errors.messages
# => {:existing_batch=>["must be blank"]}
```

I  think this is related to the change in https://github.com/mysociety/alaveteli/pull/7077 @gbp?

**Comment by gbp** [comment]
Looks like batch `2342`, with 285 requests, and `2343`, with 40 requests, are the same request to a different set of authorities.

In the two sets there are 4 duplicate requests to bodies `92678`, `91365`, `110917` and `91531`.

This is why the `existing_batch` validation is matching. I guess we should scope this validation to only run when creating new batches so the update to remove the `embargo_duration` value succeeds.

For now I have manually updated these batches so they are now visible

**Comment by garethrees** [comment]
> This is why the `existing_batch` validation is matching. I guess we should scope this validation to only run when creating new batches so the update to remove the `embargo_duration` value succeeds.

Ah, yeah, only running on create seems sensible.

**Comment by gbp** [comment]
```ruby
InfoRequestBatch.where.not(embargo_duration: nil).joins(info_requests: :info_request_events).
  where(info_request_events: { event_type: 'expire_embargo' }).distinct.pluck(:id) #=> [1382, 1597]
```

There are two other batches which have the same issue. I'll update those as well.

**Comment by gbp** [comment]
Actually `1597` has been re-embargoed so that is still hidden.
