### ISSUE TITLE
Modify authority email and then resend request : keep old email adress ?

### ISSUE THREAD

**Issue by PatrickInstalle** [mysociety/alaveteli#5613]
Question of "feature".

Actually after a change of an email destination of an authority, the option send again do not change de destination email. It is not what I expected.

The "workaround" is making a new request. 

It could be a a design feature or not. If it is in the design, an alert could be raised as "The email destination of the authority has been changed. Do you still send a request to the previous address ?"

**Comment by garethrees** [comment]
This already exists.

For example, on [this request](https://www.whatdotheyknow.com/request/fm_hard_services_2) you can see the message got resent to the new contact address after a delivery failure:

![Screenshot 2020-04-14 at 09 14 31](https://user-images.githubusercontent.com/282788/79201750-7124f980-7e30-11ea-8e3e-995bc337fed5.png)

Admins can resend messages on the admin page for a request, either by clicking in to the outgoing message, or expanding it, which reveals the resend button.

![Screenshot 2020-04-14 at 09 15 47](https://user-images.githubusercontent.com/282788/79201899-aa5d6980-7e30-11ea-96e4-1542c1ec70ed.png)

Users cannot resend requests – they should mark the request for admin attention.
