### ISSUE TITLE
Spam addresses list should ignore case

### ISSUE THREAD

**Issue by MattK1234** [mysociety/alaveteli#5624]
The spam addresses list which is used to add spam `To:` addresses which are not request emails should be case insensitive.

In this case we had an address in the spam addresses list in uppercase, which didn't prevent a spam email arriving in the holding pen with the `To:` address in lowercase.

AFAIK capitalisation doesn't matter in email addresses, so we should ignore it on the spam addresses list.

**Comment by garethrees** [comment]
Marked as an `improvement` as its not broken as such.

Current workaround would be to add a new spam address, but I agree that this isn't great.

We use [`exists?`](https://api.rubyonrails.org/v5.1.7/classes/ActiveRecord/FinderMethods.html#method-i-exists-3F) to look up the address.

https://github.com/mysociety/alaveteli/blob/4d4168ef62856fe10c3977aa91b7ae6c427cdedb/app/models/spam_address.rb#L17

Given `exists?` supports finder conditions, we could implement it like:

```ruby
  def self.spam?(email_address)
    exists?(['email ILIKE ?' email_address])
  end
```
