### ISSUE TITLE
Mail sent To team@whatdotheyknow.com with Cc pro_team@whatdotheyknow.com does not get delivered to team@

### ISSUE THREAD

**Issue by sagepe** [mysociety/alaveteli#5649]
When an email is received that was sent both to a regular support address and a Pro support address (as per the example in the title), the mail handling code will override the regular support address with the pro support address defined in `PRO_CONTACT_EMAIL`.

See [these lines](https://github.com/mysociety/alaveteli/blob/4b02ca7ee892688bcea18cd9a32579d6e3fb5cc1/lib/mail_handler/reply_handler.rb#L108-L111) in `reply_handler.rb`:
```ruby
def self.get_forward_to_address(message)
  forward_to = AlaveteliConfiguration.forward_nonbounce_responses_to
  if AlaveteliConfiguration.enable_alaveteli_pro
    pro_contact_email = AlaveteliConfiguration.pro_contact_email
    original_to = message ? MailHandler.get_all_addresses(message) : []
    if original_to.include?(pro_contact_email)
      forward_to = AlaveteliConfiguration.forward_pro_nonbounce_responses_to
    end
  end
  forward_to
end
```
 The call to `MailHandler.get_all_addresses(message)` in `mail_backend.rb`[returns an array that includes things in CC](https://github.com/mysociety/alaveteli/blob/4b02ca7ee892688bcea18cd9a32579d6e3fb5cc1/lib/mail_handler/backends/mail_backend.rb#L135-L143):
```ruby
def get_all_addresses(mail, include_invalid: false)
  addrs = []
  addrs << mail.to
  addrs << mail[:to].try(:value) if mail.to.nil? && include_invalid
  addrs << mail.cc
  addrs << mail[:cc].try(:value) if mail.cc.nil? && include_invalid
  addrs << (mail['envelope-to'] ? mail['envelope-to'].value.to_s : nil)
  addrs.flatten.compact.uniq
end
```
The first snippet then resets `forward_to` to `AlaveteliConfiguration.forward_pro_nonbounce_responses_to` if `AlaveteliConfiguration.pro_contact_email` is found in the `original_to` array - which it will be in this case.

More details available in [this internal ticket](https://github.com/mysociety/sysadmin/issues/1276).

**Comment by garethrees** [comment]
Just noting that this was implemented in https://github.com/mysociety/alaveteli/pull/3682 and similar issue fixed in https://github.com/mysociety/alaveteli/pull/4948
