### ISSUE TITLE
prioritise attachments displayed in reponses

### ISSUE THREAD

**Issue by mk270** [mysociety/alaveteli#5652]
Where there are more than about three attachments to a message, only three or so appear to be displayed by default. These may include garbage from an email signature alongside the substantive attachment to the email. For example, in [this response](https://www.whatdotheyknow.com/request/complaints_against_chief_officer#outgoing-1014704) there are five "attachments" but four of them are inlined logos and icons, and the fifth is the PDF requested, which can be revealed by clicking "Show all attachments".

One might see that the attachments all appear to be routine email signature garbage, and overlook the presence of the document requested, concluding it wasn't actually there.

I propose that where there are so many attachments, that they be sorted (e.g., by putting documents ahead of images, and/or by size).

**Comment by mdeuk** [comment]
This issue appears to relate to #4773

**Comment by mk270** [comment]
Thanks @mdeuk ; closing as duplicate
