### ISSUE TITLE
Are annotations clear enough that they are just comments?

### ISSUE THREAD

**Issue by MattK1234** [mysociety/alaveteli#5694]
[Terrible title, I know :-) Sorry... Couldn't think of anything better to describe what I'm ticketing.]

Is it clear enough to users that annotations are just comments from other users (or theirselves), as opposed to replies or advice from the public bodies?

Take request 667768 for example,

1. An annotation was added
2. The user replied to the public body instead, as if the annotation was from them.
3. Another annotation was added (separate user) explaining that the annotation in 1 was not from the public body etc.
4. The user replied to the public body again, thanking them for the above info.

The user is evidently confused. Perhaps there's some things we could do. Also, the public body will be confused regarding the two follow up messages, without context.

- Perhaps we should collect any other examples on this ticket, so we can see whether this is a frequent issue.
- Should we use 'comment' rather than 'annotation'?
- Could we perhaps add a '?' to the end of the line "xxx left an annotation" with hover text that explains what an annotation is etc.

**Comment by garethrees** [comment]
Interesting. Probably not a really common issue, but I can see that someone not so familiar with the web could get confused.

> Should we use 'comment' rather than 'annotation'?

At some point we _did_ use comment (the application model is called [`Comment`](https://github.com/mysociety/alaveteli/blob/17636f3cc6334f9fe0b1d5486baea71f354bd6f0/app/models/comment.rb)) but I think we changed to annotation to discourage general chatter.

> Could we perhaps add a '?' to the end of the line "xxx left an annotation" with hover text that explains what an annotation is etc.

Yeah something like this might be a nice addition.

**Comment by MattK1234** [comment]
Just to note that we are a bit inconsistent in what we say in the notification emails. In the subjecte we use 'note'. In the main text of the email we use 'annotated'. Ideally we should use the same name throughout I think.
 https://github.com/mysociety/alaveteli/blob/010b91ef94c3beaae4382cce28b553f3a51f8f65/app/mailers/request_mailer.rb#L187

https://github.com/mysociety/alaveteli/blob/010b91ef94c3beaae4382cce28b553f3a51f8f65/app/mailers/request_mailer.rb#L202

**Comment by garethrees** [comment]
Closing as I think it's relatively clear. Will always get the odd bit of confusion, but it doesn't seem like a more broadly concerning issue.
