### ISSUE TITLE
Report request event ruby object exposed in admin timeline

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#5699]
* Create a request as silly
* Report request as bob (e.g. "contains personal information")
* View timeline as an admin:

<img width="1006" alt="Screenshot 2020-06-03 at 09 09 50" src="https://user-images.githubusercontent.com/282788/83612216-05325800-a57a-11ea-8d6a-a0f5b0b2decc.png">

**Comment by gbp** [comment]
Duplicate of #5485
