### ISSUE TITLE
Ensure administrator action taken to hide material is effective promptly 

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#5763]
Ideally administrator action taken to hide material would be effective immediately. In cases of removal of eg. defamatory material or sensitive personal information prompt removal can be important. 

Current issues:

* Due to caching administrator actions to hide material through either censor rules or changing the prominence of requests/messages/annotations are not always immediately effective from the point of view of a non-logged in user. 

* Administrators may not realise that what they are seeing when logged in is not what a non-logged in user will see (due to caching)

* It is not clear to administrators what the expected behaviour of the system is. 

* We often say to correspondents that changes may take up to 24 hours to take effect, in many cases this is undesirable. 

* It feels as though there is inconsistency, with some changes taking effect promptly and others not. 

* Material to be redacted can appear on many different pages, and on different places on pages including in search/listing snippets, and under "requests like this" etc.

**Comment by garethrees** [comment]
A specific use case for #1006

**Comment by RichardTaylor** [comment]
Closing as a duplicate of #1475
