### ISSUE TITLE
[ERROR] request#show (ActionView::Template::Error) "incompatible character encodings: UTF-8 and ASCII-8BIT"

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#5783]
```
An ActionView::Template::Error occurred in request#show:

incompatible character encodings: UTF-8 and ASCII-8BIT
lib/mail_handler/backends/mail_backend.rb:60:in `mail_from_outlook'

-------------------------------
Request:
-------------------------------

* URL : https://www.asktheeu.org/en/request/public_documents_related_to_disi_6
* HTTP Method: GET
* Parameters : {"controller"=>"request", "action"=>"show", "url_title"=>"public_documents_related_to_disi_6", "locale"=>"en"}
* Timestamp : 2020-07-02 11:05:38 +0200
* Rails root : /REDACTED/alaveteli-2020-06-18T09-21-33

-------------------------------
Session:
-------------------------------

* session id: [FILTERED]
* data: {"session_id"=>"REDACTED", "locale"=>"en"}

-------------------------------
Backtrace:
-------------------------------

lib/mail_handler/backends/mail_backend.rb:60:in `mail_from_outlook'
lib/mail_handler/backends/mail_backend.rb:188:in `decode_attached_part'
lib/mail_handler/backends/mail_backend.rb:241:in `expand_and_normalize_parts'
lib/mail_handler/backends/mail_backend.rb:216:in `block in expand_and_normalize_parts'
lib/mail_handler/backends/mail_backend.rb:216:in `expand_and_normalize_parts'
lib/mail_handler/backends/mail_backend.rb:284:in `get_attachment_leaves'
lib/mail_handler/backends/mail_backend.rb:355:in `get_attachment_attributes'
app/models/incoming_message.rb:536:in `extract_attachments!'
app/models/incoming_message.rb:98:in `block in parse_raw_email!'
app/models/incoming_message.rb:97:in `parse_raw_email!'
app/models/incoming_message.rb:178:in `mail_from'
app/models/incoming_message.rb:197:in `safe_mail_from'
app/models/incoming_message.rb:220:in `specific_from_name?'
app/views/request/_incoming_correspondence.html.erb:4:in `_app_views_request__incoming_correspondence_html_erb___4239059047440180258_69914119794420'
app/views/request/_correspondence.html.erb:4:in `_app_views_request__correspondence_html_erb__4133394796544516923_69914122355520'
app/views/request/show.html.erb:70:in `block in _app_views_request_show_html_erb___2337845117304762896_69914123240540'
app/views/request/show.html.erb:68:in `_app_views_request_show_html_erb___2337845117304762896_69914123240540'
app/controllers/request_controller.rb:133:in `block (3 levels) in show'
app/controllers/request_controller.rb:132:in `block in show'
lib/alaveteli_localization.rb:43:in `with_locale'
app/controllers/request_controller.rb:83:in `show'
app/controllers/application_controller.rb:115:in `record_memory'
lib/strip_empty_sessions.rb:13:in `call'
```

**Comment by garethrees** [comment]
Started seeing a lot of these come in over the past few days.

**Comment by gbp** [comment]
Can't even get to the admin request#show page

Request ID: 8270
Incoming message ID: 26831

**Comment by gbp** [comment]
This issue is fixed by https://github.com/aquasync/ruby-msg/pull/16 but this conflicts with our changes at https://github.com/mysociety/ruby-msg/pull/3. I'm not really sure what our changes are doing, anyone able to provide context... 5 years later? @crowbot @garethrees ?

**Comment by garethrees** [comment]
Might be able to [manually add the response](https://github.com/mysociety/alaveteli/wiki/Manually-adding-responses) as a temporary fix until we can fix the underlying problem.

**Comment by gbp** [comment]
> Might be able to [manually add the response](https://github.com/mysociety/alaveteli/wiki/Manually-adding-responses) as a temporary fix until we can fix the underlying problem.

Not able to follow these step as generating a officer upload URL also errors

**Comment by gbp** [comment]
I've attempted to do the officer upload via the console (by calling `RequestMailer#fake_response`) and while it looks like it worked it hasn't added a message to the request `¯\_(ツ)_/¯`

The message in question is only an acknowledgement and there has since been another response to the FOI. To get this working for this case I have simply deleted the response.

**Comment by garethrees** [comment]
Just noting the relevant snippet for reproducing the error:

```ruby
require 'mapi/msg'
content = File.read '/home/vagrant/tmp/28101-outlook-attachment.msg'
msg = Mapi::Msg.open(StringIO.new(content))
msg.to_mime.to_s
```

**Comment by garethrees** [comment]
https://yehudakatz.com/2010/05/05/ruby-1-9-encodings-a-primer-and-the-solution-for-rails/

**Comment by gbp** [comment]
This is happening for:

Request ID: 8516
Incoming message ID: 27953

**Comment by garethrees** [comment]
http://tenderlovemaking.com/2020/01/13/guide-to-string-encoding-in-ruby.html

**Comment by garethrees** [comment]
Another case:

Request URL: `https://www.asktheeu.org/en/alaveteli_pro/info_requests/vaccine_talks_2`
Request ID: 8558
Incoming message ID:

**Comment by garethrees** [comment]
We haven't fixed the underlying issue (https://github.com/mysociety/alaveteli/issues/5783#issuecomment-655740838), but we've made our parsing much more resilient to failure (https://github.com/mysociety/alaveteli/pull/5920) and the message content in the original bug report is now visible.

> Request URL: https://www.asktheeu.org/en/alaveteli_pro/info_requests/vaccine_talks_2

In this case, the `.msg` file is downloadable and openable in (presumably) Outlook.
