### ISSUE TITLE
Script based installation option error on Ubuntu 16.04.

### ISSUE THREAD

**Issue by mfabunmi2013** [mysociety/alaveteli#5825]
Hi All,
I get the error below, when i attempt the use of the scripted installation method on a clean version on Ubuntu 16.04 on Amazon AWS.

**********************************************************************************************************************************************************************************
Bundle complete! 85 Gemfile dependencies, 178 gems now installed.
Bundled gems are installed into /home/alaveteli/bundle.
Installing theme alavetelitheme from git://github.com/mysociety/alavetelitheme.g                                                                                                             it
Running uninstall hook in /var/www/alaveteli/alaveteli/lib/themes/alavetelitheme
9280b9493a83ca1cbc2b3eb1317e0f06c4e16273
Checking out origin/develop
HEAD is now at 9280b94... Merge branch 'master' into develop
Running install hook in /var/www/alaveteli/alaveteli/lib/themes/alavetelitheme
Running post_install hook in /var/www/alaveteli/alaveteli/lib/themes/alavetelith                                                                                                             eme
alavetelitheme successfully installed in: /var/www/alaveteli/alaveteli/lib/theme                                                                                                             s/alavetelitheme

rake aborted!
OpenURI::HTTPError: 401 Unauthorized
/var/www/alaveteli/alaveteli/lib/tasks/geoip.rake:25:in `block (4 levels) in <to                                                                                                             p (required)>'
/var/www/alaveteli/alaveteli/lib/tasks/geoip.rake:23:in `open'
/var/www/alaveteli/alaveteli/lib/tasks/geoip.rake:23:in `block (3 levels) in <to                                                                                                             p (required)>'
/var/www/alaveteli/alaveteli/lib/tasks/geoip.rake:20:in `block (2 levels) in <to                                                                                                             p (required)>'
/home/alaveteli/bundle/ruby/2.3.0/gems/rake-12.3.3/exe/rake:27:in `<top (require                                                                                                             d)>'
Tasks: TOP => geoip:download_data
(See full trace by running task with --trace)
**********************************************************************************************************************************************************************************

Cheers,
Michael Fabunmi

**Comment by gbp** [comment]
A fix for this issue has been merged and releases as part of [0.38.0.0](https://github.com/mysociety/alaveteli/releases/tag/0.38.0.0)

**Comment by mfabunmi2013** [comment]
I ran the installation again. It completed this time around, however, the services are unable to start.
Below is the message i get:-

root@ec2-52-210-174-97:/home/ubuntu# service --status-all | grep '\[ ? \]'
 [ ? ]  alaveteli
 [ ? ]  alaveteli-alert-tracks
 [ ? ]  alaveteli-send-notifications

**Comment by mfabunmi2013** [comment]
It tried to run the installation script again. Below is the message i get:-

******************************************************************************************************************
sudo sh ./install-site.sh --default alaveteli alavet                                                                                        eli
==== Installing alaveteli
Updating package lists... done
Installing some core packages...
  apt-utils... done
  git... done
  locales... done
  lockfile-progs... done
  curl... done
  dnsutils... done
  lsb-release... done
Testing for being on EC2... done
Generating locales...
Generating locale en_GB... already done
done
Adding unix user... already done
Updating APT sources... done
Cloning or updating repository... updating... done
Updating mySociety APT source... OK
done
Hit:1 http://eu-west-1.ec2.archive.ubuntu.com/ubuntu xenial InRelease
Hit:2 http://eu-west-1.ec2.archive.ubuntu.com/ubuntu xenial-updates InRelease
Hit:3 http://eu-west-1.ec2.archive.ubuntu.com/ubuntu xenial-backports InRelease
Ign:4 http://debian.mysociety.org stretch InRelease
Hit:5 http://debian.mysociety.org stretch Release
Hit:6 http://security.ubuntu.com/ubuntu xenial-security InRelease
Reading package lists... Done
Setting hostname...
Installing nginx... done
Adding site to nginx... done
Your branch is up-to-date with 'origin/master'.
Installing postfix... done
/var/log/mail/mail.log {
[ ok ] Restarting rsyslog (via systemctl): rsyslog.service.
postfix: Postfix is running with backwards-compatible default settings
postfix: See http://www.postfix.org/COMPATIBILITY_README.html for details
postfix: To disable backwards compatibility use "postconf compatibility_level=2"                                                                                         and "postfix reload"
postfix/postfix-script: refreshing the Postfix mail system
Installing packages from repository packages file...
  done
createuser: creation of new role failed: ERROR:  role "alaveteli" already exists
Checking for postgres template_utf8 database... done
+ '[' 4 -ne 4 ']'
+ UNIX_USER=alaveteli
+ HOST=ec2-52-210-174-97.eu-west-1.compute.amazonaws.com
+ DIRECTORY=/var/www/alaveteli
+ RUBY_VERSION=
+ DB_NAME=alaveteli
++ dig +short ec2-52-210-174-97.eu-west-1.compute.amazonaws.com
+ IP_ADDRESS_FOR_HOST=172.31.17.57
+ '[' x = x172.31.17.57 ']'
+ id alaveteli
++ whoami
+ '[' alaveteli '!=' alaveteli ']'
+ REPOSITORY=/var/www/alaveteli/alaveteli
+ LINK_DESTINATION=/home/alaveteli/alaveteli
+ ln -sfn /var/www/alaveteli/alaveteli /home/alaveteli/alaveteli
+ cd /var/www/alaveteli/alaveteli
+ BASHRC=/home/alaveteli/.bashrc
+ BASHRC_GEM_COMMENT='Set up local gem directory for Alaveteli'
+ BASHRC_START='# START Set up local gem directory for Alaveteli'
+ BASHRC_END='# END Set up local gem directory for Alaveteli'
+ sed -ibackup '/# START Set up local gem directory for Alaveteli/,/# END Set up                                                                                         local gem directory for Alaveteli/d' /home/alaveteli/.bashrc
++ mktemp /home/alaveteli/.bashrc.XXXXXXX
+ TMP_BASHRC=/home/alaveteli/.bashrc.xsa4l31
+ cat
+ cat /home/alaveteli/.bashrc
+ mv /home/alaveteli/.bashrc.xsa4l31 /home/alaveteli/.bashrc
+ source /home/alaveteli/.bashrc
++ export PATH=/home/alaveteli/.gem/ruby//bin:/home/alaveteli/bin:/home/alavetel                                                                                        i/.local/bin:/home/alaveteli/.gem/ruby//bin:/usr/local/sbin:/usr/local/bin:/usr/                                                                                        sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
++ PATH=/home/alaveteli/.gem/ruby//bin:/home/alaveteli/bin:/home/alaveteli/.loca                                                                                        l/bin:/home/alaveteli/.gem/ruby//bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/u                                                                                        sr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
++ case $- in
++ return
+ echo 'gem: --no-ri --no-rdoc'
++ random_alphanumerics 32
++ head -c32
++ tr -dc A-Za-z0-9
+ RANDOM_EMAIL_SECRET=nNpL5cstj0HIF2dIGwssPEQyOwZ7RYTv
++ random_alphanumerics 10
++ head -c10
++ tr -dc A-Za-z0-9
+ RANDOM_EMERGENCY_PASSWORD=nl57rqYBU9
++ random_alphanumerics 100
++ head -c100
++ tr -dc A-Za-z0-9
+ RANDOM_COOKIE_SECRET=UdLUV7LKzsR1M5UQdCk6YZEgrN9WtfJQGl2rMhqO8fDLn37tJdbwwG1Bq                                                                                        cHDlzR2v3WOdnB9aMjtBTakvmUP7P1DtRt20sxHCsoF
+ '[' -f config/general.yml ']'
+ sed -r -e 's,^( *database: *)foi_(.*),\1alaveteli_\2,' -e 's,^( *username: *).                                                                                        *,\1alaveteli,' -e 's,^( *password: *).*,\1null,' -e 's,^( *host: *).*,\1/var/ru                                                                                        n/postgresql/,' -e 's,# constraint_disabling: false,  constraint_disabling: fals                                                                                        e,' config/database.yml-example
+ for SUFFIX in production test development
+ REAL_DB_NAME=alaveteli_production
+ echo Creating the database alaveteli_production
Creating the database alaveteli_production
+ egrep '^ *alaveteli_production *\|'
+ psql -l
+ for SUFFIX in production test development
+ REAL_DB_NAME=alaveteli_test
+ echo Creating the database alaveteli_test
Creating the database alaveteli_test
+ egrep '^ *alaveteli_test *\|'
+ psql -l
+ for SUFFIX in production test development
+ REAL_DB_NAME=alaveteli_development
+ echo Creating the database alaveteli_development
Creating the database alaveteli_development
+ egrep '^ *alaveteli_development *\|'
+ psql -l
+ echo Running rails-post-deploy
Running rails-post-deploy
+ script/rails-post-deploy
Running bundle install with options: --path /home/alaveteli/bundle/
Resolving dependencies...
Using rake 13.0.1
Using concurrent-ruby 1.1.6
Using minitest 5.14.1
Using thread_safe 0.3.6
Using builder 3.2.4
Using erubi 1.9.0
Using mini_portile2 2.4.0
Using crass 1.0.6
Using rack 2.2.3
Using nio4r 2.5.2
Using websocket-extensions 0.1.5
Using mime-types 2.99.3
Using public_suffix 4.0.5
Using arel 9.0.0
Using mimemagic 0.3.5
Using flipper 0.17.2
Using bundler 1.11.2
Using method_source 0.9.2
Using thor 1.0.1
Using ast 2.4.1
Using bcrypt 3.1.13
Using bindex 0.7.0
Using sass 3.4.25
Using uniform_notifier 1.13.0
Using byebug 11.0.1
Using cancancan 3.1.0
Using highline 2.0.0
Using net-ssh 2.9.4
Using mini_mime 1.0.2
Using regexp_parser 1.7.1
Using charlock_holmes 0.7.7
Using coderay 1.1.2
Using json 2.3.1
Using docile 1.3.2
Using simplecov-html 0.10.2
Using sync 0.5.0
Using safe_yaml 1.0.5
Using daemons 1.3.1
Using dalli 2.7.10
Using dante 0.2.0
Using diff-lcs 1.4.2
Using dynamic_form 1.1.4
Using eventmachine 1.2.7
Using execjs 2.7.0
Using fast_gettext 2.0.2
Using ffi 1.13.1
Using gender_detector 2.0.0
Using locale 2.1.3
Using text 1.3.1
Using gnuplot 2.6.2
Using hashdiff 1.0.1
Using hodel_3000_compliant_logger 0.1.1
Using holidays 7.1.0
Using htmlentities 4.3.4
Using ice_cube 0.16.3
Using iso_country_codes 0.7.8
Using jaro_winkler 1.5.4
Using libv8 3.16.14.19
Using rb-fsevent 0.10.4
Using mahoro 0.5
Using maxmind-db 1.0.0
Using mini_magick 4.10.1
Using multi_json 1.13.1
Using open4 1.3.4
Using parallel 1.19.2
Using pg 1.2.3
Using rainbow 3.0.0
Using ref 2.0.0
Using rexml 3.2.4
Using rolify 5.3.0
Using rspec-support 3.9.3
Using ruby-progressbar 1.10.1
Using unicode-display_width 1.7.0
Using ruby-ole 1.2.12.1
Using vpim 13.11.11
Using rubyzip 1.3.0
Using tilt 2.0.8
Using secure_headers 6.3.1
Using statistics2 0.54
Using stripe 5.22.0
Using syslog_protocol 0.9.2
Using unicode 0.4.4.4
Using unidecoder 1.1.2
Using will_paginate 3.3.0
Using xapian-full-alaveteli 1.4.11.1
Using xml-simple 1.1.5
Using zip_tricks 5.3.1
Using i18n 1.8.3
Using tzinfo 1.2.7
Using nokogiri 1.10.10
Using rack-test 1.1.0
Using sprockets 3.7.2
Using request_store 1.4.1
Using rack-ssl 1.4.1
Using rack-utf8_sanitizer 1.7.0
Using websocket-driver 0.7.2
Using mail 2.6.6
Using addressable 2.7.0
Using marcel 0.3.3
Using parser 2.7.1.4
Using bootstrap-sass 2.3.2.2
Using net-scp 1.2.1
Using net-sftp 2.1.2
Using net-ssh-gateway 1.3.0
Using pry 0.12.2
Using recaptcha 5.5.0
Using simplecov 0.16.1
Using tins 1.25.0
Using crack 0.4.3
Using thin 1.7.2
Using uglifier 4.2.0
Using gettext_i18n_rails 1.8.1
Using rb-inotify 0.10.1
Using gettext 3.2.9
Using icalendar 2.5.3
Using therubyracer 0.12.3
Using rspec-mocks 3.9.1
Using rspec-core 3.9.2
Using rspec-expectations 3.9.2
Using ruby-msg 1.5.2 from https://github.com/mysociety/ruby-msg.git (at ascii-en                                                                                        coding@fae72e5)
Using stripe-ruby-mock 3.0.1 from https://github.com/stripe-ruby-mock/stripe-rub                                                                                        y-mock (at 2c925fd@2c925fd)
Using money 6.13.8
Using activesupport 5.2.4.3
Using loofah 2.6.0
Using xpath 3.2.0
Using rotp 5.0.0
Using launchy 2.4.3
Using rubocop 0.81.0
Using capistrano 2.15.9
Using pry-byebug 3.7.0
Using term-ansicolor 1.7.1
Using webmock 3.8.3
Using listen 3.2.1
Using rails-dom-testing 2.0.3
Using globalid 0.4.2
Using activemodel 5.2.4.3
Using bullet 6.1.0
Using factory_bot 5.2.0
Using rails-html-sanitizer 1.3.0
Using capybara 3.15.1
Using rubocop-performance 1.5.2
Using rubocop-rails 2.5.2
Using coveralls 0.8.23
Using activejob 5.2.4.3
Using active_model_otp 2.0.1
Using activerecord 5.2.4.3
Using rspec-activemodel-mocks 1.1.0
Using strip_attributes 1.11.0 from https://github.com/mysociety/strip_attributes                                                                                        .git (at globalize3-rails5.2@62a5e1e)
Using actionview 5.2.4.3
Using acts_as_versioned 0.6.0 from https://github.com/technoweenie/acts_as_versi                                                                                        oned.git (at 63b1fc8@63b1fc8)
Using flipper-active_record 0.17.2
Using annotate 3.1.0
Using globalize 5.2.0
Using oink 0.10.1
Using actionpack 5.2.4.3
Using actioncable 5.2.4.3
Using actionmailer 5.2.4.3
Using activestorage 5.2.4.3
Using railties 5.2.4.3
Using sprockets-rails 3.2.1
Using rails-controller-testing 1.0.5
Using routing-filter 0.6.3
Using exception_notification 4.4.3
Using factory_bot_rails 5.2.0
Using fancybox-rails 0.3.1
Using jquery-rails 4.4.0
Using jquery-ui-rails 6.0.1
Using rails-i18n 5.1.3
Using rspec-rails 4.0.1
Using web-console 3.7.0
Using rails 5.2.4.3
Using sass-rails 5.0.7
Using alaveteli_features 0.0.1 from source at `gems/alaveteli_features`
Bundle complete! 83 Gemfile dependencies, 173 gems now installed.
Bundled gems are installed into /home/alaveteli/bundle.
Installing theme alavetelitheme from git://github.com/mysociety/alavetelitheme.g                                                                                        it
Running uninstall hook in /var/www/alaveteli/alaveteli/lib/themes/alavetelitheme
9280b9493a83ca1cbc2b3eb1317e0f06c4e16273
Checking out origin/develop
HEAD is now at 9280b94... Merge branch 'master' into develop
Running install hook in /var/www/alaveteli/alaveteli/lib/themes/alavetelitheme
Running post_install hook in /var/www/alaveteli/alaveteli/lib/themes/alavetelith                                                                                        eme
alavetelitheme successfully installed in: /var/www/alaveteli/alaveteli/lib/theme                                                                                        s/alavetelitheme

Can't download the latest MaxMind geoip data file. Please add MAXMIND_LICENSE_KE                                                                                        Y setting to config/general.yml
+ LOADED_INDICATOR=/home/alaveteli/.alaveteli-sample-data-loaded
+ '[' '!' -f /home/alaveteli/.alaveteli-sample-data-loaded ']'
ALTER ROLE
Creating /etc/cron.d/alaveteli... done
Creating /etc/init.d/alaveteli... done
Clearing any existing daemons
Removing /etc/init.d/alaveteli-alert-tracks... done
Removing /etc/init.d/alaveteli-send-notifications... done
Removing /etc/init.d/alaveteli-poll-for-incoming... done
Creating daemons for active daemons
Creating /etc/init.d/alaveteli-alert-tracks... alaveteli-alert-tracks.service is                                                                                         not a native service, redirecting to systemd-sysv-install
Executing /lib/systemd/systemd-sysv-install enable alaveteli-alert-tracks
done
Creating /etc/init.d/alaveteli-send-notifications... alaveteli-send-notification                                                                                        s.service is not a native service, redirecting to systemd-sysv-install
Executing /lib/systemd/systemd-sysv-install enable alaveteli-send-notifications
done
Installation complete

ubuntu@ec2-52-210-174-97:~$
******************************************************************************************************************

**Comment by mfabunmi2013** [comment]
Below are the version details:-
root@ec2-52-210-174-97:/home/ubuntu# cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
root@ec2-52-210-174-97:/home/ubuntu#

**Comment by garethrees** [comment]
The [alaveteli-dev mailing list](https://groups.google.com/u/1/g/alaveteli-dev/c/An6DheNTZvo) is a better place for this, unless there's a specific problem with the codebase that can't be resolved there.

Ubuntu 16.04 is not supported (#4970) – 18.04 is the currently supported Ubuntu.

**Comment by mfabunmi2013** [comment]
Thanks Gareth, i shall redirect any issues to the mailing list, going
forward.


Cheers,
Michael
