### ISSUE TITLE
Issues installing xapian-full-alaveteli

### ISSUE THREAD

**Issue by 1000camels** [mysociety/alaveteli#5840]
Is it possible to use xapian-ruby instead of xapian-full-alaveteli? According to this site, xapian-ruby is a better choice: https://trac.xapian.org/wiki/FAQ/RubyWrappers

xapian-full-alaveteli isn't compiling with the following error:

/root/.rbenv/versions/2.7.1/include/ruby-2.7.0/ruby/backward/cxxanyargs.hpp:198:1: note: declared here
 rb_rescue(type *q, VALUE w, type *e, VALUE r)
 ^~~~~~~~~
Makefile:773: recipe for target 'xapian_wrap.lo' failed
make[3]: *** [xapian_wrap.lo] Error 1
make[3]: Leaving directory '/root/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/xapian-full-alaveteli-1.4.11.1/xapian-bindings-1.4.11/ruby'
Makefile:675: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/root/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/xapian-full-alaveteli-1.4.11.1/xapian-bindings-1.4.11/ruby'
Makefile:521: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/xapian-full-alaveteli-1.4.11.1/xapian-bindings-1.4.11'
Makefile:443: recipe for target 'all' failed
make: *** [all] Error 2
rake aborted!

In general, I am having issues using Capistrano, so I can upgrade my installation and better manage it.

**Comment by gbp** [comment]
We don't support [Ruby 2.7](https://github.com/mysociety/alaveteli/issues/5440) we're limited by both Rails and Xapian. I would suggest trying Ruby 2.6.6 which is what we use to run for WDTK in the UK. 

For Capistrano issues, the best place to discuss would be on the [alaveteli-dev](https://groups.google.com/forum/#!forum/alaveteli-dev) group.
