### ISSUE TITLE
Allow pro admins to always extend embargoes

### ISSUE THREAD

**Issue by gbp** [mysociety/alaveteli#5889]
We've had a user support case requesting an embargo be extended. In the console I needed to run:

```ruby
User.find_by(...).info_requests.
  select { |r| r.embargo&.publish_at == Date.new(...) }.
  each { |r| e = r.embargo; e.extend(e.embargo_extensions.create(extension_duration: '6_months')) }
```

This could be improved:

- [ ] Pro admins should be allowed to extend embargos when viewing a request page
- [ ] `AlaveteliPro::Embargo#extend` could be called as an after commit callback when the `AlaveteliPro::EmbargoExtension` is saved.

**Comment by garethrees** [comment]
To do this manually for a batch:

```ruby
batch = InfoRequestBatch.find(BATCH_ID)
batch.update!(embargo_duration: '12_months')

batch.info_requests.find_each do |info_request|
  info_request.create_embargo!(embargo_duration: batch.embargo_duration)
end
```

**Comment by garethrees** [comment]
This is desirable, but unlikely to be worked on in the next 12 months so closing for now.
