### ISSUE TITLE
PDF attachment corruption regression

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#5905]
We recently had a report of a [corrupted/malformed PDF attachment](https://www.whatdotheyknow.com/request/aerial_mages_of_regent_street_ar#incoming-1625595).

Looks like this is a regression. I imported the raw email locally and get different attachment results between 0.37 and `develop`:

```ruby
# develop
attachment_attributes = MailHandler.get_attachment_attributes(RawEmail.last.mail!)
attachment_attributes.size
# => 1

# 0.37.1.4
attachment_attributes = MailHandler.get_attachment_attributes(RawEmail.last.mail!)
attachment_attributes.size
# => 2
```

**Comment by garethrees** [comment]
```sh
#!/bin/bash
bundle --quiet
bundle exec rails runner "exit 1 unless MailHandler.get_attachment_attributes(RawEmail.last.mail!).size == 2"
```

```
git bisect start
git bisect good 40306b3726c81c134207393d67b940267e493cb2 # 0.37.1.4
git bisect bad 1506c45c3 # very recent commit
git bisect run tmp/5905-bisect

# snip…

c581d83285e9093a8cd08e1e0a8901acc495eefb is the first bad commit
commit c581d83285e9093a8cd08e1e0a8901acc495eefb
Author: Graeme Porteous <graeme@rgbp.co.uk>
Date:   Wed Jul 22 11:46:52 2020 +0100

    Bump mail gem to 2.7.1

    Already bumped for the next Rails Gemfile so this is just for 5.2.

:100644 100644 de8a68dcdb3b525668ad3a7af88a8e2982501700 937859904bc66b17b6f909098fa3139e0a7419d2 M      Gemfile
:100644 100644 4dd6237626b3560e63b8d0c04d14c3d01b4bff4c 46b724b0206556176d4a19718e7f97d2c282fd64 M      Gemfile.lock
bisect run success
```

Doesn't surprise me that this is caused by https://github.com/mysociety/alaveteli/commit/c581d83285e9093a8cd08e1e0a8901acc495eefb, but _why_ is unclear.

**Comment by garethrees** [comment]
Definitely caused by a change in Mail:

```ruby
[3](main)> Mail::VERSION.version
# => "2.6.6"
[4](main)> Mail.read('1625443.eml').parts.map(&:content_type)
# => ["text/plain; charset=utf-8; format=flowed", "application/pdf; name=\"20200819 - Aerial Images.pdf\""]


[3](main)> Mail::VERSION.version
# => "2.7.1"
[4](main)> Mail.read('1625443.eml').parts.map(&:content_type)
# => []
```

Need to establish whether it's a regression or whether we're doing the wrong thing with it.

**Comment by garethrees** [comment]
```
git checkout 21222e1b48f08f6f848d26643d6b6fb1d873d18c
```

## Before Diff

```ruby
[1](main)> require 'bundler/setup'
NOTE: Gem::Specification#has_rdoc= is deprecated with no replacement. It will be removed on or after 2018-12-01.
Gem::Specification#has_rdoc= called from /vagrant/mail.gemspec:13.
=> true
[2](main)> require './lib/mail'
=> true
[3](main)> Mail.read('1625443.eml').parts.map(&:content_type)
WARNING: More than 1000 header fields; only using the first 1000 and ignoring the rest
WARNING: Ignoring unparsable header "From clerk@moultonpc.org.uk Thu Aug 20 16:18:14 2020": invalid header name syntax: "From clerk@moultonpc.org.uk Thu Aug 20 16"
=> []
```

## Apply Diff

```diff
diff --git a/lib/mail/attachments_list.rb b/lib/mail/attachments_list.rb
index ca7d0d6a..5f5ac2fb 100644
--- a/lib/mail/attachments_list.rb
+++ b/lib/mail/attachments_list.rb
@@ -7,7 +7,7 @@ module Mail
       @content_disposition_type = 'attachment'
       parts_list.map { |p|
         if p.mime_type == 'message/rfc822'
-          Mail.new(p.body.encoded).attachments
+          Mail.new(p.body).attachments
         elsif p.parts.empty?
           p if p.attachment?
         else
diff --git a/lib/mail/encodings/quoted_printable.rb b/lib/mail/encodings/quoted_printable.rb
index 6a78ffc3..6c0438a5 100644
--- a/lib/mail/encodings/quoted_printable.rb
+++ b/lib/mail/encodings/quoted_printable.rb
@@ -16,11 +16,11 @@ module Mail
       # Decode the string from Quoted-Printable. Cope with hard line breaks
       # that were incorrectly encoded as hex instead of literal CRLF.
       def self.decode(str)
-        str.gsub(/(?:=0D=0A|=0D|=0A)\r\n/, "\r\n").unpack("M*").first
+        ::Mail::Utilities.to_lf str.gsub(/(?:=0D=0A|=0D|=0A)\r\n/, "\r\n").unpack("M*").first
       end

       def self.encode(str)
-        [str].pack("M")
+        ::Mail::Utilities.to_crlf([::Mail::Utilities.to_lf(str)].pack("M"))
       end

       def self.cost(str)
diff --git a/lib/mail/message.rb b/lib/mail/message.rb
index 4398885e..32d67b11 100644
--- a/lib/mail/message.rb
+++ b/lib/mail/message.rb
@@ -2012,7 +2012,7 @@ module Mail

     def raw_source=(value)
       value = value.dup.force_encoding(Encoding::BINARY) if RUBY_VERSION >= "1.9.1"
-      @raw_source = value
+      @raw_source = ::Mail::Utilities.to_crlf(value)
     end

     # see comments to body=. We take data and process it lazily
```

## After diff

```ruby
[1](main)> require 'bundler/setup'
NOTE: Gem::Specification#has_rdoc= is deprecated with no replacement. It will be removed on or after 2018-12-01.
Gem::Specification#has_rdoc= called from /vagrant/mail.gemspec:13.
=> true
[2](main)> require './lib/mail'
=> true
[3](main)> Mail.read('1625443.eml').parts.map(&:content_type)
=> ["text/plain; charset=utf-8; format=flowed", "application/pdf; name=\"20200819 - Aerial Images.pdf\""]
```

**Comment by garethrees** [comment]
Pretty sure 21222e1b48f08f6f848d26643d6b6fb1d873d18c is causing the problem.

**Comment by garethrees** [comment]
Applying only this hunk of the diff results in the attachments being returned correctly:

```diff
diff --git a/lib/mail/message.rb b/lib/mail/message.rb
index 4398885e..32d67b11 100644
--- a/lib/mail/message.rb
+++ b/lib/mail/message.rb
@@ -2012,7 +2012,7 @@ module Mail

     def raw_source=(value)
       value = value.dup.force_encoding(Encoding::BINARY) if RUBY_VERSION >= "1.9.1"
-      @raw_source = value
+      @raw_source = ::Mail::Utilities.to_crlf(value)
     end

     # see comments to body=. We take data and process it lazily
```

```ruby
[5](main)> Mail.read('1625443.eml').parts.map(&:content_type)
# => ["text/plain; charset=utf-8; format=flowed", "application/pdf; name=\"20200819 - Aerial Images.pdf\""]
```

**Comment by garethrees** [comment]
Another case https://www.whatdotheyknow.com/request/adult_social_care_financial_asse

**Comment by sagepe** [comment]
Possibly related: https://github.com/mikel/mail/issues/1329?

**Comment by garethrees** [comment]
> Possibly related: [mikel/mail#1329](https://github.com/mikel/mail/issues/1329)?

Well, our [failing email](https://www.whatdotheyknow.com/admin/raw_emails/1639309) doesn't have a `Content-Location` header, but then neither does [this successfully parsed](https://www.whatdotheyknow.com/admin/raw_emails/1657080) email.

> I've noticed that the Mail::Body#extract_parts method requires CRLF line endings, and sometimes we seem to receive mail with only LF endings.

This could be worth verifying for the failing and successful examples.

> https://github.com/mikel/mail/pull/1350 – Handle edge case when inline image attachment part is missing a filename

Are our failing attachments inline and missing a filename? The PR seems to specifically target images, so we might need to do something different for the PDF cases we're seeing fail.

**Comment by RichardTaylor** [comment]
Another case https://www.whatdotheyknow.com/request/education_team_structure_8

**Comment by gbp** [comment]
Inspired by https://github.com/rails/rails/blob/master/actionmailbox/lib/action_mailbox/mail_ext/from_source.rb#L5

If we do: 

```diff
diff --git a/lib/mail_handler/backends/mail_backend.rb b/lib/mail_handler/backends/mail_backend.rb
index e8de3ffa9c..970ba1efd4 100644
--- a/lib/mail_handler/backends/mail_backend.rb
+++ b/lib/mail_handler/backends/mail_backend.rb
@@ -43,7 +43,7 @@ def backend
 
       def mail_from_raw_email(data)
         data = data.force_encoding(Encoding::BINARY) if data.is_a? String
-        Mail.new(data)
+        Mail.new Mail::Utilities.binary_unsafe_to_crlf(data)
       end
 
       # Extracts all attachments from the given TNEF file as a Mail object
```

and then: 

```
[1] pry(main)> cd IncomingMessage.last
[2] pry(#<IncomingMessage>):1)> get_main_body_text_folded
=> "This is a multi-part message in MIME format..."
[3] pry(#<IncomingMessage>):1> parse_raw_email!(true)
[4] pry(#<IncomingMessage>):1> clear_in_database_caches!
[5] pry(#<IncomingMessage>):1> get_main_body_text_folded
=> "Dear ..."
```

**Comment by gbp** [comment]
This is basically waht we already do in our specs as editors automattically convert CRLF into LF.

**Comment by RichardTaylor** [comment]
Another example 

https://www.whatdotheyknow.com/request/policies_329#incoming-1665717

Getting this fix up on WhatDoTheyKnow will prevent requests to extract and upload documents from reformatted responses.

**Comment by RichardTaylor** [comment]
Will the fix have a retrospective effect on messages that have already come in?

**Comment by gbp** [comment]
> Will the fix have a retrospective effect on messages that have already come in?

It won't fix them automatically but I'm intenteding to run some commands in the app console to fix

**Comment by RichardTaylor** [comment]
Possibly another case:

https://www.whatdotheyknow.com/request/professional_services_procuremen_316#incoming-1667331

**Comment by RichardTaylor** [comment]
Possibly related issue, a further message on the thread[ mentioned above ](https://github.com/mysociety/alaveteli/issues/5905#issuecomment-719944610)not involving a PDF though:

https://www.whatdotheyknow.com/request/professional_services_procuremen_316#incoming-1670997

**Comment by RichardTaylor** [comment]
Another likely example

https://www.whatdotheyknow.com/request/covid_19_in_sheltered_housing#incoming-1673474

**Comment by garethrees** [comment]
Ha, well this is strange:

```ruby
Mail.read('tmp/1625443.eml').parts.map(&:content_type)
# => []
Mail.new(File.read('tmp/1625443.eml')).parts.map(&:content_type)
# => ["text/plain; charset=utf-8; format=flowed", "application/pdf; name=\"20200819 - Aerial Images.pdf\""]
```

**Comment by gbp** [comment]
```ruby
Mail.read('tmp/1625443.eml').parts.map(&:content_type)
# => []
```
is equvailent to
```ruby
data = File.open('tmp/1625443.eml', 'rb') { |f| f.read }
Mail.open(data).parts.map(&:content_type)
# => []
```
and what we have in `MailHandler::Backends::MailBackend`
```ruby
data = File.read('tmp/1625443.eml').force_encoding(Encoding::BINARY)
Mail.open(data).parts.map(&:content_type)
# => []
```

All are fixed with the proposed CRLF change:
```ruby
data = File.read('tmp/1625443.eml').force_encoding(Encoding::BINARY)
data = Mail::Utilities.binary_unsafe_to_crlf(data.to_s)
Mail.open(data).parts.map(&:content_type)
# => ["text/plain; charset=utf-8; format=flowed", "application/pdf; name=\"20200819 - Aerial Images.pdf\""]
```

**Comment by RichardTaylor** [comment]
Further suspected example:

https://www.whatdotheyknow.com/request/agency_staff_management_and_spen#incoming-1673828

**Comment by RichardTaylor** [comment]
Further suspected example:

https://www.whatdotheyknow.com/request/use_of_agency_social_workers_894#incoming-1636554

**Comment by mdeuk** [comment]
We've another instance of this issue at:
https://www.whatdotheyknow.com/request/secure_email_contracts_7#incoming-1678252

**Comment by RichardTaylor** [comment]
Apparent further case:
https://www.whatdotheyknow.com/request/investments_and_divestment_progr_2#incoming-1672202

Once fixed it would be good to try and identify as many cases as possible systematically.

**Comment by RichardTaylor** [comment]
Possible other example, not clear if this is the same issue or not:

https://www.whatdotheyknow.com/request/ipc_grants_11#incoming-1680749

**Comment by mdeuk** [comment]
A further two examples in today's monitoring:

https://www.whatdotheyknow.com/request/social_services_qualified_and_un?nocache=incoming-1682090#incoming-1682090

https://www.whatdotheyknow.com/request/per_capita_bin_allocation_and_re?nocache=incoming-1660943#incoming-1660943

**Comment by RichardTaylor** [comment]
Another case

https://www.whatdotheyknow.com/request/intelligent_automated_systems_in_7#incoming-1683750

**Comment by garethrees** [comment]
Just to note that we do have a probable fix for this (https://github.com/mysociety/alaveteli/pull/5936). The hold up at the moment is that I wanted to add a test that demonstrates the problem (https://github.com/mysociety/alaveteli/pull/5970) and that the new code fixes it. I also want to make sure we really understand what's causing the problem we're seeing here, as I'm reluctant to push a fix when it may may turn out to cause other problems somewhere else because we've jumped to conclusions.

**Comment by RichardTaylor** [comment]
Three further likely cases:

https://www.whatdotheyknow.com/request/management_of_physical_documents_21?nocache=incoming-1684069#incoming-1684069

https://www.whatdotheyknow.com/request/professional_services_procuremen_316?nocache=incoming-1671852#incoming-1671852

https://www.whatdotheyknow.com/request/supply_spend_20172022?nocache=incoming-1684055#incoming-1684055

**Comment by garethrees** [comment]
PDF attachment corruption regression

Lets recap.

Since upgrading to Mail 2.7.1 (c581d83) we've noticed a regression in handling some PDFs. Instead of being extracted to an `FoiAttachment`, the base64 encoded string gets rendered into the main part of the correspondence. We've isolated the cause to mikel/mail@21222e1.

```
21222e1b48f08f6f848d26643d6b6fb1d873d18c is the first bad commit
commit 21222e1b48f08f6f848d26643d6b6fb1d873d18c
Author: Jeremy Daer <jeremydaer@gmail.com>
Date:   Mon May 22 10:01:00 2017 -0700

    Eliminate attachment corruption caused by line ending conversions

    * Omit initial CRLF linefeed conversion since CRLF are required newline
      separators. We shouldn't need to convert bare CR or LF. Update our
      fixture emails to use CRLF throughout. Closes #609. Fixes #408.

    * Drop quoted-printable CRLF conversion. This was introduced to
      harmonize with Ruby's \n-based line endings. But this breaks Q-P
      encoding with binary data. It's not *meant* for binary data, but we
      don't yet take adequate measures to use base64 for these cases.
      Reverts #496. Fixes #1010.

    Closes #1113
```

Since the introduction of [Action Mailbox](https://guides.rubyonrails.org/action_mailbox_basics.html) Rails  parses raw emails through Mail through [`Mail::Utilities.binary_unsafe_to_crlf`](https://github.com/mikel/mail/blob/2.7.1/lib/mail/utilities.rb#L268-L270). This appears to have been introduced in 627bbd34 with no specific explanation for the use of the helper.

[This (fixed) issue](https://www.redmine.org/issues/31549) in Redmine appears to describe a similar problem. There are some notes suggesting that for some users the `LANG` environment variable, or Postfix configuration, could be causing the issue.

I've downloaded a `RawEmail` from WhatDoTheyKnow where the problem was exhibited, anonymised it and created a spec (d325c8b) that demonstrates the problem. We can see that when the fixture has unix line endings, with the current code the spec fails in the same way the production code fails. Parsing the raw email through `Mail::Utilities.binary_unsafe_to_crlf` as Rails does (1dfb71f) makes the spec pass.

I don't fully understand whether we're doing the right thing at the infrastructure level at the moment. Are we applying any line-ending conversions during the Exim pipe process? What _should_ we be expecting the application to ingest, and is that what's happening?

If we're confident that we're not mangling the email before entry into the app, then I'd like to understand what it is about these emails is "wrong". Is it that they don't follow the RFC, but are generated in this way due to a poor email client, or is it that there's an upstream issue in Mail that we should consider raising?

It feels like 1dfb71f is _probably_ the right thing to do. If we were building Alaveteli from scratch today we'd likely use Action Mailbox, and therefore go through `Mail::Utilities.binary_unsafe_to_crlf`.

I want to be sure that:

1. By applying 1dfb71f we're not going to cause some _other_ bug because we don't really understand what's happening.
2. We're not patching over something that we've got wrong lower down the stack in Exim or on the OS.

**Comment by sagepe** [comment]
Regarding Exim: I don't think we're doing anything out of the ordinary on our infra at present. The emails are received and forwarded on without explicitly changing formats.

There's [a description in the Exim docs](https://www.exim.org/exim-html-current/doc/html/spec_html/ch-message_processing.html#SECTlineendings) covering how line endings are handled during mail processing.

There is an option to force CRLF when using [a pipe transport](https://www.exim.org/exim-html-current/doc/html/spec_html/ch-the_pipe_transport.html) rather than just LF. I'm not sure this is the right thing to do however; some attachments must be coming through correctly and the default is *not* to do this, so I'd want to understand why it was necessary before turning it on.

It's also worth noting that we can't predict necessarily how a given Alaveteli's environment may be configured; it seems sensible to me to have an internal step like the one you mention above using `Mail::Utilities.binary_unsafe_to_crlf` to ensure mail is subsequently processed correctly - we could tweak the email configuration used on WDTK infrastructure, but that might not help a re-user who may have less control over the format of their mail.

**Comment by dracos** [comment]
What happens then is due to the presence of non-ASCII characters somewhere in the raw email text.

1. lib/mail/message.rb calls Mail::Body.new(@body_raw)
2. Body initialize does @raw_source = ::Mail::Utilities.to_crlf(string.to_s)
3. to_crlf only calls binary_unsafe_to_crlf if safe_for_line_ending_conversion? which is (if ruby<1.9) if string is ASCII only, or (ruby>=1.9) if string is valid encoding or (BINARY+ASCII only)
4. the string is BINARY (fair enough, as encoding isn't known until headers are processed).

The part splitter uses a regexp(?!) which only spots \r\n, and thus will fail on any LF-ended non-ASCII email only. If the email is ASCII only, line endings are being converted back to CRLF and it works fine. I agree, unilaterally forcing a conversion to crlf, given the mail code expects CRLF and isn't always doing it, is the right thing to do.

**Comment by RichardTaylor** [comment]
Further likely example 

https://www.whatdotheyknow.com/request/supply_spend_20172022#incoming-1684055

**Comment by RichardTaylor** [comment]
Further likely cases

https://www.whatdotheyknow.com/request/professional_services_procuremen_70?nocache=incoming-1686240#incoming-1686240

and 

https://www.whatdotheyknow.com/request/it_detail_request_36#incoming-1686205

**Comment by garethrees** [comment]
I've now run the task in 7ae31c5 and all of the above messages are correctly parsed.

> Possible other example, not clear if this is the same issue or not:
>
> https://www.whatdotheyknow.com/request/ipc_grants_11#incoming-1680749

This one hasn't changed, so I expect a different, edge-case issue.

**Comment by mdeuk** [comment]
> I've now run the task in [7ae31c5](https://github.com/mysociety/alaveteli/commit/7ae31c5532480e17dbfb2e81ae1dab79fccca888) and all of the above messages are correctly parsed.
> 
> > Possible other example, not clear if this is the same issue or not:
> > https://www.whatdotheyknow.com/request/ipc_grants_11#incoming-1680749
> 
> This one hasn't changed, so I expect a different, edge-case issue.

I think this specific one is the message itself, rather than an Alaveteli (or upstream) bug.

The raw message doesn't render correctly in an email client either, and the source suggests that it was munged before it arrived. 
<img width="1073" alt="image" src="https://user-images.githubusercontent.com/249418/101636262-fa71e780-3a22-11eb-8107-4df5b6d60fe8.png">
