### ISSUE TITLE
API query syntax documentation

### ISSUE THREAD

**Issue by monty241** [mysociety/alaveteli#5916]
We are in the process of adding an [Invantive SQL](https://documentation.invantive.com/2017R2/invantive-sql-grammar/invantive-sql-grammar-17.30.html) connector on Alaveteli. In that process, we translate SQL into associated API calls.

The [developer API URL](https://alaveteli.org/docs/developers/api/) helped us discover that APIs are probably widely available, but we are struggling to find documentation on the query syntax such as:

`https://www.wob-knop.nl/feed/search/%20(variety:sent%20OR%20variety:followup_sent%20OR%20variety:response%20OR%20variety:comment).json`

Where can the API query syntax documentation be found?

**Comment by garethrees** [comment]
Hi @monty241,

Sounds interesting! The search terms are available on https://www.wob-knop.nl/advancedsearch.

Best place for questions like these is the [`alaveteli-dev`](https://alaveteli.org/community/#project-mailing-lists) mailing list. Please do follow up there if you have any questions, or even just to let us know about progress you make!

Good luck!

**Comment by monty241** [comment]
Hi @garethrees ,

thanks, found the documentation from your link on https://xapian.org/docs/queryparser.html. That should be sufficient.

Rgds
