### ISSUE TITLE
Issue with email rendering for some emails from a specific body

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#5917]
Emails from a particular public body are not being usefully rendered, with undecoded chunks of the message encoding HTML and files being displayed. 

Example:

https://www.whatdotheyknow.com/request/semi_independent_accommodation_f_27#incoming-1651059

Search which shows further examples:

https://www.whatdotheyknow.com/body/cumbria_county_council?utf8=%E2%9C%93&query=MIME+format&request_date_after=&request_date_before=&commit=Search

The email does render as expected if downloaded and opened in Mac Mail so this does appear to be an Alaveteli bug. 

Any advice we could give the authority to work around this issue would be helpful. 

cc @sagepe

**Comment by mdeuk** [comment]
This appears to be a repeat of the issue at #5905.

**Comment by RichardTaylor** [comment]
Yes it's another example of that issue, I'll close this one.
