### ISSUE TITLE
Images corrupted in PDF in response

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#5932]
See:
https://www.whatdotheyknow.com/request/newly_overflown_postcodes_during#incoming-1662245

Images render correctly showing maps if the raw email is opened in another mail application.  

Possible but unconfirmed example of the issue at #239 

Looks different to the issue at #5905 

I recall a similar issue with images on a similar subject before.

**Comment by gbp** [comment]
> Looks different to the issue at #5905

Confirmed - this is a different issue

**Comment by HelenWDTK** [comment]
+1 Had this today https://www.whatdotheyknow.com/request/thames_water_location_of_asbesto#incoming-2590461

**Comment by garethrees** [comment]
This is desirable, but unlikely to be worked on in the next 12 months so closing for now.
