### ISSUE TITLE
can be helped to run on windows

### ISSUE THREAD

**Issue by iy4nl4mp** [mysociety/alaveteli#5934]
I'm a use Windows 8 user, Rails version: 6.0.3.4, can be helped to run

**Comment by garethrees** [comment]
Hi @iy4nl4mp.

We don't support direct installation on Windows. You might be able to use the [Windows Subsystem](https://docs.microsoft.com/en-us/windows/wsl/install-win10) on a later version of Windows, but it's not something we have experience with.

You can use [Vagrant](https://www.vagrantup.com/) with the included [`Vagrantfile`](https://github.com/mysociety/alaveteli/blob/master/Vagrantfile) to create a Linux virtual machine.

Feel free to post your experiences and requests for assistance on the [Alaveteli Developers mailing list](https://alaveteli.org/community/). We're not likely to add support for Windows into the codebase though, so I'm going to close this issue.

Best,

Gareth
