### ISSUE TITLE
Decide what the refusal advice should present when we don't have JavaScript enabled

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#5938]

**Comment by garethrees** [comment]
We're going to assume this will require JS for now.

We're going to render the HTML through rails, with the JS just dealing with interaction.

This means we'll have to do something to hide the advice when JS is disabled

**Comment by garethrees** [comment]
Maybe just render the actions without suggestions?

**Comment by wrightmartin** [comment]
Ok viewing the page without Javascript gives you this...

![image](https://user-images.githubusercontent.com/2292925/119097273-7037a180-ba0c-11eb-9219-44713100d812.png)

There's two approaches

**Build a JS-free version**

This would be a multistage form that works just like the JS driven one but uses traditional GET/POST to receive answers. We could then use JS to enhance this and make it work similar to how it works now. This is a big undertaking and probably a rewrite, however the bulk of the work of this feature, the logic and the content can be reused so not unachievable. We should put this on the roadmap. 

**Remove the questionnaire and adjust the next steps display**

This pretty much what we have now. I'm thinking not showing the advice based on your questions is fine, as arguably an accessible alternative is to read through them and determine what applies based on the advice given. We should fix the `wizard__next-steps` controls to show by default and only hide when JavaScript is available.

**Comment by wrightmartin** [comment]
Actually on reflection this won't be enough as we've got the snippets to deal with too....

I think for now the non-JS version should work as everything did previously for now. We hide the questionnaire and the `wizard__next-steps` links completely from non-JS clients

**Comment by garethrees** [comment]
In https://github.com/mysociety/whatdotheyknow-theme/pull/817 I've added some text which says "use our wizard". We _could_ render that with JS, or, maybe we should just render a box in place of the wizard saying "JavaScript must be enabled, sorry".

**Comment by wrightmartin** [comment]
> "JavaScript must be enabled, sorry".

Never sure about these 'look at what you could have won' messages as it's rare JS is disabled as a choice they can easily revert

**Comment by garethrees** [comment]
Fixed by https://github.com/mysociety/alaveteli/pull/6306 and https://github.com/mysociety/whatdotheyknow-theme/pull/827.
