### ISSUE TITLE
Ability to schedule public body changes on a date in the future

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#5950]
Sometimes we know we need to make a series of public body changes on a date in the future. 

Ideally we'd be able to put these in the system and schedule them in advance. 

In some cases it would be good to get a page up for a new public body in advance of it coming into being, then opening it to requests on the day it comes to life. This might help us get a page in search engine indexes in advance of when people might be searching for a new body. 

Having a URL for a body which is about to come into existence might also help with links between predecessor and successor bodies. 

Changes we might want to schedule

* Adding new bodies
* Marking bodies defunct and updating their notes with a link to a successor body

Such a system might also be used to "draft" an entry for a body which we are expecting to add in the future, but whose addition date we don't yet know. 

See also #4714 (Record and show relationships between bodies)

**Comment by RichardTaylor** [comment]
Real examples:

* Advanced Research and Invention Agency (ARIA) - in the media now, but doesn't yet exist. 
* AWE PLC - expected to become owned by the Government and subject to FOI in the future. 

It would be nice to have pages for such bodies, and to "activate" them on the appropriate date.

**Comment by RichardTaylor** [comment]
In the UK bodies sometimes exist in "shadow" form prior being given statutory powers, this feature could enable adding a listing for a "shadow" body and setting it up to change its name, and notes, on the day it gains statutory powers. 
 
Examples of bodies which came into existence first in shadow form include: Police and Crime Panels, and new councils, eg. Dorset Council was preceded by the [Shadow Dorset Council](https://moderngov.dorsetcouncil.gov.uk/ieListMeetings.aspx?CommitteeId=135
).  

Currently in the UK Integrated Care Boards are emerging in shadow form, [for example in Somerset](https://www.somersetccg.nhs.uk/wp-content/uploads/2020/09/Enc-E-Draft-Terms-of-Reference-for-ICS-Shadow-Board.pdf).

**Comment by garethrees** [comment]
Seems like we could do something similar with `defunct` with a `shadow` tag.

**Comment by RichardTaylor** [comment]
Having another tag which like `defunct` prevents requests to a body might be useful. 

We could then set up a new body but say "you cannot make requests to this body, there may be more information in the notes".  That would be a general approach. 

A more specific approach would be a `prelisted` tag which would prompt text like: "this body is yet to come into existence so you can't make a request to it yet". 


Looking at the examples in this thread we have AWE PLC which exists now, and which we don't want to list yet, but is expected to become subject to FOI, we have ARIA which doesn't exist yet, but we want to list from the point it comes into being, and we have the unusual situation of the shadow bodies. 

In terms of shadow bodies I think we can do what we need with the existing features, there's just a policy question of exactly how to treat them to be addressed. I think listing them as eg. "Shadow Devon Council" then changing the name on the date the body becomes statutory to "Devon Council" would be reasonable. Shadow bodies hold meetings, and might make appointments eg. of chairs, so requests to them might be reasonable.

**Comment by RichardTaylor** [comment]
We now have a category on WhatDoTheyKnow for forthcoming bodies:

https://www.whatdotheyknow.com/body/list/forthcoming

**Comment by HelenWDTK** [comment]
+1 We've recently been contacted by an authority notifying us that they're being abolished on 1 Jan. It would be good to be able to note this in the system, rather than the support inbox.
