### ISSUE TITLE
Documentation should be more realistic about time taken to run a service using Alavetlei 

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#5953]
The documentation section titled: "Maintain the website" at https://alaveteli.org/docs/getting_started/#step-seven-maintain-the-website states:

>You could get by with just one or two hours per week.

While, as I understand it, we don't have a good grasp on how much time it takes to run WhatDoTheyKnow.com and WhatDoTheyKnow.com is a large website and others might be smaller I think this massively understates the amount of work, from people with a range of skills, likely to be required to run a successful service. 

In relation to WhatDoTheyKnow I think the time quoted is at least 50-100 times out. 

Advice from the documentation could impact what those running services seek funding for, so accuracy could improve the chances of a new service being properly resourced and successful.

**Comment by garethrees** [comment]
This would be a great question to put to the [Alaveteli community](https://alaveteli.org/community/). If we can come up with a better number it's a pretty quick change.

**Comment by RichardTaylor** [comment]
[The question was asked on 7 Jun 2019](https://groups.google.com/g/alaveteli-users/c/W_K3o6ifOnA)

The only response was from WhatDoTheyKnow with an estimate of: "at least half a FTE".

**Comment by garethrees** [comment]
Going to close since this covers pretty similar ground to https://github.com/mysociety/alaveteli/issues/2947.
