### ISSUE TITLE
Require sign-in before allowing submission of public body change requests

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#5957]
People are required to sign-up before reporting requests for admin attention, but not before making public body change requests via `/change_request/new/` or `/change_request/new/[public_body_name]`

Requiring sign-in might reduce unintentional and spammy use of the form. 

This is a minor issue but such requests do have to be cancelled / deleted in the system so misuse is annoying and causes a little work for administrators.

**Comment by garethrees** [comment]
The downside of this is increasing friction of genuine use of the form.

1. Do we get many uses of it from non-signed-in users?
2. How much spam do we get?
3. Does 1 outweigh 2?

Might be worth tracking this data for a month or two to get a better idea of the impact?

**Comment by RichardTaylor** [comment]
Other ideas for tackling the same issue:

* Block users based on IP address
* Prevent users with certain email addresses using the report/suggest forms
* Prevent users including certain terms within messages (enabling a ban/block)

I don't think this is a major issue at the moment.

**Comment by garethrees** [comment]
Do we actually want this?

**Comment by WilliamWDTK** [comment]
> Do we actually want this?

It seems to me to be excessive friction…

But there is a small amount of Spam from body change/addition requests etc.

**Comment by garethrees** [comment]
Closing as there hasn't been much demand.
