### ISSUE TITLE
Allow administrators to make it so the initial date of sending is used for deadline calcultions despite a resend

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#5963]
Currently if a request is re-sent the deadline calculations are based on the date of the resending not the date of the initial request. This is fine if the re-send is due to an error message as a result of a bad contact address. 

Sometimes a re-send is done because a public body has lost the original request. In these cases the deadline should not be recalculated. 

Example request on WhatDoTheyKnow: 697615

**Comment by WilliamWDTK** [comment]
In such cases, it could be accomplished by the administration team manually forwarding the request, rather than using the resend feature in Alaveteli.

**Comment by WilliamWDTK** [comment]
This is a duplicate of #1151
