### ISSUE TITLE
Respond to fact users sometimes are unable to click on links in emails

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#5968]
Outgoing emails from the system, such as track and account confirmations, contain the phrase:

>Please click on the link below

It appears this confuses users, particularity possibly those who use hotmail, if their email software doesn't make the links clickable (this is perhaps due to a feature intended to help protect them from nefarious links). 

It appears there may be settings in the users' email systems which could be changed to make such links clickable (but it might not be advisable for them to reduce their protection from bad things).  

Idea to address this:

* Add a statement letting users know they may need to copy and paste the link into their browser address bar. 
* Ensure those running Alaveteli sites have a good reputation with major email providers, consider requesting whitelisting via:
** https://sendersupport.olc.protection.outlook.com/snds/index.aspx
** https://support.microsoft.com/en-us/supportrequestform/8ad563e3-288e-2a61-8122-3ba03d6b8d75 

This appears to affect our less technically competent users, but they are a group of people we want to serve.

**Comment by garethrees** [comment]
I think this is essentially a duplicate of https://github.com/mysociety/alaveteli/issues/4569?

**Comment by RichardTaylor** [comment]
Yes. Closed in favour of #4659 

(I do search for existing tickets. I recall searching for the text "Please click on the link below". )
