### ISSUE TITLE
Warn users when a request is made authority_only

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#5976]
When requests are closed to new responses a note is published:

>This request has been closed to new correspondence from the public body. Contact us if you think it ought be re-opened. 

My understanding / expectation is that this note appears when `Allow new responses from: ` is set to `nobody`.

There is no public / requester indication when  `Allow new responses from: ` is set to `authority_only`.

A requester who has escalated a case to the ICO might want to keep it fully open. 

Ideally users would flag requests as appealed and they'd be kept open to responses. 

I'm concerned we're not supporting appealed requests as well as we should, due to the automatic restrictions on responses to old correspondence threads.

Related:
* https://github.com/mysociety/alaveteli/issues/5946  Delay closure of appealed requests #5946

**Comment by garethrees** [comment]
Linking to https://github.com/mysociety/alaveteli/issues/4524 – we could make it easier for (some?) request owners to revert this if they still want to act on the request.

**Comment by garethrees** [comment]
This would be quite easy to implement (see https://github.com/mysociety/alaveteli/commit/db5805b92d810eaef47a09fdbaa9c9713ad8218e), but the phrasing is a bit trickier!

* It's difficult to describe what "Authority Only" means in this context
* Followups are allowed, so it only affects the body, not the requester
* What's the right word to use in place of closed? "Restricted"? "Reduced"?

Here's a suggestion:

> Automatic anti-spam measures are in place for this older request. Contact us if you are having trouble responding.

Open to others.

**Comment by RichardTaylor** [comment]
How about:

> Automatic anti-spam measures are in place for this older request. Please let us know if a further response is expected or if you are having trouble responding.

"let us know" could be linked to the report this request form.

**Comment by RichardTaylor** [comment]
We've had a public body write to us asking us to re-open an authority_only request, apparently as a result of the note on the thread. The response would probably have got through just fine as they were writing from the authority domain. 

I hope this change doesn't cause more admin work, disproportionate to the issue it resolves. 

We can track cases here.

**Comment by mdeuk** [comment]
> We've had a public body write to us asking us to re-open an authority_only request, apparently as a result of the note on the thread. The response would probably have got through just fine as they were writing from the authority domain.
> 

Are you referring to University of Edinburgh? Their casework system sends out from a subdomain so gets caught on authority_only cases as we match against the domain itself.

**Comment by RichardTaylor** [comment]
>Are you referring to University of Edinburgh? 

Yes. Based on the comment above I appear to have misassumed what the issue was in this case.
