### ISSUE TITLE
Problem rendering specific incoming message

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#5990]
The message at

https://www.whatdotheyknow.com/request/medicine_bm6#incoming-1676851

contains a broken link when displayed.  

Below are snippets from the raw mail with line breaks removed:

Plain text:
```The answer to your question can be found here. [https://www.southampton.ac.=uk/~assets/doc/legal-services/FOI%20requests%20released%20documents/RITM032=7367.pdf" }.]```

HTML

```<p>The answer to your question can be found <a title=3D"here." href=3D"http=s://www.southampton.ac.uk/~assets/doc/legal-services/FOI%20requests%20relea=sed%20documents/RITM0327367.pdf&quot; }.">here.</a></p>```

The problem may be with the incoming email rather than a bug with Alaveteli but I'm not sure, hence the ticket.

**Comment by garethrees** [comment]
Actually, mail parses the link as:

```
https://www.southampton.ac.uk/~assets/doc/legal-services/FOI%20requests%20released%20documents/RITM0327367.pdf%22%20%7D.
```

It has an extra `"%20%7D.` on the end. I think this is more an error in the email itself.
