### ISSUE TITLE
Show request history on followup form

### ISSUE THREAD

**Issue by sebbacon** [mysociety/alaveteli#6]
When following links such as "I'm about to send clarification", a
form appears into which the reply can be typed. However, the
previous correspondence in that thread is not shown.

The solution is something like: 
Make it so when you make followups the whole request is shown on the page.
Remove all show_response URLs, and replace with a special version of the
request URL with a new input box at the bottom and a hash link to it

**Comment by RichardTaylor** [comment]
Just to note a user of WhatDoTheyKnow drew attention to this issue today.

**Comment by garethrees** [comment]
Related to https://github.com/mysociety/alaveteli/issues/4354
