### ISSUE TITLE
Consider how we show progress on the refusal advice interface

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#6007]
A subtask of https://github.com/mysociety/alaveteli/issues/5910

**Comment by garethrees** [comment]
@gbp could you link up the branch where we've extracted the progress bar?

**Comment by gbp** [comment]
Current work in progress is here https://github.com/mysociety/alaveteli/compare/jrct/checklist-ui-progress

**Comment by garethrees** [comment]
I'm going to close this as the current implementation feels pretty decent. Maybe we'll reopen this if we get loads of user support requests.
