### ISSUE TITLE
Upgrade to Rails 6.1

### ISSUE THREAD

**Issue by gbp** [mysociety/alaveteli#6011]
Now out: https://weblog.rubyonrails.org/2020/12/9/Rails-6-1-0-release/

- [x] Requires #5159

* [Release notes](https://guides.rubyonrails.org/v6.1/6_1_release_notes.html)
* [Upgrade notes](https://guides.rubyonrails.org/v6.1/upgrading_ruby_on_rails.html#upgrading-from-rails-6-0-to-rails-6-1)

**Comment by garethrees** [comment]
May require https://github.com/mysociety/sysadmin/issues/1407.

**Comment by garethrees** [comment]
From the upgrade notes it doesn't look like much, if anything, will have a major impact on us.

**Comment by gbp** [comment]
Looks like some changes might be required in our `conditionallyprependlocale` route filter.

See: https://github.com/svenfuchs/routing-filter/commit/8b85058acf5503877e3830158afbbbc415eae71f#diff-ff2e2792509c994a000cb388544e2b4452a96b6eaf8c065382f09f6e124ece9c

**Comment by gbp** [comment]
Need to run `bundle exec rails active_storage:update` and commit new migrations
