### ISSUE TITLE
IncomingMessage#refusals should only return unique refusals

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#6020]
![Screenshot 2020-12-11 at 09 26 46](https://user-images.githubusercontent.com/282788/101886298-31ffa180-3b93-11eb-9906-608cab9b69df.png)

**Comment by gbp** [comment]
Do we want to consider returning just "Section 12" if matching "Section 12(1)" and "Section 12(2)" etc?

**Comment by garethrees** [comment]
> Do we want to consider returning just "Section 12" if matching "Section 12(1)" and "Section 12(2)" etc?

Yeah. Subsections _look_ confusing for a start. We're trying to reduce the complexity, so zooming out a layer to the top level of exemption helps do that. On a technical point, we only have the top-level sections to select on `/help/unhappy`, so there's no benefit to getting into the details before then.

**Comment by garethrees** [comment]
While e7d29e6 mostly fixes this, it looks like there's an edge case where 2 identical refusals are cited:

Text:

```
```

Non-uniq refusals:
```ruby
message.refusals
# => [#<Legislation::Reference:0x000055698472ee10
  @elements=["12"],
  @legislation=
   #<Legislation:0x0000556984b7e740
    @key="foi",
    @refusals=["s 12", "s 14", "s 40", "s 21", "s 31"],
    @variants=
     {:short=>"FOI",
      :full=>"Freedom of Information",
      :with_a=>"A Freedom of Information request",
      :act=>"Freedom of Information Act",
      :refusals=>["s 12", "s 14", "s 40", "s 21", "s 31"]}>,
  @type="Section">,
 #<Legislation::Reference:0x000055698472e230
  @elements=["12"],
  @legislation=
   #<Legislation:0x0000556984b7e740
    @key="foi",
    @refusals=["s 12", "s 14", "s 40", "s 21", "s 31"],
    @variants=
     {:short=>"FOI",
      :full=>"Freedom of Information",
      :with_a=>"A Freedom of Information request",
      :act=>"Freedom of Information Act",
      :refusals=>["s 12", "s 14", "s 40", "s 21", "s 31"]}>,
  @type="Section">]

message.refusals[0] == message.refusals[1]
# => false
message.refusals[0].legislation == message.refusals[1].legislation
# => false
message.refusals[0].type == message.refusals[1].type
# => true
message.refusals[0].elements == message.refusals[1].elements
# => true
```

Looks like it's caused by `Legislation` lacking a definition of `==` so falls back on its object ID.
