### ISSUE TITLE
Defunct body is listed in batch request authorities list selection

### ISSUE THREAD

**Issue by schlos** [mysociety/alaveteli#6039]
As per comment in "Add support for batch requests to multiple authorities x:czech-republic" #968 by crowbot, defunct bodies should not be listed as a candidate for sending batch requests.

In the v0.33.0.0 in the select authorities multi-select box on batch requests I see bodies that have defunct tag.

**Comment by garethrees** [comment]
Closing as this has [been fixed](https://github.com/mysociety/alaveteli/blob/1200c777bf9dbb82571349ecef0935ec38930c29/app/controllers/alaveteli_pro/batch_request_authority_searches_controller.rb#L16-L18) in later versions.

**Comment by schlos** [comment]
Fix version looks to be 0.38.3.0

**Comment by garethrees** [comment]
Looks like that particular code I linked to was added in 0.32.0.0 (https://github.com/mysociety/alaveteli/commit/1f77e2e23c09cf588aaac7fbb440d17260e17f20), so strange that you're seeing them still listed. I guess we might have tweaked something somewhere down the line though, so do reopen if you get to the latest version and are still seeing the problem.
