### ISSUE TITLE
View/partial rendered in production logs

### ISSUE THREAD

**Issue by gbp** [mysociety/alaveteli#6079]
When each view/partial is rendered a line is outputted in the production Rails log. While this can be useful info it accounts for a lot of noise in the log file and we probably could change the log level to exclude this. 

By default the log level for rendering is `INFO` we could change to `DEBUG` by doing something similar to:
https://stackoverflow.com/a/57875349

**Comment by garethrees** [comment]
`WARN` is probably a bit _too_ minimal, so this removes partial rendering but keeps log lines for each action.

**Comment by garethrees** [comment]
No plans to change at present. The defaults are generally well considered.
