### ISSUE TITLE
Make mobile phone number redaction work on more mobile phone numbers

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#6081]
I'm wondering if the current redaction works on numbers of the form

>07xxx xxxxxx

but not

>07xxx xxx xxx

**Comment by RichardTaylor** [comment]
Does the current redaction rely on "mobile / mob" prefix?! [*](https://github.com/mysociety/alaveteli/blob/6ea3e5daa29b1dd222452daab2569a75b3dc9192/lib/alaveteli_text_masker.rb#L139)

I'm surprised that works as well as it does if so!

I suggest adding an automatic redaction based on the number itself, also consider:

```
+44 (0)7....
+44 7....
```

This would be UK specific though.

**Comment by garethrees** [comment]
Here's the regexp https://github.com/mysociety/alaveteli/blob/b8cdebf7aab044af3b024bd1484425f6652a562d/lib/alaveteli_text_masker.rb#L143

I think this is essentially the same as https://github.com/mysociety/alaveteli/issues/2278, so going to close as a duplicate.

I'd like to make these more configurable in general.
