### ISSUE TITLE
Authority search very poor

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#6089]
The search box at:

https://www.whatdotheyknow.com/select_authority

is particularly poor, it produces worse results than the general site search. 

A search for cabinet office on the select authority page on WhatDoTheyKnow.com currently gives no results. 

I suspect a number of the cases of reported problems logged at #1179 are not actually issues with the general site search, but with the select authority search. 

See also:  #4426

**Comment by garethrees** [comment]
#1179 is the the same mechanism and #4426 covers the most annoying specific issue, so closing this as this just covers the same ground.

**Comment by RichardTaylor** [comment]
I want to stress the /select_authority search produces different results to the search box in the header and at /search

the /select_authority search often produces no results when a public body name is entered into it. 

Currently for example on WhatDoTheyKnow.com  /select_authority has no results for cabinet office whereas the main search returns many and the Cabinet Office is second. 

Many public body names result in no hits on the authority search eg
https://www.whatdotheyknow.com/select_authority?utf8=%E2%9C%93&query=cambridgeshire+county+council&bodies=1&commit=Search
https://www.whatdotheyknow.com/select_authority?utf8=%E2%9C%93&query=oxfordshire+county+council&bodies=1&commit=Search

Where there are results, putting bodies with many requests to the top (#40470 might help too. 

<img width="1107" alt="caboffice2" src="https://user-images.githubusercontent.com/547695/106594200-b2b29c80-6549-11eb-8b8e-69d82406e5b6.png">
<img width="826" alt="caboffice1" src="https://user-images.githubusercontent.com/547695/106594209-b5ad8d00-6549-11eb-9e6f-bb0b93846ab5.png">

**Comment by RichardTaylor** [comment]
Email to WhatDoTheyKnow today:

>I am trying to make a new request to the Department of Health and Social Care. When I put that in the search box and click Search nothing happens.

They are correct, there are no results at:

https://www.whatdotheyknow.com/select_authority?utf8=%E2%9C%93&query=Department+of+Health+and+Social+Care&bodies=1&commit=Search

I'm going to reopen this, it's clearly a bug which is affecting many users who use a work-flow which takes them via the /select_authority page.

**Comment by garethrees** [comment]
Yeah okay something looks wrong here. Thanks for clarifying.

**Comment by garethrees** [comment]
Seems related https://github.com/notanumber/xapian-haystack/issues/154

**Comment by RichardTaylor** [comment]
A WhatDoTheyKnow user has asked if we can make the results for searches on HS2 and High Speed 2 include the entry we have for [High Speed Two (HS2) Limited](https://www.whatdotheyknow.com/body/hs2), currently those terms don't result in a hit for the body. 

Also related - where the /select_authority search has no hits there is no message to say "no results" it just appears to do nothing.

**Comment by RichardTaylor** [comment]
This isn't just an issue of case sensitivity, the search for Cabinet Office doesn't result in any hits irrespective of capitalisation. 

Interestingly, when typing cabinet office into the search box letter by letter the instant results shown while typing include the cabinet office while the search term is cabi, cabin, cabine, cabinet, cabinet o, and cabinet of  but not when further letters are added.

**Comment by garethrees** [comment]
> This isn't just an issue of case sensitivity, the search for Cabinet Office doesn't result in any hits irrespective of capitalisation.

Yet `"cabinet office"` and `"Cabinet Office"` (quoted) _do_ provide reasonable results.

> Interestingly, when typing cabinet office into the search box letter by letter the instant results shown while typing include the cabinet office while the search term is cabi, cabin, cabine, cabinet, cabinet o, and cabinet of but not when further letters are added.

Yeah, https://github.com/notanumber/xapian-haystack/issues/154 mentions issues to do with stemming which is related to this behaviour.

**Comment by garethrees** [comment]
Noting that I think we upgraded Xapian (or at least the underlying data format – can't remember) recently, and that I need to dig out the issue where this was discussed.

**Comment by gbp** [comment]
@garethrees I don't think this is doing a Xapian search. It looks like this is all happening in SQL via the `PublicBody.with_query` method.

**Comment by gbp** [comment]
Actually, I'm wrong I was on the "View authorities" action at `/body/list/all`. Guess this meants we have 3 differnt ways of searching for an authority

**Comment by garethrees** [comment]
Yeah, `/select_authority` uses the xapian-based [`typeahead_search `](https://github.com/mysociety/alaveteli/blob/b76b69877efa40a82012af417e0ba1152dfc80b8/app/controllers/request_controller.rb#L43).

**Comment by gbp** [comment]
Also seems to be affecting the Pro batch authority search at `/alaveteli_pro/batch_request_authority_searches`

**Comment by gbp** [comment]
In production console:
```
irb(main):001:0> TypeaheadSearch.new('Cabinet Office', { model: PublicBody }).xapian_search
=> nil
```

Dev:
```
[1] pry(main)> TypeaheadSearch.new('Cabinet Office', { model: PublicBody }).xapian_search
=> #<ActsAsXapian::Search:0x00007f99d3f4dea8 snip>
```

**Comment by gbp** [comment]
This fix has now been deployed

**Comment by RichardTaylor** [comment]
Difficulty has been reported finding the body Transport for the North via the search at 

https://www.whatdotheyknow.com/select_authority

When searching for

Transport for the North

the body with that name appears in 14th place in those authority search results, but it appears in 2nd place in the results of a research via the general site header. 

There is a related recent support inbox thread, subject: "Add authority - Transport for the North"
