### ISSUE TITLE
PDF attachments incorrectly recognised as HTML files

### ISSUE THREAD

**Issue by laurentS** [mysociety/alaveteli#6092]
We have a request on madada.fr (embargoed, so I cannot give more details for now than what is below) in which an incoming email contains 2 PDF attachments.
They are being shown by alaveteli as HTML files, although they are valid PDF files (when downloading the raw email as eml and opening in thunderbird, everything is properly recognised). It seems that the error comes from how the sender client describes the attachment:
```
--------------012345628374529843560300
Content-Type: text/html;
 name="redacted_filename.pdf"
Content-Transfer-Encoding: base64
Content-Disposition: attachment;
 filename="redacted_filename.pdf"
```
Note how `Content-Type` is `text/html`. Everything else seems to be correct.

I'm not sure how alaveteli determines the attachment file type, but this seems to throw it off.

Would it make sense to use some form of heuristics or magic numbers (like `file` does on Linux) to verify this? We've only seen this happen once so far.
Alternatively, is there some way to force alaveteli to use a different file format for a given attachment?

**Comment by garethrees** [comment]
That's annoying. 

> I'm not sure how alaveteli determines the attachment file type,

[From the `Content-Type` header[(https://github.com/mysociety/alaveteli/blob/d31ec94770b095a5c82511114dd183d5d4ea148f/lib/mail_handler/backends/mail_backend.rb#L157-L159) of the part.

> Would it make sense to use some form of heuristics or magic numbers (like `file` does on Linux) to verify this? We've only seen this happen once so far.

Could do something like this for sure, though might not be worth it unless it comes up a bit more often.

**Comment by laurentS** [comment]
Thanks for the reply. Agreed that there's no need to worry about this unless it happens more often. I'll close the ticket, and we can always reopen if this happens again, to us or elsewhere.
