### ISSUE TITLE
[JRCT] Pasting snippet removes newline below cursor resulting in weird behaviour

### ISSUE THREAD

**Issue by gbp** [mysociety/alaveteli#6094]
When you paste with mouse it ends up removing the newline below, which is a bit annoying. Might just need to add an extra newline onto the content extracted from the HTML?

![snippets-copy-paste-newline](https://user-images.githubusercontent.com/282788/106305300-6c60f300-6254-11eb-9866-baff4ec36f52.gif)

_Originally posted by @garethrees in https://github.com/mysociety/alaveteli/pull/6087#discussion_r566966404_

**Comment by gbp** [comment]
This will copy/pasting `&quot;` instead of correctly un-escaping the snippet advice.

**Comment by gbp** [comment]
I'm unable to replicate this issue.

Have tested in Firefox, Safari and Brave (Chromium-based), with different Alaveteli themes (WDTK and none theme which the gif appears to use). All combinations work.

**Comment by gbp** [comment]
Actually looking closer at the gif it appears the new line is highlighted so is removed when the snippet is pasted.

**Comment by garethrees** [comment]
The highlight occurs on right click. I'm not doing anything special other than clicking the copy button on the snippet, then right clicking in the text area, then clicking the paste action. The highlight behaviour happens both with a mouse and trackpad right click.

**Comment by garethrees** [comment]
Here it is in Safari, too:

![snippet-newline](https://user-images.githubusercontent.com/282788/125453843-d8df5025-c53c-4cd0-9721-920a443a7b58.gif)

It does seem to be an OS thing though. Left-clicking and using the keyboard shortcut to paste doesn't exhibit the problem.

**Comment by garethrees** [comment]
Interestingly, I don't get this behaviour in FireFox, so… does that mean it's a WebKit Thing?
