### ISSUE TITLE
Note on backpaged requests that they are backpaged

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#6109]
We might want to use the term "unlisted", or "accessible only with the link", or have text like:

>This request is excluded from search results on [site name] ([details](https://github.com/mysociety/whatdotheyknow-theme/issues/767)) 

linking to a full explanation on the help pages (https://github.com/mysociety/whatdotheyknow-theme/issues/767).

**Comment by HelenWDTK** [comment]
+1 (Even if only for admins). This would have been useful to me today during routine admin.

**Comment by garethrees** [comment]
This is desirable, but unlikely to be worked on in the next 12 months so closing for now.
