### ISSUE TITLE
[JRCT] Include a way to go back and change your Refusal Advice wizard answers

### ISSUE THREAD

**Issue by gbp** [mysociety/alaveteli#6138]
I think we should include a way to go back and change your answers along the lines of:

![Screenshot 2021-02-23 at 10 17 22](https://user-images.githubusercontent.com/282788/108830228-094b4d80-75c1-11eb-9c75-a373eac8f5fd.png)

_Originally posted by @garethrees in https://github.com/mysociety/alaveteli/pull/6099#discussion_r580918297_

**Comment by garethrees** [comment]
How about "Snippets related to **my previous answers** or _change my answers_"?

**Comment by garethrees** [comment]
Does "Change" makes it sound like we'll preserve what was submitted? I'm not sure we can do that easily.

**Comment by garethrees** [comment]
Just make this a link to `/help/unhappy/:url_title` for now.
