### ISSUE TITLE
Make clearer that usernames are published and sent to public bodies

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#6154]
At WhatDoTheyKnow we are seeing users who have signed a reqyest with a pseudonym in the message body surprised that their username is shown on the request thread and sent to the public body. 

The recent apparent emergence of this issue may relate to us reaching a different demographic of user. 

Next to the make a request form we currently state:

>Everything that you enter on this page, including your name, will be displayed publicly on this website forever.

that is shown for both logged in and non-logged in users. 

This could become for non-logged in users:

>Everything that you enter on this page, including your name, and username, will be displayed publicly on this website forever.

and for logged in users:

>Everything that you enter on this page, including your name, and username of "[Username]", will be displayed publicly on this website forever.

 
Related: #5063

**Comment by RichardTaylor** [comment]
Possible action to address this:

Include the username prominently on the make a request page, and on the request preview page.  Currently if the user removes their name from the message body on these pages their username is no-longer clearly associated with the request.

**Comment by WilliamWDTK** [comment]
We (WDTK) have received a message from a compliance officer on this subject:

> I have received a request from your website that came with one name attached to the account but the the request was signed off as a different person.
[. . .]
I have no issue with the requests but I would like to know the correct name to respond to.  Can you check and let me know who I should respond to for the most recent request?

Possibly linked: improving general guidance on names — mysociety/whatdotheyknow-theme#897

**Comment by RichardTaylor** [comment]
Could we spot when there is a mismatch between a username and the name used to sign a request and offer a warning, or a stronger warning, in that case. 

I wonder if some of the complex cases we get at WhatDoTheyKnow are really people who've accidentally linked their real names to an attempted use of a pseudonym - and instead of telling us what happened they suggest things like other people having accessed their account.

**Comment by garethrees** [comment]
Simple version of this would be to include a "From" line in the new request header.

![Screenshot 2022-09-23 at 17 12 29](https://user-images.githubusercontent.com/282788/192005820-16c9e147-d874-463c-9694-ff3c15b77cd9.png)

**Comment by RichardTaylor** [comment]
WDTK user correspondence today : ~"Can you please change my username to X to match the name I used to sign my request?"   (Where the username and name used to sign the request were totally different).

**Comment by RichardTaylor** [comment]
User correspondence from today on WhatDoTheyKnow (the above fix appears to be live)

>I didn't realise that the account name shows when I submit an FOI request ... I should have chosen an anonymous pseudonym

**Comment by WilliamWDTK** [comment]
> Did they register / make requests in the last week or so (since this has been live)?

No, more than 6 months ago
