### ISSUE TITLE
Snippet admin page doesn't display correctly in 'CY' version

### ISSUE THREAD

**Issue by MattK1234** [mysociety/alaveteli#6168]
Instead of 'Name', we see: 'Globalize::ActiveRecord::Translation|Name'

![image](https://user-images.githubusercontent.com/47503358/111910873-0aa25580-8a5b-11eb-9db5-6ff478003d3d.png)

This is on WDTK under the Cymraeg version of the snippet.

**Comment by garethrees** [comment]
Fixed by https://github.com/mysociety/alaveteli/pull/5926
