### ISSUE TITLE
Option to add and use a public body logo

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#6172]
Showing a public body's logo on their request page, and on each message from them, could make the service clearer to users.

#5369 suggests using Twitter profile images as logos/avatars.

**Comment by RichardTaylor** [comment]
WhatDoTheyKnow is a great source of public body logos eg. 

https://www.whatdotheyknow.com/request/590718/response/1400672/attach/7/image005.jpg


--


Adding logos could exacerbate the problem of Alaveteli sites being confused for  official government websites. https://github.com/mysociety/alaveteli/issues/7102

**Comment by RichardTaylor** [comment]
Experimental dragon  

https://www.whatdotheyknow.com/body/welsh_government

**Comment by RichardTaylor** [comment]
Imagine tag based logos. We could put the NHS logo on all body pages tagged NHS.

**Comment by RichardTaylor** [comment]
A good anecdote about the use of logos online

https://www.fark.com/comments/blog733/Fark-NotNewsletter-Why-Fark-uses-weird-source-icons-for-CNN-links

**Comment by RichardTaylor** [comment]
>See how Wikipedia justify using public body logos, which are generally subject to copyright, and whose use raises various risks at eg.
>https://en.wikipedia.org/wiki/File:Cambridge_City_Council.svg

Pulling in a comment on this from Slack: "a more UK centric source might be needed though, especially if we wish to rely on [fair dealing](https://www.gov.uk/guidance/exceptions-to-copyright#fair-dealing))". 

There might not be a relevant exception in UK copyright law. 

Perhaps the service would need to move to another jurisdiction to enable this feature to be legally used without permission from the bodies in question.

**Comment by garethrees** [comment]
On the [recent](https://docs.google.com/document/d/1E4-O6j2HP42yBVjRGGuTcu8GsAdy8fL1Jog1gShqI4E/edit#heading=h.d0lx7xvjnn9u) Community & Activism call we essentially decided that we didn't want to get in to this as it causes too much maintenance, copyright issues, and looks too official.
