### ISSUE TITLE
Backpaged requests should be findable by logged in users via search 

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#6181]
Currently backpaged requests contain meta tags to seek to exclude them from search engines, and they don't appear on body/user pages, or in search results, on the site. 

Backpaged requests are impossible to find unless you have the link. 

Making backpaged requests accessible via site search would make them available to anyone looking for them on an Alaveteli site. 

Perhaps a checkbox "include backpaged requests" would be useful to allow searches to include them or not. 

Including backpaged requests only in search results for logged in users prevents them appearing in search results pages which could be indexed by search engines. 

See also: https://github.com/mysociety/alaveteli/issues/843#issuecomment-812504832

**Comment by garethrees** [comment]
I don't disagree here, but just noting that prior to https://github.com/mysociety/alaveteli/issues/5496, the original intention of `backpage` was to explicitly exclude them from internal search results.

**Comment by garethrees** [comment]
Could introduce `unlisted` and have the following mechanics:

| Indexed by: | internal search? | external search? |
|---|---|:---:|
| `backpage` | `true` | `false` |
| `unlisted` | `false` | `false` |
