### ISSUE TITLE
Link to lists of latest requests, and latest responses

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#6183]
Links to:

* [Latest responses](https://www.whatdotheyknow.com/search/variety:response/all)

and

* [Latest requests](https://www.whatdotheyknow.com/search/variety:sent/all) 

could usefully be offered, perhaps from the front page, or from the help pages.

**Comment by garethrees** [comment]
In the sidebar of the request list pages might be a nice place for "useful searches":

![Screenshot 2021-04-06 at 14 17 36](https://user-images.githubusercontent.com/282788/113716913-f90baf80-96e2-11eb-9fea-374fca985b84.png)

Would need to check that this doesn't appear elsewhere in a way that doesn't make sense.
