### ISSUE TITLE
Document the operation of announcements

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#6203]
This refers to the announcements which appear in the green banner on the site/ 

When I currently dismiss an "everyone" announcement I don't then see the next one, either as a logged in user or if I'm not non-logged in. 

This might be a bug. 

Maybe consider:
* Do people actually dismiss the announcements?
* Should non-dismissed announcements be shown at random?

I don't think this is important  - the fact volunteer admins can set the announcement banner at all via the admin interface is excellent, and powerful, any issue just relates to the details of how it is working and how it is expected to work.

**Comment by garethrees** [comment]
I'm labelling this documentation, since it's clear we should add some better inline text about how these work in the admin interface.

If we find that the actual behaviour is not the same as what we've documented, we can convert to a bug.

**Comment by garethrees** [comment]
Noting the existence of a [banner tips page](https://wdtkwiki.mysociety.org/wiki/Banner_tips) to check when we integrate inline documentation.
