### ISSUE TITLE
Hamburger icon for menu isn't obvious to some users. Sign-in link not clear enough to those on narrow screens.

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#6211]
On WhatDoTheyKnow we have some users who appear confused by the responsive design, and in-particular the replacement of the "Sign in or sign up" link with the [hamburger icon](https://en.wikipedia.org/wiki/Hamburger_button) in narrow windows. 

We have lots of users, so occasional reports like this shouldn't be given too much weight, but they are something to consider when it comes to making the services more accessible to a wider group of people. 

Perhaps the sign-in link should remain in text towards the top of the page when the rest of the navigation disappears into the menu?

Perhaps this issue thread can be used to note some details of what is confusing people and what they are trying to do.

**Comment by garethrees** [comment]
Closing as I think the hamburger is an established-enough pattern that most understand it these days.
