### ISSUE TITLE
Public Bodies should be able to have different response time settings and rules

### ISSUE THREAD

**Issue by henare** [mysociety/alaveteli#622]
In Australia FOI laws differ between federal, state and local government. We want to have all public bodies (federal, state and local) in Alaveteli and handle the differing response time requirements transparently to the user.

Each public body should be able to have a different `REPLY_LATE_AFTER_DAYS`, `REPLY_VERY_LATE_AFTER_DAYS` and also [different rules](https://github.com/mysociety/alaveteli/issues/621) about how the days are calculated.

See also similar issue #221.

**Comment by RichardTaylor** [comment]
A user of WhatDoTheyKnow wanted to make a request under the Environmental Information Regulations to a body which is also subject to FOI.  

Presumably they would have wanted an option to mark their request as an EIR request which would have:

* turned off the mention of "Freedom of Information" in the subject line when their request is sent (or switched it to EIR)
* calculated timings for late, overdue, etc. with respect to the timings in the EIR 

There are other access to information laws too; I've personally included the following in [a request](https://www.whatdotheyknow.com/request/order_inviting_selected_accredit)  : 

>I would like this request considered in respect of any relevant access to information legislation or procedures, including by considering the request as general routine correspondence. 

My view is the benefits of mentioning FOI or whatever the primary well known law in a jurisdiction is probably outweigh any drawbacks but there might be a case for giving power users more control, particularly over if a specific law is mentioned material automatically added to the subject line / footer of their request.

**Comment by henare** [comment]
We do this in our theme - it doesn't need to be in core so I'll close this.
