### ISSUE TITLE
Recent requests not appearing on a user's profile or public body pages 

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#6223]
Three requests by WhatDoTheyKnow user 90356 are not appearing on their profile page, or on public body pages. 

These requests have numbers at the end of their titles/subjects leading to, in two cases, large numbers where a number is appended to the URL to differentiate it from otherwise identically titled requests. 

Requests in question: 751755, 751614 and 751743. 

Comments on what might be happening by @garethrees by email:

>We index the events of a request, not the request itself. That means in searches (which are used for the profile page) we often get multiple events per request. We then “collapse” these events into the single request record.

>I have a feeling that what’s happening here will be that we’re somehow getting the value we collapse on wrong for the URL title format SLUG_NUMBER_NUMBER, which presumably then results in it getting collapsed into the request of SLUG_NUMBER – the one the user can see.

**Comment by RichardTaylor** [comment]
This appears to perhaps be a wider issue. 

Four requests from user 229768 are also not appearing on their profile some 6 hours after they were made. This isn't a caching issue in that adding parameters to the profile page doesn't reveal them. 

Is the search index not updating?

**Comment by RichardTaylor** [comment]
This issue does not appear to be restricted to particular users. 

Requests 751681, 751684, 751913, and 751940 - the latest requests to Oxford City Council - submitted over the last two days - are not currently appearing on a public body page or in search results eg. 

https://www.whatdotheyknow.com/body/oxford_city_council

https://www.whatdotheyknow.com/body/oxford_city_council?utf8=%E2%9C%93&query=variety%3Asent&request_date_after=&request_date_before=&commit=Search

**Comment by gbp** [comment]
This should be fixed now. Cause was due to a deployment issue which meant the Xapian index wasn't being updated. Redeploying, waiting for Xapian to index events, and then clearing the cache for https://www.whatdotheyknow.com/body/oxford_city_council.* resulted in the requests now being visible.

**Comment by RichardTaylor** [comment]
Just to confirm the issue with user 90356's requests has also been addressed by this fix.
