### ISSUE TITLE
Enable YouTube videos, and tweets, to be embedded into request pages

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#6232]
Adding a tag 

Youtube:[YouTubeURL]
Twitter:[TweetURL]

could result in the content in question being embedded into the request page. 

This could assist those seeking to use requests for campaigning, and help people wanting to explain the background to their requests. 

An alternative approach might be allowing such embedded material (videos, tweets etc.) in annotations. 

Tweet / video embeds in annotations, combined with special/prominent annotations as proposed at https://github.com/mysociety/alaveteli/issues/34 could enable a video / tweet to be presented at the top of a request page.

**Comment by mdeuk** [comment]
> Adding a tag
> 
> Youtube:[YouTubeURL]
> Twitter:[TweetURL]
> 
> could result in the content in question being embedded into the request page.

I would suggest using the tag `tweet` - we already use `twitter` for public body twitter handles (albeit we don't presently expose this).

We might also want to consider the same basis for YouTube and Vimeo - what about `youtubevideo` and `vimeovideo` or something of that type? In any case, I'm in favour of stronger metadata - a rich dataset is extremely helpful!

**Comment by RichardTaylor** [comment]
If this feature was added we might want to restrict the ability to add such tags to admins and requesters tagging their own requests.

**Comment by garethrees** [comment]
Don't think we're likely to do this
