### ISSUE TITLE
Allow bodies to have a separate email address for internal reviews

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#6233]
On rare occasion public bodies offer a different email address for requests vs internal reviews. 

Almost always it's fine to send the internal review request as a reply to the response, however another option would be for Alaveteli to hold, and use, an optional specific internal review contact address for a public body. 

I think this is an idea not to implement on grounds of increased complexity for little gain. 

We might want to note examples here. 

Implementing this feature could help keep correspondence on the site in rare cases. 

eg. 1

>The review will be removed from the Directorate and coordinated by the Council’s team of Solicitors. A request for review should be directed, by email to [email address] 

https://www.whatdotheyknow.com/request/neca_electric_vehicle_charging#incoming-1704002

however[ in the case of that body the review address has since changed to the request address](https://www.whatdotheyknow.com/request/active_mode_appraisal_tool_amat#incoming-1775237)!.

**Comment by garethrees** [comment]
> I think this is an idea not to implement on grounds of increased complexity for little gain.

In which case I'm going to close this, but do feel free to record instances here and we can reopen if we actually find lots of cases where this would be useful.

**Comment by RichardTaylor** [comment]
Related: https://github.com/mysociety/alaveteli/issues/5998
