### ISSUE TITLE
Sometimes conflicting refusal advice

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#6244]
You can get both "We don't have any advice for your situation but you can send a followup" and "You should reply to the authority for confirmation'

From initial [volunteer feedback](https://groups.google.com/a/mysociety.org/g/alaveteli-dev-private/c/fSmxSKssIMQ/m/64k6aG9BAgAJ).

Here's an example (Section 40: Y,N,N,Y,Y):

![Screenshot 2021-05-17 at 16 55 04](https://user-images.githubusercontent.com/282788/118519078-b05b0380-b730-11eb-9a54-986992581aaf.png)

**Comment by garethrees** [comment]
I think the easiest win here is to think up some better phrasing for "We don't have any advice for your situation but you can send a followup".

This option is intended as an always-available fallback. We never want to _block_ users from making a followup, but we can't always identify something more specific than "you're on your own with this one!"

Perhaps @MyfanwyNixon or @wrightmartin have some nice ideas?

**Comment by wrightmartin** [comment]
> We don't have any _more_ advice for your situation but you can send a followup...

> If you haven't found a suitable next step you can always send a followup

> You can always send a followup to your request, even if we couldn't offer any advice that can help in this instance

I think *2* works best with some polish

**Comment by MyfanwyNixon** [comment]
If none of the next steps look suitable, you can always send a followup

**Comment by garethrees** [comment]
> the next steps

Sometimes _only_ followup is shown. Does it still work in that context?

It's certainly better. Might be a tweak we can make, but not the end of the world if this is the best given all the tradeoffs.

**Comment by wrightmartin** [comment]
> whatever the situation you can always send a followup

? situation is a bit crap

**Comment by MyfanwyNixon** [comment]
There's always the option of sending a followup

**Comment by wrightmartin** [comment]
Yep - this would work great. I can't find where to change it in the code though :)

**Comment by garethrees** [comment]
https://github.com/mysociety/whatdotheyknow-theme/blob/master/config/refusal_advice/actions.yml.erb#L36
