### ISSUE TITLE
Badges / awards for great uses of the site

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#6253]
Great requests, excellent challenges to refusals, annotations etc. should be identified and rewarded. 

Content identified as excellent could be accompanied by an icon/badge, and given prominence on the front page, and elsewhere. 

Users responsible for lots of excellent content could perhaps be given greater privileges. 

Perhaps anyone could make nominations, and admins / trusted users could confirm such awards?

Link to escalating privileges system: https://github.com/mysociety/alaveteli/issues/229

**Comment by RichardTaylor** [comment]
We could have a cuddly toy version of the icon, or a more traditional trophy/medal which we send users in the post in cases of very great use of the service!

**Comment by garethrees** [comment]
I think the notion of a generic "award" that could be applied to lots of different content – `InfoRequest`, `OutgoingMessage`, `Comment`, `User`, etc – with an "award_reason" could be quite interesting. Perhaps there are a couple of levels of award – star, medal, trophy? This feels pretty similar to how we handle "prominence".

**Comment by RichardTaylor** [comment]
The Apple Support Communities have a reputation and rewards system which is described at:

https://support.apple.com/en-us/HT209033

we could take inspiration from that.

**Comment by RichardTaylor** [comment]
We could tag requests by elected reps. 

Perhaps elected reps could be a group we could give "verified user" status to? 
https://github.com/mysociety/alaveteli/issues/7000

**Comment by RichardTaylor** [comment]
Related idea: Identify early users of the site. 

From another service:

>What if we give special user badges to our early adopters? Think about it like the “verified account” on Twitter, something that tells the world that you helped to shape Monzo from the very beginning

https://community.monzo.com/t/badges-for-alpha-beta-and-investors/8223

I'm just noting an idea discussed by others on Slack

**Comment by garethrees** [comment]
Dropping my draft shaping work on this so I can close some tabs. Think this is pretty much good to write up.

![6253-alaveteli-badges](https://user-images.githubusercontent.com/282788/221152153-609d8e24-0479-43f6-a61e-6816318f6e3e.jpg)

**Comment by garethrees** [comment]
Closing in favour of shaped issues:

* https://github.com/mysociety/alaveteli/issues/8224
* https://github.com/mysociety/alaveteli/issues/8225
