### ISSUE TITLE
Only configured exemptions should be used for refusal identification

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#6281]
A user [raised a question](https://groups.google.com/a/mysociety.org/g/alaveteli-dev-private/c/JTNPsg0x3yI/m/nXGqhbmIBgAJ) about the new refusal identification.

![Screenshot 2021-06-02 at 17 34 29](https://user-images.githubusercontent.com/282788/120517849-cde2cb00-c3c8-11eb-9c7b-8662f81c8e17.png)

In reviewing I noticed that we'd recognised "Section 37", but [at present we don't have 37 configured](https://github.com/mysociety/whatdotheyknow-theme/blob/af876b51761fa0ab3ca18cfb8169bb796c9d7c41/config/refusal_advice/exemptions.yml.erb).

We should only identify patterns where the exemption has a value in the refusal advice config.

**Comment by RichardTaylor** [comment]
Perhaps more importantly the context of the mention of "section 37" probably isn't as a FOI exemption.

**Comment by garethrees** [comment]
> the context of the mention of "section 37" probably isn't as a FOI exemption

We're always going to get false-positives in that respect. The phrasing should be along the lines of "We do some automated detection to make things easier for you. We've picked up mentions of X,Y,Z to set the scene of what this (often long) correspondence may contain. If, when you read the correspondence, if in fact we were _correct_, then we can provide a bit of help with that."
