### ISSUE TITLE
Make clear the new refusal identification is not part of the message from the public body

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#6282]
The first feedback on the new refusal identification notice to WhatDoTheyKnow was:

>Has WDTK generated this notice?

![Screenshot 2021-06-02 at 17 34 29](https://user-images.githubusercontent.com/282788/120517849-cde2cb00-c3c8-11eb-9c7b-8662f81c8e17.png)

**Comment by garethrees** [comment]
Also, in this specific example, it identifies an exemption that isn't actually configured https://github.com/mysociety/alaveteli/issues/6281.

**Comment by wrightmartin** [comment]
Could this be as simple as a small 'this message was generated by WhatDoTheyKnow' underneath the text?

**Comment by garethrees** [comment]
I think we should go a little further to explain _why_ we're showing it – perhaps as a "this message was generated by WhatDoTheyKnow (show more)"

**Comment by wrightmartin** [comment]
Yep, the 'show more' would that link to a help page or would we reveal a bit more content in-situ?

**Comment by garethrees** [comment]
We don't have a help page for this at the moment – and I don't think we're in a position to write one without a) more capacity or b) having let this bed in for a significant period (12 months or so maybe).

I think a short high-level description (1 paragraph at the most) of what this is, how we've identified the refusal and why we're showing it would be enough. Myf's been working on a [blog post](https://docs.google.com/document/d/1cCMT1CDNVFnGnFG2PnbEAvXA1RVQqP1CwXjnzau9X9Y/edit#) to announce this feature which will probably have some good wording you can crib from.

**Comment by wrightmartin** [comment]
had a chat about this in Slack, pasting it here for archive purposes.


Martin:mouse_trap: Today at 09:26
@zarino you were the designer for this - any thoughts on this ticket? https://github.com/mysociety/alaveteli/issues/6282#issuecomment-867609890

zarino  34 minutes ago
hah, didn’t anticipate this!

myf  33 minutes ago
Really surprised by it myself! If you go for 'this message was generated by WDTK' you could also link to the blog post.

Martin:mouse_trap:  33 minutes ago
I always worry about doing something based on one snippet of feedback

zarino  33 minutes ago
My instinct would be a “What is this?” link somewhere in the yellow box, which either reveals an explanation in-page, or opens an explanation in a new window

zarino  32 minutes ago
“this message was generated by whatdotheyknow” – what does “generated” mean? isn’t the whole page generated by whatdotheyknow?

[...]

zarino  31 minutes ago
(playing devil’s advocate a bit there)

[...]

myf  30 minutes ago
yeah nice to have a - 'What's this?' box.
'WhatDoTheyKnow has scanned the response you received, and identified that it mentions one or more exemptions. See more [link to blog post]'

Martin:mouse_trap:  30 minutes ago
That’s nice - scanned or even ‘read’

myf  29 minutes ago
'read' sounds like a human is doing it tho

zarino  29 minutes ago
we need a little WDTK robot mascot who can be saying the message in a little speech bubble!

Martin:mouse_trap:  29 minutes ago
argh yes. Writing is hard


zarino  28 minutes ago
Clippy.jpg 
Clippy.jpg


struan:cloud:  19 minutes ago
WTDK has identified that your response mentions one of more exemptions…

zarino  15 minutes ago
Yeah, “WhatDoTheyKnow has identified that North Yorkshire Police may have refused all or part…” is a dead quick change, and drops a much bigger hint that this yellow box has something to do with WhatDoTheyKnow

Martin:mouse_trap:  6 minutes ago
+1 on this smaller change, it’s one nugget of feedback

**Comment by wrightmartin** [comment]
@garethrees how do you feel about adding "WhatDoTheyKnow has identified" to the message "North Yorkshire Police may have..." as the solution for this ticket?

**Comment by garethrees** [comment]
+1 to "WhatDoTheyKnow has identified…"

You'll want to do something like `<%= _("{{site_name}} has identified…", site_name: site_name) %>` for the internationalisation.

Could add 🤖  or similar as a little CSS before element to emphasise that it's an automated process.
