### ISSUE TITLE
Consider presenting the "next steps" / refusal advice publicly 

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#6286]
Imagine an item in the thread timeline, in-line with the message thread, headed refusal advice, and explaining the requester has answered some questions about the response, and the automated advice on challenging the response is as follows.. then presenting it. 

Displaying the advice on the request thread would enable it to be cited, if there was a link to that section of the correspondence thread. 

Alternatively the advice could be provided in a less prominent manner via a link.

**Comment by RichardTaylor** [comment]
Linking to #6285 where I made this suggestion along with other comments.

**Comment by RichardTaylor** [comment]
>* If I select "yes" to "_Has the authority confirmed or denied whether they hold the requested information?_ " I get: "_Send a followup There's always the option of sending a followup. The authority appears to have acted correctly on this point._" « The latter sentence there doesn't appear to make much sense. 

Part of the issue here might be that the advice isn't explicitly linked to the question when it is displayed. Also perhaps there should just be no advice prompted by answering yes to  "_Has the authority confirmed or denied whether they hold the requested information?_ ".

**Comment by RichardTaylor** [comment]
Key to this suggestion I think is storing the exemptions, and other information, entered into the refusal advice wizard. 

Imagine an administrator, or another helpful (perhaps specially empowered) user, being able to complete the advice wizard for a user, and provide them with a link to tailored advice.

**Comment by garethrees** [comment]
Would like to really simplify the refusal advice, so unlikely to do this with its current implementation.
