### ISSUE TITLE
Offer more advice and practical assistance opening releases sent in various file formats

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#6287]
Government bodies appear to often use Microsoft software, and they release documents in Word, Excel and other formats which requesters sometimes can't easily open. 

The "View as HTML" option is good, but perhaps more could be done, including:

* Pointers to free viewing software offered by Microsoft
* Advice on using Google Docs / Sheets to open files (perhaps encouraging users to use annotations to link to material presented via such services?). 
* Continuing to explore options for more / alternative online viewers
* Advice on non-Microsoft software that can open Microsoft files. 

In other cases non-technical users can be surprised by a response in CSV format. 

An .ODS OpenDocument Spreadsheet Document can also pose a challenge for those unfamiliar with it. 

A note explaining what a .zip file is could help some users who receive one in a response, or see one in a response they are reading. 

Perhaps the file format could be detected and file format specific advice offered?

**Comment by mdeuk** [comment]
Do you have a specific request in mind when describing this? I'm curious as to which filetype generated the problem.

**Comment by RichardTaylor** [comment]
>Do you have a specific request in mind when describing this? 

Not really, but as with many issues I raise it was prompted by user-support experience.

There was a particular a recent message which was the prompt to raise the ticket:

>Subject: Access to replies
>I am having problems accessing the documents attached to replies on the website (which is otherwise excellent!), and was wondering if you could advise please? They just won't open, whether I click on the icon or on 'download'.  I use a chromebook so maybe its just not compatible, but thought I'd check :)
 [...]

The last request viewed their contained an Excel file.
