### ISSUE TITLE
Add Debian Bullseye support

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#6294]
Due out in spring 2021.

**Comment by gbp** [comment]
Will need some changes to commonlib to https://github.com/mysociety/commonlib/blob/5fb846276502efc8c35a0155e2c336230427fffe/bin/install-site.sh#L144-L155

See: https://github.com/mysociety/sysadmin/issues/1507

**Comment by gbp** [comment]
Bullseye repo has been created. https://github.com/mysociety/packaging/pull/2
Just need changes to commonlib
