### ISSUE TITLE
Enact policy of not allowing pro requests to be re-embargoed after publication

### ISSUE THREAD

**Issue by MattK1234** [mysociety/alaveteli#6321]
Batch requests do not have this functionality within the UI however single requests do.

To keep this uniform we should restrict the functionality, perhaps after a grace period to allow correction of errors.

Agreed in principle on the WDTK volunteers catch up call on 24/06/2021 - https://docs.google.com/document/d/1ffX3BCFweAFH3QAWOP659HYvWYD9amdjTJ6O2uQ6ZjI/edit#bookmark=id.izmusihoo8k

Admins / devs can always use discretion based on an individual case and the circumstances explained.

Requires:

- [x] https://github.com/mysociety/whatdotheyknow-theme/issues/841
- [x] https://github.com/mysociety/whatdotheyknow-theme/issues/976
- [x] ~~https://github.com/mysociety/alaveteli-professional/issues/578~~
- [x] https://github.com/mysociety/alaveteli/issues/7317
- [ ] https://github.com/mysociety/alaveteli/issues/5889 (to make covering the exceptions easier)

**Comment by garethrees** [comment]
This is desirable, but unlikely to be worked on in the next 12 months so closing for now.
