### ISSUE TITLE
'eir_only' tag does not appear to change legislation on a request

### ISSUE THREAD

**Issue by MattK1234** [mysociety/alaveteli#6322]
WDTK Body 92627 - Electricity North West Limited

This body has the tag `eir_only` yet all but the first request (704413) show
`law used: foi`

This means the public request page mentions FOI and not EIR. Requests with this issue are 716316, 716317, 716318, 738434, 749218. This may also affect advice given on requests re timings / exemptions / next actions etc.

We cannot see from the admin page when the `eir_only` tag was added but believe it to be from when the body was first created (03/03/2020).

This seems to be across all bodies tagged `eir_only` not just ENWL, I've also seen this at request 757169 to body 110962 (Abellio Scotrail Limited).

Labelling as a bug as I believe something has stopped the legislation change working.

**Comment by garethrees** [comment]
Interesting. On seeing this I thought it may have been https://github.com/mysociety/alaveteli/issues/6271, but several (all? haven't checked) of these are individual requests. Certainly looks like there's been a regression here.
