### ISSUE TITLE
Change subject of email titled "Please update the status of your request"

### ISSUE THREAD

**Issue by itsaphel** [mysociety/alaveteli#6329]
In my email client all emails with this title are bundled up into the same message thread, even though they concern different requests. Other email clients may behave differently.

Perhaps it would be better to introduce the request title into the email subject? This way it will be a separate thread, and also perhaps make the title better clarify what subject the email refers to. For example: "Please update the status of your request: 'Mortgage Rescue Scheme'" is more clear than "Please update the status of your request"

**Comment by garethrees** [comment]
> For example: "Please update the status of your request: 'Mortgage Rescue Scheme'" is more clear than "Please update the status of your request"

This looks like a nice improvement.

If you're not familiar with gettext – our internationalisation mechanism – you'll need to do use gettext's interpolation rather than Ruby string interpolation:

```ruby
# Bad: Won't work correctly or give translators context
_("Please update the status of your request: #{info_request.title}")

# Good: Gives translators context of what's being interpolated
_("Please update the status of your request: {{request_title}}",
  request_title: info_request.title)
```
