### ISSUE TITLE
Emergency admin can't change roles

### ISSUE THREAD

**Issue by itsaphel** [mysociety/alaveteli#6335]
[The docs](https://alaveteli.org/docs/installing/next_steps/#step-by-step) advise using the emergency admin account to make your own account admin. When I tried, it seems the emergency admin doesn't have the ability to change roles. On the /users/{id}/edit page the checkbox next to admin is greyed out. If I inspect element and save anyway, I get the error "Not permitted to change roles".

**Comment by garethrees** [comment]
Argh, sorry!

We're planning to replace the emergency admin user (#5996), so going to close this.

You can add a role through the rails console like:

```ruby
User.find_by(email: 'you@example.com').add_role(:pro_admin)
```

**Comment by itsaphel** [comment]
@garethrees Would it be worth adding that snippet to the doc?

**Comment by garethrees** [comment]
Sure! Would be nice to add until we manage to do https://github.com/mysociety/alaveteli/issues/5996 🙏

**Comment by pax** [comment]
I have entered the _rails console_ (with `bundle exec rails console`) – I got this warning:
    Loading development environment (Rails 5.2.6)
    irb: warn: can't alias context from irb_context.
   
then upon `User.find_by(email: 'you@example.com').add_role(:pro_admin)` I got: 
     `NoMethodError (undefined method 'add_role' for nil:NilClass)`

even `User.find_by(email: 'postmaster@alaveteli.myfoia.org')`  returns `nil`

would it also be possible to edit the user right from the database?

**Comment by pax** [comment]
I tried to make an user admin from the database: I browsed the `alaveteli_development` db / `users` table and looked for _annie@localhost_  which I knew is an admin user, then looked for her id in the `users_roles`.  

Then copied/inserted her roles (2,3) in the `users_roles` table for my new user in the `alaveteli_production` db. 

Now my user is not an admin but CAN edit users just it can't make them admin – the Roles / admin checkbox is disabled and when I enabled it via browser dev tools I got the _Not permitted to change roles_ notification.

**Comment by gbp** [comment]
> I have entered the _rails console_ (with `bundle exec rails console`) – I got this warning:
> Loading development environment (Rails 5.2.6)
> irb: warn: can't alias context from irb_context.

This is showing you're in a rail console for the development environment so this will be looking at the alaveteli_development postgres table which is probably why it can't find the user.

To open a production console run:
`bundle exec rails console RAILS_ENV=production`

**Comment by pax** [comment]
it's like never just _that_ easy :)
when trying to run console like that, I got a deprecation warning and: 

>    config.eager_load is set to nil. Please update your config/environments/*.rb files accordingly:
>      * development - set it to false
>      * test - set it to false (unless you use a tool that preloads your test environment)
>      * production - set it to true
      
Though I looked into  `config/environments/*.rb` and `config.eager_load` is already set like above, but I still get the following error, https://pastebin.com/zy6etyN8  ending in:
>  'RAILS_ENV=production' database is not configured. Available: ["default", "development", "test", "production"] (ActiveRecord::AdapterNotSpecified)

 so it seems that the correct command (for my set-up at least) would be `bundle exec rails console  production` 
 
 after this `User.find_by(email: 'you@example.com').add_role(:admin)` works indeed. 
 
 Note, for regular Alaveteli deployments is `.add_role(:admin)` , not pro_admin
