### ISSUE TITLE
Migrate legacy Chert Xapian DBs to Glass

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#6344]
- [x] Requires https://github.com/mysociety/alaveteli/pull/6208
- [ ] Requires https://github.com/mysociety/alaveteli/pull/4605

Potentially relevant here:

* https://github.com/mysociety/alaveteli/issues/4586
* https://github.com/mysociety/alaveteli/issues/4614
* https://github.com/mysociety/alaveteli/pull/4606
* https://github.com/mysociety/alaveteli/issues/4637
* https://github.com/mysociety/alaveteli/issues/4636

Lots of our older installs, including WDTK, use Chert.

Need to list the installs that need migration, and then do them.

**Comment by sagepe** [comment]
All of them will need migrating. If we're going to be deploying any new Alaveteli installations anytime soon let's get #6208 merged before then so they can start using the Glass backend.

**Comment by gbp** [comment]
While migrating vhosts to the new infra as art of https://github.com/mysociety/sysadmin/issues/1527

We have been rebuilding the Xapian indexes as `glass` where possible - eg where is didn't take long to generate from scratch and where there was no errors)

The current state of indexes are as follows:

Country | Format
-------- | ------
WDTK | chert
EU | chert
Belgium | chert
Colombia | chert
Czechia | chert
Greece | glass
Liberia | glass
Nepal | glass
Netherlands | glass
Rwanda | glass
Turkey | glass
Uganda | glass

**Comment by sagepe** [comment]
So the indexing process can take time and be quite memory intensive, so I think doing this at deploy during a migration is only really viable when the site is a small one.

We may need to look at building a new glass index offline on fast machine, then swapping into place and updating once done for the larger sites.
