### ISSUE TITLE
Add support for Ruby 3.0

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#6348]
- [x] Requires https://github.com/mysociety/alaveteli/issues/5440

**Comment by gbp** [comment]
Might need to bump Xapian bindings to 1.4.19 which includes https://github.com/xapian/xapian/commit/63a06768a250b0bb4821b835f011e8214d560f8e

**Comment by sagepe** [comment]
> Might need to bump Xapian bindings to 1.4.19 which includes [xapian/xapian@63a0676](https://github.com/xapian/xapian/commit/63a06768a250b0bb4821b835f011e8214d560f8e)

Noting that as of this comment, official Debian packages in testing and unstable are still on 1.4.18-4. If we need 1.4.19, we'll need to package this ourselves. We may also need 1.5.x when release, due to issues with IPv6 support, but that isn't likely to come before later this year.

**Comment by gbp** [comment]
@sagepe just a heads up as in the sprint after next, we're going to look at upgrading Ruby so we might need 1.4.19 although I haven't tested anything yet.

**Comment by sagepe** [comment]
OK, just checked and there's still nothing in bullseye backports so if we needed we'll have to look at building our own packages, but this can be done.

**Comment by sagepe** [comment]
Looking at the Xapian bindings issue, I don't think we need that commit - it's for building with clang/LLVM and on Bullseye we'll be using the GNU toolchain.
