### ISSUE TITLE
Extract followup option from actions menu to its own button

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#6363]
Fixes https://github.com/mysociety/alaveteli/issues/5441

The most commonly used option in the Actions menu – write a reply – is in quite an obscure place and leads to lots of user support.

![Screenshot 2021-07-12 at 15 27 54](https://user-images.githubusercontent.com/282788/125304968-e9c18100-e325-11eb-9b5a-205f40682443.png)

This ticket is to extract that option to its own button, and rename the remaining items "more actions":

![Screenshot 2021-07-12 at 15 27 55](https://user-images.githubusercontent.com/282788/125305423-3c9b3880-e326-11eb-92f6-0ffa82bafec1.png)

**Comment by wrightmartin** [comment]
Do we want this to appear at the top and the bottom?

**Comment by garethrees** [comment]
Definitely the bottom; IDK about the top – might be a bit cluttered, but equally would be annoying to maintain 2 different versions of the menu. Open to suggestion on that.

**Comment by wrightmartin** [comment]
My first thought mirrored yours tbh, but it means the 'reply' button will need to remain in the dropdown action menu too, is it that a problem?

**Comment by garethrees** [comment]
Nope, that sounds like a great solution. No harm in having a couple of different ways of getting at something.

Lloyds Bank do this:

![Screenshot 2021-08-09 at 17 02 10](https://user-images.githubusercontent.com/282788/128737526-e3b5aeec-1ab3-419a-ba6f-4ce3fb555039.png)

**Comment by HelenWDTK** [comment]
+1 We have had feedback from a user that made an internal review direct to the authority as they couldn't find the option to do so using WhatDoTheyKnow. They said that they had not noticed the Actions button, and gave some suggestions about how we could better position the button on the page. They felt the best solution would be to do away with the dropdown altogether and use text links, as the options contained within were too important to be hidden in a dropdown.

**Comment by WilliamWDTK** [comment]
When would the button be visible? Only to the logged-in requester, or to others as well?

**Comment by garethrees** [comment]
> When would the button be visible? Only to the logged-in requester, or to others as well?

Always visible with the same behaviour as it currently is – i.e. "Write a reply" is visible to all within the actions menu. If you're not logged in, you get redirected via sign in form. If you are logged in but not the requester, you get a "Only X can do that" message. Only difference with the idea here is that "Write a reply" gets its own top level button rather than being a bit hidden away in the menu.

**Comment by garethrees** [comment]
This is desirable, but unlikely to be worked on in the next 12 months so closing for now.
