### ISSUE TITLE
Admin button to delete annotations

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#6384]
While site administrators can delete messages and correspondence threads from within the web application they cannot currently delete an an annotation. Admins can only hide annotations, not delete them. 

In very rare cases (related primarily to GDPR right to Erasure Cases, or similar cases where we can't justify holding, or don't want to hold, the content of hidden annotations) hiding an annotation is not sufficient, deletion is required.  

This probably occurs rarely enough that developer action on rare occasion might be satisfactory, and less effort than actually implementing this. Front-line support admins having this feature would allow quicker case resolution, involving fewer people, and fewer emails though.

**Comment by RichardTaylor** [comment]
Note this cannot be worked around by deleting text from the annotation and saving it again as there is an event log associated with each annotation.

**Comment by HelenWDTK** [comment]
+1 This came up in relation to a recent defamation/RtE case.
