### ISSUE TITLE
Send site generated emails from a no-reply address

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#6404]
Users replying to site generated emails were responsible for 213/1400 (~15%) of the incoming issues on WhatDoTheyKnow.com in June and July 2021. 

While volunteer administrators were able to assist these correspondents in a personalised and tailored fashion, it is possible that an auto-response could have prevented some of these issues needing to be dealt with manually. 

An auto-response on the no-reply email address could:

* Urge users to classify the state of their correspondence threads, as a route to obtaining specific advice. 
* Tell users who want to respond to the public body that they can do this via the correspondence thread on WhatDoTheyKnow
* Point to the "report this request" option for raising issues with specific correspondence threads. 
* Point to /help/unhappy and the other help pages more generally
* Point to the contact form for those who want to contact the site admin team.

One could envisage different no-reply addresses and different auto-responses for different site messages. 

Admin editable autoresponses might enable quicker trial and improvement of the responses. 

Pros:

* This might one of the changes which could be made to make it practical to run the site with the resources available. 
* Some users may be able to help themselves quicker if given advice in an auto-response than if they wait for human help. 
* More correspondence will be sent via the contact form - which contains features intended to ensure it is correspondence really intended for the site admin team. 

Cons:

* We might make it harder for users, particularly those who struggle using websites, emails, and computers, to get help from us. Many of those who reply to email messages sent by the site, rather than taking actions via the website, are people who are confused and struggling. 
* Risk of feeling like a big institution or public body that tries to make it hard for the public to contact them.

Actions:

* Change text of outgoing system emails to stress ~"replies to this email will not be read".  We might want to make it clear that the intent is that actions are taken via the website, help is available online, and we have a contact form. Getting the tone right will be important. 
* Change the from address on outgoing emails to no-reply@ 
* Set up autorepsonder for messages sent to the no-reply@ address

**Comment by RichardTaylor** [comment]
A low-risk place to start would be with track/alert emails, but I think there's an opportunity to go beyond that to other site generated messages.

**Comment by sallytay** [comment]
To add to Richard suggestions, and perhaps reduce the risk factor for those who struggle with websites we could also add clearer instructions on how to carry out the task that being requested in the response. 

For example, when users are asked to update the status of their request the message doesn't actually state how to do this. So for some it may not be obvious that you access the option to do this via the action button, or we add a section on how to do this on the help page and add the link to the response.

**Comment by RichardTaylor** [comment]
> when users are asked to update the status of their request the message doesn't actually state how to do this. So for some it may not be obvious that you access the option to do this via the action button

We don't ask users to classify their requests via the action button, we point them to the request page and expect them to use the huge bright yellow classification form. 

Perhaps the form is so big people miss it or don't understand it!

We have a ticket on the design of the form

https://github.com/mysociety/alaveteli/issues/6389

Also before we get to offering advice via an autoresponse we should improve the initial message, there's a ticket for that at 

https://github.com/mysociety/alaveteli/issues/5999

**Comment by garethrees** [comment]
Linking to https://github.com/mysociety/whatdotheyknow-theme/issues/1650

**Comment by garethrees** [comment]
Just dropping some notes from a chat about how our other services handle this.

FMS identifies replies to auto-generated emails, and then auto-responds to them.

* https://github.com/mysociety/fixmystreet/blob/master/bin/handlemail is script forwarded from .forward
* https://github.com/mysociety/fixmystreet/blob/master/perllib/FixMyStreet/Email/Incoming.pm is the actual logic code
* https://github.com/mysociety/fixmystreet/blob/master/templates/email/default/reply-autoresponse is the default autoresponse email

WTT has a similar process (https://github.com/mysociety/writetothem/blob/master/bin/handlemail). If a user replies to an auto-generated message, they get an auto-reply telling them they've done so with some phrasing about what to do (~click the link in most cases). If they then reply to the auto-reply, it goes through to support.

Anecdotally, not much changed with wording tweaks to the emails we send.

**Comment by HelenWDTK** [comment]
+1 on this. Now that the holding pen is fixed, this would seem to be the next easy win in terms of cutting down on the volume of support mail.

**Comment by HelenWDTK** [comment]
As an example, since we added the labels to track this, a quick glance at the inbox shows 40 threads where the user replying to a confirmation had already confirmed vs 4 where we intervened to confirm the action for them.
