### ISSUE TITLE
Admin feature for moving annotations between users

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#6412]
Admins can move requests between users, and requests between authorities. 

There is no option to move annotations from one user account to another. 

I would have used this feature today had it been available to anonymise an annotation and move it to a [name removed] account. 

This is not important. On WhatDoTheyKnow we have an explicit policy of focusing on substantive FOI requests and responses and trying not to spend our resources supporting annotations.  

In the case in question the work around was to hide a series of annotations. This isn't ideal, but isn't too bad as it doesn't impact the core function of the service.

**Comment by garethrees** [comment]
> This is not important. 

Yeah, this seems so edge-case that it's unlikely to warrant the additional complexity and maintenance in the application. We can always manually move an annotation using the application console, so we _can_ do it if we need to, or we can work around as above. Closing for these reasons.
