### ISSUE TITLE
Admin option to turn off the holding pen and bounce misdirected messages instead

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#6431]
WhatDoTheyKnow has received 1,813 messages in the holding pen over the last two years. (~12.6% of support threads)

Every one of these has been manually reviewed, and either deleted or placed on the correct correspondence thread. 

We could save this work by turning the holding pen off. 

If you send an email to the wrong, non-existent, @gmail.com address Google staff don't (I imagine) step in and manually work out who you intended to write to and pass it on to them.

**Comment by mdeuk** [comment]
> WhatDoTheyKnow has received 1,813 messages in the holding pen over the last two years. (~12.6% of support threads)

Initially, I though this percentage was slightly implausible - but it checks out. <sup>[1](#fn1)</sup>. 

I'm quite surprised the number is so high. We get them in dribs and drabs - sometimes one a day, sometimes several, but on other days, none - so the pattern is a little hard to pinpoint.

It's worth noting that quite a number of these holding pen alerts are spam - usually either phishing or just general junk mail which is directed to old requests where the unique email address has been inadvertently made public (e.g. in a public body's PDF or docx response).

>If you send an email to the wrong, non-existent, @gmail.com address Google staff don't (I imagine) step in and manually work out who you intended to write to and pass it on to them.

I think the analogous option here is perhaps to consider what would happen if you send a letter to the wrong address. Royal Mail will make a reasonable effort to either fix the issue (via the [National Returns Centre](https://www.mirror.co.uk/news/uk-news/royal-mail-national-returns-centre-1713249) in Belfast), or they will return to sender.

We could merely bounce the messages (as in, return to sender) but wouldn't we then be in a scenario similar to when we bounce back messages where the anti-spam functionality has been engaged (e.g. on older requests) - in other words, we'd still end up with support threads, just with them being initiated by frustrated users or public bodies who complain their messages aren't getting through.

We could, of course, respond matter-of-fact by pointing out the source of the error; but that might be more trouble than it is worth. It might be easier to just deal with the issue, as we do just now - frustrating at it can sometimes be.

A nice 'fix' could be a system generated message which triggers when the message is classified stating 'you used the wrong address, here's the right one' - but, that might be fiddly to implement.

>We could save this work by turning the holding pen off.

A fix such as the one you have proposed in #6388 might help reduce the numbers generated; as would, perhaps, some more spam filtering to help reduce manual administration. Can we train the spam filter by throwing known junk mail at it so as to allow it to 'learn' from some of the junk received?

___ 
**<a name="fn1"><sup>1</sup></a>** From a thread count of the period 04/08/2019 - 04/08/2021, I make there to be 1,815 messages as of 5:04pm today. Extracting that in any reliable fashion from Gmail is a bit of a dark art, so I would caution that the statistics might be 'fuzzy', but given the closeness of our figures, and the slightly differing times between extraction, I'd say they are _accurate_.

**Comment by RichardTaylor** [comment]
Prior to enabling the turning off of the holding pen consider:

* Addressing #6388
* Addressing #5988 
* Looking at how many genuine responses are still in the holding pen after addressing the issues above. 
* Setting up an appropriate bounce message 
* How what would have come into the holding pen can still be monitored
* Continued identification of some request addresses as receiving spam, and messages to them needing to be "blackholed"
* Reviewing how turning off the holding pen would impact spam management in general.

**Comment by garethrees** [comment]
Closing as holding pen noise has been significantly reduced https://github.com/mysociety/alaveteli/milestone/53
