### ISSUE TITLE
Prevent 'calculated homepage' from being generated for certain domains

### ISSUE THREAD

**Issue by mdeuk** [mysociety/alaveteli#6434]
_Originally posted by @RichardTaylor in https://github.com/mysociety/alaveteli/issues/427#issuecomment-892806347_

>On a very closely related point we should stop calculated home pages eg. googlemail.com
>
>Do we need a list of exceptions ?
>
>This could be assembled from a list of the most common domains used in request addresses, presumably after excluding .ac.uk/.nhs.uk/gov.uk then  hotmail / aol / gmail / outlook would come top and we could treat the latter specially?

We did some rough statistics on this issue on https://github.com/mysociety/whatdotheyknow-theme/issues/690 previously - it is certainly causing a data quality issue in the UK, where we have a rather surprising number of public bodies which rely on either free or ISP provided email addresses!

Naturally, we should be surprised that our public bodies are conducting official business using free(mium) email products which are unlikely to meet the standards required by [public records legislation](https://www.nationalarchives.gov.uk/information-management/manage-information/policy-process/managing-email/), but at the same time, we should ensure our software doesn't unintentionally mislead people by sending them in the wrong direction.

This data quality issue creates issues for re-users of our data, such as the use case which prompted the WDTK ticket - e.g. our data being used to populate a Wikidata dataset; and given the pervasion of non-official email addresses for public bodies is unlikely to be a UK specific 'feature', I'd suggest it creates issues for re-users of data on other Alavateli websites as well.

**Comment by garethrees** [comment]
> our data being used to populate a Wikidata dataset

Linking to https://github.com/mysociety/alaveteli/issues/6535.

**Comment by garethrees** [comment]
I think we should only calculate a homepage for a default value in the form, which could then be deleted from the field should it not look sensible, rather than the current system that dynamically generates it.

**Comment by garethrees** [comment]
Might be resolved by a better implementation of https://github.com/mysociety/alaveteli/issues/6434#issuecomment-1036466019
