### ISSUE TITLE
Improve clarity of documentation relating to CSV upload

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#6444]
At  `/admin/bodies/import_csv` the statement "The fields name and request_email are required" is made, but it would be useful to add:

> request_email can be left blank, doing so will result in request_email not being changed. 

There is a link to the Alaveteli Docs and there is is a statement in the table at https://alaveteli.org/docs/running/admin_manual/#creating-changing-and-uploading-public-authority-data which in respect of request_email states "This column must be present, but can be left empty".

Under the table there is a statement "a blank entry leaves the existing value for that column unchanged" so technically it is all documented but not as obviously as it could be.

**Comment by garethrees** [comment]
> The fields `name` and `request_email` are required

This is incorrect if the suggested addition is true.
