### ISSUE TITLE
AttachmentController authenication callbacks

### ISSUE THREAD

**Issue by gbp** [mysociety/alaveteli#6477]
Extracted from #6436

Why is the AttachmentController cache callback is happening before the authentication callbacks... should these be the other way around? 

https://github.com/mysociety/alaveteli/blob/f44ab48dad80c0911dbeb5452c7c09a778e88964/app/controllers/attachments_controller.rb#L13-L16

**Comment by garethrees** [comment]
https://github.com/mysociety/alaveteli/commit/9c74e0ec8c0cb9820d7a19b0cb56b18e27506094 suggests that "Order of callbacks have to be adjusted otherwise the exception for preventing directory listing doesn't get triggered".
