### ISSUE TITLE
Attachments presented as TXT due to unexpected Content-Type

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#6480]
A [query](https://groups.google.com/a/mysociety.org/g/alaveteli-dev-private/c/n1bYBk-1xhI/m/ANx5y-o0AQAJ) came in recently about [a request](https://www.whatdotheyknow.com/request/collections_of_artwork_gifts_sil#incoming-1851657) where the authority had attached a CSV but Alaveteli is presenting it as `.csv.txt`.

Looking at the [raw email](https://www.whatdotheyknow.com/admin/raw_emails/1851505) they have indeed sent a .csv file, but (presumably) their mail client has incorrectly identified it as "application/octet-stream" rather than “text/csv”.

```
Content-Type: application/octet-stream; name="FOI-346070201 Collections.csv"
Content-Description: FOI-346070201 Collections.csv
Content-Disposition: attachment; filename="FOI-346070201 Collections.csv";
	size=17601763; creation-date="Tue, 10 Aug 2021 10:02:37 GMT";
	modification-date="Tue, 10 Aug 2021 10:09:52 GMT"
Content-Transfer-Encoding: base64
```

It looks like we attempt to [add an extension if it doesn’t match the content type](https://github.com/mysociety/alaveteli/blob/0.39.1.3/app/models/foi_attachment.rb#L240-L245), so what’s happening is that we’re identifying this as text/plain, storing that for the content_type, and as such, appending a .txt extension. I’m not actually sure how we’re getting "text/plain" here.

```sql
foi=> SELECT content_type, filename FROM foi_attachments WHERE id=3303691;
 content_type |             filename
--------------+-----------------------------------
 text/plain   | FOI-346070201 Collections.csv.txt
```

I don't think this is a _bug_ because we're doing exactly what we intended. I guess Alaveteli could be more intelligent with this kind of input and, in certain cases, prefer the file extension over the Content-Type header.

I’m not sure this is a huge problem since the CSV is still downloadable, but I guess a little confusing to users who aren’t particularly familiar with CSV.

**Comment by garethrees** [comment]
Hmm so strangely on first attempt I couldn't replicate this in my development environment.

![Screenshot 2021-08-17 at 09 24 36](https://user-images.githubusercontent.com/282788/129691283-9dd7c08b-de50-4055-9762-c47f025b557c.png)

```sql
alaveteli_development=> SELECT content_type, filename FROM foi_attachments WHERE id=34;
  content_type   |           filename
-----------------+-------------------------------
 application/csv | FOI-346070201 Collections.csv
```

**Comment by garethrees** [comment]
Looks similar to https://github.com/mysociety/alaveteli/issues/1232.

**Comment by WilliamWDTK** [comment]
Mentioned [here](https://www.railforums.co.uk/threads/dlr-timetables.139517/post-2827430)

**Comment by sallytay** [comment]
To add ref csv.txt file - a censor rule created to remove an address, has worked correctly at https://www.whatdotheyknow.com/request/148176/response/358889/attach/3/Standard%20FOI%20Extract%2020130208.csv.txt?cookie_passthrough=1

However in the view HTML file 
https://www.whatdotheyknow.com/request/148176/response/358889/attach/html/3/Standard%20FOI%20Extract%2020130208.csv.txt.html the text has been replaced by "xxxxx"

Presuming that this is because it has been recognised as a binary file rather than plain text.

The censor rule can be viewed at https://www.whatdotheyknow.com/admin/requests/148176

**Comment by garethrees** [comment]
We had another [similar instance](https://www.whatdotheyknow.com/request/workforce_planning_and_hr_leads_23#incoming-2444354) where a `docx` was extracted as `.docx.txt`. The correct `.docx` could be extracted cleanly by downloading the raw email.

**Comment by garethrees** [comment]
[Another](https://groups.google.com/a/mysociety.org/g/alaveteli-dev-private/c/Wd4IRpgpEcY/m/ImkZuR9cAAAJ) instance a few weeks ago (`.pdf.txt`).

**Comment by HelenWDTK** [comment]
This has happened again:
<img width="272" alt="Screenshot 2024-03-26 at 10 13 14" src="https://github.com/mysociety/alaveteli/assets/120410992/4a43f24c-f297-4ad9-9b8e-86ecbdced302">

**Comment by HelenWDTK** [comment]
+1 https://www.whatdotheyknow.com/request/cms_platform_information_localgo_33#incoming-2648280

**Comment by WilliamWDTK** [comment]
This has occurred here:
https://www.whatdotheyknow.com/request/complaints_about_uber_drivers_9#attachment-4868373

    Content-Type: text/plain; name="FOI 101007715595.docx"

**Comment by HelenWDTK** [comment]
+1 This is still happening (and seems to be increasing in frequency, but that may just be related to request volume increasing:

https://www.whatdotheyknow.com/request/foi_requests_educational_service_30#incoming-2649015
