### ISSUE TITLE
Canned CensorRule redaction replacements

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#6487]
When redacting requests there are a handful of phrases we frequently use:

* `[Personally Identifiable Information removed]`
* `[Extraneous material removed]`
* `[Potentially defamatory material removed]`

It would be good to incorporate these canned phrases into the admin interface to both save typing, and use it as a tiny teaching tool for newer admins by way of it showing some of the use cases for the feature.

To avoid too much work, we can just use a select field that loads in the canned replacements, and use [javascript to update the input field if one is selected](https://stackoverflow.com/a/10301561). It doesn't matter that these can be changed once inserted into the text field as we don't need a hard set of options – this is just a helper for common cases. Changing the selected option should change the text field text irrespective of what's currently in it.

![Screenshot 2021-08-20 at 11 27 20](https://user-images.githubusercontent.com/282788/130220304-583c1e25-67f3-48dc-807a-86735097acae.png)

![Screenshot 2021-08-20 at 11 27 28](https://user-images.githubusercontent.com/282788/130220264-4eb3933e-2e70-4f33-a2e9-bd6a00fdb28b.png)

![Screenshot 2021-08-20 at 11 35 57](https://user-images.githubusercontent.com/282788/130221094-4fdb3899-0634-44b9-a59b-4f346200c009.png)

Might want to add a prompt like "canned replacements" to the select field with an empty value that doesn't update, but no need to go out of our way for this.

It should be configurable per install, but only at a theme level since these won't change frequently. Here's a spike:

```ruby
# CORE/app/models/censor_rule.rb
DEFAULT_CANNED_REPLACEMENTS = [
  _('[Personally Identifiable Information removed]'),
  _('[Extraneous material removed]'),
 # etc
]

def self.canned_replacements
  @canned_replacements ||= DEFAULT_CANNED_REPLACEMENTS
end

def self.canned_replacements=(replacements)
  @canned_replacements = replacements
end

# THEME/lib/model_patches.rb
custom_replacements = [
  # …
]
CensorRule.canned_replacements = CensorRule.canned_replacements + custom_replacements
```

**Comment by garethrees** [comment]
Just came across [`<datalist>`](https://blog.corsego.com/interesting-html-tags) which made this [super easy](https://github.com/mysociety/alaveteli/pull/6700)!

**Comment by RichardTaylor** [comment]
There's a list of commonly used replacement text introduced via censor rules at:

https://github.com/mysociety/alaveteli/issues/4626#issuecomment-431662093

**Comment by garethrees** [comment]
Just noting for those not following the code changes that this is [a little clunky in Firefox](https://github.com/mysociety/alaveteli/pull/6700#discussion_r771445814), but fine once you're familiar with the quirks.
