### ISSUE TITLE
Change password email address box too small / emails truncated

### ISSUE THREAD

**Issue by everdha** [mysociety/alaveteli#6493]
In "change your password" page of Alaveteli (tested on the French site https://madada.fr/profile/change_password and on the UK one https://www.whatdotheyknow.com/profile/change_password/new?pretoken=[REDACTED]) the email address box is too short / small for showing not so long emails. Maximum seems to be 16 characters seen on screen, after that characters are written, but shown truncated, not visible to user. 

Typical user could think that the email is not written properly, and cannot check if it was written properly (unless he erases charcaters, then he can see what was written next), and has to figure out that he can ignore what he sees and go on by typing blindly the right address.

Try for example 123@567891123456789, this email will be visibly truncated after the 16th character, the second 6. The rest is there but no way to see it unless you erase characters.

**Comment by EdaNano** [comment]
Issue opened on the French Alaveteli platform also MaDada : https://gitlab.com/madada-team/dada-core/-/issues/60
