### ISSUE TITLE
Issue with URL in unsubscribe message

### ISSUE THREAD

**Issue by schlos** [mysociety/alaveteli#6496]
**Issue:**
URL is not parsed properly in sentence "You are no longer following '{{link_to_request}}', a request."

**Screenshot:**
https://snippyly.com/img/?q=4rEmSMBZGM0QXaQ9Mbw9

**Location:**
https://github.com/mysociety/alaveteli/blob/8641ef71de75e7db15afe9f93da63f530b9051fd/app/helpers/track_helper.rb#L82

**My tracking ticket on ImamoPravoZnati theme repo:** 
https://github.com/codeforcroatia/imamopravoznati-theme/issues/107

**Comment by gbp** [comment]
This is the same issue as https://github.com/mysociety/alaveteli/issues/3978
