### ISSUE TITLE
Tick in URL not compatible with Tweetdeck

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#6503]
Alaveteli sometimes puts the following in the URL for a search result. 

>utf8=✓

This resulted in Tweetdeck not properly counting the characters used in a tweet including a URL containing the tick. 

This may be a bug in Tweetdeck, but perhaps doing unusual things isn't a good idea. 

It appears utf8=✓ is added to the URL when a search is conducted from the second search box on a public body page, the search box under "Keywords"

**Comment by gbp** [comment]
It isn't something we've added, it comes from Rails. https://github.com/rails/rails/blob/4866154/actionview/lib/action_view/helpers/form_tag_helper.rb#L816-L823. This gives some background as to why http://intertwingly.net/blog/2010/07/29/Rails-and-Snowmen

The issue will be resolved when we #5159 as the new `action_controller.default_enforce_utf8` config defaults to false. See: https://github.com/rails/rails/pull/32125

I would say it is a fairly standard thing to do and we won't do anything for this other than upgrading Rails so am going to close this issue.

**Comment by RichardTaylor** [comment]
I hit this issue again today. 

Workarounds include removing the utf8=✓ parameter from the URL or escaping it to utf8=%E2%9C%93

**Comment by garethrees** [comment]
Assume we might actually need https://github.com/mysociety/alaveteli/issues/5851 since https://github.com/mysociety/alaveteli/issues/5159 has already been merged.
