### ISSUE TITLE
Second search box on public body page doesn't do a search limited to that public body

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#6504]
A search using the search box presented under "Keywords" in the body (rather than header) of a public body page doesn't do a search restricted to that public body. 

My expectation was the search would be limited to the public body in question. 

A similarly placed search box on a user page is associated with a button labelled "Search contributions by this person" and does function as described/expected.

**Comment by garethrees** [comment]
What did you search for and to which body?

As far as I can tell it works – a search for "computer science" on "Christ's College, Cambridge" page seems to produce the expected results:

<img width="1282" alt="Screenshot 2021-09-06 at 12 11 40" src="https://user-images.githubusercontent.com/282788/132208656-e11f61d9-a32e-45c9-bd65-813dd91c177f.png">

**Comment by RichardTaylor** [comment]
Closing as I can't reproduce this. 

I raised this issue after experiencing some sort of unexpected behaviour, but I wrongly assumed it was a more general issue. I didn't record the specific search which prompted me to raise the ticket. 

Sorry.

**Comment by garethrees** [comment]
No problem!
