### ISSUE TITLE
Include link to original page when downloading zip of all the correspondence

### ISSUE THREAD

**Issue by mlandauer** [mysociety/alaveteli#652]
Would be nice if the generated pdf contained the url of the original correspondence so someone who has just been sent the pdf can find the original on the internet.

**Comment by garethrees** [comment]
This has been happening since the updated PDF styles

![screen shot 2017-02-09 at 11 55 52](https://cloud.githubusercontent.com/assets/282788/22782385/c2bcf39c-eebe-11e6-8045-0e63652ca6a0.png)
