### ISSUE TITLE
Allow users to unsubscribe from post-request survey

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#6529]
A specific instance of https://github.com/mysociety/alaveteli/issues/4603.

While we don't yet have fine-grained unsubscribe options, we can make a small improvement here in using existing functionality to allow users to unsubscribe from the post-request survey.

- [ ] Include `User#receive_email_alerts` setting in `User#should_be_emailed?`
- [ ] Include `User#should_be_emailed?` in `User#can_send_survey?`
- [ ] Include one-click unsubscribe token in survey notification emails

**Comment by gbp** [comment]
At the moment `User#receive_email_alerts` is just used for `TrackMailer`. I would be wary of reusing this column as it would make adding fine-grained unsubscribe options harder and would mean users wouldn't receive these emails as they might expect.

It wouldn't be too much work to add a separate column to record these unsubs. The issue would be knowing which User boolean column to set to false - I believe these changes would be limited to `User::EmailAlerts`

**Comment by garethrees** [comment]
I've thought about this a bit, and on balance, I think we should go with my original proposal here.

> It wouldn't be too much work to add a separate column to record these unsubs. The issue would be knowing which User boolean column to set to false

I agree that it feels like a small change, but it adds _another_ concept to a number of email related things we already have. We'd also have to handle generating a token and an endpoint for handling the token. It's not a _super_ complex thing to do, but it'll all be work that we'll then have to unpick when we _do_ approach https://github.com/mysociety/alaveteli/issues/4603.

> I would be wary of reusing this column as it would make adding fine-grained unsubscribe options harder

I actually think it would make fine-grained subscription options more difficult. When we tackle https://github.com/mysociety/alaveteli/issues/4603, we're almost certainly not going to be adding further booleans to `User`. As per the above, we'll have lots more existing code to support and migrate away from (how do we handle old URLs? probably don't want them to just stop working when we move to a new system… etc).

All in all, doing the simple thing now to fix the problem is low cost, even if the behaviour isn't quite ideal, and makes it easier for us to do what we actually want to do later.
