### ISSUE TITLE
Install and configure Active Storage

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#6530]
As part of our 2021 infrastructure migration we're aiming to reduce the reliance on the filesystem. To do this we'll back our file-handling with [Active Storage](https://guides.rubyonrails.org/active_storage_overview.html).

Our initial setup will be a transparent migration to use the Active Storage local backend for critical models, with zero configuration required by re-users. In a later issue we'll tackle migrating to external backends.

This issue covers the basic setup of Active Storage for Alaveteli.

- [ ] Generate the migrations ([§2](https://guides.rubyonrails.org/active_storage_overview.html#setup))
- [ ] Add `config/storage.yml` ([§2](https://guides.rubyonrails.org/active_storage_overview.html#setup))
- [ ] Ensure specs cleanup files when necessary ([§11](https://guides.rubyonrails.org/active_storage_overview.html#discarding-files-stored-during-system-tests))
- [ ] Check how filesystem backend handles directory file limits

We may need to create several file services to preserve existing on-disk storage locations until we migrate to more appropriate locations in future issues.

**Comment by gbp** [comment]
Might get inspiration from https://www.fastruby.io/blog/upgrades/active-storage/gradually-migrate-from-paperclip.html

**Comment by garethrees** [comment]
Just linking to [the notes doc](https://docs.google.com/document/d/1biCNvRQUPK5N8g9FUKMKGpFowQYwsYhZ9yTbYzAOMSw/edit) that initiated these issues because it always takes me forever to find it.

**Comment by gbp** [comment]
I think we might need to get #6011 done before switching to `ActiveStorage` as it supports multiple backends. Without this then raw emails, attachments and any other stored files would be stored within the same directory or bucket.   

See: https://github.com/rails/rails/pull/34935

**Comment by garethrees** [comment]
I think we can make the first inroads into this without multiple backends, since we're going to move everything to filesystem backend as a first step before we opt to move some WDTK files over to a cloud backend?

**Comment by gbp** [comment]
For the filesystem backend, files are split up into separate directories as we similar how we currently do. 

`ActiveStorage::Blob#key` is a random generated UUID and the directories are split after the 2nd & 4th character - this is probably better than using the ID and separating after the 3rd and 6th number.

EG: `4o/3s/4o3sd1w80ghdt9tfxp1ukbh1tjvu`

The same file in S3 would just be uploaded at the root of the bucket so we can't simply upload a pre-existing `ActiveStorage` on disk store into S3.

**Comment by sagepe** [comment]
> For WDTK we probably want to go with option 2 [S3], as options 1 [new disk store] would require setting up a new NFS share which we probably don't want to do due to some recent issues and pending platform migration.

Ideally I think so, unless we wanted to combine using a new disk store with a move to the new platform. There might be some other options, too, depending on platform stability, urgency and migration timeframe - it's probably easier to talk these through in person then summarise actions here.

> EG: 4o/3s/4o3sd1w80ghdt9tfxp1ukbh1tjvu
>
> The same file in S3 would just be uploaded at the root of the bucket so we can't simply upload a pre-existing `ActiveStorage` on disk store into S3.

Although if the filenames don't vary between disk and S3 backends we could easily script it - find all the files in the hierarchy and just upload those to the root of the bucket; looking at the pattern the final hashed filename retains the full format (so the characters used in initial two directories named for the first two pairs of characters are retained in the filename itself).
