### ISSUE TITLE
Store RawEmail#data in Active Storage

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#6531]
Requires https://github.com/mysociety/alaveteli/issues/6530.

* Migrate extracting and storing the raw email to `attach` provided by Active Storage.
* Probably want to make sure we're not accessing the direct file representation outside of `RawEmail` if at all possible.
* Files on disk should continue to be stored in `APP_ROOT/../raw_emails` under directories namespaced based on the request ID. Looks like this is [possible](https://github.com/rails/rails/issues/32790#issuecomment-642128038) if a little bit of a hack.
* Once this ticket is completed, create an issue for migrating to a non-namespaced directory.

**Comment by gbp** [comment]
So I've done some changes and testing locally to ensure we can handle S3 being down. To replicate it being down I changed my work on https://github.com/mysociety/alaveteli/pull/6539 with:

```diff
diff --git a/Gemfile b/Gemfile
index 61e9a9def..0e3dfef56 100644
--- a/Gemfile
+++ b/Gemfile
@@ -161,10 +161,10 @@ gem 'alaveteli_features', :path => 'gems/alaveteli_features'
 gem 'aws-sdk-s3', require: false
 gem 'azure-storage', require: false
 gem 'google-cloud-storage', '~> 1.11', require: false
+gem 'webmock', '~> 3.14.0'
 
 group :test do
   gem 'fivemat', '~> 1.3.7'
-  gem 'webmock', '~> 3.14.0'
   gem 'simplecov', '~> 0.17.1'
   gem 'simplecov-lcov', '~> 0.7.0'
   gem 'capybara', '~> 3.35.3'
diff --git a/config/initializers/webmock.rb b/config/initializers/webmock.rb
new file mode 100644
index 000000000..f29a97915
--- /dev/null
+++ b/config/initializers/webmock.rb
@@ -0,0 +1,6 @@
+require 'webmock'
+include WebMock::API
+
+WebMock.enable!
+
+stub_request(:put, 'wdtk-test-raw-emails.s3.eu-west-2.amazonaws.com').to_timeout
diff --git a/lib/tasks/storage.rake b/lib/tasks/storage.rake
index 40592937c..c4fc1be97 100644
--- a/lib/tasks/storage.rake
+++ b/lib/tasks/storage.rake
@@ -6,20 +6,24 @@
 
   desc 'Mirror files from primary ActiveStorage backend to secondary backends'
   task mirror: :environment do
+    WebMock.allow_net_connect!
     Rake::Task['storage:raw_emails:mirror'].execute
   end
 
   desc 'Promote mirrored files to be served from the secondary backend'
   task promote: :environment do
+    WebMock.allow_net_connect!
     Rake::Task['storage:raw_emails:promote'].execute
   end
 
   desc 'Unlink primary file if mirrored and promoted to secondary backend'
   task unlink: :environment do
+    WebMock.allow_net_connect!
     Rake::Task['storage:raw_emails:unlink'].execute
   end
 
   task relocate_to_secondary_backend: :environment do
+    WebMock.allow_net_connect!
     Rake::Task['storage:mirror'].execute
     Rake::Task['storage:promote'].execute
     Rake::Task['storage:unlink'].execute

```

So assuming we use the `ActiveStorage` [config above](https://github.com/mysociety/sysadmin/issues/1546#issuecomment-984696834) (where we set up a mirror with the primary service to be the local disk and the secondary service to be S3). With S3 being down results in an exception in the `mailin` process but this exception happens after the primary on local disk file is written.

So we have the mail on local disk, but not on S3. There is now additional [rake tasks](https://github.com/mysociety/alaveteli/pull/6539/commits/ef2930f5e865cae2b6fdbc91b52c2b2b93c3f546) top handle getting mails onto S3, served from S3 and off the local disk.

1. To ensure S3 has the mails we can run `rails storage:mirror` to mirror from the primary service to the secondary service.
2. Once on the secondary service we can run `rails storage:promote` to change where `ActiveStorage::Blob` is served from.
3. Once mirrored and promoted the mail can be removed from primary service using `rails storage:unlink`.

These three rake task can be run individually or together with `rails storage:relocate_to_secondary_backend` and should be run regularly as a cron job. 

All these tasks can easily be adapted for attachments or other files which wish to locate on S3. See: https://github.com/mysociety/alaveteli/pull/6705
