### ISSUE TITLE
Store FoiAttachment#body in Active Storage

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#6532]
Requires https://github.com/mysociety/alaveteli/issues/6530.

* Migrate extracting and storing the attachment to `attach` provided by Active Storage.
* Files on disk should continue to be stored in `APP_ROOT/cache/attachments_production` under directories namespaced based on the first few characters of the hexdigest. Looks like this is [possible](https://github.com/rails/rails/issues/32790#issuecomment-642128038) if a little bit of a hack.
* Once this ticket is completed, create an issue for migrating to a non-namespaced directory.

**Comment by gbp** [comment]
In deploying this we saw increase error rates so we reverted in order to take a look.

It appears for WDTK we don't have all `FoiAttachment` records on disk. Running:

```
attachment_ids_not_on_disk = FoiAttachment.find_each.reject { |a| File.exist?(a.filepath) }.map(&:id)
attachment_ids_not_on_disk.count => 192589
```

**Comment by gbp** [comment]
WDTK is using a `ActiveStorage` backed attachment mirrored service, with primary disk and secondary SFTP to the new WDTK server is prep for migration.
