### ISSUE TITLE
Create source_url snapshot after accepting a PublicBodyChangeRequest

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#6554]
We'd used a GMail address as the address for a Town Council. The notes in our version history just state "Created from spreadsheet".

We've just had a rather frustrated contact update request from the council as they're being investigated for late responses. They claim that "The email address you have is not the Town Council's correct email, nor has it ever been". 

Via archive.org, I was able to find the GMail address listed on the county council's website at the time of us adding it to WDTK, which demonstrates that we had the correct address.

We should do more to check the functionality of addresses (https://github.com/mysociety/alaveteli/issues/4837) to avoid these situations, but also having a good audit trail helps us defend our reputation. These records add better accountability of how authorities manage their contact addresses.

**Comment by RichardTaylor** [comment]
>The notes in our version history just state "Created from spreadsheet".

There is no option to set a "Comment for this edit" when uploading from a CSV. There is a ticket suggesting this feature at #6161

**Comment by mdeuk** [comment]
> Via archive.org, I was able to find the GMail address listed on the county council's website at the time of us adding it to WDTK, which demonstrates that we had the correct address.
> 
> We should do more to check the functionality of addresses (#4837) to avoid these situations, but also having a good audit trail helps us defend our reputation. These records add better accountability of how authorities manage their contact addresses.

I recommend using https://web.archive.org/save - it takes a couple of seconds, and I've been using it successfully for this very task.

There are, of course, other archival services out there - but this is free, fast, and from a trusted source.
