### ISSUE TITLE
Show who made each edit on public body admin pages

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#6556]
Related:

* #6161 
* #1294

**Comment by RichardTaylor** [comment]
A new admin joined WhatDoTheyKnow and they signed their "Comment for this edit" - working around the absence of this feature.

**Comment by mdeuk** [comment]
> A new admin joined WhatDoTheyKnow and they signed their "Comment for this edit" with their name - working around the absence of this feature.

I agree, this would be a useful feature. I usually sign my changes, but having the audit history  right in front of us would be helpful for looking back at things in the future.
