### ISSUE TITLE
Add more illustration to Alaveteli / WhatDoTheyKnow

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#6586]
At the 2021 retreat I had a conversation with Catherine where she mentioned (paraphrasing) "Trust = Competence + Warmth".

This made me think about this with respect to WDTK. We're high on competence, but less so on warmth. Adding illustration elements could re-address that balance. What do I mean by this?

At the most basic level, here's a little notice that @zarino (I think!) doodled while on breakfast duty. It's so much more _human_ with the little drawing.

![plates](https://user-images.githubusercontent.com/282788/137730464-62a0e814-06e8-4d7f-9568-f623e419044b.jpg)

We've got a bit of this, but it's largely around the Pro marketing pages.

![Screenshot 2021-10-18 at 13 29 50](https://user-images.githubusercontent.com/282788/137730657-4c6e998d-88c3-4eaa-ab35-8f814dd7427e.png)

I also came across a holiday cottage site with context-specific landing pages ("by the beach", "near a pub", "with a hot tub", "with a log fire"):

![illustrations](https://user-images.githubusercontent.com/282788/137729631-b2827650-03f7-41b7-8ce4-9a41ee6d0a89.jpg)

I could imagine something similar for our help pages and other topic-based landing pages (https://github.com/mysociety/whatdotheyknow-theme/issues/442).

I think we could also use small illustrations on the home page, during the request flow, and to pull more case studies into the site (https://github.com/mysociety/alaveteli-project/issues/143).

**Comment by RichardTaylor** [comment]
WhatDoTheyKnow user feedback on the look of the site:

> In the days I last used it you had a nicely composed witty photo of a shocked respectable-looking couple.  I am sorry to see you have ditched it in favour of Microsoft-style blocked text.  Not a good look.  Despite Mr Blair's recantation of his sole positive achievement in office, the photo subtly reinforced the message that FoI is not some sort of extremist programme undermining good governance (the civil service line of attack) but is at the heart of true democracy and available for all of us, and may be needed even by the well-heeled as well as the downtrodden.  That message is still needed, as I suspect FoI doesn't always have particularly strong friends in the current governing party.  

>I hope the abandonment was not due to whingeing from the ultra-woke brigade, whose many and varied objections to life as we know it now extend to people clapping at concerts.

Image in question from the old WhatDoTheyKnow header:

<img width="383" alt="Screenshot 2021-11-16 at 16 55 30" src="https://user-images.githubusercontent.com/547695/142030813-a09cb692-e423-4bb6-8975-63245f94e151.png">

On being told the redesign was not a result of outside pressure, but just modernisation:

> Ah yes, the cult of modernity.  Bless.

>But the 'Microsoft look' unintentionally sends out non-verbal signals, of the "We know best, and you'll do things our way" variety.  It's chalk and cheese.  You are the goodies.  You don't dictate to your users in a micromanaging way.  (I did get the gentlest of warnings hinting that my FoI request was getting a bit long - a nice touch there).  Whereas Microsoft is an aloof corporate that infantilises its users (remember "Clippy", or read the snarky support pages).   We really don't need a 10 point or 8 point gap between every line we type even though MS says we do, or illiterate grammar suggestions or idiotic auto-reformatting.  I have never forgiven MS for arrogantly setting itself as the user's default page without please-may-I.  It hates its own customers so much that that it once portrayed them as dinosaurs in a lengthy advertising campaign.    

>Royal Blue masthead and blocks of monologue text?  Uncomfortable associations.  How about a golden colour scheme, seeing as you're letting the sunshine in, and a font that doesn't look like MS or TfL?  Georgia and Verdana are not bad; lots of other possibilities.  Something to ponder at the next house style meeting perhaps.

**Comment by RichardTaylor** [comment]
Is adding a photo to a body page worth doing? 

eg. 

https://www.whatdotheyknow.com/body/house_of_commons

<img width="1241" alt="Screenshot 2022-07-13 at 14 40 07" src="https://user-images.githubusercontent.com/547695/178747841-bb17a3b3-2d88-4aea-b507-79149ea3072a.png">

**Comment by RichardTaylor** [comment]
Banner style images appear to look better eg.
<img width="1088" alt="Screenshot 2022-07-13 at 17 35 15" src="https://user-images.githubusercontent.com/547695/178785612-2333cfd4-252f-44e8-92ad-940e2eb9da7d.png">

**Comment by mdeuk** [comment]
For what it’s worth, I think both examples look fine - logos themselves will probably look better in the box on the right.

We do, of course, need to be mindful of performance and usability before introducing too many elements here; but the experiment is certainly worth doing.

We’ve done a/b testing on elements in request pages before, I wonder if there is some value in doing something similar here?

**Comment by FOIMonkey** [comment]
I think the banner style pages look amazing and the images enhance the pages, rather than detracting from anything. 
The pages without them now look quite dull in comparison. 

![2022-07-14 (7)](https://user-images.githubusercontent.com/11962965/178985531-21f93c58-fc39-467a-8c54-ac39a765e999.png)
![image](https://user-images.githubusercontent.com/11962965/178985427-ebb94c92-66ef-4984-8f1f-ac134c49be2e.png)

**Comment by garethrees** [comment]
Discussion about images on body notes extracted to https://github.com/mysociety/alaveteli/issues/7160.

**Comment by garethrees** [comment]
Research for Action's recent [Democratising Local Governance report](https://researchforaction.uk/democratising-governance-report) has some great vibes. Nice and simple, but adds a bit of _feeling_.

**Comment by garethrees** [comment]
Really effective example from [FDS' about page](https://fragdenstaat.de/ueber-uns/).

![fds-illustration](https://github.com/mysociety/alaveteli/assets/282788/f32d5435-edf8-4de8-b844-dc55af5fd8e6)

I don't even need to translate this to instantly get the vibe of:

* Something to do with computers and documents
* Shouting about them / campaigning / people power
* Asking questions and piecing together the puzzle through the documents
* Money and justice
