### ISSUE TITLE
Unknown webhook `customer.subscription.updated`

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#6606]
Today's [webhook digest](https://groups.google.com/a/mysociety.org/g/alaveteli-pro/c/grphCInp0mg/m/8Y6WMbqHAwAJ) had an `Unknown webhook (evt_REDACTED)` entry. The webhook is `Webhook.find(4597)`.

Haven't dug in to the webhook data much – looks like `status` was just going from `incomplete ` to `active` after signup.

```json
  "previous_attributes": {
    "status": "incomplete"
  }
```

Looks like we don't handle this in [`Webhook#state`](https://github.com/mysociety/alaveteli/blob/0.39.1.7/app/models/webhook.rb#L33-L34). I'm not sure what the humanised version of this event is. "Subscription activated"?

**Comment by gbp** [comment]
We're seeing these coming through more commonly now
