### ISSUE TITLE
Tweak censor rules created by the close and anonymise process so they work in more cases

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#6617]
Compare WhatDoTheyKnow censor rules 6289 (set manually by an admin) and 6274 (set automatically by the close and anonymise process) and make it so the one set automatically works as well as the manually set one. 

From information available to admins it appears the difference might be the manual one is set to "Regexp:False", and perhaps the automatic ones should have that setting too?

See related support thread for screenshots of the issue.

**Comment by garethrees** [comment]
We haven't had further reports of this so just closing in favour of https://github.com/mysociety/alaveteli/issues/4922.
