### ISSUE TITLE
Public credit for individuals who added "in the news" links

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#6620]
Related: Add design elements across WDTK that show that volunteers are actively supporting the site, and that encourage people to consider the option #1198

**Comment by RichardTaylor** [comment]
Perhaps the credit could include Pro discounts (or whatever other freebies/rewards service providers can offer). 

https://github.com/mysociety/whatdotheyknow-theme/issues/1062

**Comment by garethrees** [comment]
Closing in favour of https://github.com/mysociety/alaveteli/issues/8314
