### ISSUE TITLE
Replace wkhtmltopdf with Ruby-based PDF generation

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#6656]
As an alternative to https://github.com/mysociety/alaveteli/issues/6489.

We only use `wkhtmltopdf` to render a PDF version of `RequestController#show` to include in the Zip download of a request. We create a PDF render because it's more human readable than the fallback plain text version.

We could generate this PDF using [prawn](https://github.com/prawnpdf/prawn) or similar. We wouldn't really reduce any dependencies, but at least prawn is Ruby so is more testable and we wouldn't have to deal with the hassles of shelling out to a binary. The downside is that we'd have to maintain extra view templates so that the HTML and PDF versions are in sync, and prawn views aren't ERB so it would be quite a task to put together a similar output.

**Comment by sagepe** [comment]
Noting that [the GitHub repos for wkhtmltopdf](https://github.com/wkhtmltopdf) have all now been archived. There are packages available for AMD and ARM on Debian Bookworm, but past that we probably can't expect further builds and given the [status](https://wkhtmltopdf.org/status.html) of the project we're probably better off doing this ticket.

**Comment by garethrees** [comment]
https://blog.corsego.com/docraptor-html-to-pdf

**Comment by garethrees** [comment]
This is desirable, but unlikely to be worked on in the next 12 months so closing for now.
