### ISSUE TITLE
Improve print styles on admin interface for information releases

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#6684]
It's useful to be able to print an admin page to PDF for information releases.

Currently some manual intervention is required to make these usable.

Critically, we need to ensure all [collapse](https://getbootstrap.com/2.3.2/javascript.html#collapse) elements are shown (which we use for e.g. track thing, info request event and request details.

```js
// Unfold all collapsed items
$(".collapse").collapse('show');
```

More nice to have, but we also remove some of the admin chrome around the printout:

```js
// Remove the admin footer, which just links to the admin guides
$(".admin-footer").remove();

// Manually delete the admin nav, since that just creates a long
// list of links to the various items in the admin toolbar.
$("#admin-navbar").remove();
```

We could also usefully hide button elements.

**Comment by mdeuk** [comment]
+1, this would be incredibly helpful for complying with GDPR Right of Access requests (RoAR / DSAR) - at the moment we're currently complying by using redacted screenshots, but this is cumbersome.

It's be great if we could generate a PDF of the page automatically; but even having some basic styling for a do-it-yourself print would make this more usable.

**Comment by RichardTaylor** [comment]
Closely related to: Feature(s) for showing all information related to a user #6267

**Comment by RichardTaylor** [comment]
Long annotations are currently truncated on the user admin page. Full copies may be required for information releases.
