### ISSUE TITLE
Canned User#ban_text reasons

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#6699]
The reason for this proposal is to improve record keeping on why we have banned users, enabling better transparency reporting, and management / oversight.  

Ban reasons:

* Misuse of the service [in breach of the house rules]
* Account suspended as it has been closed and anonymised (Currently this can be a manual, or an automated process, slightly different actions can be taken depending on circumstances)
* Spamming
* Account created to evade ban on another account
* Account suspended to prompt user to engage with admin team advice prior to further use of the service

A review of ban reasons currently in use might help spotting any which don't come into the above categories. 

The downside would be the loss of specifically tailored messages eg. 

"You have persistently misused the service to send non-FOI correspondence despite repeated warnings" 

Having both categories and an optional free-text embellishment is an option but it gets complicated. 

Issue derives from:
https://github.com/mysociety/whatdotheyknow-theme/issues/925#issuecomment-984443864
https://github.com/mysociety/whatdotheyknow-theme/issues/938#issuecomment-984996006

**Comment by mdeuk** [comment]
> Having both categories and an optional free-text embellishment is an option but it gets complicated.

My thinking was that it could work in the same way as setting a prominence reason on a message, e.g. dropdown containing a list of standard options, followed by a free-text message box where the tailored message could be set.

I'd assume, for the most part, that the message could be optional, meaning for most it might actually make this administrative task slightly more efficient, as it would become 'point and click'.

**Comment by RichardTaylor** [comment]
>My thinking was that it could work in the same way as setting a prominence reason on a message

So I think this is an extension of the proposal to include, optionally, sending a message to the user informing them of the ban from within the system.

If we follow the pattern for one-click hiding of requests, the message content would expand on the reason for the ban, but that wouldn't be recorded in the system or shown publicly.

I'll edit the title of this issue.

Related:  Bring user support and takedown requests within the system #419

**Comment by garethrees** [comment]
> My thinking was that it could work in the same way as setting a prominence reason on a message, e.g. dropdown containing a list of standard options, followed by a free-text message box where the tailored message could be set.

The first, easiest, step here would be to use the same implementation mechanism as https://github.com/mysociety/alaveteli/issues/6487.

Wouldn't handle anything in addition to making it easier to create standardised text, but that's quite a big leg up in itself.

**Comment by garethrees** [comment]
> The first, easiest, step here would be to use the same implementation mechanism as #6487.

I've [just found a really simple way to implement this](https://github.com/mysociety/alaveteli/pull/6700) so if we want to just fine tune the ban reasons that we want to include as Alaveteli defaults I can add a similarly quick implementation for this issue! 🎉

**Comment by garethrees** [comment]
You [can't](https://stackoverflow.com/a/23562341) use a `<datalist>` with a `<textarea>, which is what we currently use for `ban_text`.

We do use quite lengthy text [in some cases](https://www.whatdotheyknow.com/admin/users/855).

I guess we could add `User#ban_reason` with the canned reasons with `ban_text` being for additional free text, and then define `User#banend?` like:

```ruby
  def banned?
    ban_reason.present? || ban_text.present?
  end
```

I was against the dual field in https://github.com/mysociety/whatdotheyknow-theme/issues/975#issuecomment-1041539331, but technically might be the better way to resolve this issue.
