### ISSUE TITLE
Expose more tag based lists of authorities

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#67]
For example we have a list of Scottish authorities

http://www.whatdotheyknow.com/body/list/scotland

Internally we tag scottish authorities.

Using those tags, along with others enables searches for things like 

Scottish NHS Bodies :
http://www.whatdotheyknow.com/search/tag:scotland%20AND%20tag:nhs

or
Scottish Police
http://www.whatdotheyknow.com/search/tag:scotland%20AND%20tag:police

We don't expose links to these lists; it might be useful if we did. 

(This arose from a user email asking us why we didn't group Scottish authorities - I suspect this is what they were looking for)

**Comment by garethrees** [comment]
Closing as I think we have a mechanism for doing this – Categories.
