### ISSUE TITLE
Public lists of new citations

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#6701]
Spun out from https://github.com/mysociety/alaveteli/issues/5483#issuecomment-560945106 

>What about a "latest requests in the news" page, and/or section on the front-page?

If this was done well there would  be no need for separate private reporting of new citations as proposed at:

https://github.com/mysociety/alaveteli/issues/6238

**Comment by garethrees** [comment]
There's some great analysis of current citations in [a recent email thread](https://groups.google.com/a/mysociety.org/g/alaveteli/c/W3Qp2QT0mcU/m/8dJc889oAwAJ).

Headline is that ~25% of citations are from non-admins, and there are some that we'd want to think about whether we'd want to give extra prominence to.

**Comment by RichardTaylor** [comment]
Citations added to many requests should be noted together to prevent them from overwhelming the list.

**Comment by garethrees** [comment]
https://farmsubsidy.org/stories is nice:

![Screenshot 2022-12-05 at 13 47 10](https://user-images.githubusercontent.com/282788/205652518-5f564ded-4384-4c89-9b56-940ea586bece.png)

**Comment by RichardTaylor** [comment]
Sometimes newly added citations link to articles or other material published years ago.

We should consider if we want to draw attention to such annotations linking to old material.  

Recording the date of publication for the cited material would enable sorting by date and excluding links to old material, but that might add too much friction to the process of adding a citation.

**Comment by WilliamWDTK** [comment]
> Sometimes newly added citations link to articles or other material published years ago.
> 
> We should consider if we want to draw attention to such annotations linking to old material.
> 
> Recording the date of publication for the cited material would enable sorting by date and excluding links to old material, but that might add too much friction to the process of adding a citation.

A reasonable proxy for this would be to take into account the date of the request. This isn't completely the same, as a new article could be written with old data, particularly if it is looking at how X changes.

Also, if the same citation is added to multiple request, we might want to list it once, but allow users to see all request to which it has been applied.

**Comment by garethrees** [comment]
Closing in favour of planned implementation: https://github.com/mysociety/alaveteli/issues/8314
