### ISSUE TITLE
Is there facility in the software for monitoring whether organizations respond acknowledging requests?

### ISSUE THREAD

**Issue by le-codechetif-blanc** [mysociety/alaveteli#6710]
I notice that in the fyi.org.nz application, the New Zealand Police have maliciously pretended that they simply never received a request of high public importance.
https://fyi.org.nz/request/17510-consent-to-assume-online-internet-identity-form#incoming-68131

Usual practice for most public organizations, at least within NZ, would be to respond by email within a few days. If they don't, it's because they're doing something malicious (just deleting the emails as in this case, or pretending that they need to send a police officer to someone's house to verify that they're qualified to make the FOIA request).

Is there facility within the software to detect cases where organizations have simply stonewalled requests and pretended they never received them, to reduce the delay they can add by doing this?

**Comment by garethrees** [comment]
Hey @le-codechetif-blanc,

Alaveteli parses mail logs to check that the email was accepted by the mailservers of the authority's request address. You can read more about that at https://www.mysociety.org/2016/07/29/the-small-symbol-that-tells-you-all-is-well/

It doesn't look like this is configured on FYI.org.nz, but site admins could manually inspect the logs from that request.

Requests are automatically set to a "waiting response" state after the initial message, and progressively get to "overdue" and "very overdue" if there's been no response.

Closing this as discussions about alaveteli works are better placed on the [project mailing lists](https://alaveteli.org/community/#project-mailing-lists) – please do continue the discussion there if you have further questions. I'm sure many of us in the community have faced this issue, and will have some advice.
