### ISSUE TITLE
More structured way to request reopening of correspondence

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#6791]
Currently reopening of correspondence requests generate an unstructured free text email to the support mailbox.

We could level this up by asking for more information up front, and handling the approval/rejection within the application (https://github.com/mysociety/alaveteli/issues/419).

When the user clicks "contact us" on the reopen message, they could be given a form with a free text field to submit their request. We could also include tickbox-style yes/no questions that we almost always ask. If we added the questions, we'd want this to be stored in something like a JSON blob rather than columns on the database to make it easier to change and customise the questions.

The workflow would be nearly identical to https://github.com/mysociety/alaveteli/issues/6789, so much so that I'm just going to copy those sketches here rather than redraw. In the case of an authority making the request we'd have to handle a free text / null user record and reply address.

> ![Doc - p1](https://user-images.githubusercontent.com/282788/154268835-eb46f5fa-f115-435c-9b60-9a16b6ae0f40.jpg)
>
> ![Doc - p2](https://user-images.githubusercontent.com/282788/154268841-6a8e2e51-193d-4189-b385-e2f7dd9754ba.jpg)

We could also include an entry point to this workflow from the generated bounce message – i.e. "Click here to ask us to reopen this request" – which might help reduce the number of times we need to send a message to ask "Which request are you talking about?"

Like https://github.com/mysociety/alaveteli/issues/6789, we should consider this in the context of https://github.com/mysociety/alaveteli/issues/229 and creating a structured volunteering role around just this workflow. Similarly, we should still receive an inbox notification that a reopen request has been made.

I _think_ the same workflow could be used for both users making the request and authorities making the request, but that's something to hammer out here. I can imagine the Q&A being _slightly_ different.

**Comment by garethrees** [comment]
Related to https://github.com/mysociety/alaveteli/issues/41.

**Comment by mdeuk** [comment]
Linking to #7271 and #7448 - this ticket would be beneficial for enabling better workflows in support mail processing.
