### ISSUE TITLE
Amend heading for public body questions

### ISSUE THREAD

**Issue by mdeuk** [mysociety/alaveteli#6800]
While working on https://github.com/mysociety/whatdotheyknow-theme/issues/722 and https://github.com/mysociety/whatdotheyknow-theme/issues/745 I've noted that the way we present the public body questions on relevant bodies (currently on WDTK the Home Office) is slightly cryptic. This was implemented in #5013.

We begin by stating "Are you asking about your, or others', personal information or personal situation?" - which seems clear enough, to someone with a good grasp of English - but it might not be if you aren't a native speaker. It may also cause reuse problems, as it means the question posed has to tie into the existing heading.

<img src="https://user-images.githubusercontent.com/249418/154820107-f5dc2705-5f62-4742-8ca8-992d7a077319.png" width="300">

### Proposal

To make this easier for our users to understand, would suggest that we modify the heading to something more generic (and reusable).

A simple way of doing this would be to go for the bare minimum of asking: "**What would  you like to do?**"
<img src="https://user-images.githubusercontent.com/249418/154820432-8f4d90ef-f2f4-4f79-82b5-aabee84dd050.png" width="300">

### Why?

Two main reasons:

- Some of our users do not have a strong grasp of the language, meaning they might not fully understand why we're asking them the question, and will continue to misuse the site.
- As @RichardTaylor has noted in https://github.com/mysociety/alaveteli/issues/3515#issuecomment-457208430, we've had advice from the regulator about using _simple language_.

**Comment by garethrees** [comment]
Yep, that looks like a nice improvement 👍

**Comment by mdeuk** [comment]
> Yep, that looks like a nice improvement 👍

Looks like this is a translated string ([new.html.erb (line 238)](https://github.com/mysociety/alaveteli/blob/develop/app/views/request/new.html.erb#L238) / [app.po (line 513/4)](https://github.com/mysociety/alaveteli/blob/develop/locale/en/app.po#L513)) - forgive the dumb question, is there anything notable to do here? I have the slight disadvantage of being more familiar with the wdtk theme itself. 😳

**Comment by garethrees** [comment]
Ah! You can just change the string in the `.html.erb` file and the translation will get generated on the next release, so no need to worry about the `.po` files.

This should be all you need (I haven't checked which heading level is most appropriate though!):

```diff
- <p><%= _('Are you asking about your, or others\', personal information or personal situation?') %></p>
+ <h3><%= _('What would you like to do?') %></h3>
```
