### ISSUE TITLE
Enable and encourage users to help find missing contact details for bodies

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#6831]
Even though WhatDoTheyKnow is well established we still regularly need to research new sets of bodies which come into existence. Currently this involves a lot of work by core volunteers. We used to seek, and obtain, help with research via sharing Google docs spreadsheets but that doesn't appear to work very well any more. 

Finding email addresses could be presented as a second "game" to go alongside 

https://www.whatdotheyknow.com/categorise/play

See also

* Public credit for individuals who have found an email address for a body #6830 

There is a list of bodies with no contact address available to admins:

https://www.whatdotheyknow.com/admin#blank-contacts

Ideally we'd have that list available to all users, and make it easy for users to propose contact addresses. 

In terms of review by the core admin team, perhaps this could be done in bulk, and highlighting possible problems such as non gov email addresses? 

**What we have already**

If a user tries to make a request to a body for which we don't have a contact address they get a page saying:

>Missing contact details for 'Helbeck Parish Meeting'

Unfortunately, we do not have a working Freedom of Information address for [body name]. You may be able to find one on their website, or by phoning them up and asking. If you manage to find one, then please [send it to us](https://www.whatdotheyknow.com/change_request/new?body=body_name).

**What this would achieve**

On WhatDoTheyKnow we have a few lists of bodies which we might add to the system if, after adding them, the system was better at encouraging users to find email addresses for them.

**Comment by garethrees** [comment]
Is this the same as https://github.com/mysociety/alaveteli/issues/3477?

**Comment by RichardTaylor** [comment]
Closing in favour of #3477
