### ISSUE TITLE
Make canned censor rule redaction replacements start with a lowercase letter

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#6844]
Censor rules often end up mid-sentence, so shouldn't start with a capital letter. 

If they should have a capital letter when they appear other than mid-sentence I'm not sure, I suspect perhaps they should. 

The introduction of Canned CensorRule redaction replacements #6487 led to a change in practice.  

This is clearly a very minor issue; the reason for raising it is to seek to make the site/service look professional and smart, which I hope might contribute to encouraging good quality use of the service. 

Related:
https://github.com/mysociety/alaveteli/issues/4626#issuecomment-431662093

**Comment by garethrees** [comment]
I personally don't have a strong opinion on this, but then I capitalised the canned replacements so maybe I shouldn't weigh in.

I assume we use them more mid-sentence than where a capitalised version _would_ be correct?

The canned replacements are only a starting point so can be edited prior to form submission, but I agree we want to have it work without modification for our most frequent case.
