### ISSUE TITLE
Category Picker loses added selection when adding first authority

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#6863]
Go to the category picker and open a category:

![screen shot 2018-10-24 at 08 59 06](https://user-images.githubusercontent.com/282788/47415553-97059c80-d76b-11e8-8fe9-b1e361146386.png)

Click "Add" on an individual authority. The page reloads and forgets the open category:

![screen shot 2018-10-24 at 08 59 21](https://user-images.githubusercontent.com/282788/47415601-b56b9800-d76b-11e8-867c-9be312da303d.png)

Clicking the top-level category opens it, and the last-used category tag. The authority we just added is not marked as "Added":

![screen shot 2018-10-24 at 08 59 31](https://user-images.githubusercontent.com/282788/47415633-d16f3980-d76b-11e8-9a66-7c71d0123401.png)

Clicking "Add" on the authority we already added resolves the issue, and further authorities can be added as normal:

![screen shot 2018-10-24 at 08 59 45](https://user-images.githubusercontent.com/282788/47415684-f4015280-d76b-11e8-9a62-c2633d20e338.png)

Manually transferred from https://github.com/mysociety/alaveteli-professional/issues/567.

**Comment by gbp** [comment]
This appears to be a browser issue with Chrome. Firefox works correctly.

**Comment by gbp** [comment]
Ah actually, there is more going on here. I *can* reproduce in Firefox. If the URL doesn't contain `draft_id=n` parameter then you can see the issue. This, I assume, is when the draft is unsaved. It looks like a full page reload is happening.

**Comment by garethrees** [comment]
Similar issue to https://github.com/mysociety/alaveteli/issues/6865.
