### ISSUE TITLE
Paginating batch search results loses "Added" selection

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#6865]
Steps to reproduce:

* Visit `/alaveteli_pro/batch_request_authority_searches`
* Search for an authority where there are at least 2 pages of results
* Add an authority from the first page
* Click "Next" to go to the second page of authorities
* Add an authority from the second page
* Click "Previous" to go back to the first page
* **Expected:** Authority you initially added says "Added"
* **Actual:** Authority you initially added has "Add" button

![screen shot 2018-07-23 at 17 31 08](https://user-images.githubusercontent.com/282788/43090047-35375310-8e9e-11e8-90df-af198707301b.png)

This is somewhat harmless, as duplicates get filtered out as you go through the flow, but its clearly confusing for a user building a batch.

Requires https://github.com/mysociety/alaveteli/pull/4748 to see this happening. I don't think it got introduced by it. I think we need to trigger `toggleResultDisplay` on pagination in a similar way to https://github.com/mysociety/alaveteli/pull/4748. It would be better for pagination to trigger the existing `toggleResultDisplay` though, rather than reimplementing.

**Comment by gbp** [comment]
Can't replicate this anymore. Probably has been fixed in the recent development.
