### ISSUE TITLE
Category picker shouldn't show categories with no authorities

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#6866]
![screen shot 2018-03-12 at 15 11 05](https://user-images.githubusercontent.com/282788/37291926-a4f7b776-2607-11e8-8ec6-2fd64bc4665f.png)

Just noting that this is a difficult one to fix as outlined in [08ae16f](https://github.com/mysociety/alaveteli/commit/08ae16fa5749b8038bbec795157c545f2e0b96aa):

> This solution also makes fixing mysociety/alaveteli-professional#467
> difficult. Because we're finding and rejecting bodies in the view layer,
> we don't have a count of bodies under each category to be able to figure
> out if a category is empty.

Better quick fix is to just display a "no (requestable?) authorities in this category"

Think this requires https://github.com/mysociety/alaveteli/pull/4620#issuecomment-383517070 to fix properly

**Comment by mattiasaxell** [comment]
Makes sense I think with the quick fix.

**Comment by garethrees** [comment]
We now have a [`PublicBody.is_requestable` scope](https://github.com/mysociety/alaveteli/blob/0.40.1.0/app/models/public_body.rb#L353), so now might be able to do:

```diff
- <% public_bodies = PublicBody.with_tag(category_tag) %>
+ <% public_bodies = PublicBody.is_requestable.with_tag(category_tag) %>
```
