### ISSUE TITLE
Review and expand classifications for "in the news" links / citations

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#6887]
Currently we have:

>* News story
>* Academic paper
> * Other 

Further categories to consider:

>* Tweet « **we could show such tweets in full**
>* Parliament
>* Computer game / simulator
>* Website « **if data released was used by an Alavetei website for example**

This isn't a proposal at this stage just a place to collect ideas. 

Idea: Offer a free text description along with "other" which could be periodically reviewed to see if a new classification is warranted.

**Comment by RichardTaylor** [comment]
We should have a categories for 

* ICO decision notice
* Tribunal judgment

**Comment by RichardTaylor** [comment]
"Website" would be a generic category we could offer more specifically "Blog" and "Wikipedia Article". 

See: 

* https://github.com/mysociety/whatdotheyknow-theme/issues/1510#issuecomment-1315789524

**Comment by garethrees** [comment]
Linking to some additional proposals made as pull requests: https://github.com/mysociety/alaveteli/pull/7339, https://github.com/mysociety/alaveteli/pull/7331

In implementation I want to be careful not to add too much complexity. There's some significant overlap with tags, so I want to be careful not to end up with two systems that do almost the same thing.

**Comment by garethrees** [comment]
I've renamed the citation options in https://github.com/mysociety/alaveteli/pull/8126 to generalise them a bit more and to map with the main target audiences for pro/"high impact users". No plans to expand the categorisation further at this time.
