### ISSUE TITLE
Show note based on a request's tags

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#6912]
On WhatDoTheyKnow we have considered:

i/ Urging people to obtain information on covid from official sources such as who.int and gov.uk on requests mentioning covid.
ii/ Offering advice to those considering, or affected by, suicide on requests mentioning suicide. 

See also :

https://github.com/mysociety/alaveteli/issues/34

and specifically 

https://github.com/mysociety/alaveteli/issues/34#issuecomment-905450700

**Comment by garethrees** [comment]
Also related to #387 – likely that we could build a shared underlying mechanism here.

**Comment by FOIMonkey** [comment]
+1 From the search console data, over the last 16 months, 14,400 people have clicked through to view one particular request after searching various terms relating to how to hang themselves/suicide by hanging.

**Comment by garethrees** [comment]
I'm thinking the best place for these to be useful in the majority of contexts is within the correspondence column, before correspondence starts. It feels about the right level of prominence here.

* Putting them in the request header feels too much; for most incidental notes it would take too much space before you understand what you're looking at.
* Putting them below the correspondence would mean that really important uses of this would be no better than an annotation tacked on the end.
* Putting them in the sidebar wouldn't leave enough space for longer form text.

I think we'd omit them from being collapsible to avoid complexity and to make sure they feel distinct from the correspondence.

Any thoughts?

![Doc](https://user-images.githubusercontent.com/282788/174845675-26bd3f41-1c82-4e39-b3a8-7483e2a6970e.jpg)

**Comment by RichardTaylor** [comment]
Totally happy with the location proposed and idea of highlighting the note in some way.
