### ISSUE TITLE
2FA fail - provision the OTP secret, don't show current code 

### ISSUE THREAD

**Issue by saizai** [mysociety/alaveteli#6916]
https://github.com/mysociety/alaveteli/blob/d066b340a239d2b58abfe01a97be017b7bab0509/app/views/one_time_passwords/show.html.erb#L13

This shows the current HOTP.

Instead, it should be doing something like [this](https://github.com/heapsource/active_model_otp/wiki/Generate-QR-code-with-rqrcode-gem#create-the-qr-code) :

model: `@qr = RQRCode::QRCode.new(@user.provisioning_uri("Your app name"), :size => 7, :level => :h )`

In controller & view,:
1. on HOTP secret generation or change:
   a. show secret as plain text and as QR code, require user to input current code. do not display current code (ever).
   b. if input is correct, increment counter, turn on OTP, save user, & go to their profile page with "otp activated" message
   c. if input is incorrect, go to step 1 again without activating OTP, with "otp code incorrect, check that you entered the secret/QR correctly in your 2FA app" error message, showing exactly the same secret text & QR code as before.
2. if 2FA was enabled, show only the fact that it is, and an option to disable or change it (e.g. due to lost device or by admin); *do not show the code or secret*. (but do allow generating more backup codes if they've used some up; see below)

The confirmation step is required to ensure that the user's setup worked. If you tell them the code, then you can't prove to yourself that they can *generate* the code, which is kinda the whole point of HOTP/TOTP & 2FA.

OTPs (whether HOTP counter based or TOTP time based) are supposed to be generated by both parties from a shared secret (which the provisioning QR code shows), based on "trust on first use" (TOFU) activation. The user who activated it saves the secret. They then can prove on a future authentication, *as a second factor*, their possession of that secret (usually saved to a device, like Google Authenticator app) by generating the current code. 

If you show the code, then the security model of 2FA completely breaks. Instead of proving "I am the same person as the one you provisioned on setup", you're only proving "I had access to the last login session's display of a HOTP code" — which is weaker, easier to steal, and harder to use.

For that matter, you shouldn't be using HOTP like this. You're probably doing it because you didn't do the provisioning correctly in the first place and needed a constant "next code to use".

Use TOTP for primary 2FA, i.e. a shared secret the user can prove they hold. Use HOTP for OTP sent by email or SMS. 

It's too easy to accidentally get a counter mismatch if HOTP is used for ordinary login because you or the user incremented or didn't increment (including e.g. an unauthorized third party login, failure to note that it should be incremented, incrementing twice by accident, etc ), and once the counter is out of sync, it's hard to fix securely because the normal response is to alter it even further. TOTP ensures that this is not a possible failure condition.

HOTP works for OTPs you send, because you can ensure when it's incremented.

However, OTPs you send could also be based on a (different secret) TOTP. Just make sure the time window is set much more generously (e.g. 5 minutes) to allow it to be received, read, copied, & entered.

And while provisioning, provide a set of backup codes in case the 2FA device is lost. That can be e.g. the first 10 codes of an HOTP (where you accept any of them and note which ones have been used), or just a set of passwords which you show on generation, store hashed as usual, and invalidate on use.

**Comment by RichardTaylor** [comment]
>"I had access to the last login session's display of a HOTP code" — which is weaker, easier to steal

I can confirm this issue. I don't keep a record of my OTP, I just obtain it while logged in just before I need to use it [to change my password]. 

Generally the use of a one-time password to protect password-resets is only is quite surprising. What it isn't is two-factor authentication for login, which there is a ticket for at https://github.com/mysociety/alaveteli/issues/4093   Would two-factor authentication of login negate the need for the current one-time password to protect password-resets? I suspect it would.
