### ISSUE TITLE
Protect "add tag to all" feature on body on /admin/bodies with an "are you sure" dialog

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#6941]
I think I just accidentally added a tag to a set of bodies by mistaking the "add tag to all" form for a search form.

**Comment by FOIMonkey** [comment]
+1 I have nearly done this myself a couple of times. It's easy to do when there are a lot of exact tag matches.

**Comment by garethrees** [comment]
Should make the message like:

"Adding tags "X,Y,Z" to 78 bodies – are you sure?"

* Make it clear that you're adding tags, not searching
* Sense check the tags being added after we've parsed the individual tags from the space-separated string
* Show the scale of the addition to sense check it aligns with expectations

**Comment by RichardTaylor** [comment]
Also protect the "remove 'xxx' tag from all" button too.
