### ISSUE TITLE
[ERROR] backup-cache-dir "No such file or directory"

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#6977]
```
rsync: [sender] change_dir "/data/vhost/www.whatdotheyknow.com/alaveteli/cache/attachments_production" failed: No such file or directory (2)
rsync: [Receiver] change_dir#3 "/bytemark-backups" failed: No such file or directory (2)
rsync error: errors selecting input/output files, dirs (code 3) at main.c(825) [Receiver=3.2.3]
```

**Comment by garethrees** [comment]
We did speak about this in the Sysadmin planning call and I think figured out that this isn't a problem, but there's no ticket to record this or whether it's been resolved.

**Comment by sagepe** [comment]
This is an issue specific to our internal deployment of WDTK. I've pushed a commit that will remove this task; discussion on WDTK backup considerations following the move to Active Storage are on [this internal ticket](https://github.com/mysociety/sysadmin/issues/1546).
