### ISSUE TITLE
Ability to have a pro account which can't have embargoed requests

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#7013]
[From Alavetlei Slack](https://mysociety.slack.com/archives/C0260Q872/p1651661712506279?thread_ts=1651658123.544129&cid=C0260Q872) there is an aspiration for a piece of work described as:

>an excellent use of both pro and projects, completely in public 

The ability to offer a pro account which can't have embargoed requests might be useful for this.

**Comment by garethrees** [comment]
This would add too much code complexity. I think a better way is to make adding a privacy period an intentional action rather than a default https://github.com/mysociety/alaveteli/issues/6567.
