### ISSUE TITLE
Give some indication of the size of the batch

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#7018]
Moved from private issue at https://github.com/mysociety/alaveteli-professional/issues/237.

From @crowbot:
* So that users are hyper-aware that this is going to send emails to lots of authorities who will have to deal with them at some cost.
* eg. make the preview look like it is a stack of papers, have some kind of cost estimate total.

From @zarino:

Random thought:

<img width="780" alt="tm_starfield" src="https://cloud.githubusercontent.com/assets/739624/24303253/3c8ecec4-10ad-11e7-9771-8b9f6fbe7920.png">

From me:
* We should do this:
  * On the authority selection interface (https://github.com/mysociety/alaveteli-professional/issues/364).
  * On the preview page.
* Should do a basic implementation of this before we roll out the category picker, because that allows you to easily add loads of authorities.

**Comment by RichardTaylor** [comment]
>some kind of cost estimate

When removing the rate-limit on the free public service we urge users to consider the impact of their requests on our reputation and the reputation of access to information legislation itsself. 

As well as including some kind of cost estimate we could say something like: Misuse of this service for example by making poorly targeted requests or requests for information which is already published puts our access to information legislation at risk, it gives ammunition to those seeking to curtail public access rights and might lead to restrictions such as fees, or ID requirements.
