### ISSUE TITLE
Generate HTML previews for more filetypes, improve icons

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/alaveteli#7027]
Originally suggested for Open Document Formats:

This may not be worth doing, since I'm not sure how often it happens, but it has happened at least once (although that request was, unfortunately, a SAR, and has been hidden).

`.odt`, `.ods`…

Such files are [recommended by Government](https://www.gov.uk/guidance/using-open-document-formats-odf-in-your-organisation).

SEO: view as HTML

**Comment by garethrees** [comment]
Might be something that we can render through the Google Docs viewer.

https://github.com/mysociety/alaveteli/blob/0.40.0.0/app/models/foi_attachment.rb#L257-L274

**Comment by WilliamWDTK** [comment]
Also the current icon on the WDTK view is just a question mark:

![](https://www.whatdotheyknow.com/assets/content_type/icon_unknown-9a0163c0192d34e1cd6b1cdc4709330444f95927ccfbdfb0618f1890ee19e855.png)

(from [https://www.whatdotheyknow.com/request/the_failures_of_dumfries_and_gal#incoming-1501531](https://www.whatdotheyknow.com/request/the_failures_of_dumfries_and_gal#incoming-1501531))

rather than something like the Word icon:

![](https://www.whatdotheyknow.com/assets/content_type/icon_application_vnd.openxmlformats-officedocument.wordprocessingml.document_large-a25bbd55418610620fdb2fe8a7ac5c671a32c4a2bf5caf5819d096c705d06b48.png)

**Comment by FOIMonkey** [comment]
+1 Most [City of London Police](https://www.whatdotheyknow.com/body/city_of_london_police?utf8=%E2%9C%93&query=filetype%3Aodt&request_date_after=&request_date_before=&commit=Search) responses are .odt files and it's a pain to have to download them every time

**Comment by FOIMonkey** [comment]
Also [North Lincs Council](https://www.whatdotheyknow.com/body/north_lincolnshire_council?utf8=%E2%9C%93&query=filetype%3Aodt&request_date_after=&request_date_before=&commit=Search).

**Comment by garethrees** [comment]
Google Docs viewer [doesn't work](https://docs.google.com/viewer?url=https://www.whatdotheyknow.com/request/856634/response/2034330/attach/3/Information%20Disclosure%20FOI2022%2000598.odt), but Microsoft's Office Live View [does](https://view.officeapps.live.com/op/embed.aspx?src=https://www.whatdotheyknow.com/request/856634/response/2034330/attach/3/Information%20Disclosure%20FOI2022%2000598.odt).

Adding this should be straightforward:

1. Add an `AttachmentToHTML::Adapters::OfficeLiveViewViewer` or whatever we want to call it
2. Add `FoiAttachment#has_office_live_view_viewer?` with the correct content type mappings
3. Add a conditional to `AttachmentToHTML#fallback_adapter_for` to wire up the adapter.

**Comment by WilliamWDTK** [comment]
Microsoft's Live View also seems nicer for XLSX files:

[Google](https://docs.google.com/viewer?url=https://www.whatdotheyknow.com/request/856056/response/2041930/attach/3/Wirral%20Allotment%20Costs%202021%202022.xlsx) vs [Microsoft](https://view.officeapps.live.com/op/embed.aspx?src=https://www.whatdotheyknow.com/request/856056/response/2041930/attach/3/Wirral%20Allotment%20Costs%202021%202022.xlsx)

(from [this request](https://www.whatdotheyknow.com/request/856056/response/2041930/attach/html/3/Wirral%20Allotment%20Costs%202021%202022.xlsx.html)

Google handles .csv [like this](https://docs.google.com/viewer?url=https://www.whatdotheyknow.com/request/799933/response/2037110/attach/3/RESPONSE.csv) (not ideal), Microsoft doesn't seem to. (From [here](https://www.whatdotheyknow.com/request/business_rates_1132#incoming-2037110)).

I've taken the liberty of changing the title, which I hope won't be a problem…

**Comment by WilliamWDTK** [comment]
For CSV, there's also things like [this client-side JS viewer](https://github.com/limonte/csv-viewer-online).

**Comment by WilliamWDTK** [comment]
Prevalence of file types (according to searches of the format `https://www.whatdotheyknow.com/search/filetype:EXTENSION/all)

| Extension | Count (about…) | Note |
| :-: | :-: | :-: |
| [`csv`](https://www.whatdotheyknow.com/search/filetype:csv/all) | 48 | I think these might sometimes end up as `.csv.txt`, but I'm not sure how to find those… |
| [`txt`](https://www.whatdotheyknow.com/search/filetype:txt/all) | 8000 | |
| [`xls`](https://www.whatdotheyknow.com/search/filetype:xls/all) | 9700 |  |
| [`xlsx`](https://www.whatdotheyknow.com/search/filetype:xlsx/all) | 17000 |  |
| [`doc`](https://www.whatdotheyknow.com/search/filetype:doc/all) | 67000 |  |
| [`docx`](https://www.whatdotheyknow.com/search/filetype:docx/all) | 31000 |  |
| [`pdf`](https://www.whatdotheyknow.com/search/filetype:pdf/all) | 220000 |  |
| [`xml`](https://www.whatdotheyknow.com/search/filetype:xml/all) | 24 |  |
| [`jpg`](https://www.whatdotheyknow.com/search/filetype:jpg/all) | 40000 |  |
| [`png`](https://www.whatdotheyknow.com/search/filetype:png/all) | 29000 |  |
| [`switch`](https://www.whatdotheyknow.com/search/filetype:switch/all) | 191 | *Our favourite!* |
| [`mp3`](https://www.whatdotheyknow.com/search/filetype:mp3/all) | 10 |  |
| [`mp4`](https://www.whatdotheyknow.com/search/filetype:mp4/all) | 1 |  |
| [`wav`](https://www.whatdotheyknow.com/search/filetype:wav/all) | 3 |  |
| [`zip`](https://www.whatdotheyknow.com/search/filetype:zip/all) | 1900 |  |
| [`gz`](https://www.whatdotheyknow.com/search/filetype:gz/all) | 1 |  |
| [`html`](https://www.whatdotheyknow.com/search/filetype:html/all) | 4500 |  |
| [`tif`](https://www.whatdotheyknow.com/search/filetype:tif/all) | 342 |  |
| [`odp`](https://www.whatdotheyknow.com/search/filetype:odp/all) | 1 |  |
| [`odt`](https://www.whatdotheyknow.com/search/filetype:odt/all) | 360 |  |
| [`ods`](https://www.whatdotheyknow.com/search/filetype:ods/all) | 49 |  |
| [`rar`](https://www.whatdotheyknow.com/search/filetype:rar/all) | 4 |  |

**Comment by FOIMonkey** [comment]
@WilliamWDTK  That table is fascinating, thanks for putting it together. It's interesting to see that we're closing in on 250,000 PDFs.

There are also some other extension types that you can't use the search to find (mainly shapefiles) eg https://www.whatdotheyknow.com/request/school_catchment_areas_2#incoming-619600 
or
 https://www.whatdotheyknow.com/request/public_rights_of_way_data_4#incoming-2023061

**Comment by mdeuk** [comment]
> Google Docs viewer [doesn't work](https://docs.google.com/viewer?url=https://www.whatdotheyknow.com/request/856634/response/2034330/attach/3/Information%20Disclosure%20FOI2022%2000598.odt), but Microsoft's Office Live View [does](https://view.officeapps.live.com/op/embed.aspx?src=https://www.whatdotheyknow.com/request/856634/response/2034330/attach/3/Information%20Disclosure%20FOI2022%2000598.odt).
> 
> Adding this should be straightforward:
> 
>     1. Add an `AttachmentToHTML::Adapters::OfficeLiveViewViewer` or whatever we want to call it
> 
>     2. Add `FoiAttachment#has_office_live_view_viewer?` with the correct content type mappings
> 
>     3. Add a conditional to `AttachmentToHTML#fallback_adapter_for` to wire up the adapter.

We'll probably want a WDTK theme ticket here for any [privacy notice](https://www.whatdotheyknow.com/help/privacy#cookies) changes - as we'd be presenting this in a WDTK branded window, so we need to make the user aware of the cookies being set by this service.

A workaround could perhaps be to simply link directly to it, rather than wrapping around an iframe - but that might be a bit clunky. Worth noting, perhaps, that we likely should have a similar disclosure for Google Docs viewer - which sets cookies too - and like the Microsoft variety, doesn't give any visible indication at time of loading.

I've not raised such a ticket yet, as I'm not sure how close we are to this being implemented.

**Comment by garethrees** [comment]
> I've not raised such a ticket yet, as I'm not sure how close we are to this being implemented.

No _immediate_ plans, so this can be created when we start implementing.

**Comment by WilliamWDTK** [comment]
Not sure if this is the appropriate ticket to raise this on, but for [this attachment here](https://www.whatdotheyknow.com/request/838489/response/1994166/attach/html/4/FOI%200167%20FOI%20response.doc.html), the Google preview has mucked up the formatting, while [Microsoft's previewer](https://view.officeapps.live.com/op/embed.aspx?src=https://www.whatdotheyknow.com/request/838489/response/1994166/attach/4/FOI%200167%20FOI%20response.doc) keeps it nice.

**Comment by WilliamWDTK** [comment]
`.eml` and `.msg`

I think this was raised elsewhere, possibly by @FOIMonkey.

**Comment by garethrees** [comment]
> I'd actually quite like us to look at [Datasette](https://github.com/simonw/datasette)

Me too! https://twitter.com/_gareth/status/1521918004690399232. I did spike this out, but at the time Datasette lite didn't accept a CSV URL, only an sqlite URL, so that was annoying. Seems like it would be pretty easy to add now.

```diff
commit 3ae66c5825bd3156d24f5230b5cc49e79488800e
Author: Gareth Rees <gareth@>
Date:   Wed May 4 20:09:24 2022 +0100

    Basically working CSV to SQL
    
    Downloads as "foo.csv", but then renaming to "foo.sqlite" works as
    expected:
    
        sqlite> select * from foo;
        1|2
        3|4

diff --git a/Gemfile b/Gemfile
index 1e93ef0d6..87876c613 100644
--- a/Gemfile
+++ b/Gemfile
@@ -175,6 +175,8 @@ if rails_upgrade? && RUBY_VERSION < '3.1'
   gem 'uri', '0.10.0'
 end
 
+gem 'csv_to_sqlite3', require: 'csv_to_sqlite'
+
 group :test do
   gem 'fivemat', '~> 1.3.7'
   gem 'webmock', '~> 3.14.0'
diff --git a/Gemfile.lock b/Gemfile.lock
index 332c72c80..4a3ac6dcb 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -169,6 +169,9 @@ GEM
     crack (0.4.5)
       rexml
     crass (1.0.6)
+    csv_to_sqlite3 (0.1.4)
+      sqlite3 (~> 1.4, >= 1.4.2)
+      tty-progressbar
     daemons (1.4.0)
     dalli (3.2.2)
     dante (0.2.0)
@@ -467,7 +470,9 @@ GEM
       actionpack (>= 5.2)
       activesupport (>= 5.2)
       sprockets (>= 3.0.0)
+    sqlite3 (1.4.2)
     statistics2 (0.54)
+    strings-ansi (0.2.0)
     stripe (5.55.0)
     syslog_protocol (0.9.2)
     text (1.3.1)
@@ -478,6 +483,13 @@ GEM
     thor (1.2.1)
     tilt (2.0.10)
     trailblazer-option (0.1.2)
+    tty-cursor (0.7.1)
+    tty-progressbar (0.18.2)
+      strings-ansi (~> 0.2)
+      tty-cursor (~> 0.7)
+      tty-screen (~> 0.8)
+      unicode-display_width (>= 1.6, < 3.0)
+    tty-screen (0.8.1)
     tzinfo (2.0.4)
       concurrent-ruby (~> 1.0)
     uber (0.1.0)
@@ -529,6 +541,7 @@ DEPENDENCIES
   capistrano (~> 2.15.0, < 3.0.0)
   capybara (~> 3.37.1)
   charlock_holmes (~> 0.7.7)
+  csv_to_sqlite3
   dalli (~> 3.2.2)
   exception_notification (~> 4.5.0)
   factory_bot_rails (~> 6.2.0)
@@ -602,3 +615,6 @@ DEPENDENCIES
   xapian-full-alaveteli (~> 1.4.18.1)
   xml-simple (~> 1.1.9)
   zip_tricks (~> 5.6.0)
+
+BUNDLED WITH
+   2.1.4
diff --git a/app/controllers/attachments_controller.rb b/app/controllers/attachments_controller.rb
index c64174f82..a3524ca03 100644
--- a/app/controllers/attachments_controller.rb
+++ b/app/controllers/attachments_controller.rb
@@ -13,7 +13,7 @@ class AttachmentsController < ApplicationController
 
   include ProminenceHeaders
 
-  around_action :cache_attachments
+  around_action :cache_attachments, except: :show_as_sqlite
 
   before_action :authenticate_attachment
   before_action :authenticate_attachment_as_html, only: :show_as_html
@@ -36,6 +36,29 @@ def show
     render body: body, content_type: content_type
   end
 
+  def show_as_sqlite
+    raise StandardError unless content_type == 'text/csv'
+
+    body = @incoming_message.apply_masks(
+      @attachment.default_body,
+      @attachment.content_type
+    )
+
+    CsvToSqlite::Database.class_eval do
+      def target_dir
+        return './spec/src/' if ENV.key? "test"
+        './tmp'
+      end
+    end
+
+    tmp = "./tmp/#{params[:file_name]}"
+    File.write(tmp, body)
+    CsvToSqlite::CsvToSQLite.new([tmp]).run
+    sql_body = File.read('./tmp/data.sqlite3')
+
+    render body: sql_body, content_type: 'application/octet-stream'
+  end
+
   def show_as_html
     # images made during conversion (e.g. images in PDF files) are put in the
     # cache directory, so the same cache code in cache_attachments above will
diff --git a/config/routes.rb b/config/routes.rb
index ed94afd31..7f5aa1471 100644
--- a/config/routes.rb
+++ b/config/routes.rb
@@ -110,6 +110,10 @@
         :as => :similar_request,
         :via => :get
 
+  match '/request/:id/response/:incoming_message_id/attach/sqlite/:part/*file_name' => 'attachments#show_as_sqlite',
+        :format => false,
+        :via => :get
+
   match '/request/:id/response/:incoming_message_id/attach/html/:part/*file_name' => 'attachments#show_as_html',
         :format => false,
         :as => :get_attachment_as_html,

commit cfa3bfcd2022b45f2bfe76e69a332957e689f762
Author: Gareth Rees <gareth@>
Date:   Wed May 4 19:33:02 2022 +0100

    Use correct mime type for cached CSV attachments
    
    Currently they fall back to application/octet-stream in
    AttachmentsController#content_type

diff --git a/lib/alaveteli_file_types.rb b/lib/alaveteli_file_types.rb
index ae23ffc9f..744270254 100644
--- a/lib/alaveteli_file_types.rb
+++ b/lib/alaveteli_file_types.rb
@@ -2,6 +2,7 @@ class AlaveteliFileTypes
   # To add an image, create a file with appropriate name corresponding to the
   # mime type in app/assets/images/content_type/ e.g. icon_image_tiff_large.png
   FileExtensionToMimeType = {
+    'csv' => 'text/csv',
     "txt" => 'text/plain',
     "pdf" => 'application/pdf',
     "rtf" => 'application/rtf',
```

I just tried two WDTK CSVs ([example](https://lite.datasette.io/?csv=https://www.whatdotheyknow.com/request/879309/response/2085303/attach/3/FOI887719925%20FOI%20response.csv]) and both resulted in a Datasette error:

```
Traceback (most recent call last):
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 234, in __step
    result = coro.throw(exc)
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 500, in eval_code_async
    await CodeRunner(
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 353, in run_async
    await coroutine
  File "<exec>", line 53, in <module>
  File "/lib/python3.10/site-packages/pyodide/http.py", line 231, in pyfetch
    url, await _jsfetch(url, to_js(kwargs, dict_converter=Object.fromEntries))
  File "/lib/python3.10/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup
    future.result()
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
JsException: TypeError: Failed to fetch
```

Perhaps we need to apply cfa3bfcd2022b45f2bfe76e69a332957e689f762 from the diff above to make this work.

**Comment by mdeuk** [comment]
> Not sure if there's anything weird going on with how we're responding to the HTTP request that would cause the failure?

We don't appear to be passing the header `access-control-allow-origin: *` - [which is required here](https://github.com/simonw/datasette-lite/#loading-csv-data). I assume we'll need a sysadmin ticket?

**Comment by garethrees** [comment]
> We don't appear to be passing the header `access-control-allow-origin: *`

Doh, RTFM Gareth. AIUI we can do that in Rails on a per-action basis. Don't know if there are security implications.

**Comment by WilliamWDTK** [comment]
Updated prevalence of file types (according to searches of the format `https://www.whatdotheyknow.com/search/filetype:EXTENSION/all`)

I can't remember the exact method, but here I'm just scrolling to the last page of results and seeing what the count ends up  as. This may affect the values, as the count on the first page doesn't always match that on the last. Of course, this is the count of requests that have an attachment of that type, so requests with multiple attachments of one type will only count for one, and a request with attachments of multiple types will count as one for each type present.

| Extension | Count (about…) | Note | Example | Current Icon | Suggested icon improvement | Previewable? | Preview suggestion |
| :-: | :-: | :-: | :-: | :-: | :-: | :-: | :-: |
| [`csv`](https://www.whatdotheyknow.com/search/filetype:csv/all) | 160 (+112) | I think these might sometimes end up as `.csv.txt`, but I'm not sure how to find those… (see https://github.com/mysociety/alaveteli/issues/6480) | [This response](https://www.whatdotheyknow.com/request/811981/response/1939641/attach/3/FOI%20IAT%2000217%20Response.csv) to [this request](https://www.whatdotheyknow.com/request/top_10_most_popular_library_book_51#incoming-1939641) | ![Question mark icon](https://www.whatdotheyknow.com/assets/content_type/icon_unknown-9a0163c0192d34e1cd6b1cdc4709330444f95927ccfbdfb0618f1890ee19e855.png) (source) | Change to like that for `.xls`, but with `CSV` instead of `X` | No | *(insert suggestion here)* |
| [`txt`](https://www.whatdotheyknow.com/search/filetype:txt/all) | 8600 (+600) | This mostly seems to duplicate the request email | - | ![Lines of text icon](https://www.whatdotheyknow.com/assets/content_type/icon_text_plain_large-14bf3e96b9aea4ec489578c293c67fa6d8daff5d25ca8e925ba3aae41d250907.png) (source) | Perhaps add `TXT`? | Yes/no *(please select)* | *(insert suggestion here)* |
| [`xls`](https://www.whatdotheyknow.com/search/filetype:xls/all) | 10021 (+321) | - | - | ![Spreadsheet icon with X](https://www.whatdotheyknow.com/assets/content_type/icon_application_vnd.ms-excel_large-ff1588d24eb713a459bc0650509fbef069aea4633514dc26c85dbc234b8360e3.png) [(source)](https://github.com/mysociety/whatdotheyknow-theme/blob/master/app/assets/images/icon_application_vnd.ms-excel_large.png) | I don't think we need to distinguish between `.xls` and `.xlsx` | Yes/no *(please select)* | *(insert suggestion here)* |
| [`xlsx`](https://www.whatdotheyknow.com/search/filetype:xlsx/all) | 19000 (+2000) | - | - | ![Spreadsheet icon with X](https://www.whatdotheyknow.com/assets/content_type/icon_application_vnd.openxmlformats-officedocument.spreadsheetml.sheet_large-ff1588d24eb713a459bc0650509fbef069aea4633514dc26c85dbc234b8360e3.png) (source) | - | Yes/no *(please select)* | *(insert suggestion here)* |
| [`doc`](https://www.whatdotheyknow.com/search/filetype:doc/all) | 72000 (+5000) | - | - | ![Lines of text icon with W](https://www.whatdotheyknow.com/assets/content_type/icon_application_vnd.ms-word_large-a25bbd55418610620fdb2fe8a7ac5c671a32c4a2bf5caf5819d096c705d06b48.png) [(source)](https://github.com/mysociety/whatdotheyknow-theme/blob/master/app/assets/images/icon_application_vnd.ms-word_large.png) | - | Yes/no *(please select)* | *(insert suggestion here)* |
| [`docx`](https://www.whatdotheyknow.com/search/filetype:docx/all) | 36000 (+5000) | - | - | ![Lines of text icon with W](https://www.whatdotheyknow.com/assets/content_type/icon_application_vnd.openxmlformats-officedocument.wordprocessingml.document_large-a25bbd55418610620fdb2fe8a7ac5c671a32c4a2bf5caf5819d096c705d06b48.png) (source) | - | Yes/no *(please select)* | *(insert suggestion here)* |
| [`pdf`](https://www.whatdotheyknow.com/search/filetype:pdf/all) | 250000 (+30000) | - | - | ![Lines of text icon with PDF](https://www.whatdotheyknow.com/assets/content_type/icon_application_pdf_large-be89fb9d4a6183f530c1ddb3a6ecdff038786b22c32a2b7de9115a56dbb05dea.png) [(source)](https://github.com/mysociety/whatdotheyknow-theme/blob/master/app/assets/images/icon_application_pdf_large.png) | - | Yes/no *(please select)* | *(insert suggestion here)* |
| [`xml`](https://www.whatdotheyknow.com/search/filetype:xml/all) | 24 (+0) | - | [This unit diagram file (almost 9 MB)](https://www.whatdotheyknow.com/request/852234/response/2041290/attach/2/SAT%20Unit%20Diagrams.xml) in response to [this request](https://www.whatdotheyknow.com/request/unit_diagrams_may_2022#incoming-2041290) or [this one in some unknown format](https://www.whatdotheyknow.com/request/722652/response/1722424/attach/3/BCC%20Council%20houses.shp.xml) in response to [this other request](https://www.whatdotheyknow.com/request/building_heights_trees_administr_2#incoming-1722424) | ![Question mark icon](https://www.whatdotheyknow.com/assets/content_type/icon_unknown-9a0163c0192d34e1cd6b1cdc4709330444f95927ccfbdfb0618f1890ee19e855.png) (source) | Perhaps make it like that for `.html`, but put `XML` below the angled brackets, rather than `HTML` | Yes/no *(please select)* | *(insert suggestion here)* |
| [`jpg`](https://www.whatdotheyknow.com/search/filetype:jpg/all) | 50000 (+10000) | - | - | ![Mountain with sun icon](https://www.whatdotheyknow.com/assets/content_type/icon_image_jpeg_large-b39f2c1e6d477aa6c95baf7b8660be034222924f79b65dccabd1dfef8d94dea4.png) (source) | Include the extension below the mountains? | Yes/no *(please select)* | *(insert suggestion here)* |
| [`png`](https://www.whatdotheyknow.com/search/filetype:png/all) | 40000 (+11000) | - | - | ![Mountain with sun icon](https://www.whatdotheyknow.com/assets/content_type/icon_image_png_large-b39f2c1e6d477aa6c95baf7b8660be034222924f79b65dccabd1dfef8d94dea4.png) (source) | Include the extension below the mountains? | Yes/no *(please select)* | *(insert suggestion here)* |
| [`switch`](https://www.whatdotheyknow.com/search/filetype:switch/all) | 235 (+44) | *Our favourite!* | - | ![Binary digits icon (1101 0010 1011)](https://www.whatdotheyknow.com/assets/content_type/icon_application_octet-stream_large-984999d87061d0e884dd4364d237b5f74f5df91ba832382ebccc779889baee68.png) [(source)](https://github.com/mysociety/whatdotheyknow-theme/blob/master/app/assets/images/icon_application_octet-stream_large.png) | An icon with a padlocked envelope? *Or a frowning face(!)* | Yes/no *(please select)* | *(insert suggestion here)* |
| [`mp3`](https://www.whatdotheyknow.com/search/filetype:mp3/all) | 10 (+0) | - | [This recording](https://www.whatdotheyknow.com/request/486286/response/1162756/attach/8/TRAIN%20WELCOME%20ABOARD.mp3) from [this request](https://www.whatdotheyknow.com/request/latest_announcements_for_buses_a#incoming-1162756) | ![Question mark icon](https://www.whatdotheyknow.com/assets/content_type/icon_unknown-9a0163c0192d34e1cd6b1cdc4709330444f95927ccfbdfb0618f1890ee19e855.png) (source) | Soundwave? | Yes/no *(please select)* | *(insert suggestion here)* |
| [`mp4`](https://www.whatdotheyknow.com/search/filetype:mp4/all) | 1 (+0) | - | [This 8MB video demonstrating how to update the TTK app (railway ticketing) on a smartphone](https://www.whatdotheyknow.com/request/519843/response/1252631/attach/2/How%20to%20update%20the%20TTK%20App.mp4) in response to [this request to LNER](https://www.whatdotheyknow.com/request/ticket_issuing_systems_training#incoming-1252631) | ![Question mark icon](https://www.whatdotheyknow.com/assets/content_type/icon_unknown-9a0163c0192d34e1cd6b1cdc4709330444f95927ccfbdfb0618f1890ee19e855.png) (source) | Camcorder icon, video casette or a [clapperboard](https://en.wikipedia.org/wiki/Clapperboard)? | Yes/no *(please select)* | *(insert suggestion here)* |
| [`wav`](https://www.whatdotheyknow.com/search/filetype:wav/all) | 5 (+2) | - | [This announcement fragment](https://www.whatdotheyknow.com/request/801654/response/1939202/attach/2/ANN%20804.wav) released in response to [this request to SE Trains Limited](https://www.whatdotheyknow.com/request/on_board_announcements_4#incoming-1939202) | ![Question mark icon](https://www.whatdotheyknow.com/assets/content_type/icon_unknown-9a0163c0192d34e1cd6b1cdc4709330444f95927ccfbdfb0618f1890ee19e855.png) (source) | Soundwave? | Yes/no *(please select)* | *(insert suggestion here)* |
| [`zip`](https://www.whatdotheyknow.com/search/filetype:zip/all) | 2006 (+106) | - | [This ZIP (7.6MB)](https://www.whatdotheyknow.com/request/801654/response/1931232/attach/2/High%20Speed%20WAV%20Files.zip) released in [response to the same request as above](https://www.whatdotheyknow.com/request/on_board_announcements_4#incoming-1931232) | ![Checquer representing zip teeth icon](https://www.whatdotheyknow.com/assets/content_type/icon_application_zip_large-cb58455fd99a740a86fb7fbf0cbd4437db350987c7149dfd086cf466cf73fe9b.png) [(source)](https://github.com/mysociety/whatdotheyknow-theme/blob/master/app/assets/images/icon_application_zip_large.png) | Indicate with text `ZIP` | Yes/no *(please select)* | *(insert suggestion here)* |
| [`gz`](https://www.whatdotheyknow.com/search/filetype:gz/all) | 1 (+0) | - | [This file](https://www.whatdotheyknow.com/request/3150/response/9576/attach/2/21st%201st20M.gz) in response to [this request for web server access logs](https://www.whatdotheyknow.com/request/web_server_access_logs#incoming-9576) | ![Question mark icon](https://www.whatdotheyknow.com/assets/content_type/icon_unknown-9a0163c0192d34e1cd6b1cdc4709330444f95927ccfbdfb0618f1890ee19e855.png) (source) | Like `.zip`, but with text `GZ`? | Yes/no *(please select)* | *(insert suggestion here)* |
| [`html`](https://www.whatdotheyknow.com/search/filetype:html/all) | 4983 (+483) | - | - | ![Angled bracket with HTML icon](https://www.whatdotheyknow.com/assets/content_type/icon_text_html_large-26837468ac3ebf9be6e0b6ed6bfdfe573def7c889fd99e06fbc784c823b63076.png) (source) | Yes/no *(please select)* | *(insert suggestion here)* |
| [`tif`](https://www.whatdotheyknow.com/search/filetype:tif/all) | 348 (+6) | - | [This diagram of a concourse in Gateshead](https://www.whatdotheyknow.com/request/812693/response/1939986/attach/2/822%20108AC.tif) released in response to [this request](https://www.whatdotheyknow.com/request/asbestos_reports_and_architectur#incoming-1939986) | ![Mountain with sun icon with TIFF](https://www.whatdotheyknow.com/assets/content_type/icon_image_tiff_large-f2414ad6fd3de39e5e6839af2796fadf94ed3adbf7d0525042056277a8876386.png) (source) | Yes/no *(please select)* | *(insert suggestion here)* |
| [`odp`](https://www.whatdotheyknow.com/search/filetype:odp/all) | 3 (+2) | - | [This governance management structure diagram](https://www.whatdotheyknow.com/request/437702/response/1062608/attach/3/Governance%20Management%20Structure.odp) from [this request](https://www.whatdotheyknow.com/request/organisational_structure_for_the_8#incoming-1062608) | ![Question mark icon](https://www.whatdotheyknow.com/assets/content_type/icon_unknown-9a0163c0192d34e1cd6b1cdc4709330444f95927ccfbdfb0618f1890ee19e855.png) (source) | Like `.ppt`/`.pptx` but with text `ODP` | Yes/no *(please select)* | *(insert suggestion here)* |
| [`odt`](https://www.whatdotheyknow.com/search/filetype:odt/all) | 558 (+198) | - | - | ![Question mark icon](https://www.whatdotheyknow.com/assets/content_type/icon_unknown-9a0163c0192d34e1cd6b1cdc4709330444f95927ccfbdfb0618f1890ee19e855.png) (source) | Like `.doc`/`.docx` with `ODT` instead of `W`? | Yes/no *(please select)* | *(insert suggestion here)* |
| [`ods`](https://www.whatdotheyknow.com/search/filetype:ods/all) | 56 (+7) | - | - | ![Question mark icon](https://www.whatdotheyknow.com/assets/content_type/icon_unknown-9a0163c0192d34e1cd6b1cdc4709330444f95927ccfbdfb0618f1890ee19e855.png) (source) | Like `.xls`/`.xlsx` with `ODS` instead of `X`? | Yes/no *(please select)* | *(insert suggestion here)* |
| [`rar`](https://www.whatdotheyknow.com/search/filetype:rar/all) | 4 (+0) | - | [This file](https://www.whatdotheyknow.com/request/126875/response/308367/attach/2/ICO%20Retention%20and%20Disposal%20Schedule%20v1%202.rar) released in response to [this request to the ICO](https://www.whatdotheyknow.com/request/ico_polociy_and_procedures_for_r#incoming-308367) | ![Question mark icon](https://www.whatdotheyknow.com/assets/content_type/icon_unknown-9a0163c0192d34e1cd6b1cdc4709330444f95927ccfbdfb0618f1890ee19e855.png) (source) | Like with `.zip`, but with `RAR` text | Yes/no *(please select)* | *(insert suggestion here)* |
| [`ppt`](https://www.whatdotheyknow.com/search/filetype:ppt/all) | 245 (+3) | - | - | ![Slide screen and stand with play symbol icon](https://www.whatdotheyknow.com/assets/content_type/icon_application_vnd.ms-powerpoint_large-501193190ff5e702bfeb248f2e84795641e7707593c621d9bbd51e746764e487.png) [(source)](https://github.com/mysociety/whatdotheyknow-theme/blob/master/app/assets/images/icon_application_vnd.ms-powerpoint_large.png) | Add text `PPT` | Yes/no *(please select)* | *(insert suggestion here)* |
| [`pptx`](https://www.whatdotheyknow.com/search/filetype:pptx/all) | 332 (+37) | - | - | ![Slide screen and stand with play symbol icon](https://www.whatdotheyknow.com/assets/content_type/icon_application_vnd.openxmlformats-officedocument.presentationml.presentation_large-501193190ff5e702bfeb248f2e84795641e7707593c621d9bbd51e746764e487.png) (source) | Add text `PPT` | Yes/no *(please select)* | *(insert suggestion here)* |
| [`rtf`](https://www.whatdotheyknow.com/search/filetype:rtf/all) | 1649 (+249) | - | [This request](https://www.whatdotheyknow.com/request/pol_branch_makeup#incoming-2039371) | ![Question mark icon](https://www.whatdotheyknow.com/assets/content_type/icon_unknown-9a0163c0192d34e1cd6b1cdc4709330444f95927ccfbdfb0618f1890ee19e855.png) (source) | Should be text lines? Thought I saw that icon in the code… | Yes/no *(please select)* | *(insert suggestion here)* |
| [`pages`](https://www.whatdotheyknow.com/search/filetype:pages/all) | 1 (+0) | - | [This request](https://www.whatdotheyknow.com/request/2021_minutes_2#incoming-1983783) | ![Question mark icon](https://www.whatdotheyknow.com/assets/content_type/icon_unknown-9a0163c0192d34e1cd6b1cdc4709330444f95927ccfbdfb0618f1890ee19e855.png) (source) | Should be text lines, perhaps. | No | Neither Google nor Microsoft previewers work, though I notice if I try to open it, I can access a preview image (![preview](https://user-images.githubusercontent.com/99501342/169704619-45c4f30a-1166-4074-928c-f6fdf195ad61.jpg)) |

**Comment by HelenWDTK** [comment]
+1 csv files are likely to become more common following recent ICO guidance to authorities.

**Comment by garethrees** [comment]
Looks like CSV is previewable in Google Docs Viewer with some degree of success.

* **Good:** [Response](https://www.whatdotheyknow.com/request/expenditure_payments_to_supplier_2#incoming-2425145) -> [Preview](https://docs.google.com/viewer?url=https://www.whatdotheyknow.com/request/1022278/response/2425145/attach/2/FOI%20Request%20Payments%20over%20500%20June%20Aug%2022.csv?cookie_passthrough=1&embedded=true)
* **Not great:** [Response](https://www.whatdotheyknow.com/request/top_10_most_popular_library_book_51#incoming-1939641) -> [Preview](https://docs.google.com/viewer?url=https://www.whatdotheyknow.com/request/811981/response/1939641/attach/3/FOI%20IAT%2000217%20Response.csv?cookie_passthrough=1&embedded=true)

**Comment by garethrees** [comment]
This is desirable, but unlikely to be worked on in the next 12 months so closing for now.

**Comment by garethrees** [comment]
https://blog.appsignal.com/2025/08/13/extend-activestorage-for-ruby-on-rails-with-custom-previewers.html
