### ISSUE TITLE
automated appeals to ICO

### ISSUE THREAD

**Issue by confirmordeny** [mysociety/alaveteli#703]
I know this could be contentious but the suggestion is to automate appeals to the ICO in the same way  as the site currently deals with internal review requests and related correspondence.

This would expose the ICO's (FOI) regulatory activities to increased scrutiny.

**Comment by schlos** [comment]
+1

**Comment by garethrees** [comment]
I'm going to close this ticket as https://github.com/mysociety/alaveteli/issues/2819 has more discussion and is actually at the top of the list to be worked on. This ticket has a better title, so I'll update the new ticket's name to reflect that it is indeed the ticket that will add this feature.
