### ISSUE TITLE
Allow pro users to delete drafts

### ISSUE THREAD

**Issue by kingqueen3065** [mysociety/alaveteli#7049]
I have a number of draft requests at https://www.whatdotheyknow.com/alaveteli_pro/info_requests?alaveteli_pro_request_filter%5Bfilter%5D=draft&page=1 
Some of the drafts are from several years ago. 
I don't intend to send any of the draft requests. 
But there's no option to delete them. They just sit there, unsent, and my only options are to send, or to resave as a draft. 

I would like to be able to delete them.

**Comment by garethrees** [comment]
We can manually clear those out if you write to support (just use the in-app contact form).

Code will be something like:

```ruby
user = User.find(USER_ID)
user.draft_info_requests.destroy_all
user.draft_info_request_batches.destroy_all
```

**Comment by kingqueen3065** [comment]
The inability to delete drafts is still a pretty unimportant anomaly, ameliorated a little by the fact that one can use a "stagnant draft" request the next time one wants to send any FOI, by means of deleting the contents and authorities from the draft and simply filling in the new one as usual.

**Comment by HelenWDTK** [comment]
+1 I sometimes create drafts by accident that it would be good to be able to delete.

**Comment by garethrees** [comment]
This is desirable,  but unlikely to be worked on in the next 12 months so closing for now.
