### ISSUE TITLE
Authority subcategories

### ISSUE THREAD

**Issue by gbp** [mysociety/alaveteli#7051]
As an admin I would like the Categories feature to have subcategories, preferably at least 2 subcategories in order to categorize and display correctly and pedagogically for users

**Comment by garethrees** [comment]
> at least 2 subcategories

I think the current 2-level approach is as much as is necessary. So does Tufte:

> [It is] notable that the Feynman lectures (3 volumes) write about all of physics in 1800 pages, using only 2 levels of hierarchical headings: chapters and A-level heads in the text… Undergraduate Caltech physics is very complicated material, but it didn’t require an elaborate hierarchy to organize.
>
> – https://www.edwardtufte.com/bboard/q-and-a-fetch-msg?msg_id=0000hB

**Comment by FOIMonkey** [comment]
> Be good to see a concrete example of where subcategories would be useful.

Parish Council Listings. 

We list over 6000 town and parish councils, and these are currently in one category. I have tagged the councils by their parent district. There are 251 districts with parish councils - too many to neatly list separately. Some districts already have [a lot of councils](https://www.whatdotheyknow.com/body?tag=parent_mapit%3A2260) in them, and there is name duplication, so it is hard to combine them. There are over 5000 potential councils left to add, which will make things worse.

The current set up doesn't fit well with the batch category picker. It's much more likely a user would want to ask all the parish councils in eg South Cambs, then any other type of grouping, but there is no good way to present this option to the user at the moment.
