### ISSUE TITLE
Ability to remove an in use category

### ISSUE THREAD

**Issue by gbp** [mysociety/alaveteli#7052]
As an admin I would like to be able to delete a category with a even if it is in use, perhaps with a browser popup "are you sure you want to delete"? and that the authorities which had that category are moved to another unlisted category to later be re-categorized

**Comment by garethrees** [comment]
Categories _can_ be destroyed?

<img width="679" alt="Screenshot 2022-05-27 at 16 29 28" src="https://user-images.githubusercontent.com/282788/170730975-f0955e81-2d1e-4886-ae19-386e79fb72cd.png">

**Comment by garethrees** [comment]
More that the tag can't be modified once created and has bodies assigned.

![Screenshot 2022-06-16 at 12 45 18](https://user-images.githubusercontent.com/282788/174062942-a634cb1e-1a27-479c-a042-14da5d035f7f.png)
