### ISSUE TITLE
Reduce the carbon footprint of Alaveteli by reducing amount of email sent.

### ISSUE THREAD

**Issue by FOIMonkey** [mysociety/alaveteli#7055]
This [blog post](https://www.mysociety.org/2022/05/27/scope-3-emissions-and-remote-teams/) led me to this [guide](https://www.mysociety.org/files/2021/03/Working-from-home-sustainably-a-guide-from-mySociety-1.pdf) which has a section in it about the climate impact of sending short pointless emails.

Alaveteli sites generate a lot of emails, not just to authorities, but also to users and admins. We should see if all these are needed or if some can be eliminated eg 
- request classification prompts on auto acknowledgements 
- someone has updated the status of your request emails on requests that are more than a few years old.

**Comment by garethrees** [comment]
Related to #4603.

**Comment by FOIMonkey** [comment]
Another thing that we could do is to roll out the email digest feature of Pro more widely, so that users are only getting one email a day.

**Comment by HelenWDTK** [comment]
+1 to this. We send far too many emails, and these generate a considerable percentage of the support mail we deal with.

**Comment by garethrees** [comment]
This is unlikely to be worked on in the next 12 months so closing for now.
