### ISSUE TITLE
Render multiple newlines in outgoing message as paragraphs not linebreaks

### ISSUE THREAD

**Issue by equivalentideas** [mysociety/alaveteli#707]
The request items are getting structured as a single paragraph with `<br>`'s rather than as multiple paragraphs. for example: 

    <p>Dear Department of Immigration and Citizenship,<br>     <br>     Pursuant to the Freedom of Information Act 1982 (Cth) I request the<br>     following document:<br>     <br>     The most current register of Client Service Officers trained and<br>     accredited in the use of force and restraints within the<br>     Immigration Detention Network.<br>     <br>     To assist your agency in locating this information, the register is<br>     referred to in the document 'Immigration Detention Centre, Use of<br>     force, Policy and Procedure' at paragraph 3.17 which states: "the<br>     Senior Operations Manager/Operations Manager/CSM will maintain an<br>     up to date register of CSOs trained and accredited in the use of<br>     force and restraints."</p>

rather than:

    <p>Dear Department of Immigration and Citizenship</p>
    <p>Pursuant to the Freedom of Information Act 1982 (Cth) I request the following document:</p>
    <p>The most current register of Client Service Officers trained and accredited in the use of force and restraints within the Immigration Detention Network.</p>
    <p>To assist your agency in locating this information, the register is referred to in the document 'Immigration Detention Centre, Use of force, Policy and Procedure' at paragraph 3.17 which states: "the Senior Operations Manager/Operations Manager/CSM will maintain an up to date register of CSOs trained and accredited in the use of force and restraints."</p>

**Comment by garethrees** [comment]
> I personally like single \n becoming a <br>, two or more \n being a paragraph separator.

We're using `simple_format` in outgoing messages as of https://github.com/mysociety/alaveteli/commit/1a0626aea04455bd19a31b5f63fe0473b8465f9b, which does exactly that.
