### ISSUE TITLE
Make messages taggable

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#7074]
Requests (in other words correspondence threads) are taggable and there is a ticket for making those tags, and the tagging system, public at https://github.com/mysociety/alaveteli/issues/2302

Some things we might want to tag will relate to a specific message. 

One could get even more specific, it may be useful to relate a tag to specific text, or a specific attachment.

**Comment by garethrees** [comment]
> One could get even more specific, it may be useful to relate a tag to specific text, or a specific attachment.

Attachment is possible given we have an `FoiAttachment` record per attachment, though we have no admin UI for these at the momemt.

I can't imagine how we'd tag a specific piece of text, so I don't think it's worth ticketing unless there are several important use cases.

Extract to separate issues if/when necessary as this will be closed by https://github.com/mysociety/alaveteli/pull/7075.
