### ISSUE TITLE
Improve promotion of option of rate-cap removal and Pro service to relevant users

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#7083]
A valuable user making great use of WhatDoTheyKnow wrote to the support team today to say:

> I can only make 10 requests per 24 hour period, therefore I have also been making my requests through e-mail to help me reach my target faster. 

As one of our aims is to get as many FOI requests made via our service as possible hearing about these requests going off-site is disappointing, but it is useful feedback we might be able to act on. We immediately removed the rate cap on their account and pointed them to the Pro service. 

It looks as if we should already be proactively promoting the option of rate cap removal and Pro when the rate cap is reached:

```
<p><%= _("You have hit the rate limit on new requests. Users are ordinarily " \
	       "limited to {{max_requests_per_user_per_day}} requests in any " \
	       "rolling 24-hour period. You will be able to make another request " \
	       "in {{can_make_another_request}}.",
	     :max_requests_per_user_per_day => AlaveteliConfiguration::max_requests_per_user_per_day,
	     :can_make_another_request => distance_of_time_in_words(
      Time.zone.now, @next_request_permitted_at)) %></p>

<p><%= _("There is a limit on the number of requests you can make in a day, " \
	        "because we don’t want public authorities to be bombarded with " \
	        "large numbers of inappropriate requests. If you feel you have a " \
	        "good reason to ask for the limit to be lifted in your case, " \
	        "please <a href='{{help_contact_path}}'>get in touch</a>.",
	     :help_contact_path => help_contact_path) %></p>

<% if feature_enabled?(:alaveteli_pro) %>
  <p>
    <%= _('<strong>Journalist, Academic or Power User?</strong> ' \
          '{{pro_site_link}} is an all-in-one FOI toolkit including ' \
          'everything you need to keep on top of complex FOI-driven ' \
          'investigations.',
          pro_site_link: link_to(pro_site_name, account_request_index_path)) %>

```

https://github.com/mysociety/alaveteli/blob/a27a28ef18e8c23f2757272d0629ec0c2f705799/app/views/user/rate_limited.html.erb

Related:

https://github.com/mysociety/alaveteli/issues/6789   More structured way of requesting rate cap removal #6789 

That ticket mentions a "contact us" link on the rate cap reached message.

**Comment by garethrees** [comment]
I don't think there's a massive amount we can add here
