### ISSUE TITLE
Export public bodies assoicated by tags with public body category

### ISSUE THREAD

**Issue by gbp** [mysociety/alaveteli#7086]
As an admin I would like to be able to export separate lists of authorities with the given tags for each public body category as separate CSV or get from read API.

**Comment by RichardTaylor** [comment]
Possible duplicate of #6442 but perhaps not as I suspect this ticket is just for a list of names of public bodies, and perhaps URLs / URL slugs and  #6442  is for all the fields that are in the all authorities CSV download.

**Comment by garethrees** [comment]
This was intended as a mechanism for managing tags and categories, so closing as duplicate of https://github.com/mysociety/alaveteli/issues/6442
