### ISSUE TITLE
Reduce repeated alerts  

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#7089]
Repeats within an email alert:

* If a request thread matches more than one search term, don't include multiple links to the same request in the alert. 

Repeats over different email alerts:

We do want alerts, and a repeated pointer to a request, when action takes place on the request. We could reduce the set of events which prompt alerts. 

* Make it so a resend of a message by an admin doesn't prompt an alert  (This would specifically help the WDTK admin team, as when we do a resend following an error/bounce we then get an alert the next day apparently triggered by the resend). 

Related:

* https://github.com/mysociety/alaveteli/issues/5433
* https://github.com/mysociety/alaveteli/issues/2733

**Comment by FOIMonkey** [comment]
+1 It's annoying to get repeated alerts for delivery issues that we've already fixed. Fixing this would also help with inbox zero.

**Comment by RichardTaylor** [comment]
Does us re-sending a message on a thread prompt another delivery issue alert? If it does perhaps it shouldn't.

**Comment by RichardTaylor** [comment]
I deleted a comment I made here as I was accidentally just restating the suggestion already made above:

>Make it so a resend of a message by an admin doesn't prompt an alert
