### ISSUE TITLE
Make prominance icon for normal requests on admin pages green

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#7095]
Currently the coloured icons indicating prominence of requests on admin pages are:

* normal - black and white / grey
* requester_only - yellow
* hidden - red

I have repeatedly found myself initially assuming black and white means "greyed out" / "not public", which is not the case. 

I think green for normal would be more intuitive for me.

**Comment by garethrees** [comment]
Closing this as we've been running as is for quite a while now and I think it's working pretty well generally.

> normal - black and white / grey

Just to clarify, "normal" has no background "circle". The icon only gets the background when it's in a non-default state.

Grey is backpage.

Also considering something like https://github.com/mysociety/alaveteli/issues/7565, so trying to minimise where we use lots of colour elements.
