### ISSUE TITLE
Calling PublicBody#expire_requests causes platform stability issue

### ISSUE THREAD

**Issue by gbp** [mysociety/alaveteli#7101]
Just had a issue where most of our WDTK passenger processes were tied up and weren't able to response to web traffic.

Which root cause is due to calling `PublicBody#expire_requests`

This happens for at least two (maybe more?) occasions.
1. `PublicBody#url_name` is changed
2. `CensorRule` applicable to a public body's requests is created/updated/destroyed

In absence of #1240 we should ensure this works without blocking the passenger processes.

Initial attempt at fixing this is at https://github.com/mysociety/alaveteli/pull/6967

**Comment by RichardTaylor** [comment]
Noting that today's issue related to adding/editing a body-wide censor rule to a body with lots of requests - https://github.com/mysociety/whatdotheyknow-private/issues/20#issuecomment-1154038699

A previous similar feeling issue arose when renaming a set of authorities which had a reasonable number of requests made to them. This was in relation to name changes on Welsh County Councils. See https://github.com/mysociety/whatdotheyknow-theme/issues/1131 and https://github.com/mysociety/whatdotheyknow-theme/issues/1132  

Perhaps the fix here will address the issue in both cases?

**Comment by garethrees** [comment]
Noting that there's a bunch of different implementations for essentially the same thing across different models, so  we should think about this from the point of view of coalescing them into a common `Reindexable` concern (https://github.com/mysociety/alaveteli/issues/6931).
