### ISSUE TITLE
Sensitive content warning

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#7106]
Ability to insert a warning prior to showing sensitive content. 

Sensitive could mean potentially upsetting, or potentially harmful. 

Suggested text for a warning:
>We've noted this might be sensitive content, are you sure you want to see it? 

Some websites have per-user-account, or per session, settings which enable selecting an option to eg. "view sensitive content".

Warning could be triggered by a per-request, or per-message tag. 
Tags could be specific to particular types of sensitive content, enabling tailored warnings including links to relevant advice or support.  

Consider:
* How can we keep information which is behind a sensitive content warning accessible to search engines?
* How can we apply such a warning to attachments 

A low-tech minimal implementation could be via a special annotation, one which appears at the top of the page, and which one would generally have to scroll down past to reach the material in question. We have an existing ticket for special annotations: https://github.com/mysociety/alaveteli/issues/34 the discussion there covers tag and keyword/phrase triggered annotations. 

There is some limited history already of admins on WhatDoTheyKnow using existing standard annotations to include links to relevant advice or support on threads. 

[I'm just noting, and developing the idea for, an issue raised on Slack]

**Comment by garethrees** [comment]
I think this is mostly just a special case of #6912 (which is a form of #34).

The new idea in this issue is "**are you sure you want to see it?**".

I think we could just hook this off request tags, and if a request is tagged `sensitive` then render an overlayed generic "sensitive content" warning and button.

If we want to say more about it, we'd do so via #6912 or #34.

**Comment by garethrees** [comment]
We can now do this via https://github.com/mysociety/alaveteli/issues/7771.
