### ISSUE TITLE
Suggest a campaigning action to a user making a request to a body not subject to FOI

### ISSUE THREAD

**Issue by confirmordeny** [mysociety/alaveteli#7112]
If a user makes a request to a body not subject to FOI (tag: foi_no) then in my view it is likely that the person thinks the body should be subject to FOI. It might be good to have a prompt after submitting such a request  to write to a politician or start a petition to get the body added to FOI legislation.

**Comment by garethrees** [comment]
We kind of already do this, in that we show a note based on `foi_no` and link to a help page.

![Screenshot 2022-06-21 at 09 27 11](https://user-images.githubusercontent.com/282788/174753957-3ef14e5e-c2f8-48bb-8adb-9af7f42930e9.png)

With https://github.com/mysociety/alaveteli/issues/6912 we can give this a bit more prominence. I think the best thing to do then is link to a specific `foi_no`-based help page.

**Comment by confirmordeny** [comment]
Thank you. The current text is informative but it doesn't prompt the user to take a campaigning action.

**Comment by confirmordeny** [comment]
We now have tag-based notes so this can be done without any code change. That means it is closed for the purposes of this repo.
