### ISSUE TITLE
Body list displays oddly when Authority name is not added for all locales

### ISSUE THREAD

**Issue by FOIMonkey** [mysociety/alaveteli#7132]
See https://www.whatdotheyknow.com/cy/body/list/all

My best guess is that this is because we have bodies where a Welsh translation of the name hasn't been added, but it is not possible to check this, as I can't tell which authorities these are meant to be.
![screen](https://user-images.githubusercontent.com/11962965/177004835-0f8c454e-3932-4e08-85b6-adb899c0d275.png)

**Comment by mdeuk** [comment]
I can reproduce this issue.

As an example:
![image](https://user-images.githubusercontent.com/249418/177008745-841160ed-e6cd-492c-9875-a2fc27b89ee2.png)
…if we take the second and third entries here, the respective HTML is a little unusual, as the url_name isn't being rendered in the hyperlink either.

```
<div class="body_listing">
  <div class="head body-listing__header">
    <a href="/cy/body/body"></a>
  </div>
  <div class="desc body-listing__description">
  </div>
  <div class="bottomline body-listing__request-count">
    4 cais.
  </div>

</div>
```

```
<div class="body_listing">
  <div class="head body-listing__header">
    <a href="/cy/body/101_medical_practice_troon">101 Medical Practice, Troon</a>
  </div>
  <div class="desc body-listing__description">
        This practice closed in 2018.
      <br>
          Wedi darfod.
  </div>
  <div class="bottomline body-listing__request-count">
    1 cais.
  </div>

</div>
```

It's notable that the body shown, 64551, doesn't have a Welsh translation - so I wonder if this a variant of #3134 / #5084 making an appearance.

**Comment by FOIMonkey** [comment]
It looks like this is already noted at https://github.com/mysociety/whatdotheyknow-theme/issues/1123 so I'll close this

**Comment by FOIMonkey** [comment]
Actually, that's slightly different, though probably related.

**Comment by garethrees** [comment]
> The problem here is that a `cy` translation record exists for these authorities, but all its attributes are empty string (so "blank", rather than "NULL"). That means that we don't fall back to the EN translation.
>
> – https://github.com/mysociety/whatdotheyknow-theme/issues/1123#issuecomment-1108630730

**Comment by mdeuk** [comment]
The bodies affected by this are:
```52935
52942
91691
91712
92021
92137
92190
92192
111163
111164
111165
111167
111171
111175
111179
111185
111191
```

A sample of this set shows a common theme, in that the bulk of them appear to have been imports from a CSV file - but that doesn't appear to be _**the cause**_ itself, as there are a good number of other bodies (e.g. the 1111 range) which were also CSV imports and don't appear to be problematic.

Curious, and curiouser. 🕵️
