### ISSUE TITLE
Finer control over embargo options on a per-message, or set of messages, basis

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#7179]
We had a case where a user wanted to re-embargo the latest response on a thread but only had the option to re-embargo a whole thread. 

Idea:

* Ability to "publish existing messages on this thread", which then leaves any further incoming messages embargoed (for x time).

We don't really want re-embargoing to be an option at all - #6321 -  but if it ever was to happen in an exceptional case ideally the material removed from public view would be minimised so the embargo would only be applied to a specific message. 

Exceptional cases could be dealt with via the standard requester_only setting for messages.

**Comment by RichardTaylor** [comment]
I think this is probably introducing too much complexity, but it's worth noting it may have helped in one case.

**Comment by garethrees** [comment]
Yeah I don't think there's been a massive demand for this and I think it would get really complicated and generate lots of admin work when users get it wrong.

**Comment by RichardTaylor** [comment]
> Ability to "publish existing messages on this thread", which then leaves any further incoming messages embargoed (for x time).

On WhatDoTheyKnow we've had a second use-case for this. 

A user included sensitive material in their request, which we wanted to redact. 

Exceptionally we wanted to review incoming responses to ensure censor rules had worked before publishing due to the sensitivity of the material.

**Comment by RichardTaylor** [comment]
We have now had another case on WhatDoTheyKnow where we've made a thread requester_only because we want to moderate responses. 

There are two related issues being considered on this thread:

i/ Embargo privacy settings under the control of a pro user
ii/ Access settings for threads/messages under the control of site admins

I've started a separate ticket focused on non-pro use, where the publication decision would be in the hands of site-admins:

* https://github.com/mysociety/alaveteli/issues/7557

**Comment by garethrees** [comment]
Closing as there's no real desire to do this at present.
