### ISSUE TITLE
Describe request tag changes as request tag changes rather than merely an "edit" on a request's public event log 

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#7189]
Currently request tag changes are logged on the public event log as an event_type of "edit". 

Ideally the type of edit would be shown ie. "tags edited". 

eg. 

https://www.whatdotheyknow.com/details/request/statistics_of_how_many_tickets_h

Reason for acting:

* Some users can be concerned by unexplained "edits" to requests.

**Comment by mdeuk** [comment]
Agreed - this is a bit of a nuisance for GDPR requests, as there are a couple of different types of event which will all show in the event log as `edit`, requiring explanation each time.

I think something like `tag_added`, `tag_set`, or `tag_edited` (as you've suggested) might be a useful descriptor.

**Comment by garethrees** [comment]
For technical reasons I think it would be easier to keep it as `edit` but then have some way of displaying the modified fields for the public view (but not the before/after values):

|  id | event_type | event_details          |         created_at         |  described_state  |      last_described_at     |  calculated_state |    link   |
|:---:|:----------:|------------------------|:--------------------------:|:-----------------:|:--------------------------:|:-----------------:|:---------:|
| 100 | sent       |                        | 2022-06-20 00:12:51 +0100  | waiting_response  | 2022-06-20 00:12:51 +0100  | waiting_response  | outgoing  |
| 123 | edit       | tag_string, prominence | 2022-07-23 19:21:13 +0100  |                   |                            |                   |           |

**Comment by mdeuk** [comment]
> For technical reasons I think it would be easier to keep it as `edit` but then have some way of displaying the modified fields for the public view (but not the before/after values):

I'm not opposed to this, although it does feel slightly 'clunky'. Anything is an improvement over what we have just now though.

**A possibly related question:** would this allow changes made by  `InfoRequest.stop_new_responses_on_old_requests` to have a more useful indicator in the public event log? I know we'd need to change the code there, but hypothetically, I'm wondering if  this is an enabler.

Currently they are also just shown as `edit`, which presents a potentially misleading view to users, as it gives indication that a change has been made to the request - whereas, it's merely a change behind the scenes to reduce the possibility of spam.

**Comment by garethrees** [comment]
IDK, would have to think about all that in much more detail.
