### ISSUE TITLE
Request count on Alaveteli.org is out-of-date

### ISSUE THREAD

**Issue by mdeuk** [mysociety/alaveteli#7190]
@FOIMonkey has very helpfully noted that there are now well over **one million** transparency requests on Alaveteli powered sites around the world. This is worth noting.

**Comment by mdeuk** [comment]
This was completed in #7191, bc4fb09dd21e887ded3583f3fc3b0d4df1027783.

**Comment by garethrees** [comment]
https://www.mysociety.org/2022/08/31/more-than-a-million-public-foi-requests-have-been-made-through-alaveteli-sites/ 🎉
