### ISSUE TITLE
Bring some web logs into Alaveteli and provide easier access to them, and perhaps publish some statistics

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#7192]
Reasons:

* On WhatDoTheyKnow we often get asked for download statistics for material following a data-breach. While such data won't directly show how widely the material has been distributed it might help.  We'd want IP address data to analyse this and distinguish between search engines and others - which raises data protection questions. 

* We could show some view count data on request pages / next to attachments (typically these would be very low)

* We could show lists of requests eg. "most viewed this week" and "most viewed this year for this body".   (Often these are not great uses of the site). 

I don't think there is actually anything here which it makes sense to do at the moment. I think we should consider it though, hence this ticket. 

Related:

* https://github.com/mysociety/alaveteli/pull/6822 (which was turned off following data protection concerns https://github.com/mysociety/whatdotheyknow-theme/issues/1203#issuecomment-1136989453 )
*

**Comment by garethrees** [comment]
Related to https://github.com/mysociety/whatdotheyknow-theme/issues/1379.

I'm going to close this as I can't see us ever implementing through the specific mechanism of ingesting server logs (though, we do do this with mail logs).

I'd rather start with the outcomes we're after (e.g. view counts) and then decide on the technicalities of doing so if we're convinced the outcome is a good idea.
