### ISSUE TITLE
Classifying a request waiting_clarification after sending a clarification message triggers an unnecessary reminder email

### ISSUE THREAD

**Issue by FOIMonkey** [mysociety/alaveteli#7197]
A user reported that they'd sent two clarification messages by mistake due to receiving duplicate reminders from the system. This seems to have been triggered by the fact that they marked to request as waiting_clarification after they had provided clarification. 

@WilliamWDTK thinks there might already be a ticket for this somewhere, but I can't find one.

Possibly #6133 or #6662

**Comment by WilliamWDTK** [comment]
Just to note that we've had another message today from a user in a similar situation, who was confused about continuing to receive messages.

**Comment by WilliamWDTK** [comment]
Another user has contacted us about this issue.

**Comment by garethrees** [comment]
This is desirable, but unlikely to be worked on in the next 12 months so closing for now.
