### ISSUE TITLE
More options for rate capping

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#7207]
* As well as a per day cap should there be a per week/month cap too?
* Should we be able to set the rate cap on a per-user basis, so eg. have the ability to cap a specific user at 1 request per day/week

We have had a number of cases on WhatDoTheyKnow where people have been making requests up to the daily limit every day for many days.

Uses for this may be rare, and would need to be linked to policies on running the service.

**Comment by garethrees** [comment]
We now do this for comments via https://github.com/mysociety/alaveteli/pull/7602. Would be resolved by #7620, so closing in favour of #7620
