### ISSUE TITLE
Promote active bodies over those tagged defunct in search results

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#721]
- [ ] Currently active bodies ought be promoted over those tagged defunct in search results. 
- [x] Those bodies marked "defunct" should be marked "defunct" in the search results. 
- [x] The defunct tag currently prevents the "make a Freedom of Information request.." button appear. Perhaps instead of the button it should explain "you cannot make a Freedom of Information request as this body has been marked defunct" or similar.

**Comment by garethrees** [comment]
Renamed to reflect outstanding issue.
