### ISSUE TITLE
Admin change history linking to incorrect user

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/alaveteli#7231]
If you look at the [test quango](https://www.whatdotheyknow.com/admin/bodies/2), you can see version 1 and 2 were made by a user called `francis` in 2007 and 2008.  This username is linked, but to a user with that URL name that was created in 2011.

I don't think this should happen, but I'm not sure if anything can be done about it.

**Comment by garethrees** [comment]
I imagine this should link to user ID 1, but I don't know why only `francis` was recorded as the username.

Closing this as a wontfix as it likely only affects a handful of records on a handful of very old alavetelis.

**Comment by mdeuk** [comment]
> Closing this as a wontfix as it likely only affects a handful of records on a handful of very old alavetelis.

It happens on new installs as well - but, I don't think it is massively consequential, as I'd imagine it is coming from the sample data which would never be used in production.
