### ISSUE TITLE
Rendering notes based on tag in Alaveteli

### ISSUE THREAD

**Issue by lucascumsille** [mysociety/alaveteli#7240]
TL;DR is that we (Transparency) probably need some design help for integrating our new generalised notes system into the public view of Alaveteli. @gbp is away this week but will lead coordination on this when he's back w/c 22nd August.

Expecting this to be in the order of day or two of work.

See [concept doc](https://docs.google.com/document/d/1MEcZTk0a_Bjub2vKG3efi-f83sjWGU154Y1_Q4PnPRU/edit#heading=h.kez93fsraqpr) for more info.

**Comment by lucascumsille** [comment]
https://docs.google.com/document/d/1MEcZTk0a_Bjub2vKG3efi-f83sjWGU154Y1_Q4PnPRU/edit#heading=h.23lv2wpjvv0o

Places to work on:

- http://0.0.0.0:3000/en/body/ago
-

**Comment by lucascumsille** [comment]
@garethrees and @gbp 

For the notes in the authority type, I thought of the following options:

Optio
<img width="1037" alt="Screenshot 2022-08-26 at 08 23 20" src="https://user-images.githubusercontent.com/13790153/186851277-b98cb843-06ed-4056-91d0-df211eb50b00.png">
n 1: Include only the notes box on the page. No further changes.

Pretty much copy what I did here: https://github.com/mysociety/alaveteli/issues/6920#issuecomment-1228108459

Option 2: Box styling for all major components:

<img width="726" alt="Screenshot 2022-08-26 at 08 45 00" src="https://user-images.githubusercontent.com/13790153/186851451-129ab7d0-54d4-4d2f-842b-acfb901142e7.png">

Note:
Covert the element `<div class="authority__header__stats">2 requests</div>` into a title inside the request box.

Option 3: Keep current styling
<img width="726" alt="Screenshot 2022-08-26 at 08 38 56" src="https://user-images.githubusercontent.com/13790153/186851515-b4e4719a-24ca-4907-b963-e1948711b7e8.png">

I think the easier to scan is option 2 and the request count is more visible. It doesn't require major changes to the markup.

**Comment by garethrees** [comment]
Couple of notes that we just chatted about in standup:

* I don't think we want to use the "correspondence bubble" style for things that aren't exchanges between citizen and authority; We do have some existing styling for body notes when you go through to [make a request](https://www.whatdotheyknow.com/new/aberdeen_inspired) (the white box with green top border).
* While I agree the request list could be improved, again I'm not sure we want to reuse the "correspondence bubble" style and I think it's a little orthogonal to improving the note styling
* Notes should be at the top on both body pages and request pages
* Styling of individual notes looks great – dividing line is good
* Not sure where the blue `Note 1` boxes will come from, as notes are currently just a single text/html attribute

**Comment by garethrees** [comment]
> Places to work on

Also the new request page: http://0.0.0.0:3000/en/new/ago

**Comment by lucascumsille** [comment]
Thanks for the feedback @garethrees I'll come up with something and share it.

**Comment by lucascumsille** [comment]
@garethrees let me know if something like this is more suitable

Option 1
![Image](https://user-images.githubusercontent.com/13790153/186892946-d8ae298d-b9e3-4203-a829-40907f80fed5.png)

Option 2
![Image](https://user-images.githubusercontent.com/13790153/186892947-ae642cee-d407-4b7f-8f41-bf4a428c7a8e.png)

**Comment by garethrees** [comment]
> let me know if something like this is more suitable

Nice, I think this is better in that it's at least somewhat differentiated from the correspondence bubbles, though the single top-border does make it feel a little close still. I think the "NOTES" title helps make it clearer that it's not part of the correspondence.

> I could give a background colour to the whole section.

Might be worth trying. This has to work with _all_ Alaveteli themes – not just WDTK – and ideally without _requiring_ custom styling. Could also have a go with a border on all sides of the element.

I'm not sure about the zebra-striping effect (the blue middle note); feels quite disjointed? The previous version seems a bit more coherent in the way it renders each note.

> As an alternative so it looks more like a "post it" 

I wasn't actually thinking of being so literal about the post it, but I just came across https://mentormate.com/blog/css-postit-note/! Given the size I don't think we'd want it quite as vibrant as that though!

**Comment by lucascumsille** [comment]
> I wasn't actually thinking of being so literal about the post it, but I just came across https://mentormate.com/blog/css-postit-note/! Given the size I don't think we'd want it quite as vibrant as that though!

I had the same thought, I love the looks, but I don't think it would work with the amount of content we could have. I thought about implementing this and create a post it for each one of the notes, but it might use a lot of space.

I do think we should include a name for the section like I did on "option 1" ("NOTES"). It provides some context to new users.

> Could also have a go with a border on all sides of the element.

I tried with borders, but I noticed that we don't use much borders across the website and page. Except with forms fields, so I got rid of them to keep consistency across the styling. However not completely against adding it. 

>I'm not sure about the zebra-striping effect (the blue middle note); feels quite disjointed? The previous version seems a bit more coherent in the way it renders each note.

In option 1 I added a subtle version of that of the zebra striping, because I noticed that on option 2, the colour made the second note stand out more than the rest.

Thanks for all the feedback @garethrees, I'll work on those changes then =)

**Comment by lucascumsille** [comment]
Hey @garethrees 

Here are some screenshots of how it would look like in each of the pages. I ended up adding a background color so it looks different to users interactions and more like system messages.

### New Request

![Image](https://user-images.githubusercontent.com/13790153/187179581-c2f6a0c6-2994-41a2-aa14-271df2412e87.png)

### Authority page

![Image](https://user-images.githubusercontent.com/13790153/187179648-90e7f377-b7e0-4b8b-bf66-2adcb355a792.png)

### Request page

![Image](https://user-images.githubusercontent.com/13790153/187179796-d806fa65-6876-4811-b923-296e7d9647ed.png)

A couple of things:

- Do you want me to include a title for the section like in the first option "Notes"? It might not be necessary, but it could give some context for new users.

- In the WDTK theme there is a wrapper element `to_public_body_notes` that the styling seems a bit off. Are we using this for any other content? otherwise I'd like to get rid of that styling.

### Current state `to_public_body_notes`
![Image](https://user-images.githubusercontent.com/13790153/187182470-bfeefa83-4377-4fc5-95f0-621bb126f503.png)

### Without styling state `to_public_body_notes`
![Image](https://user-images.githubusercontent.com/13790153/187182689-67fc8f2b-39c4-4840-bd24-289250aa6da1.png)

Let me know what you think and if there is any other changes you'd like to apply.

**Comment by garethrees** [comment]
Awww yeeaaa! This looks great! 🎯 

> Do you want me to include a title for the section like in the first option "Notes"? It might not be necessary, but it could give some context for new users.

We don't have a title now, so let's see how it goes without.

> In the WDTK theme there is a wrapper element `to_public_body_notes` that the styling seems a bit off. Are we using this for any other content? otherwise I'd like to get rid of that styling(Without styling).

I agree the styling looks weird in the "Current state `to_public_body_notes`" screenshot, and I agree with getting rid of it if we can. I don't know off hand where else it's used, so take a look around. If it ends up we use it elsewhere and it's too difficult to change, then don't worry too much about it. What you've put together is still an improvement on what we have now. ✨
