### ISSUE TITLE
Add link to body admin page (and possibly public page) from change requests

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/alaveteli#7260]
Sometimes, when we receive a change request, I want to look at e.g. the body's history, like what changes it has undergone.  It would be good to have a direct link to the admin interface for this purpose.

**Comment by garethrees** [comment]
We already link to the edit form from the change request notification.

To avoid cluttering that email, would it be better if we had a quicker link to the public/admin pages similar to https://github.com/mysociety/alaveteli/pull/7241?:

![Screenshot 2022-09-01 at 15 41 53](https://user-images.githubusercontent.com/282788/187942612-4f064720-32d1-4818-ba85-1c328f583060.png)

(Eye links to public view; body name links to admin view)

**Comment by mdeuk** [comment]
> To avoid cluttering that email, would it be better if we had a quicker link to the public/admin pages similar to https://github.com/mysociety/alaveteli/pull/7241?

I like that idea - I'd be inlined to set a target so it opens in a new window / tab, meaning you can have both open side-by-side, but its probably not a deal breaker either way.

Alternatively, could we render the change log on the page itself, perhaps using an anchor so as to provide quick access? It seems like that might be a more intuitive workflow.

**Comment by garethrees** [comment]
> I'd be inlined to set a target so it opens in a new window / tab

Eep that's typically seen as [bad practice](https://css-tricks.com/use-target_blank/). It really frustrates _me_ when sites do  this. If I want a new tab I `cmd` + click.

> Alternatively, could we render the change log on the page itself, perhaps using an anchor so as to provide quick access

It's quite a busy page as is, but I can see the appeal. It's a more work than the two proposals above though, so less likely to have time found for it.

**Comment by mdeuk** [comment]
> Eep that's typically seen as [bad practice](https://css-tricks.com/use-target_blank/). It really frustrates _me_ when sites do this. If I want a new tab I `cmd` + click.

I generally agree - the [example here](https://css-tricks.com/use-target_blank/#aa-a-good-reason-the-user-is-working-on-something-on-the-page-that-might-be-lost-if-the-current-page-changed) is the scenario I'd be thinking of, but realistically, I'm agnostic on the 'solution'. 😃
