### ISSUE TITLE
Show tag based note on a page listing bodies with that tag

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#7304]
eg. at 

https://www.whatdotheyknow.com/body/list/cancer_alliance 

show the note associated with the tag `cancer_alliance `

This issue was mentioned at https://github.com/mysociety/alaveteli/issues/387#issuecomment-1186228863

**Comment by gbp** [comment]
This is planned, a duplicate of https://github.com/mysociety/alaveteli/issues/7255
