### ISSUE TITLE
Add a border to the green banners

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/alaveteli#7315]
When there are multiple (possibly only the case when out-of-country + an announcement?), it looks a bit confusing, so I think some sort of border might be good, or alternating colours.

**Comment by WilliamWDTK** [comment]
(I wasn't quite sure whether to call them announcements or not, I'm not sure whether the country one counts as an announcement.  Feel free to change the title.)

**Comment by FOIMonkey** [comment]
![2022-09-22](https://user-images.githubusercontent.com/11962965/191736184-a7a5edaa-4b4f-4582-bfb9-cf608780be90.png)

**Comment by garethrees** [comment]
Ah gotcha – yeah I think out-of-country + announcement is the only edge-case where this is possible.

Hacked this in via web inspector just to test and seems like it would work:

```css
  border-bottom: 1px solid green;
```

<img width="301" alt="Screenshot 2022-09-22 at 12 38 01" src="https://user-images.githubusercontent.com/282788/191736847-5aac3813-1c57-436d-b185-5243014aeb51.png">

**Comment by FOIMonkey** [comment]
I did the same and I think that looks better:
![2022-09-22 (1)](https://user-images.githubusercontent.com/11962965/191737916-cc24d7d6-6590-4be0-8a02-87b64e601c62.png)
