### ISSUE TITLE
Move display of prominence reason on incoming messages for admins to above the section showing the sender 

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#7338]
As shown in the screenshot the prominence reason on an incoming message is presented without a divider separating it from the message content. 

<img width="745" alt="Screenshot 2022-09-30 at 15 24 48" src="https://user-images.githubusercontent.com/547695/193291695-65eb62a8-5950-4c35-8000-7d18fcb458a2.png">

The treatment of an outgoing message is better as the prominence reason is separated from the message body:
<img width="744" alt="Screenshot 2022-09-30 at 15 29 39" src="https://user-images.githubusercontent.com/547695/193292793-321288b9-e665-4922-b34b-6dbd5c3e1a6e.png">

This only affects the admin display so it's not important, but consistency would be preferable. 

I don't know if this is a new issue.

**Comment by FOIMonkey** [comment]
I think this is a dupe of #7314

**Comment by RichardTaylor** [comment]
Closing in favour of https://github.com/mysociety/alaveteli/issues/7314 

Two recent reports of this issue makes me wonder if it has recently arisen.
