### ISSUE TITLE
Make substantive attachments more prominent and reduce the prominance of tiny image file attachments

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#7342]
Often substantive attachments are only accessible after clicking "show more". Ideas for making the substantive attachments more prominent:

* order attachments by size, descending
* put attachments with "response" in the file name at the top
* put small image files at the end of the list of attachments

<img width="322" alt="Screenshot 2022-10-01 at 14 09 33" src="https://user-images.githubusercontent.com/547695/193411193-6bfb7329-9031-412d-91ea-9fe80e6b08b8.png">

<img width="409" alt="Screenshot 2022-10-01 at 14 09 39" src="https://user-images.githubusercontent.com/547695/193411188-0cd6cd7e-ac80-409e-ab03-56c2043e6dc2.png">

Related: 

* https://github.com/mysociety/alaveteli/issues/6173

**Comment by FOIMonkey** [comment]
I think this is largely covered by #4773

**Comment by RichardTaylor** [comment]
Closing in favour of https://github.com/mysociety/alaveteli/issues/4773
