### ISSUE TITLE
Auto tag authorities that have received no/very few requests

### ISSUE THREAD

**Issue by FOIMonkey** [mysociety/alaveteli#7361]
Similar to the auto tagging of missing emails, this would enable us to suggest users make requests to these authorities and/or offer suggestions as to what they could ask for.

**Comment by FOIMonkey** [comment]
Related to #7362

**Comment by FOIMonkey** [comment]
1.  I think less than 5 makes sense for now, we can always up it later.
2. `not_many_requests` is perfect.
3. I'm fine ignoring embargoed requests. The chances of there being tons made to a tiny parish meeting somewhere is negligible, and it keep the appearance of any note consistent with what the average user/visitor can see.

**Comment by WilliamWDTK** [comment]
I'd agree with only counting public (non-embargoed, non-reduced-prominence) requests, such that the presence of the note is consistent with the body's public page.

Regarding number, do we have means/medians/etc for the number of public requests to bodies with which this could be compared?

**Comment by garethrees** [comment]
Potential source of good questions https://clairemiller.net/blog/2013/01/a-great-big-list-of-foi-ideas/

**Comment by garethrees** [comment]
FDS have a great list of suggested requests based on authority category https://fragdenstaat.de/hilfe/erste-anfrage/anfrage-ideen/
