### ISSUE TITLE
Don't show `missing_email` note on `defunct` bodies

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#7372]

**Comment by WilliamWDTK** [comment]
Or, don't apply the `missing_email` tag to `defunct` bodies.

**Comment by mdeuk** [comment]
> Or, don't apply the `missing_email` tag to `defunct` bodies.

@confirmordeny recently suggested that we could use a `defunct@<sitedomain>` email address for these entities, perhaps that would be a solution?

**Comment by gbp** [comment]
Deployed and ran `PublicBody.with_tag('missing_email').with_tag('defunct').each { |b| b.send :update_missing_email_tag }` to update the 6 bodies which had both tags.
