### ISSUE TITLE
Trap UK Border Agency & other non-team emails on Contact Us page

### ISSUE THREAD

**Issue by skenaja** [mysociety/alaveteli#74]
The WhatDoTheyKnow mailbox receives around 3-8 emails a month by UKBA applicants wanting help with their visa issues.

As part of the Contact Us page, before any message gets added, we should add various radio buttons to ask the user what they need help with.

The UKBA page could then redirect to a special support static page.

This could be extended for other common situations where people write to us when they really want to be writing to someone else.

**Comment by zarino** [comment]
Using `last_body` sounds totally magic. Would love to see that in action.

I worry that adding a radio button about visa applications actually *legitimises* the user in thinking we have *anything* to do with visa decisions. (Imagine: non native English speaker visits page, quickly scans down, spots what looks like a list of things the contact form can be used for, starts typing, sends message.)

Do the contact form messages intended for the UKBA follow any sort of pattern? Eg: Do they tend to mention the word "visa"? Could we detect that as the user types their message, and pop up a "Did you mean to do this?" message, just like we do for request titles and the "Similar requests" popup message?

**Comment by zarino** [comment]
We've had lots of really useful feedback on proposed copy for this page, here: https://docs.google.com/document/d/1W1eP7Xu4QZHsEyIX7yNfslDwKeAhMd1oWqONeI_b4XY/edit

So, thanks to everyone for that. I think I've got enough to get a first iteration of this deployed, then we can see whether it has an effect, and tweak further if required.

@crowbot – I spotted a `contact.cy.html.erb` file in whatdotheyknow-theme. I'm assuming we'll need someone to translate the English page to Welsh once it's ready?

**Comment by zarino** [comment]
Pull request here: https://github.com/mysociety/whatdotheyknow-theme/pull/323

I'll need some help from a developer (@lizconlan @garethrees @crowbot) to get it finished.

**Comment by lizconlan** [comment]
@zarino that would be me! I've assigned both of us, erm, because it's a new feature so I can! (and this will be the first time we've used it on purpose rather than by mistake 😀)

**Comment by garethrees** [comment]
Fixed by https://github.com/mysociety/whatdotheyknow-theme/pull/323
