### ISSUE TITLE
 Improve guessing heuristics for holding pen emails: missing punctuation

### ISSUE THREAD

**Issue by hsenag** [mysociety/alaveteli#740]
Try to parse the address by inserting hyphens at the right character positions if not present - e.g. I've just dealt with two unrelated requests which had To addresses of the form

request-103521b891ac80@whatdotheyknow.com

See issue #15

**Comment by garethrees** [comment]
Just noting some example mis-typings that I was using to review #4974. I don't think that deals with all of them, but just adding for reference so that we can mop up any unhandled ones at a later date.

```
request-123-9e5760f9@example.com
request123-9e5760f9@example.com
request1239e5760f9@example.com

request=123=9e5760f9@example.com
request123=9e5760f9@example.com

request-123-9E5760f9@example.com

request-1-jwhbewiuxxxxxxxxxxxx@example.com

request-nope-9e5760f9@example.com
requestnope9e5760f9@example.com
request-9e5760f9@example.com
request9e5760f9@example.com
request-123@example.com
request123@example.com
```

This regexp [caught 9/13](http://rubular.com/r/nScK0fBAGa):

```ruby
/request\W?(\w+)\W?(\w{8}).*@/i
```
