### ISSUE TITLE
Verify email address given by non-logged-in users when using the contact form

### ISSUE THREAD

**Issue by FOIMonkey** [mysociety/alaveteli#7437]
At the moment anyone can use anyone else's email address when using the contact form, and AIUI, we don't currently verify this. This increases the risk of impersonation and the chance of a data breach occurring when responding to support mail.

Requiring those using the form to verify that they own/are in control of the email address would help mitigate this risk.

**Comment by RichardTaylor** [comment]
We could expand this to all public forms where we take the person's email address. 

Do we want to allow/encourage/enable anonymous contacts/reports? 

This isn't really far off requiring people to sign up to contact us via a form.  The difference would be we wouldn't require a password, and we wouldn't set up a profile, we'd still need a user account or something akin to it, at least temporarily.

**Comment by FOIMonkey** [comment]
Previously I've contacted companies via their form and on pressing submit, have been taken to a page that says to check my email for a link to click on to confirm my email address and send my query. I'd imagine that the workflow would work a bit like that.

It would of course be necessary to consider potential impacts on accessibility.

I had thought about appending a message with a warning to the top of messages from people who weren't logged in, as I've seen lots of public authorities do, but this seemed neater.

**Comment by WilliamWDTK** [comment]
In addition, I think it would be worth noting on reports where a reporter is the same as the requester, so that admins can tell more easily, without having to look and compare email addresses.

**Comment by WilliamWDTK** [comment]
This is possibly getting too far into hypotheticals, but a potential problem with email tokens is that someone could click it without necessarily knowing what it does, and then it would seem like the email address had been properly validated. I assume this is why some services still send a code that you have to input on the same page.
