### ISSUE TITLE
Ability to delete a request and "blackhole" further responses

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#7438]
On WhatDoTheyKnow we're considering, on data protection risk reduction grounds, deleting more non-FOI personal  correspondence rather than keeping it visible only to the requester. 

A concern is that responses to deleted threads will end up on the holding pen, and we'll have a new/expanded admin task of identifying and deleting them. 

Consider:

* Would we always want to "blackhole" responses to deleted requests?
* Do we need/want the ability to select between the bounce/holding-pen/blackhole options for a deleted request

Related:

*  #7414 
* https://github.com/mysociety/alaveteli/issues/7393

**Comment by HelenWDTK** [comment]
On a related note, we're considering starting to track thread deletions manually to enable these to be added to the transparency report. Ideally this would be recorded automatically in Alaveteli in some way.

**Comment by HelenWDTK** [comment]
We've had a refusal through today a request that we had to delete that has ended up in the holding pen.

**Comment by HelenWDTK** [comment]
+1 This happened again today. We had to delete a thread due to the presence of third party special category personal data in the outgoing message, and the authority responded, which ended up in the holding pen.

**Comment by RichardTaylor** [comment]
>Would we always want to "blackhole" responses to deleted requests?

The practice of deleting requests on data protection risk reduction grounds has now unfortunately extended to include a couple of FOI requests (we don't currently have the technical ability to delete the initial outgoing message from a thread). In one case we've passed a response on to a requester, which is something we wouldn't have been able to do if the response has been blackholed. 

The ticket covering enabling the deletion of the original message on the thread, which would enable us to delete material from a request, but continue to publish other elements of the correspondence on the thread is at https://github.com/mysociety/alaveteli/issues/7414
