### ISSUE TITLE
Ability to show a note on requests with a status of "error_message" or "requires_admin"

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#7441]
The automatically added "missing_email" tag enables a note to be added to bodies without an email address, encouraging users to find and suggest one. 

The "missing_email" tag doesn't help with finding addresses for bodies where a delivery error has been reported.  

https://www.whatdotheyknow.com/search/status:error_message

If we could add a note to requests with a status of "error_message" or "requires_admin" we could encourage users to help address the issues there. Often the issues are of a nature such that those outside the core team could help eg. obtaining information from strangely formatted documents, or finding a new email address. 

Considerations:

* While there is some potential to save admin time here, suggestions from the wider community are far from always helpful, and accurate. To some extent seeking more help results in either more admin work, or just prompts admin work by the core team. 
* We might not want to encourage others to review threads which have been marked for admin attention, as there might be issues which warrant immediate attention from the core team, that said more eyes on an issue might help understand it more quickly and prompt quicker action.

**Comment by FOIMonkey** [comment]
Interesting suggestion!

+1 for error_message - I think this could be helpful.

-1 for requires_admin - I'd not want to give more prominence to defamatory material or other problematic content, particularly if it were to be flagged over a weekend etc. I'd be open to changing my mind on that if we ever had escalating permissions, which meant that someone could easily fix some of these.

**Comment by RichardTaylor** [comment]
One interpretation of what was being proposed here was a "recent_bounce" tag for bodies, which would be cleared on a successful send, or email address update. 

If so, such tags could be added even if the bounce was on a private Pro request.
