### ISSUE TITLE
install-site.sh breaks for Alaveteli while copying storage.yml-example

### ISSUE THREAD

**Issue by gavinrozzi** [mysociety/alaveteli#7463]
Hi all. Trying to install Alaveteli using the install-site.sh script from this repo on Ubuntu 22.04. When I follow the steps to run the script, I receive the following message:

`+ cp config/storage.yml-example
cp: missing destination file operand after 'config/storage.yml-example'
Try 'cp --help' for more information.`

**Comment by garethrees** [comment]
https://github.com/mysociety/alaveteli/blob/152d22a2fae7fc3cc10b1ad17453ff710f49d289/script/install-as-user#L198-L199

Looks like a typo:

```diff
- cp config/storage.yml-example > config/storage.yml
+ cp config/storage.yml-example config/storage.yml
```

**Comment by gavinrozzi** [comment]
Thanks Gareth! Will give it a try.
