### ISSUE TITLE
Add a link to the tag page from the admin navbar

### ISSUE THREAD

**Issue by HelenWDTK** [mysociety/alaveteli#7466]
At the moment you have to follow the link from the authorities page to reach the tags page. We use this a lot to add notes, so it'd be nice to make this easier to find.

**Comment by garethrees** [comment]
IIRC we intentionally didn't add this – partly because it wasn't obvious where to put it, and partly because we figured it was easy enough to just navigate via other content – but I agree; I've been finding myself typing `/admin/tags` fairly frequently these days.

**Comment by garethrees** [comment]
Fixed by 8db57c4b5.
