### ISSUE TITLE
Improve wording around close and anonymise to ensure censor rules work

### ISSUE THREAD

**Issue by HelenWDTK** [mysociety/alaveteli#7495]
Censor rules are applied in the order that they are added. When pressing the close and anonymise button, a censor rule is added for the username, which is usually their first and last name. When processing right to erasure requests, we often add additional censor rules to remove variations on a user's name such as their surname or first name only. These can sometime render the censor rule for the full name ineffective.

It would be helpful to add some text to the close and anonymise warning box on the user page to highlight this. This could say something along the lines of: "If you wish to apply additional censor rules, for example to cover where someones title and surname has been used, this could make the automatic censor rule ineffective"

**Comment by garethrees** [comment]
How's this for a more generic version?

<img width="1048" alt="Screenshot 2023-01-05 at 09 27 19" src="https://user-images.githubusercontent.com/282788/210746587-6a01b01c-5f95-4de1-8255-371024b7806f.png">

We could also add to the C&A help for the specific case of faffing with firstname and surname given it's a frequent action, but perhaps knowing more generally about how the censor rules are applied make this case more obvious?

**Comment by HelenWDTK** [comment]
Looks great!
