### ISSUE TITLE
Make it clearer on body pages that Alaveteli is not the authority website

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#7517]
We had a recent example of someone making a request clearly thinking that WDTK is the authority website:

<img width="1077" alt="Screenshot 2023-01-16 at 09 25 07" src="https://user-images.githubusercontent.com/282788/212643360-02a439a1-00ee-48a1-b88a-0f7c958ee4b4.png">

This is what a first-time visitor would see when they viewed the above authority:

<img width="1111" alt="Screenshot 2023-01-16 at 09 23 03" src="https://user-images.githubusercontent.com/282788/212643189-d352f120-d5c5-47b4-9137-eef5633467e5.png">

We could make it much clearer that they're viewing a third-party public archive of FOI material.

We could do this for non-logged in visitors, and get rid of the additional material once logged in, or once logged in and a user has more than one FOI request (indicating they understand what's happening).

**Comment by HelenWDTK** [comment]
This would be great, as it is an issue that comes up reasonably frequently.

**Comment by RichardTaylor** [comment]
Duplicate of

* https://github.com/mysociety/alaveteli/issues/7102

**Comment by garethrees** [comment]
Duplicate of https://github.com/mysociety/alaveteli/issues/7102
