### ISSUE TITLE
Offer downloadable meta data relating to all requests on an installation

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#7534]
Offer everything available via the event history pages and /help/api as one big meta-data download. 

Include request links and titles. 

Enabling research, and integrations, and who knows what people might do with it...

See also

* https://www.whatdotheyknow.com/help/privacy#research
* https://github.com/mysociety/alaveteli/issues/6691

[Noted following correspondence to WDTK seeking such data]

**Comment by garethrees** [comment]
Incorporated in to and closing in favour of https://github.com/mysociety/alaveteli/issues/6691
