### ISSUE TITLE
Show date and author on notes

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#7543]
This could help remove ambiguity over who wrote a note (if it's from the public body, site operator, or a user). 

A date might assist with interpretation of a note. 

Reasons not to do this:

* Many notes are timeless - the date isn't relevant. 
* Having an old date on a note on a public body page could give the impression it's not up-to-date

The underlying issues here might be better dealt with by care over phrasing notes so it's clear who they are from, and when relevant, when they were written, however I'm raising this as an idea/option. 

Related:

* https://github.com/mysociety/alaveteli/issues/7279#issuecomment-1401207668

**Comment by garethrees** [comment]
> This could help remove ambiguity over who wrote a note

I don't think we'd show the author, as this isn't really a reliable concept. Many admins may edit a note over time. It ought to be clear that the note is by the site operator, but I that's a more general issue with is page https://github.com/mysociety/alaveteli/issues/7102.

Notes are designed in such a way that they're intended to be timeless / current. Comments / Annotation are for more temporal updates, though I appreciate we don't have these on body pages right now.

Closing this issue but noting it as a consideration in https://github.com/mysociety/alaveteli/issues/7102.
