### ISSUE TITLE
Ability to view initial request when replying to response

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/alaveteli#7546]
Apologies; if there's already a ticket for this please add this comment to it and delete this one, but the closest I found was #5441. 

A Twitter user says:

> When writing a reply to a response received to an FoI request, would it be possible to get the website to also display the original request? On a few occasions now I've had to reword questions because of a tendency of certain government departments to play silly buggers with anything they get sent and it would be useful to have that on the same screen when doing the rewording.

**Comment by garethrees** [comment]
Going to close as we'd consider this in https://github.com/mysociety/alaveteli/issues/5441, but thanks for raising – always good to have these specific cases recorded, as even if we close them we can still get back to them.
