### ISSUE TITLE
Ability to add tag and note, or annotation, to all requests made to-date by a user

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#7549]
The use-case for this, which comes up from time to time, is wanting to add a note to existing requests before making a username change. 

The need for this would be negated by https://github.com/mysociety/alaveteli/issues/285 

The ability to annotate all requests by a user was suggested at https://github.com/mysociety/alaveteli/issues/5434#issuecomment-848310144

**Comment by garethrees** [comment]
Closing in favour of https://github.com/mysociety/alaveteli/issues/285.
