### ISSUE TITLE
Ability to add an annotation without drawing attention to the annotation/thread

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#7550]
We sometimes want to add an annotation in the interests of running the service transparently, but don't want to draw undue attention to an issue. 

Adding an annotation "quietly" has been considered.  This might mean adding the annotation without triggering alerts or bumping a thread on body/user pages. 

Would the annotation still appear on the user page for the user who created it? An annotation appearing on the page for [the official user account for a service](https://github.com/mysociety/alaveteli/issues/6997), or a publicly known site admin, might negate the attempt to add the annotation quietly. 

We can add a note without triggering alerts or bumping a thread on body/user pages however an annotation is less prominent on the page so would be preferable in some circumstances.  

The option to add a note to the bottom of a page rather than the top might be another approach to this issue.

**Comment by RichardTaylor** [comment]
In discussions on this issue a suggestion has been made for a new setting for a request thread something like 

`no_bump` 

which would have the effect of no actions on the thread prompting the thread to come to the top of user or body pages and no alerts being generated in respect of the thread. 

Would we want requesters to not get alerts of new responses in such cases?

Related:  

* https://github.com/mysociety/whatdotheyknow-theme/issues/1464

**Comment by RichardTaylor** [comment]
`no_bump` could be applied to all suspended users' content.

**Comment by garethrees** [comment]
Related to https://github.com/mysociety/alaveteli/issues/2733.

**Comment by garethrees** [comment]
This is desirable, but unlikely to be worked on in the next 12 months so closing for now.
