### ISSUE TITLE
Option to show a note on a request at the bottom of the request page rather than the top

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#7551]
Not all notes need to be given the prominence associated with appearing at the top of a page. 

Idea spun out from

*  https://github.com/mysociety/alaveteli/issues/7550

**Comment by garethrees** [comment]
Going to close this in favour of https://github.com/mysociety/alaveteli/issues/7302. Issue as proposed seems like too much complexity for marginal gain.
