### ISSUE TITLE
An ActionView::Template::Error occurred in info_requests#new: missing interpolation argument "autority_name"

### ISSUE THREAD

**Issue by schlos** [mysociety/alaveteli#7606]
Error occurs when Pro user tries to access a new request deeplink with slug of a defunct authority, i.e. campaign deeplink. 
Example of a defunct body on IPZ:

https://imamopravoznati.org/alaveteli_pro/info_requests/new?public_body=agencija_za_investicije_i_konkurentnost_zagreb

Error from PagerDuty:

An ActionView::Template::Error occurred in info_requests#new:

  missing interpolation argument "autority_name" in {:authority_name=>"Agencija za investicije i konkurentnost, Zagreb"} ("Nažalost, \"{{autority_name}}\" je označen kao neaktivan, što znači da im više ne možemo podnositi zahtjeve. Možda ćete morati provjeriti je li njihove odgovornosti preuzelo drugo tijelo javne vlasti." given)
  lib/i18n_fixes.rb:34:in `block in gettext_interpolate'

-------------------------------
Request:
-------------------------------

  * URL        : https://imamopravoznati.org/alaveteli_pro/info_requests/new?public_body=agencija_za_investicije_i_konkurentnost_zagreb
  * HTTP Method: GET
  * IP address : [REDACTED]
  * Parameters : {"public_body"=>"agencija_za_investicije_i_konkurentnost_zagreb", "controller"=>"alaveteli_pro/info_requests", "action"=>"new"}
  * Timestamp  : 2022-04-14 22:11:30 +0200
  * Server : imamopravoznati.org
    * Rails root : /data/www/imamopravoznati.org/alaveteli
  * Process: 64643

-------------------------------
Session:
-------------------------------

  * session id: [FILTERED]
  * data: {"session_id"=>"[REDACTED]",
   "locale"=>"hr",
   "remember_me"=>false,
   "_csrf_token"=>"[REDACTED]",
   "user_id"=>7,
   "ttl"=>"2022-04-14T22:10:24.680+02:00",
   "post_redirect_token"=>"[REDACTED]"}

-------------------------------
Environment:
-------------------------------

  * GATEWAY_INTERFACE                                      : CGI/1.2
    * HTTP_ACCEPT                                            : text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
    * HTTP_ACCEPT_ENCODING                                   : gzip
    * HTTP_ACCEPT_LANGUAGE                                   : hr,en-GB;q=0.9,en-US;q=0.8,en;q=0.7
    * HTTP_CDN_LOOP                                          : cloudflare
    * HTTP_CF_CONNECTING_IP                                  : [REDACTED]
    * HTTP_CF_IPCOUNTRY                                      : HR
    * HTTP_CF_RAY                                            : [REDACTED]
    * HTTP_CF_VISITOR                                        : {"scheme":"https"}
    * HTTP_CONNECTION                                        : close
    * HTTP_COOKIE                                            : [REDACTED]
    * HTTP_DNT                                               : 1
    * HTTP_HOST                                              : imamopravoznati.org
    * HTTP_SEC_FETCH_DEST                                    : document

    * HTTP_SEC_FETCH_MODE                                    : navigate

    * HTTP_SEC_FETCH_SITE                                    : none
    * HTTP_SEC_FETCH_USER                                    : ?1
    * HTTP_SEC_GPC                                           : 1
    * HTTP_UPGRADE_INSECURE_REQUESTS                         : 1
    * HTTP_USER_AGENT                                        : Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.88 Safari/537.36
    * HTTP_VERSION                                           : HTTP/1.0

    * HTTP_X_ACCEL_MAPPING                                   : /var/www/imamopravoznati.org/alaveteli/cache/zips/production/download=/download

    * HTTP_X_FORWARDED_FOR                                   : [REDACTED]
    * HTTP_X_FORWARDED_PROTO                                 : https
    * HTTP_X_REAL_IP                                         : [REDACTED]
    * HTTP_X_SENDFILE_TYPE                                   : X-Accel-Redirect
    * ORIGINAL_FULLPATH                                      : /alaveteli_pro/info_requests/new?public_body=agencija_za_investicije_i_konkurentnost_zagreb
    * ORIGINAL_SCRIPT_NAME                                   :
    * PATH_INFO                                              : /alaveteli_pro/info_requests/new
    * QUERY_STRING                                           : public_body=agencija_za_investicije_i_konkurentnost_zagreb
    * REMOTE_ADDR                                            : 127.0.0.1

    * REQUEST_METHOD                                         : GET
    * REQUEST_PATH                                           : /alaveteli_pro/info_requests/new
    * REQUEST_URI                                            : /alaveteli_pro/info_requests/new?public_body=agencija_za_investicije_i_konkurentnost_zagreb
    * ROUTES_47434986658420_SCRIPT_NAME                      :
    * SCRIPT_NAME                                            :
    * SERVER_NAME                                            : imamopravoznati.org
    * SERVER_PORT                                            : 80
    * SERVER_PROTOCOL                                        : HTTP/1.1

    * SERVER_SOFTWARE                                        : thin 1.8.1 codename Infinite Smoothie
    * action_controller.instance                             : #<AlaveteliPro::InfoRequestsController:0x00005648a752ec70>
    * action_dispatch.authenticated_encrypted_cookie_salt    : authenticated encrypted cookie
    * action_dispatch.backtrace_cleaner                      : #<Rails::BacktraceCleaner:0x00005648a2fc28f8>
    * action_dispatch.content_security_policy                :
    * action_dispatch.content_security_policy_nonce_generator:
    * action_dispatch.content_security_policy_report_only    : false
    * action_dispatch.cookies                                : #<ActionDispatch::Cookies::CookieJar:0x00005648a7525170>
    * action_dispatch.cookies_digest                         :
    * action_dispatch.cookies_rotations                      : #<ActiveSupport::Messages::RotationConfiguration:0x00005648a1795000>
    * action_dispatch.cookies_serializer                     : hybrid
    * action_dispatch.encrypted_cookie_cipher                :
    * action_dispatch.encrypted_cookie_salt                  : encrypted cookie
    * action_dispatch.encrypted_signed_cookie_salt           : signed encrypted cookie
    * action_dispatch.http_auth_salt                         : http authentication
    * action_dispatch.key_generator                          : #<ActiveSupport::CachingKeyGenerator:0x00005648a56034e0>
    * action_dispatch.logger                                 : #<ActiveSupport::Logger:0x00005648a3096108>
    * action_dispatch.parameter_filter                       : [:password]
    * action_dispatch.redirect_filter                        : []
    * action_dispatch.remote_ip                              : [REDACTED]
    * action_dispatch.request.content_type                   :
    * action_dispatch.request.formats                        : [#<Mime::Type:0x00005648a20c23d0 @synonyms=["application/xhtml+xml"], @symbol=:html, @string="text/html", @hash=1317882043423>]
    * action_dispatch.request.parameters                     : {"public_body"=>"agencija_za_investicije_i_konkurentnost_zagreb", "controller"=>"alaveteli_pro/info_requests", "action"=>"new"}
    * action_dispatch.request.path_parameters                : {:controller=>"alaveteli_pro/info_requests", :action=>"new"}
    * action_dispatch.request.query_parameters               : {"public_body"=>"agencija_za_investicije_i_konkurentnost_zagreb"}
    * action_dispatch.request.request_parameters             : {}
    * action_dispatch.request.unsigned_session_cookie        : {[REDACTED]}
    * action_dispatch.request_id                             : 25becf66-3c2f-41e3-b155-233c99c8e090
    * action_dispatch.routes                                 : #<ActionDispatch::Routing::RouteSet:0x00005648a30f34e8>
    * action_dispatch.secret_key_base                        : 
    * action_dispatch.secret_token                           :
    * action_dispatch.show_detailed_exceptions               : false
    * action_dispatch.show_exceptions                        : true
    * action_dispatch.signed_cookie_digest                   :
    * action_dispatch.signed_cookie_salt                     : signed cookie
    * action_dispatch.use_authenticated_cookie_encryption    : false
    * async.callback                                         : #<Method: #<Thin::Connection:0x00005648a7564488 @signature=84590, @request=#<Thin::Request:0x00005648a75643c0 @parser=#<Thin::HttpParser:0x00005648a7564398>, @data=nil, @nparsed=1967, @body=#<StringIO:0x00005648a75642d0>, @env={"SERVER_SOFTWARE"=>"thin 1.8.1 codename Infinite Smoothie", "SERVER_NAME"=>"imamopravoznati.org", "rack.input"=>#<StringIO:0x00005648a75642d0>, "rack.version"=>[1, 0], "rack.errors"=>#<IO:/data/www/imamopravoznati.org/alaveteli/log/thin.3000.log>, "rack.multithread"=>false, "rack.multiprocess"=>false, "rack.run_once"=>false, "REQUEST_METHOD"=>"GET", "REQUEST_PATH"=>"/alaveteli_pro/info_requests/new", "PATH_INFO"=>"/alaveteli_pro/info_requests/new", "QUERY_STRING"=>"public_body=agencija_za_investicije_i_konkurentnost_zagreb", "REQUEST_URI"=>"/alaveteli_pro/info_requests/new?public_body=agencija_za_investicije_i_konkurentnost_zagreb", "HTTP_VERSION"=>"HTTP/1.0", "HTTP_HOST"=>"imamopravoznati.org", "HTTP_X_REAL_IP"=>"[REDACTED]", "HTTP_X_FORWARDED_FOR"=>"[REDACTED]", "HTTP_X_FORWARDED_PROTO"=>"https", "HTTP_X_SENDFILE_TYPE"=>"X-Accel-Redirect", "HTTP_X_ACCEL_MAPPING"=>"/var/www/imamopravoznati.org/alaveteli/cache/zips/production/download=/download", "HTTP_CONNECTION"=>"close", "HTTP_ACCEPT_ENCODING"=>"gzip", "HTTP_CF_IPCOUNTRY"=>"HR", "HTTP_CF_RAY"=>"[REDACTED]-ZAG", "HTTP_CF_VISITOR"=>"{\"scheme\":\"https\"}", "HTTP_DNT"=>"1", "HTTP_UPGRADE_INSECURE_REQUESTS"=>"1", "HTTP_USER_AGENT"=>"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.88 Safari/537.36", "HTTP_ACCEPT"=>"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9", "HTTP_SEC_GPC"=>"1", "HTTP_SEC_FETCH_SITE"=>"none", "HTTP_SEC_FETCH_MODE"=>"navigate", "HTTP_SEC_FETCH_USER"=>"?1", "HTTP_SEC_FETCH_DEST"=>"document", "HTTP_ACCEPT_LANGUAGE"=>"hr,en-GB;q=0.9,en-US;q=0.8,en;q=0.7", "HTTP_COOKIE"=>"_[REDACTED]", "HTTP_CF_CONNECTING_IP"=>"[REDACTED]", "HTTP_CDN_LOOP"=>"cloudflare", "GATEWAY_INTERFACE"=>"CGI/1.2", "SERVER_PORT"=>"80", "SERVER_PROTOCOL"=>"HTTP/1.1", "rack.url_scheme"=>"http", "SCRIPT_NAME"=>"", "REMOTE_ADDR"=>"127.0.0.1", "async.callback"=>#<Method: #<Thin::Connection:0x00005648a7564488 ...>.post_process>, "async.close"=>#<EventMachine::DefaultDeferrable:0x00005648a755eda8>, "action_dispatch.parameter_filter"=>[:password], "action_dispatch.redirect_filter"=>[], "action_dispatch.secret_token"=>nil, "action_dispatch.secret_key_base"=>"[REDACTED]", "action_dispatch.show_exceptions"=>true, "action_dispatch.show_detailed_exceptions"=>false, "action_dispatch.logger"=>#<ActiveSupport::Logger:0x00005648a3096108 @level=1, @progname=nil, @default_formatter=#<Logger::Formatter:0x00005648a3095a28 @datetime_format=nil>, @formatter=#<Logger::Formatter:0x00005648a4083b60 @datetime_format=nil, @thread_key="activesupport_tagged_logging_tags:47434994818480">, @logdev=#<Logger::LogDevice:0x00005648a3095988 @shift_period_suffix=nil, @shift_size=nil, @shift_age=nil, @filename=nil, @dev=#<File:/data/www/imamopravoznati.org/alaveteli/log/production.log>, @mon_owner=nil, @mon_count=0, @mon_mutex=#<Thread::Mutex:0x00005648a3095000>>, @local_levels=#<Concurrent::Map:0x00005648a3094df8 entries=0 default_proc=nil>>, "action_dispatch.backtrace_cleaner"=>#<Rails::BacktraceCleaner:0x00005648a2fc28f8 @filters=[#<Proc:0x00005648a2fc2380@/home/alaveteli/bundle/ruby/2.5.0/gems/railties-5.2.6/lib/rails/backtrace_cleaner.rb:16>, #<Proc:0x00005648a2fc2308@/home/alaveteli/bundle/ruby/2.5.0/gems/railties-5.2.6/lib/rails/backtrace_cleaner.rb:17>, #<Proc:0x00005648a2fc2128@/home/alaveteli/bundle/ruby/2.5.0/gems/railties-5.2.6/lib/rails/backtrace_cleaner.rb:18>, #<Proc:0x00005648a2fbf680@/home/alaveteli/bundle/ruby/2.5.0/gems/railties-5.2.6/lib/rails/backtrace_cleaner.rb:31>], @silencers=[#<Proc:0x00005648a2fbf568@/home/alaveteli/bundle/ruby/2.5.0/gems/railties-5.2.6/lib/rails/backtrace_cleaner.rb:21>], @root="/data/www/imamopravoznati.org/alaveteli/">, "action_dispatch.key_generator"=>#<ActiveSupport::CachingKeyGenerator:0x00005648a56034e0 @key_generator=#<ActiveSupport::KeyGenerator:0x00005648a5603508 @secret="[REDACTED]", @iterations=1000>, @cache_keys=#<Concurrent::Map:0x00005648a56034b8 entries=3 default_proc=nil>>, "action_dispatch.http_auth_salt"=>"http authentication", "action_dispatch.signed_cookie_salt"=>"signed cookie", "action_dispatch.encrypted_cookie_salt"=>"encrypted cookie", "action_dispatch.encrypted_signed_cookie_salt"=>"signed encrypted cookie", "action_dispatch.authenticated_encrypted_cookie_salt"=>"authenticated encrypted cookie", "action_dispatch.use_authenticated_cookie_encryption"=>false, "action_dispatch.encrypted_cookie_cipher"=>nil, "action_dispatch.signed_cookie_digest"=>nil, "action_dispatch.cookies_serializer"=>:hybrid, "action_dispatch.cookies_digest"=>nil, "action_dispatch.cookies_rotations"=>#<ActiveSupport::Messages::RotationConfiguration:0x00005648a1795000 @signed=[], @encrypted=[]>, "action_dispatch.content_security_policy"=>nil, "action_dispatch.content_security_policy_report_only"=>false, "action_dispatch.content_security_policy_nonce_generator"=>nil, "action_dispatch.routes"=>#<ActionDispatch::Routing::RouteSet:0x00005648a30f34e8>, "ROUTES_47434986658420_SCRIPT_NAME"=>"", "ORIGINAL_FULLPATH"=>"/alaveteli_pro/info_requests/new?public_body=agencija_za_investicije_i_konkurentnost_zagreb", "ORIGINAL_SCRIPT_NAME"=>"", "action_dispatch.request_id"=>"25becf66-3c2f-41e3-b155-233c99c8e090", "action_dispatch.remote_ip"=>#<ActionDispatch::RemoteIp::GetIp:0x00005648a75569c8 @req=#<ActionDispatch::Request:0x00005648a75569f0 @env={...}, @filtered_parameters=nil, @filtered_env=nil, @filtered_path=nil, @protocol=nil, @port=nil, @method=nil, @request_method=nil, @remote_ip=nil, @original_fullpath=nil, @fullpath=nil, @ip=nil>, @check_ip=false, @proxies=[#<IPAddr: IPv4:127.0.0.1/255.255.255.255>, #<IPAddr: IPv6:0000:0000:0000:0000:0000:0000:0000:0001/ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff>, #<IPAddr: IPv6:fc00:0000:0000:0000:0000:0000:0000:0000/fe00:0000:0000:0000:0000:0000:0000:0000>, #[REDACTED]>, "rack.session"=>#<ActionDispatch::Request::Session:0x00005648a753dc98 @by=#<ActionDispatch::Session::CookieStore:0x00005648a3268f58 @app=#<ActionDispatch::ContentSecurityPolicy::Middleware:0x00005648a3268fd0 @app=#<Rack::Head:0x00005648a3268ff8 @app=#<Rack::ConditionalGet:0x00005648a3269070 @app=#<Rack::ETag:0x00005648a32690c0 @app=#<Rack::TempfileReaper:0x00005648a32690e8 @app=#<ExceptionNotification::Rack:0x00005648a3309db8 @app=#<ActionDispatch::Routing::RouteSet:0x00005648a30f34e8>, @ignore_cascade_pass=true>>, @cache_control="max-age=0, private, must-revalidate", @no_cache_control="no-cache">>>>, @default_options={:path=>"/", :domain=>nil, :expire_after=>nil, :secure=>true, :httponly=>true, :defer=>false, :renew=>false}, @key="_wdtk_cookie_session", @cookie_only=true, @same_site=nil>, @req=#<ActionDispatch::Request:0x00005648a753dcc0 @env={...}, @filtered_parameters=nil, @filtered_env=nil, @filtered_path=nil, @protocol=nil, @port=nil, @method=nil, @request_method=nil, @remote_ip=nil, @original_fullpath=nil, @fullpath=nil, @ip=nil>, @delegate={"session_id"=>"2cbecf8d03fa96c1ee0e715f4bc1ec0d", "locale"=>"hr", "remember_me"=>false, "_csrf_token"=>"3XPuZsg/ysAKW0/5Ux0fQn1wO5CY6mI6AF1B47o4WJc=", "user_id"=>7, "ttl"=>"2022-04-14T22:10:24.680+02:00", "post_redirect_token"=>"hu8xlj8tg5hct6bzaqa"}, @loaded=true, @exists=true>, "rack.session.options"=>#<ActionDispatch::Request::Session::Options:0x00005648a753dc48 @by=#<ActionDispatch::Session::CookieStore:0x00005648a3268f58 @app=#<ActionDispatch::ContentSecurityPolicy::Middleware:0x00005648a3268fd0 @app=#<Rack::Head:0x00005648a3268ff8 @app=#<Rack::ConditionalGet:0x00005648a3269070 @app=#<Rack::ETag:0x00005648a32690c0 @app=#<Rack::TempfileReaper:0x00005648a32690e8 @app=#<ExceptionNotification::Rack:0x00005648a3309db8 @app=#<ActionDispatch::Routing::RouteSet:0x00005648a30f34e8>, @ignore_cascade_pass=true>>, @cache_control="max-age=0, private, must-revalidate", @no_cache_control="no-cache">>>>, @default_options={:path=>"/", :domain=>nil, :expire_after=>nil, :secure=>true, :httponly=>true, :defer=>false, :renew=>false}, @key="_wdtk_cookie_session", @cookie_only=true, @same_site=nil>, @delegate={:path=>"/", :domain=>nil, :expire_after=>nil, :secure=>true, :httponly=>true, :defer=>false, :renew=>false, :id=>"2cbecf8d03fa96c1ee0e715f4bc1ec0d"}>, "rack.tempfiles"=>[], "action_dispatch.request.path_parameters"=>{:controller=>"alaveteli_pro/info_requests", :action=>"new"}, "action_controller.instance"=>#<AlaveteliPro::InfoRequestsController:0x00005648a752ec70 @_action_has_layout=true, @_routes=nil, @_request=#<ActionDispatch::Request:0x00005648a753dae0 @env={...}, @filtered_parameters={"public_body"=>"agencija_za_investicije_i_konkurentnost_zagreb", "controller"=>"alaveteli_pro/info_requests", "action"=>"new"}, @filtered_env=nil, @filtered_path=nil, @protocol=nil, @port=nil, @method=nil, @request_method="GET", @remote_ip=nil, @original_fullpath=nil, @fullpath="/alaveteli_pro/info_requests/new?public_body=agencija_za_investicije_i_konkurentnost_zagreb", @ip=nil, @headers=#<ActionDispatch::Http::Headers:0x00005648a752c4e8 @req=#<ActionDispatch::Request:0x00005648a753dae0 ...>>, @variant=[]>, @_response=#<ActionDispatch::Response:0x00005648a752ee78 @mon_owner=nil, @mon_count=0, @mon_mutex=#<Thread::Mutex:0x00005648a752ee28>, @header={"Vary"=>"Cookie"}, @stream=#<ActionDispatch::Response::Buffer:0x00005648a752edd8 @response=#<ActionDispatch::Response:0x00005648a752ee78 ...>, @buf=[], @closed=false, @str_body=nil>, @status=200, @cv=#<MonitorMixin::ConditionVariable:0x00005648a752edb0 @monitor=#<ActionDispatch::Response:0x00005648a752ee78 ...>, @cond=#<Thread::ConditionVariable:0x00005648a752ed88>>, @committed=false, @sending=false, @sent=false, @cache_control={}, @request=#<ActionDispatch::Request:0x00005648a753dae0 @env={...}, @filtered_parameters={"public_body"=>"agencija_za_investicije_i_konkurentnost_zagreb", "controller"=>"alaveteli_pro/info_requests", "action"=>"new"}, @filtered_env=nil, @filtered_path=nil, @protocol=nil, @port=nil, @method=nil, @request_method="GET", @remote_ip=nil, @original_fullpath=nil, @fullpath="/alaveteli_pro/info_requests/new?public_body=agencija_za_investicije_i_konkurentnost_zagreb", @ip=nil, @headers=#<ActionDispatch::Http::Headers:0x00005648a752c4e8 @req=#<ActionDispatch::Request:0x00005648a753dae0 ...>>, @variant=[]>>, @_lookup_context=#<ActionView::LookupContext:0x00005648a752eb58 @details_key=#<Concurrent::Map:0x00005648a4317a98 entries=11 default_proc=nil>, @cache=true, @prefixes=["alaveteli_pro/info_requests", "alaveteli_pro/base", "application"], @rendered_format=:html, @details={:locale=>[:hr], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby]}, @view_paths=#<ActionView::PathSet:0x00005648a752e838 @paths=[#<ActionView::OptimizedFileSystemResolver:0x00005648a7526f98 @pattern=":prefix/:action{.:locale,}{.:formats,}{+:variants,}{.:handlers,}", @cache=#<ActionView::Resolver::Cache:0x5648a7526f70 keys=1 queries=0>, @path="/data/www/imamopravoznati.org/alaveteli/lib/themes/imamopravoznati-theme/lib/views">, #<ActionView::OptimizedFileSystemResolver:0x00005648a4076960 @pattern=":prefix/:action{.:locale,}{.:formats,}{+:variants,}{.:handlers,}", @cache=#<ActionView::Resolver::Cache:0x5648a4076938 keys=15 queries=0>, @path="/data/www/imamopravoznati.org/alaveteli/app/views">]>>, @_action_name="new", @_response_body=nil, @_params=<ActionController::Parameters {"public_body"=>"agencija_za_investicije_i_konkurentnost_zagreb", "controller"=>"alaveteli_pro/info_requests", "action"=>"new"} permitted: false>, @locales={:current=>"hr", :available=>["en"]}, @marked_for_same_origin_verification=true, @_config={}, @user=#<User id: 7, email: "[[REDACTED]](mailto:[REDACTED])", name: "Miroslav Schlossberg", hashed_password: "$2a$10$T4lzI6BYlam8DNxmCeU2ke/uFm1dHtYxjjaZnkYL/tS...", salt: nil, created_at: "2015-04-11 22:22:08", updated_at: "2021-08-13 08:34:31", email_confirmed: true, url_name: "miroslav_schlossberg", last_daily_track_email: "2019-10-12 02:15:25", ban_text: "", about_me: "", locale: "hr", email_bounced_at: nil, email_bounce_message: "", no_limit: true, receive_email_alerts: true, can_make_batch_requests: true, otp_enabled: false, otp_secret_key: nil, otp_counter: 1, confirmed_not_spam: true, comments_count: 470, info_requests_count: 444, track_things_count: 66, request_classifications_count: 2, public_body_change_requests_count: 33, info_request_batches_count: 5, daily_summary_hour: 8, daily_summary_minute: 26, closed_at: nil, address: nil, national_id_number: nil>, @in_pro_area=true, @_db_runtime=5.837306380271912, @_view_context_class=#<Class:0x00005648a9ecb970>, @_view_renderer=#<ActionView::Renderer:0x00005648a7437c18 @lookup_context=#<ActionView::LookupContext:0x00005648a752eb58 @details_key=#<Concurrent::Map:0x00005648a4317a98 entries=11 default_proc=nil>, @cache=true, @prefixes=["alaveteli_pro/info_requests", "alaveteli_pro/base", "application"], @rendered_format=:html, @details={:locale=>[:hr], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby]}, @view_paths=#<ActionView::PathSet:0x00005648a752e838 @paths=[#<ActionView::OptimizedFileSystemResolver:0x00005648a7526f98 @pattern=":prefix/:action{.:locale,}{.:formats,}{+:variants,}{.:handlers,}", @cache=#<ActionView::Resolver::Cache:0x5648a7526f70 keys=1 queries=0>, @path="/data/www/imamopravoznati.org/alaveteli/lib/themes/imamopravoznati-theme/lib/views">, #<ActionView::OptimizedFileSystemResolver:0x00005648a4076960 @pattern=":prefix/:action{.:locale,}{.:formats,}{+:variants,}{.:handlers,}", @cache=#<ActionView::Resolver::Cache:0x5648a4076938 keys=15 queries=0>, @path="/data/www/imamopravoznati.org/alaveteli/app/views">]>>>, @public_body=#<PublicBody id: 28308, version: 7, last_edit_editor: "administrator_miroslav", last_edit_comment: "Updated from spreadsheet", created_at: "2015-04-26 21:51:15", updated_at: "2019-10-06 02:55:38", home_page: "http://www.aik-invest.hr/", api_key: "mRrEJOm96+q94JZbEtVCgtDyx2ZuD7s4qIcdp02Y7Po9", info_requests_count: 3, disclosure_log: nil, info_requests_successful_count: 2, info_requests_not_held_count: 1, info_requests_overdue_count: 0, info_requests_visible_classified_count: 3, info_requests_visible_count: 3, name: "Agencija za investicije i konkurentnost, Zagreb", short_name: nil, request_email: "[ljerka.bregant@aik](mailto:ljerka.bregant@aik)-invest.hr", url_name: "agencija_za_investicije_i_konkurentnost_zagreb", notes: nil, first_letter: "A", publication_scheme: nil>, @draft_info_request=#<DraftInfoRequest id: nil, title: nil, user_id: nil, public_body_id: 28308, body: nil, embargo_duration: nil, created_at: nil, updated_at: nil>, @info_request=#<InfoRequest id: nil, title: nil, user_id: nil, public_body_id: 28308, created_at: nil, updated_at: nil, described_state: "waiting_response", awaiting_description: false, prominence: "normal", url_title: nil, law_used: "foi", allow_new_responses_from: "anybody", handle_rejected_responses: "bounce", idhash: nil, external_user_name: nil, external_url: nil, attention_requested: false, comments_allowed: true, info_request_batch_id: nil, last_public_response_at: nil, reject_incoming_at_mta: false, rejected_incoming_count: 0, date_initial_request_last_sent_at: nil, date_response_required_by: nil, date_very_overdue_after: nil, last_event_forming_initial_request_id: nil, use_notifications: nil, last_event_time: nil, incoming_messages_count: 0>, @outgoing_message=#<OutgoingMessage id: nil, info_request_id: nil, body: "Za: Agencija za investicije i konkurentnost, Zagre...", status: nil, message_type: nil, created_at: nil, updated_at: nil, last_sent_at: nil, incoming_message_followup_id: nil, what_doing: nil, prominence: "normal", prominence_reason: nil>, @embargo=#<AlaveteliPro::Embargo id: nil, info_request_id: nil, publish_at: "2022-07-13 22:00:00", created_at: nil, updated_at: nil, embargo_duration: "3_months", expiring_notification_at: "2022-07-06 22:00:00">, @exception_backtrace="/data/www/imamopravoznati.org/alaveteli/lib/i18n_fixes.rb:34:in `block in gettext_interpolate'\n/data/www/imamopravoznati.org/alaveteli/lib/i18n_fixes.rb:30:in `gsub'\n/data/www/imamopravoznati.org/alaveteli/lib/i18n_fixes.rb:30:in `gettext_interpolate'\n/data/www/imamopravoznati.org/alaveteli/lib/i18n_fixes.rb:10:in `_'\n/data/www/imamopravoznati.org/alaveteli/app/views/request/new_defunct.html.erb:7:in `_app_views_request_new_defunct_html_erb___2958776485975916384_47435021919340'\n/home/alaveteli/bundle/ruby/2.5.0/gems/actionview-5.2.6/lib/action_view/template.rb:159:in `block in render'\n/home/alaveteli/bundle/ruby/2.5.0/gems/activesupport-5.2.6/lib/active_support/notifications.rb:170:in `instrument'\n/home/alaveteli/bundle/ruby/2.5.0/gems/actionview-5.2.6/lib/action_view/template.rb:354:in `instrument_render_template'\n/home/alaveteli/bundle/ruby/2.5.0/gems/actionview-5.2.6/lib/action_view/template.rb:157:in `render'\n/home/alaveteli/bundle/ruby/2.5.0/gems/actionview-5.2.6/lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'\n/home/alaveteli/bundle/ruby/2.5.0/gems/actionview-5.2.6/lib/action_view/renderer/abstract_renderer.rb:44:in `block in instrument'\n/home/alaveteli/bundle/ruby/2.5.0/gems/activesupport-5.2.6/lib/active_support/notifications.rb:168:in `block in instrument'\n/home/alaveteli/bundle/ruby/2.5.0/gems/activesupport-5.2.6/lib/active_support/notifications/instrumenter.rb:23:in `instrument'\n/home/alaveteli/bundle/ruby/2.5.0/gems/activesupport-5.2.6/lib/active_support/notifications.rb:168:in `instrument'\n/home/alaveteli/bundle/ruby/2.5.0/gems/actionview-5.2.6/lib/action_view/renderer/abstract_renderer.rb:43:in `instrument'\n/home/alaveteli/bundle/ruby/2.5.0/gems/actionview-5.2.6/lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'\n/home/alaveteli/bundle/ruby/2.5.0/gems/actionview-5.2.6/lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'\n/home/alaveteli/bundle/ruby/2.5.0/gems/actionview-5.2.6/lib/action_view/renderer/template_renderer.rb:52:in `render_template'\n/home/alaveteli/bundle/ruby/2.5.0/gems/actionview-5.2.6/lib/action_view/renderer/template_renderer.rb:16:in `render'\n/home/alaveteli/bundle/ruby/2.5.0/gems/actionview-5.2.6/lib/action_view/renderer/renderer.rb:44:in `render_template'\n/home/alaveteli/bundle/ruby/2.5.0/gems/actionview-5.2.6/lib/action_view/renderer/renderer.rb:25:in `render'\n/home/alaveteli/bundle/ruby/2.5.0/gems/actionview-5.2.6/lib/action_view/rendering.rb:103:in `_render_template'\n/home/alaveteli/bundle/ruby/2.5.0/gems/actionpack-5.2.6/lib/action_controller/metal/streaming.rb:219:in `_render_template'\n/home/alaveteli/bundle/ruby/2.5.0/gems/actionview-5.2.6/lib/action_view/rendering.rb:84:in `render_to_body'\n/home/alaveteli/bundle/ruby/2.5.0/gems/actionpack-5.2.6/lib/action_controller/metal/rendering.rb:52:in `render_to_body'\n/home/alaveteli/bundle/ruby/2.5.0/gems/actionpack-5.2.6/lib/action_controller/metal/renderers.rb:142:in `render_to_body'\n/home/alaveteli/bundle/ruby/2.5.0/gems/actionpack-5.2.6/lib/abstract_controller/rendering.rb:25:in `render'\n/home/alaveteli/bundle/ruby/2.5.0/gems/actionpack-5.2.6/lib/action_controller/metal/rendering.rb:36:in `render'\n/home/alaveteli/bundle/ruby/2.5.0/gems/actionpack-5.2.6/lib/action_controller/metal/instrumentation.rb:46:in `block (2 levels) in render'\n/home/alaveteli/bundle/ruby/2.5.0/gems/activesupport-5.2.6/lib/active_support/core_ext/benchmark.rb:14:in `block in ms'\n/usr/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'\n/home/alaveteli/bundle/ruby/2.5.0/gems/activesupport-5.2.6/lib/active_support/core_ext/benchmark.rb:14:in `ms'\n/home/alaveteli/bundle/ruby/2.5.0/gems/actionpack-5.2.6/lib/action_controller/metal/instrumentation.rb:46:in `block in render'\n/home/alaveteli/bundle/ruby/2.5.0/gems/actionpack-5.2.6/lib/action_controller/metal/instrumentation.r

**Comment by garethrees** [comment]
> Nažalost, "{{autority_name}}" je označen

Typo here (missing "h"):

```diff
- autority_name
+ authority_name
```

**Comment by schlos** [comment]
Good catch!
Cannot find "autority_name" in the theme. Is it in the alaveteli core (or already fixed)?

**Comment by schlos** [comment]
Found it, it was a typo in HR app.pot more than a year ago. It was fixed, only after 0.39.0.0, so repo tag has old translation.

Thanks! Will mark it as closed.
