### ISSUE TITLE
Option to be more vague about event times in published event history log data

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#7616]
On event history logs associated with request correspondence threads ([example](https://www.whatdotheyknow.com/details/request/milton_road_remodelling_detailed)) detailed timestamps for each event, with precision down to the second, are provided. 

The availability of this data may, in the UK, enable a non-judicial demand for user-identifying data following the issuing of an authorisation by [a designated senior officer of a relevant public authority](https://www.legislation.gov.uk/ukpga/2016/25/schedule/4/enacted) under the condition set out in [Section 62(3) of the Investigatory Powers Act 2016](https://www.legislation.gov.uk/ukpga/2016/25/section/62/enacted). 

This enables an order for the provision of
> "data to identify which person or apparatus is using an internet service where—
>
>(a) the service and time of use are already known, but
>(b) the identity of the person or apparatus using the service is not known.

(See broader context under heading: [Targeted authorisations for obtaining data](https://www.legislation.gov.uk/ukpga/2016/25/part/3/crossheading/targeted-authorisations-for-obtaining-data/enacted)). 

Not publishing the precise time of each use/action may prevent such requests for user-data. 

I don't think the change would impact the intended application of the law. 

The detailed timestamps are also on the main JSON page for each request. 

Reasons to continue to publish the timestamps:

* Exact timestamps help those working with the data eg. to identify the fastest responses. 
* Reuse of timestamps is likely to be easier than a vague time described in words

Related:

* https://github.com/mysociety/whatdotheyknow-theme/issues/1512

**Comment by WilliamWDTK** [comment]
How vague is vague? To the minute? Hour?

I'm not sure I'd get any vaguer than minutes.

**Comment by garethrees** [comment]
> On event history logs

Also in the `title` attribute of the correspondence anchors (hover to view).

<img width="283" alt="Screenshot 2023-03-01 at 10 55 21" src="https://user-images.githubusercontent.com/282788/222119817-d11bbbaf-6aff-4506-91a9-07f9d1b984b6.png">

**Comment by garethrees** [comment]
> Not publishing the precise time … may prevent such requests for user-data.

On the basis that the "time of use" wouldn't be known as required by clause (a)?

**Comment by RichardTaylor** [comment]
>Not publishing the precise time … may prevent such requests for user-data.

>> On the basis that the "time of use" wouldn't be known as required by clause (a)?

Yes.

**Comment by RichardTaylor** [comment]
I think this is something we'd only do if we were extremely serious about protecting the identity of our users, even in the face of legal requests from public bodies for information to help identify them, hence the link to https://github.com/mysociety/whatdotheyknow-theme/issues/1512 

This consideration might actually be most useful in terms of lobbying for changes to the law or informing reviews of the operation of the law. It may be that legislators did not consider that some websites (Alaveteli isn't the only one) publish timestamps associated with site activity.

**Comment by garethrees** [comment]
> > On the basis that the "time of use" wouldn't be known as required by clause (a)?
>
> Yes.

I'd have thought even _day of use_, at least in our context, would likely be enough of a sense of "time of use" to satisfy this? IANAL, ofc.

**Comment by RichardTaylor** [comment]
The more vague a time is the less likely a request is to be considered proportionate and be authorised.  

There is the counter-point that the more precise a time the less likely a request is to encompass personal data of those other than the intended target. The degree of collateral intrusion will be a factor for assessing the proportionality of a request too. 

>I'd have thought even day of use, at least in our context, would likely be enough of a sense of "time of use" to satisfy this? IANAL, ofc.

There are references in [guidance](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/757850/Communications_Data_Code_of_Practice.pdf) to "a specific point in time " and "a specific point, or points, in time".

**Comment by garethrees** [comment]
I don't think this is a big enough issue to warrant considering.
