### ISSUE TITLE
[ERROR] NoMethodError in AdminGeneralController#index - undefined method `created_at' for nil:NilClass

### ISSUE THREAD

**Issue by schlos** [mysociety/alaveteli#7625]
Running on "develop" branch.

When logging in to the Docker for the first time as Emergency Admin user on:
http://0.0.0.0:3000/admin?emergency=1

I got the following error:

<header style="color: rgb(240, 240, 240); background: rgb(204, 0, 0); padding: 0.5em 1.5em; font-family: helvetica, verdana, arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><h1 style="overflow-wrap: break-word; margin: 0.2em 0px; line-height: 1.1em; font-size: 2em;">NoMethodError in AdminGeneralController#index</h1></header><main role="main" id="container" style="box-sizing: border-box; width: 1920px; padding: 0px 1.5em; color: rgb(236, 236, 236); font-family: helvetica, verdana, arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="exception-message" style="padding: 8px 0px;"><div class="message" style="margin-bottom: 8px; line-height: 25px; font-size: 1.5em; font-weight: bold; color: rgb(204, 0, 0);">undefined method `created_at' for nil:NilClass</div></div><div class="source " id="frame-source-0-0" style="border: 1px solid rgb(85, 85, 85); background: rgb(51, 51, 51); max-width: 978px;"><div class="info" style="margin: 0px; padding: 0.5em;">Extracted source (around line<span> </span><strong style="margin: 0px; padding: 0px;">#51</strong>):</div><div class="data" style="margin: 0px; padding: 0px; font-size: 10.4px; overflow: auto; background: rgb(68, 68, 68);">

49 50 51 52 53 54 | # hide old announcements, created before user signed up     where('announcements.created_at >= ?', user.created_at).      visible_to(roles)   }
-- | --

</div></div><p style="font-family: helvetica, verdana, arial, sans-serif; font-size: 13px; line-height: 18px;"><code>Rails.root: /alaveteli</code></p><div id="traces-0"><a href="http://0.0.0.0:3000/admin?emergency=1#" onclick="hide('Framework-Trace-0');hide('Full-Trace-0');show('Application-Trace-0');; return false;" style="color: rgb(204, 0, 0);">Application Trace</a><span> </span>|<span> </span><a href="http://0.0.0.0:3000/admin?emergency=1#" onclick="hide('Application-Trace-0');hide('Full-Trace-0');show('Framework-Trace-0');; return false;" style="color: rgb(204, 0, 0);">Framework Trace</a><span> </span>|<span> </span><a href="http://0.0.0.0:3000/admin?emergency=1#" onclick="hide('Application-Trace-0');hide('Framework-Trace-0');show('Full-Trace-0');; return false;" style="color: rgb(204, 0, 0);">Full Trace</a><div id="Application-Trace-0" style="display: block;"><code class="traces" style="font-size: 11px;"><a class="trace-frames trace-frames-0" data-exception-object-id="140060" data-frame-id="0" href="http://0.0.0.0:3000/admin?emergency=1#" style="color: rgb(153, 153, 153); overflow-wrap: break-word;">app/models/announcement.rb:51:in `block in &lt;class:Announcement&gt;'</a><br><a class="trace-frames trace-frames-0" data-exception-object-id="140060" data-frame-id="6" href="http://0.0.0.0:3000/admin?emergency=1#" style="color: rgb(153, 153, 153); overflow-wrap: break-word;">app/controllers/admin_general_controller.rb:67:in `index'</a><br><a class="trace-frames trace-frames-0" data-exception-object-id="140060" data-frame-id="12" href="http://0.0.0.0:3000/admin?emergency=1#" style="color: rgb(153, 153, 153); overflow-wrap: break-word;">app/controllers/application_controller.rb:116:in `record_memory'</a><br><a class="trace-frames trace-frames-0" data-exception-object-id="140060" data-frame-id="41" href="http://0.0.0.0:3000/admin?emergency=1#" style="color: rgb(153, 153, 153); overflow-wrap: break-word;">lib/deeply_nested_params.rb:15:in `call'</a><br><a class="trace-frames trace-frames-0" data-exception-object-id="140060" data-frame-id="47" href="http://0.0.0.0:3000/admin?emergency=1#" style="color: rgb(153, 153, 153); overflow-wrap: break-word;">lib/strip_empty_sessions.rb:14:in `call'</a><br></code></div></div><h2 class="request-heading" style="color: rgb(204, 0, 0); line-height: 25px; margin-top: 30px;">Request</h2><p style="font-family: helvetica, verdana, arial, sans-serif; font-size: 13px; line-height: 18px;"><b>Parameters</b>:</p><pre style="font-size: 11px; white-space: pre-wrap;">{"emergency"=&gt;"1"}
</pre><div class="details" style="border: 1px solid rgb(102, 102, 102); border-radius: 4px; margin: 1em 0px; display: block; max-width: 978px;"><div class="summary" style="padding: 8px 15px; border-bottom: 1px solid rgb(102, 102, 102); display: block; border-top-color: rgb(102, 102, 102); border-right-color: rgb(102, 102, 102); border-left-color: rgb(102, 102, 102);"><a href="http://0.0.0.0:3000/admin?emergency=1#" onclick="return toggleSessionDump()" style="color: rgb(204, 0, 0);">Toggle session dump</a></div></div><div class="details" style="border: 1px solid rgb(102, 102, 102); border-radius: 4px; margin: 1em 0px; display: block; max-width: 978px;"><div class="summary" style="padding: 8px 15px; border-bottom: 1px solid rgb(102, 102, 102); display: block; border-top-color: rgb(102, 102, 102); border-right-color: rgb(102, 102, 102); border-left-color: rgb(102, 102, 102);"><a href="http://0.0.0.0:3000/admin?emergency=1#" onclick="return toggleEnvDump()" style="color: rgb(204, 0, 0);">Toggle env dump</a></div></div><h2 class="response-heading" style="color: rgb(204, 0, 0); line-height: 25px; margin-top: 30px;">Response</h2><p style="font-family: helvetica, verdana, arial, sans-serif; font-size: 13px; line-height: 18px;"><b>Headers</b>:</p><pre style="font-size: 11px; white-space: pre-wrap;">None</pre></main>NoMethodError in AdminGeneralController#index
undefined method `created_at' for nil:NilClass
Extracted source (around line #51):
49
50
51
52
53
54
              

    # hide old announcements, created before user signed up
    where('announcements.created_at >= ?', user.created_at).

    visible_to(roles)
  }

Rails.root: /alaveteli

[Application Trace](http://0.0.0.0:3000/admin?emergency=1#) | [Framework Trace](http://0.0.0.0:3000/admin?emergency=1#) | [Full Trace](http://0.0.0.0:3000/admin?emergency=1#)
[app/models/announcement.rb:51:in `block in <class:Announcement>'](http://0.0.0.0:3000/admin?emergency=1#)
[app/controllers/admin_general_controller.rb:67:in `index'](http://0.0.0.0:3000/admin?emergency=1#)
[app/controllers/application_controller.rb:116:in `record_memory'](http://0.0.0.0:3000/admin?emergency=1#)
[lib/deeply_nested_params.rb:15:in `call'](http://0.0.0.0:3000/admin?emergency=1#)
[lib/strip_empty_sessions.rb:14:in `call'](http://0.0.0.0:3000/admin?emergency=1#)
Request
Parameters:

{"emergency"=>"1"}
[Toggle session dump](http://0.0.0.0:3000/admin?emergency=1#)
[Toggle env dump](http://0.0.0.0:3000/admin?emergency=1#)
Response
Headers:

None

Backtrace:

```
imamopravoznati-app-1  | NoMethodError (undefined method `created_at' for nil:NilClass):
imamopravoznati-app-1  |   
imamopravoznati-app-1  | app/models/announcement.rb:51:in `block in <class:Announcement>'
imamopravoznati-app-1  | app/controllers/admin_general_controller.rb:67:in `index'
imamopravoznati-app-1  | app/controllers/application_controller.rb:116:in `record_memory'
imamopravoznati-app-1  | lib/deeply_nested_params.rb:15:in `call'
imamopravoznati-app-1  | lib/strip_empty_sessions.rb:14:in `call'
```

**Comment by schlos** [comment]
Similar to:
https://github.com/mysociety/alaveteli/issues/5604

Maybe this can be merged to:
https://github.com/mysociety/alaveteli/issues/5996

**Comment by garethrees** [comment]
Yeah I think this is basically a problem specific to the emergency user which is essentially no longer supported https://github.com/mysociety/alaveteli/issues/5996
