### ISSUE TITLE
Select authority is listing defunct authorities

### ISSUE THREAD

**Issue by schlos** [mysociety/alaveteli#7651]
Similar to Defunct body is listed in batch request authorities list selection #6039, but for this instance, I'm seeing defunct bodies being listed on https://imamopravoznati.org/select_authority using search query "ministarstvo" (i.e. ministry).

![Screenshot from 2023-03-20 08-49-12](https://user-images.githubusercontent.com/1014134/226277768-b95b68b9-7701-4bb6-bcc6-b206e4a06fe8.png)

IPZ version info:

"alaveteli_git_commit": "4c2aa965c7c0e7f6c1c77d14b3ac711e66e12f07",
"alaveteli_version": "0.39.1.6",
"ruby_version": "2.5.1",

Reproducible also on WDTK:
https://www.whatdotheyknow.com/select_authority

![Screenshot from 2023-03-20 08-51-45](https://user-images.githubusercontent.com/1014134/226278349-4e117707-8f65-49e0-b22e-67df0b87c823.png)

WDTK version info:

"alaveteli_git_commit": "0b77ee54061004bbf63a5337f4f6396120fc156b",
"alaveteli_version": "0.42.0.0",
"ruby_version": "3.2.0",

Since on this screen we're tryign to submit a request, I don't see a reason why we should list defunct bodies. Only non-defunct bodies should be shown (i.e. those that can receive a request - not defunct, not internal admin testing, has email address).

**Comment by garethrees** [comment]
These are listed here intentionally since users might not realise a "popular" authority has now been replaced.

Here's a situation:

1. User made an FOI request last year to "Another Public Body"
2. In the meantime, the body gets made defunct
3. A year later, the user wants to request the same data for this year

Right now, the user types "Another Public Body" as they did before, and then gets "notified" that they're defunct.

If we didn't list them, the user would be wondering why they aren't appearing. Did they make a typo? Has the site deleted that authority?

The current behaviour is clearer, though agree the presentation could be better, so closing in favour of https://github.com/mysociety/alaveteli/pull/7655 and https://github.com/mysociety/alaveteli/issues/721.

**Comment by schlos** [comment]
Thanks Gareth.

I don't fully agree with you. Users that go to screen "select authority" are going actually to try to send a new request, so IMHO we should list here only active bodies that can receive requests.

We could always add a small text below or above result list saying:

> Displaying 14 bodies matching your search, but there are [3 more that are defunct|https://imamopravoznati.org/search/ministarstvo%20tag:defunct/all] and can no longer receive new requests.

If user did not find what he was looking for, they can always use the provided link that lists all bodies with "tag:defunct" using the search keyword, so they can investigate separately from "create new request" flow what happened to those bodies.

I think this is better for user experience - less frustrated users that see dozens defunct bodies when searching the active ones for new request.

Moreover, Public body directory page should always continue to show defunct and non-defunct bodies same as now.
My proposal applies only to authority search with intent of sending new requests.

**Comment by garethrees** [comment]
> We could always add a small text below or above result list saying…

That would work better, for sure.

> I think this is better for user experience

I agree that the situation you describe isn't great.

With the way the indexing works though, it's quite technically difficult to make this change without a hack.

If you wanted to try this out in your theme, I think you'd have to customise [`public_body/_search_ahead`](https://github.com/mysociety/alaveteli/blob/develop/app/views/public_body/_search_ahead.html.erb) like:

```diff
      <% for result in @xapian_requests.results %>
+       <% next if result[:model].defunct? %>
+
        <%= render :partial => 'public_body/body_listing_single',
          :locals => { :public_body => result[:model],
                       :request_link => true } %>
      <% end %>
```

This would be less performant than excluding defunct authorities from the search results, but might work okay.

I think https://github.com/mysociety/alaveteli/issues/721 is likely a better fix in terms of performance and reduced complexity (and we've been experimenting with weighting a little in https://github.com/mysociety/alaveteli/pull/7553).

**Comment by schlos** [comment]
Works like a charm (defunct bodies are no longer listed on New request / Search authorities). Thanks!
