### ISSUE TITLE
Allow administrators to link their Google accounts for Webmaster Tools / Analytics via admin interface

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#766]
Enable super users to add the code required to give permission for their Google accounts to access Google Webmaster Tools / Google Analytics for the site via the Alaveteli admin interface. 

Implementation within the site may reduce instances of these codes being lost on server moves etc. ?

**Comment by garethrees** [comment]
Realistically, I don't think we'll ever get to this. Management of Google Webmaster Tools / Google Analytics access will vary across installs, and it'll add complexity to Alaveteli that we'll have to maintain. I don't think this happens very often either, so I don't think there's a large problem at play.
