### ISSUE TITLE
Localize delivery_status

### ISSUE THREAD

**Issue by schlos** [mysociety/alaveteli#7660]
Currently, delivery_status (label) seems to be always displayed in English, i.e.
- Delivered
- Failed
- Unknown

![Screenshot from 2023-03-22 19-46-20](https://user-images.githubusercontent.com/1014134/227006501-930cdf11-a282-4ebc-8985-7abda8bfbeee.png)

Related line where it gets printed out on frontend:
https://github.com/mysociety/alaveteli/blob/develop/app/views/request/_outgoing_correspondence.html.erb#L19

Didn't found where I can make strings translatable.

There is this string in PO file, but maybe used in different place?
https://github.com/mysociety/alaveteli/blob/hotfix/0.39.1.5/locale/hr/app.po#L4091

**Comment by laurentS** [comment]
@schlos I fixed this a while ago on madada.fr, assuming you're talking about the circled word on my screenshot below. Sadly I don't remember exactly what I did :(
![image](https://user-images.githubusercontent.com/1745184/227032409-15575161-eb5a-4776-bc76-8c3551441140.png)

I think this PR should help you https://github.com/mysociety/alaveteli/pull/7325

**Comment by schlos** [comment]
Thanks @laurentS ! This fixed the issue.

Closing since it was fixed with https://github.com/mysociety/alaveteli/pull/7325
