### ISSUE TITLE
Managing antispam and "invalid address" replies

### ISSUE THREAD

**Issue by laurentS** [mysociety/alaveteli#7661]
I don't know how portable this issue is, but in France, many authorities use a spam protection system whereby a few seconds after sending them an email, we receive a message with a link to a captcha page. The captcha needs to be solved for our email to be delivered.

I am looking for ways to identify these emails automatically, in order to help pro users deal with them more effectively.

So far, my thinking looks like:
- run a cron job every few minutes that lists recent emails that contain a certain sender keyword.
- mark them with a tag or custom status like `needs_captcha_resolution`
- present these to the user on the dashboard and let them solve the captchas
- do some magic trick to automatically recognise that said captcha has been solved (still figuring out how to do this in a clean way) and either remove the tag or switch the status to "awaiting response". If magic can't be done, let the user manually adjust.

What would you suggest is the best way to go about this? tags or status (I'm leaning toward the second option, but would like confirmation that I'm not going to create too much trouble for ourselves down the line). Ideally, I'd want a mechanism that changes the delivery timestamp of the initial outgoing email, since it is not actually delivered until captcha is solved, meaning our delay calculations are all wrong without such an update.

Similarly, some email servers (they seem to all be MS ones) have a tendency to respond to incoming emails with a code `250 OK`, followed by an email within a second or so saying that the recipient address does not exist. This marks our email as sent, although it wasn't. I'd like to follow a similar pattern to identify such replies, mark corresponding requests as needing admin attention, maybe with some extra info to identify that the public body's address is invalid. This would save the requester a step of checking incoming emails only to find that nothing useful has happened. I suspect that we're not the only platform facing this issue given the prevalence of MS email servers.

I'm happy to write the code for these 2 points, but would like your feedback to make sure I'm approaching this the right way :)

**Comment by garethrees** [comment]
Oh my, that sounds _terrible_. This isn't something we've seen here. Worth reaching out to FragDenStaat who [solved a similar issue](https://fragdenstaat.de/en/blog/2022/08/16/we-cracked-the-frontex-code/). 

My first thought would be to go with tags actually. They've been quite a lot more flexible for us in implementing custom behaviour ([example](https://github.com/mysociety/whatdotheyknow-theme/blob/6e96327acda087c5aa6da4d34c352f20f6cd0bf2/lib/model_patches.rb#L51-L59). The status is more about the _information_ (am I waiting? did I get it?). This is something I'd like to simplify/improve in future, but I think the tags might be better when a pattern/behaviour only happens in some cases. 

I think you could add a hook that resets the timestamp on removal of the tag (or indeed, you could use a pair of tags like `captcha:required` and then `captcha:solved`). https://github.com/mysociety/alaveteli/commit/8c36499e247f5708cdc2c8b1180fabe21ca74628 might provide some inspiration here. That said, I'm not sure I'd want to treat this as an okay thing for an authority to do, so would be seriously thinking about leaving the timeline as it is and using it as a campaigning tool to show how authorities are putting barriers in the way of people asking for information.

> Similarly, some email servers (they seem to all be MS ones) have a tendency to respond to incoming emails with a code 250 OK, followed by an email within a second or so saying that the recipient address does not exist. This marks our email as sent, although it wasn't.

It _was_ delivered though. We treat a 250 response as analogous to a signed for parcel delivery being accepted. It's then their responsibility to route it correctly. I think the "real life" analogy here is that you've sent a letter that needs to be signed for. The receptionist accepts and signs for it, and then writes back to you to say the department no longer exists. That said, can see a utility in automating the marking of these for admin attention. In this case you probably want to change the status, or have something that calls `InfoRequest#report!`.

**Comment by garethrees** [comment]
FWIW, we've also had [some recent challenges](https://www.mysociety.org/2022/08/01/public-bodies-refusing-emailed-foi-requests/) along similar lines. We've tracked them, reported some to the regulator, and had some good outcomes. We've also directed requests to the org director / CEO until they stop forcing users to forms.

**Comment by laurentS** [comment]
Thanks for your quick feedback, this is very helpful! 

> FWIW, we've also had [some recent challenges](https://www.mysociety.org/2022/08/01/public-bodies-refusing-emailed-foi-requests/) along similar lines. We've tracked them, reported some to the regulator, and had some good outcomes. We've also directed requests to the org director / CEO until they stop forcing users to forms.

Sadly in France, the law is on their side, if there's a webform, users should use it. This is still not a huge concern, but it means we need to tread carefull with email.

 > Oh my, that sounds terrible. This isn't something we've seen here. Worth reaching out to FragDenStaat who [solved a similar issue](https://fragdenstaat.de/en/blog/2022/08/16/we-cracked-the-frontex-code/).

This is super interesting. If volumes increase, then this might be a lifesaver.

> My first thought would be to go with tags actually. They've been quite a lot more flexible for us in implementing custom behaviour ([example](https://github.com/mysociety/whatdotheyknow-theme/blob/6e96327acda087c5aa6da4d34c352f20f6cd0bf2/lib/model_patches.rb#L51-L59). The status is more about the information (am I waiting? did I get it?). This is something I'd like to simplify/improve in future, but I think the tags might be better when a pattern/behaviour only happens in some cases.

Noted. I'll try to follow this. It does seem less scary than statuses in terms of how tightly coupled it is with the upstream code. If you think it'll work, I'll trust your judgement :)

> It was delivered though. [...]

I agree with you. However we're starting from *very* far. 80% of our emails never get any reply, not even a delivery receipt (although it is mandated by law). Our goal right now is to show how badly the law is followed by using metadata. So we're trying to remove any possible excuse like "you started counting before we even got the email". Basically, I think we need to build a data-backed argument like "even when we go above and beyond what we're supposed to do, we're still not getting any reply". The other aspect is that there is not established jurisprudence about whether a `250 OK` from a mail server constitutes a proof of delivery under French law (at least to our knowledge).
And obviously, we're also trying to make our life easier.

**Comment by garethrees** [comment]
Closing given this is more of a Q&A.
