### ISSUE TITLE
Prettify numbers in the admin interface

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/alaveteli#7663]
Where it is not an ID, numbers in the admin interface could be formatted to make them prettier and easier to read.

Instead of

![46094 public authorities
961917 requests, 1436718 outgoing messages, 2245111 incoming messages
266132 users, 168870 tracked things
110164 annotations](https://user-images.githubusercontent.com/99501342/227657341-f3273e63-9b0c-4c31-912c-97ed45b20a15.png)

We could have something like

![46,094 public authorities
961,917 requests, 1,436,718 outgoing messages, 2,245,111 incoming messages
266,132 users, 168,870 tracked things
110,164 annotations](https://user-images.githubusercontent.com/99501342/227657749-fa9efa81-4011-4bbe-bed3-5e8babe3c266.png)

Not just on this page ([`https://www.whatdotheyknow.com/admin/stats`](https://www.whatdotheyknow.com/admin/stats)), but elsewhere also.

**Comment by confirmordeny** [comment]
This would be helpful for WhatDoTheyKnow and other Alaveteli sites based in English speaking countries.

**Comment by HelenWDTK** [comment]
+1 Though it would need localising, as some countries use . or a space as a thousands separator.
