### ISSUE TITLE
Special tag to exclude bodies from Pro batches

### ISSUE THREAD

**Issue by mdeuk** [mysociety/alaveteli#7665]
On WhatDoTheyKnow there are a number of bodies which aren't subject to FoIA.

This could be bodies with obligations under the Environmental Information Regulations only (e.g. security bodies), and those which either voluntarily comply, or, ones which meet WDTK's listing policy.

It would be helpful if a 'special' tag was available which would allow Alaveteli to automatically exclude these bodies from being added to batches - whilst still allowing the bodies to appear in relevant categories in the UI.

Examples:
- [York Minster Police](https://www.whatdotheyknow.com/body/york_minster_police) - very narrow application of FoIA
- [Solicitors Regulation Authority](https://www.whatdotheyknow.com/body/sra) - voluntary transparency code

**Comment by confirmordeny** [comment]
As an aside, we have improved our tagging of police forces.
