### ISSUE TITLE
PDF turned into 8000 PNGs

### ISSUE THREAD

**Issue by Flupsy** [mysociety/alaveteli#772]
The response to the request at http://www.whatdotheyknow.com/request/133195 has turned into nearly 8000 little PNGs, which just caused a nasty load spike on atlas when someone tried to access it.

**Comment by garethrees** [comment]
Just noticed that the [original upstream bug report](https://bugs.freedesktop.org/show_bug.cgi?id=77932) has now been [migrated to their new issue tracker](https://gitlab.freedesktop.org/poppler/poppler/issues/346).
