### ISSUE TITLE
RuboCops: Style

### ISSUE THREAD

**Issue by alexander-griffen** [mysociety/alaveteli#7729]
This is the list of the 'Style' RuboCops to be done. Some of these will be auto-correctable, and others will not. Some will be a mixture.

This list will change, because as new cops get fixed they sometimes introduce more cops to crop up. I'll try and keep this up to date as of the `develop` branch for the start of each sprint, and also record the work that has been completed.

## Cops
 - [ ] 295  Documentation
 - [ ] 151  [GuardClause](https://rubystyle.guide#no-nested-conditionals)
 - [ ] 53   [HashSyntax](https://rubystyle.guide#hash-literals)
 - [ ] 35   [ClassVars](https://rubystyle.guide#no-class-vars)
 - [ ] 31   [NumericLiteralPrefix](https://rubystyle.guide#numeric-literal-prefixes)
 - [ ] 27   GlobalVars
 - [ ] 5    [DoubleNegation](https://rubystyle.guide#no-bang-bang)
 - [ ] 5    [IfUnlessModifier](https://rubystyle.guide#if-as-a-modifier)
 - [ ] 5    [NegatedIf](https://rubystyle.guide#unless-for-negatives)
 - [ ] 4    [ColonMethodCall](https://rubystyle.guide#double-colons)
 - [ ] 4    [RedundantSelf](https://rubystyle.guide#no-self-unless-required)
 - [ ] 4    [WordArray](https://rubystyle.guide#percent-w)
 - [ ] 3    ZeroLengthPredicate
 - [ ] 2    [Alias](https://rubystyle.guide#alias-method-lexically)
 - [ ] 2    [Lambda](https://rubystyle.guide#lambda-multi-line)
 - [ ] 1    [ClassCheck](https://rubystyle.guide#is-a-vs-kind-of)
 - [ ] 1    [DefWithParentheses](https://rubystyle.guide#method-parens)
 - [ ] 1    [For](https://rubystyle.guide#no-for-loops)
 - [ ] 1    [MultilineBlockChain](https://rubystyle.guide#single-line-blocks)
 - [ ] 1    [Proc](https://rubystyle.guide#proc)
 - [ ] 1    [RedundantBegin](https://rubystyle.guide#begin-implicit)
 - [ ] 1    RedundantParentheses
 - [ ] 1    [RedundantReturn](https://rubystyle.guide#no-explicit-return)
 - [ ] 1    SymbolProc

**Comment by garethrees** [comment]
This is desirable, but unlikely to be worked on in the next 12 months so closing for now.
