### ISSUE TITLE
RuboCops: Naming

### ISSUE THREAD

**Issue by alexander-griffen** [mysociety/alaveteli#7730]
This is the list of the 'Naming' RuboCops to be done. Some of these will be auto-correctable, and others will not. Some will be a mixture.

This list will change, because as new cops get fixed they sometimes introduce more cops to crop up. I'll try and keep this up to date as of the `develop` branch for the start of each sprint, and also record the work that has been completed.

## Cops
 - [ ] 43   [AccessorMethodName](https://rubystyle.guide#accessor_mutator_method_names)
 - [ ] 41   [PredicateName](https://rubystyle.guide#bool-methods-qmark)
 - [ ] 5    [FileName](https://rubystyle.guide#snake-case-files)
 - [ ] 4    [ConstantName](https://rubystyle.guide#screaming-snake-case)

**Comment by garethrees** [comment]
This is desirable, but unlikely to be worked on in the next 12 months so closing for now.
