### ISSUE TITLE
RuboCops: Lint

### ISSUE THREAD

**Issue by alexander-griffen** [mysociety/alaveteli#7731]
This is the list of the 'Lint' RuboCops to be done. Some of these will be auto-correctable, and others will not. Some will be a mixture.

This list will change, because as new cops get fixed they sometimes introduce more cops to crop up. I'll try and keep this up to date as of the `develop` branch for the start of each sprint, and also record the work that has been completed.

## Cops
 - [ ] 8    UnderscorePrefixedVariableName
 - [ ] 6    [RescueException](https://rubystyle.guide#no-blind-rescues)
 - [ ] 6    [SuppressedException](https://rubystyle.guide#dont-hide-exceptions)
 - [ ] 4    RedundantCopDisableDirective
 - [ ] 2    DuplicateMethods
 - [ ] 1    ShadowedException

**Comment by garethrees** [comment]
This is desirable, but unlikely to be worked on in the next 12 months so closing for now.
