### ISSUE TITLE
Integer `body` URL slugs redirect to seemingly random body ("All roads lead to Flint")

### ISSUE THREAD

**Issue by confirmordeny** [mysociety/alaveteli#7733]
https://www.whatdotheyknow.com/body/1 redirects to Flint Town Council, Flintshire as does https://www.whatdotheyknow.com/body/5000 and seemingly every other positive whole number.

**Comment by WilliamWDTK** [comment]
For what it's worth (probably nothing), [Flint Town Council](https://www.whatdotheyknow.com/body/flint_town_council_flintshire) has been replaced by [Birchanger Parish Council](https://www.whatdotheyknow.com/body/birchanger_parish_council) (in this error, not in terms of responsibility!).

**Comment by garethrees** [comment]
This is desirable, but unlikely to be worked on in the next 12 months so closing for now.
