### ISSUE TITLE
RuboCop Layout/LineLength - specs

### ISSUE THREAD

**Issue by alexander-griffen** [mysociety/alaveteli#7739]
This issue is part of #7728.

It will be one of multiple issues used to track the Layout/LineLength cop.

These have been separated into separate issues due to the massive amount of changes required. Also, whilst many of the instances of this cop are marked as autocorrectable, the autocorrecting does not produce results consistent with the Ruby Style guide, so the majority of the work will be manual. 

In the interest of atomicity, I am trying to only make changes regarding line length, but some other small style changes end up being implicit these changes.

The scope of this issue is to correct the LineLength cops in the `spec` directory and sub-directories:
- [x] `views` https://github.com/mysociety/alaveteli/pull/7740
- [x] `controllers` https://github.com/mysociety/alaveteli/pull/7744
- [x] `factories` https://github.com/mysociety/alaveteli/pull/7789
- [ ] `fixtures`
- [ ] `helpers`
- [ ] `integration`
- [ ] `jobs`
- [ ] `lib`
- [ ] `mailers`
- [ ] `models`
- [ ] `script`
- [ ] `services`
- [ ] `support`
- [ ] `validators`
- [ ] top-level spec directory

**Comment by garethrees** [comment]
This is desirable, but unlikely to be worked on in the next 12 months so closing for now.
