### ISSUE TITLE
Wording of Was the response you got to your FOI request any good? message

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#775]
We send out automated emails to those who have not categorised their request with the subject:

"Was the response you got to your FOI request any good?"

Some people reply to us by email rather than clicking selecting the best option from those presented. 

Current:

Subject: Was the response you got to your FOI request any good?

```
 To let everyone know, follow this link and then select the
 appropriate box.

 http://www.whatdotheyknow.com/c/xxxxxxxxxxxxxxx

 Your request was called xxxx   Letting everyone know
 whether you got the information will help us keep tabs on xxxxx

 -- the WhatDoTheyKnow team
```

Ideas:

Perhaps the subject line ought say something more like "Please classify the response to your request"

The message could also note that the reason the message is being sent is because the classification has not yet been set. 

Perhaps an explicit note urging people not to reply by email unless there is  a matter they wish to discuss with those running the site?
# 

It may of course be the current email is already as good as it gets and any changes will just result in more users hitting reply rather than visiting the link and categorising their request. 

I'm raising the issue as it's one of the causes of emails to the team and minimising such emails would generally be a good thing.

**Comment by garethrees** [comment]
Be more direct in the subject line – "Please classify this request" or similar

**Comment by garethrees** [comment]
> Perhaps something like “Please classify the latest response to your request..”
> “Please update the status of your request”

**Comment by RichardTaylor** [comment]
Just to note we're still getting the occasional user responding to this email rather than following the link. 

The message as it is at the moment doesn't actually make sense. It used to say
:Subject: Was the response you got to your FOI request any good? 
:To let everyone know, follow this link and then select the appropriate box.
 
now the subject has changed but the first line which used to follow from the subject has stayed the same:
>Please update the status of your request 
>To let everyone know, follow this link and then select the appropriate box.

Perhaps the email should start:
>Please let us know about the latest response to your request for information by following the link below and selecting the appropriate box: 

We could add something like:
>Please use the link to the form to classify your own responses rather than replying to this message and emailing the volunteer team. 

It might be useful to explain why classification is important too, with something like:

>We ask you to classify your responses so our system knows what state a request is in. Properly classified responses are needed so our system knows what, if anything, to prompt you to do next. Marking requests as successful, or otherwise, can help those browsing the site, as well as those who've signed for alerts to, for example, successful requests to particular bodies. 


Also to note the ticket for preventing these messages being sent to suspended users: #5090
