### ISSUE TITLE
Generate short request summaries

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#7769]
[Secret Canada](https://www.secretcanada.com/) is a Canadian FOI collaboration between some newspapers there. It's essentially a disclosure log.

While we do have titles, their summaries are more about the _information_ requested rather than the topic. What's quite nice about it is the, which gives a little extra insight into what's in the request. An `InfoRequest#summary` could be used in request listings to aid browsing for interesting things, on the request page to give an overview of the potentially long correspondence thread, and as a higher priority field in search rankings.

<img width="1791" alt="Screenshot 2023-06-12 at 09 29 45" src="https://github.com/mysociety/alaveteli/assets/282788/c5398aac-95e7-46a6-997a-e33b19755b1e">

We'd want to make this an optional field as we might only want to generate for a subset of requests (successful? completed?, specific authority categories), so would have to have a fallback in the UI.

**Comment by mdeuk** [comment]
Great idea.

It does strike me that this would be a very good place to look for AI assistance. Obviously, cost is a potential issue - but, if we can get it right [^1], it could be pretty powerful.

We've done some [early experiments](https://mysociety.slack.com/archives/CNH83HJP4/p1680766630553469?thread_ts=1680762642.757539&cid=CNH83HJP4) with GPT and Bing AI [^2] - mostly @HelenWDTK's tinkering. 

[^1]: ideally, optimising the query to reduce "cost" - perhaps only do it on a subset of requests?
[^2]: consumer service, so probably not suitable here - but worthy of experimenting with MSFT's API, and perhaps the Google variants. Perhaps seek sponsorship?

**Comment by garethrees** [comment]
Yeah, AI was implied (though didn't want to rule out other approaches like crowdsourcing). This issue is just a place to flesh out our thoughts and then incorporating into a funding application at some point in the future.

**Comment by garethrees** [comment]
Nice example of summarising ONS mentions on TWFY: https://datasciencecampus.ons.gov.uk/parliai-using-ai-tools-to-monitor-parliamentary-coverage-of-the-ons-across-the-uk/

**Comment by garethrees** [comment]
This is desirable, but unlikely to be worked on in the next 12 months so closing for now.
