### ISSUE TITLE
Make all request URLs use `url_title` instead of `id` as the identifier

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#7784]
When dealing with support requests we often have to figure out multiple permutations of request (and associated content) URLs.

For example, given the request `/request/foo`, we might end up with:

* `/request/foo`
* `/cy/request/foo`
* `/request/123/response/456/attach/2/bar.doc`
* `/request/123/response/456/attach/2/bar.doc.html`
* `/request/123/followups/new/456`
* `/details/request/foo`
* `/feed/request/foo`

While the locale prefix (`/cy/`) and other routing (e.g. `/feed/request/…`) is a bit more of a faff to fix, knowing that public request URLs will consistently use the `url_title` instead of `id` as the identifier is a good thing to not have to worry about.

This ticket should:

- [ ] Replace all uses of `InfoRequest#id` as a URL parameter `InfoRequest#url_title` for any public request URL
- [ ] Handle existing routes that use `InfoRequest#id` by permanently redirecting to the updated URL (i.e. we should always be able to _use_ `id` in place of the `url_title`, but it should always result in a redirect)

**Comment by HelenWDTK** [comment]
🙏 This would massively simplify the search engine url removal request process.

**Comment by mdeuk** [comment]
Stupid question: will this stop `request/$numeric-id` (which I'm assuming `InfoRequest#id` is from eventually working? This would break some of our functionality.

**Comment by garethrees** [comment]
> Stupid question: will this stop `request/$numeric-id` (which I'm assuming `InfoRequest#id` is from eventually working?

Part two covers that (ensure existing ID-based routes redirect to the title-based route – the current behaviour of navigating to `/request/123`). So for example, navigating to `/request/123/followups/new/456` would result in a `301` redirect to `/request/foo/followups/new/456`.

**Comment by mdeuk** [comment]
> Part two covers that (ensure existing ID-based routes redirect to the title-based route

I thought it would - it was "existing" that threw me [^1].

[^1]: as I interpreted that as being _"support it on what we already have, but not on anything new"_

**Comment by garethrees** [comment]
👍 clarified the todo.

**Comment by gbp** [comment]
What about:

`api_show_request GET      /api/v2/request/:id.json(.:format)                                                                api#show_request`

**Comment by garethrees** [comment]
Ah, maybe not that because of the contract with iCasework and doesn't immediately cause as much of a problem with cache clearance as it requires a key to authenticate against.
