### ISSUE TITLE
Make Pro base path `/pro` rather than `/alaveteli_pro`

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#7788]
`/alaveteli_pro` doesn't look right. Lets change it to `/pro`.

- [x] Requires https://github.com/mysociety/alaveteli/issues/7787.

After #7787 there _shouldn't_ be any need to add redirects for `/alaveteli_pro`-prefixed routes, but we'll want to be sure before shipping this.

**Comment by laurentS** [comment]
Could I suggest making the `/pro` replacement configurable if it's not a huge amount of work?

**Comment by garethrees** [comment]
We can certainly explore that as an option, though routes aren't quite as easy to customise. What would you use instead?

**Comment by laurentS** [comment]
I think your "not quite as easy" comment is enough for me to say it's not worth it. We have tried to avoid the "pro" word, but we're still using english URLs and all, so I think it says it's not a big priority. (we call it "plusplus / ++" for madada)

**Comment by LisetHamming** [comment]
Hi Gareth and Laurent! Probably not the best place to leave personal notes, but wanted to let you know that I made it this far (where are the smileys in this place...) and am exploring, thanks to you! Are is a lot to see here...

See you soon!

Ps ha, did discover a few smileys by accident👍

**Comment by garethrees** [comment]
In planning today @alexander-griffen noted that he and @gbp had noted some potential complexity with this change. I had a quick look at the routes and while I'm not 100% sure, I can see that all this might be more annoying than a simple word change. If it's easier, we could make this `/dashboard`, which would also be more agnostic to what different sites call their pro offering. I'm leaning towards preferring `/dashboard` anyway – it more closely describes what the user is looking at, _and_ it's served by the `DashboardController`.
