### ISSUE TITLE
`/favicon.ico` returns 406

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#7810]
```
$ curl --silent -I https://www.whatdotheyknow.com/favicon.ico | head -n 1
HTTP/2 406
```

The favicon is rendered, but via an asset URL with digest, e.g.:

```html
<link rel="icon" type="image/x-icon" href="/assets/favicon-afe76651f859e6a7b6b153def0358ae1b959842c02fdc46bc3adca58eb6395b2.ico" />
```

Not just mySociety-hosted installs, so probably an issue in Alaveteli somewhere:

```
$ curl --silent -I https://madada.fr/favicon.ico | head -n 1
HTTP/1.1 406 Not Acceptable
```

Might be an issue with the symlinking non-digest asset [task](https://github.com/mysociety/alaveteli/blob/develop/lib/tasks/assets.rake#L2).

**Comment by garethrees** [comment]
Presumably this fixes it just for us? Should Alaveteli come with an update to `config/httpd.conf-example`?

**Comment by gbp** [comment]
Ooh I will have to test this.

Linking to my comment on how to do this in UTM as it took me ages to find this:
https://github.com/mysociety/alaveteli/pull/7503#issuecomment-1490553549
