### ISSUE TITLE
Limit page navigator to the 500 results hardcoded limit

### ISSUE THREAD

**Issue by FozzieHi** [mysociety/alaveteli#7822]
As mentioned in [this issue](https://github.com/mysociety/alaveteli/issues/2137#issuecomment-1631497996).

If the page limit is 20 pages, then we shouldn't show any pages beyond that in the page navigation. This already seems to be implemented when searching requests, but not for authorities or users.

Below images from @garethrees in the above linked issue:
![Navigation limited to 20 pages](https://user-images.githubusercontent.com/282788/252906907-73766a23-fcf6-497e-9028-dee4e47343b5.png)
*Navigation limited to 20 pages*

![Example footnote about technical limitations of displaying content past page 20](https://user-images.githubusercontent.com/282788/252909721-d1f7a568-c184-44af-9368-844fb0a346a3.png)
*Example footnote about technical limitations of displaying content past page 20*

**Comment by WilliamWDTK** [comment]
A user has just got in contact with us at WDTK to report the issue of results pages being displayed in the navigation that cannot be viewed. I decided this was a more appropriate place to note this than #2137.

**Comment by garethrees** [comment]
This is desirable, but unlikely to be worked on in the next 12 months so closing for now.
