### ISSUE TITLE
Investigate issue with `inline` background job mode

### ISSUE THREAD

**Issue by gbp** [mysociety/alaveteli#7833]
Sweden used this mode and [experienced missing attachments](https://groups.google.com/g/alaveteli-dev/c/nSfq61tM_20) from their Active Storage on disk service. These could be recovered from the raw email so no data lost. The only difference between them and WDTK is the background job mode was set to `inline` rather than the default `server`.

I helped Sweden to setup Redis/Sidekiq and switched mode to resolve the issue for them.

https://github.com/mysociety/alaveteli/blob/c41bf9c8b9983cc6dcf1f1d32a17a3aa45bab7e4/config/general.yml-example#L1293-L1307

**Comment by garethrees** [comment]
Do we know what the problem was here? Inline processing _should_ act in the same way as we had prior to introducing ActiveJob.

**Comment by gbp** [comment]
I believe the issue is caused by some of the internal Rails' ActiveStorage jobs which are getting scheduled to be performed later and not run inline.

This wasn't an issue without ActiveJob and simply including ActiveJob changes the Rails behaviour.
