### ISSUE TITLE
Allow manual override of refusal advice.

### ISSUE THREAD

**Issue by HelenWDTK** [mysociety/alaveteli#7845]
A user contacted us to say that the system had detected that the response was a s40 refusal when it wasn't. They wanted us to remove the advice as it was misleading, but we can't currently do this.

**Comment by WilliamWDTK** [comment]
We've just had an example where section 35 was detected where it was, in fact, section 36.

Probably this sentence:

>The section 36 exemption applies only to information that falls outside the scope of section 35.

([source](https://www.whatdotheyknow.com/request/documents_related_to_funding_for#incoming-2385240))

**Comment by WilliamWDTK** [comment]
One could envision a system that permits the detection of multiple exemptions, and allows a user to select the relevant one(s) for continuing the process.
