### ISSUE TITLE
Inconsistent batch request counts

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/alaveteli#7851]
From the perspective of a `pro` `admin` who isn't a `pro_admin` on WDTK in respect of a batch that isn't mine:

https://www.whatdotheyknow.com/info_request_batch/2083 in the public view shows "Sent to 130 authorities…"

The admin view says there are 100 normal requests.

There appear to be duplicate requests within the batch.

**Comment by garethrees** [comment]
This is desirable, but unlikely to be worked on in the next 12 months so closing for now.
