### ISSUE TITLE
Sender's name not appearing on some incoming messages

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/alaveteli#7858]
On WhatDoTheyKnow, taking [this message](https://www.whatdotheyknow.com/request/closed_enforcement_notices_for_o#incoming-2389435) as an example, the sender's name doesn't appear in the header.

![image](https://github.com/mysociety/alaveteli/assets/99501342/f977f7f9-f04e-470e-98b3-b4b18ec659ae)

This same message has the sender's name set in the admin interface:

![image](https://github.com/mysociety/alaveteli/assets/99501342/d5b64470-5d3e-4953-a585-d52da64975f9)

**Comment by garethrees** [comment]
This is desirable, but unlikely to be worked on in the next 12 months so closing for now.
