### ISSUE TITLE
Do something with the UKBA "FAQ" robot reply

### ISSUE THREAD

**Issue by skenaja** [mysociety/alaveteli#79]
The standard UKBA response to many FOI requests is to send this massive FAQ reply:

http://foiwiki.com/foiwiki/index.php/UK_Border_Agency_standard_email_reply

It has this message at the bottom:
"If you have read this message and looked on the UK Border Agency website, but you have not found the information you require, please re-send your enquiry with "FAQ" in the subject/title line to: UKBApublicenquiries@ukba.gsi.gov.uk"
- A requester can get this FAQ many times in a request, meaning that the page is very cluttered, and it's hard to see the flow.  Suggest that if >1 is received, fold up all the previous versions into an smaller message section that could be expanded if required
- Replies are often ignored and trigger a new FAQ to be sent.  Have in place a mechanism to allow the requester to follow the instructions above,.
- Admin often get emails asking for the email addresses - show them by default in this one, overriding the auto-censor rules.

This is definitely a WDTK-specific issue.

**Comment by garethrees** [comment]
A specific case of #2045

**Comment by garethrees** [comment]
UKBA was marked as defunct in ~2013, so closing as no longer relevant.
