### ISSUE TITLE
Clarify the different user account Danger Zone options

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/alaveteli#7906]
This is possibly just a "me" problem, but I struggle a bit to understand the different options, and consistently do them in the wrong order.

![image](https://github.com/mysociety/alaveteli/assets/99501342/6c50a3c8-b1f7-42b1-8d36-558a600ef9b5)

**Comment by HelenWDTK** [comment]
+1 (It's not just you). One solution might be if we could have the one click close and anonymise button back.

**Comment by garethrees** [comment]
@WilliamWDTK I've had a stab at this in https://github.com/mysociety/alaveteli/pull/7927; does it help? I haven't closed this as I'm sure there's more that can be done, but either way I think any further comments will build on an improved version.

**Comment by garethrees** [comment]
Closing as improvements have been made. Can open new issues for any further specifics.
