### ISSUE TITLE
Only include active users in leaderboards

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#7946]
On `/statistics` we show the top requesters over the last 28 days. Sometimes users are in this list due to misuse and have had their account suspended. We shouldn't include these in the list.

While it's less likely for `/categorise/play`, we should also do this for the leaderboards there.

**Comment by chrismytton** [comment]
@garethrees As well as banned users, do you think we should exclude users who have closed their accounts from leaderboards?

**Comment by garethrees** [comment]
I think yes, to keep things simple. There's a `User.active` scope, so should just be using that to filter the existing list.
