### ISSUE TITLE
Update "view as HTML" to do processing in the background

### ISSUE THREAD

**Issue by gbp** [mysociety/alaveteli#7978]
Our view attachments in the browser feature, "view as HTML", is doing alot of processing inline in the web processes and this sometimes causes memory issues on the server and results in oom-kill running.

We should run `AttachmentToHTML` in the background. This is more complex than #7977 as this results in artefacts from the conversion process, these HTML files and images are currently stored on disk in the old attachment file cache. We should consider moving these into ActiveStorage as part of this issue or we could separated out into a second issue.

**Comment by garethrees** [comment]
This is desirable, but unlikely to be worked on in the next 12 months so closing for now.
