### ISSUE TITLE
Subject-based holding pen guesses show incorrect scores

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#7996]
Where the guess is based on subject the `id_score` / `idhash_score` shows as 100%, because we [set default values of `1`](https://github.com/mysociety/alaveteli/blob/0.44.0.0/app/models/guess.rb#L41-L49) if the guess doesn't have that info. This is misleading as it makes it look like subject-based requests are exact matches:

![Screenshot 2023-11-06 at 10 04 55](https://github.com/mysociety/alaveteli/assets/282788/e47bef31-d87b-46e6-a7ef-0b5c3d93ee73)

Related to https://github.com/mysociety/alaveteli/issues/7973

**Comment by gbp** [comment]
> Any reason not to return `0` instead of `1`?

No, that should be fine afaik.
