### ISSUE TITLE
Show PublicBody version history when handling PublicBodyChangeRequest

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#7997]
Almost every time I do one of these (for an existing authority) I open the body admin show page to see the version history to e.g. check that the proposed email isn't one we've already tried, or if we're using the current email for a specific campaigning reason.

Could just extract the history code to a partial and render under the form like so:

![Screenshot 2023-11-06 at 17 04 19](https://github.com/mysociety/alaveteli/assets/282788/14f8b88f-69f8-42c5-9c16-23f76798fbc5)

**Comment by mdeuk** [comment]
+1,  this would be a welcome improvement, as I often have the same issue.
