### ISSUE TITLE
Anchor links to public attachments from the admin panel don't work if there are lots of attachments

### ISSUE THREAD

**Issue by HelenWDTK** [mysociety/alaveteli#8042]
If you need to click "show all attachments" to view the attachment on the public page, then the link from the "eye" in the admin panel won't direct you to the correct message. These links should probably point to the attachment instead allowing you to download it.

eg: https://www.whatdotheyknow.com/request/meta_request_re_foi_22_026_ir_22#attachment-3901394 should load https://www.whatdotheyknow.com/request/907741/response/2191281/attach/10/FOI%2022%20062%20Response.pdf which is in this response https://www.whatdotheyknow.com/request/meta_request_re_foi_22_026_ir_22#incoming-2191281 but instead the link takes you to the top of the request page.

**Comment by garethrees** [comment]
The problem here is that the additional attachments are `display: none;` so the anchor can't find them.

Might be able to auto-unfold the "show more" link if the anchor exists but is not visible.

**Comment by garethrees** [comment]
This is desirable, but unlikely to be worked on in the next 12 months so closing for now.
