### ISSUE TITLE
Authority pages not updating for category changes

### ISSUE THREAD

**Issue by confirmordeny** [mysociety/alaveteli#8081]
e.g. https://www.whatdotheyknow.com/body/cabinet_office

Is tagged department_uk so authority page should say "A Ministerial Department of the UK Government".

as per: https://www.whatdotheyknow.com/admin/categories/315/edit?model_type=PublicBody

At first, I thought this was a caching issue but changes made the changes were made over 36 hours ago.

**Comment by gbp** [comment]
This doesn't seem fixed. I think maybe it now assuming top-level categories whereas we need to look at child categories as well.
