### ISSUE TITLE
Add “unlisted” `InfoRequest` prominence

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#8085]
As a site grows you inevitably end up with content that doesn’t break rules, but you also don’t want to go out of your way to promote. Originally backpage only excluded requests from internal search. As of https://github.com/mysociety/alaveteli/pull/6048 excludes from both internal and external search.

To give us more flexibility of how much amplification a request gets, we'll add a new “unlisted” prominence option for `InfoRequest` that excludes a request both from internal and external search (i.e,  the current backpage behaviour). “backpage” will become internally searchable, but not externally searchable (i.e. set an `X-Robots-Tag: noindex` header).

| Indexed by: | internal search? | external search? |
|---|---|:---:|
| `backpage` | `true` | `false` |
| `unlisted` | `false` | `false` |

We'll want to migrate requests currently with “backpage” prominence to “unlisted” to make the state of the currently backpaged requests match the new behaviour.[^1]

[^1]: I appreciate there's some faff in the renaming, but I think its worth it to make the names of each prominence make sense for the behaviour. To me "unlisted" sounds like "hard to find", and "backpage" makes it sound like it will appear in search results, but right at the end. In practice it'll still sort by relevance, but we can later tune the indexing prioritisation for backpaged requests to push them towards the end.

**Comment by mdeuk** [comment]
+1, this sounds like it _would_ be a beneficial thing to have.

**Comment by garethrees** [comment]
This is desirable, but unlikely to be worked on in the next 12 months so closing for now.
