### ISSUE TITLE
Allow requests to be flagged for deletion

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/alaveteli#8091]
Sometimes, when hiding requests, we may hide a request that we don't need or want to hold long term. However, we may want to retain it for a short while, so that the requester (or anyone else) can take a copy (or otherwise interact) as necessary. However, we do not want to forget to delete it, nor do we want to create extra work by setting reminders to delete something manually.

When requests are flagged for deletion, they should be deleted after a certain time period has elapsed. This duration could, perhaps, be customisable on the hiding interface. It should also be included on the message to the user, and possibly on the request page itself for the requester and admins, so it is know how long is left before it will no longer be accessible.

**Comment by garethrees** [comment]
Related to https://github.com/mysociety/alaveteli/issues/7393.

**Comment by WilliamWDTK** [comment]
This could also delete requests instantly if required, but just provide a convenient mechanism to let the user know what is happening.

**Comment by garethrees** [comment]
This is desirable, but unlikely to be worked on in the next 12 months so closing for now.
