### ISSUE TITLE
Allow admins to use the request hiding interface without sending a message to the user

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/alaveteli#8092]
At WDTK, in cases where admins are hiding an old request, we do not always think it is appropriate to inform a user that their request has been hidden. This is for a variety of reasons.

However, it is useful to be able to use the hiding interface on the main request administration page, particularly given the prominence reason it sets.

Therefore, it would be ideal if an option could be selected to not automatically send a message to the user. The default could change depending on the date the request was made or of the last action (ideally, from my perspective, the last action the user personally took).

**Comment by mdeuk** [comment]
> However, it is useful to be able to use the hiding interface on the main request administration page, particularly given the prominence reason it sets.

+1 - from a metadata perspective[^1], this is a win-win.

> Therefore, it would be ideal if an option could be selected to not automatically send a message to the user. The default could change depending on the date the request was made or of the last action (ideally, from my perspective, the last action the user personally took).

Making this something like the change requests, where there is an option to act _with_, or _without_ a message seems like it might be a good idea. Sending these messages on ancient requests just increases follow-up administration [^2], with not benefit to any party.

[^1]: having consistent reasons, and categorisations, would certainly help improve the quality of the metadata we have, which could serve as part of the continual improvement of administrative decision making quality.
[^2]: e.g. a ~five year old immigration correspondence that has long been forgotten, probably doesn't require a message.

**Comment by garethrees** [comment]
This is desirable, but unlikely to be worked on in the next 12 months so closing for now.

**Comment by garethrees** [comment]
Think the basic version of this we want is:

BEFORE

<img width="998" height="611" alt="Image" src="https://github.com/user-attachments/assets/85441b0a-f31f-45d8-b943-e94474e53ff3" />

AFTER

<img width="1007" height="617" alt="Image" src="https://github.com/user-attachments/assets/1a9ac168-ffb4-4029-a4b1-9e1d2118b7fd" />

The logic looks like it should be easy enough to change. The orange button would perform the current action of hide + notify, with the grey button just omitting [this part](https://github.com/mysociety/alaveteli/blob/develop/app/controllers/admin_request_controller.rb#L192-L205) of the action.

Might want to tweak the UI phrasing but I think it would be fine as in the screenshot above really – I think its clear enough what button would do what?
