### ISSUE TITLE
Displaying hiding message to user in-system

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/alaveteli#8093]
Currently, a user whose request has been hidden can see the prominence message that's visible to all. However, there will sometimes be extra information stored in the message they were sent. This will, of course, have been sent by email, but it may be useful to display it on the relevant content (perhaps hidden behind an arrow), since it is already stored in the event history. As in #7383, I think the prominence reason should be designed to be read by an external audience, so it could be useful to display the message sent to the user. Of course, not all requests are hidden through the hide function.

Also see #8092.

**Comment by garethrees** [comment]
This is desirable, but unlikely to be worked on in the next 12 months so closing for now.
