### ISSUE TITLE
Store and make visible a record of user-to-user messages sent or received

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/alaveteli#8097]
A user has contacted us to suggest that "[i]t would be helpful if the site stored [user-to-user] messages in [user] accounts," so that they can be reviewed at a later date.

**Comment by garethrees** [comment]
Going to close this as a "wontfix" as https://github.com/mysociety/alaveteli/issues/7099 is more likely, and this is quite adjacent to our core features and would come with a significant overhead in admin / user data concerns.
