### ISSUE TITLE
Improve user notification experience for multiple incoming messages on one request in a short time period

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/alaveteli#8098]
Some authorities send multiple emails in quick succession in a variety of circumstances.

The separate notifications for this do not make it obvious that they refer to different incoming messages, which causes confusion for some users.

There are several solutions that come to mind:

- Include basic details of the message (time, date, sender, number of attachments)
- Only send another notification if the user has viewed the request since the last one (would require user to be logged in, and for views to be tracked in this way)
- Perform some sort of notification batching (maybe up to 60 minutes) to combine them
- Simply not send a second notification if it is <x minutes after the last one for the same request.

We probably don't want to include the content of the message body in the notification, in order to keep everything more easily on-site.

**Comment by garethrees** [comment]
This is desirable, but unlikely to be worked on in the next 12 months so closing for now.
