### ISSUE TITLE
Look at subject/body length on form submissions to reduce spam

### ISSUE THREAD

**Issue by HelenWDTK** [mysociety/alaveteli#8101]
We've had a recent uptick in spam through the contact form where the subject line has been a copy of the message body, or very similar. It is unlikely that a genuine query would come with a subject many hundreds of characters long, so we could use this info to help reduce spam through the form.

**Comment by HelenWDTK** [comment]
Could expand this to character length of submissions too. We had a 3,000 word essay land in the WDTK inbox this morning.

**Comment by HelenWDTK** [comment]
+1 A message with a long subject line broke the inbox monster today. It also makes the correspondence harder to follow.

**Comment by WilliamWDTK** [comment]
The subject on the [mySociety contact form](https://www.mysociety.org/contact/) has a maximum length of 40 characters:
![Subject: This subject has to be relatively short. 0 of 40 character(s) left](https://github.com/user-attachments/assets/22149d08-8775-4346-9e27-14f72538ae64)

**Comment by WilliamWDTK** [comment]
The question is, would you want it to fail silently?

If it fails with an error message, some automatic spam systems may adapt to it.

However, failing silently is not wanted for genuine correspondents, since a genuine correspondent can adapt their previously unwieldy correspondence.

**Comment by WilliamWDTK** [comment]
We at WDTK have recently received a submission through the body change form with the notes field summing 21,230 words (136,317 characters).

**Comment by garethrees** [comment]
This is desirable, but unlikely to be worked on in the next 12 months so closing for now.
