### ISSUE TITLE
Sign in / log out issues 

### ISSUE THREAD

**Issue by HelenWDTK** [mysociety/alaveteli#8190]
We've had a recent uptick in user support about people encountering unexpected behaviour when trying to log in the WDTK.  Admins, including myself have found ourselves unexpectedly logged out. I have not been able to pin down the exact circumstances where this is happening, but both myself and @confirmordeny have observed it happening when we have multiple tabs open.

A user reported being repeatedly returned to the log in page with no explanation, and another talked of being stuck in a loop.

We have also had several pro users report being logged out

https://groups.google.com/a/mysociety.org/g/alaveteli-pro/c/5XQOkZoDFJ4/m/snBsNARwAAAJ
https://groups.google.com/a/mysociety.org/g/alaveteli-pro/c/NGMOOd814lM/m/ArXiwZuFAAAJ

The reports seem to have started around the bank holiday weekend.

**Comment by gbp** [comment]
Seems like there is something strange happening when calling [`render html: ...`](https://github.com/mysociety/alaveteli/blob/722c51e37f2e40fa1d0c817722e3453c6a81a47a/app/controllers/attachments_controller.rb#L51) and [updating the session](https://github.com/mysociety/alaveteli/commit/392af7292875c577188cdbe0fd7f581a5bcdac52) which is causing the session to be reset.
