### ISSUE TITLE
Add ability to apply censor rules by batch

### ISSUE THREAD

**Issue by HelenWDTK** [mysociety/alaveteli#8202]
Sometimes when dealing with a RtO form a pro user, we want to take action that applies to a specific batch of requests. This is not currently possible from the admin panel without applying rules to each request individually.

**Comment by HelenWDTK** [comment]
+1 This would have been helpful today.

**Comment by garethrees** [comment]
This is desirable, but unlikely to be worked on in the next 12 months so closing for now.
