### ISSUE TITLE
Prevent duplicate reports generating emails

### ISSUE THREAD

**Issue by HelenWDTK** [mysociety/alaveteli#8215]
There is no need to send a second/third etc email to the site admin team if a user repeatedly reports a request that is already in an error/flagged state. This makes it harder to keep track of outstanding issues in need of fixing, so we should prevent this. I'm thinking about:

- Delivery errors
- Requests flagged for admin attention.

**Comment by gbp** [comment]
How about we could look at the info request events to ensure there has been a `response`, or `followup` event since the last time a report was sent.

**Comment by HelenWDTK** [comment]
That might work. 

In some cases a bounce generates 2/3 response emails over 48/72 hours, and we get a message as each new one is classified, but those might just be too tricky to handle well.

**Comment by gbp** [comment]
I think the changes in #8217 will prevent this.
