### ISSUE TITLE
Stop search engines indexing contentless pages

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/alaveteli#8216]
I've noticed on a couple of occasions that Google returns search results for annotation and similar request pages. In the case of the former, it adds no useful content, and I can't see that the similar requests page is useful to be indexed and returned as a search result. Additionally, it may just be another thing to be anonymised when people request erasure.

We could consider this for the below, if not already done:
- The annotation page (`/request/SLUG/annotate`)
- Any links that always require a sign-in (reply, report, status update, request ZIP download)
- The similar requests page (`/request/SLUG/similar`)

**Comment by HelenWDTK** [comment]
Linked to #8132

**Comment by garethrees** [comment]
Closing in favour of #8132
