### ISSUE TITLE
Mistakenly destroyed issues

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#8229]
On 11th April some issues in this repo were mistakenly permanently destroyed. We managed to preserve at least some of the issue titles. Creating an issue here to record them for searchability.

* Add dropdown or similar with suggested comment when adding censor rules
* Renaming a user account can leave the profile url slug unchanged
* Make the tag edit box on the body admin page bigger.
* Add the ability to search by request email address to the admin interface
* RuboCop: Layout
* Ability to delete an incoming message but leave an explanation
* Consider practicality of generating alerts when Excel files containing hidden data are released
* Hide "Authority: Respond to request" in actions menu
* Improve post-report messaging
* Button to revert status of requests marked for admin attention

**Comment by garethrees** [comment]
I've bolded the ones which have some more important stuff / where work has gone in to shape a ready-to-go solution.

If we can find the issue IDs, we might be able to restore some amount via public archives:

* Consider practicality of generating alerts when Excel files containing hidden data are released [#2663](http://web.archive.org/web/20210204002441/https://github.com/mysociety/alaveteli/issues/2663)

**Comment by HelenWDTK** [comment]
Added: #8230

**Comment by HelenWDTK** [comment]
- [ ] Add dropdown or similar with suggested comment when adding censor rules
- [ ] Renaming a user account can leave the profile url slug unchanged
- [ ] Make the tag edit box on the body admin page bigger.
- [ ] Add the ability to search by request email address to the admin interface
- [ ] RuboCop: Layout
- [ ] Ability to delete an incoming message but leave an explanation
- [ ] Consider practicality of generating alerts when Excel files containing hidden data are released
- [ ] Hide "Authority: Respond to request" in actions menu
- [ ] Improve post-report messaging
- [ ] Button to revert status of requests marked for admin attention

**Comment by HelenWDTK** [comment]
Added https://github.com/mysociety/alaveteli/issues/8231

**Comment by HelenWDTK** [comment]
Added #8232

**Comment by HelenWDTK** [comment]
Added #8233 - This was reconstructed from archive.org and email, so may be an incomplete record.

**Comment by HelenWDTK** [comment]
Added #8235

**Comment by HelenWDTK** [comment]
Added #8236

**Comment by HelenWDTK** [comment]
Added #8237

**Comment by HelenWDTK** [comment]
These have now all been restored with the exception of the following two issues which I have been unable to locate:
-  Hide "Authority: Respond to request" in actions menu
-  RuboCop: Layout

**Comment by HelenWDTK** [comment]
Added #8238, so only the Rubocop is lost.
