### ISSUE TITLE
Add dropdown or similar with suggested comment when adding censor rules

### ISSUE THREAD

**Issue by HelenWDTK** [mysociety/alaveteli#8232]
Replaces Issue #7964, deleted in error:

On 18 October 2023 @HelenWDTK wrote:
At the moment the system suggests replacement text - I'd like something similar implementing for the comment field.

At the moment it is quite annoying to have to repeatedly type the same comment when needing to add multiple censor
rules, and we usually add these for a very limited number of reasons.
***
On 19 October 2023 @garethrees wrote:
Should be quite easy to render recent comments (`CensorRule.last(3).pluck(:last_edit_comment)`) and display
them with a button that inserts the text into the current comment field.
![4](https://github.com/mysociety/alaveteli/assets/120410992/8688936f-eab7-4c48-aafb-8a9feb5bb49e)
Would also be good to show a preview of the comment for the "use previous" button that appears when editing a rule
while we're at it.

Might want to reduce the width of the comment field a tad to allow for the previous/recent comments section.

**Comment by garethrees** [comment]
This is desirable, but unlikely to be worked on in the next 12 months so closing for now.
