### ISSUE TITLE
Improve post-report messaging

### ISSUE THREAD

**Issue by HelenWDTK** [mysociety/alaveteli#8234]
Replaces #7778, deleted in error:

On 19 June 2023, @garethrees wrote:
One of the issues raised in mysociety/whatdotheyknow-private#219 was whether we should auto acknowledge reports. This would get in to some annoying details with threading and we guess this is probably on the lower end of impact.

What we could do fairly easily is improve the text that appears when something is reported.

Currently you fill out the form...
<img width="1074" alt="246778403-09406242-2146-4a53-b5b6-1920b1a2b2c4" src="https://github.com/mysociety/alaveteli/assets/120410992/e66403fc-5ce1-4265-ba39-93d5674fb5a0">
...and on submission just get a basic success flash...
![](https://user-images.githubusercontent.com/282788/246778485-b6966c26-29f4-4862-9710-71b06ca78c2e.png)
We could add an overridable partial to that flash, so that site runners can either add more to the message (a list of bullet points of the process admins will follow) and/or a link to a help page that describes the process in more detail.

We'll want to make this generic in alaveteli, and then add some WDTK specific content.

Bonus points if we have a @report object available that details the particular report made that we could use to dynamically pick the content to render (as in something like...)
```
<%=
       case @report.reason
       when 'defamatory'
            render partial: 'report/next_steps/defamatory'
       when 'vexatious'
            render partial: 'report/next_steps/vexatious'
       else
            render partial: 'report/next_steps/general'
%>
```
***
On 19 June 2023 @mdeuk wrote:

> One of the issues raised in mysociety/whatdotheyknow-private#219 was whether we should auto
> acknowledge reports.

You must be a mind reader, as this was something I pondered over the weekend.

If this is something we want to do, we can do it once the Monster handles labelling of inbound mail. I would envision
this being a generic response, rather than one that quoted the report itself[1]

Early draft copy

An early draft of what this could look like. It would need refinement.

> Case reference: XXX
> Thank you for taking the time to make us aware of your concerns.
> Our team will review the information you've provided, along with the request itself, and get back to you
> in due course.
> For more information about how we handle these cases, please see https://www.whatdotheyknow.
> com/help/how#what_happens

Related:

- mysociety/whatdotheyknow-theme#740 (comment)
### Footnotes
1. so as to avoid backscatter containing PII. We would probably also want to send from DoNotReply@. ↩
***
On 19 June 2023 @garethrees wrote:
🕴
Yeah, I think auto-acks feels more the responsibility of the support system than Alaveteli, though I'm not sure I could fully back up my reasoning for that.

I think let's see where improving the Alaveteli UI gets us, and then ticket up auto-acks for the monster if it still feels we want it.
***
On 19 June 2023 @mdeuk wrote:

> Yeah, I think auto-acks feels more the responsibility of the support system than Alaveteli

Yup, I agree... it's certainly how you would do it with a ticketing system, so for re-user compatibility, I think
'outsourcing' the function back to whatever runs their support "system" would be better.
***
On 4 July 2023 @garethrees wrote:
We've got some good content about how we deal with these reports at https://www.whatdotheyknow.com/help/how#what_happens. Here's how I think they map to the form field values.
<img width="641" alt="Screenshot 2024-05-01 at 19 32 13" src="https://github.com/mysociety/alaveteli/assets/120410992/e5ff5232-c0eb-4d7c-818d-de67fba9fe3c">
I expect many people report content having never seen this guidance.

Perhaps instead of linking to this in the post report flash, we render the guidance specific to the currently selected field
on the new report form page.
![](https://user-images.githubusercontent.com/282788/250835839-8c49eee2-49b1-4146-a9b1-71f38d6eb8e3.png)
We could extract each section to a partial (report/how/vexatious – similar to above) and render if it exists, or fall
back to the generic message.
***
On 5 July 2023 @HelenWDTK wrote
We could do both. Render the guidance on the report form, then send a generic acknowledgement to confirm that the
report has been received.
***
On 13 July 2023 @garethrees wrote:
Just noting here that we have a help section related to reporting at https://www.whatdotheyknow.com/help/about#reporting_unavailable

**Comment by garethrees** [comment]
This is desirable, but unlikely to be worked on in the next 12 months so closing for now.
