### ISSUE TITLE
Renaming a user account can leave the profile url slug unchanged

### ISSUE THREAD

**Issue by HelenWDTK** [mysociety/alaveteli#8236]
Replaces #7918, deleted in error

On 27 September 2023 @HelenWDTK wrote:
I renamed a user account using the admin interface, and the public url for the user profile remained the same, leaving
no way to change the original url.

I was expecting the url to change, and the old one to either not work, or appear as a slug that I could then delete.

The user was a former pro user, who had made over 1,000 requests.
***
On 3 November 2023 @garethrees wrote:

This should be a redirect (`301` probably?) to the most recent slug, but instead it finds/presents the user record under
the old slug:
```
$ curl -I https://www.whatdotheyknow.com/user/AN_OLD_USER_SLUG
HTTP/2 200
```

**Comment by garethrees** [comment]
This is desirable, but unlikely to be worked on in the next 12 months so closing for now.
