### ISSUE TITLE
Topic pages - make search box less prominent

### ISSUE THREAD

**Issue by confirmordeny** [mysociety/alaveteli#8240]
Currently on topic pages, the search box appears at the top (centre) and takes up quite a bot of space. Consider giving it less prominence.

**Comment by HelenWDTK** [comment]
+1 - They look much better without. I'm thinking something like this:
<img width="1237" alt="Screenshot 2024-10-22 at 21 17 38" src="https://github.com/user-attachments/assets/2b13f753-9ba2-4f42-b1c8-f71d1fc3e36f">

**Comment by garethrees** [comment]
Superseded by https://github.com/mysociety/alaveteli/issues/8445
