### ISSUE TITLE
Erronous shebang in docker/reset

### ISSUE THREAD

**Issue by andersjl** [mysociety/alaveteli#8244]
The shebang is #!/bin/sh, but on my Ubuntu 22.04 the script does not run with bash in sh mode.

I see three solutions, which is why I do not make a pull request:

1. Change the shebang to #!/bin/bash
2. Change the script so that it runs in sh mode
3. Change the documentation to do "bash docker/reset" rather than "docker/reset" (and probably remove the shebang).

**Comment by garethrees** [comment]
Definitely want the script to be executable as `docker/reset`, so I'd rule out 3 as an option.

I don't have a preference between option 1 and 2. I guess I'd say option 2 if its trivial; option 1 if option 2 would take a significant amount of time or involves downsides that we wouldn't want to accept.

**Comment by andersjl** [comment]
Ok, I will try 2, then?
