### ISSUE TITLE
Make it possible to extend an embargo by clicking on a link in the expiration reminder email.

### ISSUE THREAD

**Issue by HelenWDTK** [mysociety/alaveteli#8256]
I got an email today about an embargoed request that said:

> The following request will be made public on WhatDoTheyKnow in the next week. If you do not wish this request to go public at that time, please click on the link below to keep it private for longer.

Clicking on the link does not extend the embargo, it takes me to the request page, where I have to scroll down and select a new option from the dropdown to extend it. This was not intuitive. It'd be good to be able to default extend the embargo for 3 months with a single click.

**Comment by garethrees** [comment]
This is desirable, but unlikely to be worked on in the next 12 months so closing for now.
