### ISSUE TITLE
Show that foi_no authorities are not subject to FOI on the authority search listing pages

### ISSUE THREAD

**Issue by HelenWDTK** [mysociety/alaveteli#8260]
At the moment, the `foi_no` tag adds a message on the authority page indicating that the body is not subject to FOI. It would be good if this could also appear on the search/ category listing pages before the rest of the authority description text. This would help make it even clearer to users that these authorities are not under any obligation to respond.

This was suggested by an organisation that we list who are not subject to FOI, but I also think it's a great idea that could reduce confusion.

**Comment by garethrees** [comment]
This is desirable, but unlikely to be worked on in the next 12 months so closing for now.
