### ISSUE TITLE
Allow users to check authority email address

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#8264]
A potential replacement for https://github.com/mysociety/alaveteli/pull/8263.

Some users or authority staff may wish to check whether we're using the correct email address for an authority. Previously we'd just show the email address, but that's too open to abuse.

Instead we could allow the user to enter the expected address, which we then compare to our records. If the addresses don't match, we can point them towards the change request form.

![Screenshot 2024-05-17 at 15 11 21](https://github.com/mysociety/alaveteli/assets/282788/447642b8-dc9c-427a-b337-6d7599cbfafe)

**Comment by HelenWDTK** [comment]
If they are wanting to monitor that it is up to date, could we let them sign up to get an alert if we change it? A bit like the land registry do for property charges etc.

**Comment by garethrees** [comment]
And/or could do something similar to the request event history page.

**Comment by WilliamWDTK** [comment]
> If they are wanting to monitor that it is up to date, could we let them sign up to get an alert if we change it? A bit like the land registry do for property charges etc.

We could automatically send an alert to both the old and the new when a change is made, as well as the submitter of a change request (with only one email if the submitter of the change request matches either the old or the new).

---

> And/or could do something similar to the request event history page.

I think it would be good to publicly list changes to bodies. That's probably a separate issue, though.

**Comment by olineham** [comment]
The vast majority of our authority email addresses are already displayed on the agencies' own websites. I've also never had any complaints in 13 years about displaying authority addresses. We tell users and authorities to view the address, and I consider it part of being transparent.

I guess WDTK must have this problem, but we don't, so removing the feature just adds admin workload for no gain. I'm not excited to see the feature has already been removed in develop - I'll have to look at putting it back in a fork or theme. (And I'm trying really hard to defork and not overcomplicate the theme.)

Maybe it could've been an option?

**Comment by WilliamWDTK** [comment]
A user has contacted us with a request that the information be restored.

---

> I guess WDTK must have this problem
My understanding is that the issue on WDTK was an instance of someone bulk-harvesting email addresses, which I think was causing server load issues.

**Comment by WilliamWDTK** [comment]
In any case, I agree that making it an option for different installations is probably a good idea.

**Comment by WilliamWDTK** [comment]
Also, if one still values the ability for people to actually view the email address, but wants more protection, one could require someone to be signed in to view it, although that perhaps doesn't add a great deal.

**Comment by confirmordeny** [comment]
That could work if we restricted it to people with verified email addresses and we limited each user to three lookups a day (say).

**Comment by garethrees** [comment]
This is desirable, but unlikely to be worked on in the next 12 months so closing for now.
