### ISSUE TITLE
Admin navbar is not fully visible using mobile

### ISSUE THREAD

**Issue by HelenWDTK** [mysociety/alaveteli#8288]
The black admin nabber does not fully display on mobile, making some options inaccessible. You can work around it by rotating your phone, but a more mobile friendly solution would be better.

**Comment by garethrees** [comment]
Here's how it looks:

![Screenshot 2024-06-14 at 17 56 03](https://github.com/mysociety/alaveteli/assets/282788/fce8ff8c-0f19-4e58-9539-b18f515ab9e9)

Bootstrap supports a responsive nav: https://getbootstrap.com/2.2.0/components.html#navbar

It looks like we've even half-attempted to use this: https://github.com/mysociety/alaveteli/blob/1d5a50919cb8ec4db55124c107d3cb9e57334d40/app/views/admin_general/_admin_navbar.html.erb#L6

Applying the following gets us nearly there, but borks the padding for some reason:

```diff
diff --git a/app/assets/stylesheets/admin.scss b/app/assets/stylesheets/admin.scss
index c1e7df9d9..17b7b64d0 100644
--- a/app/assets/stylesheets/admin.scss
+++ b/app/assets/stylesheets/admin.scss
@@ -47,6 +47,7 @@ body.admin {
   line-height: 20px;
 
   @import "bootstrap";
+  @import "bootstrap-responsive";
 
   #main {
     flex: 1;
diff --git a/app/views/admin_general/_admin_navbar.html.erb b/app/views/admin_general/_admin_navbar.html.erb
index 23384a12a..f6a440fdc 100644
--- a/app/views/admin_general/_admin_navbar.html.erb
+++ b/app/views/admin_general/_admin_navbar.html.erb
@@ -2,8 +2,16 @@
 <div id="admin-navbar" class="navbar navbar-fixed-top navbar-inverse">
   <div class="navbar-inner">
     <div class="container">
+
+      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
+        <span class="icon-bar"></span>
+        <span class="icon-bar"></span>
+        <span class="icon-bar"></span>
+      </a>
+
       <%= link_to 'Alaveteli', frontpage_path, :class => "brand" %>
-      <div class="nav-collapse">
+
+      <div class="nav-collapse collapse">
         <ul class="nav">
           <% if session[:user_circumstance] == 'login_as' %>
```

![Screenshot 2024-06-14 at 17 57 39](https://github.com/mysociety/alaveteli/assets/282788/0b1380f8-b5f9-4964-b093-5fa1270f09d4)

![Screenshot 2024-06-14 at 17 57 55](https://github.com/mysociety/alaveteli/assets/282788/62629732-e28e-40ec-9f68-dbecb9f77497)
