### ISSUE TITLE
Feature Request: Allow a request to be split between different departments

### ISSUE THREAD

**Issue by benrfairless** [mysociety/alaveteli#8300]
In Australia, It's possible for a request to be partially transferred, so 2 departments are working on the same request at the same time (depending on the material).

I'm not sure the best way to do this, but it would be good if there was a way to specify that the request was being handled by more than one authority.

**Comment by HelenWDTK** [comment]
+1 We occasionally come across something similar in the UK, when all/part of the request is transferred to another authority. At the moment, we tend to suggest users indicate what has happened using annotations, but it can be confusing, and is less than ideas. 

Figuring out some way to better handle requests that are transferred by linking them to more than one authority could be helpful. This came up in user support that I dealt with this morning.

**Comment by garethrees** [comment]
This is desirable, but unlikely to be worked on in the next 12 months so closing for now.

**Comment by HelenWDTK** [comment]
+1 This happened again recently. the second authority used a do not reply address and the best we could do was tell the user to write back to authority 1 and ask them to write to authority 2
