### ISSUE TITLE
Stop search engine indexing of `/request_event/` pages

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/alaveteli#8310]
On WhatDoTheyKnow, `https://www.whatdotheyknow.com/request_event/` pages seem to have been indexed in Google, which I'm not sure we want.

**Comment by garethrees** [comment]
Strange that it indexes these even though [we use a `moved_permanently`](https://github.com/mysociety/alaveteli/blob/15c547e8ac4e8726f4eb89d03ce31ce7c5dd660a/app/controllers/request_controller.rb#L328-L344) status code.

These are only redirect to something that's already public (e.g. https://www.whatdotheyknow.com/request_event/15105960 redirects to the associated incoming message associated with the event https://www.whatdotheyknow.com/request/admission_statistics_202275#incoming-2320286), but probably does result in some amount of cached snippet proliferation. In some cases it looks like the snippet is generic "about WDTK", but other cases request content is cached.

In any case I agree, seems like these ought not to be indexed; we want the canonical request pages indexed and these URLs are more convenience helpers for the API.
