### ISSUE TITLE
Replace pdftohtml with pdf.js

### ISSUE THREAD

**Issue by henare** [mysociety/alaveteli#833]
pdf.js is pretty awesome but I wonder what the downsides of doing this might be? Compatibility? Mobile?

**Comment by WilliamWDTK** [comment]
This is perhaps linked to a possible problem (not directly reported to WDTK) where a PDF table was made difficult to read by conversion to HTML.

**Comment by garethrees** [comment]
This is desirable, but unlikely to be worked on in the next 12 months so closing for now.
