### ISSUE TITLE
Attempting to add a profile photo sometimes causes users to be logged out

### ISSUE THREAD

**Issue by HelenWDTK** [mysociety/alaveteli#8346]
We had a user contact us to say that when they tried to complete the process of adding a profile picture, the site logged them out of their account and gave them the message that they must be logged in to change their photo. They were eventually able to fix it themselves, but the behaviour was also confirmed by one of the WhatDoTheyKnow volunteers who tested it with their own account.

**Comment by WilliamWDTK** [comment]
Another user has got in touch, having experience this problem

**Comment by HelenWDTK** [comment]
+ 1 Another user has informed us about this

**Comment by garethrees** [comment]
This is desirable, but unlikely to be worked on in the next 12 months so closing for now.

**Comment by HelenWDTK** [comment]
Noting another occurrence of this today
