### ISSUE TITLE
Batch dashboard arrow icon clipped

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#8347]
![Screenshot 2024-07-30 at 09 28 15](https://github.com/user-attachments/assets/aa5f49b4-4923-4980-8fd0-c2ed5324a62a)

**Comment by HelenWDTK** [comment]
Changing the left and right borders on the down arrow icon from 4px to 6px fixes this.

**Comment by gbp** [comment]
ecb52f8cf938c4510c7b519507235539ddf1bd9d is the first bad commit
