### ISSUE TITLE
Allow more interactivity with requests

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/alaveteli#8378]
A user has got in touch with WDTK support to suggest that to stop completed request being forgotten, that there be some interactivity, such as:
> 1. Simple Like/ Don't like button
> 2. Separate Like/Don't like for both FOI and Response
> 3. 5 star rating (similar to 1 & 2) above
> 4. Amazon style star rating with user comments
> 5. No of views

This is potentially already achieved to a certain extent by the track feature, which is promoted on AsktheEU.org, but I think we've noted potential problems with it on WDTK, and don't currently do it.

**Comment by garethrees** [comment]
This is desirable, but unlikely to be worked on in the next 12 months so closing for now.
