### ISSUE TITLE
Resend events on requests to not display associated admin user

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/alaveteli#8382]
When reviewing a request to determine which admin had re-sent it, I noticed that the `resent` event does not appear to record this, or, at least, does not display it for `admin` users to view.

For example:
![Screenshot 2024-09-11 at 18-20-21](https://github.com/user-attachments/assets/0e0fdbb6-f1ee-4e10-89cf-1922c01330a9)

**Comment by garethrees** [comment]
This is desirable, but unlikely to be worked on in the next 12 months so closing for now.
