### ISSUE TITLE
InfoRequest level censor rule was not applied

### ISSUE THREAD

**Issue by laurentS** [mysociety/alaveteli#8387]
We received a message from a user requesting to hide their name from an incoming message. I added a censor rule on the info request, but it never was applied on the public page (I could see it in effect for admins), even several weeks later, which we found out after receiving a second request from the same person.

After running `IncomingMessage.find(xxx)._cache_main_body_text` in the console, the problem was fixed.
However, I wonder how this could happen. We are running sidekiq for background job queues, my understanding is that jobs should not be lost because of a server reboot or similar situations. What scenarii could lead to the job being skipped? Are there counter measures we can put in place to ensure this does not happen again?
We were running alaveteli 0.44.0.0 at the time of the bug. I came across https://github.com/mysociety/alaveteli/issues/3959 which suggests that this was fixed several years ago.

**Comment by nhatlaso1** [comment]
I think this will help you.

https://mega.nz/file/1vkGlJTL#yU-SJLlIilF0mx5qwpPOd3BM8iKZqOJLEQUStR76rrQ
I put the necessary dlls in the archive

**Comment by garethrees** [comment]
This is desirable, but unlikely to be worked on in the next 12 months so closing for now.
