### ISSUE TITLE
check-recent-requests-sent flags some emails incorrectly

### ISSUE THREAD

**Issue by laurentS** [mysociety/alaveteli#8392]
I regularly receive (for the past couple of years at least) an email from the `check-recent-requests-sent` script with lines like:
```
failed to find request sending in MTA logs for request id <some-id> <some_url_title> (check envelope from is being set to request address in Ruby, and load-mail-server-logs crontab is working)
```

When checking the request page, the corresponding outgoing message is marked as "Delivered".

Looking into the code, I noticed that (for `postfix`, which we use), the check is for `dsn=2.0.0` in the logs, but some servers reply with `dsn=2.6.0` instead (`outlook` seems to always reply `2.6.0` and never `2.0.0`).

I've not been able to find a clear explanation about what `2.6.0` means, and why it replies with it instead of the usual `2.0.0`. MS forums are very vague about it, but mostly seem to consider that the email was delivered, and it's now up to the outlook receiving server to deal with the message (what the leading `2` means).

But reading through [RFC3463](https://datatracker.ietf.org/doc/html/rfc3463) (which describes the codes used by [RFC3464](http://tools.ietf.org/html/rfc3464)) I see [first](https://datatracker.ietf.org/doc/html/rfc3463#section-2):

```
      2.XXX.XXX   Success

         Success specifies that the DSN is reporting a positive delivery
         action.  Detail sub-codes may provide notification of
         transformations required for delivery.
```
and [then](https://datatracker.ietf.org/doc/html/rfc3463#section-3.7):
```
      X.6.0   Other or undefined media error

         Something about the content of a message caused it to be
         considered undeliverable and the problem cannot be well
         expressed with any of the other provided detail codes.
```
which I concatenate as "the email was delivered, but it's undeliverable and I can't tell you why".

This code does not make sense to me. Has anyone else looked into it?

I would be tempted to modify [the code](https://github.com/mysociety/alaveteli/blob/9917dc2e6b312f7e11cb72c200b444c6ff7811ec/app/models/mail_server_log.rb#L161) in alaveteli to also accept `2.6.0`, but I'd like to confirm this with others first.

Some stats: our db has 76k log lines with `2.0.0` and 5.4k lines with `2.6.0`, so about 7% of our outgoing emails hit this. Of the 5.4k lines, ~90% also contain `outlook`.

EDIT: for what it's worth, I tested our server with https://www.mail-tester.com (got 10/10) and confirmed that everything is ok from MS's perspective via https://sendersupport.olc.protection.outlook.com/snds. So it's unlikely that this means "marked as spam".

**Comment by garethrees** [comment]
This is desirable, but unlikely to be worked on in the next 12 months so closing for now.
