### ISSUE TITLE
Admin todo list crashes after hiding a comment

### ISSUE THREAD

**Issue by laurentS** [mysociety/alaveteli#8402]
To reproduce (as an admin user):
- edit a comment in the admin, eg: `admin/comments/395/edit`
- change its `Admin attention requested` to "yes" and save
- go to `/admin`, the page crashes.

This is because `Comment.attention_requested` is `true` so it gets picked up [here](https://github.com/mysociety/alaveteli/blob/7a3ae911b75d840634dceffda438fdc4474f2e48/app/controllers/admin_general_controller.rb#L57) and the template then tries to call `simple_date(item.last_reported_at)` [here](https://github.com/mysociety/alaveteli/blob/7a3ae911b75d840634dceffda438fdc4474f2e48/app/views/admin_general/_to_do_list.html.erb#L85) but there is no `report_comment` event, so it ends up with `simple_date(nil)` which causes the crash.

The fix is to jump in the db, find the offending comment and then edit it and clear the attention flag. However, I don't think the admin page should crash this way.

This happened to us because a user reported a comment off platform (it was their own comment, which they posted on the wrong page), and I mistakenly marked the comment as requesting attention when hiding it.

## Options to fix:
- handle `nil` in `simple_date` to show `-` or something similar
- fallback on the comment date in `Comment.last_reported_at` so that the latter method always returns a date.
- or simply test for `nil?` in the template and display something else than the date. This has the benefit of no unintended side effects.

What seems most logical to you? Happy to send in a small patch if it helps.

**Comment by garethrees** [comment]
Ah, I guess the admin interface made the assumption that even admins would escalate issues via the public UI (which always has the nice side effect of using what users see as much as possible).

I think option two would be useful – "fallback on the comment date in `Comment.last_reported_at`", perhaps like:

```rb
# First look for the report;
# Failing that, make the assumption that the last update was when it was marked for attention;
# Still return nil when the comment isn't "reported"
def last_reported_at
  last_report.try(:created_at) ||
    updated_at if attention_requested?
end
```

**Comment by garethrees** [comment]
This is desirable, but unlikely to be worked on in the next 12 months so closing for now.
