### ISSUE TITLE
Add a preview button to the admin interface for notes/request categories

### ISSUE THREAD

**Issue by HelenWDTK** [mysociety/alaveteli#8403]
We have rich text support now, which is great. It'd be good to be able to see how content will be displayed before it goes live on the site, so we can check things are displaying as I would expect. I'd like a preview button that renders the note/topic page content in the admin interface so I can see it and edit it without needing to click away and come back.

**Comment by garethrees** [comment]
This is desirable, but unlikely to be worked on in the next 12 months so closing for now.
