### ISSUE TITLE
Requests with reduced prominence should appear on requestor's "My requests" page

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#843]
Requestors, but not the world at large, can access requests with a prominance "requestor only".

Users currently have to keep a record of requests which have been hidden in this way so they can continue to access them. 

This can be annoying from a requestor's perspective; and it also causes some support requests from users asking how they can get at their "requester_only" requests. 

Users appear to expect to find their "requester_only" requests on their "my requests" page. 

Obviously care should be taken not to expose these requests more generally in search results / listings on the site.

**Comment by RichardTaylor** [comment]
Adding a +1 as another user has been confused by the fact we don't do this. 

If we've made a users' requests requester_only they're probably someone who has misused the service and improving the service for those who misuse it shouldn't be a priority. The motivation for addressing this should be reducing support mail.  It doesn't feel like a significant enough cause of correspondence from users to address.

**Comment by RichardTaylor** [comment]
Easier-admin label added as this feature could prevent subject access requests and make responding to them easier.

**Comment by RichardTaylor** [comment]
This should also apply to backpaged requests. A user should be able to see their own backpaged requests on their user page when they are logged in.

**Comment by WilliamWDTK** [comment]
A user has recently got in touch with us at WDTK, concerned that their request had been removed from the site, when it had just been made `requester_only`.

**Comment by garethrees** [comment]
This is desirable, but unlikely to be worked on in the next 12 months so closing for now.
