### ISSUE TITLE
"Contact us" link in sidebar of previously reported request does not lead to contact form

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/alaveteli#8435]
The "contact us" link in the sidebar of a request that has previously been reported, but subsequently had its status reset does not lead to a contact form (i.e. [`https://www.whatdotheyknow.com/help/contact`](https://www.whatdotheyknow.com/help/contact) or [`https://www.whatdotheyknow.com/help/contact#wdtk`](https://www.whatdotheyknow.com/help/contact#wdtk)), as I would expect, but instead to [`https://www.whatdotheyknow.com/help/requesting`](https://www.whatdotheyknow.com/help/requesting).

![image](https://github.com/user-attachments/assets/f770668c-ebfe-4f6a-a0f9-6e1ee2b85382)

**Comment by garethrees** [comment]
This is desirable, but unlikely to be worked on in the next 12 months so closing for now.
