### ISSUE TITLE
When a requester sends a followup in a request marked to allow responses from authority_only, reset it to anybody

### ISSUE THREAD

**Issue by hsenag** [mysociety/alaveteli#863]
In http://www.whatdotheyknow.com/request/school_applications_broken_by_fa

the requester sent the request in March, then an internal review request in December., by which time the request had become "Allow new responses from authority_only". One of the school governors then tried to reply in January from his own email address, which wasn't associated with the school.

I believe the current logic stops new outgoing messages from being sent from "old" requests that are completely closed: in this case it should either do the same thing, or the request should be reset to allow responses from "anybody". I'd favour the latter.

**Comment by RichardTaylor** [comment]
On WhatDoTheyKnow we've had to re-open 

https://www.whatdotheyknow.com/admin/requests/277868

to responses but the latest follow-up message from the requestor was only a month old.

**Comment by RichardTaylor** [comment]
A public body replying from a different domain to the public body request address got a bounce at:

https://www.whatdotheyknow.com/admin/requests/308179

There had been a follow up message the day before so had the suggestion in this ticket been in place it would have been re-opened to "anybody".

**Comment by RichardTaylor** [comment]
Another example where a public body was trying to reply from a different domain, where there had been a follow-up just over a month before

https://www.whatdotheyknow.com/admin/requests/293154

Had the suggestion in this ticket been in place then the authority wouldn't have experienced a bounce and a volunteer wouldn't have had to re-open the request and write asking the authority to re-send their response.
