### ISSUE TITLE
Hiding a request can be done in two different ways in the admin interface

### ISSUE THREAD

**Issue by mlandauer** [mysociety/alaveteli#867]
You can go to a request page and edit the metadata "prominence" directly or in the "Actions" section "Hide the request and notify the user".

As an admin I've already found myself having to hide a request. Because I managed to do it one way (by editing the prominence directly) I didn't even realise until now that there was another way of doing it.

I think it would be better if there was only one way to hide a request.

**Comment by garethrees** [comment]
Closing as the two routes serve different purposes.

Actions generate a message to user; editing doesn't and allows more specific values to be chosen.
