### ISSUE TITLE
Logic to force users to classify requests before making new ones can be bypassed

### ISSUE THREAD

**Issue by hsenag** [mysociety/alaveteli#888]
Normally users who haven't classified previous responses are stopped from making new requests and instead directed to a page saying "classify these responses".

A user noticed that if you logout, start making a new request, and then login again, WDTK doesn't stop you from making it. When I tried to reproduce it a couple of times, once it did stop me, and once it didn't stop me - I'm not quite sure what the difference was.

Anyway, I don't think this is a big deal because we're just trying to encourage people in the right direction, not be 100% secure, but it's probably worth having a ticket just to track that the bug exists.

**Comment by garethrees** [comment]
Closing this as I think this scenario is pretty rare. Can reopen if it becomes a really big problem though.
