### ISSUE TITLE
"View as HTML" page should be generated from censored binary documents

### ISSUE THREAD

**Issue by hsenag** [mysociety/alaveteli#934]
Currently, PDF attachments are first converted to HTML, then the PDF and the HTML versions are censored separately. Sometimes PDFs need custom censor rules based on the internal representation of the PDF. So it's also necessary to add a "plain text" rule to catch the HTML version and it's easy to forget to do this.

There's also a small risk that future changes to the HTML extraction would defeat the censor rule - the closer to the original source the censoring is done, the better.

**Comment by HelenWDTK** [comment]
+1 I'm frequently having to create extra censor rules specifically to deal with character encoding in the html preview. It also makes removing images from PDF files using censor rules much harder than it needs to be.

**Comment by gbp** [comment]
Done in https://github.com/mysociety/alaveteli/pull/7979
