### ISSUE TITLE
resolve "no parts on multipart mail" errors

### ISSUE THREAD

**Issue by mhl** [mysociety/alaveteli#940]
About 0.4% of the emails we've received have a single MIME part with a missing final boundary, which currently raise the exception `"no parts on multipart mail"`. There is a test for this type of malformed email (currently marked "pending") here:

  https://github.com/mysociety/alaveteli/blob/527669bdb09a5d3add9270983a93320555e8bf7c/spec/lib/mail_handler/mail_handler_spec.rb#L348

Ideally, we should still return the single part for these malformed mails. (Incidentally, in the random sample these are all from the Department of Health.)

**Comment by gbp** [comment]
I can't recall ever seeing this spec fail - it has been enabled since 46e7df935929793fafb6069fbd272f5a35752e89
