### ISSUE TITLE
JSON (and atom feed) only returns first 25 results...

### ISSUE THREAD

**Issue by mlandauer** [mysociety/alaveteli#986]
... and there is no ability to get the next lot of results

See this thread on the alaveteli-dev mailing list: https://groups.google.com/forum/#!topic/alaveteli-dev/m45iUDT0OSI

**Comment by athornz** [comment]
Any update on this feature? I'm attempting to build an android app to consume the _API_, but only the first 25 results is not that useful :)

**Comment by HNygard** [comment]
#2732 will solve the same issue

As I wrote in #2732 :

I'm looking for the same read API. I want a list of all requests matching my tag.

I'm currently using this URL to get JSON data or my search: https://www.mimesbronn.no/feed/search/tag:mt-postliste-v2.json

At the moment this returns 25 events for 8 requests.

If I look at search page, there should be 12 requests:
https://www.mimesbronn.no/en/search/tag:mt-postliste-v2/all

Currently there is no place I can get the whole list.

**Comment by mlandauer** [comment]
We (as in "righttoknow.org.au") have slammed into this problem again. There's some external data analysis / data visualisation folk who we are working with to do some big picture analysis and visualisation on the data in our Alavateli instance. I was hoping that we could point them at the json feed and that would give them a safe way to get at most of the publically accessible information on the site without having to scrape it.

I'd rather avoid trying to do a custom database dump for them as I want to be absolutely sure I'm not releasing any private information and the schema for Alaveteli is pretty complicated so there's lots of room for making mistakes.

Is there any advice on how to work around this other than what @crowbot suggested in https://groups.google.com/g/alaveteli-dev/c/m45iUDT0OSI
