### ISSUE TITLE
add a button to reset a request in a "requires admin" state back to its previous state

### ISSUE THREAD

**Issue by hsenag** [mysociety/alaveteli#995]
There are a few request statuses that generate "FOI response requires admin" emails - error_message, attention_requested, requires_admin.

When dealing with these, it would be useful to have a button to put the request back in the state it was before that status was reported. This might involve resetting "Awaiting description" as well as "Described state".

Obviously we can do it by hand but it's a bit of a pain to dig the right status out of the history.

**Comment by garethrees** [comment]
Closing in favour of duplicate https://github.com/mysociety/alaveteli/issues/1773 as it's more developed (edit: now at https://github.com/mysociety/alaveteli/issues/8230).
